mozilla-mobile/mozilla-vpn-client

android/AndroidManifest.xml, android/src/com/mozilla/vpn/VPNWebView.java, src/command.cpp, src/commands/commandui.cpp, src/mozillavpn.cpp, src/mozillavpn.h, src/networkmanager.cpp, src/networkmanager.h, src/networkrequest.cpp, src/platforms/android/androidauthenticationlistener.cpp, src/platforms/android/androidauthenticationlistener.h, src/platforms/android/androidauthenticationview.qml, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h, src/platforms/android/androidwebview.cpp, src/platforms/android/androidwebview.h, src/qml.qrc, src/src.pro, src/systemtrayhandler.cpp, src/tasks/authenticate/authenticationlistener.cpp, src/tasks/authenticate/authenticationlistener.h, src/tasks/authenticate/taskauthenticate.cpp, src/ui/components/VPNMainImage.qml, src/ui/main.qml
We cannot use WebView because it doesn't allow localStorage. See: https://bugreports.qt.io/browse/QTBUG-75723
So I created an AndroidWebView to do something similar. It works. Give me feedback.
=> Authentication into a webview for android

src/ui/components/VPNToggle.qml
Add tooltip to toggle and improve accessible name. - Fix #135
=> Fix #135 - Improve toggle a11y

src/ui/views/ViewOnboarding.qml
=> Fix onboarding link position

android/src/com/mozilla/vpn/VPNServiceBinder.kt, src/platforms/android/androidcontroller.cpp
=> Match Mac/Linux ForSwitch behaviour

README.md, scripts/android_package.sh
=> Add Release Conf to  android_package.sh

src/qml.qrc, src/ui/components/VPNLoader.qml, src/ui/states/StateAuthenticating.qml, src/ui/states/StateSubscriptionValidation.qml
Adds VPNLoader {} and uses it for the sign in validation and subscription confirmation states.
Placeholder pending UX decisions requested in #302
=> Add VPNLoader.qml

android/AndroidManifest.xml, android/src/com/mozilla/vpn/BootReceiver.kt, android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNServiceBinder.kt, src/commands/commandui.cpp, src/mozillavpn.cpp, src/platforms/android/androidcontroller.cpp, src/platforms/android/androidcontroller.h, src/platforms/android/androidstartatbootwatcher.cpp, src/platforms/android/androidstartatbootwatcher.h, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h, src/src.pro
reopening the PR. See the previous comments here: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/240
=> Android on boot

.github/l10n/check_l10n_issues.py, .github/l10n/exceptions.json, .github/workflows/l10n_lint.yaml
What the script does is exporting strings to .ts, then:
- Check for misused character, i.e. apostrophes, quotes, ellipsis
- Check for missing comments when string has variables
- Check for empty strings
It support a list of exceptions per category via JSON file.
=> Add GitHub action to check pull requests for l10n issues

.clang-format-ignore, .github/workflows/l10n_lint.yaml
=> Add clang-format action

src/ui/components/VPNConnectionInfo.qml
=> Disable the animation in the chart - closes #269

src/mozillavpn.cpp, src/platforms/android/androiddatamigration.cpp, src/platforms/android/androiddatamigration.h, src/platforms/android/androidsharedprefs.cpp, src/platforms/android/androidsharedprefs.h, src/settingsholder.cpp, src/settingsholder.h, src/src.pro
Adds the Code to upgrade Users from 1.3 to 2.0. 
Closes #291
=> Add Android Migration 

src/ui/components/VPNConnectionInfo.qml, src/ui/components/VPNRemoveDevicePopup.qml
=> Remove Accessible properties from Popup types.

android/build.gradle, android/src/com/mozilla/vpn/VPNWebView.java
=> Add Google Play Referrer to the URI

src/ui/components/VPNLoader.qml
=> Remove "and try again" from authenticating screen.

src/mozillavpn.cpp, src/mozillavpn.h, src/qml.qrc, src/ui/components/VPNAboutUs.qml, src/ui/components/VPNGreyLink.qml, src/ui/components/VPNLinkButton.qml, src/ui/themes/themes.js, src/ui/views/ViewSubscriptionNeeded.qml
- Remove "No one can track you" and reorder feature list
- Add Privacy Notice and Terms of Service links 
- Change "Privacy Policy" to "Privacy Notice" everywhere
Closes #353, #336
=> Subscription view updates

.github/workflows/linters.yaml, .github/workflows/test_coverage.yaml
Just in time for the release of QT 6.
Also renaming the linter workflow, since it does more than just l10n linting.
=> Update automation to QT 5.15.2

src/ui/views/ViewUpdate.qml
In case of the required update stackview was undefinded
fixes #361
=> Remove stackview.pop on requiredUpdate

src/settingsholder.cpp, src/settingsholder.h
=>  Give Setting VPN_DISABLED_APPS a default value

src/ui/components/VPNServerCountry.qml, src/ui/views/ViewServers.qml
Incremental server list improvements: 
- Fixes some overlapping items when country list items are opened and closed
- Adds footer space to the bottom of the country list so that the last list item doesn't get stuck underneath the bottom bar. We still have some work to do around how to scroll when the last list item is opened or when a list item is opened and the entire sub-list isn't entirely visible. 
When the last list item is expanded:
=> Server selection improvements

.gitmodules, android/build.gradle, android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNServiceBinder.kt, android/src/com/mozilla/vpn/VPNTunnel.kt
=> Update Wireguard lib && remove guardian git dep

src/ui/states/StateSubscriptionValidation.qml
=> Update subscription validation loading string

scripts/ppa_script.sh
This is to support builds being produced by the VPN team, but signed/uploaded by RelEng.
=> add support for skipping sign and uploading to ppa script

README.md
https://wiki.qt.io/Building_Qt_5_from_Git#Linux.2FX11
=> Fix qt5 build instructions

android/src/com/mozilla/vpn/PackageManagerHelper.java
Lets not make a parse failure crash the app :)
=> Android Fix Chrome-Version Parsing

android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/src/com/mozilla/vpn/PackageManagerHelper.java
Enables desugaring to make sure java8 features are supported on android versions <8.0
Closes #414
=> Android Support Deshugaring

src/ui/settings/ViewAppPermissions.qml
Some are quite confusing, only realized how they were used after looking at the screenshot in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/397
Please add comments as much as possible ;-)
=> Add comments to strings for App permissions

android/AndroidManifest.xml, android/src/com/mozilla/vpn/PackageManagerHelper.java
=> Add a SystemApp-Allowlist and AppQueryPermissions

android/src/com/mozilla/vpn/PackageManagerHelper.java
As @ValentinaPC noted, the Google Assistant and Location History was missing. 
Closes #416
=> Add Missing SystemApps to Allow-List

src/command.cpp, src/commands/commanddevice.cpp, src/commands/commandlogin.cpp, src/commands/commandlogout.cpp, src/commands/commandstatus.cpp, src/controller.cpp, src/models/device.cpp, src/models/device.h, src/models/devicemodel.cpp, src/models/devicemodel.h, src/models/keys.cpp, src/models/keys.h, src/mozillavpn.cpp, src/platforms/windows/windowsdatamigration.cpp, src/settingsholder.cpp, src/settingsholder.h, src/tasks/removedevice/taskremovedevice.cpp, src/tasks/removedevice/taskremovedevice.h, tests/unit/testmodels.cpp
Let's use the public key to identify the current device instead of the name,
=> Public key to identify the current device instead of the name

README.md, src/src.pro
Use env variables everywhere in src.pro and update README
=> Use env variables everywhere in src.pro

src/ui/settings/ViewAppPermissions.qml
=> Wrap app permission subtitle

.github/workflows/macos-build.yaml
The result of this action is a non-signed production/staging build.
=> MacOS builds from github actions

android/build.gradle, scripts/android_package.sh, version.pri
=> let Gradle use Version.pri for Android Version

src/ui/components/VPNCheckBox.qml
=> Restrict IPv6 toggling via Voice Control when VPN is on.

android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNTunnel.kt
Revert the Changes made in #440 - Lets revert this for now, as it's causing the crash - I need a bit more time to debug this properly x)
=> Backout Changes made in #440

src/mozillavpn.cpp, src/mozillavpn.h, src/ui/components/VPNAboutUs.qml
"License" is new so this will require a string refresh before building.
=> Add License link to About Us.

.gitignore
My editor is exploding otherwise after a compile. 🙈
=> Add windows related files to gitignore

src/ui/views/ViewDevices.qml
=> Fix DeviceList warnings/errors

src/ui/components/VPNConnectionStability.qml, src/ui/components/VPNControllerView.qml
=>   Fix disappearing text (#499)

android/src/com/mozilla/vpn/BootReceiver.kt, android/src/com/mozilla/vpn/NotificationUtil.kt, android/src/com/mozilla/vpn/VPNPermissionHelper.kt, android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNServiceBinder.kt, android/src/com/mozilla/vpn/VPNTunnel.kt
If we wanna add ktlint in the ci step, we also might want to clear up old errors.
and welp... ktlint had a lot to fix here 🙈
=> Fix formatting with ktlint

src/platforms/android/androidcontroller.cpp
=> Better idle notification text

src/update/versionapi.cpp
we're currently showing "update-recommended" every time
=> only recommend update if needed

.github/workflows/import_lang.yaml
We've been quite a few commits behind :( - This adds a ci action to bump i18n submodule every workday if something changed.
=> Auto lang update

src/ui/settings/ViewLanguage.qml
- Selected language is centered on view load
- Scrollbar is always visible
- Arrow navigation through language list is enabled
- Last focused position in list is remembered when tabbing between list and the back button
=> Fix #575  and improve language list behavior 

src/errorhandler.h, src/mozillavpn.cpp, src/mozillavpn.h, src/platforms/android/androidutils.cpp, src/platforms/android/androidwebview.cpp, src/platforms/ios/iosauthenticationlistener.mm, src/tasks/authenticate/taskauthenticate.cpp, src/ui/components/VPNAlert.qml, src/ui/components/VPNSystemAlert.qml, tests/unit/mocmozillavpn.cpp
Let's have remote and backend (not background) errors. We can try to recover from the backend error only.
=> Introduce RemoteServiceError

src/qml.qrc, src/ui/components/VPNDevicesListHeader.qml, src/ui/components/VPNRemoveDevicePopup.qml, src/ui/components/VPNVerticalSpacer.qml, src/ui/components/VPNWasmAlerts.qml, src/ui/components/VPNWasmHeader.qml, src/ui/components/VPNWasmMenu.qml, src/ui/components/VPNWasmMenuButton.qml, src/ui/main.qml, src/ui/themes/themes.js, src/ui/views/ViewDevices.qml, src/ui/views/ViewSubscriptionNeeded.qml, wasm/main.css
=> Wasm viewer menu updates ... 

scripts/android_package.sh, scripts/apple_compile.sh, src/mozillavpn.h, src/src.pro, src/ui/components/VPNAboutUs.qml
This adds info field for the BuildID if it's available :) 
closes #511
=> Add BuildID

src/platforms/linux/daemon/helper.sh, src/src.pro, src/wgquickprocess.cpp
https://git.zx2c4.com/wireguard-tools/tree/src/wg-quick/linux.bash
=> Use our own copy of wg-quick

android/src/com/mozilla/vpn/VPNServiceBinder.kt
=> Catch DeadObject Exception

linux/daemon/helper.sh
Naive removal of all the parts that we're not using.
=> Strip down helper.sh

src/ui/views/ViewErrorFullScreen.qml
=> Make get help link in full screen error view blue

src/mozillavpn.cpp, src/mozillavpn.h, src/platforms/ios/iaphandler.h, src/platforms/ios/iaphandler.mm, src/ui/views/ViewSubscriptionNeeded.qml
Fixes the frontend bits of #380
=> Remove "Restore purchases" UI from ViewSubscriptionNeeded.qml

version.pri
2.0.4 is out, and the new builds should be 05 then :)
=> Bump version to 2.0.5

src/ui/components/VPNPanel.qml
=> Fix #688 - Fix restore icon size

src/ui/components/VPNMenu.qml
=> Fix #720 - Prevent mouse events from passing through menu

src/localizer.cpp, src/localizer.h, src/qml.qrc, src/settingsholder.cpp, src/settingsholder.h, src/ui/components/VPNSettingsToggle.qml, src/ui/settings/ViewLanguage.qml, tests/unit/testlocalizer.cpp, tests/unit/testlocalizer.h
- Adds VPNSettingsToggle
- Adds "Use system language" pref
When system language pref is enabled:
- The list of languages is scrollable, but disabled. 
- The current language is not marked as selected
- The list does not scroll to the current language when ViewLanguage is opened
Enabled:
Disabled:
=> Fix 694 - 

src/ui/components/VPNDevicesListHeader.qml
Closes #752 
Followed up with @jess-cook03 via Slack and we decided to also change the wording in the first sentence from 'your limit' to the 'the device limit' as well.
=> Update remove a device blurb

src/ui/main.qml, src/ui/themes/themes.js
=> Fix some of scaling/resolution change issues on Windows

version.pri
I'ts certainly not 2.1 anymore :)
=> Bump Current Main Branch version to 2.3

android/src/org/mozilla/firefox/vpn/VPNLogger.kt, android/src/org/mozilla/firefox/vpn/VPNService.kt, android/src/org/mozilla/firefox/vpn/VPNServiceBinder.kt, android/src/org/mozilla/firefox/vpn/VPNTunnel.kt, src/controller.cpp, src/featurelist.cpp
2 changes here:
- More logs! And sensitive ones for debug builds. Otherwise i would have not found out what the connection issue was. 
- Also disable CP for android, and double check FeatureList&&Pref like we do with LNA
Closes #860
=> Android: Disable CaptivePortal and Check FeatureList for ipAllowList

android/src/org/mozilla/firefox/vpn/VPNService.kt, src/platforms/android/androidappimageprovider.cpp
The classname was wrong - this caused a crash :( ﻿
=> Fix JNI Classname

.github/workflows/issues.yml
Puts new incoming issues to the "mozilla product vpn"board
Example issue  https://github.com/strseb/mozilla-vpn-client/issues/2
=> CI: Auto put new issues on our board

src/ui/components/VPNFlickable.qml
This reduces the scroll velocity on Windows.
Closes #776
=> Improve scrolling on Windows 

docs/releasenotes/v2.1.0.md, docs/releasenotes/v2.2.0.md
Can you please take a look at these 2 release notes? If there is anything to change/add/remove, let's do it.
=> Release notes for v2.2.0 and v2.1.0 - closes #891

extension/app/app.pro, extension/app/handler.cpp, extension/app/handler.h, extension/app/main.cpp, extension/app/manifests/windows/manifest.json, macos/pkg/scripts/postinstall, src/src.pro, windows/installer/MozillaVPN.wxs
=> Windows native-extension

src/models/device.cpp, src/models/device.h, src/mozillavpn.cpp, src/settingsholder.cpp, src/settingsholder.h
So we know wich settings have been set and what device this logs come from :) ﻿
=> Append Reports From Settings & Device when exporting the logs

src/ui/components/VPNAlert.qml
=> Fix floating alert X

src/ui/settings/ViewSettingsMenu.qml
=> Fix get help link in settings

src/ui/views/ViewMain.qml
With any luck this will fix the same issue on Linux. 
Fixes #1038 
Before:
After:
=> Fix scrollbar in main view on Windows

.github/workflows/functional_tests.yaml, scripts/test_function.sh
Experiment: instead of running all tests in one loop and generate a huge logfile (imho), 
maybe we can have a job automatically for every test so it's faster to spot what is failing and why.
=> Experiment: function Tests Matrix-Run 

android/src/org/mozilla/firefox/vpn/VPNService.kt
=> Fix Switching on Android

src/src.pro
lets use all cores of the system instead of just one :)
=> Make windows builds super fast

src/tasks/authenticate/taskauthenticate.cpp
Bug fix necessary to correctly detect clients on auth.
=> Append userAgent to auth network request.

android/src/org/mozilla/firefox/vpn/qt/PackageManagerHelper.java
It's probably not feasable to have a manual allowlist aaaand we can avoid "show system apps" ui with a bit of filtering. 
So my proposal: show a system app IF:
-> They use internet
-> And have an activity (so they are able to have a launching icon on the homescreen)
-> They had an update ( this would imply they are published on any appstore/ device internal updating serivce)
Closes #994
=> Android: Remove System-Apps Allowlist and do better filtering

src/systemtrayhandler.cpp
This is just a temporary fix until we can allocate more time towards this.
=> Dont use systemtrayhandler for mobile

src/platforms/macos/macosmenubar.cpp
=> keeping VPN active after cmd+w

README.md
...totally not copied from mozilla-mobile/fenix
also closes #1157
=> Add helpful Links to Readme

android/src/org/mozilla/firefox/vpn/VPNService.kt
.If the Service has a cold start (e.g. app off and user enabled always-on) and is booted with onStartCommand, we did not load wg-go thus crash.
=> Same init path for all service start methods

src/models/serverdata.cpp, src/models/serverdata.h, src/notificationhandler.cpp, src/notificationhandler.h
I haven't seen you assigning the bug to yourself! Sorry I already have a patch...
=> Localize notifications - fixes #1184

src/ui/settings/ViewNetworkSettings.qml, src/ui/settings/ViewNotifications.qml, src/ui/settings/ViewPrivacySecurity.qml
=> Fix #1138 - Overscrolling in Notifications and Network Settings views

src/ui/states/StateTelemetryPolicy.qml
=> Fix #1141 - Update string per request from legal

src/ui/components/VPNDeviceListItem.qml, src/ui/views/ViewDevices.qml
=> Fix device list recursive rearranges

src/models/devicemodel.h, src/mozillavpn.cpp, src/mozillavpn.h, src/networkrequest.cpp, src/platforms/ios/iaphandler.h, src/platforms/ios/iaphandler.mm, src/platforms/ios/taskiosproducts.cpp, src/qml.qrc, src/ui/components/VPNCallout.qml, src/ui/components/VPNSubscriptionOption.qml, src/ui/themes/themes.js, src/ui/views/ViewSubscriptionNeeded.qml
The UI is... simply not done! What this PR does is the following:
- fetch the list of products from the guardian-website
- expose the products via a IAP model (sorted by type)
- trigger the subscription using the product ID
I haven't spent time on the UI because the UX has not been defined yet.
=> Virtual price for IAP

.github/workflows/functional_tests.yaml, scripts/inspector.py, scripts/test_function.sh, src/inspector/inspectorwebsocketconnection.cpp, src/mozillavpn.cpp, src/mozillavpn.h, src/ui/components/VPNStackView.qml, src/ui/main.qml, src/ui/settings/ViewNetworkSettings.qml, src/ui/settings/ViewNotifications.qml, tests/functional/helper.js, tests/functional/localizeServers.js, tests/functional/screenCapture.js, tests/functional/testAuthentication.js, tests/functional/testCaptivePortal.js, tests/functional/testConnection.js, tests/functional/testDevices.js, tests/functional/testHeartbeat.js, tests/functional/testServers.js, tests/functional/testSettings.js, tests/functional/testUnsecuredNetworkAlert.js
This is kind of a grab bag of things that have bugged me while trying to diagnose issues in the functional tests, changes include:
- Close selenium webdriver after authentication.
- Expose QML/C++ singletons via inspector.
- Add currentView property to the VPN singleton.
- Fix potential race during authentication/reset_devices.
- Upload logs of failed tests as artifacts.
=> More testing fixes

.github/workflows/linux.yaml, linux/debian/mozillavpn.service, linux/mozillavpn.service, linux/mozillavpn.spec, scripts/linux_script.sh, src/src.pro
This is a test to see if we can build functioning RPM packages from a github workflow.
=> RPM packaging in github CI

src/constants.h, src/platforms/ios/iaphandler.h, src/platforms/ios/iaphandler.mm, src/ui/components/VPNSubscriptionOption.qml
This path does also the following:
- compute the price (total and monthly)
- one single registration operation of all the products
=> Expose the montly payment and the savings

src/ui/settings/ViewLanguage.qml
=> Enable languages search bar when !useSystemLanguageEnabled

src/serveri18n.cpp
=> Apply PR 1278 on main

android/src/org/mozilla/firefox/vpn/VPNService.kt
This is not in main yet. 🙈 
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1171
=> Android: apply always-on crash fix on main

src/controller.cpp, src/controller.h
=> Use the start time of the connection instead of a timer to show time

src/ui/components/VPNFeedbackRadioDelegate.qml, src/ui/settings/ViewGiveFeedback.qml
=> Correct layout issues on the app rating view

src/ui/settings/ViewGiveFeedback.qml
Before landing this, I want to be sure it's OK for the localization team to have this extra string so late in the process.
@flodolo feel free to say "No, we cannot land this PR".
=> Extra string for the "good" rating in app-feedback-form

.gitignore, scripts/importLanguages.py
The menu is localized at the following app restart. The QT cocoa plugin seems to ignore any retranslation signal.
=> Localize MacOS app menu - closes #1087

.github/l10n/check_l10n_issues.py, .github/workflows/linters.yaml, .github/workflows/test_coverage.yaml, scripts/import_macos_pkg_resources.py, src/src.pro
This script is now broken because of the macos menu localization
=> Fix the MacOS resource generation

src/ui/settings/ViewGiveFeedback.qml
=> Move done button down

src/platforms/windows/windowsapplistprovider.cpp, src/platforms/windows/windowsapplistprovider.h, src/settingsholder.cpp, src/settingsholder.h
=> Windows: Add Supporting Code for Missing Apps

src/platforms/android/androidappimageprovider.cpp, src/ui/components/VPNCheckBoxRow.qml
Already landed in release 2.4
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/1375
=> CherryPick PR 1375 onto Main

src/ui/settings/ViewAppPermissions.qml
=> Fix scrolling in App Permissions

src/ui/settings/ViewLanguage.qml
=> Fix ViewLanguage scrolling on Windows - #1389

version.pri
Let's increase the version to 2.5.0 for the `main`.
=> Version bump: 2.5.0

src/ui/components/VPNCheckBox.qml
Closes #1397
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-783)
=> Fix #1397 - Flickering checkboxes

src/loghandler.cpp
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-784)
=> Support `info` in MOZVPN_LEVEL

src/ipaddressrange.cpp, src/ipaddressrange.h, src/platforms/windows/daemon/windowsfirewall.cpp
#closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1409
=> fix lna windows

src/ipaddressrange.cpp, src/ipaddressrange.h, src/platforms/windows/daemon/windowsfirewall.cpp
Cherrypick of #1412
Closes #1409
=> Cherrypick LNA Fix to Main

src/platforms/linux/linuxapplistprovider.cpp
=> Cherry pick Flatpak application fix to 2.4.0

src/pingsender.cpp, src/pingsender.h, src/platforms/linux/linuxpingsender.cpp, src/platforms/linux/linuxpingsender.h
Closes: #1422
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-803)
=> Add fallback to "ping" command if an ICMP socket failed.

windows/installer/README.md
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-812)
=> Fix the Windows Installer README link - closes #1427

scripts/ppa_script.sh
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-815)
=> Go dependencies in linux PPA script

.github/workflows/windows-build.yaml
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-827)
=> Add missing deps (#1447)

windows/installer/MozillaVPN_prod.wxs, windows/installer/build_prod.cmd
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-829)
=> Separate MozillaVPN.wxs file for production

src/authenticationinapp/authenticationinapp.h, src/authenticationinapp/authenticationinapplistener.cpp, src/authenticationinapp/authenticationinapplistener.h, src/authenticationlistener.cpp, src/authenticationlistener.h, src/commands/commandlogin.cpp, src/featurelist.cpp, src/featurelist.h, src/platforms/android/androidauthenticationlistener.cpp, src/platforms/android/androidauthenticationlistener.h, src/platforms/ios/iosauthenticationlistener.h, src/platforms/ios/iosauthenticationlistener.mm, src/platforms/wasm/wasmauthenticationlistener.cpp, src/platforms/wasm/wasmauthenticationlistener.h, src/qml.qrc, src/src.pro, src/tasks/authenticate/desktopauthenticationlistener.cpp, src/tasks/authenticate/desktopauthenticationlistener.h, src/tasks/authenticate/taskauthenticate.cpp, src/ui/authenticationInApp/ViewAuthenticationFallbackInBrowser.qml, src/ui/authenticationInApp/ViewAuthenticationInApp.qml
This is needed for desktop (windows and mac) where we want to support only the sign-in but not the sign-out.
=> Auhentication in-app with fallback in browser

src/platforms/windows/daemon/windowsfirewall.cpp, src/platforms/windows/daemon/windowsfirewall.h, src/platforms/windows/windowsapplistprovider.cpp, src/platforms/windows/windowscommons.cpp, src/platforms/windows/windowscommons.h
=> Exclude ourselves from Split-Tunnel on windows

src/ui/components/VPNAnimatedRings.qml, src/ui/components/VPNControllerView.qml, src/ui/components/VPNMainImage.qml, src/ui/components/forms/VPNComboBox.qml, src/ui/views/ViewMain.qml
=> Fix recursive drop shadows and gradients

src/ui/components/VPNServerCountry.qml, src/ui/views/ViewMain.qml, src/ui/views/ViewServers.qml, translations/strings.yaml
This adds a search to the server list and makes it filterable by country name and code.
Resolves #1358
=> Add search bar to server list

src/qml.qrc, src/ui/components/VPNTabNavigation.qml
This adds the VPNTabNavigation.qml component which we'll need for the new DNS and Mult-Hop UI. 
Closes #1473
=> Add VPNTabNavigation.qml

src/authenticationinapp/authenticationinapplistener.cpp
This has been discussed with the FxA team. There are no other authentication/verification methods.
=> Remove a TODO comment

.github/workflows/test_coverage.yaml, mozillavpn.pro, scripts/test_coverage.sh, src/authenticationinapp/authenticationinapp.cpp, src/authenticationinapp/authenticationinapp.h, src/authenticationinapp/authenticationinapplistener.cpp, src/authenticationinapp/authenticationinapplistener.h, src/commands/commandlogin.cpp, src/networkrequest.cpp, src/networkrequest.h, tests/auth/auth.pro, tests/auth/main.cpp, tests/auth/testpasswordvalidation.cpp, tests/auth/testsignupandin.cpp, tests/auth/testsignupandin.h
This is the last bit to have a full test coverage.
=> TOTP tests - authentication-in-app

linux/mozillavpn.spec, scripts/linux_script.sh, src/src.pro
This reverts commit 738cc4d94e8fda1ee5ba35ede22f7c8b02a60afe
The reason I want to revert this PR is that, it breaks the CI. There are issues with glean_parser, not being installed when needed.
=> Revert "Preparing the project for a Fedora release. (#1555)"

translations/strings.yaml
This is the "excellent" string needed per the latest spec
=> Add "Excellent" string

src/ui/components/VPNConnectionInfo.qml, src/ui/components/VPNIPAddress.qml
- Dynamically resize IP address text size if it has too many characters to fit in graph without wrapping.
- Fix vertical centering of graph lines
=> Fix 1195 - Connection info layout issues

translations/strings.yaml
I rewrote the file to hopefully make more sense. I will be online early so we can chat live if needed.
=> Updated 2.5 strings.yaml

src/models/server.cpp
The `Server::choosePort()` method produces a highly non-uniform distribution of ports which is due to multiple stages of the randomization. For example, if `m_portRanges` contained `[53-53], [54-65535]` then it would select port 53 half of the time. To make port selection a little more uniform, we calculate the total number of ports available, call `random()` only once, and then iterate over the `m_portRanges` to produce the desired port number.
The motivation for finding this issue is that we were disproportionately selecting port 53, which is blocked by Mullvad, leading to frequent breakage of multihop connections. Port 53 would be fine for the entry node on a multihop connection, but for any other hop this would get blocked.
=> Improve uniformity of port selection and avoid 53/DNS

src/platforms/android/androidiaphandler.cpp
=> Mark productsRegstrationCompleted when there are no skus too.

src/ui/views/ViewContactUs.qml
=> Fix #1647 - Layout issues in support form

src/ui/components/VPNServerList.qml
=> Wrap server list search bar error messages

src/ui/components/VPNRecentConnections.qml, src/ui/components/VPNServerCountry.qml, src/ui/components/VPNServerList.qml
=> Ensure recent connections, tab navigation, menu navigation, and server list items are accessible by keyboard.

src/ui/components/VPNStackView.qml, src/ui/views/ViewMain.qml
=> Fix ViewMain layout on Linux - (maybe)

src/platforms/android/androidiaphandler.cpp, src/ui/components/VPNRemoveDevicePopup.qml, src/ui/themes/themes.js
This fixes the layout issues mentioned in #1681.
=> Fix remove device popup layout

src/apppermission.cpp
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1631
=> Do not fire missingappAdded notification if the app was aleady added

src/ui/components/VPNAlert.qml, src/ui/components/VPNAlerts.qml, src/ui/components/VPNSystemAlert.qml, src/ui/components/VPNWasmAlerts.qml, src/ui/themes/themes.js
- Adds focus indicators
- Fixes wasm viewer alert list
- #1642
- Adds unicode whitespace between bits of alert text
- #1455
- Fixes alert related console errors/warnings
-  #1606 
- Fixes logout alert flicker
- #1630
=> Fix alerts/banners and wasm alert viewer

src/localizer.cpp
We also need a tool to detect when a similar issue happens again.
=> es_CL must be translated differently then what QT says

src/ui/settings/ViewSettingsMenu.qml, src/ui/views/ViewSettings.qml
The issue here is related to the binding JS properties. See: https://doc.qt.io/qt-5/qtqml-syntax-propertybinding.html
I have covered some of the issues. There are others, probably.
=> Fix a couple of language binding issues - closes #1770

src/ui/components/VPNFeatureTour.qml, src/ui/components/VPNPopup.qml, src/ui/settings/ViewSettingsMenu.qml, src/ui/views/ViewSettings.qml
Fixes the binding loop and layout issues (see screenshot) @lesleyjanenorton discovered and fixed for Android.
=> FeatureTour binding loop

src/ui/views/ViewContactUs.qml
This PR fixes two issues.
1. for authenticated users we did not send an email
2. from the thank you view we did not get back to the settings page
=> Fix minor support flow issues

src/ui/components/VPNAlerts.qml, src/ui/settings/ViewNotifications.qml
Fixes #1756 and a few `undefined` QML warnings.
=> Fix: Edit notification in notifications menu

src/ui/components/VPNViewDNSSettings.qml
=> Fix: Binding loop for custom DNS text input

scripts/generate_strings.py, src/apppermission.cpp, src/l18nstringsimpl.cpp, src/models/feature.cpp, src/models/supportcategorymodel.cpp, src/ui/views/ViewContactUs.qml, translations/strings.yaml
tr() produces warning messages when running `lupdate`. Let's call L18nString::tr() -> t().
Plus this PR removes a few other comments producing warning messages in a qml file.
=> Qml strings

src/models/device.cpp, src/models/device.h, src/models/devicemodel.cpp, src/models/devicemodel.h, src/mozillavpn.cpp, src/mozillavpn.h, tests/unit/testmodels.cpp
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-822)
=> Unique device ID to remove devices - closes #1360

src/featurelist.cpp, src/features/featureunauthsupport.h, src/inspector/inspectorwebsocketconnection.cpp, src/models/feature.cpp, src/models/feature.h, tests/unit/testfeature.cpp, tests/unit/testfeature.h, tests/unit/unit.pro
Right now we have the dev-menu. Let's deprecate the inspector step by step.
We need to change the guardian-website too.
=> Let's use the devModeFeatureFlags to enable/disable features

android/src/org/mozilla/firefox/vpn/qt/VPNUtils.kt, src/models/device.cpp, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1901
=> Implement uniqueDeviceId for android

src/models/feature.cpp
Very spammy but i doubt it has any real value - how about we remove it :)
=> Remove FeatureList Logs with no value

src/ui/views/ViewContactUs.qml
The way we can open the unauth support screen is on the "Get started" screen which is shown if we are in the "StateInitialize".
=> Fix the unauth support screen

src/ui/settings/ViewGiveFeedback.qml
The buttons on the "Leave review" screen were too high. 
I used a similar way to do this we have on the "Get started" screen.
=> Push buttons down on "Leave review" screen

src/ui/components/forms/VPNTextArea.qml
=> Do not delete input characters automatically when limit is exceeded

docs/releasenotes/v2.6.md
=> Add changelog for v2.6.0

src/connectionhealth.cpp, src/pinghelper.cpp
=> Temporary fix to reduce the "unstability/connectivity" alert for 2.6

.gitignore, src/mozillavpn.cpp
I don't know if this was new, but the code was not handling VPNDependentErrors correctly.  It was treating almost everything as "Connection Failed"
Also added .pdb files to gitignore, as those don't belong in the repo.
=> VPN-890 - Fixed Error Display Logic - 2.6 critical.

src/ui/settings/ViewAppPermissions.qml, src/ui/states/StateSubscriptionBlocked.qml
=> Fix string casing in QML files

src/ui/states/StateTelemetryPolicy.qml, translations/strings.yaml
This will be included in VPN v2.6.1
=> Update the strings for the telementry policy view - closes VPN-1114

src/ui/settings/ViewPrivacySecurity.qml, src/ui/settings/ViewSettingsMenu.qml, translations/strings.yaml
=> Add settings strings - #1684

scripts/Qt5_static_compile.bat
This is for local builds only.  Will not help the missing dependency we currently have in main builds.
=> Added sqllite to Qt dependencies

android/src/org/mozilla/firefox/vpn/VPNService.kt, src/platforms/android/androidcontroller.cpp
Fixes #2172 so the connection info graph shows the correct values on Android.
=> Connection Info Android

scripts/Qt5_static_compile.bat
Added sqlite switch.  Changed from debug-and-release to release.
=> Add sqlite driver to windows build

taskcluster/ci/lint/kind.yml
We are still getting LLVM OOM errors.
=> Reduce clang parallelization again

scripts/windows_compile.bat
Downloads and stages crashpad in our 3rdparty folder.
=> Fetch crashpad build in windows compile script

src/ui/states/StateTelemetryPolicy.qml
=> Fix: Telemetry screen layout

src/ui/components/VPNGraphLegendMarker.qml, translations/strings.yaml
This PR changes the units for the connection speeds that are displayed to the users from `bytes` to `bits`.
**Screenshots**
| Download | Upload |
| --- | --- |
| <img width="810" alt="connection-speed-down" src="https://user-images.githubusercontent.com/13835474/144266085-0c138d17-98dc-46fb-a0e3-cf0a7d8d5de4.png"> | <img width="821" alt="connection-speed-up" src="https://user-images.githubusercontent.com/13835474/144266158-76e262b1-9459-4b20-bc90-3e960eb04da5.png"> |
Resolves #1104
=> Convert connection speed from bytes to bits

src/ui/settings/ViewPrivacySecurity.qml, src/ui/settings/ViewSettingsMenu.qml, translations/strings.yaml
Addresses comments attached to the now closed #2271
=> Update settings strings

scripts/apple_compile.sh
Explanation in [VPN-1437](https://mozilla-hub.atlassian.net/browse/VPN-1437)
=> Streamline qt tools for apple

glean/glean.h, mozillavpn.pro, nebula/nebula.h, scripts/android_package.sh, src/main.cpp, tests/qml/main.cpp
And the user of CONFIG+=ordered - not needed in the `.pri` projects
=> Removed the use of the Q_INIT_RESOURCE macro

scripts/android_package.sh, taskcluster/ci/build/kind.yml, taskcluster/ci/docker-image/kind.yml, taskcluster/docker/android-build/Dockerfile, taskcluster/scripts/android_build_debug.sh
As first step. Lets move the android-debug (qt5) job to taskcluster
=> Add Android/debug to tc

CODEOWNERS
This will automatically request a review from @flodolo anytime changes are pushed to `strings.yaml`.
=> Add @flodolo as strings.yaml code owner

.github/workflows/android_qt6.yaml, .gitignore, android/AndroidManifestQt6.xml, android/build.gradle, android/qt5/org/mozilla/firefox/vpn/compat/CompatVPNActivity.java, android/qt5/org/mozilla/firefox/vpn/compat/CompatVPNApplication.java, android/qt6/org/mozilla/firefox/vpn/compat/CompatVPNActivity.java, android/qt6/org/mozilla/firefox/vpn/compat/CompatVPNApplication.java, android/res/values/libs.xml, android/src/org/mozilla/firefox/vpn/qt/VPNActivity.java, android/src/org/mozilla/firefox/vpn/qt/VPNApplication.java, android/tunnel/CMakeLists.txt, android/tunnel/libwg-go/Makefile, scripts/android_package.sh, src/adjust/adjusthandler.cpp, src/features/featuresharelogs.h, src/platforms/android/androidappimageprovider.cpp, src/platforms/android/androidappimageprovider.h, src/platforms/android/androidapplistprovider.cpp, src/platforms/android/androidauthenticationlistener.cpp, src/platforms/android/androidcontroller.cpp, src/platforms/android/androidcontroller.h, src/platforms/android/androidiaphandler.cpp, src/platforms/android/androidjnicompat.h, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h, src/platforms/android/androidvpnactivity.cpp, src/platforms/android/androidwebview.cpp, src/platforms/android/androidwebview.h, src/src.pro
This is a replicate of #2387 - As CI was failing- since it was a pr from a fork. So pulled it in this branch :)
=> Android: Dual Compile for Qt6 and Qt5 

scripts/android_package.sh, src/src.pro
=> Enable Qt Quick Compiler for all platforms

scripts/android_package.sh, src/src.pro
Reverts mozilla-mobile/mozilla-vpn-client#2490
See discussion in #2487
=> Revert "Enable Qt Quick Compiler for all platforms"

src/commands/commandui.cpp, src/theme.cpp, src/theme.h, tests/qml/helper.cpp, tests/qml/helper.h, tests/qml/qml.pro, tests/unit/testthemes.cpp
=> Load themes when VPNTheme is exposed to use the right QQmlEngine object

src/mozillavpn.cpp, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h
Now apparently the jni.h init did not work and crashes. 
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2618
=> Fix AndroidGleanInit

nebula/ui/components/VPNSignOut.qml, src/ui/main.qml, src/ui/views/ViewErrorFullScreen.qml
=> Fix restore purchase error screens

nebula/ui/components/VPNHeaderLink.qml
=> Fix header link width for Android Qt 6

src/controller.cpp, src/errorhandler.h, src/mozillavpn.cpp
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2776
=> Handle currentDevice == nullptr on activation

src/constants.h, src/mozillavpn.cpp, src/mozillavpn.h, src/networkrequest.cpp, src/ui/authenticationInApp/ViewAuthenticationSignIn.qml, translations/strings.yaml
- Fixes #2772
- Fixes #2778 
- Adds final content
- Adds 'invalid password' error messaging
- Adds TOS links and blurb (TODO should be component since it's copy/paste from in-app subscription view)
=> Incremental updates to in-app Sign in 

src/localsocketcontroller.cpp
Cherrypick of: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/2812
=> 🍒: Stay in eReady when the Deamon

.gitignore, extension/bridge/Cargo.toml, extension/bridge/src/main.rs, tests/nativemessaging/helper.cpp, tests/nativemessaging/helper.h, tests/nativemessaging/testbridge.cpp
This is a new implementation of mozillavpnnp in rust.
Running the unit-tests for the mozillavpnnp component on windows I found several bugs:
1. the STDIN reading/writing was totally wrong. We were using stdin to synchronize the socket reading; some messages were not received; etc..
2. the TCP handling was wrong too! The connection was sync (blocking all the rest); big windows timeouts
I tried to cleanup the mess and the code was a collection of `#ifdef MVPN_WINDOWS...`. Better to rewrite it.
1. a proper review by rust experts
2. integration with the compilation scripts
=> Bridge in rust

nebula/ui/components/VPNAboutUs.qml, nebula/ui/components/VPNFeatureTourPopup.qml, nebula/ui/components/VPNPopup.qml, nebula/ui/components/VPNServerUnavailablePopup.qml
Small VPNModal.qml refactor to fix close button clickability. Fixes #2711 
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix the close button in VPNModal.qml

nebula/ui/components/VPNButtonBase.qml, nebula/ui/components/VPNServerCountry.qml
Fix #2855 
Restores the scrolling into view of focused buttons/links/clickable things.
=> Fix onFocus scrolling

src/platforms/wasm/wasminspector.cpp
Currently crashes -> https://mozilla-mobile.github.io/mozilla-vpn-client/
=> Fix wasm Crash

.github/workflows/macos-build.yaml, .github/workflows/test_lottie.yaml, .github/workflows/test_qml.yaml, .github/workflows/test_unit.yaml, .github/workflows/wasm.yaml
Removed:
lottie tests mac/linux Qt5
unit test mac/linux Qt5
wasm Qt5
macos Qt5 build
=> Remove some Qt6 CI workflows

src/mozillavpn.cpp, src/mozillavpn.h, src/ui/developerMenu/ViewDeveloperMenu.qml, tests/auth/mocmozillavpn.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp
Crash button added.  Only works in staging and requires 5 clicks so shouldn't be hit accidentally.
=> Add Crash Test to developer options

nebula/ui/components/VPNIconAndLabel.qml, nebula/ui/components/VPNSettingsItem.qml
Fixes #2888, which was caused by me in VPN-1842.
Windows "screencap" taken with phone:
=> Fix vertical button alignment on Windows

src/ui/authenticationInApp/ViewAuthenticationSignUp.qml
=> Cancel auth instead of resetting auth on 'Cancel' click - #2882

glean/metrics.yaml, src/authenticationinapp/authenticationinapp.cpp, src/authenticationinapp/authenticationinapplistener.cpp, src/authenticationinapp/authenticationinapplistener.h, src/mozillavpn.h, src/ui/main.qml
This PR requires a data-review too. But first, can you tell me if you are OK with these events?
=> Glean events for the auth-in-app - fixes VPN-1882

nebula/ui/components/VPNCheckBoxRow.qml, nebula/ui/components/VPNExpandableAppList.qml, src/ui/settings/ViewAppPermissions.qml
Fixes #2965
Text is wrapping again:
=> Fix app permissions layout #2965

nebula/ui/components/VPNRadioDelegate.qml
=> Fix 2681 - Fix random appearance of some language list items

taskcluster/ci/build/android.yml, taskcluster/ci/config.yml, taskcluster/ci/signing/kind.yml, taskcluster/mozillavpn_taskgraph/transforms/build.py, taskcluster/mozillavpn_taskgraph/transforms/multi_dep.py, taskcluster/mozillavpn_taskgraph/transforms/signing.py
Mac build/signing isn't ready yet, this will refactor the signing logic to be more generic, and make it easy to add mac signing (and others) when needed.
=> RELENG-804 - Refactor signing tasks

.github/workflows/android_qt6.yaml, scripts/android/sign.sh
This reverts commit c0dab41757b86e8a70f0f4b9609e8e44e316d470.
=> Reactivate Qt6 android builds

nebula/ui/components/inAppAuth/VPNInAppAuthenticationErrorPopup.qml, translations/strings.yaml
<table>
<td>
</td>
<td>
</td>
</table>
=> Add missing error string

src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml
=> Disable 2FA "Verify" button when code input is empty

src/ui/views/ViewMobileOnboarding.qml
=> Fix animations not playing when navigating back from Get help

nebula/ui/components/VPNConnectionInfoScreen.qml
=> Fix connection info restart button on error view

src/ui/authenticationInApp/ViewAuthenticationUnblockCodeNeeded.qml
=> Add ViewAuthenticationUnblockCodeNeeded.qml UI

nebula/ui/components/VPNFeatureTour.qml
=> Fix What’s new panel translations

nebula/ui/components/VPNControllerView.qml, nebula/ui/components/VPNIconButton.qml
=> Fix settings label when Connection info screen is open

.github/workflows/test_lottie.yaml, .github/workflows/test_qml.yaml, .github/workflows/test_unit.yaml, scripts/linux/utils/commons.sh, scripts/macos/utils/commons.sh, scripts/tests/lottie_tests.sh, scripts/tests/qml_tests.sh, scripts/tests/unit_tests.sh
I cannot include lottie in this PR because grcov crashes with the following error:
```
Error: 0 [ERROR] A panic occurred at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/grcov-0.8.7/src/parser.rs:377: called `Result::unwrap()` on an `Err` value: Error("invalid type: floating point `2507390`, expected u64", line: 1, column: 212345)
```
=> grcov for linux

nebula/ui/components/VPNIconButton.qml
=> Fix VPNIconButton tooltips

src/ui/main.qml, src/ui/views/ViewGetHelp.qml, src/ui/views/ViewMobileOnboarding.qml
This PR removes the safe area for the mobile onboarding on iOS devices.
=> Fix mobile onboarding white space on iOS

.github/workflows/android_qt6.yaml, taskcluster/ci/docker-image/kind.yml, taskcluster/docker/android-qt6-build/Dockerfile
We seem to be using 6.2.3 everywhere else.
=> Update Android Qt version 6.2.1-> 6.2.3

src/platforms/android/androidcontroller.cpp, src/platforms/android/androidvpnactivity.cpp
=> Uplift to 2.8: Do not block UI thread for ipc (#3100)

nebula/ui/themes/themes.js, src/ui/views/ViewMobileOnboarding.qml
Same problem as the transparency issue. We should have our colors in a theme so android does parse them correctly :)
=> Fix mobile onboarding background on android 12

nebula/ui/components/VPNConnectionInfoContent.qml, src/connectionbenchmark/benchmarktaskdownload.cpp, src/connectionbenchmark/connectionbenchmark.cpp, src/connectionbenchmark/connectionbenchmark.h, src/constants.h
In the  last changes, I broke how we compute the speed.
And I also applied 2 extra changes:
- expose bitsPerSec instead of bytesPerSec
- renamed a few variables (ping -> pingLatency, download -> bitsPerSec)
=> Fix the connection-speed value

src/authenticationinapp/authenticationinapp.h, src/ui/authenticationInApp/ViewAuthenticationUnblockCodeNeeded.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml, translations/strings.yaml
This is the fix for the `main` branch. I'm about to submit a special PR for 2.8 because we are in string freeze and we don't want to add new content now.
=> Verification code is a 8-digit string - fixes VPN-2000

.github/pull_request_template.md
created the initial pr template
=> added initial pr template

src/authenticationinapp/authenticationinapp.cpp, src/authenticationinapp/authenticationinapp.h, src/authenticationinapp/authenticationinapplistener.cpp, src/commands/commandlogin.cpp, tests/auth/testsignupandin.cpp, tests/auth/testsignupandin.h, translations/strings.yaml
See https://mozilla-hub.atlassian.net/browse/VPN-2020
=> Remove a non-catchable Fxa error and increase the test-coverage for auth-in-app

windows/installer/MozillaVPN_prod.wxs
Block install on non x86 64 bit platforms and < Win10
Added the 2 Condition statements under Product.  The rest is the clang format.
=> Only install on Win10 or higher, 64bit, x86

.github/workflows/functional_tests.yaml, .github/workflows/linters.yaml, .github/workflows/screencapture.yaml
Use Qt6 for all the github actions
https://mozilla-hub.atlassian.net/browse/VPN-2026
=> Use qt6 for all the github actions

nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml
This PR refactors the password creation tooltip to fix a layout issue on some Android devices.
Fixes #3230 
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
#3230
=> Fix password creation tooltip 

src/ui/main.qml, src/ui/settings/ViewSettingsMenu.qml, src/ui/views/ViewGetHelp.qml, src/ui/views/ViewMain.qml
Move the onContactUsNeeded() slot in the about-us view
VPN-2047
=> Fix the contact-us stackview handling - fixes VPN-2047

nebula/ui/themes/themes.js
Fixes #3255 
<table>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/22355127/163267410-694f3f1f-e247-492f-aa48-74dd055c4a28.mov
</td>
<td>
https://user-images.githubusercontent.com/22355127/163267421-5be90b19-ac4a-460c-85f9-b8a8c59d7e7e.mov
</td>
</tr>
</table>
=> Fix location button background color changes when connecting

nebula/ui/components.qrc, nebula/ui/components/VPNCancelButton.qml, nebula/ui/components/VPNLinkButton.qml, nebula/ui/components/VPNLoader.qml, nebula/ui/components/VPNRemoveDevicePopup.qml, nebula/ui/components/inAppAuth/qmldir, nebula/ui/components/qmldir, src/ui/authenticationInApp/ViewAuthenticationSignIn.qml, src/ui/authenticationInApp/ViewAuthenticationSignUp.qml, src/ui/authenticationInApp/ViewAuthenticationUnblockCodeNeeded.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml, src/ui/views/ViewContactUs.qml
- Create `VPNCancelButton` component to be used everywhere that a cancel button is needed (for consistency)
[2783: As a user, I want buttons that perform the same function to look the same - [make new 'Cancel' component]](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2783)
=> Fix-2783: Consistent cancel button

translations/strings.yaml
This PR adds strings to support trial subscriptions.
=> Add free trial strings

src/featurelist.cpp, src/features/featurefreetrial.h, src/ui/views/ViewMobileOnboarding.qml
This PR adds free trials to the feature list.
- Jira: [Add free trials as feature and enable by default on mobile (VPN-2051)](https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-2051)
=> Add free trial as feature

nebula/ui/components/VPNCollapsibleCard.qml, translations/strings.yaml
- This fixes the issue where collapsible card would not expand again after being collapsed
[VPN-2033: Multi-hop collapsible card can only be expanded once](https://mozilla-hub.atlassian.net/browse/VPN-2033) / #3267
[VPN-923: Add accessibleName to VPNCollapsibleCard toggle](https://mozilla-hub.atlassian.net/browse/VPN-923) /  #1665
=> Fix collapsible card not expanding

src/ui/views/ViewMobileOnboarding.qml
Fixes binding loops in mobile onboarding panel. This should go out with the Free Trials updates.
=> Fix binding loops in mobile onboarding

scripts/utils/generate_strings.py
No empty line means that the last string changes every time we add new content at the end of the file.
=> Enforce empty line at the end of strings.yaml

src/ui/authenticationInApp/ViewAuthenticationInApp.qml
Fixes the ` isDeleteAccountAuth` is undefined error.
Fixes #3388
=> Fix isDeleteAccountAuth is undefined

src/ui/views/ViewContactUs.qml
Hides user details and avatar in the Contact Support form when the user is unauthenticated. Restores functionality I inadvertently removed in #3381 
=> Hide user info in Contact Support form if user is unauthenticated

nebula/ui/components/VPNConnectionInfoContent.qml
Tiniest refactor to fix recursive rearranges in connection speed test and reduce `Warning: Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.` warnings.
#3416
=> Fix recursive rearranges in connection speed test screen

src/mozillavpn.cpp, src/mozillavpn.h, src/ui/main.qml, tests/auth/mocmozillavpn.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp
https://mozilla-hub.atlassian.net/browse/VPN-2160
=> Expose graphicsApi and use it in the glean initialization

src/iaphandler.cpp, src/iaphandler.h
In our last backlog refinement, we talked about potentially bumping plans with free trials up, as 6mnt plan won't be deprecated soon.
=> Proposal: Sort Plans by trial days

src/platforms/windows/daemon/windowsdaemontunnel.cpp, src/platforms/windows/daemon/wireguardutilswindows.cpp, src/platforms/windows/daemon/wireguardutilswindows.h, src/wgquickprocess.cpp, src/wgquickprocess.h, windows/tunnel/main.go, windows/tunnel/service.go
[ As per #2910 
](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2910) - We're not writing the config to disk anymore, but passing it directly into the windowstunneldaemon
[    i.e Jira or Github issue URL](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2910)
=> Do not write the conf file on windows

src/platforms/ios/iosiaphandler.mm
Haven't tried it yet, as xcode is still installing, but i am fairly confident that i made a mistake here :D 
=> Fix IAP-Discount not shown

.taskcluster.yml
Bump to latest.
[RELENG-911](https://mozilla-hub.atlassian.net/browse/RELENG-911)
=> ci(taskcluster): bump decision image

android/gradle.properties, taskcluster/ci/build/android.yml, taskcluster/ci/config.yml
we're running OOM a lot, so let's use a bigger taskcluster vm :) 
=> Get android builds a bigger taskcluster vm

android/src/org/mozilla/firefox/vpn/InAppPurchase.kt
Google play and java seem to disagree how to note a week-duration.
Causing in an unhandled exception and thus never finishing the load of a plan, when a free-trial ( of a week ) is present
=> Android: Fix Enless Loading of a free trial plan

glean/metrics.yaml
Mark some of the glean events as `interaction`
https://mozilla-hub.atlassian.net/browse/VPN-2182
=> Mark some of the glean events as `interaction`

docs/tutorials.md, scripts/ci/jsonSchemas/tutorial.json, src/models/tutorial.cpp, src/models/tutorial.h, src/models/tutorialmodel.cpp, src/models/tutorialmodel.h, src/ui/developerMenu/ViewTutorials.qml, src/ui/tutorials/01_get_started.json
We need to show the highlighted tutorial on top of the view. Let's expose it
https://mozilla-hub.atlassian.net/browse/VPN-2200
=> Add highlighted tutorial attribute

docs/Command-line-interface.md, src/commands/commandstatus.cpp
Expose VPN status to the cli 'status' command
VPN-2197
=> Expose VPN state via 'status' cli - VPN-2197

src/adjust/adjusttasksubmission.cpp, src/networkrequest.cpp
=> Reduce the level of information shared through logs

src/iaphandler.cpp
Do not expose trial days if the feature is not exposed
https://mozilla-hub.atlassian.net/browse/VPN-2230
=> Do not expose free-trial products if free-trial feature is not supported

taskcluster/ci/build/macos.yml, taskcluster/ci/config.yml, taskcluster/ci/signing/kind.yml, taskcluster/mozillavpn_taskgraph/__init__.py, taskcluster/mozillavpn_taskgraph/transforms/build.py, taskcluster/mozillavpn_taskgraph/transforms/signing.py, taskcluster/mozillavpn_taskgraph/worker_types.py, taskcluster/scripts/build/macos_build.sh, taskcluster/scripts/signing/entitlements.xml, taskcluster/scripts/signing/loginItems-entitlements.xml, taskcluster/test/params/main-push.yml, taskcluster/test/params/pull-request.yml, taskcluster/test/params/release-push.yml
commit 52f3a0014af68bebbf11ff0956a8e9702706434a
Author: Heitor Neiva <hneiva@mozilla.com>
Date:   Wed May 11 11:38:48 2022 -0700
Fix mac build artifact path
commit 0158bae2b303f875feb5e200326aa913444d3140
Author: Heitor Neiva <hneiva@mozilla.com>
Date:   Tue May 10 14:34:30 2022 -0700
Verbose logging on mac build script
commit bd476809d2fcd701c59ef10e1b4f72631375469d
Author: Heitor Neiva <hneiva@mozilla.com>
Date:   Mon May 9 16:08:17 2022 -0700
Change artifact paths
commit a0c81f206298e7679e97ebbea0ca5f6f0afd6b1d
Author: Andrew Halberstadt <ahal@mozilla.com>
Date:   Mon May 9 16:28:20 2022 -0400
Stand up a Mac signing task
Jira: RELENG-804
=> ci: Mac build and signing tasks

taskcluster/ci/docker-image/kind.yml, taskcluster/docker/wasm/Dockerfile, taskcluster/scripts/build/wasm.sh
Should fix our permared wasm builds
=> Taskcluster: Fix wasm build

src/models/tutorialstepbefore.cpp, src/models/tutorialstepbefore.h, src/ui/tutorials/01_get_started.json
https://mozilla-hub.atlassian.net/browse/VPN-2175
We need to reset the entry/exit nodes for the first tutorial.
=> Change location to support multi-hop in tutorials

translations/translations.pri
=> Mention ./scripts/utils/import_languages.py in error message.

src/featurelist.cpp, src/features/featurewebsocket.h, src/mozillavpn.cpp, tests/unit/testwebsockethandler.cpp
Clone from https://github.com/mozilla-mobile/mozilla-vpn-client/pull/3600, but not from my fork branch.
https://mozilla-hub.atlassian.net/browse/VPN-2276
=> VPN-2276 - Put push feature behind feature flag

src/models/survey.cpp, src/models/survey.h, tests/unit/testmodels.cpp
Is this what we need for the survey for 2.9?
=> Make surveys per locale

src/update/balrog.cpp
On windows, we see the installer killed together with the app. This happens because the program is still attached to the VPN client instance. Let's use `startDetached` instead.
=> Start update with a detached process - VPN-116

.taskcluster.yml
Remove copied code from Fenix. Fixes retrigering decision tasks.
=> ci: Fix decision task retrigger

src/ui/settings/ViewGuide.qml
https://user-images.githubusercontent.com/22355127/171677495-8ba8a888-2425-4745-ba40-f82674ca6969.mov
#3643
=> Update back button in guide views - Fix #3643

nebula/ui/components/VPNConnectionInfoContent.qml
Fixes the vertical alignment of the connection info details.
[VPN-2263](https://mozilla-hub.atlassian.net/browse/VPN-2263)
=> Center connection info details vertically

.github/workflows/translations.yaml, .gitignore, scripts/addon/build.py, scripts/utils/generate_strings.py, scripts/utils/generate_ts.sh
@bakulf 
This is built/open against your current PR. Feel free to close if it's not useful.
You can see the result of the action here
https://github.com/flodolo/mozilla-vpn-client/actions/runs/2447966583
=> Fixes for PR3638

src/mozillavpn.cpp, src/mozillavpn.h
Remove unused LinkFeedback (was replaced with inapp feedback form)
Tech Debt
=> Remove unused LinkFeedback

src/websockethandler.cpp, src/websockethandler.h, tests/unit/testwebsockethandler.cpp, tests/unit/testwebsockethandler.h
The title is descriptive enough for the main changes here.
I also did some clean up and added an extra test for the `close` method.
https://mozilla-hub.atlassian.net/browse/VPN-2259
=> VPN-2259 - Implement exponentially increasing interval between WebSocket server connection retries

glean/metrics.yaml, macos/pkg/scripts/postinstall, src/cmake/sources.cmake, src/commands/commandui.cpp, src/mozillavpn.cpp, src/mozillavpn.h, src/qmake/sources.pri, src/releasemonitor.cpp, src/tasks/release/taskrelease.cpp, src/tasks/release/taskrelease.h, src/ui/views/ViewUpdate.qml, src/update/balrog.cpp, src/update/updater.cpp, src/update/updater.h, src/update/webupdater.cpp, src/update/webupdater.h, tests/auth/CMakeLists.txt, tests/auth/auth.pro, tests/auth/mocmozillavpn.cpp, tests/qml/CMakeLists.txt, tests/qml/mocmozillavpn.cpp, tests/qml/qml.pro, tests/unit/CMakeLists.txt, tests/unit/mocmozillavpn.cpp, tests/unit/unit.pro, windows/installer/MozillaVPN.wxs, windows/installer/MozillaVPN_prod.wxs
This PR introduces a list of glean event states to go through the whole update flow.
VPN-2173
=> Glean events for the update flow

src/featureslist.h, src/platforms/ios/ioscontroller.mm, src/platforms/ios/ioscontroller.swift
https://mozilla-hub.atlassian.net/browse/VPN-2393
=> Remove the ios-kill-switch `Feature` and include all networks by default

addons/guide_04_connecting_external_devices/manifest.json
- Small update to the content of the [Connecting External Devices](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/addons/guide_04_connecting_external_devices/manifest.json) guide
[VPN-2302: Discrepancies between Mozilla VPN app and Figma for the “VPN Tips and tricks” feature ](https://mozilla-hub.atlassian.net/browse/VPN-2302)
=> Content change for guide

CMakeLists.txt, version.pri
As we have entered Codefreeze for 2.9, main is now targeting 2.10 :) 
=> Version Bump 2.10.0

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3718
Note: This is currently depending on those 2 pr's merging first: 
-> https://github.com/mozilla-mobile/mozilla-vpn-client/pull/3717
-> https://github.com/mozilla-mobile/mozilla-vpn-client/pull/3375
=> Add periodic controllerStateOn event as backgrounded task in android

src/featureslist.h, tests/functional/testSettings.js
Enable subscription management by default.
[VPN-2437](https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-2437)
=> Enable subscription management feature by default

src/ui/views/ViewMobileOnboarding.qml
This seems to work, but I don't understand why you added the `shouldRestoreSlide` prop. Maybe this PR introduces regressions.
=> Go back to the previous onboarding view from the get-help menu - VPN-2258

nebula/ui/components/VPNTutorialPopups.qml
Fixes the rest of VPN-2432/ #3795.
VPN-2432/ #3795
=> Reset onClosed() when opening "Leave tutorial?" popup

src/ui/deleteAccount/ViewDeleteAccountRequest.qml, src/ui/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml, tests/functional/testSubscription.js
=> Add tests for the auth in subscription and account deletion

.github/workflows/macos-build.yaml, .github/workflows/wasm.yaml, addons/CMakeLists.txt, linux/mozillavpn.spec, scripts/addon/build.py, scripts/addon/generate_all.py, scripts/android/package.sh, scripts/linux/ppa_script.sh, scripts/macos/apple_compile.sh, scripts/windows/compile.bat, taskcluster/scripts/build/android_build_debug.sh, taskcluster/scripts/build/android_build_release.sh, taskcluster/scripts/build/wasm.sh, taskcluster/scripts/build/windows.ps1
We need the TS files only when generating strings for the translation. But because this is a temporary thing for 2.9. only, I don't want to change the l10n repo.
=> Remove extra files in the final addon folder

addons/examples/tic-tac-toe/manifest.json, scripts/addon/build.py, scripts/ci/check_jsonschema.py, scripts/ci/jsonSchemas/addon.json, scripts/ci/jsonSchemas/composer_block.json, scripts/ci/jsonSchemas/conditions.json, scripts/ci/jsonSchemas/demo.json, scripts/ci/jsonSchemas/message.json, src/addons/addon.cpp, src/addons/addondemo.cpp, src/addons/addonmessage.cpp, src/addons/addonmessage.h, src/cmake/sources.cmake, src/qmake/sources.pri, tests/unit/CMakeLists.txt, tests/unit/testaddon.cpp, tests/unit/testaddon.h, tests/unit/unit.pro
A simple addon message to start.
=> Addon messages

src/models/subscriptiondata.cpp, src/models/subscriptiondata.h, src/ui/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml, tests/functional/testSubscription.js
[Card funding type](https://stripe.com/docs/api/charges/object#charge_object-payment_method_details-card-funding) can be `credit`, `debit`, `prepaid` or `unknown`.
[VPN-2499](https://mozilla-hub.atlassian.net/browse/VPN-2499)
=> Handle debit and prepaid cards in subscription management

src/ui/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
On bigger screens like iPads the subscription management content is centered vertically.
[VPN-2461](https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-2461)
=> Fix vertical subscription alignment

nebula/ui/components/VPNTutorialPopups.qml, src/externalophandler.cpp, src/externalophandler.h, src/mozillavpn.cpp, src/mozillavpn.h, src/tutorial/tutorial.cpp, src/tutorial/tutorial.h, src/ui/main.qml, tests/auth/mocmozillavpn.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp
=> Move the leave-tutorial logic in the C++ layer

src/addonmanager.cpp, src/addonmanager.h, src/ui/views/ViewMain.qml
https://mozilla-hub.atlassian.net/browse/VPN-2576
=> Show the tips&tricks modal when the addons are fully loaded

src/models/subscriptiondata.cpp, tests/functional/testSubscription.js
=> Consider any non-active subscription state as inactive - fixes VPN-2592

wasm/controller.js, wasm/main.js
There is 1 small typo in the wasm client code that just landed.
=> Fix a small typo in the wasm client

src/featureslist.h, src/featureslistcallback.h, src/iaphandler.cpp, src/mozillavpn.cpp, src/networkrequest.cpp, src/networkrequest.h, src/platforms/wasm/wasmiaphandler.cpp, src/platforms/wasm/wasmiaphandler.h, src/qmake/platforms/wasm.pri, src/tasks/purchase/taskpurchase.cpp, src/tasks/purchase/taskpurchase.h, wasm/main.js, wasm/presets.js
This is a big PR because it introduces:
- IAP for wasm - with all the possible error scenarios
- backend failure scenario in wasm
- better messaging handler in the wasm viewer
- more auth error scenarios (basically all..?)
=> Wasm errors

wasm/controller.js, wasm/index.html, wasm/main.css, wasm/main.js
This feature has been asked by the QA team
=> Expose languages in the wasm view

src/addonmanager.cpp
The loading of addons during the first execution is broken by another PR. I found the issue via the wasm functional tests, but I want to land asap to unblock other developers/testers.
=> Fix the loading of the addons during the first execution

nebula/ui/components/VPNButton.qml, nebula/ui/components/VPNButtonLoader.qml, nebula/ui/components/VPNClickableRow.qml, nebula/ui/components/VPNLinkButton.qml, nebula/ui/components/VPNUserProfile.qml, src/ui/settings/ViewSettingsMenu.qml, src/ui/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml, src/ui/views/ViewContactUs.qml, tests/functional/testContactUs.js, tests/functional/testSettings.js
This expands the clickable area of VPNUserInfo.qml so that the entire row is clickable, instead of just the icon button,  updates affected files, and adds or updates functional tests.
https://user-images.githubusercontent.com/22355127/180316383-d978c40f-56fd-4dcb-b5b6-5ee43baf00a5.mov
#4040
=> Increase VPNUserInfo clickable area

src/cmake/sources.cmake, src/commands/commandui.cpp, src/constants.h, src/keyregenerator.cpp, src/keyregenerator.h, src/mozillavpn.cpp, src/mozillavpn.h, src/qmake/sources.pri, src/settingslist.h, src/tasks/adddevice/taskadddevice.cpp, tests/unit/mocmozillavpn.cpp
It was actually quite easy to implement.
=> Regenerate keys once a week

src/cmake/sources.cmake, src/inspector/inspectorhandler.cpp, src/mozillavpn.cpp, src/mozillavpn.h, src/networkrequest.cpp, src/qmake/sources.pri, src/ui/views/ViewMain.qml, src/websocket/exponentialbackoffstrategy.cpp, src/websocket/exponentialbackoffstrategy.h, src/websocket/pushmessage.cpp, src/websocket/pushmessage.h, src/websocket/websockethandler.cpp, src/websocket/websockethandler.h, tests/functional/guardian.js, tests/functional/helper.js, tests/functional/setupVpn.js, tests/functional/testPushMessageHandlers.js, tests/functional/wasm-test-ignore, tests/unit/CMakeLists.txt, tests/unit/unit.pro, tests/unit/websocket/testexponentialbackoffstrategy.cpp, tests/unit/websocket/testexponentialbackoffstrategy.h, tests/unit/websocket/testpushmessage.cpp, tests/unit/websocket/testpushmessage.h, tests/unit/websocket/testwebsockethandler.cpp, tests/unit/websocket/testwebsockethandler.h
I also did some housekeeping work to break the websockets module into multiple files, because with the `pushmessage` module also in there, it would get too crowded.
Note: I suggest reviewing this commit-by-commit.
https://mozilla-hub.atlassian.net/browse/VPN-2261
=> VPN-2261 - Implement handler for DEVICE_DELETED push message

src/addonmanager.cpp
This is a simply optimization to make or code safer.
=> Use QSaveFile to save files

src/addonmanager.cpp, src/commands/commandui.cpp, src/crashreporter/crashreporter.cpp, src/crashreporter/crashreporter.h, src/crashreporter/crashui.cpp, src/filterproxymodel.cpp, src/filterproxymodel.h, src/inspector/inspectorhandler.cpp, src/inspector/inspectorutils.cpp, src/models/featuremodel.cpp, src/qmlengineholder.cpp, src/qmlengineholder.h, tests/qml/CMakeLists.txt, tests/qml/helper.cpp, tests/qml/qml.pro, tests/qml/tst_filterableModel.qml, tests/unit/testaddon.cpp, tests/unit/testthemes.cpp
Let's make the model sortable and filterable. VPN-2532
=> Filter and sortable model

src/mozillavpn.cpp
I don't know how to reproduce this crash. I suspect it's a regression of the key regeneration.
=> Fix a crash for the device registration

src/ui/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
There is a missing objectName propagation
=> Fix the functional tests

src/featureslist.h, tests/unit/websocket/testwebsockethandler.cpp
https://mozilla-hub.atlassian.net/browse/VPN-2646
=> VPN-2646 - Remove websocket feature flag and leave it on by default

android/build.gradle, android/gradle.properties, android/src/org/mozilla/firefox/vpn/qt/VPNUtils.kt, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h
Closes [#android signature](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3926)
=> Android Addon verification

tests/unit/CMakeLists.txt
=> Fix running of websocket tests with ctest

src/tasks/adddevice/taskadddevice.cpp
This fixes VPN-2643, probably just partially, but it's a good starting point.
=> Do not reset the journal public/private keys when something goes wrong

scripts/ci/jsonSchemas/message.json, src/addons/addonmessage.cpp, src/addons/addonmessage.h, src/localizer.h, tests/unit/testaddon.cpp, tests/unit/testaddon.h, translations/strings.yaml
A way to set the incoming dates for addon messages.
=> Date message

taskcluster/ci/build/kind.yml, taskcluster/ci/build/windows.yml, taskcluster/ci/config.yml, taskcluster/ci/repackage-signing/kind.yml, taskcluster/ci/repackage/kind.yml, taskcluster/ci/signing/kind.yml, taskcluster/mozillavpn_taskgraph/transforms/build.py, taskcluster/mozillavpn_taskgraph/transforms/release_artifacts.py, taskcluster/mozillavpn_taskgraph/transforms/signing.py, taskcluster/requirements.in, taskcluster/requirements.txt, taskcluster/scripts/build/windows.ps1, windows/installer/build_prod.cmd
This will add 3 tasks that run one after the other:
1. Signing internals
2. Repackage MSI
3. Signing MSI
Still a WIP
=> Add signing tasks for Taskcluster windows builds

nebula/ui/components/VPNSettingsToggle.qml
This prevents UI responses when hovering/pressing disabled toggles.
#3703  / VPN-2376
=> Fix disabled toggle behavior (VPN-2376/#3703 pt. 2)

src/websocket/websockethandler.cpp, src/websocket/websockethandler.h, tests/unit/websocket/testwebsockethandler.cpp, tests/unit/websocket/testwebsockethandler.h
https://mozilla-hub.atlassian.net/browse/VPN-2384
=> VPN-2384 - Fix intermittent MacOS failure on websocket tests

nebula/ui/components/VPNCheckmarkList.qml, nebula/ui/components/VPNConnectionInfoContent.qml, nebula/ui/components/VPNControllerView.qml, nebula/ui/components/VPNIPAddress.qml
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table
#4063
=> Fix connection info screen in landscape mode - #4063

LICENSE.md
This has been discussed on slack.
=> License updated

src/addons/manager/addonmanager.cpp, src/addons/manager/addonmanager.h, src/constants.h, src/settingslist.h, src/tasks/addon/taskaddon.cpp, src/tasks/addonindex/taskaddonindex.cpp, src/ui/developerMenu/ViewDeveloperMenu.qml
=> Custom addon server URLs

src/websocket/websockethandler.cpp
~No ticket for this one, found it and fixed it immediatelly.~ Eh, ended up filing a ticket: https://mozilla-hub.atlassian.net/browse/VPN-2713
=> BUGFIX: Do not attempt to close websocket, if not connected

src/ui/screens/settings/ViewAboutUs.qml
This fixes the broken "Okay" button in the update modal. 
#4244 , VPN-2728
=> 4244/2728 - Fix update modal close

nebula/ui/components/VPNLinkButton.qml
This fixes flickering VPNLinkButton text
#4251
=> Fix 4251/2735 - Fix flickering links

src/websocket/websockethandler.cpp, src/websocket/websockethandler.h
Have tested this on MacOS and confirmed it does fix the issue. Here are the logs:
```
[25.08.2022 18:15:02.388] Debug: (main - WebSocketHandler) WebSocket pong 163
[25.08.2022 18:15:50.390] Debug: (main - WebSocketHandler) WebSocket pong 157
[25.08.2022 18:16:38.390] Debug: (main - WebSocketHandler) WebSocket pong 156
[25.08.2022 18:17:26.376] Debug: (main - WebSocketHandler) WebSocket pong 155
[25.08.2022 18:18:09.703] Debug: (main - WebSocketHandler) WebSocket error: QAbstractSocket::RemoteHostClosedError
[25.08.2022 18:18:09.703] Debug: (main - WebSocketHandler) Closing WebSocket
[25.08.2022 18:18:09.704] Debug: (main - WebSocketHandler) WebSocket error: QAbstractSocket::SslInternalError
[25.08.2022 18:18:09.704] Debug: (main - WebSocketHandler) Attempted to close a WebSocket …
```
=> VPN-2729, VPN-2740 - Mitigate infinite loop errors on closing ws connection

src/ui/screens/settings/ViewSettingsMenu.qml, src/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
=> Fix manage account flows

src/ui/main.qml
https://mozilla-hub.atlassian.net/browse/VPN-2704
=> VPN-2704 - Submit a ping before shuttind app down

glean/metrics.yaml, src/mozillavpn.cpp, src/mozillavpn.h, src/tasks/removedevice/taskremovedevice.cpp, src/websocket/pushmessage.cpp, src/websocket/pushmessage.h, src/websocket/websockethandler.cpp, tests/auth/mocmozillavpn.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp
https://mozilla-hub.atlassian.net/browse/VPN-2563
- I would have loved to add tests for these. With the current structure that is not really straight forward so I skipped that for now.
- I tested manually though, see https://debug-ping-preview.firebaseapp.com/pings/beavpntesting
=> VPN-2563 - Instrument websocket handler and device removal push message

src/addons/addontutorial.cpp, src/addons/addontutorial.h, src/cmake/sources.cmake, src/frontend/navigator.cpp, src/frontend/navigator.h, src/frontend/navigatorreloader.cpp, src/frontend/navigatorreloader.h, src/qmake/sources.pri, tests/unit/CMakeLists.txt, tests/unit/unit.pro
=> Force the navigator reload via RAA classes

docs/add-on.md
=> Add-on documentation

src/addons/addonapi.cpp, src/addons/addonapi.h, src/mozillavpn.cpp, src/mozillavpn.h, tests/auth/mocmozillavpn.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp, tests/unit/testaddon.cpp
Expose the navigator and a way to open URLs to add-ons
=> Expose navigator and openURL

src/ui/screens/devices/ViewDevices.qml, src/ui/screens/home/ViewHome.qml, src/ui/screens/settings/ViewSettingsMenu.qml, tests/functional/testDevices.js
Move device list button from home screen to settings menu
[VPN-2486: Move "My devices" to inside settings](https://mozilla-hub.atlassian.net/browse/VPN-2490)
=> Move device list to settings

src/ui/screens/home/ViewHome.qml
=> fix: Mobile header icon

src/statusicon.cpp
Fixes loop in the status icon image generation.
[VPN-2808](https://mozilla-hub.atlassian.net/browse/VPN-2808): Loop in the StatusIcon image generation
=> Fix: Status icon indicator loop

src/ui/navigator/navigatorLoader.qml
Oh hey, i'm doing more esoteric bug fixing. 
@lesleyjanenorton, @MattLichtenstein, @flozia - In case you know where that values come from, please tell me 😅 
|--------|-------|
| ![screen-20220905-140743_AdobeExpress](https://user-images.githubusercontent.com/9611612/188477526-97872d9f-364d-4de0-8fb6-8c20ec268369.gif)  | ![screen-20220905-165614_AdobeExpress](https://user-images.githubusercontent.com/9611612/188477772-6b42134b-2ca5-4751-89e0-9cf545014a50.gif)
|
=> Android: Hotfix qml navigation

src/ui/screens/messaging/ViewMessagesInbox.qml
Fix inbox menu title
[VPN-2834: Incorrect menu title for message inbox screen](https://mozilla-hub.atlassian.net/browse/VPN-2834)
=> Fix inbox menu title

addons/message_whats_new_v2.10/manifest.json
This PR adds the 2.10 "Whats new" message
=> Add What's New message

src/urlopener.cpp, src/urlopener.h, tests/unit/CMakeLists.txt, tests/unit/testurlopener.cpp, tests/unit/testurlopener.h, tests/unit/unit.pro
See 37a0e9f15e146f4f540cf54204f0f8209bd8e7cd
=> Add URLOpener query replacement

addons/message_update/manifest.json, docs/add-on.md, docs/guides.md, docs/messages.md, scripts/ci/jsonSchemas/message.json
Wiki documentation for add-on messages
None
=> Add add-on message documentation

addons/message_privacy_bundle_staging/EnableBundleUpgrade.js, addons/message_privacy_bundle_staging/OpenBundleUpgradeFlow.js, addons/message_privacy_bundle_staging/OpenGetHelpScreen.js, addons/message_privacy_bundle_staging/manifest.json
=> Add bundle message 

nebula/ui/themes/themes.js, src/ui/navigator/navigationBar/VPNBottomNavigationBar.qml, src/ui/navigator/navigationBar/VPNBottomNavigationBarButton.qml
- Fix spacing betwen navbar icons so that it matches the spec up to 6 icons
[VPN-2806: Navigation bar icons are spaced too far apart](https://mozilla-hub.atlassian.net/browse/VPN-2806)
=> Vpn 2806 navbar icon spacing

src/addons/addonmessage.cpp, src/addons/manager/addonmanager.cpp, src/settingsholder.cpp, src/settingsholder.h, src/ui/navigator/navigationBar/VPNBottomNavigationBar.qml, tests/unit/testaddon.cpp
I also reduced the number of getAddonSettingsKey call because each time we were generating a key string.
=> Fix the message notification - VPN-2857

src/ui/navigator/navigationBar/VPNBottomNavigationBar.qml
Fixes VPN-2824/ #4418
Fixes #4418
=> Fix connection error in nav bar

addons/message_survey/manifest.json, addons/message_survey/setDate.js, addons/message_survey_staging_1h/manifest.json, addons/message_survey_staging_1h/setDate.js, addons/message_survey_staging_30m/manifest.json, addons/message_survey_staging_30m/setDate.js, scripts/ci/jsonSchemas/addon.json, scripts/ci/jsonSchemas/javascript.json, scripts/ci/jsonSchemas/message.json, src/addons/addon.cpp, src/addons/addon.h, src/addons/addonmessage.cpp, src/addons/addonmessage.h
fixes [VPN-2866](https://mozilla-hub.atlassian.net/browse/VPN-2866)
=> Add the javascript scripts for addon enabling/disabling

nebula/ui/components/forms/VPNSearchBar.qml, src/ui/screens/messaging/ViewMessagesInbox.qml, src/ui/screens/settings/ViewLanguage.qml
Fixes a qml warning generated by VPNSearchBar.qml
[VPN-2845: Bug in VPNSearchBar](https://mozilla-hub.atlassian.net/browse/VPN-2845)
=> Fix qml warning in searchbar

nebula/ui/components/VPNTutorialPopups.qml, src/tutorial/tutorial.cpp, src/tutorial/tutorial.h, src/tutorial/tutorialstep.cpp, src/tutorial/tutorialstep.h
This was a regression of the DOM PR
=> Do not expose the AddonProperty object but its value - fixes VPN-2880

src/inspector/inspectorhandler.cpp, src/mozillavpn.cpp, tests/functional/helper.js, tests/functional/testDevices.js
I moved the logic in `deviceRemoved()`
=> Recompute the device-limit view when the device is removed - VPN-2847

src/addons/manager/addonmanager.cpp, src/adjust/adjusttasksubmission.h, src/task.h, src/tasks/adddevice/taskadddevice.h, src/tasks/addon/taskaddon.h, src/tasks/function/taskfunction.cpp, src/tasks/function/taskfunction.h, src/tasks/group/taskgroup.cpp, src/tasks/group/taskgroup.h, src/tasks/release/taskrelease.h, src/tasks/removedevice/taskremovedevice.h, src/taskscheduler.cpp, tests/unit/CMakeLists.txt, tests/unit/testtasks.cpp, tests/unit/testtasks.h, tests/unit/unit.pro
This is the algorithm I was discussing with you. It seems to work fine. Not for 2.10.
=> Reschedulable tasks

src/frontend/navigator.cpp, src/frontend/navigator.h, src/ui/deleteAccount/ViewDeleteAccount.qml, src/ui/screens/ScreenDeleteAccount.qml, src/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml, src/ui/ui.qrc
This adds VPNNavigator.ScreenDeleteAccount to fix #4401 / VPN-2778
#4401 / VPN-2778
=> Add ScreenDeleteAccount - Fix VPN-2778

addons/message_privacy_bundle_staging/manifest.json
This adds final bundle message content minus one string, which we will only have once pricing has been determined.
=> Add final bundle message content minus one pending string

src/platforms/windows/windowspingsender.cpp
When cleaning up the `WindowsPingSender` class, we need to call the Windows `IcmpCloseHandle` API. However, this method appears to hang until all outstanding ICMP echo replies are either received, or a timeout occurs, which can lead to an application hang of up to 10 seconds.
To resolve the issue, we move the `IcmpCloseHandle` API into a separate thread, which allows the closure to occur asynchronously without blocking the client.
GitHub #4509 ([VPN-2932](https://mozilla-hub.atlassian.net/browse/VPN-2932))
=> Defer IcmpCloseHandle when cleaning up.

glean/metrics.yaml, nebula/ui/components/VPNComposerView.qml, src/addons/addon.cpp, src/addons/addon.h, src/addons/addonmessage.cpp, src/addons/addonmessage.h, src/addons/manager/addonmanager.cpp, tests/unit/testaddon.cpp
=> Emit Glean pings on addon, message state changes

taskcluster/ci/config.yml, taskcluster/mozillavpn_taskgraph/actions/release_promotion.py, taskcluster/mozillavpn_taskgraph/target_tasks.py, taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
- [Simplify release-promotion target_task methods](https://github.com/mozilla-mobile/mozilla-vpn-client/commit/a87d1b4de5ae83eb8b5bc342e8906abb12d8b6ca)
- [Delete un-used build_number parameter from release-promotion action](https://github.com/mozilla-mobile/mozilla-vpn-client/commit/aff3d7ab753655eec505fe5599277b38bfcad9a7)
- [Move addons release-artifacts generation to a separate transform](https://github.com/mozilla-mobile/mozilla-vpn-client/commit/ba892a7e5bfc048b5ce99ff181cbf5a92664fb85)
cc @strseb 
#4341
=> A bit of clean up for vpn taskgraph

src/models/featuremodel.cpp
=> Feature fix in 6/8

taskcluster/mozillavpn_taskgraph/transforms/signing.py
Sign the VPN add-ons with the release key.
[RELENG-968](https://mozilla-hub.atlassian.net/browse/RELENG-968)
=> Sign the VPN addons using the release key

src/ui/screens/getHelp/contactUs/ViewContactUsForm.qml
There is still another issue: the secondary button (the learn-more link) is under the navigation bar. @flozia is there anything we can do here?
=> Fix the try-again button in the contact-us-form - VPN-2908

src/ui/screens/settings/appPermissions/ViewAppPermissions.qml
This fixes success banners when adding new apps in the app permissions view.
VPN-2815 / #4379
=> Fix app permissions success banners

nebula/ui/components/VPNCollapsibleCard.qml, nebula/ui/components/VPNSegmentedToggle.qml, tests/functional/actions.js, tests/functional/elements.js, tests/functional/helper.js, tests/functional/testMultihop.js
added multihop connectivity functional tests
[i.e Jira or Github issue URL](https://mozilla-hub.atlassian.net/browse/PSP-493)
=> adding multihop functional tests, some optimizations to helper class

src/ui/main.qml
This fixes UI conflicts (unclickable regions of some header buttons, obscured menu titles) on iPhone 14 Pro and iPhone 14 Pro Max. iPhone 14 & iPhone 14 Plus are not affected.
<table>
<tr>
<td>Before - iPhone 14 Pro</td>
<td>After</td>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/22355127/195423536-b023eefd-9589-4607-99e1-1065808482c4.mov
</td>
<td>
https://user-images.githubusercontent.com/22355127/195424595-dcc45898-dbaa-4120-9e65-c42dd00314b9.mov
</td>
</tr>
</table>
<table>
<tr>
<td>Before - iPhone 14 Pro Max</td>
<td>After</td>
</tr>
<tr>
<tr>
<td>
https://user-images.githubusercontent.com/22355127/195424016-ea13574d-7a30-4449-9348-194872bcbee2.mov
</td>
<td>
https://user-images.githubusercontent.com/22355127/195424316-5110459d-c52e-4fba-bfcb-33048ff191ac.mov
</td>
</tr> …
=> Update native header clearance for iPhone 14 Pro & iPhone 14 Pro Max

nebula/ui/components/VPNViewBase.qml, src/ui/screens/tipsAndTricks/ViewTipsAndTricks.qml
Not sure why this warning was only showing on the Tips & Tricks page. AFAICT it could be shown in any page (?).
=> VPN-2886 - Fix warning about titleComponent not being defined

.github/workflows/functional_tests.yaml
Provide grcov with the necessary permissions to generate coverage details
[JIRA EPIC LINK](https://mozilla-hub.atlassian.net/browse/PSP-540)
=> provide permissions to grcov to generate  coverage details

.github/workflows/functional_tests.yaml, .github/workflows/gh_pages.yaml, .github/workflows/linters.yaml, .github/workflows/linux.yaml, .github/workflows/ppa-automation.yaml, .github/workflows/test_lottie.yaml, .github/workflows/test_qml.yaml, .github/workflows/test_unit.yaml, .github/workflows/wasm.yaml, .github/workflows/wiki.yaml
Update GA node version from 12
[VPN-3043](https://mozilla-hub.atlassian.net/browse/VPN-3043)
=> update ga node version

src/platforms/windows/windowsstartatbootwatcher.cpp
Wrong entry in the register key. This fixed the remaining part of VPN-2054
=> Fix the startup-at-boot minimized on windows

README.md
-Noted recommended Qt version and required Qt packages
-Noted required VS studio packages
-Added hint about x64 prompt
-Added UI debug instructions
-Note about OpenSSL
=> Readme improvements for Windows

README.md
[Rendered](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/451aa6904f2a560d6da5effd6a9232a8aebd0bca/README.md#working-on-tickets-with-new-glean-instrumentation)
=> VPN-3022 - Update data-review instructions on README.md

tools/wasm_chrome/branch_selector.mjs, tools/wasm_chrome/fluent_components.mjs, tools/wasm_chrome/index.html, tools/wasm_chrome/taskcluster_frame.mjs
This Pr replaces the old select with a combo-box from fluent. So we have better keyboard support and autofill (!) on the page. Also moved the buttons to a small menu :)
=> Wasm_Chrome: Replace Select with a combo box

taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
Guardian composes the string **mac**/MozillaVPN.pkg
=> Upload macos release candidates to mac directory

nebula/ui/components/forms/VPNPasswordInput.qml, nebula/ui/components/forms/VPNSearchBar.qml, nebula/ui/components/forms/VPNTextArea.qml, nebula/ui/components/forms/VPNTextField.qml
Improve the accessibility of text inputs for screen readers.
- #4555
- #4556
=> Improve text input a11y for screen readers

src/mozillavpn.cpp
Running the removal-device together with the reset() operation means that, if something goes wrong, at the next execution we show the initial screen immediately.
=> Better logout procedure - VPN-3037

taskcluster/ci/signing/kind.yml
https://mozilla-hub.atlassian.net/browse/RELENG-1007
=> Toggle off Linux build signing

package-lock.json, package.json
fix 2 vulnerabilities for npm packages in test suite
[ PSP-555](https://mozilla-hub.atlassian.net/browse/PSP-555)
=> vulnerabilities fix

src/ui/authenticationInApp/ViewAuthenticationStart.qml
This disables predictive text (auto-correct) on the in-app authentication email input.
Fixes VPN-3182 (can't find GitHub issue?)
=> Disable autocorrect on sign up/in email input

android/daemon/src/main/AndroidManifest.xml, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/BootReceiver.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt, src/featureslistcallback.h, src/platforms/android/androidvpnactivity.cpp, src/platforms/android/androidvpnactivity.h
Adds Support for start on boot.
=> Android: Support "Start On Boot" 

src/settingsholder.cpp, src/settingsholder.h, tests/unit/testsettings.cpp
Just to cover 100% the journal-settings impl
=> Extend the journal-settings unit-test to cover the post-recovering

android/AndroidManifest.xml, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNTileService.kt, android/resources/all/values/strings.xml, android/src/org/mozilla/firefox/vpn/VPNTileService.kt, src/platforms/android/androidcontroller.cpp, src/platforms/android/androidcontroller.h
Small thing i wrote while waiting for taskcluster jobs 😅
Adds a tile-service that can interact with the vpn-Service.
The tile service is registered with the OS, thus adding a quick-settings option to control "on/off" on the VPN. 
https://user-images.githubusercontent.com/9611612/155134283-5b0507e0-047b-4602-bb94-b802d0357405.mp4
=> ✨Quicksettings Integration for android 

CMakeLists.txt, version.pri
=> version bump 2.12.0 to 2.13.0

src/ui/screens/ScreenSubscriptionInProgressWeb.qml, translations/strings.yaml
Got the right string from content, updating strings.yaml
https://mozilla-hub.atlassian.net/browse/VPN-3258
=> Update string after content input

src/addons/manager/addonmanager.cpp, src/addons/manager/addonmanager.h, tests/unit/CMakeLists.txt
Refresh client on addon change
[VPN-4922](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4922)
=> testaddons fix with js changes

nebula/ui/components/VPNBoldLabel.qml, nebula/ui/components/forms/VPNSearchBar.qml, nebula/ui/components/forms/VPNTextField.qml
Incremental UI tweaks for better frontend RTL support. 
<table>
<tr>
<th>Search Bar Before</th>
<th>Search Bar After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>VPNBoldLabel Before</th>
<th>VPNBoldLabel After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix RTL search bar & bold labels

CMakeLists.txt, version.pri
=> Version bump for 2.11.1

src/daemon/daemon.cpp, src/platforms/linux/daemon/dnsutilslinux.cpp, src/platforms/linux/daemon/pidtracker.cpp
Fixed allocating unnecessary temporary containers in for-loops
=> Fixed allocating unnecessary temporary containers

src/connectionbenchmark/connectionbenchmark.cpp, src/constants.h, src/featureslist.h, tests/functional/testBenchmark.js
Enable upload benchmark by default and extend functional tests.
- Jira: [VPN-2519](https://mozilla-hub.atlassian.net/browse/VPN-2519)
=> Enable network upload benchmark by default

.gitignore
=> add dummybuild to gitignore

taskcluster/ci/build/android.yml, taskcluster/ci/docker-image/kind.yml
=> Have a 'NEXT' task for armv7

src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml
Remove duplicate version indicator in developer options.
- #4995
=> Remove duplicate dev version indicator

linux/mozillavpn.spec
RPM spec's license field follows SPDX standard and Mozilla Public License 2.0's SPDX code is MPL-2.0.
=> Update license code for RPM spec file

README.md
Update README with more details on Inspector
This came from a discussion I had with Sarah last week. I think it is beneficial to include a little more info on what the Inspector can do and add a screenshot so it doesn't get missed in this rather large read me.
=> Update README with more details on Inspector

src/platforms/ios/iosiaphandler.mm
Products were not flowing through, as function wasn't being called on expected object.
https://mozilla-hub.atlassian.net/browse/VPN-3256
=> Fix iOS IAP options

src/addons/addoni18n.cpp, src/commands/commandui.cpp, src/inspector/inspectorhandler.cpp, src/localizer.cpp, src/localizer.h, src/ui/screens/settings/ViewLanguage.qml, tests/functional/actions.js, tests/functional/helper.js, tests/functional/setupVpn.js, tests/functional/setupWasm.js, tests/functional/testCaptivePortal.js, tests/functional/testConnection.js, tests/functional/testMultihop.js, tests/functional/testServers.js, tests/functional/testSettings.js, tests/functional/testTelemetryView.js, tests/functional/testTipsAndTricksIntroModal.js, tests/functional/testTutorials.js, tests/functional/testUnsecuredNetworkAlert.js, tests/unit/testaddon.cpp, tests/unit/testlocalizer.cpp, wasm/main.js
It turned out that we can cleanup the inspector + settings a lot using QT meta object.
=> Improve the settings code via inspector

src/ui/screens/ScreenInitializeMobileOnboarding.qml, tests/functional/testAuthenticationInApp.js, tests/functional/testAuthenticationInBrowser.js, tests/functional/testDevices.js, tests/functional/testNavigation.js, tests/functional/testOnboarding.js, tests/functional/testTelemetryView.js, tests/functional/testTutorials.js
This is just an experiment to remove a few wait() in tests. We should reach 0 wait()s because behind any of them there is conceptually a bug.
=> Remove a few wait() in tests

docs/add-on.md
Add the exact command to generate and expose custom addons to the instructions.
=> Command for exposing addons through a webservice

.github/workflows/test_unit.yaml
include macos unit test reports to codecov upload
=> small pr to include generated macos unit tests in codecov upload

docs/vpnglean.md, src/cmake/ios.cmake, src/glean/glean.cpp, src/platforms/ios/iosgleanbridge.h, src/platforms/ios/iosgleanbridge.mm, src/platforms/ios/iosgleanbridge.swift, vpnglean/ios.cmake
~This is built on top of #4709.~
Still to do before i take this out of draft mode:
=> VPN-3054 - Use the Glean Rust + iOS SDK on iOS

.github/workflows/gh_pages.yaml, Doxyfile
-> Move doxyfile to repo root.
-> Make /src and /docs as input folder. 
-> adjust ci for that.
=> Include /docs in doxygen

README.md
=> README updates for building

README.md
Explain that currently we do not support enabling VPN from the iOS simulator in XCode.
n/a
=> Add note about iOS simulator

src/apps/vpn/controller.cpp, src/apps/vpn/settingslist.h, translations/strings.yaml
More port 53 cleanup following #4944 .
VPN-3260
=> More port 53 cleanup

nebula/ui/components/VPNLinkButton.qml
=> Fix VPN-3424: Unable to assign [undefined] to QString

nebula/ui/components/VPNAlert.qml, nebula/ui/components/VPNAvatar.qml, nebula/ui/components/VPNButtonBase.qml, nebula/ui/components/VPNCheckBoxRow.qml, nebula/ui/components/VPNClickableRow.qml, nebula/ui/components/VPNConnectionInfoItem.qml, nebula/ui/components/VPNConnectionStability.qml, nebula/ui/components/VPNExternalLinkListItem.qml, nebula/ui/components/VPNFocusOutline.qml, nebula/ui/components/VPNLoader.qml, nebula/ui/components/VPNMainImage.qml, nebula/ui/components/VPNPanel.qml, nebula/ui/components/VPNPopupButton.qml, nebula/ui/components/VPNRadioDelegate.qml, nebula/ui/components/VPNUIStates.qml, nebula/ui/components/forms/VPNComboBox.qml, src/apps/vpn/ui/screens/devices/VPNDevicesListHeader.qml, src/apps/vpn/ui/screens/getHelp/giveFeedback/GiveFeedbackRadioDelegate.qml, src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededIAP.qml, src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededWeb.qml
This fixes a few obviously incorrect custom property types in our QML files following this comment thread (https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5301#discussion_r1054825472). Full audit still needed.
=> First pass QML custom property type cleanup 

nebula/ui/components/VPNLoader.qml
=> VPN-1344 Fix Unable to assign [undefined] to QString

nebula/ui/components/VPNTabNavigation.qml
Fix VPN-3553 - Fix tab navigation header on desktop
https://user-images.githubusercontent.com/22355127/209454891-7ddc3b58-30cc-4f7a-8372-29897aa8d126.mov
=> VPN-3553: Fix tab nav glitching

src/apps/vpn/commands/commandui.cpp, src/apps/vpn/qmlengineholder.cpp, src/apps/vpn/qmlengineholder.h
This is a rebase of https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5237
=> Fix segfault on QML load error - VPN-2403

src/apps/template/appconstants.h, src/apps/vpn/addons/manager/addonmanager.cpp, src/apps/vpn/appconstants.h, src/apps/vpn/appsettingslist.h, src/shared/constants.h, src/shared/loghandler.cpp, src/shared/platforms/linux/linuxcryptosettings.cpp, src/shared/platforms/windows/windowscryptosettings.cpp
=> Modules 07: no VPN references in src/shared

src/apps/vpn/notificationhandler.cpp, src/apps/vpn/platforms/android/androidnotificationhandler.cpp, tests/functional/testServers.js, translations/strings.yaml
Remove the server country name from the notification to reduce verbosity
https://mozilla-hub.atlassian.net/browse/VPN-3514
=> Add yaml strings and update notification handler cpp

CMakeLists.txt, version.pri
verion bump from 2.13.0 to 2.14.0
=> verion bump from 2.13.0 to 2.14.0

nebula/ui/components/VPNConnectionInfoContent.qml
Cherry pick [this](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5442) PR to 2.13
https://mozilla-hub.atlassian.net/browse/VPN-3639
=> Only show city name for multihop server names (#5442)

src/apps/vpn/websocket/websockethandler.cpp
Turns out we are recording more events than necessary. Oops.
=> No ticket - Only record websocket connection attempt telemetry when there is an attempt

.github/workflows/linux.yaml
They run on taskcluster now.
Fixes [VPN-3707](https://mozilla-hub.atlassian.net/browse/VPN-3707)
=> Remove Ubuntu builds from GH Actions

src/apps/vpn/platforms/windows/windowspingsender.cpp, src/shared/platforms/windows/windowsutils.cpp
That's refed in line 39, but not defined.
=> Windows Fix Build Issues

src/apps/vpn/ui/screens/devices/ViewDevices.qml
=> Fix VPN-3638: Don't reassign value to non-existent 'rightTitle' property

src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededWeb.qml
=> Fix VPN-3390: Remove markup from Accessible.name

addons/tutorial_04_split_tunneling/manifest.json, src/apps/vpn/apppermission.cpp
Matt: this seems to work fine with the tutorial 04.
=> Revert app-permission settings when the tutorial is completed

src/apps/vpn/localizer.cpp, src/apps/vpn/localizer.h, src/apps/vpn/ui/screens/settings/ViewLanguage.qml, tests/unit/testlocalizer.cpp
In this screen, I just set RTL values for testing:
=> Support RTL languages in settings - VPN-3737

src/apps/vpn/inspector/inspectorhandler.cpp
=> Fix inspector typo

.taskcluster.yml
Taskcluster 47 renamed the roles used for release-related events.
=> Update scope for github-release decision task

tests/functional/setupVpn.js
=> Better shutdown procedure for functional tests

.github/workflows/linters.yaml
Makes it easier to read the checks in the branch restrictions.
=> Add name to linter

src/apps/vpn/tasks/controlleraction/taskcontrolleraction.h
Mark deletePolicy() as override since it is overwriting a method from the base class `Task` to get rid of the compiler warning noise.
```In file included from /Users/mozilla/Desktop/mozilla-vpn-client/src/apps/vpn/tasks/controlleraction/taskcontrolleraction.cpp:5:
/Users/mozilla/Desktop/mozilla-vpn-client/src/apps/vpn/tasks/controlleraction/taskcontrolleraction.h:34:24: warning: 'deletePolicy' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual DeletePolicy deletePolicy() const  { return NonDeletable; }
^
/Users/mozilla/Desktop/mozilla-vpn-client/src/shared/task.h:37:24: note: overridden virtual function is here
virtual DeletePolicy deletePolicy() const { return Deletable; }
^
In file included from …
```
=> Mark `deletePolicy()` as override

.taskcluster.yml
Patch to the main branch which switches the [PR policy](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/b4e0378ed14e75b27a4ae80213b5104d9221852a/.taskcluster.yml#L6) to `public_restricted`.
Issue #5608
=> Issue #5608 - Update Github PR policy to public_restricted

src/apps/vpn/appconstants.h, src/apps/vpn/captiveportal/captiveportal.h, src/apps/vpn/captiveportal/captiveportalrequest.cpp, src/apps/vpn/mozillavpn.cpp, src/shared/constants.cpp, src/shared/networkmanager.cpp, src/shared/networkmanager.h, src/shared/settingslist.h, tests/functional/constants.js, tests/functional/servers/captivePortalServer.js, tests/functional/servers/guardian_endpoints.js, tests/functional/setupVpn.js, tests/functional/setupWasm.js, tests/unit/testaddonapi.cpp, tests/unit/testipaddresslookup.cpp, tests/unit/testipfinder.cpp, tests/unit/testnetworkmanager.cpp, tests/unit/testreleasemonitor.cpp, tests/unit/testtasks.cpp, wasm/test.html
=> Localhost requests only in functional tests - VPN-3935

tests/auth/CMakeLists.txt, tests/qml/CMakeLists.txt
=> Fix unit-tests on main - VPN-3977

src/apps/vpn/connectionhealth.cpp, src/apps/vpn/pinghelper.cpp, src/apps/vpn/pingsender.h, src/apps/vpn/serverlatency.cpp
=> Fix crash on linux in the pingsenders - VPN-3572

.github/workflows/test_unit.yaml
Trying a few things to see if we can get the Windows unit tests to build and run a little faster.
Github #5583 ([VPN-3847](https://mozilla-hub.atlassian.net/browse/VPN-3847))
[VPN-3847]: https://mozilla-hub.atlassian.net/browse/VPN-3847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Build Windows unit tests with Ninja

addons/message_whats_new_v2.13/manifest.json, addons/message_whats_new_v2.13/setDate.js
Figma: https://www.figma.com/file/Disx2dX7tw81NQIN39BrYo/In-app-Messaging?node-id=1515%3A5328&t=qaBi1ZXEt4QIyapE-0
=> VPN-3703 - Implement What's New messsage for 2.13

addons/message_update_v2.13/enable.js, addons/message_update_v2.13/getHelp.js, addons/message_update_v2.13/manifest.json, addons/message_update_v2.13/update.js, addons/message_update_v2.13/updateWeb.js
Figma: https://www.figma.com/file/Disx2dX7tw81NQIN39BrYo/In-app-Messaging?node-id=1515%3A5359&t=iW656xyySoz91GQ4-0
=> VPN- 3704 Implement 2.13 update message

src/apps/vpn/appsettingslist.h, src/apps/vpn/commands/commandui.cpp, src/shared/localizer.cpp
Currently we go in staging mode in the command ui but it's too late to have all the strings in WASM.
=> WASM client in staging mode via settings

vpnglean/CMakeLists.txt, vpnglean/glean_parser_ext/rust.py, vpnglean/include/glean/counter.h, vpnglean/include/glean/metrictypes.h, vpnglean/src/cpp/counter.cpp, vpnglean/src/ffi/counter.rs, vpnglean/src/ffi/mod.rs, vpnglean/vpnglean.pri
~This is based on #5523. The only actually new commit os 4d3a7ec40b49dd54c568c52b299ae87cd45d23d8.~
=> VPN-3673 - Implement counter metric type on vpnglean

glean/CMakeLists.txt, ios/adjust/CMakeLists.txt, lottie/CMakeLists.txt, src/CMakeLists.txt, src/apps/vpn/cmake/sources.cmake, src/shared/sources.cmake, translations/CMakeLists.txt, vpnglean/CMakeLists.txt, vpnglean/ios.cmake
- Type conversion warnings were showing up as errors for some compilers
-N/A
=> Chore: Ignore type conversions

addons/message_update_v2.13/enable.js
~Draft because still untested.~ WFM. 
A unit test would have been nice, but there is urgency here and that is proving to not be the simplest from my work on #5743.
=> VPN-4034 - Show download button for v2.13 update message on Windows

src/apps/vpn/appfeaturelist.h
Everything Required from a Code-Perspective Landed, let's enable sentry on supported plattforms
=> Chore: Flip Sentry On

.dictionary, docs/Command-line-interface.md
I was too hasty in PR #5817 and I missed that we have a wiki page and docs for the CLI interface. So let's make sure they are up to date too.
Github PR #5817
Github issue #3165 ([VPN-1988](https://mozilla-hub.atlassian.net/browse/VPN-1988))
[VPN-1988]: https://mozilla-hub.atlassian.net/browse/VPN-1988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update CLI docs to describe the wgconf command

CMakeLists.txt, version.pri
=> version bump to 2.15

scripts/utils/generate_ts.sh
=> Exclude non-vpn apps when generating strings for translations - VPN-4076

android/daemon/tunnel/libwg-go/Makefile, scripts/android/cmake.sh
=> VPN-3880 and Nits:  Better Android compile experience

src/apps/vpn/cmake/macos.cmake, taskcluster/ci/build/macos.yml, taskcluster/scripts/build/macos_build.sh, taskcluster/scripts/requirements.txt
This PR add's symbol generation and uploading to sentry for the Macos Task :)
=> VPN-3159: Mac/Sentry: Upload debug symbols :) 

tests/functional/helper.js, tests/functional/queries.js, tests/functional/testServerSearch.js
Add functional tests to verify search in serverlist views
[PSP-531](https://mozilla-hub.atlassian.net/browse/PSP-531)
[PSP-531]: https://mozilla-hub.atlassian.net/browse/PSP-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add tests to verify search functionality in serverlist views

.github/codecov.yml
Chore: temp remove code cov comment
=> Chore: temp remove code cov comment

.github/workflows/linters.yaml, scripts/utils/generate_ts.sh
The linter workflow could run a little faster if we used the native Qt6 packages instead of `aqt`, so let's give it a try.
=> Chore: Update linter workflow to ubuntu-jammy runner.

.gitignore, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt, android/vpnClient/build.gradle, android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNUtils.kt
This was accidentally broken by https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5480/files#diff-db0ecec3f7e1a3df82d4c1d31cde4b3a640f05e1f799e78f156c51d87ff48a56
=> VPN-4158 - Fix Glean on Android

taskcluster/ci/config.yml
Migrate 2012 tasks to Azure
https://firefox-ci-tc.services.mozilla.com/tasks/groups/dmlmwi6yRZ6pQw_XYJ78xg
https://bugzilla.mozilla.org/show_bug.cgi?id=1801167
=> Bug 1801167 - migrate 2012 tasks to Azure

taskcluster/ci/config.yml
(cherry picked from commit a8ad471c01eb2218d6e8f58c587761fd614208d6)
=> Bug 1801167 - migrate 2012 tasks to Azure (#6028)

addons/message_update_v2.14/manifest.json, addons/message_whats_new_v2.14/manifest.json
Both issues were fixed in the update message during review, but not in the what's new one addon.
=> Fix typos (capitalization) in WN 2.14 message

addons/guide_12_multi_account_containers/manifest.json
This PR updates the strings in the guide_12_multi_account_containers/manifest.json and removes the platform condition.
VPN-4036
=> VPN-4036: Update MAC addon manifest

src/apps/vpn/ui/screens/settings/ViewPrivacy.qml
This listens to VPNController.state and resets the warning height accordingly.
VPN-4189
=> Fix VPN-4189 - UI issues in iOS disconnect warning

tests/functional/setupVpn.js, tests/functional/setupWasm.js
Pulled out of https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5892
=> Chore - Print functional test logs if test didn't run at all

qtglean/ios.cmake
You'll just have to trust me that this works, because CI doesn't run it yet.
=> VPN-4235 - Fix ios.cmake Glean script

src/apps/vpn/cmake/macos.cmake
The `Makefile` provided in the `wireguard-go` repository builds artifacts in the source directory, which can lead to state carrying between builds, and managed to introduce bugs in some of our CI builds. To try and avoid this in the future we should fix this so that build artifacts are *only* generated somewhere under `${CMAKE_BINARY_DIR}`
Github issue #5886 ([VPNB-4109](https://mozilla-hub.atlassian.net/browse/VPN-4109))
=> VPN-4109: Build wireguard-go in the binary dir

tests/functional/testAddons.js, tests/functional/testAuthenticationInBrowser.js, tests/functional/testCaptivePortal.js, tests/functional/testConnection.js, tests/functional/testContactUs.js, tests/functional/testHeartbeat.js, tests/functional/testIpInfo.js, tests/functional/testMultihop.js, tests/functional/testNavigation.js, tests/functional/testOnboarding.js, tests/functional/testServers.js, tests/functional/testSettings.js, tests/functional/testSubscription.js, tests/functional/testTelemetryView.js, tests/functional/testTutorials.js, tests/functional/testUnsecuredNetworkAlert.js
Currently, we have numerous asserts that check whether a condition is true or false. Updating these asserts to provide actual values vs expected values for debugging
=> Test Chore: updating asserts to provide actual values

taskcluster/scripts/build/ios_build_no_adjust.sh, taskcluster/scripts/build/macos_build.sh, taskcluster/scripts/toolchain/bundle_qt_ios.sh, taskcluster/scripts/toolchain/compile_qt_6_mac.sh
It's fine to set this for debugging purposes but echoing is bad as we pass things into the client as cmake args :)
=> VPN-4233 Taskcluster: No more echoing of shell commands

scripts/tooltool.py
This is a simple update of the tooltool.py script, copied from https://github.com/mozilla-releng/tooltool. It should be a drop-in replacement for the old version.
This update includes several tooltool changes, but I am mostly motivated by the fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1806899.
=> update tooltool client

nebula/ui/components/MZClickableRow.qml
Addresses [this](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6246#discussion_r1129622148) review comment.
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6246#discussion_r1129622148
=> Remove VPN specific comment

src/apps/vpn/settingswatcher.cpp
It can happen that the task is not deleted immediately. Let's allow new changes immediately before triggering the TaskControllerAction task.
=> Make the silent-switch operation faster - VPN-4295

qtglean/glean_parser_ext/run_glean_parser.py, qtglean/pings.yaml
Adds new ping. Have tested this by submitting the empty ping, can see on the debug ping viewer.
https://mozilla-hub.atlassian.net/browse/VPN-4095
=> vpn-4095 add ping

src/apps/vpn/cmake/macos.cmake
Removing a lingering FIXME in the MacOS build in order to generate `wireguard-go` as a Universal binary.
Github issue #286 ([VPN-82](https://mozilla-hub.atlassian.net/browse/VPN-82))
[VPN-82]: https://mozilla-hub.atlassian.net/browse/VPN-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-82: Generate universal builds of wireguard-go

CMakeLists.txt, version.pri
- Bump version from 2.15 to 2.16
=> version bump to 2.16

nebula/nebula.pri
Adds utils.qrc to nebula.pri to fix the iOS qmake build which was <not> working on my machine. 
=> Add utils to nebula.pri

addons/message_update_v2.15/manifest.json
One string with "App exclusions" was updated in review in #6405, but not the other.
=> Fix inconsistency (App exclusions) in 2.15 what's new content

src/apps/vpn/translations/strings.yaml, src/apps/vpn/ui/screens/home/controller/ControllerView.qml
- Adds new accessible label strings for the speed test and connection information/ip panel buttons
- Removes old strings
VPN-3680
=> VPN-3680: Update controller view strings

addons/guide_03_adding_and_removing_devices/manifest.json
update addon string
https://mozilla-hub.atlassian.net/browse/VPN-4061
=> VPN-4061 Update the instructions on the VPN tips & tricks for "how to add and remove devices"

CODEOWNERS
As discussed in retro / eng meeting.
=> Chore: Remove Sarah from CODEOWNERS

taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
Previously this was pointing at the candidates dir, even when running the ship-client phase.
This change fixes the wrong build dirs being linked in the `release-notify` message that gets posted to Slack.
- [ x ] My code follows the style guidelines for this project
- [ x ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ x ] I have performed a self review of my own code
- [ x ] I have commented my code PARTICULARLY in hard to understand areas
- [ x ] I have added thorough tests where needed
=> ci: use the proper beetmover destination on 'ship-client' phase

src/apps/vpn/appfeaturelist.h, tests/functional/queries.js, tests/functional/testServerSearch.js, tests/functional/testServers.js
- Turn feature flags on for Recommended Servers and Server Connection Score
[VPN-4438: Flip recommended servers and latency indicator feature flags on](https://mozilla-hub.atlassian.net/browse/VPN-4438)
=> VPN-4438: Turn on recommended servers and latency indicators

src/shared/platforms/android/androidcommons.cpp
=> VPN-4476 - Fix share logs on 2.15

android/common/src/main/java/org/mozilla/firefox/qt/common/Utils.kt, android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNUtils.kt, src/shared/platforms/android/androidcommons.cpp
=> VPN-4476 Fix share logs

.gitignore
Really found those handy :) 
Since user presets should not be checked in, let's ignore them
https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html
=> Nit: Ignore CMakeUserPresets.json

src/apps/vpn/ui/screens/initialize/ViewInitialize.qml
=> VPN-4487: Logo missing after sign out

nebula/ui/components/MZAvatar.qml, nebula/ui/components/MZUIStates.qml, nebula/ui/components/MZUserProfile.qml, src/apps/vpn/ui/screens/home/controller/ControllerImage.qml, src/apps/vpn/ui/screens/home/controller/ControllerView.qml, src/apps/vpn/ui/sharedViews/ViewUpdate.qml
I have been running into a few QML warnings in the logs, most of which appear to be fallout from the ongoing App/Module refactoring, and I felt like cleaning them up.
=> Chore: Address some QML warnings

qtglean/include/glean/event.h, qtglean/include/glean/timingdistribution.h, qtglean/src/cpp/timingdistribution.cpp, src/apps/vpn/apppermission.cpp, src/apps/vpn/commands/commandexcludeip.cpp, src/apps/vpn/models/recentconnections.cpp, src/apps/vpn/models/recommendedlocationmodel.cpp, src/apps/vpn/models/servercity.cpp, src/apps/vpn/models/servercity.h, src/apps/vpn/serverlatency.cpp, src/apps/vpn/serverlatency.h, src/apps/vpn/telemetry.h, src/shared/frontend/navigationbarmodel.cpp, src/shared/frontend/navigationbarmodel.h, src/shared/languagei18n.cpp
Just making a pass through the project to clean up any simple compiler warnings that appear now that we are officially building with CMake.
This does leave a few non-trivial warnings to fix related to our Swift integration, but those require some significant refactoring to fix.
Github issue #3481 ([VPN-2188](https://mozilla-hub.atlassian.net/browse/VPN-2188))
[VPN-2188]: https://mozilla-hub.atlassian.net/browse/VPN-2188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore: Tidy up iOS compile warnings

tests/functional/testAddons.js
- Fixes a functional test that seems to have mistakenly been uplifted to 2.15 and is causing failures on the 2.15 release branch
=> 2.15 fix addons functional test

tests/functional/queries.js, tests/functional/testMultihop.js
Bring back the commented out multihop tests and get them running again. Please only review tests that are not marked with `it.skip(...)` (aka the last 3 tests are not yet ready).
https://mozilla-hub.atlassian.net/browse/VPN-3205
=> VPN-3205 Resurrect the multi-hop functional tests from the dead

nebula/ui/components/inAppAuth/MZInAppAuthenticationInputs.qml
https://user-images.githubusercontent.com/22355127/235540280-46109a56-c001-41b6-8313-43f8534d4daf.mov
VPN-3389
=> VPN-3389: Fix no-show verification code error message on ios

android/build.gradle, android/common/build.gradle, android/common/src/main/java/org/mozilla/firefox/qt/common/CoreApplication.kt, android/daemon/build.gradle, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt, android/gradle/wrapper/gradle-wrapper.properties, android/qtglean/build.gradle, android/vpnClient/build.gradle, src/apps/vpn/platforms/android/androidvpnactivity.cpp, src/apps/vpn/platforms/android/androidvpnactivity.h, src/shared/glean/mzglean.cpp, src/shared/glean/mzglean.h
I have tested this with a sample ping from the daemon and it works i.e. it is able to submit pings and record metrics.
=> VPN-4706, VPN-4709 - Initialize Glean instance from the Android Daemon

docs/qtglean.md, src/apps/vpn/telemetry/metrics.yaml, src/apps/vpn/telemetry/metrics_deprecated.yaml, src/apps/vpn/telemetry/pings.yaml, src/shared/telemetry/metrics_deprecated.yaml, src/shared/telemetry/pings_deprecated.yaml
Fixes VPN-891
Use vpn-telemetry@mozilla.com that folks can subscribe to and the whole org can look at if needed as opposed to individual email addresses.
=> VPN-891 - Replace individual email addresses with team

docs/dev-setup/macos.md
So the user doesn't have to scroll back and forth to find what command we're referring to.
=> Explicitly include the command needed to build XCode solution

.dictionary, docs/rfcs/0001-rfc-process.md
This PR proposes the adoption of an RFC process and submits an inaugural RFC describing the rationale for doing so. The goal here is to get alignment on adopting the process. We can follow up with an RFC template, additional notes on process, and modify any part of this as needed going forward.
=> [RFC] Proposal to adopt an RFC process

ios/networkextension/CMakeLists.txt, qtglean/CMakeLists.txt, qtglean/build.rs, qtglean/ios.cmake, qtglean/src/lib.rs, scripts/cmake/rustlang.cmake, src/apps/vpn/cmake/ios.cmake, src/apps/vpn/platforms/ios/iosconstants.swift, src/apps/vpn/platforms/ios/ioscontroller.swift, src/apps/vpn/platforms/ios/iostunnel.swift, src/apps/vpn/platforms/ios/iostunnelmanager.swift, src/apps/vpn/platforms/ios/iostunnelmessage.swift, src/shared/glean/mzglean.cpp, src/shared/platforms/ios/iosgleanbridge.h, src/shared/platforms/ios/iosgleanbridge.mm, src/shared/platforms/ios/iosgleanbridge.swift
~Draft as it is still missing the synchronization of uploadEnabled between netext and main app.~
This is ready for review.
Note: I suggest reviewing this commit by commit.
=> VPN-4707 - Initialize Glean on the iOS network extension

qtglean/Cargo.lock
I probably forgot to commit this.
=> Chore - Commit updates to cargo.lock

android/daemon/build.gradle, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/ConnectionHealth.kt, ios/networkextension/CMakeLists.txt, qtglean/CMakeLists.txt, qtglean/build.rs, qtglean/ios.cmake, qtglean/src/lib.rs, scripts/cmake/rustlang.cmake, src/apps/vpn/cmake/ios.cmake, src/apps/vpn/platforms/ios/iosconstants.swift, src/apps/vpn/platforms/ios/ioscontroller.swift, src/apps/vpn/platforms/ios/iostunnel.swift, src/apps/vpn/platforms/ios/iostunnelmanager.swift, src/apps/vpn/platforms/ios/iostunnelmessage.swift, src/apps/vpn/telemetry/metrics.yaml, src/apps/vpn/telemetry/metrics_deprecated.yaml, src/shared/glean/mzglean.cpp, src/shared/platforms/ios/iosgleanbridge.h, src/shared/platforms/ios/iosgleanbridge.mm, src/shared/platforms/ios/iosgleanbridge.swift
Both are QA not necessary tasks. I would like to cherry pick these into 2.16 so we can start getting data ASAP.
=> Chore: Cherry pick Glean on the netext + deamon health metrics into 2.16

android/daemon/build.gradle, src/apps/vpn/cmake/android.cmake
=> Android: no more build lottery

src/apps/vpn/commands/commandui.cpp, src/apps/vpn/platforms/ios/iostunnelmanager.swift, src/shared/platforms/ios/iosgleanbridge.swift
=> VPN-5035 - Always execute TunnelManager.initialize completion handler

src/apps/auth_tests/appconstants.h, src/apps/vpn/appconstants.h, wasm/main.js
- Update the URL used for staging
N/A
=> Update staging url

src/apps/vpn/ui/screens/ScreenInitialize.qml
Cherry-picks #7208 to release branch
=> Cherry-pick VPN-5026: Fix reference error in ScreenInitialize.qml (#7208)

src/apps/auth_tests/appconstants.h, src/apps/vpn/appconstants.h, wasm/main.js
Cherry picking the staging URL update to release branch, to allow some tests to pass.
N/A
=> cherry pick to 2.16 release branch: Update staging url

src/apps/vpn/appsettingslist.h, src/apps/vpn/controller.cpp, src/apps/vpn/controller.h, src/apps/vpn/telemetry.cpp, src/apps/vpn/telemetry.h, src/apps/vpn/telemetry/pings.yaml, src/apps/vpn/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml
- Uplift eeab93c to 2.16 (PR: #7216)
[VPN-4443: Session ping: Create session ping submissions triggers](https://mozilla-hub.atlassian.net/browse/VPN-4443)
=> VPN-4443: VPN session pings (#7096)

docs/dev-setup/index.md
=> Update windows hyperlink

nebula/ui/components/MZDropShadowWithStates.qml, src/apps/vpn/ui/screens/home/controller/ControllerImage.qml, src/apps/vpn/ui/screens/home/controller/ControllerView.qml, src/apps/vpn/ui/screens/home/controller/VPNToggle.qml
Factor in check subscription state in the UI
https://mozilla-hub.atlassian.net/browse/VPN-5024
=> VPN-5024 Handle StateCheckSubscription in UI

nebula/ui/components/MZDropShadowWithStates.qml, src/apps/vpn/ui/screens/home/controller/ControllerImage.qml, src/apps/vpn/ui/screens/home/controller/ControllerView.qml, src/apps/vpn/ui/screens/home/controller/VPNToggle.qml
cherry-pick from https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7305
https://mozilla-hub.atlassian.net/browse/VPN-5024
=> VPN-5024 Handle StateCheckSubscription in UI (#7305)

docs/dev-setup/ios.md, scripts/macos/conda_setup_qt.sh
Small touch up from https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7196/
Improve formatting, and I think that Android reference is an artifact from the Android file. Also, we don't need to make the folder before building into it.
N/A
=> iOS: Improve readme and script output

nebula/ui/components/MZCheckBoxRow.qml, nebula/ui/components/MZHeadline.qml, nebula/ui/components/MZSubtitle.qml, nebula/ui/components/MZTextBlock.qml, nebula/ui/components/inAppAuth/MZInAppAuthenticationBase.qml, nebula/ui/components/inAppAuth/MZInAppAuthenticationInputs.qml, nebula/ui/components/navigationBar/MZBottomNavigationBar.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationSignUp.qml, src/apps/vpn/ui/screens/ScreenPostAuthentication.qml, src/apps/vpn/ui/screens/getHelp/contactUs/ViewContactUsForm.qml, src/apps/vpn/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml, src/apps/vpn/ui/screens/messaging/ViewMessage.qml, src/apps/vpn/ui/screens/settings/ViewAboutUs.qml, src/apps/vpn/ui/screens/settings/ViewLanguage.qml, src/apps/vpn/ui/screens/settings/ViewPrivacy.qml, src/apps/vpn/ui/screens/settings/ViewSubscriptionManagement/SubscriptionManagementItem.qml, src/apps/vpn/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
=> [Uplift] VPN-4913: Fix various UI issues with Qt 6.4

src/apps/vpn/ui/screens/ScreenTelemetryPolicy.qml
Uplift of #7372
[VPN-4913: Investigate and fix QML layout issues in Qt 6.4.3](https://mozilla-hub.atlassian.net/browse/VPN-4913)
=> [Uplift] VPN:4913: Fix data collection screen layout (#7372)

src/apps/vpn/ui/authenticationInApp/ViewAuthenticationSignIn.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml
- Uplifts #7376
[VPN-5143: [Qt 6.4] Layout issues in auth views](https://mozilla-hub.atlassian.net/browse/VPN-5143)
=> [Uplift] VPN-5143: Fix re-auth page layout

taskcluster/ci/build/windows.yml, taskcluster/ci/fetch/kind.yml, taskcluster/scripts/build/windows.ps1
This cherry-picks #7347 to releases/2.16. 
Please see #7347 for important pictures.
=> [CI] WIP fix 2.15.1 (#7347)

android/common/build.gradle, android/common/src/main/java/org/mozilla/firefox/qt/common/Prefs.kt, android/common/src/main/java/org/mozilla/firefox/qt/common/SettingsKeystore.kt, android/daemon/build.gradle, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/BootReceiver.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt, src/apps/unit_tests/mocsentryadapter.cpp, src/apps/vpn/cmake/android.cmake, src/shared/platforms/android/androidcryptosettings.cpp, src/shared/platforms/android/sources.cmake
- Fix test code
- Add cryptosettings
- Pile of shame added!
=> VPN-5018 enable cryptosettings for android

taskcluster/scripts/build/windows_clang_cl.ps1
=> Fix windows release CI

scripts/cmake/osxtools.cmake, scripts/macos/conda_setup_qt.sh, src/apps/vpn/cmake/macos.cmake
This reverts commit 00d37766f96d40d93930789083953b44618cac8a.
=> Revert "Support QT using shared-libs (#7406)"

.github/workflows/ppa-automation.yaml
Uplifting https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7417 to the 2.15.2 release branch.
=> Uplift 7417 to release branch

ios/app/WireGuard-Bridging-Header.h, ios/networkextension/WireGuardNetworkExtension-Bridging-Header.h, src/apps/vpn/cmake/ios.cmake, src/apps/vpn/platforms/ios/iosconstants.swift, src/apps/vpn/platforms/ios/ioscontroller.mm, src/apps/vpn/platforms/ios/ioscontroller.swift, src/apps/vpn/platforms/ios/iosglue.mm, src/apps/vpn/platforms/ios/ioslogger.h, src/apps/vpn/platforms/ios/ioslogger.mm, src/apps/vpn/platforms/ios/ioslogger.swift, src/apps/vpn/platforms/ios/iostunnel.swift, src/apps/vpn/platforms/ios/iostunnelmanager.swift, src/shared/loghandler.cpp, src/shared/platforms/ios/iosgleanbridge.swift
I built this on top of #7256. Will rebase once that merged.
This PR starts at 59aa9126e12157fb9b7b4899c066007196b60e71.
=> VPN-4921 - Get all iOS logs to show up on console and log file

android/common/src/main/java/org/mozilla/firefox/qt/common/Utils.kt, android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNUtils.kt, src/shared/platforms/android/androidcommons.cpp
I based this on the release branch, so opening this first PR pointing there. I'll cherry pick into the main branch later.
=> VPN-5049 - Move sharePlainText back to VPNUtils

.github/workflows/test_lottie.yaml, .github/workflows/test_unit.yaml
That's a bit old and need's manual maintaining, let's use the Taskcluster Toolchain.
=> Can we archive the Qt-Static mac repo?

extension/bridge/src/main.rs, tests/nativemessaging/CMakeLists.txt, tests/nativemessaging/helper.cpp, tests/nativemessaging/helper.h, tests/nativemessaging/test_illegal_invoke.cpp, tests/nativemessaging/test_illegal_invoke.h
=> VPN-5009 Webext add asserts and tests

src/apps/vpn/ui/screens/ScreenTelemetryPolicy.qml
Cherry-picking #7358 to 2.16 release branch.
VPN-5059
=> Cherry-pick: Fix VPN-5059- Wrap privacy policy link (#7358)

nebula/ui/components/forms/MZTextField.qml
Cherry picking this commit from `main` to fix a crash with special characters: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7546
=> Reset accessibility focus (#7546)

src/apps/unit_tests/mocsentryadapter.cpp, src/shared/sentry/sentryadapter.cpp, src/shared/sentry/sentryadapter.h
=> [Cherrypick] Sentry: Report QML status (#7203)

linux/debian/mozillavpn.postinst, linux/debian/mozillavpn.postrm, linux/debian/mozillavpn.preinst
Cherry pick of PR #7548 to the `releases/2.16.0` branch.
Github issue #7403 ([VPN-5159](https://mozilla-hub.atlassian.net/browse/VPN-5159))
Github issue #7404 ([VPN-5160](https://mozilla-hub.atlassian.net/browse/VPN-5160))
[VPN-5159]: https://mozilla-hub.atlassian.net/browse/VPN-5159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-5160]: https://mozilla-hub.atlassian.net/browse/VPN-5160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-pick: Fix systemd service launch on installation (#7548)

src/apps/vpn/controller.cpp, src/apps/vpn/controller.h, src/apps/vpn/telemetry.cpp
#7565 was PR for main. Uplift that to 2.16.0
https://mozilla-hub.atlassian.net/browse/VPN-5222
=> Uplift VPN-5222 to 2.16.0 release branch

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNActivity.java, src/apps/vpn/platforms/android/androidvpnactivity.cpp, src/apps/vpn/platforms/android/androidvpnactivity.h
=> VPN-5016 - [Android] Disable screenrecoding on auth screens

addons/message_whats_new_v2.15/manifest.json, addons/message_whats_new_v2.15/setDate.js
This was deleted by mistake, 2.15 is the current release.
=> VPN-5261 - Bring back the 2.15 whats new message

.dictionary, docs/rfcs/0003-rfc-controller_refactor.md
RFC to breakdown how we want to undertake the `Controller` refactor work.
Friday July 14th (7/14/2023)
https://mozilla-hub.atlassian.net/browse/VPN-4918
=> [RFC] VPN-4918 Refactor Controller and move connectivity logic to Connection Manager

addons/message_update_v2.16/manifest.json
Disable upgrade message. This is is so we can release addons. After it is released, this will be reverted.
If for some reason any clients out there are running version 1.0, they will see this message.
N/A
=> disable upgrade message

nebula/ui/components/MZCollapsibleCard.qml, src/apps/vpn/ui/screens/settings/appPermissions/AppPermissionsList.qml, src/apps/vpn/ui/screens/settings/appPermissions/ViewAppPermissions.qml
- Uplift #7619 to 2.16
[VPN-5275: Layout/UI issues in the client (Qt 6.4.2)](https://mozilla-hub.atlassian.net/browse/VPN-5275)
=> VPN-5275: Fix app permissions and collapsible card layouts (#7619)

.github/workflows/ppa-automation.yaml
Cherry-pick of PR #7417 to `releases/2.16.0`
=> Cherry-pick: Upload PPA workflow artifacts, even if dput fails. (#7417)

CMakeLists.txt
Version bump for 2.16.1 dot release.
=> Bump version for 2.16.1 dot release

docs/Accessibility - Principles and Requirements.md, docs/Accessibility - Testing Resources.md
Document that outlines Accessibility Principles and Requirements for VPN Client
[VPN-4923](https://mozilla-hub.atlassian.net/browse/VPN-4923), [Github issue 7090](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/7090)
[VPN-4923]: https://mozilla-hub.atlassian.net/browse/VPN-4923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-4923: Accessibility Principles and Requirements doc

taskcluster/ci/beetmover/kind.yml
Looking at : https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/taskcluster/ci/build/android.yml#L135
It seems i mis-spelled the artifact name 😓
=> Fix Beetmover for Android-x64

tools/inspector/views/view-ui.js
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/9611612/8f76f0e9-620a-4578-b110-57d8b319d5d3
=> Make Inspector Live-View Sticky

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNUtils.kt
=> Shh, nobody noticed

android/buildSrc/src/main/kotlin/Config.kt
=> Bump Target SDK

android/buildSrc/src/main/kotlin/Config.kt
Bumping https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7809/
=> Uplift #7809 to 2.16.2 release branch

CMakeLists.txt
=> version bump to 2.16.2

android/AndroidManifest.xml
=> Uplift 7822: Remove AD-ID permission

src/shared/tasks/sentry/tasksentry.cpp
=> Remove leaking of tasksentry

env.yml, taskcluster/ci/fetch/kind.yml, taskcluster/ci/toolchain/qt.yml, taskcluster/scripts/toolchain/bundle_qt_ios.sh
- Tie the qt-ios toolchain task to the env.yml
- Update QT
=> [Qt 6.5.1] Update QT - for Android, Linux, OsX, iOS

tests/functional/testAddons.js
The only big change here is removing the `.only`, everything else is formatting changes by the linter.
The `.only` was added in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6803, we believe it was an artifact from local testing.
N/A
=> Enable full file of functional tests for addons

taskcluster/ci/build/macos.yml, taskcluster/ci/fetch/kind.yml
Cherry-picking this to resolve issues outlined in VPN-5144 which have resurfaced in main since reverting the bump to Qt 6.5.1 yesterday.
=> 🍒 Pin Qt Toolchain artifact (#7411)

addons/message_whats_new_v2.17/manifest.json, addons/message_whats_new_v2.17/setDate.js
- Adds "What's new" message for 2.17
*Note: The list of new features is an over-estimation of what we think will make it into the release so that we have translations available if needed. This list will most likely be shortened once we have a final call on what features will be in the release.
[VPN-5338: Implement the 'What's New' message for 2.17](https://mozilla-hub.atlassian.net/browse/VPN-5338)
=> VPN-5338: 2.17 whats new message

.github/workflows/linters.yaml, src/controller.cpp, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/shared/mfbt/mozilla/CheckedInt.h
We are on version 11 which is 3 years old and we should update.
https://mozilla-hub.atlassian.net/browse/VPN-5490
=> VPN-5490 Update clang format to version 16.0.3

.github/workflows/gh_pages.yaml
Having this on every commit on every pr is burning though our rate limits :), it's rarely touched so let's skip it.
=> Nit: Let's not generate the branch file on pr's

addons/message_update_v2.17/manifest.json, addons/message_whats_new_v2.17/manifest.json
[VPN-5499: Remove unimplemented changes from 2.17 Update / What's new messages](https://mozilla-hub.atlassian.net/browse/VPN-5499)
=> VPN-5499: Remove unimplemented content from 2.17 messaging

.github/workflows/i18n_update.yaml
Fix another outdated translation directory
=> fix translation for branch

.github/workflows/i18n_update.yaml
Uplift https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8008/ to release branch.
=> Uplift PR 8008: fix translation

src/telemetry/metrics.yaml
Uplifts https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8027 to the release branch.
https://mozilla-hub.atlassian.net/browse/VPN-5479?focusedCommentId=730515
=> Uplift PR 8027: VPN-5479 part 2

nebula/ui/components/MZStepNavigation.qml, nebula/ui/components/MZStepProgressBar.qml, src/mozillavpn.cpp, src/ui/screens/ScreenOnboarding.qml, src/ui/screens/onboarding/OnboardingDataSlide.qml, src/ui/screens/onboarding/OnboardingDevicesSlide.qml, src/ui/screens/onboarding/OnboardingPrivacySlide.qml, src/ui/screens/onboarding/OnboardingStartSlide.qml, src/ui/screens/onboarding/ViewOnboarding.qml, tests/functional/helper.js, tests/functional/queries.js, tests/functional/testInitialize.js, tests/functional/testOnboarding.js
- Functional tests for the new onboarding experience
- Moved old "onboarding" test to `testInitialize.js`
N/A
=> Onboarding functional tests

scripts/windows/conda_install_extras.ps1, scripts/windows/conda_setup_win_sdk.ps1, taskcluster/ci/build/windows.yml, taskcluster/ci/config.yml, taskcluster/ci/repackage/kind.yml, taskcluster/ci/toolchain-openssl/kind.yml, taskcluster/ci/toolchain/conda_windows.yml, taskcluster/ci/toolchain/qt.yml
Played around with them in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7920 
Just some minor changes to the conda env, given we no lonver have vs-build tools.
=> Update our Windows workers to win22

ios/app/main.entitlements, src/connectionmanager.cpp
Uplift PR #8143 to the 2.17.1 release branch.
https://mozilla-hub.atlassian.net/browse/VPN-5400
=> VPN-5400 fix 2 iOS crashes (#8143)

nebula/ui/components/inAppAuth/MZInAppAuthenticationBase.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml, src/ui/deleteAccount/ViewDeleteAccountRequest.qml, tests/functional/queries.js, tests/functional/testAuthenticationInApp.js
This comes from additional QA on the ticket.
Per chat on ticket and 1:1 w/ Peter, we're going to remove the "X" button from the 2FA screen, as we also have the "cancel" button to duck out of the flow.
https://mozilla-hub.atlassian.net/browse/VPN-5697
=> VPN-5697 follow up

src/platforms/windows/windowscommons.cpp, src/platforms/windows/windowscommons.h
Correct the log file location
[VPN-5657](https://mozilla-hub.atlassian.net/browse/VPN-5657)
[VPN-5657]: https://mozilla-hub.atlassian.net/browse/VPN-5657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-5657: Log file location

src/telemetry/metrics.yaml
Decided to pull this out of the original VPN-5251 (https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8139) PR, just because it adds a lot of noise.
=> VPN-5251 - Declare metrics

tests/functional/setupWasm.js
This will help me out to test https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8139. I am getting weird local WASM errors, so I thought: "What if I don't need to deal with that?"
=> No ticket - Make it possible to run functional tests locally with remote WASM build

taskcluster/scripts/build/ios_build_no_adjust_cmake.sh, taskcluster/scripts/build/macos_build.sh
Welp. Our build folder should not live in `/fetches`
=> Nit: Macos&iOS let's not build in task/fetches 

CMakeLists.txt, scripts/cmake/rustlang.cmake, scripts/windows/conda_setup_win_sdk.ps1, taskcluster/ci/build/windows.yml, taskcluster/ci/toolchain/qt.yml, taskcluster/scripts/build/windows_clang_cl.ps1, taskcluster/scripts/toolchain/compile_qt_6.ps1
We already have a[ android-next task ](https://treeherder.mozilla.org/jobs?repo=mozilla-vpn-client&searchStr=next) that builds the client using a more recent version of qt. 
Given we want to upgrade windows too soon, let's create them here aswell.
=> Windows: Create a QT 6.6.0-Next task 

CMakeLists.txt, scripts/windows/conda_setup_win_sdk.ps1, taskcluster/ci/build/windows.yml, taskcluster/ci/toolchain/qt.yml, taskcluster/scripts/build/windows_clang_cl.ps1, taskcluster/scripts/toolchain/compile_qt_6.ps1
This reverts commit 339da843bf9fe51906594d1dc3f38bcaa6cc98fd.
I did turn on auto merge, but ofc the 2 new tasks were not required, merging in a broken state 😅
=> Revert "Windows: Create a QT 6.6.0-Next task  (#8063)"

CMakeLists.txt
=> Bump version number to v.2.20.0

taskcluster/scripts/build/wasm.sh
We build in debug mode, resulting in an 182 MEGABYTE wasm file....
=> Nit: Can we shrink the wasm build?

.dictionary, docs/rfcs/0004-cirrus-experiments.md, docs/rfcs/0006-cirrus-experiments.md
This RFC was first shared with product and the Nimbus team on Google Docs. It has been aproved by that crowd and I am now sharing it here to get technical feedback from engineers that also work on the MozVPN.
[Rendered](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/340996ebf399d39708dd4d596546cf292c1f0469/docs/rfcs/0004-cirrus-experiments.md).
=> [RFC] VPN-4935 - Cirrus Experiments

taskcluster/mozillavpn_taskgraph/transforms/scriptworker.py, taskcluster/mozillavpn_taskgraph/worker_types.py
This pr'adds a transform that should add on any authenticode signed MSI without a comment the default `Mozilla VPN Installer` as comment.
=> VPN-5868 add authenticode comment to msi signing tasks

CMakeLists.txt
=> Version bump to 2.19.1

ci_scripts/ci_post_clone.sh, src/adjust/adjusthandler.cpp, src/cmake/ios.cmake, src/mozillavpn.cpp, src/platforms/ios/iosadjusthelper.mm, src/platforms/ios/sources.cmake
Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8567 into 2.19.1 release branch
VPN-5821
=> Cherry pick VPN-5821: Fix adjust in iOS

scripts/android/cmake.sh, src/platforms/android/sources.cmake
Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8690
VPN-5822
=> Cherry pick VPN-5822: Uplift adjust android fix

android/AndroidManifest.xml
Uplift https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8790
N/A
=> Uplift add ad_id permission in for Android

src/settingsholder.cpp, src/settingsholder.h, src/settingslist.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/testsettingsholder.cpp, tests/unit_tests/testsettingsholder.h
This is pre-work for my upcoming PR which actually completely refactors the Settings management.
The idea was to test the APIs as is, then change it all and check that the test are passing all the same.
Also, I removed an unused configuration for settings since I was at it.
=> Chore: Write test suite for SettingsHolder generated functions

CMakeLists.txt
Bumping version on release branch
N/A
=> Version bump to 2.19.2

android/AndroidManifest.xml, android/adjust/build.gradle, android/common/build.gradle, android/common/src/main/java/org/mozilla/firefox/qt/common/CoreApplication.kt, android/daemon/build.gradle, android/resources/all/xml/network_security_config.xml, scripts/android/cmake.sh
Uplift https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8824
This is part two of VPN-5822.
A write up of the issues this fixes is in the ticket: https://mozilla-hub.atlassian.net/browse/VPN-5822?focusedCommentId=809828
=> Uplift VPN-5822 (part 2) to 2.19.2

taskcluster/requirements.in, taskcluster/requirements.txt
This contains an important fix that unbreaks actions.
=> ci: Upgrade to Taskgraph 7.0.2

src/daemon/daemonlocalserverconnection.cpp
During the support request flow, the client attempts to collect logs from both itself and the (privileged) daemon process to send to the support team. However, if the client is not yet authorized against the daemon, the daemon ignores the request, and this causes the client to hang. This is a quick fix that simply returns empty logs from the daemon if we are in this situation. 
Fixes VPN-5878
=> VPN-5878: Handle failure to get privileged logs from daemon

src/feature/featurelistcallback.h
- Turn on the annual upgrade feature flag for the production environment
[VPN-5637: Turn the VPN plan upgrades feature ON](https://mozilla-hub.atlassian.net/browse/VPN-5637)
=> VPN-5637: Enable annual plan upgrade in production

.github/l10n/exceptions.json, src/translations/strings.yaml, src/ui/authenticationInApp/ViewAuthenticationSsoAccount.qml, src/urlopener.cpp
Fixes changes requested on [VPN-5871](https://mozilla-hub.atlassian.net/browse/VPN-5871).
[VPN-5871]: https://mozilla-hub.atlassian.net/browse/VPN-5871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-5871: Passwordless auth: string update

android/daemon/build.gradle, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/NotificationUtil.kt, android/daemon/src/test/java/org/mozilla/firefox/vpn/daemon/NotificationUtilTest.kt, taskcluster/config.yml, taskcluster/kinds/build/android.yml, taskcluster/kinds/test/junit.yml, taskcluster/kinds/test/kind.yml, taskcluster/kinds/test/taskgraph.yml, taskcluster/scripts/build/android_build_debug.sh
=> "VPN-6037 - fix de-serialisation of canned notifications"  (#8976)

tests/functional/testSubscription.js
- Looks like I forgot to remove some debug/test code in eef4311 which prevents all other tests in the `testSubscriptions` suite from running 😬 
N/A
=> Run all tests in testSubscription

src/feature/featurelist.h, src/inspector/inspectorhandler.cpp, tests/functional/helper.js, tests/functional/testMultihop.js, tests/functional/testSettings.js
- Enables helps sheets
[VPN-6104: Turn the in-product help sheets feature on](https://mozilla-hub.atlassian.net/browse/VPN-6104)
=> VPN-6104: Turn on help sheets feature flag

src/telemetry/impression_metrics.yaml, src/telemetry/interaction_metrics.yaml, src/ui/screens/getHelp/ViewGetHelp.qml, src/ui/screens/settings/ViewReset.qml, tests/functional/testSettings.js
- Add telemetry for: 
- Get help impression
- Factory reset interaction
[VPN-5234: Improvement: Implement "Reset and Quit" telemetry](https://mozilla-hub.atlassian.net/browse/VPN-5234)
=> VPN-5234: Factory reset telemetry

src/feature/featurelist.h
This PR enables the factory reset feature on all platforms. 
VPN-6146
=> VPN-6146 : Enable factory reset

src/update/balrog.cpp
When launching an update process via Balrog on Windows, we find that the `TaskUpdate` task is blocks indefinitely under the expectation that the MSI installer will terminate the application for us. However, this isn't necessarily true if the installer exits unsuccessfully and results in a hang of the VPN client.
To resolve this, we need to check the exit condition of the installer process, and terminate the `TaskUpdate`
accordingly. In order to catch this exit condition, we also need to use `QProcess::start()` instead of `QProcess::startDetached()`
Github issue: #9324 ([VPN-6287](https://mozilla-hub.atlassian.net/browse/VPN-6287))
[VPN-6287]: https://mozilla-hub.atlassian.net/browse/VPN-6287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-6287: Handle MSI installer errors when updating via Balrog

taskcluster/kinds/toolchain/conda_android.yml
=> Add env.yml as a dep for conda-pack-android

src/translations/strings.yaml, src/ui/screens/home/ViewMultiHop.qml, src/ui/screens/home/servers/ServerList.qml
Cherry pick of PR #9413 to the `releases/2.22.0` branch.
Github PR #9413
Jira issue [VPN-6327](https://mozilla-hub.atlassian.net/browse/VPN-6327)
[VPN-6327]: https://mozilla-hub.atlassian.net/browse/VPN-6327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-pick VPN-6327: Remove server list info cards and associated strings

tools/wasm_chrome/branch_selector.mjs
Make sure that if you put a query that is not an existing branch , that we pick one that exitsts instead :)
=> Nit: Assert the branch param is really a branch

src/translations/extras/extras.xliff
Companion PR to https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/439
=> VPN-5175 - Add city names to extras.xliff

linux/mozillavpn.spec, taskcluster/docker/linux-dpkg-build/Dockerfile, taskcluster/docker/linux-rpm-build/Dockerfile
Just updating some stale names and maintainer e-mails.
=> Nit: Update maintainer info for Naomi Kirby

android/daemon/src/main/AndroidManifest.xml
Cherry pick of PR #9475 to the `releases/2.22.0` branch.
JIRA issue: [VPN-6344](https://mozilla-hub.atlassian.net/browse/VPN-6344)
[VPN-6344]: https://mozilla-hub.atlassian.net/browse/VPN-6344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-pick: VPN-6344 Android Permissions Fix

nebula/ui/components/MZStackView.qml, nebula/ui/components/navigationBar/MZBottomNavigationBarButton.qml, src/frontend/navigator.cpp, src/ui/main.qml, tests/functional/testInitialize.js
Pulled this out of https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8139 because it is not as simple as I initially figured.
~Opening this as a draft, will see what I can do when I get some time.~ Paired on this with @lesleyjanenorton and now it works!
=> VPN-2833 - Skip loading of currently loaded screen

linux/netfilter/netfilter.go, src/controller.cpp, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/platforms/linux/daemon/wireguardutilslinux.h, src/rfc/rfc4291.cpp, src/rfc/rfc4291.h
I am taking a stab at reviewing VPN-5865, and I have been finding a few things that don't work on my machine. This is a collection of fixes that I have needed to get the branch working in my particular environment.
Upstream PR #9257
JIRA issue: [VPN-5865](https://mozilla-hub.atlassian.net/browse/VPN-5865)
[VPN-5865]: https://mozilla-hub.atlassian.net/browse/VPN-5865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-5865: Naomi Testing Fixes

.dictionary, docs/Components/l10n.md
Ok so 2674dbcb1e25a0dd59d719dd309c605898e2710e is just a copy paste from a doc Vinoo wrote a while back and which was meant to be added to the repo anyways.
And this is the docs on the new `extras.xliff` file 65348abd3c53886e5e4beebc6a37d8b92dfe9c96.
=> VPN-6348 - Add l10n docs

taskcluster/config.yml, taskcluster/kinds/mark-as-shipped/kind.yml, taskcluster/mozillavpn_taskgraph/transforms/set_name.py
This task makes a call to the Shipit API to update the release's status to "shipped" once all other release tasks have successfully completed.
Issue: #8945
=> VPN-6098: Create a 'mark-as-shipped' task for Shipit integration

.gitmodules, ios/networkextension/CMakeLists.txt, src/platforms/ios/SwiftyPing.swift
[We're not the only ones with these crashes.](https://github.com/samiyr/SwiftyPing/issues/33#issuecomment-1918663230)
Since we need to edit the SwiftyPing source code, we have two main options:
- Fork the repo, make change there, change to using the forked repo
- Copy the files into our codebase and make the change there.
Since there is one file of source code (not including tests, project files, etc.) and the repo has not been updated in almost 3 years (so we won't need to maintain parity with the repo), I selected the second option for simplicity/timeliness. Open to changing this and forking into a mozilla-owned repo if folks prefer that.
VPN-6412
=> VPN-6412: Fix SwiftyPing crashes

taskcluster/mozillavpn_taskgraph/transforms/beetmover_apt.py
Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9636 to release branch
=> Cherry pick: ci: Don't run beetmover-apt tasks as part of relpro yet

addons/message_update_v2.23/manifest.json, addons/message_whats_new_v2.23/manifest.json
There were errors in the Figma that the original messaging was pulled from. This fixes the message, and changes the id of the strings so they get re-translated.
N/A
=> Fix 2.23 update/welcome messages

addons/message_update_v2.23/enable.js
I missed one update in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9631/. This should fix the headline.
N/A
=> Fix update addons for 2.23

src/platforms/windows/windowsutils.cpp, src/update/balrog.cpp, src/update/balrog.h
- VPN-5588 Add OS Version to balrog requests (#9688)
=> basti/ balrog lift

taskcluster/kinds/beetmover-apt/kind.yml, taskcluster/kinds/beetmover-ship/kind.yml, taskcluster/kinds/mark-as-shipped/kind.yml, taskcluster/requirements.txt
=> chore: update Taskgraph and dependencies

package-lock.json, package.json
See write up on https://mozilla-hub.atlassian.net/browse/VPN-6527
I'm not sure if this fixes it, but will check the CI run on this PR. While this was failing on prior PRs, it isn't required to pass, which is why we didn't notice it.
VPN-6527
=> VPN-6527: remove artifacts

package.json
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9746 gave a new error. Hopefully this fixes it. It does when running the work flow against this branch, but that was true before as well.
=> VPN-6527: improve workspace

android/vpnClient/build.gradle
We need to update our Android billing library.
Notes from reading this [migration doc](https://developer.android.com/google/play/billing/migrate-gpblv7)  (thanks @oskirby for pulling that doc out before I grabbed this ticket)
- We previously were using 5.2, so looking PBL 5 to PBL 7 section
- None of those other bullet points apply to us, so only change is to the billing library in build.gradle (From a quick glance at orderId in the Android code, I do not believe the "Handle pending transactions" section applies to us - but this is the only one I'm not 100% confident in. Note to self - If we get any errors, check into this one first.)
@oskirby reported build errors on their machine, but it built fine locally for me. If it builds on the server successfully, I'll chalk it up to Naomi's …
=> VPN-6498: Update Android billing library

src/platforms/android/androidcontroller.cpp
Cherry-pick of #9757 to `releases/2.24.0` to close VPN-6523
PR to `main`: #9757
JIRA Issue: [VPN-6523](https://mozilla-hub.atlassian.net/browse/VPN-6523)
[VPN-6523]: https://mozilla-hub.atlassian.net/browse/VPN-6523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-pick VPN-6523: Fix Android LAN exclusions

src/translations/strings.yaml, src/ui/screens/settings/ViewPreferences.qml
Updating strings per the ticket:
VPN-6476
=> VPN-6476: update telemetry strings

macos/pkg/scripts/postinstall.in
Cherry pick of PR #9825 to the `releases/2.24.0` branch.
Initial PR #9825
JIRA Issue [VPN-6572](https://mozilla-hub.atlassian.net/browse/VPN-6572)
[VPN-6572]: https://mozilla-hub.atlassian.net/browse/VPN-6572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-Pick: VPN-6572: Add extra checks for symlinks in MacOS/postinstall script

src/webextensionadapter.cpp, tests/functional/testWebExtensionApi.js
The Extension should know the Client Version, as we will have a "minimum" client version needed to run the extension.
=> EXT: Add the current client version

src/translations/strings.yaml, src/ui/screens/settings/ViewPreferences.qml
Updated strings per ticket and conversation with Santiago.
VPN-6488
=> VPN-6488: update string for iOS exclude LAN feature

src/settingslist.h, src/translations/strings.yaml, src/ui/screens/onboarding/OnboardingStartSlideDesktop.qml, tests/functional/helper.js, tests/functional/setupVpn.js, tests/functional/testAuthenticationInBrowser.js, tests/functional/testConnection.js
Change the desktop default for start on boot. This pattern is used elsewhere in the file.
VPN-6460
=> VPN-6460: Change default for desktop start on boot

src/webextensionadapter.cpp, tests/functional/testWebExtensionApi.js
=> Pass StateOnPartial to web extensions

nebula/ui/components/MZSignOut.qml, src/controller.cpp, src/controller.h, src/mozillavpn.cpp, src/mozillavpn.h, src/ui/main.qml, src/ui/screens/ScreenSubscriptionInUseError.qml, src/ui/screens/devices/ViewDeviceLimit.qml, tests/qml/moccontroller.cpp, tests/unit/moccontroller.cpp
Cherry pick of PR #9859 to the `releases/2.24.0` branch.
JIRA Issue: [VPN-6570](https://mozilla-hub.atlassian.net/browse/VPN-6570)
JIRA Issue: [VPN-6583](https://mozilla-hub.atlassian.net/browse/VPN-6583)
[VPN-6570]: https://mozilla-hub.atlassian.net/browse/VPN-6570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-6583]: https://mozilla-hub.atlassian.net/browse/VPN-6583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-6570/VPN-6583: Fix logout race condition when VPN is active (#9859)

signature/src/lib.rs
The FFI logging unit tests in the `signature` crate made use of an expected `panic!()` macro to check that the expected error messages are generated, but it seems that this has recently started to result in test failures on Windows. It seems that exception handling across FFI boundaries is undefined behaviour.
This attempts to rewrite those tests so that they instead set a static variable with the error message, which should allow us to check it after the FFI function is invoked.
=> signature: Rewrite FFI logging tests to remove panics

taskcluster/kinds/build/linux.yml
=> Add task index routes for the Linux static build

src/ui/screens/onboarding/OnboardingStartSlideDesktop.qml, tests/functional/testOnboarding.js
Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9878
=> Cherry pick VPN-6593 to 2.24.0 release branch

windows/installer/MozillaVPN.wxs
Cherry-pick of PR #9886 to the `releases/2.24.0` branch.
PR to `main`: #9886 
JIRA Issue: [VPN-6593](https://mozilla-hub.atlassian.net/browse/VPN-6593)
[VPN-6593]: https://mozilla-hub.atlassian.net/browse/VPN-6593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry Pick VPN-6953: Force reinstallation when running in maintenence mode

src/platforms/windows/daemon/windowssplittunnel.cpp, src/platforms/windows/daemon/windowssplittunnel.h
Stacked PRs:
* #9892
* #9891
* #9890
* #9889
* __->__#9888
--- --- ---
None of those things are needed in the Header of splittunnel, and just make embedders slower.
=> SplitTunnel 00: Cleanup the header

windows/installer/MozillaVPN.wxs
It's currently loose in the unsigned.zip - let's have it in the msi so the foxfooding instruction is simply "install this msi"
=> add proxy exe to msi

nebula/ui/components/MZSystemAlert.qml, src/daemon/daemon.h, src/daemon/daemonerrors.h, src/daemon/daemonlocalserverconnection.cpp, src/daemon/daemonlocalserverconnection.h, src/errorhandler.cpp, src/errorhandler.h, src/localsocketcontroller.cpp, src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowssplittunnel.cpp, src/platforms/windows/daemon/windowssplittunnel.h, src/translations/strings.yaml
Stacked PRs:
* __->__#9892
* #9891
* #9890
* #9889
--- --- ---
This pr adds error codes to the daemon backend failure signal and a catcher for the UI
=> SplitTunnel 04: Add Daemon Error Reporting

taskcluster/config.yml, taskcluster/mozillavpn_taskgraph/transforms/beetmover_apt.py
We'll need to update grants in fxci-config for this as well.
=> ci: fix scope prefix in beetmover apt task

src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowssplittunnel.cpp, src/platforms/windows/daemon/windowssplittunnel.h
Have you tried turning it on an off again, but make it for drivers!
=> Let's reboot the driver 

.github/workflows/linux.yaml, .github/workflows/ppa-automation.yaml
Cherry-pick of #9837 to the `releases/2.24.1` branch in order to fix the PPA automation workflows.
=> Cherry-pick: fix GitHub workflow source jobs

taskcluster/config.yml, taskcluster/mozillavpn_taskgraph/transforms/beetmover_apt.py
Cherry-pick of #9905 to the `releases/2.24.1` branch
=> Cherry-pick: ci beetmover apt scope fix

src/cmake/ios.cmake, src/constants.cpp, src/constants.h, src/platforms/ios/iosiaphandler.h, src/platforms/ios/iosiaphandler.mm, src/platforms/ios/iosiaphandler.swift, src/tasks/purchase/taskpurchase.cpp, src/tasks/purchase/taskpurchase.h
Cherry pick of #9873 
VPN-6512
=> Cherry pick #9873 to release branch

src/platforms/ios/iosiaphandler.mm
=> Cherry pick #9946 to 2.24.2 release branch (VPN-6640: Fix crash on reset and quit)

src/translations/extras/extras.xliff
Update translations on release branch
=> update translations on 2.24.2 release branch

taskcluster/config.yml
=> ci: remove b-linux-generic worker alias

src/localizer.cpp, tests/unit_tests/testlocalizer.cpp
=> Uplift #9933 to 2.24.3 (VPN-6622: Fix broken device language for Chinese)

taskcluster/config.yml, taskcluster/kinds/beetmover-apt/kind.yml
#9998 is the beetmover fix for Linux
=> Uplift #9998 to 2.24.3 release branch

extension/socks5proxy/bin/sockslogger.cpp, extension/socks5proxy/bin/sockslogger.h, extension/socks5proxy/src/socks5connection.cpp, extension/socks5proxy/src/socks5connection.h, extension/socks5proxy/tests/testsocks5connection.cpp, extension/socks5proxy/tests/testsocks5connection.h
After doing some performance testing of the SOCKS5 proxy, we aren't doing a great job of handling flow control and congestion when uploading to slow networks, or receiving data faster than Firefox can consume. This is due to the fact that the `QTcpSocket` class performed buffering for us, and doesn't enforce any upper bound on the size of that buffer.
For example, if we try uploading a 1GB file to some slow host, Firefox will open a connection to the proxy and send the upload as quickly as possible. Because the connection is over localhost, this happens fast and the proxy winds up storing the entire 1GB of data in the TCP socket buffer. This is both wasteful of memory and misleads Firefox into thinking the network is blindingly fast.
To make this behave better, let's add some flow control …
=> FXVPN-104: Implement Proxy Flow Control

scripts/windows/conda_setup_win_qt.ps1
Needed to do a re-setup of my machine, noticed that this one is pointing to the wrong thing.
=> Nit: fix broken link

.gitmodules, env.yml, ios/networkextension/CMakeLists.txt, scripts/cmake/rustlang.cmake, src/cmake/ios.cmake, src/models/devicemodel.cpp, src/models/devicemodel.h
I've been trying to get my iOS development environment working again after the latest round of updates from Apple. Here's the fixes I've had to apply in order to get going.
My initial PR included code changes necessary to get the iOS simulator working, but that has proved to be too complex of a task, and I am going to split it out into a separate pull request.
Split from: #10092
=> Xcode 16 build fixes

src/profileflow.cpp
Uplift https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10190
=> Uplift PR #10190 to 2.25.0 release branch

src/ui/screens/ScreenAuthenticating.qml
=> Missing include for MZI18n in ScreenAuthenticating.qml

macos/pkg/conclusion.html.in
=> Uplift #10208 to 2.25.0 release branch

src/profileflow.cpp, src/ui/screens/settings/ViewSettingsMenu.qml
VPN-6318 follow up - better resetting of state. Uplifting #10210 to release branch.
=> Uplift #10210 to 2.25 release branch

src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowsfirewall.cpp, src/platforms/windows/daemon/windowsfirewall.h, src/platforms/windows/daemon/windowssplittunnel.cpp, src/platforms/windows/windowscommons.cpp
Cherry-pick #10225 to `releases/2.25.0`
Cherry-pick: #10225 
JIRA Issue: [VPN-6632](https://mozilla-hub.atlassian.net/browse/VPN-6632)
[VPN-6632]: https://mozilla-hub.atlassian.net/browse/VPN-6632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-Pick VPN-6632: Fix split tunnel when IPv6 unreachable (#10225)

src/webextensionadapter.cpp
RE; https://github.com/mozilla-extensions/mozilla-vpn-extension/pull/195
let's push the updated list to extension when it changes, so it can re-calculate if the current firefox is affected or not.
=> Nit: Push disabled app list

addons/message_try_firefox_extension/downloadFirefox.js, addons/message_try_firefox_extension/getExtension.js, addons/message_try_firefox_extension/manifest.json, src/mozillavpn.cpp
Final touch ups for the extension promo addon:
- Update URL (though it's not live yet)
- Add UTC params to both URLs (and I moved them both to the addon, so it works on older clients)
- Add the condition of time installed back (had been removed for QA's testing)
- Update timestamp to next Monday
- Remove condition of staging
FXVPN-280
=> FXVPN-280: finish addon message for extension promo

.dictionary, docs/Troubleshooting/inspector.md
Finally got this working for me when I stopped using Nightly to try to connect. Adding info on how to connect to our repo.
Please reject this PR if there are parts of this that are not clearly worded - would love to make sure this is helpful for us, whenever the next time we need it is.
N/A
=> Documentation: add inspector connection info for iOS

src/ui/screens/getHelp/developerMenu/ViewTelemetryDebugging.qml
Ever set telemetry debug options, but forget to turn on telemetry? This PR fixes that problem. And gives a notice at the top of the page about what is happening.
None
=> Auto start telemetry when setting debug options

src/ui/screens/getHelp/developerMenu/ViewImagesPlayground.qml
Request from design for a debug menu.
VPN-6873
=> VPN-6873: alphabetize assets in image playground

src/cmake/android_openssl.cmake
Uplift https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10283 to release branch. Without it, Android builds fail.
N/A
=> Uplift #10283 to release branch

extension/bridge/src/commands.rs
I should have called CLI commands that exist ...
=> FXVPN-246 fix open vpn command

extension/socks5proxy/src/socks5.cpp, extension/socks5proxy/src/socks5connection.cpp
=> 2.25.1 Uplifts

.dictionary, .gitmodules, 3rdparty/CMakeLists.txt, CMakeLists.txt, LICENSE.md, extension/socks5proxy/CMakeLists.txt, extension/socks5proxy/bin/CMakeLists.txt, extension/socks5proxy/bin/main.cpp, extension/socks5proxy/bin/windowsbypass.cpp, extension/socks5proxy/bin/windowsbypass.h, extension/socks5proxy/bin/winfwpolicy.cpp, extension/socks5proxy/src/CMakeLists.txt, extension/socks5proxy/src/dnsresolver.cpp, extension/socks5proxy/src/dnsresolver.h, extension/socks5proxy/src/socks5.h, extension/socks5proxy/src/socks5connection.cpp, extension/socks5proxy/src/socks5connection.h, extension/socks5proxy/src/winutils.cpp, extension/socks5proxy/src/winutils.h, taskcluster/scripts/build/windows_clang_cl.ps1
Cherry-pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10304
=> Cherry-pick #10304

src/translations/strings.yaml
This is part of VPN-6178. I'm about 75% through, but wanted to get these strings in today in case this feature is ready for the next release.
VPN-6178
=> strings for theme selection

src/translations/extras/extras.xliff
Add new language for translation.
VPN-6961
=> VPN-6961: add Friulian language

.github/dependabot.yml, .github/workflows/dependabot_auto_merge.yml
=> Bundle Dependabot PR's

linux/extra/org.mozilla.vpn-startup.desktop.in, linux/extra/org.mozilla.vpn.desktop.in
Fix missed icon on Linux with Wayland
mozilla-mobile/mozilla-vpn-client#10430
https://mozilla-premium-services.zendesk.com/tickets/249831
=> Fix missed icon on Linux with Wayland

taskcluster/kinds/build/linux.yml, taskcluster/kinds/docker-image/kind.yml
=> Add Taskcluster Linux builds for Ubuntu/Plucky

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNActivity.java
In order to fix [this ](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/10442) - we need to remove rotation lock, as newer android tablets can ignore that anyway. 
That ofc, caused on phones the option to use the app in landscape where stuff is utterly broken. 
So let's instead check when the activity is created the space we have. 
From Deskop we have a fixed size, 320*640, if this also fits in landscape onto the screen, it should be fine to rotate.
=> Bugfix: Toogle Orientation lock based on wheter the device has enough space

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNActivity.java
Toogle Orientation lock based on wheter the device has enough… space (#10513)
=> Uplift: #10513

src/translations/extras/extras.xliff
Add new language for translation. The lack of this translation is [currently blocking updating translations](https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/15267735677/job/42936323026?pr=10526).
VPN-7063
=> VPN-7063: add Sicilian language to app

src/platforms/windows/daemon/windowsfirewall.h
thanks clang-20 with all warnings as errors.
=> nit remove unused private field

addons/message_upgrade_to_bundle_1/conditions.js, addons/message_upgrade_to_bundle_1/openLink.js, addons/message_upgrade_to_bundle_2/conditions.js, addons/message_upgrade_to_bundle_2/openLink.js, addons/message_upgrade_to_bundle_3/conditions.js, addons/message_upgrade_to_bundle_3/openLink.js
Adding the USD critieria back in (in addition to being physically located in the US)
VPN-7002
=> VPN-7002 addendum - add USD criteria back in

addons/message_upgrade_to_bundle_1/conditions.js, addons/message_upgrade_to_bundle_2/conditions.js, addons/message_upgrade_to_bundle_3/conditions.js, src/mozillavpn.cpp, src/mozillavpn.h
Uplift #10589 to 2.29.0 release branch
=> Uplift #10589 to 2.29.0 (VPN-7002 fix - always load location)

taskcluster/config.yml
Switches signing to new m2 mac signer pool
https://mozilla-hub.atlassian.net/browse/VPN-7117
=> VPN-7117 - Switch to new m2 mac signer pool

addons/message_upgrade_to_bundle_1/openLink.js, addons/message_upgrade_to_bundle_2/openLink.js, addons/message_upgrade_to_bundle_3/openLink.js
Needed new links so that we don't ever get the test variant that doesn't show the PPP pricing. While we're at it, we'll update the stage links.
VPN-7135
=> VPN-7135: update links for addons

addons/message_upgrade_to_bundle_1/openLink.js, addons/message_upgrade_to_bundle_2/openLink.js, addons/message_upgrade_to_bundle_3/openLink.js
After the last VPN-7135 PR, we got confirmation that we could remove these params from the URL. (Had gone ahead with the last one while awaiting an answer because this is time-sensitive.)
VPN-7135
=> VPN-7135 touch up

scripts/cmake/rustlang.cmake
Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10642 to 2.30.0 release branch
=> Cherry pick #10642 to 2.30.0 release branch

src/utils.cpp, src/utils.h, src/utils/loghandler.cpp, src/utils/loghandler.h
Cherry-pick of PR #10644 to `releases/2.30.0`
JIRA Issue: [VPN-7156](https://mozilla-hub.atlassian.net/browse/VPN-7156)
[VPN-7156]: https://mozilla-hub.atlassian.net/browse/VPN-7156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-pick: VPN-7156: Fix view logs in containerized environments

macos/pkg/scripts/postinstall.in
Cherry-pick of PR #10654 to `releases/2.30.0`
JIRA Issue: [VPN-7142](https://mozilla-hub.atlassian.net/browse/VPN-7142)
[VPN-7142]: https://mozilla-hub.atlassian.net/browse/VPN-7142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cherry-pick: VPN-7142: macOS privileged helper fixes

macos/pkg/scripts/postinstall.in, src/cmake/macos.cmake, src/platforms/macos/daemon/wireguardutilsmacos.cpp, src/platforms/macos/daemon/wireguardutilsmacos.h, src/platforms/macos/daemon/xpcdaemonserver.mm, src/platforms/macos/macoscryptosettings.mm, src/utils/logger.cpp, src/utils/logger.h
It seems that installing a wrapper script into `/Library/PrivilegedHelperTools`  is a bit brittle and can lead to some problems in the XPC communication channel. Despite the daemon launching successfully, XPC messages just seem to end with an "invalid message". Surprisingly, If we replace the script with the daemon itself (which is how `SMJobBless` does it), then it all seems to work fine, so I am guessing that there is some codesign or security check that is failing.
So, let's do it the `SMJobBless` way and make the daemon actually installable. The only reason we didn't attempt this in the first place is that can no longer use a relative path inside the bundle to find the `wireguard-go` binary, and furthermore, because the daemon and `wireguard-go` are no longer running in the same …
=> VPN-7142: Directly install daemon for macOS<13

docs/Building/android.md, docs/Building/index.md, env-android.yml
- Change the default name. 
- Remove the instruction to overwrite the default name. 
- Update documentation in a couple places.
VPN-7216
=> VPN-7216: update name for Android conda environment

taskcluster/kinds/fetch/kind.yml, taskcluster/kinds/toolchain/qt.yml
Qt released the 6.9.2 update yesterday which includes a bunch of minor fixes, including the proper resolution for [VPN-7172](https://mozilla-hub.atlassian.net/browse/VPN-7172)
- [Qt 6.9.2 Released](https://www.qt.io/blog/qt-6.9.2-released)
- [Release notes](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.9.2/release-note.md)
[VPN-7172]: https://mozilla-hub.atlassian.net/browse/VPN-7172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update to Qt 6.9.2 for Linux and macOS static builds

src/settingslist.h
Per discussion Tuesday.
VPN-7246
=> VPN-7246: change local network default for iOS

linux/debian/rules
Cherry-pick of #10770 to `releases/2.31.0`
=> Cherry-pick VPN-7259: Exclude 3rdparty from dh_clean (#10770)
