src/ui/components/VPNAboutUs.qml, src/ui/components/VPNCheckBoxAlert.qml, src/ui/components/VPNCheckBoxRow.qml, src/ui/settings/ViewNetworkSettings.qml, src/ui/settings/ViewNotifications.qml, src/ui/settings/ViewSettingsMenu.qml
Noticed this layout issue while running the app in a few of the Android simulators.
This PR 
- Allows text in the settings views to wrap, unwrap as necessary according to the window width
- Prevents checkbox alert "VPN must be disabled.." from being cut off on narrower devices. 
<br>
<br>
Text will now wrap based on window width
=> Better text wrapping in settings menu and settings views

src/ui/components/VPNMouseArea.qml
Revert to "uiState.stateDefault" when a mouse event is canceled because scrolling is detected or another component has usurped the mouse event. This fixes the issue on iOS and Android emulators.
=> Fix #236 - Components remain selected on scroll

src/ui/components/VPNConnectionInfo.qml, src/ui/components/VPNControllerView.qml, src/ui/components/VPNGraphLegendMarker.qml
Fixes #134 and most of #136 
- Restricts focus to connection info when connection info graph is visible
- Makes graph legend information accessible screen readers (do we want to create some new strings for this?)
- Makes IP address accessible to screen readers
- Connection info can be closed by clicking escape, clicking outside the graph, or clicking the close button
A few remaining issues:
- the semantics of the connection info Popup {} are not exposed to screen readers.
=> Make connection info accessible

src/ui/components/VPNLinkButton.qml
This fixes the accessibility highlighting display issue with VPNLinkButton, as seen in #226.
Modified VPNLinkButton to inherit from VPNButtonBase and added an extra "base style" property. This keeps the logic for buttons in the base class to allow for easier management.
These design choices allow to keep the current implementation of link buttons and how they're styled without majorly re-hauling how themes work.
I do have the question of whether enter/space should be used for "clicking" the button when focused. In the VPNButtonBase class, only enter is used for actually clicking the button, while VPNLinkButton, allows for either enter or space.
=> Fix #226: Make LinkButton inherit from ButtonBase

src/ui/components/VPNGraphLegendMarker.qml
Hopefully I figured out the right comment looking at the code. The export looks correct, the multiline comment is rendered as one line.
```
<message id="vpn.connectionInfo.accessibleName">
<location filename="../src/ui/components/VPNGraphLegendMarker.qml" line="50"/>
<source>%1: %2 %3</source>
<extracomment>Used as accessibility description for the connection info: %1 is the localized label for “Upload” or “Download”, %2 is the speed value, %3 is the localized unit. Example: “Upload: 10 Mbps”.</extracomment>
<translation type="unfinished"></translation>
</message>
```
=> Add comment for vpn.connectionInfo.accessibleName

src/ui/components/VPNFlickable.qml, src/ui/components/VPNFooterLink.qml, src/ui/main.qml, src/ui/settings/ViewSettingsMenu.qml, src/ui/views/ViewDevices.qml, src/ui/views/ViewLogs.qml, src/ui/views/ViewSubscriptionNeeded.qml, src/ui/views/ViewUpdate.qml
Had to do a bit of repositioning to prevent some of the VPN content from getting stuck beneath the default device info.
=> Actually use full screen on iOS devices

src/ui/components/VPNControllerServer.qml, src/ui/components/VPNServerCountry.qml, src/ui/views/ViewMain.qml, src/ui/views/ViewServers.qml
Marking this as WIP because there are a few things to decide: 
1.) What should happen when the server list is opened and `VPNController.state === VPNController.StateSwitching` ? Right now, we just return instead of scrolling to the previously selected server country. Maybe there is something better to do here.
2.) Do we want to disable clicks to the server list when `VPNController.state === VPNController.StateSwitching` ? We disable the toggle, so this doesn't feel like a stretch. 
Fixes #116
=> Open server list to selected server

src/ui/components/VPNButtonBase.qml, src/ui/components/VPNClickableRow.qml, src/ui/components/VPNMouseArea.qml, src/ui/components/VPNServerCountry.qml
Prevents clicks to the left of server city names, and clicks to the spacing between server city names, from collapsing the entire city list.
=> Prevent mouse clicks around server city names from toggling list visibility

src/ui/components/VPNAlert.qml
Prevent VPNAlert {} from getting stuck underneath the "swipe up" bar on iOS.
=> Reposition VPNAlert {} on mobile

scripts/qt5_compile.sh
This allows the build script to be used as
```shell
./scripts/qt5_compile.sh -j 10 qt qt # before mandatory vars
./scripts/qt5_compile.sh qt qt -j 10 # after mandatory vars
./scripts/qt5_compile.sh --jobs 10 qt qt # before mandatory vars
./scripts/qt5_compile.sh qt qt --jobs 10 # after mandatory vars
```
=> Fix #90 - Add jobs argument for Qt compile script

src/controller.cpp, src/controller.h, tests/unit/moccontroller.cpp
- Fix for #299 
We always add 0.0.0.0/0 to the allowed ip - so local traffic is always routed through the vpn on android.
=> Do not add Catch All IP range if LAN access is enabled

src/ui/components/VPNControllerServer.qml
Elide server city names in the main view when there is not enough space to show the entire name.
Closes #120
=> Elide server city names when necessary

src/ui/main.qml
Older iOS devices require less clearance. This varies the height of `iosSafeAreaTopMargin` by device to maintain the layout (prevent it from getting pushed awkwardly downward) on older iOS devices.
**Before  /     After** - Screen caps from iPhone 8 simulator. Note the "Get Help" link in the upper right corner. 
<div>
</div>
=> Vary iOS top margin height based on device

src/ui/components/VPNAlert.qml
Fixes part 1 of #347 
This moves error message from the bottom of the window to the top. There will be additional work to eventually nest these in the layout like the update alerts but not before V2.
=> Reposition error alerts

src/ui/components/VPNConnectionInfo.qml
Fixes #365 - 
I was able to reproduce #365 by removing the `maximumWidth` / `minimumWidth` properties set to the window in main.qml and adjusting the overall window width. After these changes, I can no longer reproduce.
=> Fix connection graph layout breakage

src/platforms/android/androiddatamigration.cpp, src/platforms/android/androidsharedprefs.cpp
We're currently only looking at the release shared-pref. This makes testing the migration require a release->release upgrade.
Lets use the debug shared-pref on debug, so QA can test migration from a debug 1.3 version to 2.0 debug apk
=> Add debug->debug android app migration path

android/src/com/mozilla/vpn/VPNServiceBinder.kt
Just noticed mullvad/check said we're not using the mullvad dns on android.
=> Force use of mullvad dns on android 

src/ui/components/VPNServerCountry.qml, src/ui/views/ViewServers.qml
This scrolls a city list into view when it's parent country item is expanded but the city list isn't totally visible.
=> Make city list visible when a country list item is expanded

src/apppermission.cpp, src/apppermission.h, src/qml.qrc, src/ui/components/VPNCheckBoxAlert.qml, src/ui/components/VPNCheckBoxRow.qml, src/ui/components/VPNClickableRow.qml, src/ui/components/VPNExpandableAppList.qml, src/ui/settings/ViewAppPermissions.qml, src/ui/settings/ViewNetworkSettings.qml
I've tried to make the AppPermission View to function more of what we currently have in the current android app. Currently we just show a plain list of all apps. 
I've added: 
- Split list ( Protected / Unprotected)
- Made Lists Expandable/Collapsible
- Add a unblock/block all button
Let me know what you think :)
=> Improve AppPermission Functionality

android/src/com/mozilla/vpn/BootReceiver.kt, android/src/com/mozilla/vpn/PackageManagerHelper.java, android/src/com/mozilla/vpn/VPNWebView.java, src/platforms/android/androidauthenticationlistener.cpp, src/platforms/android/androidauthenticationlistener.h, src/src.pro
This is an idea i came up to handle #344. 
Even though i think it's unlikely that a user on a real device that has the play store will encounter this, a fallback is always good.
So what i try to do here is to detect old webviews and then use the DesktopAuth. 
In that case we would open the users default browser instead of a webview, which hopefully is way newer. 
Currently the user would need to navigate back to the app by hand, but still this is way better then not beeing able to login in at all.
=> WIP: Detect too old WebViews

android/src/com/mozilla/vpn/BootReceiver.kt, android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNServiceBinder.kt, src/platforms/android/androidcontroller.cpp
- The the pref would never transfer to VPNService since reading the QVariant did not properly work in Kotlin
- Without Preloading the Backend, the Android Scheudler might drop loading the Service as a whole because of cpu pressure 
- Also we're now propagating a vpn state change to the frontend (if loaded) - in case the system starts the vpn :) 
- Also more logs
=> Android 5&6 : Fix Start On Boot

android/AndroidManifest.xml
It seems qt's "androiddeployQT"  `` adds fine location access as default permission. 
We aren't really requiring this, right?
=> Do not rely on QT to add Permissions

src/ui/components/VPNCheckBoxRow.qml, src/ui/components/VPNExpandableAppList.qml
Hello! I've changed a few small things in the AppPermission that came up:
- The List is no longer child of VPNClickableRow
-> Otherwise if you fat finger in the list anything other than the checkbox, the list will close (which is probably not good)
- The Action Button (unprotect all etc) is hidden if the list is empty
-> Since it doesn't do anything if the list is empty we might also just hide it
- Disable Word Wrapping for the App PackageID
-> Some apps have very long package names, with wrapping the list element would grow and look janky :(, I've disabled word wrapping - its i guess not that important for the user, unlike the App Name. 
let me know what you think :) 
New Screen attached :
=> Fix small UX issues in AppPermission

scripts/android_package.sh
The play console suggested that we might use aab - so we dont ship x86 binaries to arm and vice versa
https://developer.android.com/platform/technology/app-bundle
=> Create an AAB for Release Builds

src/platforms/android/androiddatamigration.cpp
From my Android Logs - it seems the prod-migration fail was caused by the name beeing wrong
```
[12.01.2021 14:31:04.903] (android - AndroidDataMigration) Android Data Migration -- Start
[12.01.2021 14:31:04.904] (android - AndroidDataMigration) Migration org.mozilla.firefox.vpn.preferences.xml was not file found - skip
[12.01.2021 14:31:04.904] (android - AndroidDataMigration) Migration files:  [.,..,org.mozilla.firefox.vpn_preferences.xml]
[12.01.2021 14:31:04.904] (main - SettingsHolder) Setting nativeAndroidDataMigrated
```
=> Change MigrationFile Name for prod

src/src.pro
While not really relevant on android, x86_64 is  very relevant on Chrome OS. 
Users that have an x86_64 abi currently just experience a crash. "A fatal error... and the app cannot continue etc"
=> Android: Also Support x86 64 abi

src/ui/components/VPNFlickable.qml, src/ui/settings/ViewSettingsMenu.qml
This reduces the opacity of the scrollbar only when the the settings list StackView is transitioning between views.
=> Nit: "Hide" settings list scrollbar during stack transitions

.github/workflows/android.yaml, android/build.gradle, android/gradle.properties, scripts/android_package.sh
Closes #459 - Whilst nothing we should try in 2.0.x, i think this is a neat thing for the next release.
This adds abi- splitted apk's in addition to our (current) universal apk. They are way smaller, 20mb vs 80mb (universal).
I followed https://developer.android.com/google/play/publishing/multiple-apks
=> Build also ABI-Splitted apk's for release

android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNTunnel.kt
Fixes #439
It might be that the OS kills our vpn connection, e.g. when always-on vpn gets set to false. This was not propagated to the front end.
=> Pass Tunnel State changes to QT

scripts/android_package.sh
Lets change the android version code to use something time based instead of our real version, so we dont have to bump it every time we we want to test on google play. 
the $Fullversion is sadly too big. We have a max versioncode of 2 100 000 000. With just a UNIX timestamp we would burn all codes out in ~15 years. So my idea is to cut of the last ~16 minutes of the timestamp, which adds more then enough time before the codes burn out.
=> Use Timestamp to calculate the android version code

src/ui/components/VPNAnimatedRings.qml, src/ui/components/VPNControllerView.qml
Hello! About #445 - I've had the idea that we might freeze the ring-animation when we navigate to another page and wait a bit when navigating back.
So devices that are already struggling with the ring animation (Like my pixel) have GPU time for the navigation animations. That makes it way smother to navigate to languages/devices while connected
Let me know what you think :)
=> Stop the animated-circles when not visible or navigating

.github/workflows/android.yaml
This should add all the diffrent arches, let's see what the ci gets :) 
- Works, prod-release artifact has them all now :)
=> Add All release APK's to the Artifact

src/ui/components/VPNHeadline.qml, src/ui/components/VPNPanel.qml
=> Wrap exceedingly long words (or display names) anywhere.

src/ui/components/VPNCheckBoxRow.qml
On windows, without this change, the network settings will be wrapped in this way:
I could change the wrapping for the settings only, but why wrapAnywhere? @lesleyjanenorton let me know what you think.
=> Word wrap by default for VPNCheckBoxRow

android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNServiceBinder.kt, android/src/com/mozilla/vpn/VPNTunnel.kt
Currently the Android Controller get's the "connected/disconnected" events from multiple places. 
We can simplify this with the VPNTunnel, which gets all connection events from the wg-go-backend anyway. 
This solves also the problems of #440 - as we there had multiple actors emitting the same events.
=> Handle all Connection-Events in VPNtunnel.kt

android/AndroidManifest.xml, android/build.gradle, android/src/com/mozilla/vpn/VPNPermissionHelper.kt, android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNServiceBinder.kt, android/src/com/mozilla/vpn/VPNTunnel.kt, src/controller.cpp, src/platforms/android/androidcontroller.cpp
There were 3 things that caused us to close down unexpectedly:
We were starting the service as a bind-first service ( so it got closed once all binders are disconnected)
We were starting the service with context of qt -> so once the qt context got closed the service aswell
Qt just kills the whole process when closing -> so the service was killed aswell. 
So in android controller we're now starting the service intent-first with the app context. ( so unbinding does not affect lifecycle)
And we're putting QT in it's own process called QtOnlyProcess. This means i had to create a small dummy-vpn service that is able to prompt the vpn permission for us, since can't use jni cross process.
=> Android isolate qt

.github/workflows/linters.yaml
Our hooks don't seem to catch kotlin, so i thought about adding a ci step for that :)
=> CI: add a kotlin linter

.github/workflows/android.yaml, src/src.pro
We can take this and use it later with https://developer.android.com/ndk/guides/ndk-stack to make logcat crashes in the google play console more readable :)
=> Upload debug symbols for release builds

.github/workflows/macos-build.yaml
Right now the zipfile starts with `Contents` as the root dir, which means we can't sign it.
=> Include .app directory in macos build upload

version.pri
I guess for the next fixed Android release, we might want to bump the to version 2.0.4 ?
=> Version Bump to 2.0.4

src/connectiondataholder.cpp, tests/unit/testconnectiondataholder.cpp, tests/unit/testconnectiondataholder.h
Prevent to fetch the ip if we're not connected so the real ip is not shown while we try to get the vpn-ed ip. 
Assert that the fetched ip has to be reported in the same country as we are connected to, otherwise retry. 
Oh and change the "unknown" string to "loading".. as we're probably loading when the user sees this. :) 
Closes #549
=> Wait for the Correct IP to be fetched

src/captiveportal/captiveportalrequest.cpp, src/controller.cpp, src/ipaddress.cpp, src/ipaddress.h, src/ipaddressrange.cpp, src/ipaddressrange.h, src/mozillavpn.cpp, src/rfc1918.cpp, src/rfc1918.h, src/rfc4193.h, src/src.pro, src/wgquickprocess.cpp, tests/unit/testipaddress.cpp, tests/unit/testipaddress.h, tests/unit/unit.pro
On top of the IP filtering for the captive portal, this PR closes #295 and #521, implementing the local access network for all the platforms (Linux, windows, macos, ios, for sure. Android to be checked)
=> Filtering out the captive portal endpoint

src/captiveportal/captiveportalrequest.cpp, src/connectiondataholder.cpp, src/logger.h, src/networkrequest.cpp, src/networkrequest.h, src/platforms/ios/iaphandler.mm, src/platforms/ios/taskiosproducts.cpp, src/platforms/wasm/wasmnetworkrequest.cpp, src/tasks/accountandservers/taskaccountandservers.cpp, src/tasks/adddevice/taskadddevice.cpp, src/tasks/authenticate/taskauthenticate.cpp, src/tasks/captiveportallookup/taskcaptiveportallookup.cpp, src/tasks/removedevice/taskremovedevice.cpp, src/update/balrog.cpp, src/update/balrog.h, src/update/versionapi.cpp, tests/unit/mocnetworkrequest.cpp
This PR does 2 things:
1. it fixes the authentication failure, letting the `NetworkRequest::replyFinished()` to propagate the error
2. it removes the sharing of `QNetworkReply` to the rest of the codebase. It was done for balrog and used for 2 methods: `rawHeader` and `statusCode`. Now these 2 methods are part of the `NetworkRequest` class
=> Network requests improvements

src/qml.qrc, src/ui/states/StateBackendFailure.qml, src/ui/states/StateSubscriptionBlocked.qml, src/ui/views/ViewErrorFullScreen.qml
Adds ViewErrorFullScreen.qml and updates StateSubscriptionBlocked and StateBackendFailure to use it.
=> Add reuseable full screen error view

src/ui/settings/ViewSettingsMenu.qml
=> Fix 626 - Use "Close" instead of "Back" for close button tooltip in Settings Menu

src/ui/components/VPNCheckBoxRow.qml
Tiniest of nits noticed while working on #661 
After:
Before:
=> Fix spacing in Notifications

macos/daemon/helper.sh, src/platforms/macos/daemon/macosdaemon.cpp, src/platforms/macos/daemon/macosdaemon.h, src/platforms/macos/daemon/macosdaemonserver.cpp, src/wgquickprocess.cpp, src/wgquickprocess.h
This is a temporary fix for the next release until we have a better daemon implementation. It turned out that macOS leaks VPN DNSs randomly. I suspect there is a crash or a restart of the daemon. When this happens, the user is unable to navigate because the DNSs are wrongly set.
This is a temporary fix that stores the DNSs in a Settings and remove them at startup if found.
If somebody has time to work on a better fix, I'm happier :)
=> MacOS DNS recovering after crash

android/src/com/mozilla/vpn/BootReceiver.kt, android/src/com/mozilla/vpn/NotificationUtil.kt, android/src/com/mozilla/vpn/VPNLogger.kt, android/src/com/mozilla/vpn/VPNService.kt, android/src/com/mozilla/vpn/VPNServiceBinder.kt
Closes #685
Logcat has a few issues. If the call fails and the callback is never done we'll just show a white page. 
Also logcat does not keep logs as long as we want to, so i want to replace it with a drop-in replacement that also stores everything to disk aswell as printing to logcat. - Just like the qt version. 
This should be more robust as we can just catch i/o errors :)
=> Replace logcat reading with a log-file

src/connectionhealth.cpp, src/connectionhealth.h
Stop ConnectionHealth when the app goes into an inactive state and resume once the app is back up - so we're not getting a "no connection" after every resume :)
=> Suspend Connection Health when the app is inactive

src/captiveportal/captiveportalnotifier.cpp, src/commands/commandui.cpp, src/networkwatcher.cpp, src/platforms/linux/linuxsystemtrayhandler.cpp, src/platforms/linux/linuxsystemtrayhandler.h, src/qmlengineholder.cpp, src/qmlengineholder.h, src/systemtrayhandler.cpp, src/systemtrayhandler.h
This PR contains 2 commits:
1. the first one contains a less-intrusive systemTrayHandler code. Let's move the "Linux vs Default" in the CTOR of SystemTrayHandler and let's overwrite just the `showNotificationInternal` method.
2. The clicking is not received for me. I had to add a slot for that.
=> Ubuntu notification - a few changes

src/errorhandler.cpp, src/errorhandler.h, src/mozillavpn.cpp
Closes #495 
Issue here is: 
We have a task that starts an http-request.  (e.g. account&Servers)
We connect vpn.
The Request times out, as expected.  
We show the no connection banner.
My idea: Add a new connection-error for things that might be caused by vpn and are okay to ignore if the vpn is connected.
=> Fix random timout banner

src/ui/components/VPNControllerView.qml
This disables the settings button and reduces its opacity when `VPN.state === VPN.StateDeviceLimit`.
=> Fix #751 - Disable settings button when device limit is reached

src/qml.qrc, src/ui/components/VPNCheckBoxRow.qml, src/ui/components/VPNExpandableAppList.qml, src/ui/components/VPNSettingsToggle.qml, src/ui/settings/ViewAppPermissions.qml
- Adds and uses VPNSettingToggle instead of checkbox for "Protect selected apps" setting
- Fixes menu header to top of view to match other settings sub-pages
- Disables clicking/toggling of zero length lists
- Closes #682
- Moves 'VPN Must be off..." to top of view
- Adds list item transitions when items are removed or added to each list
=> App permissions UI update

src/qml.qrc, src/ui/components/VPNControllerNav.qml, src/ui/components/VPNControllerView.qml, src/ui/components/VPNDeviceListItem.qml, src/ui/components/VPNDevicesListHeader.qml, src/ui/components/VPNMenu.qml, src/ui/components/VPNRemoveDevicePopup.qml, src/ui/states/StateDeviceLimit.qml, src/ui/views/ViewDevices.qml, src/ui/views/ViewMain.qml
Fixes #752 
User flow changes when the device limit is exceeded:
- When the device limit has been exceeded, the user is taken directly to the devices view instead of the main view
- Adds 'Sign Out' and 'Get Help' links to the devices view, and disables the 'back' button when the device limit warning is visible.
- Removes code to show UI/disable certain bits of functionality in the main view when `VPN.StateDeviceLimit`
- Refactors as needed
=> Improved UX / UI when device limit is exceeded

src/notificationhandler.cpp
Currently we only allow updating the notification if we're on the main screen. 
To close #683, we probably should also allow the disconnected notification on the init screen, as it might have been triggered by a logout.
=> Allow Disconnect Notification On Init Screen

android/AndroidManifest.xml, android/src/org/mozilla/firefox/vpn/BootReceiver.kt, android/src/org/mozilla/firefox/vpn/NotificationUtil.kt, android/src/org/mozilla/firefox/vpn/VPNLogger.kt, android/src/org/mozilla/firefox/vpn/VPNService.kt, android/src/org/mozilla/firefox/vpn/VPNServiceBinder.kt, android/src/org/mozilla/firefox/vpn/VPNTunnel.kt, android/src/org/mozilla/firefox/vpn/qt/PackageManagerHelper.java, android/src/org/mozilla/firefox/vpn/qt/VPNPermissionHelper.kt, android/src/org/mozilla/firefox/vpn/qt/VPNWebView.java, src/platforms/android/androidapplistprovider.cpp, src/platforms/android/androidauthenticationlistener.cpp, src/platforms/android/androidcontroller.cpp, src/platforms/android/androidwebview.cpp
Small refactor, as our current namespace does not make any sense :) 
A: Our global package is org.mozilla.firefox.. for legacy reasons. 
Most but not all of the classes have been under com.mozilla.* - so i changed those so they are consistent across the project.
B: We're currently having two independent processes (QT and the Deamon/Service) and you can't see where each file lives.
So i created the subpackage ./QT for stuff jni'd into the qt process since they can't really access the service stuff under ./vpn :)  
Also i removed quite a few unused headers while i'm at it :) 
﻿
=> Android: Cleanup the Namespace

src/platforms/linux/linuxnetworkwatcher.cpp, src/platforms/linux/linuxnetworkwatcher.h, src/platforms/linux/linuxnetworkwatcherworker.cpp, src/platforms/linux/linuxnetworkwatcherworker.h, src/src.pro
The reason why this is needed is that a couple of QT dbus methods do I/O on main-thread and, changing network, it takes a few seconds in which the UI is frozen.
=> Separate thread for linux-network-watcher

android/AndroidManifest.xml, android/build.gradle, android/src/org/mozilla/firefox/vpn/BootReceiver.kt, android/src/org/mozilla/firefox/vpn/NotificationUtil.kt, android/src/org/mozilla/firefox/vpn/Prefs.kt, android/src/org/mozilla/firefox/vpn/VPNLogger.kt, android/src/org/mozilla/firefox/vpn/VPNService.kt, android/src/org/mozilla/firefox/vpn/VPNServiceBinder.kt, android/src/org/mozilla/firefox/vpn/qt/VPNWebView.java, src/loghandler.cpp
** Dont Merge yet. - As this would include dropping support of android <7.  **
-->This is required for the Encrypted Shared prefs and #805 - to force using the v2 APK signature. 
This should address all WP5 related issues.
Disallow Backups of Data (2ca5182)
Closes #803
Encypt Shared Prefs (830231c)
Closes #808
Make the Web-View a secured View (10c90ae)
Closes #804
Stop Posting all Log messages to Logcat on Release Builds (e3b3eba)
Closes #809
Closes #805 - As we require android 7 now.
=>  FVP-02 WP5: Harden android

src/ui/components/VPNControllerView.qml
Touching  #846 - Whilst we need to get this more performant, we can definitely limit the cpu usage when the window is minimized. 
We could also remove Qt.ApplicationInactive condition, so we stop when the window gets out of focus. 
... But's might also look wierdish having the frozen animation in a - non focused window when it's visible.
=> Only allow ring animation if the app is visible

src/ui/components/VPNButtonBase.qml, src/ui/components/VPNFlickable.qml, src/ui/components/VPNIconButton.qml, src/ui/components/VPNLinkButton.qml, src/ui/components/VPNMenu.qml, src/ui/components/VPNServerCountry.qml, src/ui/settings/ViewLanguage.qml, src/ui/views/ViewServers.qml
This PR consolidates and improves the code for scrolling items into view and resolves some personal nits I've been wanting to triage.
- Fixes jumpiness in server list when tabbing through list items
- Better support for upward tabbing
- Uses 'vpnFlickable.ensureVisible' to handle scrolling into view on tab everywhere so that the behavior is consistent across views.
=> Consolidate code for scrolling items into view

src/commands/commandselect.cpp, src/commands/commandstatus.cpp, src/controller.cpp, src/inspector/inspectorwebsocketconnection.cpp, src/localizer.cpp, src/localizer.h, src/models/servercountry.cpp, src/models/servercountry.h, src/models/servercountrymodel.cpp, src/models/servercountrymodel.h, src/models/serverdata.cpp, src/models/serverdata.h, src/notificationhandler.cpp, src/serveri18n.cpp, src/systemtrayhandler.cpp, src/ui/components/VPNServerCountry.qml, src/ui/views/ViewMain.qml, tests/unit/testmodels.cpp
This PR contains the following commits (squashed):
1. rename ServerData::country() to ServerData::countryName()
2. rename ServerData::city() to ServerData::cityName()
3. sort countries/cities when the language changes
4. expose `localizedName` in the ServerCountryModel
5. expose `cities` as an array of QVariant<QStringList> composed by name and localizedName
6. update the tests
=> Sort countries and cities by localized names

src/command.cpp, src/ui/main.qml
This fixes a few Windows UI issues when using multiple displays noticed by @bfyee and referenced in #895.
- Fixes UI distortion triggered by "monitor hopping" the app across multiple displays using Window key + arrow left or Windows key + arrow right.
- Prevents the app from being incorrectly resized on Display #1 when changing the scale of Display #2. 
Before:
After:
=> Fix #895 - Resolution/scaling issues on Windows

src/connectioncheck.cpp, src/connectiondataholder.cpp, src/connectionhealth.cpp, src/connectionhealth.h, src/controller.cpp, src/controller.h, src/controllerimpl.h, src/localsocketcontroller.cpp, src/pinghelper.cpp, src/pinghelper.h, src/pingsender.cpp, src/pingsender.h, src/pingsendworker.h, src/platforms/android/androidcontroller.cpp, src/platforms/dummy/dummycontroller.cpp, src/platforms/dummy/dummypingsendworker.cpp, src/platforms/dummy/dummypingsendworker.h, src/platforms/ios/ioscontroller.mm, src/platforms/ios/ioscontroller.swift, src/platforms/linux/daemon/dbusservice.cpp, src/platforms/linux/linuxcontroller.cpp, src/platforms/linux/linuxpingsendworker.cpp, src/platforms/linux/linuxpingsendworker.h, src/platforms/macos/daemon/macosdaemon.cpp, src/platforms/macos/macospingsendworker.cpp, src/platforms/macos/macospingsendworker.h, src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/windowspingsendworker.cpp, src/platforms/windows/windowspingsendworker.h, tests/unit/moccontroller.cpp
There is a potential race condition when sending ICMP pings for connection health monitoring where closing the tunnel could result
in exposure of the gateway IP address (see issue #801). By binding to the source address when sending a ping, we should prevent this from occurring.
So far I have tested this on Linux and Windows. I've updated the platform code for Android, iOS and Mac while I was at it, but I haven't been able to test any of them yet.
=> Fix #801: Potential race condition in ping sender

src/ui/components/VPNClickableRow.qml, src/ui/components/VPNConnectionInfo.qml, src/ui/components/VPNControllerNav.qml, src/ui/components/VPNControllerView.qml, src/ui/views/ViewMain.qml
Resolves some weird aliasing grief brought about by using Popup{} to show/hide the connection info.
Before:
After:
=> Fix connection info graph pixelation

src/ui/components/VPNIconButton.qml, src/ui/components/VPNToggle.qml, src/ui/components/VPNToolTip.qml
Resolves some awkward tooltip edge-case behavior. 
- Hides the tooltip automatically after 5000ms 
- Hides the tooltip if the user clicks elsewhere in the app
- Hides the tooltip on click release of parent element
=> Add timeout and close policy to VPNToolTip

src/src.pro, tests/unit/unit.pro
In order to be able to build on platforms that don't have fully support for C++17, C++14 should be considered the minimum required.
=> Lower C++ language version to C++14

linux/daemon/helper.sh
OS - Fedora 34. 
/usr/sbin/resolvconf stems to /usr/sbin/resolvconf.openresolv which does not have +x. 
Closes #987
=> Execute resolvconf as a shell script

README.md
When compiling `mozilla-vpn-client` from source I noticed there is a small typo in the README.md or `scripts/generate_glean.py` was renamed recently.
=> Fix script name typo in initialization section

balrog/Makefile, balrog/api.go, balrog/go.mod, balrog/go.sum, src/update/balrog.cpp, src/update/balrog.h
Fixes #797, #798
Instead of rolling our own, we use the new verify module of the mozilla go package autograph (https://github.com/mozilla-services/autograph/).
This allows for simplification of both the api.go code and the update/balrog.cpp. 
In addition, we also resolve the FVP-02-002 and FVP-02-003.
Note, we have verified that balrog algorithm is p384ecdsa which is supported by autograph module.
Thanks to @g-k for splitting out the verify module.
=> Simplify balrog implementation

linux/debian/control.prod.bionic, linux/debian/control.prod.focal, linux/debian/control.prod.groovy, linux/debian/control.stage.bionic, linux/debian/control.stage.focal, linux/debian/control.stage.groovy, linux/debian/mozillavpn.preinst, linux/debian/mozillavpn.service, linux/debian/rules.prod.bionic, linux/debian/rules.prod.focal, linux/debian/rules.prod.groovy, linux/debian/rules.stage.bionic, linux/debian/rules.stage.focal, linux/debian/rules.stage.groovy, src/platforms/linux/daemon/org.mozilla.vpn.dbus.service
When launching the D-Bus service as a bus-activatable service we can start the daemon but we don't have a good way to stop it
during a software update. Adding a systemd service file allows the OS to manage that service when interacting with the package
manager.
However, when upgrading from 2.2.0 and earlier the systemd service file doesn't exist. For these cases we need a preinst hook to kill off any old versions that might be running.
Together, these two changes should ensure that the user can't be left running a version of the daemon that's older than the UI after performing an upgrade via the package manager.
See: mozilla-mobile/mozilla-vpn-client#977
=> Add systemd service file and kill old versions on upgrade

src/captiveportal/captiveportaldetection.cpp, src/captiveportal/captiveportaldetection.h, src/connectionhealth.cpp
2 Bugs here to solve. 
On desktop when the window loses focus, we suspend ping-send worker. This thus we set stability to "stable".
This means when the user connects to a cp-wifi while the app is in the background, we would not start detection. 
Also i limit the amound of Captive Portal requests to only one after we're no longer stable. 
Reason here beeing, connection health might move from stable->instable->noSignal causing 2 cp detections and  2 notifications.
We would need to go to "stable" once again to trigger a new one.
=> Debounce Captive Portal Notification

src/controller.cpp
Since we have #593 still open, we have no code to filter a certain v6 adress out. 
So currently instead we add "[cp-address-v6]/0" to the allowed ipv6 adress ranges, which is not correct.
So i think we should remove this todo for now :)
=> Remove Unresolved CaptivePortal Todo code 

src/src.pro
In a recent commit, 7f44dc826f6c8d6f2bb9533a5d7b5383771360f6, which added a systemd service file, we only added it to the Debian package. This means that a user trying to install from sources can miss the installation of this file via `make install`. Leaving them with an incomplete installation.
See also: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1028
=> Install systemd service file via make install

src/ui/components/VPNSystemAlert.qml
- Changes the sign out alert to green
- Tweaks the sign out message
@flodolo Do you think this requires adding a new string? It is a one word change and, without knowing how this has been handled in other locales, I'm wondering if it makes sense to keep the existing string ID and update the English string only.
=> Fix #780 - Confusing sign out language

src/constants.h, src/models/survey.cpp, src/models/survey.h, src/mozillavpn.cpp, src/tasks/authenticate/taskauthenticate.cpp, src/update/versionapi.cpp, tests/unit/testmodels.cpp
This allows surveys to include a `platforms` array, which lists the platforms on which a survey should be trigger-able, if the array is absent, or empty, then the survey should apply to all platforms.
Closes: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/988
=> Add optional filter for surveys by platform

src/ui/states/StateBackendFailure.qml, src/ui/views/ViewErrorFullScreen.qml
Fixes #834
ToDos:
- add string to ftl file
- get @lesleyjanenorton input on how to make this clickable to open a web page
- @chrisrooneys this is the string i need a copy review on "Check for outage updates on our <a href='https://vpn.status.mozilla.org'>status page</a>." Clicking on the link will take you to a page that looks like https://status.mozilla.org/ but tailored for VPN.
Before:
After:
=> Add status page message.

src/loghandler.cpp, src/loghandler.h, src/platforms/linux/daemon/linuxdaemon.cpp
The linux daemon is started as a D-Bus service by systemd, in which case it will not have a valid $HOME directory and it would be more appropriate to send out logs to /var/log.
Closes: mozilla-mobile/mozilla-vpn-client/issues/1057
=> Linux daemon should output logs to /var/log

src/ui/settings/ViewPrivacySecurity.qml
Removes "settings" from Privacy & Security settings sub-page.
If the new German string is the same as the one on the settings menu view, it will fix #1037 and look like this:
=> Fix Privacy & Security view title

src/apppermission.cpp, src/apppermission.h
In the App Permissions window, it's a little easier to find applications if they are sorted by name instead of application ID.
This would be a fix for #939
=> Sort application list by name

android/AndroidManifest.xml
Bandaid fix for #1067 
This restricts the screen orientation on Android devices to portrait which is consistent with existing behavior on iPhone.
=> Restrict screen orientation to portrait on Android

src/networkrequest.cpp
Of course, this is just the client-side. Then we need extra work to parse the header and follow what the user asks.
=> Use DNT/GPC to inform the server when the user doesn't want to be tracked - closes #1089

src/captiveportal/captiveportaldetection.cpp
From @ValentinaPC  #1066
> VPN ON - Captive Portal checked - connected to a network with CP -> CP notification is displayed -> click on the notification -> nothing happens at click; (this might happen because the VPN does not finalize connection until the user clicks on the notification)
We should allow any state here for the notification to disconnect the connection
=> Allow CP-Deactivation in any State that is not State::OFF

android/src/org/mozilla/firefox/vpn/NotificationUtil.kt
In: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/862/files android/AndroidManifest.xml
we changed the main activity, but i forgot to update the Notification code, so currently on notification tap nothing happens :(
=> Android: Fix Notification Intent

scripts/generate_glean.py
The latest update to glean v3.5 now requires the `glean.js` version passed when invoking `glean_parser`
=> Pass glean version when invoking glean_parser.

src/platforms/linux/linuxnetworkwatcherworker.cpp
The `checkSecurityFlags()` function in the `LinuxNetworkWatcher` returns true whenever an unsecured network is detected but we probably want to emit an `unsecuredNetwork()` notification whenever either the WPA or RSN flags indicate an unsecured network instead of their inverse.
Closes: #1121
=> Fix inverted WPA/RSN security flag checks for Linux

README.md, linux/mozillavpn.spec, scripts/importLanguages.py, scripts/qt5_compile.sh, src/src.pro
After a bit of experimenting, I've been able to build and run the VPN client on Fedora 33 and 34, and I've written a spec file that should enable us to build binary RPM packages out of a git checkout by doing:
```
sudo dnf builddep linux/mozillavpn.spec
rpmbuild -bb linux/mozillavpn.spec
```
Some users have noted problems with SELinux, but I wasn't able to reproduce them in my virtual machine, it just seemed to work for me, even with `getenforce` reporting that SELinux is enabled.
=> Build fixes and RPM packaging for Fedora 33+

src/ui/components/VPNAnimatedRings.qml
In recent builds of the VPN client, I have been experiencing intermittent crashes when loading the main view. Backtraces show that a null `this` pointer is making its way into the OpenGL context during the Qt canvas creation and things go badly from there. I first encountered this on my Fedora/RPM pull request (mozilla-mobile/mozilla-vpn-client/pull/1122) but I think users have been experiencing this in the 2.3.0 release (mozilla-mobile/mozilla-vpn-client/issues/1150)
=> Fix OpenGL framebuffer crash on Linux

glean/pings.yaml
It seems to be missing per https://dictionary.telemetry.mozilla.org/apps/mozilla_vpn/pings/main?showExpired=1
=> Add data review URL for Mozilla VPN metrics

linux/debian/mozillavpn.service, src/apppermission.cpp, src/commands/commandui.cpp, src/featurelist.cpp, src/platforms/linux/daemon/apptracker.cpp, src/platforms/linux/daemon/apptracker.h, src/platforms/linux/daemon/dbusservice.cpp, src/platforms/linux/daemon/dbusservice.h, src/platforms/linux/daemon/dbustypeslinux.h, src/platforms/linux/daemon/org.mozilla.vpn.dbus.xml, src/platforms/linux/daemon/pidtracker.cpp, src/platforms/linux/daemon/pidtracker.h, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/platforms/linux/daemon/wireguardutilslinux.h, src/platforms/linux/dbusclient.cpp, src/platforms/linux/dbusclient.h, src/platforms/linux/linuxappimageprovider.cpp, src/platforms/linux/linuxappimageprovider.h, src/platforms/linux/linuxapplistprovider.cpp, src/platforms/linux/linuxapplistprovider.h, src/platforms/linux/linuxcontroller.cpp, src/src.pro
This is a rebase of PR  #996 to merge the firewall and daemon together into the same D-Bus servce and to incorporate the changes resulting from the removal of the Linux helper script in commit 2f291e35db90ada46fbbe95c3c0d891364ed3a23
This change still lacks a solution to the shared DNS cache/resolvers provided by systemd, so there still exists a potential for the VPN to be detected by an application excluded from the VPN, but I think that should be addressed as a separate issue.
=> Support per-app VPN on Linux

.github/workflows/android.yaml, .github/workflows/functional_tests.yaml, .github/workflows/linux.yaml, .github/workflows/macos-build.yaml, .github/workflows/test_coverage.yaml, .github/workflows/wasm.yaml, .github/workflows/windows-build.yaml, README.md
Since MozillaVPN release v2.3.0, a new version of `glean_parser` was released that is incompatible with MozillaVPN. To work around it, we must use glean_parser v3.4 or earlier in the github workflow.
This PR is really to test that the automated tests and builds are functioning.
=> Release v2.3.1 glean fixes

src/ui/components/VPNAnimatedRings.qml
This is starting to get into cargo cult programming, but it seems that the issue is still related to changing the renderTarget
programmatically in QML, regardless of whether it occurs in the onComplete handler or elsewhere.
Since it seems that the dynamic selection of the renderTarget was added for an iOS bug it seems a bit more sensible to change the target only for iOS.
Closes: mozilla-mobile/mozilla-vpn-client/issues/1150
=> Fix OpenGL framebuffer crash on Linux again

src/platforms/linux/linuxnetworkwatcherworker.cpp
To help diagnose issue #1176 it would be handy to get a bit more visibility into the WPA and RSN flags being reported by the network manager. So let's log them in case of an unsecured network detection.
=> Linux: Consider network unsecure when both WPA and WPA2 are disabled

src/platforms/linux/linuxnetworkwatcher.cpp, src/platforms/linux/linuxnetworkwatcher.h, src/platforms/linux/linuxnetworkwatcherworker.cpp
Because the `LinuxNetworkWatcherWorker` runs in its own thread, even the delaying call to `checkDevices()` can occur before the main `QEventLoop` starts, leading to potential race conditions. To prevent such races, the `initialize()` call should be invoked from a timer owned by the main `QEventLoop`.
=> Fix segfault if LinuxNetworkWatcher loads before qApp->exec()

src/platforms/linux/linuxnetworkwatcherworker.h
Debugging #1187 I found that initialize() needs to be defined as a public slot.
=> Set LinuxNetworkWatcherWorker::initialize as a public slot

src/signalhandler.cpp, src/signalhandler.h
While testing #1187 I found that somewhere around 2% of the time while handling a POSIX signal, the VPN client will deadlock on the logger mutex. To prevent the problem we can write the signal to a pipe, and use the read end of the pipe to emit the necessary Qt signals to terminate the application gracefully.
Unfortunately, signal safety didn't seem to be the culprit for #1187
=> Fix deadlock due to unsafe signal handling

src/commands/commandui.cpp, src/logger.cpp, src/logger.h
There are two issues here:
- SignalHandler receives signal notifications on random threads. This is fixed
using QMetaObject::invokeMethod to emit signals.
- QmlEngineHolder must be created before MozillaVPN to avoid memory corruption
=> Fix SIGABRT on linux during the shutdown - closes #1187

scripts/inspector.py
I found this tool to be handy when trying to reproduce infrequent crashed by automating GUI actions with shell scripting. For example, to click the connection information button: `./scripts/inspector.py click connectionInfoButton`
=> Add python script to run inspector commands

src/networkrequest.cpp, src/pinghelper.cpp, src/pinghelper.h, src/pingsender.cpp, src/pingsender.h, src/pingsendworker.h, src/platforms/dummy/dummypingsendworker.cpp, src/platforms/dummy/dummypingsendworker.h, src/platforms/linux/linuxpingsendworker.cpp, src/platforms/linux/linuxpingsendworker.h, src/platforms/macos/macospingsendworker.cpp, src/platforms/macos/macospingsendworker.h, src/platforms/windows/windowscommons.cpp, src/platforms/windows/windowscommons.h, src/platforms/windows/windowspingsendworker.cpp, src/platforms/windows/windowspingsendworker.h
To try and make the connection health checker a bit more resilient to packet loss, we should convert the Windows ping sender to use asynchronous calls when sending pings. This allows the ping worker thread to continue sending more pings during the timeout on the lost ping. This prevents `sendPing()` calls from backing up and triggering unnecessary server switching when they all arrive late.
Since the windows implementation was the only one that blocked anyways, it's no longer necessary to have a worker thread at all after converting them to use asynchronous operations.
=> Make ping workers async and remove threading

scripts/importLanguages.py
Using the lconvert command to merge the TS and XLIFF files means that we can now get the engineering English strings to show up immediately in the UI without needing to wait for an automated CI run on the i18n submodule.
=> Merge translations when running importLanguages.py

src/connectionhealth.cpp
The recent PR #1231  introduced a bug where the health check timer would be left running after stopping the connection health check. This would trigger a No-Signal warning even though the VPN is disconnected.
=> Fix: No-Signal shown after disconnecting VPN

README.md
The codeblocks for the MacOS+iOS instructions weren't rendering
correctly, add some code delimiters to address this. This then resulted
in the numbering of these instructions not being sequential, so also
update that to be more explicit.
=> Adjust codeblocks and numbering in README

.gitignore, scripts/qt5_compile.sh, src/platforms/linux/linuxpingsender.cpp
Some miscellaneous improvements for the build process based on my experience building on Debian which I hope other's might find helpful: 
- Log strerror linuxpingsender socket create failure
This helped me diagnose #1252 so others might find it useful.
- Update .gitignore rules for `glean`
With a96253e44482f11745f1d2ddd1ee35d1e90c5d63 scripts/generate_glean.py
was updated to write under 'glean/telemetry' rather than
'glean/generated' `.gitignore` was updated then to reflect this, but
then was updated again with e27252cf59ea28bb16fbfcca78b6ba53abac5fd9.
Since it appears `glean` is indeed writing under `telemetry`, restore
this previous ignore behaviour
- Add .gitignore rule for QT compilation
One of the suggested methods for installing QT5 in the README is to
compile it under `qt/`, so …
=> Misc improvements from linux build

README.md
For Linux, the VPN client requires golang version 1.13 or higher, due to improvements in how Go modules are handled. This can cause problems if the version provided by the package manager is too old (eg: Ubuntu Bionic and Debian 10/Buster). While we try to write our README from the perspective of Ubuntu Focal, calling out the required version explicitly may provide some valuable hints to users on other distros.
=> Add minimum golang version to README

src/update/balrog.cpp
When launching an MSI installer from within the VPN client, the installer generates its logs in UTF-16, which causes them to be printed incorrectly to the client logs, which I think are in UTF-8. To make them a little more readable, we should use a `QTextStream` to convert the character encodings before committing them to the client logs.
=> Convert installer logs from UTF-16 before writing.

src/ui/components/VPNAlerts.qml
While testing some stuff in the windows update code, I think there actually is a bug in the update alert. It seems that when forcing an update using the inspector, most of the time the notification fails to show unless something else triggers the `VPNAlerts` to become visible (such as a survey).
What I think is going wrong is that the `updateAlert` is hidden, causing the parent `VPNAlerts` to be hidden and because the parent is hidden updates to the children's properties are not processed. The fix is to make `VPNAlerts` visible depending on whether an update is recommended and thereby untangle the visibility dependency graph.
Closes: #1254
=> Fix bug preventing update notification from showing

src/platforms/linux/daemon/pidtracker.cpp, src/platforms/linux/daemon/pidtracker.h, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/signalhandler.cpp
The API to the `QSocketNotifier` changed between Qt 5.14 and 5.15, which caused the `SignalHandler` class to stop receiving signals. We can work around the problem by using functions pointer instead of trying to marshal the signal with the `SIGNAL()` macro.
Closes: #1275
=> Fix broken SignalHandler slot connection on Qt<5.15

README.md
Just noticed that we did not update the submodule when upgrading to the new wireguard-apple version.
=> Update wireguard-apple submodule

src/serveri18n.cpp
If we have Spanish as sys language, we might get "es" (which we don't have in our json ) instead of "es_ES" (which we have), so we should just attempt as a last attempt to try "language_LANGUAGE" as a possible present translation :)
=> Fallback attempt to use language code as region for City translation

.github/workflows/linux.yaml, linux/debian/rules.prod.bionic, linux/debian/rules.prod.focal, linux/debian/rules.prod.groovy, linux/debian/rules.prod.hirsute, linux/debian/rules.stage.bionic, linux/debian/rules.stage.focal, linux/debian/rules.stage.groovy, linux/debian/rules.stage.hirsute, linux/mozillavpn.spec, scripts/linux_script.sh
This attempts to update the source bundled generated from `linux_script.sh` to produce output that's suitable for upload to a PPA. This is the simple half of PR #1282 that just ensures we have the necessary files in place without trying to rework the version numbering scheme.
Changes include:
- The `.orig.tar.gz` should be reproduceable when generated from the same commit. This means we need determinstic timestamps, UID/GID and generated content.
- Add package signing support to `linux_script.sh` using GPG keys (debian only, RPMs are still mysterious to me).
- Use `dpkg-buildpackage` to produce the necessary `_souce.buildinfo` and `_source.changes` for PPA upload.
- Fix missing golang Build-Depends for Focal and Bionic
=> Create PPA release bundle from linux_script.sh

android/src/org/mozilla/firefox/vpn/VPNServiceBinder.kt
This is not really well documented but this is the signal Android sends us if the User does an action in the Settings.app that would require the vpn tunnel to be closed. E.g: 
- Disable Always On VPN
- Revoke VPN permission
- Disconnect vpn from the Quicksettings
Closes #1194
=> Detect the Request of the OS to close the vpn connection

src/platforms/android/androidcontroller.cpp, src/platforms/android/androidcontroller.h
Since the signal is:
```   
void statusUpdated(const QString& serverIpv4Gateway,
const QString& deviceIpv4Address, uint64_t txBytes,
uint64_t rxBytes); 
```
I think this should not be `m_server.ipv4AddrIn()`right? Otherwise the ping send worker tries to bind to that and fails.
=> Fix Linux PingSend Worker on Android

src/ui/settings/ViewGiveFeedback.qml
Fixes #1289  - This changes the "Poor" string to "Very Poor" in the app rating view. Regarding the "Excellent" string... we actually do not have an "Excellent" string (I think the strings in the spec may have changed since this was implemented) and so will have to add an "Excellent" string in later releases since we're now in string freeze.
=> Fix #1289 - Use correct string in rating view

.github/workflows/functional_tests.yaml
It turns out we can't upload artifacts with path components in their name, which was causing the upload of logs on a failed test to fail. To fix it, we parse a sensible name out of the test file path.
There was also a problem that using `continue-on-error` actually causes the job to succeed even if the tests fail.
=> Fix log uploads on failed tests

src/pingsender.cpp, src/pingsender.h, src/platforms/linux/linuxpingsender.cpp, src/platforms/linux/linuxpingsender.h, src/platforms/macos/macospingsender.cpp, src/src.pro
Some Linux distros, such as Debian 11, are starting to disable ICMP ping sockets, in which case the least-intrusive way install the VPN and still be able to send pings is to use a raw socket and then acquire `CAP_NET_RAW` either by starting as root or using `setcap cap_net_raw+ep /usr/bin/mozillavpn` after installation.
=> Add fallback to raw sockets in LinuxPingSender

src/ui/main.qml
When telemetry is disabled, or when not on a production build, we get lots of warnings about glean pings being disabled:
```
[14.07.2021 10:10:13.053] Info: Glean disabled: not submitting pings. Glean may still submit the deletion-request ping. (glean.lib.js:1)
```
We can fix this just by not submitting pings only when enabled.
=> Fix glean warnings when telemetry disabled

src/mozillavpn.cpp
The windows installer stops and restarts the client and the daemon, so there is no need to disconnect while downloading the updates.
=> Allow update while connected for Windows builds

src/ui/components/forms/VPNSearchBar.qml, src/ui/components/forms/VPNTextArea.qml, src/ui/components/forms/VPNTextField.qml, src/ui/main.qml
On iOS it is currently quite difficult, in some cases impossible without clicking on another button, to drop focus and close the native keyboard once you've clicked into any of the text inputs.  This lets users bail out of text editing and close the native keyboard by tapping or clicking anywhere outside of the input.
=> Remove TextField/TextArea focus on outside click

src/ui/components/forms/VPNTextArea.qml
VPNTextArea updates to address a few UX asks: 
- Restyles VPNTextArea placeholder text to match other text throughout the app
- Hides placeholder text only after the user starts typing, instead of immediately disappearing when the input receives focus. 
:-------------------------:|:-------------------------:
=> Restyle textarea placeholder text and adjust visibility conditional

src/ui/main.qml
We're getting a QML exception the unit tests due to the `window.activeFocusItem` potentially being null if the app looses focus. This was causing the functional tests to fail when the browser steals focus for the authentication flow.
This bug was introduced in b61249dcd256b6a4c676bd2ec2393efb142bd77e
=> Fix unit tests after window focus changes

src/captiveportal/captiveportalrequest.cpp, src/captiveportal/captiveportalrequest.h, src/ipaddressrange.cpp, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/ui/main.qml
There were a collection of bugs that were breaking the functional tests, including:
- Glean tests broken due to change in ping submission (tests only).
- IPv6 captive portal detection breaks when IPv6 is unreachable.
- IPv6 excluded addresses were incorrectly parsed as IPv4 in `fromIPAddressList()`
=> Fix Functional Tests

src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowsfirewall.cpp, src/platforms/windows/daemon/windowsfirewall.h, src/platforms/windows/daemon/windowssplittunnel.cpp, src/src.pro
**Do not merge, this is currently based on the split tunnel PR**
This creates a set of rules in the WFP, to get a good killswitch. Not quite complete, i.e dnsv6/ dhcpv6 is missing.
Sets the following rules: 
- blockAllTrafffic(LOW_WEIGHT)
- allowTrafficOfAdapter(vpnAdapterIndex, MED_WEIGHT)
- allowDHCPTraffic(MED_WEIGHT))
- allowHyperVTraffic(MED_WEIGHT)
- allowTrafficForAppOnAll(MozillaVPN,MAX_WEIGHT)
- allowTrafficTo(DNS, HIGH_WEIGHT))
The split tunnel driver sets its own rules in this sublayer so they interact with eachother:
-> blockSplittedAppFromTUN(HIGH_WEIGHT)
-> allowSpplittetAppNonTUN(MAX_WEIGHT)
Marking this as wip, since i need to do a bit more testing if the rules currently work as they should. 
... maybe i should write a script that can test that 🤔
=> Windows Firewall Implementation

android/build.gradle
Getting set up on for google play is an interesting iterative process. According to the docs, per my reading, we need to upload a copy of the app to the google play store that contains the billing library before certain features are unlocked.
> To integrate Google Play's billing system, first add a dependency to the Google Play Billing Library in your app. This library provides access to Android APIs that connect you to Google Play. From there, you can access purchase information, query for updates about purchases, prompt a user to make new purchases, and more.
> Once you've added the library to your app, build and publish your app. For this step, create your app and then publish to any track, including the internal test track.
> After enabling Google Play Billing features for your app, …
=> Add billing to dependencies

src/daemon/daemon.cpp, src/daemon/daemon.h, src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowsdaemon.h, src/platforms/windows/daemon/windowssplittunnel.cpp, src/platforms/windows/daemon/windowssplittunnel.h, src/platforms/windows/windowscommons.cpp, src/platforms/windows/windowscommons.h
As afraid, checking the metrics table does not really work except for clean vm's >:c 
I.e NordVPN put's itself into the first spot even when disabled. 
So he's what i want to do instead: 
When the deamon starts before the vpn starts, check what adapter can route to 1.1.1.1, and use that as the "Internet" Adapter.  
For the vpn adapter check the name :)
=> Do not rely on the metrics table to choose right adapters for split-tunnel

src/platforms/linux/linuxapplistprovider.cpp
There is a bug in how applications are found vs. how they are tracked by the daemon that manifests when the `.desktop` file is a symlink to somewhere else on the system. The VPN client uses `QFileInfo::canonicalFilePath()` which collapses and `..` path elements and resolves symlinks, but the daemon gets launch notifications with the absolute file path (eg: symlinks are not resolved). Because we use the filename to match PIDs to an application group, this causes the split tunnelling to fail.
To resolve it, we use the absolute file path instead of the canonical file path when building the application list.
=> Fix app permissions for Flatpak applications

src/pingsender.cpp
I don't have a good explanation for why the generic ping sender was crashing on Bionic builds, but it seems to have something to do with the parameter capture in the lambda expression. Making a separate connection just for the garbage collection of the ping process seems to make the crash go away.
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-814)
=> Fix crash in generic ping sender on Ubuntu/Bionic

.gitignore, android/gradle.properties, android/settings.gradle, android/tunnel/CMakeLists.txt, src/src.pro
Currently as we can only do full compiles for android ... it's a bit slow. 
Let's use ccache, if that is installed on a machine to speed things up. 
Also let's move the .gradle cache to a folder outside of .tmp so it is actually usefull :)
On my old mbp which i'm able to get up to 2x speedup, which is nice :)
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-816)
=> Use ccache if installed for speedups

.github/workflows/android.yaml, scripts/android_sign.sh
This expects a GH Secret set:
AUTOGRAPH_KEY
Test Result: 
https://github.com/strseb/mozilla-vpn-client/actions/runs/1071509877
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-813)
=> CI: Generate Signed Android apks

.clang-format-ignore, scripts/generate_strings.py
I realized that we hard-coded unix paths in commands, and there's no real need to force the script to be run from the root of the repository.
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-820)
=> Allow generate_strings.py to run cross-platform from any path

scripts/generate_strings.py
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-826)
=> placeholder to make windows' compiler happy when there are no strings

src/ui/settings/ViewGiveFeedback.qml
Ergonomic layout enhancement for the in-app feedback form on mobile devices. The design for the changes can be found here: [In-App Feedback Form Figma](https://www.figma.com/file/nPn8jQUlIrhVTqh48wm7UK/In-App-Feedback-Form?node-id=515%3A6056).
**Screenshots**
Mobile (before) | Mobile (after)
:---: | :---:
Desktop (before) | Desktop (after)
:---: | :---:
Resolves #1425
=> Feedback form mobile ergonomic enhancement

src/controller.cpp, src/controller.h, src/platforms/windows/daemon/windowsfirewall.cpp, src/rfc/rfc1918.cpp, src/rfc/rfc1918.h, src/settingsholder.cpp, src/settingsholder.h, src/ui/settings/ViewAdvancedDNSSettings.qml
Since we now control the killswitch, we can now enable dns servers that are also non local. :)
┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/VPN-818)
=> Remove Local DNS restrictions

.github/workflows/android.yaml, README.md, android/AndroidManifest.xml, android/build.gradle, android/src/org/mozilla/firefox/vpn/qt/VPNAdjustHelper.java, android/src/org/mozilla/firefox/vpn/qt/VPNApplication.java, scripts/android_package.sh, src/platforms/android/androidadjusthelper.cpp, src/platforms/android/androidadjusthelper.h, src/src.pro
I this PR I added the Adjust SDK to Android. 
Thanks to @strseb for helping :)
Parts of this PR:
- Added a `VPNApplication` to initialize adjust
- Add the Adjust SDK token as a build variable
- Add a way to call adjust functions from C++
The Adjust SDK will only be initialized and track events if the environment variable `ADJUST_SDK_TOKEN` is defined at build time. Also adjust will use the sandbox environment if the application is build for `debug` and will use the production environment when build for `release`.
=> Add the Adjust SDK to Android

.github/workflows/test_coverage.yaml, scripts/test_coverage.sh
There was a missing space when running the test_coverage script.
=> Fix the unit-test script

src/src.pro
Some Linux distros choose to configure Go differently to how it's assumed to be in the build scripts. When linking against netfilter  on the latest version of Fedora the linker would emit errors because it can't find Go's runtime object code. Linking with `-lgo` resolves these errors.
=> Fixed Go link errors on Linux build.

src/ui/components/VPNExpandableAppList.qml
Closes #1410.
The issue was caused by a QML component that had the expandable app list sub-view set as the default state for the view. When the view was rendered, the app would see that `VPNSettings.protectSelectedApps` is `false` and fire the transition to the hidden state, which caused the screen to flicker. This solution sets the default state of the view to match the "hidden" state. (This means that the app list fades in if the view is selected and `protectSelectedApps` is true, but it's barely noticeable imo.)
=> Fix 'flicker' on App permissions view

src/platforms/windows/daemon/windowstunnellogger.cpp, src/platforms/windows/daemon/windowstunnellogger.h, src/platforms/windows/daemon/windowstunnelservice.cpp, src/platforms/windows/daemon/windowstunnelservice.h, src/src.pro
If the tunnel daemon fails to start, then we can be left in the condition where we never actually started the ring logger, meaning that we might not get any logs as to the cause of the failure. To make debug easier when this occurs, we move the ring logger into its own thread so that it can run asynchronously from whatever the service startup is doing.
Closes: #1548
=> Move windows ring logger into its own thread

linux/mozillavpn.spec, scripts/importLanguages.py, scripts/linux_script.sh
This tries to get a little closer to supporting RPM builds when run from a git checkout, and without needing `linux_script.sh` to do any fixups for us. To build an RPM package this way, you would need to do the following:
- `git clone` to fetch the mozilla-vpn-client project.
- `git submodule init && git submodule update` to fetch the relevant submodules.
- `pip3 install glean_parser==3.5 && ./scripts/generate_glean.py` to generate the telemetry code.
- `sudo dnf builddep linux/mozillavpn.spec` to install the build-dependencies.
- `rpmbuild -ba linux/mozillavpn.spec` to build the package.
This is not yet a complete solution to go from git checkout -> usable RPM, since we still need `glean_parser` and it has no RPM equivalent that I can find.
=> Fix rpmbuild when run from git checkout

scripts/generate_strings.py, scripts/importLanguages.py
When parsing a yaml file, and no byte-order-mark is present, then the file will be assumed to use the system encoding, on Windows this tends to misfire and we try to parse the file as CP-1251 instead of UTF-8. We workaround the issue by explicitly opening the `strings.yaml` as UTF-8.
We also fixed a comment that is out of date after merging #1571
=> Fix pyyaml exception on Windows when parsing strings.yaml

src/platforms/windows/daemon/windowsfirewall.cpp, src/platforms/windows/daemon/windowsfirewall.h
we block all non-tunnel traffic with the killswitch but any dns server reachable through the tunnel may still be used. Lets block all dns traffic unless it's targeted to our dns server from the config. 
closes #1546
=> Block all unallowed dns traffic

src/platforms/linux/linuxnetworkwatcherworker.cpp
On Linux, the network interface watcher checks the active access points over D-Bus to determine if they are connected to an unsecure Wi-Fi network. However, when the Wi-Fi is disconnected, we get a non-empty string, but invalid D-Bus path of `/`. Trying to retrieve the WiFi flags for this bogus path returns invalid `QVariant`, which confuses the unsecured Wi-Fi check.
To fix this, we must ensure that the properties we got back from the Wi-Fi access point are actually valid before continuing with the check.
Closes: #1454
=> Fix unsecured Wi-Fi detection when disconnected

src/ui/components/VPNPanel.qml
=> Fix QML VPNPanel: Binding loop detected for property "height"

src/apppermission.cpp
well if you add a non valid file, we should not show the success banner and not add it to the list. (this will be cleared from there, and you will see the missing apps notification then ) 
-> Maybe we should have also an alert for that :) 
#closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1402#
=> Only add apps that are Valid to the Missing Apps List

android/src/org/mozilla/firefox/vpn/VPNService.kt
Currently, we're moving the vpn service to a foreground service asap. This means we might encounter a notification that did not get a string from the qt-notification handler, so we show the English fallback message.
Going foreground is not needed until we actually connect the VPN and need the service to be alive.
Closes #548
=> Android: Only go Foreground-Service if the vpn is Connected

src/commands/commandui.cpp, src/featurelist.cpp, src/featurelist.h, src/inspector/inspectorwebsocketconnection.cpp, src/models/helpmodel.cpp, src/models/supportcategorymodel.cpp, src/models/supportcategorymodel.h, src/mozillavpn.cpp, src/mozillavpn.h, src/networkrequest.cpp, src/networkrequest.h, src/platforms/wasm/wasmnetworkrequest.cpp, src/qml.qrc, src/src.pro, src/tasks/createsupportticket/taskcreatesupportticket.cpp, src/tasks/createsupportticket/taskcreatesupportticket.h, src/tasks/getfeaturelist/taskgetfeaturelist.cpp, src/tasks/getfeaturelist/taskgetfeaturelist.h, src/ui/main.qml, src/ui/views/ViewContactUs.qml, src/ui/views/ViewErrorFullScreen.qml, tests/auth/auth.pro, tests/auth/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp, tests/unit/mocnetworkrequest.cpp, tests/unit/unit.pro
This PR implements:
- the frontend of the in app support flow
- creating a support ticket on guardian
- an addition to `FeatureList` to load a feature list (unauthSupportEnabled in this case) from guardian
- enable the unauthenticated in app support form if enabled
=> implement in app support client side with additions to featurelist

src/mozillavpn.cpp, src/mozillavpn.h, src/ui/settings/ViewAppPermissions.qml
Note: This should not be merged until we have the right sumo article and changed the url.
Also wierd, our font seems to be failing on `we’ve`
=> Add a link to split-tunnel help page

src/controller.cpp, src/platforms/windows/windowsnetworkwatcher.cpp, src/qml.qrc, src/rfc/rfc4193.cpp, src/rfc/rfc4193.h, src/settingsholder.cpp, src/settingsholder.h, src/ui/components/VPNViewDNSSettings.qml, src/ui/settings/ViewAdvancedDNSSettings.qml, src/ui/settings/ViewNetworkSettings.qml, translations/strings.yaml
This is based on #902 
With our Code for custom dns in place, we can extend the feature to offer ad-blocking and/or tracking blocking dns servers. 
Which i think would be nice :) 
┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/VPN-796)
=> ✨Experiment✨ Extend custom DNS with AD & Tracking Protection

src/commands/commandselect.cpp, src/commands/commandselect.h, src/commands/commandstatus.cpp, src/connectiondataholder.cpp, src/constants.h, src/controller.cpp, src/controller.h, src/inspector/inspectorwebsocketconnection.cpp, src/models/servercountry.cpp, src/models/servercountrymodel.cpp, src/models/servercountrymodel.h, src/models/serverdata.cpp, src/models/serverdata.h, src/mozillavpn.cpp, src/mozillavpn.h, src/notificationhandler.cpp, src/settingsholder.cpp, src/settingsholder.h, src/systemtrayhandler.cpp, src/ui/components/VPNServerCountry.qml, src/ui/components/VPNServerLabel.qml, src/ui/settings/ViewNetworkSettings.qml, src/ui/views/ViewMain.qml, tests/auth/mocmozillavpn.cpp, tests/unit/moccontroller.cpp, tests/unit/mocmozillavpn.cpp, tests/unit/testmodels.cpp
This extends the `ServerData` class to hold an exit server and optional entry server, which permits the configuration of multihop tunnelling. From QML, this can be achieved by providing optional parameters to the `VPNCurrentServer.update()` or `VPNController.changeServer()` methods. When those options are omitted, only a single hop is used.
For example: `VPNController.changeServer("aq", "McMurdo Station", "ca", "North Pole")`
While we were at it, we also added a recent connections list to the `SettingsHolder` class which contains a list of up to 5 recent connections.
=> Add settings to hold multihop entry server

src/pinghelper.cpp
The server test has been unstable for a while, and examining the logs it seems that we have a bug with the ping statistics that treats a latency of zero as a lost ping. This is unlikely in real life, but for the dummy client this results in connection instability and server switches.
The test instability occurs, because pings that are less than 1 second old are ignored from loss calculation, resulting in a few seconds of delay before the instability manifests and opens a timing window for a race with the test driver.
The fix is to consider a ping latency of zero as valid.
Closes: #1640
=> Fix ping loss calculation if latency is zero

src/ui/settings/ViewAdvancedDNSSettings.qml
Open DNS view to correct tab based on the user's DNS setting.
Fixes #1653
=> Fix #1653 - Open DNS view to correct tab

src/controller.cpp, src/controller.h
When performing a server switch, we store the server country and city codes in the `Controller` class, and change the server on receipt of the `disconnected()` signal. However, for this to work for multihop we need to store both the entry and exit server.
=> Fix bug in multihop server switch that reverts to single-hop

src/daemon/daemonlocalserverconnection.cpp, src/daemon/daemonlocalserverconnection.h, src/localsocketcontroller.cpp
We have encountered a sporadic assert when activating multihop connections on MacOS and Windows. This seems to be caused by generating a `connected()` signal for each peer in a multihop connection while the `Controller` class only expected a single signal for the exit server.
```
[31.08.2021 15:44:59.796] Debug: (controller - LocalSocketController) Reading
[31.08.2021 15:44:59.796] Debug: (controller - LocalSocketController) Parse command: {"type":"connected"}
[31.08.2021 15:44:59.796] Debug: (controller - TimerController) TimerController - Operation completed: 2 1
[31.08.2021 15:44:59.797] Error: ASSERT: "m_state == None" in file /Users/okirby/Work/mozilla-vpn-client/src/timercontroller.cpp, line 139 (timercontroller.cpp:139)
```
To fix this, we should pass the hopindex from daemon to …
=> Fix assert when activating multihop on Mac and Windows

src/platforms/android/androidiaphandler.cpp, src/platforms/android/androidiaphandler.h
Should close https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1686 - we kinda have a race condition here :) 
From QA logs 
```
09-02 10:05:46.080  6703  6723 I System  : Loaded time zone names for "c_DEFAULT_Default" in 12ms (12ms in ICU)
09-02 10:05:46.086  6703  6703 W System.err: java.lang.NoSuchMethodError: no non-static method "Lorg/mozilla/firefox/vpn/InAppPurchase;.<init>()V"
{....}
09-02 10:05:46.103  6703  6703 F zygote64: java_vm_ext.cc:504] JNI DETECTED ERROR IN APPLICATION: java_object == null
```
=> Init IAP handler lazy to handle onCreateRace

README.md, scripts/xcode_patcher.rb
To build for iOS, we lack a script to build Qt from sources so it's only really practical to use the Qt online installer for iOS development.
We also have a problem that the `APP_ID_MACOS` and `GROUP_ID_IOS` variables don't get expanded when used by Xcode, so for code-signing to work we must set them in the `config.build_settings` dictionary for that to succeed.
=> Fix xcode patcher for iOS and MacOS builds, update Readme

src/pingsender.cpp
RE: Android-Samsung devices which fail to confirm connection: #637 
It seems on some OEM's executing ping does require root, or ping might not even be present.
We should check if the QProcess fails to start and handle it. 
The handling itself is up to debate, if we can't use ICMP ourselves and can't use the ping bin either, I would propose to just fake it for now, which is probably better than devices being falsely blocked from connecting :)
=> GenericPingSender handle QProcess::ProcessError

android/src/org/mozilla/firefox/vpn/qt/VPNWebView.java, src/platforms/android/androidauthenticationview.qml, src/platforms/android/androidwebview.cpp, src/platforms/android/androidwebview.h
We should clear that on close, so people can't get stuck like #1657
closes #1657
=> Clear WebviewStorage on Auth abort

src/dnshelper.cpp
Since a custom v6 DNS is rare, we should disable those while i figure out why the v6 dns fwp_condition_values is corrupting the memory but other v6 fwp_values work fine🙈 
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1633
=> Disable v6 custom DNS for now

linux/debian/mozillavpn.service, linux/debian/rules.bionic, linux/debian/rules.focal, linux/debian/rules.groovy, linux/debian/rules.hirsute
After moving `mozillavpn.service` and replacing it with a symlink in commit 92beeb927c79ae90b282ce83a8d2c63518dcea00, we broke the systemd helpers in the Debian packages. To fix it, we remove the symlink and override the systemd debhelpers with the path to the real `mozillavpn.service` file.
=> Fix systemd packaging for Debian

src/daemon/daemonlocalserverconnection.cpp
When the client is able to send JSON commands to the daemon faster than the Qt event loop is able to process them, this can lead to data getting queued up on the socket, but without generating a `readyRead()` signal. This manifests as instability in the daemon where some commands get delayed for ridiculously long periods of time.
To resolve the issue, keep calling `readAll()` until it returns an empty `QByteArray`, indicating that the socket was empty or an error occured.
Closes: #1706
=> Fix MacOS local socket hang on queued JSON commands

src/platforms/android/androidiaphandler.cpp
Crash reason for https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1686
```
QAndroidJniObject javaClass(CLASSNAME);
```
This line creates an instance of CLASSNAME. But as this does not have a default constructor it is null; jni causes a crash on ```env->GetObjectClass(javaClass.object<jobject>()); ```
=> Do not create an IAP Handler Obj

src/ui/views/ViewGetHelp.qml
Unlocking the developer menu produces a QML error due to a typo of the `restart()` method, which also means that the unlock counter doesn't get reset after 10s of inactivity anymore.
```
[07.09.2021 11:14:37.965] Warning: qrc:/ui/views/ViewGetHelp.qml:44: TypeError: Property 'restaabrt' of object QQmlTimer(0x3fe2470) is not a function (ViewGetHelp.qml:44)
```
=> Fix developer unlock timer due to typo

src/models/servercountrymodel.cpp, src/models/servercountrymodel.h, src/mozillavpn.cpp, src/mozillavpn.h, src/ui/views/ViewServers.qml, tests/unit/testmodels.cpp
On the server selection view, when switching from single-hop to multihop, the entry server is left uninitialized, which looks weird and inconsistent. To fix this, we make `ServerCountryModel::pickRandom()` invokable by QML and use it to pick an entry server at random.
=> Choose a random entry server when loading multihop tab

tests/functional/testOnboarding.js, tests/functional/testSettings.js
During the settings refactoring, it seems that the naming and ordering of the help links changed, resulting in a bunch of broken tests. This should hopefully fix them.
The tests were also hanging by failing to wait for an animation to complete when returning from the feedback view.
=> Fix functional tests that touch getHelpLinks

src/notificationhandler.cpp
When changing only the entry server for a multihop connection (or switching from single to multihop), the VPN client can generate a confusing server switch notification (eg: "Switched from Mos Eisley, Tatooine to Mos Eisley, Tatooine"). Since a proper fix for this likely requires a string change, we can work around the issue by simply supressing the notification when the exit server is unchanged.
See: #1719
=> Disable switch notifications when exit server is unchanged

src/ui/components/VPNFeatureTourPopup.qml, src/ui/components/VPNIconAndLabel.qml, src/ui/settings/ViewWhatsNew.qml
Fixes longer titles not wrapping in the “WhatsNew” overview list.
| --- | --- |
| <img width="472" alt="text-not-wrapping" src="https://user-images.githubusercontent.com/13835474/132316128-75bb4d55-8138-4886-b6d4-b76de49f8f87.png"> | <img width="472" alt="text-wrapping" src="https://user-images.githubusercontent.com/13835474/132316154-89d701ca-f86d-4d68-a930-d0e54daba7bf.png"> |
=> Wrap “WhatsNew” overview title

src/ui/settings/ViewSettingsMenu.qml
In case we do not have any new features that we would like to show this hides the WhatsNew menu item in the settings view.
=> Hide WhatsNew in settings when there are no new features

src/ui/components/VPNAlert.qml
The Unicode character added in #1728 to create space between `alertText` and `alertActionText` and fix #1455 is rendering as a smiley face on Windows (though not on macos, ios, or android emulators- need someone with a Linux machine to check on Linux). Injecting a blank space `" "` is correctly interpreted by the Windows build however. This adds a `whiteSpaceCharacter` property variable that checks if the platform is Windows and sets itself to `" "` or `\u0001` accordingly.
The smiley face:
=> Don't use Unicode character in alert strings on Windows

android/src/org/mozilla/firefox/vpn/VPNServiceBinder.kt, src/dnshelper.cpp, src/platforms/android/androidcontroller.cpp
Android Builder.addDNS rejects a loopback address, so we should disable this. 
Also added some error handling so an invalid config won't deadlock the client. :) 
closes #1785
=> Disable loopback as valid dns on android

src/platforms/windows/daemon/dnsutilswindows.cpp, src/platforms/windows/daemon/dnsutilswindows.h, src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowsdaemon.h, src/platforms/windows/daemon/windowsfirewall.cpp, src/platforms/windows/daemon/windowsfirewall.h, src/platforms/windows/daemon/wireguardutilswindows.cpp, src/src.pro, windows/tunnel/addressconfig.go
When relying on the Wireguard Go module to configure DNS, we find ourselves with a chicken-and-egg bug in Windows when multihop is enabled. The DNS server lists need to be provided when creating the interface, but that is typically done for the entry server, however, we aren't given the DNS configuration until we configure the exit server, which is configured last.
To resolve the issue, we implement the `DnsUtils` class for Windows and remove the DNS setup from the Go module, which conveniently takes us one step closer to completing #1526
Closes: #1673
=> Implement DNS utils for Windows

src/ui/components/VPNAlerts.qml
Sorry, for some reason StackView is not defined in the callback - so pressing the update action won't do anything.
=> Fix UpdateAlert

src/src.pro
On macOS SVGs didn’t show anymore when building the app with QT Creator and the application output logged the warning `svg: Unsupported image format` for multiple SVGs — this fixed the issue.
| before | after |
| --- | --- |
| <img width="472" alt="macos-svg-error" src="https://user-images.githubusercontent.com/13835474/133254023-86287780-d63d-465f-ae2b-cfcd9a9a33cc.png"> | <img width="472" alt="macos-svg-fixed" src="https://user-images.githubusercontent.com/13835474/133253996-bae633cc-efaf-4234-a324-461a65f741d1.png"> |
=> Fix SVGs not showing on macOS

src/ui/components/VPNSubscriptionOption.qml
This updates the layout of pricing options in the IAP view, per feedback from the App Store reviewers.
=> Update IAP view per AppStore review feedback

android/src/org/mozilla/firefox/vpn/VPNService.kt, android/src/org/mozilla/firefox/vpn/VPNServiceBinder.kt, src/connectioncheck.cpp, src/platforms/android/androidcontroller.cpp
The connection gets stuck because,  in ConnectionCheck::start() we fetch the ping destination via the Controller::Status event. 
On android, we did get the current server gateway on the android-controller - so when the system started the vpn via always-on this would still be null. So ConnectionCheck fails silently. 
Since the server's gateway is not part of the wg-conf obj, let's pass the whole "connect" args json, so the VPNService can respond with the appropriate server gateway in Controller::Status. :)
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1179
=> Android: Fix Contoller::Status callback when activated by always-on

src/constants.cpp, src/constants.h, src/platforms/wasm/wasmnetworkrequest.cpp, src/settingsholder.cpp, src/settingsholder.h, tests/unit/mocnetworkrequest.cpp
We should use Constants::API_STAGING_URL as Default setting value if MVPN_API_BASE_URL is not present - Otherwise auth uri might be empty when unset;  thus we get stuck on windows (we crash on android) ... also I don't want to copy our guardian uri every time I install a debug build on my phone :) 🙈
=> Use Constants::API_PROD as default value for Stage_server if none is given

src/features/featurecustomdns.h
Regressed by: https://github.com/mozilla-mobile/mozilla-vpn-client/commit/e27252cf59ea28bb16fbfcca78b6ba53abac5fd9#
My initial pr actually did not flip the feature flag for IOS when it should have, as @mbirghan wrote the required supporting code. 
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1852
=> Enable Advanced DNS for all

src/apppermission.cpp, src/captiveportal/captiveportal.cpp, src/captiveportal/captiveportalrequest.cpp, src/controller.cpp, src/featurelist.cpp, src/localizer.cpp, src/models/devicemodel.cpp, src/models/feature.cpp, src/models/keys.cpp, src/models/servercountrymodel.cpp, src/models/survey.cpp, src/models/surveymodel.cpp, src/models/whatsnewmodel.cpp, src/mozillavpn.cpp, src/networkwatcher.cpp, src/networkwatcher.h, src/platforms/ios/iosiaphandler.mm, src/platforms/macos/macosstartatbootwatcher.cpp, src/platforms/macos/macosstartatbootwatcher.h, src/platforms/windows/windowsapplistprovider.cpp, src/platforms/windows/windowsstartatbootwatcher.cpp, src/platforms/windows/windowsstartatbootwatcher.h, src/settingsholder.cpp, src/settingsholder.h, src/settingslist.h, tests/unit/testmodels.cpp
This is a big refactoring of how we expose setting "properties". There is a new file (`settinglist.h`) containing a map of the properties. And this map is included in multiple ways to give different meetings to the `SETTING` macro.
=> Settings refactoring

src/controller.cpp
In order to access the internal Mullvad network of proxies servers, we need to add them explicitly to the allowed IP ranges since the internal Mullvad network may overlap with the 10.0.0.0/8 private address range.
The private IPv4 address range of the Mullvad network isn't explicitly described anywhere, so the size of this prefix range as 20-bits is just a guess. At present there are 427 Wireguard servers in the network and the 3rd digit is always zero or one, so we could probably get away with a /23 prefix but that leaves very little room for growth if Mullvad adds more servers.
Closes: #1872
=> Allow access to Mullvad proxy network

src/daemon/daemon.cpp, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/platforms/linux/daemon/wireguardutilslinux.h
When switching servers with multihop enabled, this can sometimes result in changing a peer's configuration but without choosing a new peer. This results in a sequence of calls where we `updatePeer()` to set its config, and then immediately `deletePeer()` to remove it.
The fix is that we should only call `deletePeer()` on the old public key, if that key has changed.
Closes: #1875
=> Fix hang on multihop server switch if one hop is unchanged

src/controller.cpp, src/inspector/inspectorwebsocketconnection.cpp, src/localizer.cpp, src/localizer.h, src/models/server.cpp, src/ui/components/VPNRecentConnections.qml
To address the assert when switching to a server in the US from the recent connections list, we need to remove the case mangling when QML is attempting to parse the recent connections. However, since this feature has already shipped, we may need to handle users for whom the recent connections list may contain malformed city names.
To handle this, and other possible server list edge cases (such as a server being removed), we replace the asserts in the connection activation procedure with a backend failure. This leads to a clunky user experience if such an edge case can occur, but it is presumably much better than crashing the client.
While we're at it, we also make an attempt to resolve the localization problems in the recent connections list.
Closes: #1878
=> Fix assert when switching to recent connections

android/AndroidManifest.xml
Starting early next year Google will require new permissions to read Google Advertiser ID which is required by the Adjust SDK. 
Documentation:
https://help.adjust.com/en/article/get-started-android-sdk#add-permissions
https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient.Info#public-string-getid
=> Adding permissions needed for Android 12

src/ui/components/VPNViewDNSSettings.qml
Now that the advanced DNS menu is visible while connected, we need to make sure that the fields are not editable while connected, and unfortunately, I missed the custom DNS field.
Closes: #2162
=> Disable editing of custom DNS while connected

src/featurelist.cpp, src/features/featureuniqueid.h, src/networkrequest.cpp, src/src.pro
Given that we are close to fix-freeze we might consider not sending the device id to guardian. - This would Mean 2.7 would still have the device-duplicate issue but we gain a whole cycle to debug this.
=> Do not send unique ID to the prod server

src/mozillavpn.cpp
Adding that line there, we broke the logoutObserver. The LogoutObserver monitors the authentication state and that _must_ run after a reset. Note that reset() calls `setUserAuthenticated(false)` too.
=> Restore the login after a logout - closes #1254

src/main.cpp
This code allocates a console for windows debug builds.  Since you can't see std::out, we need to do this to see the logs.
=> Add a console to windows to see debug

scripts/xcode_patcher.rb
Closes #2129 
This issue only happens on older iOS versions (before 14.3) since these versions do not have `AdServices.framework` installed. This PR sets the `AdServices.framework` to optional which prevents the app from crashing if it cannot be found. 
References:
https://githubmemory.com/repo/BranchMetrics/ios-branch-deep-linking-attribution/issues/1116
https://developer.apple.com/forums/thread/12110
https://gist.github.com/onevcat/033cc4eb4f0cc29cce56#file-xcodeproj_build-rb-L48
=> Set AdServices.framework to optional

android/src/org/mozilla/firefox/vpn/qt/VPNUtils.kt
Fixes 2 Issues:
-> Writer & Outstream were not flushed, not all text might be written to the file.
-> Change mime-type from text/plain to "any" - some applications (i.e slack) are handling text/plain intents "wrong" as in they try to read "EXTRA_TEXT" (which is empty) and ignore the attachment file. Applications that can handle "any" have a higher probability to check the attached file :)   
#closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2226
=> Android: Fix Log Share

src/controller.cpp
PR #2239 changed the way allowedIps are calculated.
This broke the connection on iOS. I do not know why and this will need further investigation but this fixes the issue for now.
=> Use catch all allowedip for iOS

README.md, tools/inspector/package.json
We need to set the --public-url, otherwise parcel will import everything from `/`  :D
=> Fix Github pages path for the inspector

.github/workflows/ppa-automation.yaml
This should also trigger the PPA automation workflow when pushing a release tag to github, and will ensure that the build-revision mangling is removed when doing so.
Some food for though: Would it be worthwhile uploading the signed source bundle (or any other build artifact) as a release asset on github?
=> Add PPA automation for tagged releases

src/platforms/android/androidcontroller.cpp
VPNBinder is not guaranteed to be in the qapp thread, so instead of letting it call a func in androidcontroller it should only use emits :) 
Otherwise we might access the l18n via some subthread and fail here:
```
11-16 14:28:37.951 24769 24769 D mozillavpn: (Parent is QApplication(0x7530611df0), parent's thread is QThread(0xb4000075ccd7b790), current thread is QThread(0xb4000075ccdb7b10)
11-16 14:28:38.050 24769 24799 D mozillavpn: [16.11.2021 14:28:38.050] Error: QQmlEngine: Illegal attempt to connect to QQmlPropertyMap(0xb4000075ccdb7ef0) that is in a different thread than the QML engine QQmlApplicationEngine(0x7530611a68.
```
=> Fix Crash in androidController::Binder::init

android/src/org/mozilla/firefox/vpn/qt/VPNActivity.java
We don't use the clipboard on android 10>, so no need for QT to read it, as it might creep out people :) 
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2183
=> Android: Disable qt's read-access to the clipboard

android/src/org/mozilla/firefox/vpn/VPNLogger.kt, android/src/org/mozilla/firefox/vpn/VPNService.kt, android/src/org/mozilla/firefox/vpn/VPNServiceBinder.kt, src/platforms/android/androidcontroller.cpp
VPNService::turnOn can throw, but we did not catch that in the always-on path. 🙈 
Let's handle it and also while at it, make sure our logs are more insightful to what the exception/activation error is. 
#closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1863
=> Android: Fix crash in onStartCommand()

src/ui/components/VPNMainImage.qml
Adds additional states to the status indicator for when the VPN is on but the connection is unstable or lost.
**Design**
[Figma spec](https://www.figma.com/file/ziJ5tGCqhfst4svjtKJlbr/2.7--Feature-Enhancements?node-id=1%3A1631)
**Screenshots**
| VPN on & unstable | VPN on & no signal |
|---|---|
|<img width="100" alt="unstableOn" src="https://user-images.githubusercontent.com/13835474/142024087-e5cd39f5-04ae-4c89-bf44-264e1033afce.png">|<img width="95" alt="noSignalOn" src="https://user-images.githubusercontent.com/13835474/142024122-a03721b3-fa74-44b1-8a3d-465cc0974a2c.png">|
=> Status indicator states for unstable and lost connection

.github/workflows/wasm.yaml
Qt6 is not ready for wasm. We need to keep qt5 around.
=> Reintroduce wasm with qt5

ci_scripts/ci_post_clone.sh, scripts/apple_compile.sh
This PR removes the lines that set the build system to legacy from the `xcsettings` file. 
We have to do it this way since `Xcodeproj` does not allow us to change those files. 
Due to this change we can remove the part of the ci_scripts for iOS that were doing this.
=> Remove line that sets the build system to legacy

src/daemon/daemon.cpp, src/daemon/daemon.h, src/daemon/daemonlocalserverconnection.cpp, src/daemon/daemonlocalserverconnection.h, src/daemon/wireguardutils.h, src/localsocketcontroller.cpp, src/localsocketcontroller.h, src/platforms/linux/daemon/dbusservice.cpp, src/platforms/linux/daemon/dbusservice.h, src/platforms/linux/daemon/org.mozilla.vpn.dbus.xml, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/platforms/linux/daemon/wireguardutilslinux.h, src/platforms/linux/dbusclient.h, src/platforms/linux/linuxcontroller.cpp, src/platforms/linux/linuxcontroller.h, src/platforms/macos/daemon/macosdaemon.cpp, src/platforms/macos/daemon/macosdaemon.h, src/platforms/macos/daemon/macosroutemonitor.cpp, src/platforms/macos/daemon/macosroutemonitor.h, src/platforms/macos/daemon/wireguardutilsmacos.cpp, src/platforms/macos/daemon/wireguardutilsmacos.h, src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowsdaemon.h, src/platforms/windows/daemon/windowsroutemonitor.cpp, src/platforms/windows/daemon/windowsroutemonitor.h, src/platforms/windows/daemon/wireguardutilswindows.cpp, src/platforms/windows/daemon/wireguardutilswindows.h, src/src.pro
This attempts to make the activation and server switch of a multihop connection a bit more reliable by waiting for each peer to come up before starting the next one. This also enables us to get feedback on the individual servers being used and makes the procedure a bit more reliable.
In the process of testing this, it was discovered that we have a race condition when switching entry servers. This occurs because the routes to the entry server are set up by carefully excluding them from the allowed IPs of the exit server, but during a server switch we find ourselves in the situation where we are switching the entry server while still using the old exit server's allowed IPs. As a resolution to this problem, we introduce route monitoring to the desktop platforms, and use it to bind the entry …
=> Delay multihop peer startup based on handshake completion

src/adjust/adjustproxyconnection.cpp, src/adjust/adjusttasksubmission.cpp, src/authenticationinapp/authenticationinapp.cpp, src/authenticationinapp/authenticationinapplistener.cpp, src/captiveportal/captiveportaldetectionimpl.cpp, src/captiveportal/captiveportalmonitor.cpp, src/captiveportal/captiveportalrequest.cpp, src/captiveportal/captiveportalrequesttask.cpp, src/connectiondataholder.cpp, src/controller.cpp, src/mozillavpn.cpp, src/platforms/android/androidiaphandler.cpp, src/platforms/ios/iosiaphandler.mm, src/platforms/wasm/wasmauthenticationlistener.cpp, src/tasks/accountandservers/taskaccountandservers.cpp, src/tasks/adddevice/taskadddevice.cpp, src/tasks/authenticate/desktopauthenticationlistener.cpp, src/tasks/authenticate/taskauthenticate.cpp, src/tasks/captiveportallookup/taskcaptiveportallookup.cpp, src/tasks/createsupportticket/taskcreatesupportticket.cpp, src/tasks/getfeaturelist/taskgetfeaturelist.cpp, src/tasks/heartbeat/taskheartbeat.cpp, src/tasks/ipfinder/taskipfinder.cpp, src/tasks/products/taskproducts.cpp, src/tasks/removedevice/taskremovedevice.cpp, src/tasks/sendfeedback/tasksendfeedback.cpp, src/tasks/surveydata/tasksurveydata.cpp, src/timercontroller.cpp, src/update/balrog.cpp, src/update/versionapi.cpp
Often we do not pass a 'context' param when connecting signals/slots via
functor. We should because in this way objects are automatically disconnected
when destroyed.
=> Fixing the parenting of QObjects

src/commands/commandui.cpp
When terminating the desktop session, the default termination provided by Qt often results in a hung logout session due to the minimize-on-quit behavior of the main window.
Furthermore, logging out of the desktop session with the VPN connected may leave the tunnel active even though the GUI has exited. This can lead to confusing connection behavior when logging back in. To remedy this, it is safer to disconnect the VPN when handling session termination.
Closes: #2370
=> Gracefully support QSessionManager termination

src/fontloader.cpp, src/systemtraynotificationhandler.cpp
On Linux, it seems that we fail to load fonts and assets from the Nebula QRC archive, which leads to warnings warnings in the `QFontDatabase` about missing system fonts, and breakage in the system tray due to misising country flags.
=> Fix QRC resource loading after Nebula refactor

translations/strings.yaml
Strings that will be needed for the [“Server unavailable” modal](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/2419#issue-796124399).
=> Add strings for “Server unavailable” modal

nebula/ui/components/VPNAlert.qml
There was already an attempt to make the alert banner width consistent with PR #1882. Unfortunately, it seems like I did not resolve a merge conflict with `main` correctly and the significant change for fixing this issue was lost. 
Resolves #1754
=> fix: Alert banner width

src/features/featuremultihop.h
Updates the icon path of the “Multi-hop” feature to point to the new nebula resources.
Fixes #2413
=> fix: Multi-hop feature icon path

nebula/ui/components/VPNGraphLegendMarker.qml
This was due to a missing QML import, leading to error messages in the `VPNGraphLegendMarker.qml` file as follows:
```
qrc:/nebula/components/VPNGraphLegendMarker.qml:19: ReferenceError: VPNl18n is not defined (VPNGraphLegendMarker.qml:19)
```
Closes: #2422
=> Fix missing units in connection info screen

src/constants.h
The recent refactoring for Nebula moved the `logo-dock.png` into the Nebula directory, which caused the VPN client to show an empty dock icon.
Closes: #2436
Closes: #2424
=> Fix the logo dock path after Nebula refactor

src/networkrequest.cpp, src/networkrequest.h
The network request to lookup the user's IP address makes use of the raw `Host` header so that we can dispatch the request separately for both IPv4 and IPv6. However, this triggers an SSL error due to the certificate not matching the explicit IP addresses used for the network request. While we are able to ignore the error by calling `QNetworkReply::ignoreSslErrors()` this still generates a lot of noise in the logs, and we are leaving ourselves open to ignoring other certificate errors.
This patch should improve upon this solution by manually checking the certificate's subject names against the raw host header, and suppresses the SSL warning if, and only if, a match is found.
=> Suppress false-positive SSL errors with raw Host headers

src/update/versionapi.cpp
On WASM, the network request life-time depends on how the browser handles
XMLHttpRequest objects. They can be deleted at a different time then what we
expect on other platforms. To unblock the version-API check, we need to call
`deleteLater` manually.
=> Do not use NetworkRequest::destroyed as signal for the versionAPI check

.taskcluster.yml
This will stop running Decision tasks on feature branches. To run tasks
a pull request can still be opened for them.
=> Only run Taskcluster on main + releases/* branches

.taskcluster.yml
Dupe of #2449 - CI was failing since secrets are not filled in on forks 
This will stop running Decision tasks on feature branches. To run tasks
a pull request can still be opened for them.
=> Only run Taskcluster on main + releases/* branches (#2449)

src/ui/main.qml
This zeroes out the height of the wasm menu when `!isWasmApp` and prevents app content from getting awkwardly pushed down on mobile (strangely, desktop is unaffected). 
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td colspan="2">
With visible wasm menu...
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Set wasm menu height to 0 when not visible

src/ui/settings/ViewPrivacySecurity.qml
Fix margin issue in **System preferences**
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix margins in ViewPrivacySecurity.qml/"System preferences"

nebula/ui/components/VPNAboutUs.qml
```
[28.12.2021 10:12:05.224] Warning: qrc:/nebula/components/VPNAboutUs.qml:318: ReferenceError: QtQuick_Window is not defined (VPNAboutUs.qml:318)
[28.12.2021 10:12:05.929] Warning: qrc:/nebula/components/VPNAboutUs.qml:179: TypeError: Cannot call method 'runSoon' of undefined (VPNAboutUs.qml:179)
```
This fixes some console complaints in VPNAboutUs.qml about `runSoon()` and `QtQuick_Window` being undefined. 
Also fixes #2386. Clicking the 'Check for updates' button once again triggers the 'no update' modal to open again.
=> Fix warnings in VPNAboutUs.qml and 'Check for update' button

src/ui/views/ViewMobileOnboarding.qml
Transforming the `height` of the images for the entering transition seems to cause some slight visual _jitter_ for me. Using `Scale` seems to resolve this issue. I also tweaked the transition durations a bit, but I’m not really sure if it’s _better_ and happy to reset to the initial values.
**Before**: Using `height`
https://user-images.githubusercontent.com/13835474/147763905-70cd26fa-22af-4727-adc1-ac6e4ee607f5.mp4
**After**: Using `Scale`
https://user-images.githubusercontent.com/13835474/147763910-80c1217f-043e-45f9-abc7-45a4f68ce221.mp4
=> Mobile onboarding image transitions

.github/workflows/windows-build.yaml, src/commands/commandui.cpp, src/src.pro
Apparently the Lottie.pri is breaking windows builds and the CI did not catch it. 
Something about those 2 lines is making qmake generate a broken vcxproj but i dont know enough currently about how a qml import name would create broken vcxproj include-groups🤷 - See: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2509
```
QML_IMPORT_NAME = vpn.mozilla.lottie
QML_IMPORT_MAJOR_VERSION = 1
```
Since the code path is not relevant for 2.7, let's disable lottie on win so QA can get testable builds for now. 
Also let's have the CI error when there is no final msi.
=> Disable Lottie Support for Windows

src/ui/main.qml
Launches the **Server unavailable modal** #2420 `onReadyToServerUnavailable`.
=> Launch server unavailable modal

src/notificationhandler.cpp, translations/strings.yaml
From the new [spec ](https://www.figma.com/file/OQpyNjmowo3BIE23WGnOCM/Captive-Portal---Additional-Messaging?node-id=14%3A1434) - we did update the new "captivePortalBlockMessage2" - but I missed adjusting the "unblock" message to the new wording. 
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/729
=> Fix string naming in captive_portal unblock

src/captiveportal/captiveportaldetection.cpp
The issue here is: 
-> We detect captive portal.
-> Press deactivate.
-> Doing this, we activate the background-monitor - this will look for a captive portal, to check if it is gone after auth. 
-> Instead we connect to another "secure" network.
-> The still active monitor will now detect "no portal" and send the "captive portal gone" notification but this network never had one in the first place.
So we should deactivate the Monitor once the network changes. 
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2544
=> Deactivate Background Monitor on Network Changes

src/mozillavpn.cpp
In addition to showing the “Server unavailable” modal and launching a system notification we set `StateBackendFailure` which results in showing the error view on `readyToServerUnavailable`. If there isn’t a reason that we need it for something else at this point — let’s remove it.
Resolves #2582
=> Don’t show error screen behind “Server unavailable” modal

src/update/versionapi.cpp, tests/unit/testreleasemonitor.cpp
The use of pre-release version suffixes causes `VersionApi::compareVersions()` to generate bad comparison results by dropping the trailing digit of the release. This in effect, leads to several of the feature API checks to report that features are unavailable when they ought to be. This can be fixed by extracting only the leading substring which contains digits and decimal separators.
Closes: #2584 #2581 #2572
=> Fix version bug when a pre/post release suffix exists.

src/ui/views/ViewCaptivePortalInfo.qml, src/ui/views/ViewMain.qml
Fixes the layout issues for longer locales on the `captive portal` view.
**Design**
[Figma spec](https://www.figma.com/file/OQpyNjmowo3BIE23WGnOCM/Captive-Portal---Additional-Messaging?node-id=14%3A1494)
**Before**
| EN | NL |
| --- | --- |
| <img width="472" alt="captive-portal-layout-before-en" src="https://user-images.githubusercontent.com/13835474/149787923-e3f3ced4-f97d-44fd-b027-ffe383a1eb51.png"> | <img width="472" alt="captive-portal-layout-before-nl" src="https://user-images.githubusercontent.com/13835474/149787942-aedc4009-d3ba-4a23-8fc9-a3bdc9b27970.png"> |
**After**
| EN | NL |
| --- | --- |
| <img width="472" alt="captive-portal-layout-after-en" src="https://user-images.githubusercontent.com/13835474/149788186-0b02f9cf-8e42-4454-ad07-92b7108e8f47.png"> | <img width="472" …
=> fix: Captive portal layout

nebula/ui/components/VPNFeatureTour.qml
In case we only show one feature in the _What’s new_ panel there is a single page indicator that might be confusing. Let’s only show it if there is more than one feature to discover.
| --- | --- |
| <img width="472" alt="single-feature-slide-indicator-before" src="https://user-images.githubusercontent.com/13835474/149816428-ad6f53a7-ddad-4c8b-bb1d-539b8190a79e.png"> | <img width="472" alt="single-feature-slide-indicator-after" src="https://user-images.githubusercontent.com/13835474/149816434-336f740c-d495-4626-bd82-cf0be126a11c.png"> |
=> Hide slide indicator for single tour features

src/networkrequest.cpp
MacOS falls back to a system API call to perform CA trust validation, which will throw a certificate validation warning if the hostname does not match the provided certificate. This warning gets interpreted as an untrusted certificate by Qt and by the time that error reaches the application it's indistinguishable from a genuine untrusted certificate.
The proper fix us to explicitly set the certificate name using `QSslSocket::setPeerVerifyName()` so that MacOS can validate against the expected hostname. This likely makes our workaround in `NetworkRequest::sslErrors()` unnecessary as well.
Closes: #2462
=> Fix certificate validation when a hostname mismatch occurs.

src/platforms/ios/iosiaphandler.mm, src/ui/main.qml, src/ui/views/ViewErrorFullScreen.qml
Fixes #2598 and #2570 
The problem is a random subscription failed event. This causes an error to be shown. 
We should not show an error if we are not in an active subscription process.
The second error happened due to a change in variable names in `ViewErrorFullScreen.qml`
=> Check if we are in an active subscription process before showing error

src/platforms/ios/ioscontroller.swift
A few months ago we removed the `completionHandler` for the sendProviderMessage call in the switching function. 
However, the handleAppMessage function, which receives the provider messages, returns if the `completionHandler` is nil. This might be a bug in the wireguard code. 
By simply adding a `completionHandler` that just returns the message gets handled and the switch works.
=> Add completion handler to the switching call

src/controller.cpp, src/controller.h, src/models/servercountrymodel.cpp, src/models/servercountrymodel.h, src/mozillavpn.cpp, src/mozillavpn.h
When a user tries to connect to an unavailable server the VPN is stuck in `StateDisconnecting`. This PR prevents the VPN from attempting to connect to a city which has all of their servers set to a cooldown period.
Resolves #2583
=> Prevent VPN from reconnecting to a location that is currently “unavailable”

src/platforms/linux/linuxsystemtraynotificationhandler.cpp
When a server unavailable notification occurs on Linux platforms, this can cause an assert in the system tray handler because the notification type is missing from the switch statement.
=> Fix assert in server unavailable notification on Linux

src/ui/settings/ViewGiveFeedback.qml
Closes #2302 
For some reason the transition caused the blank page. Removing it fixed it.
=> Remove transition from stackview.pop

src/features/featuresharelogs.h, src/models/device.cpp, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h
QtAndroid::androidSdkVersion() is gone it Qt6, so we need replacement
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2459
=> Polyfill missing QtSdk()

src/controller.cpp, src/models/server.cpp, src/models/server.h, src/settingslist.h, src/ui/settings/ViewNetworkSettings.qml, translations/strings.yaml
This option allows the user to force their VPN traffic to use UDP port 53/DNS, which may do a better job of evading aggressive network firewalls. This option can be supported generically in all cases except mobile platforms when combined with multihop.
Some room for improvement: 
See: #2621
=> Add option to tunnel VPN traffic on port 53/DNS

nebula/ui/components/VPNAvatar.qml, nebula/ui/components/VPNPanel.qml, src/ui/settings/ViewSettingsMenu.qml
`OpacityMask` as `layer.effect` is not working as expected so that images do not show when compiling with Qt6.
=> Show masked images when using Qt6

src/localsocketcontroller.cpp
When logging out of a MacOS desktop session, while the VPN is connected, we first need to shut down the VPN connection before the client can be safely terminated. Unfortunately, due to the asynchronous nature of socket IO, it often occurs that a `disconnect` command gets written to the socket, but it is never received by the daemon. We can work around this situation by calling `QAbstractSocket::flush()` after writing any command in the `LocalSocketController`
Closes: #2370
=> Fix MacOS session logout bugs

nebula/ui/components/VPNTabNavigation.qml, src/ui/views/ViewMain.qml
Fixes some QML warnings related to `Connections` properties syntax and `undefined` properties in `VPNTabNavigation`.
=> Fix qml warnings

scripts/openssl_compile.bat
Disable engines in openssl so that we do not load them at runtime.
The -DOPENSSL_NO_ENGINES switch disables all use of engines in openssl.  It will still load an openssl.cnf file, but not load any engines from it.
=> Openssl script update

.github/workflows/wiki.yaml, docs/Command-line-interface.md, docs/Home.md
I __really__ like that we now start having stuff in docs/.
How about we push the docs into the Wiki tab of the Repo - so they have a place to be read ? :) 
Example Repo: 
https://github.com/strseb/mozilla-vpn-client/wiki
Example Run:
https://github.com/strseb/mozilla-vpn-client/actions/runs/1819266877
=> Proposal: Expose /docs/📑 in the Github Wiki Tab

src/captiveportal/captiveportalrequest.cpp, src/networkrequest.cpp, src/networkrequest.h
I managed to reproduce a crash:
It seems that we call ::onResult() multiple times. This can happen because an abort() triggers a finished() signal.
```
[11.02.2022 12:48:43.737] Debug: (captiveportal - CaptivePortalRequest) request: http://34.107.221.82/success.txt
[11.02.2022 12:48:43.737] Debug: (networking - NetworkRequest) Network request created by CaptivePortalRequestTask
[11.02.2022 12:48:43.737] Debug: (captiveportal - CaptivePortalRequest) request: http://[2600:1901:0:38d7::]/success.txt
[11.02.2022 12:48:43.737] Debug: (networking - NetworkRequest) Network request created by CaptivePortalRequestTask
[11.02.2022 12:48:43.737] Debug: (networking - NetworkRequest) Network reply received - status: 0 - expected: any
[11.02.2022 12:48:43.737] Error: (networking - NetworkRequest) …
```
=> Do not run CaptivePortalRequest::onResult() after an abort

nebula/ui/components/VPNServerCountry.qml
Fixes the height of items in the server list when compiling with Qt 6 so that inputs are spaced correctly and are not being cut off anymore.
**Screenshots**
|Server list (before)|Server list (after)|
|---|---|
|<img width="428" alt="server-list-before" src="https://user-images.githubusercontent.com/13835474/153628391-337c5705-c3a1-4579-9179-8ae285920780.png">|<img width="472" alt="server-list-after" src="https://user-images.githubusercontent.com/13835474/153628397-bba3202f-8791-43bb-9db6-cc766bd374d3.png">|
Fixes #2649
=> Fix server list spacing

src/controller.cpp, src/mozillavpn.cpp
So 2 Things go wrong here: 
We're refreshing the device key on any update, even though we only need to to it when a key has been used before the 2.5 update. 
Also looking at the video at: 0:51-0:57.  https://mozilla-hub.atlassian.net/browse/VPN-1747
- After refresh  we also scheudle a full account refresh, pulling in the new devices
- We can see on the video the device count now dropped from 5 to 4
- I think the update of the device failed, and thus guardian has removed it. (idk why tho)
- It's likely that the devicemodel no longer includes the current keys. 
- So we should check the nullptr case on activation this is the case. Otherwise we will crash once we deref the device :)
Maybe we should force a full reset() of the app here, so the user can-re login and reauth the device.
=> Pin Device Key regeneration To <2.5

linux/debian/control.impish, linux/debian/control.jammy
A dependency on `Qt.labs.qmlmodels` has recently been introduced, and needs to be added as a Debian package dependency on distributions that supply their own version of Qt5.
Without this package installed, we are unable to open the network settings menu, and receive the following error instead:
```
[16.02.2022 09:50:00.092] Warning: qrc:/ui/views/ViewSettings.qml:35:5: QML VPNStackView: push: qrc:/ui/settings/ViewNetworkSettings.qml:52 Type VPNContextualAlerts unavailable
qrc:/nebula/components/forms/VPNContextualAlerts.qml:7 module "Qt.labs.qmlmodels" is not installed (ViewSettings.qml:35)
```
=> Fix missing QML import of Qt.labs.qmlmodels

nebula/ui/components/VPNMenu.qml, src/ui/developerMenu/ViewDeveloperMenu.qml, src/ui/views/ViewGetHelp.qml
When opening the Get Help menu from the settings view, clicking on the "Get Help" text at the top of the window doesn't trigger the developer unlock, but it still appears to work fine when the menu is accessed from any other view. This appears to be caused by toggling the `visible` property, eventually leading to either missing or mis-routed `onClicked` signals.
It seems that this has already been worked around by using the `VPNMouseArea` component, so let's just use that for unlocking the developer menu in place of a standard QML `MouseArea`
=> Fix developer menu unlock from settings view

src/localsocketcontroller.cpp
Sorry apparently did this on the release branch, i will do a follow-up cherrypick for main later :) 
Marking m_state = eDisconnected; means the deamon socket closed, so pressing the "disconnect" button means we're marking deamon as closed, thus after a new activation we won't listen to handshake response oder "activation completed" signals. :)
=> Stay in eReady when VPN disconnects

src/networkrequest.cpp
See the release version of [QTBUG-100651](https://bugreports.qt.io/browse/QTBUG-100651).
=> HTTP2-redirect hack can be removed after qt6.4.0 - Fixes VPN-1723

lottie/lib/lottie/LottieAnimation.qml, lottie/lib/lottieprivate.cpp, lottie/lib/lottieprivate.h, lottie/lib/lottieprivatewindow.cpp, lottie/lib/lottieprivatewindow.h, lottie/tests/unit/testwindow.cpp, lottie/tests/unit/testwindow.h
There are 2 problems:
- we create the lottie JS component even when the LottieAnimation QML object is not visible
- we do not suspend timers when the object becomes invisible.
=> Suspend the timer execution if the Lottie object is not visible - Fixes VPN-1704

src/commands/commandui.cpp, src/inspector/inspectoritempicker.cpp, src/inspector/inspectoritempicker.h, src/inspector/inspectorutils.cpp, src/inspector/inspectorutils.h, src/inspector/inspectorwebsocketconnection.cpp, src/inspector/inspectorwebsocketconnection.h, src/itempicker.cpp, src/itempicker.h, src/src.pro, src/tutorial.cpp, src/tutorial.h, src/ui/main.qml, tests/unit/testtutorial.cpp, tests/unit/testtutorial.h, tests/unit/unit.pro, tools/tutorialgen/package.json, tools/tutorialgen/tutorialgen.js, tools/tutorialplayer/package.json, tools/tutorialplayer/tutorialplayer.js
This is the engine of the tutorial system for the VPN client. The code works, but we need to add the final UI (not in this PR).
- unit-tests for the tutorial parser
- a tool to generate tutorial files (tools/tutorialgen)
- a tool to test tutorial files (tools/tutorialplayer)
- the parser of the tutorial files (src/tutorial.cpp)
- the QML object to start/stop tutorials (src/tutorial.cpp)
- the inspector hooks
- an example about how to show tooltip QML elements
- the final UI of the tooltips
- the guide view
- the tutorial
A few steps for the use of this code.
The easiest solution is to use the `tutorialgen.js` app. Enter in `tools/tutorialgen` folder and run `npm install` to install the dependencies. Then, start the recording of a tutorial running the command: `node ./tutorialgen.js …
=> Tutorial engine

src/controller.cpp, src/controller.h, src/daemon/daemon.cpp, src/daemon/daemonlocalserverconnection.cpp, src/models/servercountrymodel.cpp, src/models/servercountrymodel.h, src/mozillavpn.cpp, src/mozillavpn.h
This commit reverts the previous workaround in #2610 and fixes the underlying problem by ensuring that the daemon always emits a `disconnected()` signal, even if no attempt was made to  start a connection in the first place.
We also transition to the `Controller::StateConfirming` state as soon as a request has been made to the platform to start the connections. This should allow the user to abort the connection instead of waiting for the server unavailable popup, should the handshake take too long to complete.
We also remove the direct call to `Controller::serverUnavailable()` when setting cooldowns via the inspector, since we should leave it up to the controller to generate this naturally when instructed to activate the connection.
Closes: #2615
Closes: #2775
=> Fix server reconnection issues

nebula/ui/components/VPNButton.qml, nebula/ui/components/VPNMouseArea.qml, nebula/ui/components/VPNUIStates.qml, src/ui/authenticationInApp/ViewAuthenticationSignIn.qml, src/ui/authenticationInApp/ViewAuthenticationSignUp.qml, src/ui/authenticationInApp/ViewAuthenticationStart.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml
This PR does two things:
1. Uses the new VPNAuthInApp states that were introduced by PR #2793 to support transitions in the In-App Auth flow through showing button loaders.
2. Fixes `VPNButton`’s disabled state and style
=> In-App Auth button loaders and disabled style

extension/bridge/Cargo.toml, extension/bridge/src/main.rs, tests/nativemessaging/helperserver.cpp, tests/nativemessaging/helperserver.h, tests/nativemessaging/testbridge.cpp, tests/nativemessaging/testbridge.h
2 issues found:
1. I have not managed to reproduce it yet, but it's something related to do-not-write in stdout. This triggers an exception (panic!) in rust. The fix is to run the read_stdin in a loop
2. the TcpStream is non-blocking and we need to cover scenarios where the `read` returns partial data. I had to get rid of the chome-native-messaging crate and implement something better
=> Read STDIN in a loop in the browser bridge rust app

nebula/ui/components/VPNExpandableAppList.qml, nebula/ui/components/forms/VPNContextualAlert.qml, src/ui/settings/ViewAppPermissions.qml, src/ui/settings/ViewNetworkSettings.qml
I thought this would be a fast fix but it turned into something else. This fixes #2682, then fixes a binding loop and some anchor warnings in the app permissions view. It also refactors for better handling of text wrapping/responsiveness to app width changes (which only _really_ matters to us in a landscape-mode-enabled future when app width can change). 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th colspan="3">Also verified on Android and Windows</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</table>
=>  Fix #2682

nebula/ui/components/VPNIconAndLabel.qml, src/ui/settings/ViewWhatsNew.qml
<table>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> nit: Fix vertical alignment of settings menu button text

nebula/ui/components/VPNFlickable.qml
Fix #2879 
<table>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>
Before
</th>
<th>
After
</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Mitigate scrollbar/content overlaps

taskcluster/ci/build/kind.yml, taskcluster/ci/build/wasm.yml, taskcluster/ci/docker-image/kind.yml, taskcluster/docker/wasm/Dockerfile, taskcluster/mozillavpn_taskgraph/transforms/build.py, taskcluster/scripts/build/wasm.sh
This adds taskcluster jobs to build wasm(qt6)
-> Small nit change:
- Every /build/ task now will be indexed. 
- (Currently only decision tasks are indexed) 
- This gives us static routes for each build-job,branch combo  (i.e main.android.opt.x86.apk) ... or the mozillavpn.wasm, similar to what we have for the static_qt builds :)
=> Wasm builds on taskcluster

src/commands/commandcrashreporter.cpp, src/commands/commandcrashreporter.h, src/commands/commandui.cpp, src/crashreporter/crashreporterapp.cpp, src/crashreporter/crashui/main.qml, src/crashreporter/platforms/windows/wincrashreporter.cpp, src/crashreporter/platforms/windows/windowscrashclient.cpp, src/main.cpp, src/src.pro
This patch contains 3 things:
- fixes a string conflict between mainTitle via VPNl18n and qsTrId
- move the crashreporter command as a `Command` - to be consistent with the rest of the code.
- if there is nothing to send, quick exit.
=> Crash reporter as a `Command` and fix the exit steps if nothing needs to be sent

nebula/ui/components.qrc, nebula/ui/components/VPNIconButton.qml, nebula/ui/components/VPNPopup.qml, nebula/ui/components/forms/VPNContextualAlert.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationBase.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationErrorPopup.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml, nebula/ui/components/inAppAuth/qmldir, src/authenticationinapp/authenticationinapplistener.cpp, src/ui/authenticationInApp/ViewAuthenticationInApp.qml, src/ui/authenticationInApp/ViewAuthenticationSignIn.qml, src/ui/authenticationInApp/ViewAuthenticationStart.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml
This PR:
- Adds VPNInAppAuthenticationInputs.qml to consolidate duped code across all auth templates (except password creation)
- Adds VPNInAppAuthenticationErrorPopup.qml to surface authentication errors not relevant to a specific input. 
Also:
- Valid forms can be submitted by hitting 'Enter'
- Adds `inputMethodHints` to email entry text field to cue mobile devices and improve native keyboard options on Apple
- Email validation occurs after hitting "submit"
- Handles all auth errors currently exposed to the QML
To follow: 
- final content
- final TOS content/UI
- tests
- password creation fixes
- more error handling, form polish, etc.
Fixes #2870 , #2823 , #2818, #2817, VPN-1771, VPN-1610, VPN-1611
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td> …
=> Auth flow updates

src/authenticationinapp/authenticationinapplistener.cpp, src/authenticationinapp/authenticationinapplistener.h
This PR is mainly about moving code around. Plus an extra validation block for "code" in error 107.
=> Improve the error code propagation for auth-in-app

src/connectionhealth.cpp, src/dnspingsender.cpp, src/dnspingsender.h, src/pinghelper.cpp, src/pinghelper.h, src/pingsender.cpp, src/pingsender.h, src/pingsenderfactory.cpp, src/pingsenderfactory.h, src/platforms/dummy/dummypingsender.cpp, src/platforms/dummy/dummypingsender.h, src/platforms/linux/linuxpingsender.cpp, src/platforms/linux/linuxpingsender.h, src/platforms/macos/macospingsender.cpp, src/platforms/macos/macospingsender.h, src/platforms/windows/windowspingsender.cpp, src/platforms/windows/windowspingsender.h, src/src.pro, tests/unit/unit.pro
For some Linux and Android platforms, we have encountered cases where ICMP sockets are not available without root permissions, and this can lead to a scenario when we fall back to the dummy ping sender and lose the ability to test the network connectivity. We now have a better workaround in in the form of the `DnsPingSender` which uses DNS queries, and shouldn't require any elevated permissions.
To test this on Linux, we can deny ICMP socket creation with: `echo 0 0 > /proc/sys/net/ipv4/ping_group_range`
After this change, we can observe in the logs that the client still produces realistic ping measurements.
=> DNS ping fallback when ICMP sockets are unavailable

ci_scripts/ci_post_clone.sh
This PR changes the Xcode Cloud workflow to use Qt6 for both iOS and MacOS.
For iOS we switch from using `qt_static_ios` to using `aqt` to install qt6. 
Note that since qt6 for iOS references the macos packages witch we have to install first. 
Also, since the installation on iOS using `aqt` references `clang_64` instead of `macos` we rename the macos installation.
=> Remove qt5 from xcode cloud

nebula/ui/components/inAppAuth/VPNInAppAuthenticationBase.qml
Fixes #2933 : Elide longer email addresses 
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Elide long email addresses in in-app auth flow

nebula/ui/components.qrc, nebula/ui/components/inAppAuth/VPNInAppAuthenticationBase.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationCancel.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationErrorPopup.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationLegalDisclaimer.qml, nebula/ui/components/inAppAuth/qmldir, src/ui/authenticationInApp/ViewAuthenticationSignIn.qml, src/ui/authenticationInApp/ViewAuthenticationSignUp.qml, src/ui/authenticationInApp/ViewAuthenticationStart.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml, src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml
This PR adds two components to consolidate content/copypasta 
- Adds VPNInAppAuthenticationLegalDisclaimer.qml to consolidate legal disclaimer content & reduce copyDuping
- Adds VPNInAppAuthenticationCancel.qml to consolidate cancel button content & reduce copyDuping
- Replaces _most_ (two errors will be addressed in a follow-up) hard-coded content with string IDs.
- Adds missing headline el to VPNInAppAuthenticationPopup.qml
=> Consolidate and use final content

nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml
Fixes #3026 
This prevents auth forms from being submitted when the user clicks 'Enter' or taps 'Done' on mobile native keyboards if the form's submit button is disabled.
=> Fix #3026 - Submit auth forms on 'Enter' clicks only when submit buttons are enabled

nebula/ui/components/VPNControllerView.qml
This PR disables the VPNToggle while the Connection Info Screen is open. Additionally `Sample.connectionInfoOpened.record()` is now only called when opening the view and not when closing as well.
=> Disable VPNToggle when Connection Info Screen is open

scripts/utils/generate_glean.py
In the upgrade from Windows 10 --> 11. Microsoft has decided to install yet another copy of python at some incomprehensible path, and this led to a conflicts between the location of `python.exe`, `pip.exe`, `glean_parser.exe` and the module location all of which being slightly incompatible with one another. I have attached a diagram of my situation...
To resolve the build situation I have found myself in, let's ensure that we invoke the `glean_parser` using the current python interpreter. This is effectively the same as replacing `glean_parser --foo=bar` with `python -m glean_parser --foo=bar`
=> Invoke glean_parser as a module.

nebula/ui/components/VPNConnectionInfoContent.qml
Only run the speedometer animation on the Connection info view once.
=> Run Connection info animation only once

src/platforms/android/androidcontroller.cpp, src/platforms/android/androidvpnactivity.cpp
We're deadlocking the UI and Qt thread, after you press "yes" on the permission prompt it seems. (on signed, release builds only )
Thinking about it, there is no reason to 
A: move `s_instance->resume_activate()`to the QT-Main thread anymore, as now IPC is no longer handled by QTIBinder.
B: Force "AndroidActivity::sendToService" to be on the Android-UI thread; it does not have side effects and the transaction later is happening on the ipc thread anyway. 
Should close https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2774
Update: Got confirmation of QA that this fixes the issue.
=> Android: Do not block UI thread for ipc

src/platforms/windows/daemon/windowstunnellogger.cpp
On windows, the conversion from the fixed length buffer read from the tunnel's ringbuffer resulted in a 512b fixed length string being written to the log.  When encoded and sent to guardian for a support request that turned in to 512 /u0000s which caused it to be rejected by FxA for length.
I now truncate the buffer before conversion.  Also fixed a casting issue that was causing a warning.
=> Tunnel log entries were not decoded correctly

macos/app/Info.plist, src/authenticationlistener.cpp, src/platforms/macos/macosauthenticationlistener.cpp, src/platforms/macos/macosauthenticationlistener.h, src/qmake/platforms/macos.pri, src/tasks/authenticate/desktopauthenticationlistener.h
Recently MacOS users with Safari as their default browser have been unable to authenticate due to Safari's HSTS policy forcing the use of HTTPS when accessing localhost. As a workaround to this, we may need to implement our own custom URL handler in order to pass the OAuth auth code from Safari back to the VPN client.
This PR extends the `DesktopAuthenticationListener` class for MacOS to include support for receiving the OAuth code via a deep link of the form `mozilla-vpn://login/success?code=XXXXX` which should provide an alternate path for Safari users to complete authentication. For this to resolve the issue completely, we will need a corresponding update to the guardian website to utilize such a deep link.
See: #2846
=> Add MacosAuthenticationListener to support deep linking

src/localsocketcontroller.h
While refactoring the `ControllerImpl` class to support the new "Port 53/DNS" option, we added a new API to check if the platform supports multihop. Unfortunately, this was left unimplemented for the `LocalSocketController` which meant that Mac and Windows were falling back to the Mullvad multihop port, which conflicts with the "Port 53/DNS" option.
Closes: #3123
=> Re-enable native multihop support via LocalSocketController

.github/workflows/linux.yaml
I've re-built the Qt6 packages in a PPA that's a bit more suitable for backporting and less of a mess. Let's switch the Github CI to use this new PPA at [ppa:okirby/qt6-backports](https://launchpad.net/~okirby/+archive/ubuntu/qt6-backports)
=> Linux: Update Qt6 PPA URL for Github CI builds

src/connectionbenchmark/benchmarktask.h, src/connectionbenchmark/benchmarktasksentinel.h, src/connectionbenchmark/connectionbenchmark.cpp, src/connectionbenchmark/connectionbenchmark.h, src/mozillavpn.cpp, src/qmake/sources.pri
The tasks are fully disconnected when they complete their job or when they are
deleted. Because of this, the ConnectionBenchmark object does not receie the
QObject::destroyed signal, it does not cleanup the list of tasks, and
eventually, it crashes.
This PR fixes this using a 3rd QObject (a sentinel). It also remove the
multiple connections using a `initialize` method.
=> Fix a crash in the CI - VPN-1989

src/qmake/platforms/linux.pri
Some firefox builds (all 64-bit builds? just some?) look for the `native-messaging-hosts` under `/usr/lib64/native-messaging-hosts`. These changes allow to build for those systems with `qmake ... LIBPATH=/usr/lib64`.
The manifest file is now also updated to contain the install-configured path to the `mozillavpnnp` binary, rather than the hardcoded default path as previously.  Changes to `USRPATH` (or the new `LIBPATH`) previously caused the installed json file to point to a wrong location.
The sed command does not depend on the current path in the file and just replaces the line that contains ”path” with the appropriate path. Not sure this is optimal, but it works. An alternate way that depends on the current path (not sure it’s more readable) could be something like:
``` …
```
=> Allow the lib path to be set during build config

.github/workflows/android_qt6.yaml
Currently the release task generates 5 apks (each arch, + universal) - 
However, as qt only builds one arch now - only the matching apk for the job actually contains everything. 
Therefore, we should delete the broken any other APKs - so noone is wondering why "universal" won't work for them :) 
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3126
=> Remove Broken Apk's in release tasks

.github/workflows/android_qt6.yaml, scripts/utils/import_languages.py, taskcluster/scripts/build/android_build_debug.sh, taskcluster/scripts/build/android_build_release.sh
We had this line `git submodule update --remote --depth 1 i18n` in the package.sh prior. 
So therefore when adding the old gh-ci script back, that was not caught i guess :) 
Also let's print the current used translation commit in the script so we can easily check what commit was used in each build
=> Update i18n repo in ci runs

lottie/lib/lottieprivate.cpp, lottie/lib/lottieprivate.h
The QJSValue constructor for qstring actually constructs a js-number (a float actually) on android-11+ on arm64. (...Don't ask me why...)
Therefore getContext and loadanimation are not working there. 
Luckly engine->toScriptValue creates the right value here.
=> Fix Not Loadable Lottie Animations on Android 12

src/captiveportal/captiveportaldetection.cpp, tests/functional/testCaptivePortal.js
After the last refactoring of the connection states, `Controller::StateConnecting` and `Controller::StateConfirming` have kind of become the same thing, and exist as transient states during which the Wireguard connection(s) are being negotiated. We should treat these two states the same when responding to a captive portal check.
=> Fix captive portal functional tests.

src/ui/main.qml, tests/qml/tst_mainWindowGleanMocks.qml
Hey folks, I noticed this issue while going through the code. 
This was our bad for not communicating the change better to our users, but in [v0.27.0](https://github.com/mozilla/glean.js/releases/tag/v0.27.0) Glean.js removed the `debug` option for the configration object. So the way that was set up right now would just be ignored by Glean.
This PR addresses that issue.
=> Fix way to enable debug features for Glean

src/settingsholder.cpp
We end up writing the setting file too many times. This PR reduces the number of writes to ~0. But it could introduce regressions. So, please, extra care when reviewing. Thanks!
=> Reduce the number of writing operations - fixes VPN-VPN-1996

src/command.cpp, src/ui/main.qml
⚠️ This PR possibly has wide-ranging consequences for scaling on Android devices. If we decide to make this change we should test the change on as many Android devices as possible.
On some Android devices the dimensions of the application window are not filling the screen entirely. The issue seems to be rooted in how the app is scaled for high-DPI screens. The default policy for rounding the DPI scale factor for Android is different from other devices. This behaviour can be adjusted by using [QGuiApplication::setHighDpiScaleFactorRoundingPolicy](https://doc.qt.io/qt-5/qguiapplication.html#setHighDpiScaleFactorRoundingPolicy). From the documentation: 
> The default value is Qt::HighDpiScaleFactorRoundingPolicy::Round. On Qt for Android the default is …
=> Fix high-DPI scaling on Android

src/crashreporter/crashreporterapp.cpp, src/crashreporter/platforms/windows/wincrashreporter.cpp
This is a working theory that the dump files might not be written at the time the crash reporter is launched.  There is a 5x retry of the directory listing with an increasing interval (+ 1s each time).
=> Rescan for dumps

nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationPasswordCondition.qml
This PR tweaks the way we show password rules in the password creation screen.
We now:
- Dim the opacity of 'Must not be common password" and "Must not be email" rules until "Must be at least 8 characters" is satisfied. 
- Hide the red "X" images beside 'Must not be common password" and "Must not be email" rules until "Must be at least 8 characters" is satisfied.
=> Revise password hint behavior in create password view

src/ui/views/ViewLogs.qml
On Qt6 ScrollView behaves wierd with upward scrolling, not limiting the upper limit. Also "flicking" is broken. So let's replace it with VPNFlickable which works great and has none of those issues. 
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2710
https://user-images.githubusercontent.com/9611612/161100048-c40ffe8a-62ac-4e74-8738-5cbfd7e87e16.mp4
=> Fix LogViewer

src/ui/developerMenu/ViewDeveloperMenu.qml, src/ui/main.qml, src/ui/views/ViewContactUs.qml, src/ui/views/ViewGetHelp.qml
Fixes the safe area for the settings contact and developer views when visited from the mobile onboarding on iOS.
Fixes #3215
=> Fix contact and developer menu when visited from iOS onboarding

nebula/ui/components.qrc, nebula/ui/components/forms/VPNCursorDelegate.qml, nebula/ui/components/forms/VPNTextArea.qml, nebula/ui/components/forms/VPNTextField.qml, nebula/ui/components/forms/qmldir
This PR adds `VPNCursorDelegate {}` and uses it in `VPNTextField {}`and `VPNTextArea {}` to correct the red cursor issue on Android and fix the rest of #2901. This also fixes a misalignment issue between the placeholder text and cursor position in `VPNTextArea {}`.
<table>
<tr>
<th colspan="2">After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</tr>
</table>
=> Fix red cursor in VPNTextArea on Android

.github/workflows/functional_tests.yaml, scripts/linux/getdeps.py, src/inspector/inspectorhandler.cpp, src/inspector/inspectorhandler.h, src/mozillavpn.h, src/urlopener.cpp, tests/functional/helper.js, tests/functional/setupVpn.js, tests/functional/testAuthentication.js, tests/functional/testSettings.js, tests/unit/mocinspectorhandler.cpp
Another round of refactoring and cleanup for our functional tests. The big feature is switching to use Qt6 in our functional tests, however, some other changes include:
- Eliminate the `Generate Tasklist` job, it's silly to get Github to spin up a container just to list a directory.
- Reduce CPU usage by compiling `grcov` only once.
- Gracefully ignore coverage if `grcov` decides to panic on us.
- Fix test flakiness due to state carried between tests:
- Clear state with a `hard_reset` after each test.
- Add `scrollToElement()` to ensure an element is clickable during tests.
- Convert `lasturl` to a property, so that it can be cleared.
=> Functional testing: Qt6 and cleanup

src/controller.cpp
We don't need to have this timeout to simulate the disconnecting phase, because:
- we have removed it elsewhere
- it introduces funny non-sense animations when already disconnected
VPN-1985
=> Remove the 'fake' disconecting timeout - closes VPN-1985

nebula/ui/components/inAppAuth/VPNInAppAuthenticationErrorPopup.qml
This PR adds updates VPNInAppAuthenticationErrorPopup.qml to show a generic error message for the following edge-case errors `ErrorAccountAlreadyExists`, `ErrorAccountUnknown`, and `ErrorServerUnavailable`.
#3243 #3068
=> Add generic authentication error message

docs/authentication-in-app.md, nebula/ui/components/VPNPopup.qml, nebula/ui/components/VPNRemoveDevicePopup.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationErrorPopup.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml, nebula/ui/themes/themes.js, src/authenticationinapp/authenticationinapp.h, src/authenticationinapp/authenticationinapplistener.cpp, src/commands/commandlogin.cpp
During the weekend, I tried logging in on a VERY flaky internet connection. It was not fun. 
Currently, on a timeout in the sign-in step, we will error out, have show the "auth failed notification" and close the dialogue, forcing me to go through all the steps again, which is quite painful on an already flaky/bad connection. 
How about we use the error modal and let the user retry instead of exiting auth?
https://user-images.githubusercontent.com/9611612/161549325-381be9e0-9beb-4d90-8439-b44192b8a1bc.mp4
=> Proposal: Handle Timeouts in InAppAuth Sign-In Step

taskcluster/scripts/build/windows.ps1
We should be generating the pdb already, so let's put into the artifacts. 
Also log open processes. Currently, the task builds fine but is marked as "fail" due to failing the post-task cleanup. 
Something is having an open handle to some vs-studio .dll and i want to know which :)
=> TC-Windows: Add debug symbols to artifact bundle

nebula/ui/components/VPNConnectionInfoItem.qml
This PR addresses issues with long country names and city names after running a speed test. 
The fix makes long bolded labels wrap - by whole words, making sure we don't break words. Example: United States of America wraps at end of `of` instead of United States of Am-erica. See image below: 
Bug addressed can be seen in image below: 
Jira Issue: https://mozilla-hub.atlassian.net/browse/VPN-2023
=> modified layout to support long country names

src/platforms/windows/daemon/windowsroutemonitor.cpp, src/platforms/windows/daemon/windowsroutemonitor.h
When handling the exclusion routes, Windows will sometimes report multiple default routes, including interfaces that may be inactive or hidden. If one of these interfaces is selected for the exclusion route, then this often results in a broken routing table and a failure to remain connected.
To resolve this properly, we must do two things:
- Rank duplicate routing table entries using their routing metric.
- Ignore routes on inactive interfaces. We utilize the `GetNetworkConnectivityHintForInterface` API call for this.
Closes: #2693
JIRA Issue: [VPN-1698](https://mozilla-hub.atlassian.net/browse/VPN-1698)
=> Windows: Ignore hidden interfaces for exclusion routes.

windows/installer/MozillaVPN_prod.wxs
During production code signing, we have encountered an XML schema error when trying to generate the installer package. This seems to be due to the `Condition` element being present in the wrong order. To fix this, we simply move it after the `Product` element, which is required to go first.
See: #3236
=> Fix Wix schema error due to out-of-order Conditions.

.github/workflows/ppa-automation.yaml, scripts/linux/script.sh
In PR #3063 we reorganized the structure of the source bundle, but this was never reflected in the PPA automation workflow, which now fails to find the changeset for upload. This should fix the workflow and get it uploading packages again.
See: #3063
=> Fix PPA automation workflow after Qt6 changes

nebula/ui/components/VPNConnectionInfoError.qml, nebula/ui/components/VPNConnectionInfoScreen.qml, nebula/ui/components/VPNControllerView.qml, src/connectionbenchmark/benchmarktask.cpp, src/connectionbenchmark/benchmarktask.h, src/connectionbenchmark/benchmarktaskdownload.cpp, src/connectionbenchmark/benchmarktaskdownload.h, src/connectionbenchmark/connectionbenchmark.cpp, src/connectionbenchmark/connectionbenchmark.h, src/connectionhealth.cpp, src/connectionhealth.h, src/networkrequest.cpp, src/networkrequest.h, src/platforms/wasm/wasmnetworkrequest.cpp, tests/functional/helper.js, tests/functional/testBenchmark.js
In an attempt to get benchmark results closer to what's reported by speedtest.net, we can open multiple connections to try and do a better job of saturating the VPN network connection. This patch does so by exploiting DNS load balancing to open connections to multiple servers that ought to be hosting the download file.
Closes: #3002
Closes: #3000
=> Parallelize the connection download benchmark

.gitignore, ios/app/Info.plist, nebula/ui/components.qrc, nebula/ui/components/VPNMobileStatusBarModifier.qml, nebula/ui/components/qmldir, src/mozillavpn.cpp, src/mozillavpn.h, src/platforms/ios/iosutils.h, src/platforms/ios/iosutils.mm, src/platforms/macos/macosutils.h, src/theme.cpp, src/theme.h, src/ui/views/ViewMobileOnboarding.qml
The default text color is black for this text. Contrary to what I
thought, iOS does not automatically verify background color and
change the text accordingly. Status bar text color needs to explicitly be
changed when necessary.
This is a draft because I still need to:
- Skipped for this functionality due to the lack of structue for adding platform specific tests at the moment.
I would like to get some early feedback on the approach I took here,
especially on how I handled this on the QML side, since this is my first PR on the project.
I thought it would be best to double check.
https://user-images.githubusercontent.com/25176023/164515154-2f296ad5-95b3-4228-b4b5-c0902815f451.mov
https://mozilla-hub.atlassian.net/browse/VPN-1839
=> VPN-1839: Dinamically change status bar text color on mobile

android/src/org/mozilla/firefox/vpn/InAppPurchase.kt, android/src/org/mozilla/firefox/vpn/qt/VPNUtils.kt, nebula/ui/components/VPNSubscriptionOption.qml, src/iaphandler.cpp, src/iaphandler.h, src/inspector/inspectorhandler.cpp, src/inspector/inspectorhandler.h, src/platforms/android/androidiaphandler.cpp, src/platforms/android/androidutils.cpp, src/platforms/android/androidutils.h, src/platforms/ios/iosiaphandler.h, src/platforms/ios/iosiaphandler.mm
This PR fetches the in-app subscription free trial info from playstore and passes it to qml. 
Given this is a bit hard to test, you need to use a signed build on prod. - When the dev menu is enabled, it will mock the 12-month plan with 7 days, otherwise it will return the values from google play (all 0 currently)  - so qa can test the ui flow for now, we might need a better way to test this. 
=> Pass iap free trial duration to qml

.github/workflows/linters.yaml, taskcluster/mozillavpn_taskgraph/parameters.py, taskcluster/requirements.in, taskcluster/requirements.txt
When working on Taskcluster CI changes it's useful to be able to debug locally by running the `taskgraph` command. However, a couple of exceptions have crept into this process lately necessitating workarounds. This ensure we can run `taskgraph <subcommand>` without errors.
Ideally we should set up some tests to cover this, but I haven't had a chance to work on those yet.
=> Ensure `taskgraph` can be generated locally

nebula/ui/components/VPNConnectionInfoScreen.qml, src/connectionbenchmark/benchmarktaskdownload.cpp, src/ui/views/ViewMain.qml
When aborting the download benchmark for the _Connection Info Screen_ while it was running not all network requests were stopped. There was always one request left in `m_requests` that did not reliably call `downloadReady` on the `requestFailed` signal so that the `BenchmarkTaskDownload` only finished after this request completed.
- Issue: #3314
=> Fix handling of aborted download benchmark

nebula/ui/components/VPNSubscriptionOption.qml
- Added a "7-day free trial" chip to valid subscription options on the subscriptions page
[VPN-2098: Add and conditionally show '7-day free trial' label in `VPNSubscriptionOption {}`](https://mozilla-hub.atlassian.net/browse/VPN-2098)
=> Add free trial chip to subscription options

nebula/ui/components.qrc, nebula/ui/components/VPNAvatar.qml, nebula/ui/components/VPNMenu.qml, nebula/ui/components/VPNUserProfile.qml, nebula/ui/components/qmldir, src/ui/settings/ViewSettingsMenu.qml, src/ui/views/ViewContactUs.qml, src/ui/views/ViewSettings.qml, tests/functional/testScreenCapture.js, tests/functional/testSettings.js, translations/strings.yaml
This updates the Settings menu view to latest Figma spec ahead of upcoming In-App Subscription Management work. 
- Adds and uses VPNUserInfo.qml in ViewSettingsMenu.qml and ViewContactUs.qml. 
- Adds menu bar to settings view
- Removes blue 'Manage account' button.
- Fixes #3366
This will need a rebase and some small refactors once #3376 and #3365 are merged. Also, once the new in-app subscription management view is available, we'll need to update the VPNUserInfo button to open that view, instead of opening a browser window.
Fixes #3366 & VPN-2068
- [] I have commented my code PARTICULARLY in hard to understand areas
- [] I have added thorough tests where needed
=> Update settings menu per in-app subscription management updates

src/ui/authenticationInApp/ViewAuthenticationSignIn.qml
Center disclaimer text on in-app auth sign in page.
|Before|After|
|---|---|
|<img width="373" alt="disclaimer-before" src="https://user-images.githubusercontent.com/13835474/165858517-104e9b5d-389f-4a37-b9fa-0c0d6be619ef.png">|<img width="371" alt="disclaimer-after" src="https://user-images.githubusercontent.com/13835474/165858525-e0929892-128a-483d-9fb1-d396a23225b3.png">|
Fixes #3393
=> Fix disclaimer alignment in auth template

nebula/ui/components/VPNViewDNSSettings.qml
Fixes overflowing content in DNS settings.
|Before|After|
|---|---|
|<img width="472" alt="dns-before" src="https://user-images.githubusercontent.com/13835474/165862647-66602e73-a141-48e6-8b96-2927d48b90c0.png">|<img width="472" alt="dns-after" src="https://user-images.githubusercontent.com/13835474/165862651-228f2ab8-b640-4751-96b4-8d79595206ea.png">|
- Fixes #3389
=> Fix layout breakage in DNS settings

nebula/ui/components/VPNLoader.qml
Restores 'Cancel' button functionality on desktop in-browser authentication loading screen
=> Fix in-browser auth cancel button

ci_scripts/ci_post_clone.sh
@mbirghan , @bakulf - It seems on the release branch we are not currently building ios in appstore connect...
Looking at the logs
```
==> Running `brew cleanup go`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
/Volumes/workspace/repository/qt_ios/6.2.3/ios/bin/qmake
/Volumes/workspace/repository/qt_ios/6.2.3/ios/bin/qmake: line 7: /Volumes/workspace/repository/qt_ios/6.2.3/macos/bin/qmake: No such file or directory
/Volumes/workspace/repository/qt_ios/6.2.3/ios/bin/qmake: line 7: /Volumes/workspace/repository/qt_ios/6.2.3/macos/bin/qmake: No such file or directory
This script compiles MozillaVPN for MacOS/iOS
Using the MVPN_IOS_ADJUST_TOKEN value for the adjust token
qmake path: …
```
=> Maybe fix appstore connect build in 2.8.2?

src/mozillavpn.cpp
=> Check the model initialization before going to StateMain

.github/workflows/android_qt6.yaml, .github/workflows/functional_tests.yaml, .github/workflows/ios-build.yaml, .github/workflows/linters.yaml, .github/workflows/linux.yaml, .github/workflows/macos-build.yaml, .github/workflows/screencapture.yaml, .github/workflows/test_lottie.yaml, .github/workflows/test_qml.yaml, .github/workflows/test_unit.yaml, .github/workflows/wasm.yaml, .github/workflows/windows-build.yaml, README.md
I have noticed that I have often created dumb bugs that cause a CI run to fail, and therefore require an extra commit to fix. However, doing so causes us to waste a bunch of compute time running the extra workflows for the old and stale commit. Fortunately, github has a [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) directive that can abort these stale jobs for us.
I am particularly worried that my sloppy code may be causing us to run afoul of an execution cap, and leading to a lot of queued jobs blocking important work.
None!
=> Try enforcing concurrency limits to abort stale CI runs

glean/metrics.yaml, src/mozillavpn.cpp
Expose the app state via glean events.
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3411
=> Expose the app-state via glean events

scripts/windows/compile.bat, src/platforms/windows/daemon/dnsutilswindows.cpp, src/platforms/windows/daemon/windowsdaemon.cpp, src/platforms/windows/daemon/windowsroutemonitor.cpp, src/platforms/windows/daemon/windowsroutemonitor.h, src/platforms/windows/daemon/wireguardutilswindows.cpp
In the 2.8.0 release train, we encountered an issue where the VPN client would fail to launch on Windows 10 versions 1909.00 and older due to a new dependency introduced on the `GetNetworkConnectivityHint` system call. Unfortunately this would mean dropping support for some LTSC versions of windows that may still be out in the wild.
This patch attempts to work around this system call by inspecting the IP interface table, using the `GetIpInterfaceTable` system call, which is supported from Windows Vista and onwards. This is also slightly more correct, and we now respect the routing policy if users opt to disable IPv6 on one or more interfaces.
JIRA ticket [VPN-2135](https://mozilla-hub.atlassian.net/browse/VPN-2135)
Github issue #3394
Related issue #2693
=> Windows: Replace connectivity hint with GetIpInterfaceTable()

nebula/ui/components/VPNSubscriptionOption.qml
Currently, the free trial chip is cut off in German, so let's take the Headline-Overflow into account when calculating the box size
Before German:
| Live(German) | Fixed (German) | Fix applied  (English) |
| ------------- | ------------- | -----|
| ![Screenshot_20220505-151213(1)](https://user-images.githubusercontent.com/9611612/166940000-68de56df-37ac-4990-bbf0-d38a165178d7.png) | ![Screenshot_20220505-155911](https://user-images.githubusercontent.com/9611612/166940451-637f5bb7-cbb6-41d7-9681-48159dafaa2e.png) | ![Screenshot_20220505-155943](https://user-images.githubusercontent.com/9611612/166940512-6631c7ba-d644-48c6-a2ed-096c8fec1e5f.png) |
Don't mind the sorting, that is from my other pr.
=> Fix German Free Trial layout

windows/installer/MozillaVPN.wxs
In - https://github.com/mozilla-mobile/mozilla-vpn-client/pull/3236 We changed that the prod installer can only run on x64, we should do that on non prod (like taskcluster) installers aswell.
=> Also check for x64 arch on non-prod .msi

taskcluster/ci/config.yml
The GCP build images we were using have an outdated Chain of Trust key
baked in and will need to be re-built with the new ones.
This means we can't use these images for any release builds as they'll
fail the CoT verification when the signing tasks run.
For now let's just switch back to an AWS pool.
=> ci(signing): switch Android builds back to an AWS pool

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
The Default value here is "START_STICKY" - So if the OS stops the service not because of the unbind, Android will re-deliver the intent but without the extra "start-only". 
We handle a start without extras as if the os requests-always on, thus enabling the vpn. 
Start_NOT_STICKY means here that once the service is stopped by the os, we won't get a new intent to restart. 
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3179
=> Android: Fix Random Service starts in the client

nebula/ui/components/VPNCheckBoxRow.qml, tests/qml/tst_VPNCheckBoxRow.qml
- Reduce the clickable area of a checkboxrow label to just the width (and height) of the text
[VPN-889: Clicking on a radiobox/checkbox label should enable/disable the input field.](https://mozilla-hub.atlassian.net/browse/VPN-889)
=> Reduce clickable area for checkboxrow labels

scripts/linux/script.sh
In the omnibus CMake PR #3350 I moved some things around and introduced a typo in the linux packaging script that set the Debianization version suffix incorrectly when the gitref is `refs/heads/main` This means that we have not been including the suffix in the nightly builds, resulting in rejected packages because the version number is duplicated.
None
=> Fix a dumb typo causing the nightly PPA to fail.

.github/workflows/windows-build.yaml, CMakeLists.txt, src/cmake/windows.cmake, src/platforms/windows/daemon/windowsfirewall.cpp, windows/installer/MozillaVPN_cmake.wxs, windows/version.rc.in
Some cleanup of the executable paths in the Wix installer after renaming the client from `MozillaVPN.exe` to `Mozilla VPN.exe` and the sources for the GPU check command got lost in the rebase when merging PR #3350 
GitHub: #3528 ([VPN-2224](https://mozilla-hub.atlassian.net/browse/VPN-2224))
GitHub: #3515 ([VPN-2211](https://mozilla-hub.atlassian.net/browse/VPN-2211))
=> Fix the cmake-generated windows installer

README.md, src/CMakeLists.txt, src/cmake/sources.cmake, src/crashreporter/CMakeLists.txt, src/mozillavpn.cpp, src/mozillavpn.h, src/qmake/sources.pri, src/websockethandler.cpp, src/websockethandler.h, tests/auth/CMakeLists.txt, tests/auth/auth.pro, tests/auth/mocmozillavpn.cpp, tests/qml/CMakeLists.txt, tests/qml/mocmozillavpn.cpp, tests/qml/qml.pro, tests/unit/CMakeLists.txt, tests/unit/helper.h, tests/unit/main.cpp, tests/unit/mocmozillavpn.cpp, tests/unit/testwebsockethandler.cpp, tests/unit/testwebsockethandler.h, tests/unit/unit.pro
This sets up the client to connect to the Guardian websocket implemented on https://github.com/mozilla-services/guardian-website/pull/1504.
Right now it's not sending any messages so over here we are also not doing anything to process messages. Those will come as follow up work.
https://mozilla-hub.atlassian.net/browse/VPN-2260
=> VPN-2260 - Create resilient connection with Guardian Websocket

.github/workflows/ppa-automation.yaml
It appears that an Ubuntu package has been updated, to which the github runners are now out of date and are now pointing to a stale URL. To resolve the problem, we should run an `apt-get update` first to ensure we have the updated package manifest.
=> Run apt-get update in PPA automation workflow

src/CMakeLists.txt
In a recent PR #3567 to get the Windows installer working again, we renamed the top-level project, and neglected to update the use of the `${mozillavpn_VERSION_MAJOR}` CMake variable accordingly.
GitHub #3593 [(VPN-2272)](https://mozilla-hub.atlassian.net/browse/VPN-2272)
=> Fix auto-generated BUILD_ID to include major version.

src/networkmanager.cpp
Remove the 'aia' params in the client user-agent
PSP-393
=> Remove the 'aia' params in the client user-agent - PSP-393

src/controller.cpp
Fixing bug in #3470 - glean event name was wrong.
=> Fix wrong name for controller step event

nebula/ui/components/VPNMobileStatusBarModifier.qml, src/ui/main.qml, src/ui/views/ViewMobileOnboarding.qml
Meant to include this in #3407 with other changes arising from the mobile onboarding -> get help flow. This updates the status bar color on iOS as new views are pushed to/popped from `mainStackView` instead of `on<MobileOnboardingView>Destruction` so that the status bar stays legible on 'Get help' menu opens. 
https://user-images.githubusercontent.com/22355127/168169323-73e57485-01fd-41a3-95c6-90569505167d.mov
=> Quick followup to #3407

nebula/ui/components.qrc, nebula/ui/components/VPNAboutUs.qml, nebula/ui/components/VPNFeatureTourPopup.qml, nebula/ui/components/VPNPopup.qml, nebula/ui/components/VPNRemoveDevicePopup.qml, nebula/ui/components/VPNServerUnavailablePopup.qml, nebula/ui/components/VPNSimplePopup.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationErrorPopup.qml, nebula/ui/components/qmldir
- Refactor VPNPopup to:
- Parent the background to the popup instead of the content
- Be the correct width
- Have a more dynamic layout with toggle-able "showCloseButton" property and allow the contents of the popup to start beneath the close button OR at the top of the popup
- Add VPNSimplePopup to be used for *most* of our popups that neatly displays just an image + title + description + action button(s)
- Refactor current VPNPopup based modals (Check for updates, server unavailable, in-app authentication errors) to work with  VPNSimplePopup
- Refactor current Popup based modals (Remove device) to work with VPNSimplePopup
Note: This patch will break the "What's new" modal - but that will quickly be resolved in #3625 since that feature is being modified
[VPN-2283: [Tech Debt] - Refactor …
=> Refactor VPNPopup

src/connectionhealth.cpp
Replaces the server using a public mullvad controlled one :) 
Closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3171
https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/
=> Stop using 8.8.8.8 in the connection check

src/command.cpp
Some distros may set `QT_STYLE_OVERRIDE` by default when attempting to apply a uniform style their Qt5 applications. However, this style may not necessarily exist for Qt6, which will result in a failure to load QML content. To work around this issue, check that the style exists before creating the `QApplication`, and unset the environment variable if no such style was found.
The QML fails to load `QtQuick.Controls` when this situation occurs.
Github: #3367
JIRA: [VPN-2113](https://mozilla-hub.atlassian.net/browse/VPN-2113)
=> Clear QT_STYLE_OVERRIDE if the style was not found.

scripts/utils/generate_strings.py, src/models/helpmodel.cpp, src/ui/views/ViewGetHelp.qml, translations/l18nstrings.cpp
This changes the 'Contact us' string to 'Contact support' in the macOS top bar menu and moves 'Give feedback' to the bottom of the list in ViewGetHelp.qml. 
VPN-2198
=> Update Get help menus

scripts/utils/generate_strings.py, scripts/utils/generate_ts.sh
https://github.com/mozilla-mobile/mozilla-vpn-client/runs/6838383168?check_suite_focus=true
> Unable to find /home/runner/work/mozilla-vpn-client/translations/strings.yaml
We're running a copy of the script in a different folder, the default defined in the Python script won't exist.
=> Fix string export for main branch

taskcluster/scripts/toolchain/compile_qt_6.ps1
This fixes a bug in the Windows qt toolchain task which was resulting in an invalid artifact (and therefore also invalid Windows builds. This was regressed by #3620 ,
=> fix: misnamed path in Windows qt toolchain script

addons/tutorial_02_connect_on_startup/manifest.json, docs/add-on.md, docs/guides.md, docs/tutorials.md, scripts/ci/jsonSchemas/addon.json, scripts/ci/jsonSchemas/guide.json, scripts/ci/jsonSchemas/tutorial.json, src/addons/addon.cpp, src/addons/addon.h, src/models/guide.cpp, src/models/guide.h, src/models/tutorial.cpp, src/models/tutorialstep.cpp, tests/unit/CMakeLists.txt, tests/unit/testaddon.cpp, tests/unit/testaddon.h, tests/unit/testguide.cpp, tests/unit/unit.pro
To clean up the code more, let's unify the "conditions" property in the addon manifest instead as a sub-property of tutorial/guide objects.
=> Move the condition block in the addon world

nebula/ui/components/VPNDeviceListItem.qml, nebula/ui/components/VPNRemoveDevicePopup.qml, nebula/ui/themes/themes.js, src/ui/views/ViewDevices.qml
- When clicking "Remove" on the "Remove device" popup from the device limit reached page:
- Close the "Remove device" popup
- Disables all of the items in the list
- Indefinitely shows a spinner next to the device being removed
https://user-images.githubusercontent.com/15353801/173144876-d4802772-66eb-40fd-9bcb-9231a81a1b9a.mov
[VPN-2002: Improve "loading" visual cues when removing a device during authentication](https://mozilla-hub.atlassian.net/browse/VPN-2002)
=> Improve "device limit" removal visual cues

nebula/ui/components/VPNFlickable.qml, src/ui/views/ViewMultiHop.qml
Tweaks to VPNFlickable so that scrollbar is not visible when scrolling is unnecessary
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr></tr>
</table>
#3610
=> Nit: Update scrollbar visibility

src/inspector/inspectorhandler.cpp, src/profileflow.cpp, src/profileflow.h, src/tasks/getsubscriptiondetails/taskgetsubscriptiondetails.cpp, src/tasks/getsubscriptiondetails/taskgetsubscriptiondetails.h, tests/functional/helper.js
This PR adds the inspector command `force_subscription_managment_reauthentication` for testing the re-authentication flow for the subscription management view.
[VPN-2320](https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=)
=> Inspector command to force subscription management re-authentication

taskcluster/mozillavpn_taskgraph/transforms/release_index.py
I also added a 'latest' to the route for two reasons:
A) Consistency with the decision task
B) This will leave the door open to other branch based routes so we can
e.g find tasks by revision, date or version number in the future.
Jira: RELENG-938
=> ci: Add missing 'index' prefix to Taskcluster branch routes

glean/metrics.yaml, src/constants.h, src/controller.cpp, src/controller.h, src/telemetry.cpp, src/telemetry.h
Adds two new events for particular controller states (to ease analysis as opposed to using the controller_step data) and sets a long timer (3 hours / 10 minutes) to report the controller state for desktop. Follow-up work will be done to incorporate the controllerStateOn event for mobile in separate PRs.
* [Jira](https://mozilla-hub.atlassian.net/browse/VPN-1619)
* [Github](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/2643)
=> Add periodic check (3 hours / 1 minute) for controller state

src/subscriptiondata.cpp, src/subscriptiondata.h, src/ui/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
The parsing of the received subscription `payment` data from FxA did not handle missing data well and was also missing the payment `provider`. There are instances where we would expect payment information for a subscription, but due to an issue ([FXA-3856](https://mozilla-hub.atlassian.net/browse/FXA-3856)) we could end up not receiving it. In that case let’s just not show it instead of throwing an error and blocking the user from accessing the `profile` view.
- Resolves #3789
=> Fix parsing of subscription payment data

nebula/ui/components/VPNAlerts.qml, src/models/surveymodel.cpp, src/models/surveymodel.h
This adds client support for the survey alert described in https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3402. This survey alert will be removed after 2.9.
#3402
=> Support unique survey alert for 2.9 UR #3402 / VPN-2139 - WIP 

.github/workflows/linux.yaml
They break the linux package generation because we are unable to include the addons in the RPM package yet.
=> Remove RPM github action

nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml, src/ui/authenticationInApp/ViewAuthenticationStart.qml
This fixes behavior described in #3729. 
https://user-images.githubusercontent.com/22355127/174878481-c06d198c-a717-45d1-bb7b-a3f8124cd9d7.mov
#3279
=> Fix authentication input error message visibility on Android 

nebula/ui/components/VPNSegmentedToggle.qml
ElideRight seems to cause android to simply not render any text, so lets make it conditional 
Fixes https://mozilla-hub.atlassian.net/browse/VPN-2158
Closes #3437
=> Fix Missing Text in segmented button

src/ui/settings/ViewGuide.qml
The issue is in how we load ViewGuide.qml: always on the mainview stack. We do
it also when we are in settings.  When we go back, the app removes a layer on
top stack view (settings) and the tips&tricks view goes away, instead of the
guide.
=> Support back-button on android in the guide view - fixes VPN-2435

src/cmake/linux.cmake
When pkg-config is unable to locate the systemd package configuration, we skip the installation of the systemd service file on the assumption that the packaging tools will install it for us. Unfortunately, it seems that this assumption isn't true on Ubuntu/18.04 Bionic, which leaves the MozillaVPN service incorrectly installed.
When this occurs, let's choose a sensible default of `/lib/systemd/system` instead.
Github: #3670
JIRA: [VPN-2322](https://mozilla-hub.atlassian.net/browse/VPN-2322)
=> Add fallback path when pkg-config is unable to find systemd

nebula/ui/components/VPNTutorialPopups.qml
Fixes wonky behavior described in #3811 when the "Leave tutorial?" modal is triggered twice by attempting to open Preferences or Contact support from the macos top menu bar whilst taking a tutorial. 
#3811
=> Fix #3811 - Leave tutorial modal issues when opened from top bar

src/itempicker.cpp
This adds `QEvent::TouchEnd` to `ItemPicker::eventFilterInternal` to fix #3814. 
#3814
=> Add QEvent::TouchEnd to ItemPicker::eventFilterInternal

nebula/ui/components/VPNToolTip.qml
This prevents tooltips from opening when an element has focus during a tutorial. Tooltips will still open if the user hovers over an accepted element.
#3795 #3794
=> Show tooltips only on hover during a tutorial

.taskcluster.yml
This adds index routes for release decision task graphs as well as
change the name so it doesn't overwrite the `on-push` Decision Task in
the Github checks UI.
=> ci: make Github Release Taskcluster graphs more discoverable

CMakeLists.txt, src/qmake/debug.pri
This is a 2.9.0 backport of the security fix for both qmake and CMake in #3539.
> * In qmake, the `debug` variable and the `release` variable are both present by default.  We need to check which one is active, by virtue of having been set later.
>
>   https://doc.qt.io/qt-6/qmake-test-function-reference.html#config-config
>
> * In CMake, the `"${CMAKE_BUILD_TYPE}"` test did not do what it looks like it does.  CMake evaluates `if("${CMAKE_BUILD_TYPE}")` to `if(Release)`, which tests whether the *variable named `Release`* is defined; it isn’t, so we were unconditionally setting `CMAKE_BUILD_TYPE` to `Debug`.
>
>   https://cmake.org/cmake/help/latest/command/if.html#variable-expansion
>
>   We need to check whether `CMAKE_BUILD_TYPE` variable itself is defined, and we need to do so before …
=> [2.9.0] Properly disable qmljsdebugger in release mode

src/profileflow.cpp
Fixes the inspector command `force_subscription_mananagement_reauthentication` for testing the re-authentication flow for the profile view
[VPN-2320: Add a way to test the re-authentication flow](https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-2320)
=> Fix subscription management re-auth inspector command

tests/functional/helper.js, tests/functional/setupVpn.js
Because hard-reset requires a restart. Instead, what we want is to go go back
to the initial screen.
VPN-2466
=> Using hard-reset for reinitialize functional tests is wrong

taskcluster/ci/build/windows.yml, taskcluster/ci/signing/kind.yml, taskcluster/mozillavpn_taskgraph/transforms/release_index.py, taskcluster/test/params/github-release.yml
This change will make it easier for QA and others to find release builds after creating a new "Github Release".
=> Add index routes to find builds from a `github-release` graph

src/models/subscriptiondata.cpp
QA can create subscriptions for testing that have `day` as subscription interval. Let’s support them and show them as monthly plans for testing purposes.
[VPN-2428](https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-2428)
=> Support more subscription intervals for testing

src/addons/addonguide.cpp, version.pri
With the introduction of CMake, we now use a generated header file to set the `APP_VERSION` and `BUILD_ID` macros, so that we don't have to re-build everything whenever the makefiles get touched.
Unfortunately, this has the downside that when `src/version.h` already exists we don't update the version numbers, which can often lead to stale build identifiers even when the code is updated. To resolve this issue, we can make the version generation depend on the `FORCE` target.
Github: #3853
JIRA: [VPN-2460](https://mozilla-hub.atlassian.net/browse/VPN-2460)
=> Fix version.h regeneration with qmake

nebula/ui/components/VPNFlickable.qml, nebula/ui/components/forms/VPNTextField.qml, src/ui/authenticationInApp/ViewAuthenticationStart.qml, src/ui/main.qml
This restores native input edit menus (select/select all/cut/copy depending on platform) on Android and iOS and restores the ability to paste into inputs on iOS.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/22355127/176479126-1bec4acf-8104-486a-a8b5-095048dbb18e.mov
</td>
<td>
https://user-images.githubusercontent.com/22355127/176478974-b129e04f-7d4c-484b-8b4f-fafdfd40881c.mov
</td>
</tr>
</table>
TBD
=> Restore copy/paste functionality for inputs on iOS

src/websockethandler.cpp, src/websockethandler.h, tests/unit/testwebsockethandler.cpp
--
https://mozilla-hub.atlassian.net/browse/VPN-2384
=> VPN-2384 - Do not rely on QElapsedTimer for websocket handler tests

src/models/subscriptiondata.cpp, src/models/subscriptiondata.h
We need to reset the subscription data entirely and not expect it to be overwritten. If the subscription type a user has for the VPN changes (for example “web” to “Apple IAP”) and we were able to show more data for a previous subscription than for the current one, it could be that we partly show infos from the old subscription.
TBD
=> Clear subscription data before populating

CMakeLists.txt, lottie/CMakeLists.txt, windows/version.rc.in
With `qmake` we can set the application icon using the `RC_ICON` macro, but unfortunately this doesn't exist in CMake and we need to implement this by adding a the `IDI_ICON1` directive when generating the application resource file.
Closes: #3641
JIRA: [VPN-2301](https://mozilla-hub.atlassian.net/browse/VPN-2301)
=> Set Windows app icon when building with CMake.

README.md
We hard-code /usr/bin/mozillavpn in a couple places on Linux.
The right fix would be to make the relevant files:
* `linux/extra/mozillavpn-startup.desktop`
* `linux/extra/mozillavpn.desktop`
* `linux/mozillavpn.service`
* `src/platforms/linux/daemon/org.mozilla.vpn.dbus.service`
Generated at build-time, using the specified `CMAKE_INSTALL_PREFIX`
instead. But I'm not a CMake expert and I'm not sure what's the best way
to do that.
Instead, document that this flag is needed, since a lot of distros
default to /usr/local otherwise.
=> Document that right now we rely on CMAKE_INSTALL_PREFIX=/usr

.gitignore, windows/installer/MozillaVPN_prod.wxs, windows/installer/build_prod.cmd
This should generate a valid .msi with addons working. 
We would need the "msi-windows-tunnel"  task to change the MOZ_FETCHES from 
```
"MOZ_FETCHES": "[{\"artifact\": \"public/build/signed-internals.zip\", \"dest\": \"../build/src/\", \"extract\": true, ....
```
to: 
```
"MOZ_FETCHES": "[{\"artifact\": \"public/build/signed-internals.zip\", \"dest\": \"../build/src/signed-internals\", \"extract\": true, ....
```
=> Consume signed stuff from the 'signed-internals' folder

scripts/macos/utils/commons.sh
With the change from Apple to switch to arm64 on new macbooks
the default value of the ARCHS_STANDARD configuration is 'arm64 x86_64'.
Since the VPN app does not support arm64 architectures yet,
this is an issue (see: https://mozilla-hub.atlassian.net/browse/VPN-82).
It became an apparent issue, though, after the addition of the
signature Rust library to the codebase.
Rust will only build for the active architecture (x86_64), while xcode
will attempt to build for both. That was causing a linker error.
https://mozilla-hub.atlassian.net/browse/VPN-2524
=> VPN2524 - Update xcodebuild script to only build for x86_64 arch

taskcluster/ci/toolchain/qt.yml
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3960
Sounds very much like a bug we had in android that we had resolved by upgrading to 6.2.4. - Let's do that for ios too, we can always roll back if it breaks things
Note: Merging this into main will bump the next ios build but not windows/macos. - :)
=> Bump Qt version / Maybe fix iOS crash?

src/cmake/sources.cmake
It seems that we forgot to enable the ServerHandler class when converting CMake, which prevents the MAC addon and webextension from being able to communicate with the VPN.
Closes: #3919 ([VPN-2507](https://mozilla-hub.atlassian.net/browse/VPN-2507))
=> Enable MVPN_WEBEXTENSION when building for desktop

addons/message_survey_28d_desktop/manifest.json, addons/message_survey_28d_mobile/manifest.json, addons/message_survey_staging_10s/manifest.json, addons/message_survey_staging_4s/manifest.json, scripts/addon/build.py, scripts/ci/jsonSchemas/conditions.json, src/addonmanager.cpp, src/addons/addon.cpp, src/addons/addon.h, src/addons/addondemo.cpp, src/addons/addondemo.h, src/addons/addoni18n.cpp, src/addons/addoni18n.h, src/addons/conditionwatchers/addonconditionwatcher.cpp, src/addons/conditionwatchers/addonconditionwatcher.h, src/addons/conditionwatchers/addonconditionwatchergroup.cpp, src/addons/conditionwatchers/addonconditionwatchergroup.h, src/addons/conditionwatchers/addonconditionwatcherlocales.cpp, src/addons/conditionwatchers/addonconditionwatcherlocales.h, src/addons/conditionwatchers/addonconditionwatchertriggertimesecs.cpp, src/addons/conditionwatchers/addonconditionwatchertriggertimesecs.h, src/cmake/sources.cmake, src/qmake/sources.pri, tests/unit/CMakeLists.txt, tests/unit/testaddon.cpp, tests/unit/testaddon.h, tests/unit/unit.pro
This patch introduces a big change in addons. They now can be:
- not loaded - in case the "static" conditions do not match (platform, env, ...)
- loaded but disabled - in case dynamic conditions do not match (locales, triggering time, ...)
- loaded and enabled - in case conditions match.
When the conditions change the addon can be enabled or disabled. The model is updated and the frontend will be updated too.
I also wrote 4 temporary addons to test the surveys as addon messages with triggering time. 2 for testing only.
This PR has also unit-tests.
=> Condition watcher for addons

src/commands/commandui.cpp
On iOS devices the VPN crashed when swipe killed from multiple views.
[VPN-2548](https://mozilla-hub.atlassian.net/browse/VPN-2548): [iOS] Crash after swipe kill while on Profile screen
=> Fix crash on swipe kill

CMakeLists.txt, src/qmake/debug.pri
* In qmake, the `debug` variable and the `release` variable are both present by default.  We need to check which one is active, by virtue of having been set later.
https://doc.qt.io/qt-6/qmake-test-function-reference.html#config-config
* In CMake, the `"${CMAKE_BUILD_TYPE}"` test did not do what it looks like it does.  CMake evaluates `if("${CMAKE_BUILD_TYPE}")` to `if(Release)`, which tests whether the *variable named `Release`* is defined; it isn’t, so we were unconditionally setting `CMAKE_BUILD_TYPE` to `Debug`.
https://cmake.org/cmake/help/latest/command/if.html#variable-expansion
We need to check whether `CMAKE_BUILD_TYPE` variable itself is defined, and we need to do so before `project()` defines it by default.
=> Properly disable qmljsdebugger in release mode

windows/installer/MozillaVPN.wxs, windows/installer/MozillaVPN_prod.wxs
So apparently "not installed" is true after updating, so we are running both LaunchActions after an update
=> Fix Windows Installer / Double run after update 

nebula/ui/components/VPNFlickable.qml, nebula/ui/components/VPNServerCountry.qml, nebula/ui/components/VPNTutorialPopups.qml
Bandaid fix for tutorial UI issues in the 'Get started' tutorial when Australia is not the first country in the server list. We will do something more future-proof for 2.10. 
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
#4002
=> HackFix for 2.9 tutorial UI issues (#4002)

src/addonmanager.cpp, tests/functional/guardian.js
This is a temporary fix because it seems that WASM is unable to message addon RCC Files (yet).
=> Fix the wasm client - fixes VPN-2589

nebula/ui/components/VPNTutorialPopups.qml, src/externalophandler.cpp, src/externalophandler.h, src/inspector/inspectorhandler.cpp, src/platforms/macos/macosmenubar.cpp, src/ui/views/ViewMain.qml
There are 2 issues here:
- maybe the VPNAddonManager is faster than nebula and when the tips&tricks modal is loaded the addons have been already processed. If this happens, the `loadCompleted` signal was already emitted and the `Connection` block will not be executed.
- the inspector does not call the `ExternalOpHandler` when loading settings and contact-us views. Now it does.
- Same thing for the macosbar handler.
=> Fix the test failures

CMakeLists.txt
While #3539 was waiting to be merged, it accumulated an undetected merge conflict with commit 7369bb3dc5792059389295504b56d2e7917fb615 (#3935), which moved the `project()` directive to the top of the file. GitHub incorrectly resolved this by duplicating the `project()` directive.  Then commit 28cc02cdd9de5f1c00e258a3fe32f132d875bb31 (#4023) deleted one of the duplicates, but left the original fix ineffective, because the `set(CMAKE_BUILD_TYPE …)` directive is still incorrectly after the remaining `project()` directive.
Fix it.
=> Repair mismerge of #3539

.github/workflows/linux.yaml, scripts/linux/ppa_script.sh, scripts/linux/script.sh
Ubuntu 21.10/Impish reached EOL status on July 14th (announcement [here](https://lists.ubuntu.com/archives/ubuntu-announce/2022-July/000281.html)) and is no longer accepting new packages. This means that we can no longer build packages for Impish on any of our PPA tasks.
=> Drop support for Ubuntu/Impish which is EOL.

src/addonmanager.cpp, src/addonmanager.h, src/inspector/inspectorhandler.cpp
As we know, we don't load all the addons. But because of this, without this PR, at any refresh, we try to download the non-loaded ones. With this PR, we keep track of them, storing them on disk without loading them.
=> An optimization related to saved addons

src/profileflow.cpp
Reset the profile flow on account deletion.
[VPN-2554: Profile screen cannot be accessed after a delete-account action](https://mozilla-hub.atlassian.net/browse/VPN-2554)
=> Reset profile flow on account deletion

.github/workflows/functional_tests.yaml
I cannot find that script in package.json. I guess it never existed.
=> Remove cleanup-flaky-script-output reference from the github action - fixes VPN-2601

nebula/ui/components/forms/VPNInputStates.qml
This PR disables UI state changes when hovering a disabled `VPNTextField`
Fixes #3703 / VPN-2376
=> Nit Fix #3703 / VPN-2376- Disable UI state changes when hovering disabled input

nebula/ui/components/VPNMenu.qml, src/ui/views/ViewSettings.qml
This changes the tooltip label of the "X" button on the Settings menu page from "Back" to "Close". 
Fixes #626
=> Nit Fix #626 - Use correct accessible name for Settings close button

nebula/ui/components/VPNExpandableAppList.qml, nebula/ui/components/VPNServerList.qml, nebula/ui/components/forms/VPNSearchBar.qml, src/ui/settings/ViewAppPermissions.qml, src/ui/settings/ViewLanguage.qml
This PR consolidates instances of `VPNFilterProxyModel{}` into `VPNSearchBar.qml` and refactors to fix UI bug in App Permissions. 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Fixes #4009
=> Fix #4009 - UI overlap in App Permissions

src/ui/views/ViewSubscriptionNeeded.qml
This fixes #4078 - 'StackView has detected conflicting anchors' console warning in ViewSubscriptionNeeded.qml
#4078
=> Fix 2609/#4078 - QML warning in ViewSubscriptionNeeded.qml

nebula/ui/components/VPNSettingsItem.qml
This PR adds handling for very long Settings menu labels and fixes #4067.
<table>
<tr>
<th>Do nothing when there is enough horizontal space...</th>
<th colspan="2">Wrap text when there is not enough horizontal space...</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr><th>Elide words exceeding the available <br>horizontal space instead of breaking and wrapping<br>(see Kerfisstilli...)</th></tr>
<tr>
<td>
</td>
</tr>
</table>
=> Fix #4067 - Wrap or elide long labels in Settings menu

nebula/ui/components/VPNMouseArea.qml, tests/qml/tst_VPNMouseArea.qml
This prevent button "clicks" after 1.) clicking and holding a button then 2.) moving the mouse away from the button and 3.) releasing the mouse outside of the button.
Fixes #3384
=> Nit fix #3384 - Prevent button "clicks" if pressed mouse leaves button

src/addonmanager.cpp, src/addonmanager.h, src/addons/addon.cpp, src/ui/developerMenu/ViewMessages.qml
For the in-app messaging we need to show the number of unread messages. I don't want to expose a method in VPNAddonManager because that break the addon isolation. Instead, I want to have a `reduce` method to compute the number of unread message in the front-end code.
In the meantime, I have optimized the dynamic condition handling.
=> Fix the condition and introduce a reduce() method

.github/workflows/functional_tests.yaml
Currently, we're pushing our builds that will run the functional test into a cache, that will be restored on the runner. 
We did this as artifact passing was much more a hasstle. 
However as caches are global, it is possible that one task can pollute the cache of another task (i.e functional tests wasm/linux) - or a really busted build can persist even after a retry. As this happened once now, and required manual intervention, let's have the build task produce an artifact that we pull instead, so we keep run context
=> Functional Tests: Use artifact passing instead of caching

.github/workflows/wasm.yaml
Compiling in debug mode (the default mode) creates a >100mb wasm file and this cannot be uploaded to github.io
=> Compile wasm in release mode

taskcluster/ci/fetch/kind.yml
This is only a bandaid fix as we'll see the same error the next time a
new version of 'rustup-init' is released. Ideally we should either find
a URL that is pinned to a specific version, or else find another way to
bootstrap rustup.
Issue: #4162
=> ci: update hash and size for newer version of 'rustup-init'

taskcluster/ci/beetmover/kind.yml, taskcluster/ci/config.yml, taskcluster/mozillavpn_taskgraph/transforms/beetmover.py, taskcluster/mozillavpn_taskgraph/worker_types.py
These code changes add tasks to upload VPN macos release candidates to https://ftp.mozilla.org/pub/vpn/candidates/ on `github-release` events.
I tried it out in staging. First I created a release with the tag `v0.0.16`. This triggered the release graph and uploaded release candidate [20220803200417](https://ftp.stage.mozaws.net/pub/vpn/candidates/0.0.16/)
To upload a second release candidate I deleted the release tag:
`git push --delete origin v0.0.16`
The release then turned back into a pre-release. I republished the release with the same tag. That uploaded release candidate [20220803202328](https://ftp.stage.mozaws.net/pub/vpn/candidates/0.0.16/)
[Here's is the latest release beetmover task I ran in staging](https://github.com/mozilla-releng/staging-mozilla-vpn-client/runs/7660304101) …
=> Add MacOS beetmover tasks on the mozilla-vpn-client github-release taskgraph

taskcluster/ci/build/kind.yml, taskcluster/ci/repackage-signing/kind.yml, taskcluster/mozillavpn_taskgraph/transforms/release_index.py
I accidentally regressed the index paths for non-Windows builds in my recent Windows signing PR. I also noticed that the Windows path is `msi` rather than `windows. This PR addresses both issues.
=> Fix Taskcluster release indexes

taskcluster/ci/beetmover/kind.yml, taskcluster/ci/config.yml, taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
Refactors the beetmover task kind and adds tasks to upload VPN windows release candidates to https://ftp.mozilla.org/pub/vpn/candidates/ on `github-release` events.
[Here's is the latest windows beetmover task I ran in staging](https://github.com/mozilla-releng/staging-mozilla-vpn-client/runs/7735897834)
[RELENG-937](https://mozilla-hub.atlassian.net/browse/RELENG-937)
=> Refactor beetmover tasks and add Windows candidates

src/ui/developerMenu/ViewFeatureList.qml
This PR 
- Consolidates the three features lists in our dev menu (_features that can be toggled on, features that can be toggled off, the whole feature laundry list_) into a single list
- Replaces the check boxes with toggles to indicate feature status. 
- Features that can be toggled on/off have functioning, enabled toggles at full opacity. 
- Features that cannot be toggled on and off have disabled toggles with lower opacity. 
https://user-images.githubusercontent.com/22355127/183742881-611f4b6b-6a10-4916-82f1-f327cfb12264.mov
Once #4168 closes, which disables UI changes when hovering disabled toggles, the distinction between an enabled and disabled toggle will be even clearer.
#4150
=> Consolidate dev menu feature lists and use toggles to indicate status

.github/workflows/gh_pages.yaml
It was added as part of the wasm-task which we removed from gh-pages. my bad :c
=> Bring back logviewer

src/websocket/websockethandler.cpp
There is no point in leaving the timer going once the websocket is closed. This is not a critical bug it is just superfluous execution of code, but didn't do real harm to the functionality. Either way, should be fixed so here is the fix.
No bug for this one, just saw it and fixed it. A test would be way too complicated to justify, so no test.
=> BUGFIX: Stop ping timer once websocket is closed

taskcluster/ci/config.yml
The worker-type for MacOS signing changed awhile back but we never updated the definition in config.yml. So currently Mac signing tasks on level 1 (staging-mozilla-vpn-client or pull-requests) just time out as the configured pool doesn't have any workers.
- [ x ] My code follows the style guidelines for this project
- [ x ] I have not added any packages that contain high risk or unknown licenses (GPL,  LGPL, MPL, etc. consult with DevOps if in question)
- [ x ] I have performed a self review of my own code
- [ x ] I have commented my code PARTICULARLY in hard to understand areas
- [ x ] I have added thorough tests where needed
=> fix: use new worker-type names for MacOS dep signing pools

src/externalophandler.cpp, src/externalophandler.h, src/mozillavpn.cpp, src/mozillavpn.h, src/platforms/macos/macosmenubar.cpp, src/systemtraynotificationhandler.cpp, tests/auth/mocmozillavpn.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp
This restores tutorial interruptions when Get help is opened from the systray/menu bar during a tutorial.
#4247 / VPN-2731
=> Interrupt tutorials on Get help clicks

nebula/ui/components/VPNGuideList.qml, nebula/ui/components/VPNTutorialList.qml, src/ui/screens/tipsAndTricks/ViewTipsAndTricks.qml
Fix the layout of the tips and tricks "all" tab when no addons are active
[VPN-2753: Tips & Tricks feature has UI issues for a inexistent add-on URL](https://mozilla-hub.atlassian.net/browse/VPN-2753)
=> Fix tips and tricks layout with no addons

nebula/ui/components/VPNUserProfile.qml, src/ui/screens/settings/ViewSettingsMenu.qml
Fixes `ReferenceError: _iconButtonImageSource is not defined (VPNUserProfile.qml:91)` and `Warning: qrc:/ui/settings/ViewSettingsMenu.qml:48:13: QML VPNUserProfile: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (ViewSettingsMenu.qml:48)` warnings/errors in ViewSettingsMenu.qml.
Fixes #4118
=> Fix QML warnings in ViewSettingsMenu.qml #4118

src/controller.cpp, src/controller.h, tests/qml/moccontroller.cpp, tests/unit/moccontroller.cpp
This patch add's a last attempt to establish a connection, forcefully using port 53. 
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/3268
=> Fallback to port 53 before failing 

nebula/ui/components/VPNServerUnavailablePopup.qml, src/controller.cpp, src/controller.h, src/mozillavpn.cpp, src/notificationhandler.cpp, src/notificationhandler.h, src/ui/main.qml, tests/qml/CMakeLists.txt, tests/qml/moccontroller.cpp, tests/qml/qml.pro, tests/unit/moccontroller.cpp, translations/strings.yaml
Fixes: Server unavailable message is misleading if blocked by firewall
-> In parallel with the handshake, we attempt to ping the server.
-> If the ping succeeds and the handshake fails, the error message is changed to reflect that this might be a firewall issue. 
[ Jira VPN-1748 ](https://mozilla-hub.atlassian.net/browse/VPN-1748)
=> Do a canary ping while connecting, pass info to the unavailable notification

nebula/ui/components/VPNMenu.qml
This refactors VPNMenu.qml to handle longer menu titles in some locales.
VPN-2621
#4090
=> 2621/4090 - Fix menu UI breakages with lengthier menu titles

tools/wasm_chrome/branch_selector.mjs, tools/wasm_chrome/deno.json, tools/wasm_chrome/generate_branch_file.ts, tools/wasm_chrome/taskcluster_frame.mjs
2 Bugs in the wasm-viewer. 
I miscalculated the cache time, the age getting smaller instead of bigger, therefore you would never fetch new branches. 
Also fixed a race. The wasm-info json, might not have info of the "main" branch, as taskcluster might not have started building the wasm client. Currently, the script will mark it as "no-run" info, like a stale branch. Let's never have that for main.
=> Fix cache calc

src/tasks/adddevice/taskadddevice.cpp, tests/unit/mocnetworkrequest.cpp
This can be a good fix for the key-rotation
=> Disable timers for add-device requests

src/ui/navigator/navigationBar/VPNBottomNavigationBar.qml, src/ui/navigator/navigationBar/VPNBottomNavigationBarButton.qml
This hides the bottom navigation bar and disables the navigation buttons during connection speed tests
VPN-2768, nothing in GH yet.
=> Hide navigation bar during speed test

src/statusicon.cpp
Make sure the indicator color is always set initially and is being reset if we are not in `StateMain`.
[VPN-2520](https://mozilla-hub.atlassian.net/browse/VPN-2520): Menu bar status indicators
=> Init and reset menu indicator color

src/addons/addon.cpp, src/addons/addon.h, src/addons/addonapi.cpp, src/addons/addonapi.h, src/addons/conditionwatchers/addonconditionwatcherjavascript.cpp, src/addons/conditionwatchers/addonconditionwatcherjavascript.h, src/composer/composerblockbutton.cpp, src/composer/composerblockbutton.h
Having an API object per add-on means that we can store data and we can keep separate state machines for each addon without conflicts.
=> Separate AddonApi per addon

src/platforms/macos/macosutils.mm
Always scale the status bar icon to fit the status bar height.
- [VPN-2520](https://mozilla-hub.atlassian.net/browse/VPN-2520): Status bar scaling issue: https://mozilla-hub.atlassian.net/browse/VPN-2520?focusedCommentId=582118
=> fix: Always set the status icon dimensions to the status bar height

macos/pkg/scripts/postinstall
On my mac when running postinstall.sh  i'm getting:
``` 
/Library/LaunchDaemons/org.mozilla.macos.FirefoxVPN.daemon.plist: Could not find specified service
Unload failed: 113: Could not find specified service
```
The script then exits with return code `126` - Therefore the installer will consider it failed. 
Let's only unload the daemon when we know it's there, and make the comments log entries so we can check at which time stuff is failing :)
=> MacOs/Installer: Check if the daemon exists before unloading

linux/mozillavpn.service.in, linux/netfilter/netfilter.go, src/featureslistcallback.h, src/platforms/linux/daemon/apptracker.cpp, src/platforms/linux/daemon/apptracker.h, src/platforms/linux/daemon/dbusservice.cpp, src/platforms/linux/daemon/dbusservice.h, src/platforms/linux/daemon/wireguardutilslinux.cpp, src/platforms/linux/daemon/wireguardutilslinux.h, src/platforms/linux/linuxdependencies.cpp, src/platforms/linux/linuxdependencies.h
This is an experiment to investigate how to pursue split tunnelling with Linux Control Groups v2. This presents some unique challenges because the support for network traffic classification was dropped in the transitions from Cgroups v1 to v2. And there doesn't appear to be a reliable mechanism to map between control group and application ID.
Roughly speaking, to resolve this issue, we need to accomplish the following tasks:
See: #3283
=> Experiment: Support split tunneling with cgroups v2

src/filterproxymodel.cpp
If the JS callback fails or throws an error, we do not report it. And we should.
=> Expose JS errors in FilterProxyModel

glean/metrics.yaml, src/constants.h, src/featureslist.h, src/mozillavpn.cpp, src/mozillavpn.h, src/ui/screens/settings/ViewSubscriptionManagement/SubscriptionManagementItem.qml, src/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml, tests/functional/testSubscription.js, translations/strings.yaml
This PR:
- Adds "bundleUpgrade" feature
- Adds bundle upgrade UI to in-app subscription management view. This UI is hidden unless:
-  the bundleUpgrade feature is enabled
-  the subscription type is "web"
-  the locale is en_US or en_CA
VPN-2726, #4243
=> Add bundle upgrade UI to subscription management view

nebula/ui/components/forms/VPNSearchBar.qml, src/ui/screens/messaging/ViewMessagesInbox.qml
Without this PR, we close all the swipe at each filtering callback execution which means at least for each message. We just need to do it once when the search input-field value changes.
=> Optimize the filtering of messages

CODEOWNERS
I've realized addon changes (including strings) are not flagged for review (e.g. https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4351).
This fix is less than ideal, since it will pick up more changes than needed, but the proper approach would be a lot more complex (as part of a workflow actually compare strings.yaml, see if it changes, then flag the l10n reviewer in the PR via gh commands, probably requiring a PAT).
- [] I have commented my code PARTICULARLY in hard to understand areas
=> Flag addon changes for l10n review

taskcluster/ci/build/wasm.yml
The wasm builds are not indexed, let's add them so we can load those up in the wasm viewer as fallback :)
=> add wasm builds to the index

src/frontend/navigator.cpp, src/frontend/navigator.h, src/mozillavpn.cpp, src/ui/navigator/navigationBar/VPNBottomNavigationBarButton.qml, src/ui/navigator/navigatorLoader.qml
In this PR I introduce a LoadingFlags enum where I can specify the type of loading I want:
- reload the current one
- reload all of them
Then, I use 'reload all of them' when the MozillaVPN state changes. This fixes VPN-2800
=> Implement a way to reload all the screens - VPN-2800

tools/wasm_chrome/branch_selector.mjs, tools/wasm_chrome/index.html, tools/wasm_chrome/taskcluster_frame.mjs
We have the "main" branch now on the index. In case we want to load main, let's use that build. So we can load up the latest "successfull" commit instead of getting an error when the build is still running.
=> WasmLoader: Load main branch from the Taskcluster index

android/resources/all/drawable/ic_mozvpn_mono.xml, android/resources/debug/mipmap-anydpi-v26/vpnicon.xml, android/resources/release/mipmap-anydpi-v26/vpnicon.xml
Android 13 allowed 3rdparty apps to use the themed icon feature -  https://developer.android.com/about/versions/13/features#themed-app-icons
Android will when the app is on the home screen generate a themed version of the app icon. The app-list is unaffected :)
=> Android: Add Themed Icon support

nebula/ui/components/forms/VPNSearchBar.qml
Prevent errored searchbar inputs from being eaten
[VPN-2842: Strange behavior in the search-box in the messaging view](https://mozilla-hub.atlassian.net/browse/VPN-2842)
=> Allow errored searchbar to accept input

src/ui/screens/ScreenNoSubscriptionFoundError.qml, src/ui/screens/ScreenSubscriptionExpiredError.qml, src/ui/screens/ScreenSubscriptionGenericError.qml, src/ui/sharedViews/ViewErrorFullScreen.qml
Return user to `ViewSubscriptionNeeded` to re-select a subscription option when clicking "Try again" on an IAP full screen error
[VPN-2892: [iOS] “Try again” button from “Problem confirming subscription” error screens does not work](https://mozilla-hub.atlassian.net/browse/VPN-2892)
=> Fix try again button on IAP error screen

src/ui/navigator/navigationBar/VPNBottomNavigationBar.qml, src/ui/navigator/navigationBar/VPNBottomNavigationBarButton.qml
Prevent clicks from going through the navbar into components behind it
[VPN-2887: Components behind the navbar can be clicked](Components behind the navbar can be clicked)
=> Prevent navbar composed clicks

addons/message_privacy_bundle_staging/manifest.json
This removes the platform condition from the privacy bundle in-app message. This means that 
- All devices which meet the locale condition will be eligible to receive the bundle message
- The 'bundleUpgrade' feature will be enabled on devices which receive the bundle message, which unlocks the UI in the subscription management view for a larger pool of people.
- There is additional visibility logic in the subscription management view which will still prevent the upgrade UI in that view from being exposed to users who purchased their subscription through IAP (though they may still receive the bundle message)
VPN-2898
=> Remove platform condition from bundle message

nebula/ui/components/VPNSettingsItem.qml, src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml, src/ui/screens/getHelp/developerMenu/ViewFeatureList.qml, src/ui/screens/settings/ViewSettingsMenu.qml
Fixes the breaking layout in the settings menu after transitioning from landscape to portrait mode. 
#4293 (layout breakage only, does not address native ui color changes in guides)
=> Fix 2758/#4293

src/controller.cpp
Currently, I added a port53 fallback to the end of the activation-retry phase. 
However, not every City has 10 Servers, meaning we might try all servers on the City (and putting them on cooldown) before even attempting to connect to one with p53. 
Let's have the 2nd activation try port 53 and have the rest be classic :)
=> Try port53 fallback early

nebula/ui/components/VPNConnectionInfoScreen.qml, src/ui/navigator/navigationBar/VPNBottomNavigationBar.qml
This PR:
- Prevents the nav bar from becoming visible when VPN.state !== VPN.StateMain (VPN-2828)
- Closes connection speed tests when a user navigates away from ScreenHome, and resets nav bar opacity on Navigator current component changes. (VPN-2891, VPN-2897)
VPN-2891, VPN-2828, VPN-2897
=> Fix nav bar visibility bugs

nebula/ui/components/VPNMenu.qml, src/ui/screens/devices/ViewDevices.qml, src/ui/screens/messaging/ViewMessage.qml
- Menu title is always centered
- Menu title elides instead of overlapping menu actions
Examples of eliding:
[VPN-2799: Menu title is glitchy, off-center on some views](https://mozilla-hub.atlassian.net/browse/VPN-2799)
=> Center menu title and elide when appropriate

src/constants.h, src/models/subscriptiondata.cpp, src/models/subscriptiondata.h, src/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
This PR:
1.) looks through the user's list of subscriptions for a bundle subscription and
2.) hides bundle upgrade paths in ViewSubscriptionManagement if a bundle subscription exists
@flozia , @bakulf These changes were requested by PM on Thursday. You two are more familiar with the gotchas and things that can go wrong here. If this doesn't seem scary, it'd be nice to get it in but I don't want to introduce something that could cause us a lot of potential grief at this late stage. What do we think?
[VPN-2913](https://mozilla-hub.atlassian.net/browse/VPN-2913)
=> Hide bundle upgrade if already subscribed

src/connectionhealth.cpp
I don't know if this is the reason of this bug. But for sure it sounds like a bug the use of m_dnsPingLatency if not initialized.
=> Use DNS ping latency only when enabled - VPN-2647

src/platforms/windows/daemon/windowstunnelservice.cpp, src/platforms/windows/daemon/windowstunnelservice.h
After some refactoring of the windows daemon startup, we are now leaking a bit too much data into the backend logs. We can close some of this by stripping the arguments from the daemon command line.
=> Reduce logging of tunnel service command line.

taskcluster/ci/test/kind.yml
- Don't install extra dependencies that won't be in the `taskgraph` decision task on the test
- Use `taskgraph full -p taskcluster/test/params` to run `taskgraph` with the parameter files
cc @strseb 
#4341
=> Clean up Taskgraph definition test

nebula/ui/components/forms/VPNSearchBar.qml
- Trigger the search bar edit callback when text is deleted (not just added) and remove `_searchBarHasError` criteria
[VPN-2895: Messages are not swiped close when being in the “Edit” mode and using the search bar](https://mozilla-hub.atlassian.net/browse/VPN-2895)
=> Fix when edit callback is triggered for search bar

src/connectionbenchmark/benchmarktaskdownload.cpp
QDnsLookup is still not implemented for android. Let's see with qt6.5
=> Fix the compilation of Qt6.4

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
For some locations, it is possible that we might find ourselves without any fallback servers (eg: Skopje, Macedonia has only a single server). When trying to connect to such a location, we encounter an exception in `VPNService.kt` when parsing the connection parameters from JSON.
To fix this, we attempt to check for the existence of `serverFallback` before attempting to parse it.
Github #4569 ([VPN-2978](https://mozilla-hub.atlassian.net/browse/VPN-2978))
=> Fix android exception when no fallback server is present.

taskcluster/ci/beetmover/kind.yml
`action:release-promotion` checks if the `"task_for"` is in the tasks `"run-on-tasks-for"` [here](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/df7517bc5aeda13601891d9ff448cef0b8249e19/taskcluster/mozillavpn_taskgraph/transforms/beetmover.py#L36)
The `"task_for"` in the action's decision task is `"action"`. The beetmover task thinks this is not an real `release-promotion` action because `"action"` is not in `["github-release", "action:release-promotion"]`
[Here's a busted task](https://firefox-ci-tc.services.mozilla.com/tasks/WGbSR9wKSgiMRlN7IJMGkw)
[RELENG-981](https://mozilla-hub.atlassian.net/browse/RELENG-981)
=> Fix release-promotion trying to push to dep bucket in prod

taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
Ignore deprecated addons when populating the addons release-artifacts.
[RELENG-981](https://mozilla-hub.atlassian.net/browse/RELENG-981)
=> Ignore deprecated addons when populating release-artifacts

src/controller.cpp
On iOS 16, the operating system now has the ability to activate VPN services directly through the settings menu, and much to my surprise it *almost* works. The only thing that falls apart is the UI which doesn't handle the unexpected `connected()` signal from the VPN service, leading to deadlocks and UI breakage.
To fix this, the `Controller` simply needs to be prepared to handle such an unexpected signal, and transition states correctly. 
Github #4558 ([VPN-2970](https://mozilla-hub.atlassian.net/browse/VPN-2970))
=> Gracefully handle external activation of VPN service.

src/platforms/ios/ioscontroller.mm
Only disconnect preventively if we are not in `Controller::StateInitializing`.
- #4553
- Jira issue: [VPN-2965](https://mozilla-hub.atlassian.net/browse/VPN-2965)
=> fix: VPN disconnects after swipe kill on iOS

addons/message_whats_new_v2.10/manifest.json
This removes an incorrect bullet point from the Whats New message.
VPN-2992, #4595
=> Remove incorrect string from message_whats_new_v2.10

nebula/ui/components/forms/VPNSearchBar.qml, src/ui/screens/messaging/ViewMessagesInbox.qml
- Always close message swipe delegate after search query changes
- Exit edit mode in inbox if the last swiped open message is deleted
[VPN-2895: Messages are not swiped close when being in the “Edit” mode and using the search bar](https://mozilla-hub.atlassian.net/browse/VPN-2895)
=> Fix edit mode bugs in message inbox

src/addons/addon.cpp, src/addons/addon.h, src/addons/manager/addonmanager.cpp, tests/unit/testaddon.cpp
This is a nasty bug. The STR/bug is the following:
1. using the jira STR, we have only 2 addons with a conditional-watcher locale set to 'it'
2. set the locale to 'ru'; the addons are disabled. AddonManager has 0 active addons.
3. change the language to 'it'
4. the conditional watcher of addon A emits `conditionChanged(true)`
5. the addonManager adds the addon in the list.. but to do this, QT calls `rowCount` which calls, for each addon `->enabled()`, which calls `addon->m_conditionalWatcher->conditionApplied()` which returns `true` for both addons. `rowCount` _before_ adding the first addon return 2 - the bug.
6. QT thinks there are 2 addons and we are adding a 3rd one.
7. in the log we see an error message about an invalid QModelIndex
8. In the frontend code we use a …
=> Cache the conditionEnabled status to avoid race conditions - VPN-3006

nebula/ui/components/VPNLinkButton.qml
Fix crash when clicking link buttons with space bar (specifically ones that call VPNNavigator.requestScreen())
[VPN-3012: Keyboard navigation through VPN screens before being signed in causes the app to quit](https://mozilla-hub.atlassian.net/browse/VPN-3012)
=> Fix link button crash when clicked via space bar

windows/installer/MozillaVPN.wxs, windows/installer/MozillaVPN_cmake.wxs, windows/installer/MozillaVPN_prod.wxs
For MSI installers, the typical upgrade flow when installing over an already-installed version of the client is to check the file version numbers, and update the files only if the version has changed. When installing or updating a beta or release candidate build we don't always change the version number leading to incomplete installations.
To address this situation, we change the `MajorUpgrade` schedule to use the `afterInstallValidate` which will force uninstallation of the old version first, and ensuring that we always apply the update correctly at the expense of more time spent copying files.
Github #4617 ([VPN-3002](https://mozilla-hub.atlassian.net/browse/VPN-3002))
=> MSI: Use afterInstallValidate schedule during upgrades

src/featureslist.h, src/featureslistcallback.h, src/models/feature.cpp, src/models/feature.h, tests/unit/testaddon.cpp, tests/unit/testaddonapi.cpp, tests/unit/testfeature.cpp
This PR (VPN-3033) is needed to compute the flip on/off of `addon-signature` after the main.
=> Use flippable on/off as callback to execute them after the main()

src/taskscheduler.cpp, tests/unit/testtasks.cpp, tests/unit/testtasks.h
When we delete tasks, maybe we do not delete them all because some of them could be marked as "not-deleteable". So, when this happens, we need to schedule the following task.
=> Schedule more tasks after a `TaskScheduler::deleteTasks()` - VPN-3010

taskcluster/scripts/build/windows.ps1
Adds `--remote` to the submodule init incantation in the TaskCluster windows build script
VPN-3032, #4653
=> Fix VPN-3032 : Missing strings on Windows builds

src/addons/addon.cpp, src/addons/addon.h, src/addons/manager/addonmanager.cpp
This is already on `main` and was implemented on #4642. 
I extracted only what mattered so that we can ship it with 2.10, because it causes a crash.
Fix for the issues with the debug build crashing on force quit I'll send another PR for.
=> VPN 3047 - Remove call to log on addon destruction

src/adjust/adjusthandler.cpp, src/captiveportal/captiveportaldetection.cpp, src/connectionbenchmark/connectionbenchmark.cpp, src/controller.cpp, src/errorhandler.cpp, src/externalophandler.cpp, src/ipaddresslookup.cpp, src/keyregenerator.cpp, src/networkwatcher.cpp, src/platforms/ios/iosdatamigration.mm, src/platforms/macos/macossystemtraynotificationhandler.cpp, src/profileflow.cpp, src/server/serverconnection.cpp, src/statusicon.cpp, src/systemtraynotificationhandler.cpp, src/telemetry.cpp, src/tutorial/tutorial.cpp, src/update/webupdater.cpp, src/websocket/pushmessage.cpp, src/websocket/websockethandler.cpp
That is not necessary. MozillaVPN::instance already asserts that.
=> No ticket - Remove all Q_ASSERT(vpn) after using MozillaVPN::instance

src/cmake/sources.cmake, src/commands/commandui.cpp, src/qmake/sources.pri, src/temporarydir.cpp, src/temporarydir.h, src/update/balrog.cpp, src/update/balrog.h, src/wgquickprocess.cpp, tests/unit/CMakeLists.txt, tests/unit/testtemporarydir.cpp, tests/unit/testtemporarydir.h, tests/unit/unit.pro
Somehow when the app is executed by the PKG installer on macos, it runs in a sandbox that does not have access to the temporary folder. This does not happen when the app is executed by the user.
The result is that, QTemporaryDir is invalid at the first execution. We use QTemporaryDir with balrog to download the new version of the app so, it must work. This is a TemporaryDir implementation with fallback in the App-Data directory.
=> TemporaryDir component - VPN-3074

android/AndroidManifest.xml, android/build.gradle, android/buildSrc/src/main/kotlin/Config.kt, android/buildSrc/src/main/kotlin/Dependencies.kt, android/daemon/build.gradle, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/NotificationUtil.kt, taskcluster/docker/android-qt6-build/Dockerfile
As per Google Play policy, the next Update needs to Target SDK version 31. 
This PR: 
-> Bumps the target sdk,
-> Fixes new violations
-> Updates old deps
-> Cleans up our dependency tree
=> Android: Bump target sdk

nebula/ui/components/VPNRecentConnections.qml
- Initialize the recent connections model earlier in `VPNRecentConnections`'s initialization so that it is factored into `VPNServerList`'s `contentHeight`
[VPN-927: Active server is not centered when going from ViewMain to the single hop server list when there are recent connections.](https://mozilla-hub.atlassian.net/browse/VPN-927)
=> VPN-927: Center selected server in server list on init

nebula/ui/components/VPNCancelButton.qml, nebula/ui/components/VPNSignOut.qml, nebula/ui/themes/themes.js, src/ui/deleteAccount/ViewDeleteAccountRequest.qml, src/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
Adds theme for red text button links.
- [VPN-3052](https://mozilla-hub.atlassian.net/browse/VPN-3052): Change main red color for red text buttons to #E22850
=> Add theme for red text buttons links

src/constants.h, src/update/balrog.cpp
Instead of using the staging balrog instance, always use the production instance, so that staging is no longer on the critical path for releases.
https://mozilla-hub.atlassian.net/browse/RELENG-797
=> Use the production balrog server (and a test channel) in testing mode

src/commands/commandui.cpp, src/connectionbenchmark/benchmarktasktransfer.cpp, taskcluster/ci/build/android.yml, taskcluster/ci/docker-image/kind.yml
I want to have a task that will assert we can get builds with the "next" version of QT - so we can either QA that or throw this in some automation ... or let me check if my build tools break :)
=> Taskcluster: Check compat with "next" QT

src/tasks/addonindex/taskaddonindex.h
I don't know if we want to write a unit-test to check the delete state of each task. It seems not particularly useful. Note the the logic is fully tested already.
=> Make the TaskAddonIndex reschedulable - VPN-3094

src/addons/addon.cpp, src/addons/conditionwatchers/addonconditionwatcherlocales.cpp, src/collator.cpp, src/localizer.cpp, src/localizer.h, tests/unit/testlocalizer.cpp
A bit of context: on IOS, bc47name() returns `es-US` when the language is set to spanish. The fix to this issue is to use the `uiLanguages` method (https://doc.qt.io/qt-6/qlocale.html#uiLanguages).
In this PR I also centralize the fetching of system language code in all the code base.
=> Fix 'es' language on iOS - VPN-2212

src/platforms/macos/macosstatusicon.h, src/platforms/macos/macossystemtraynotificationhandler.cpp, src/platforms/macos/macossystemtraynotificationhandler.h
This does _not_ cause the other systray icon to blink when a new notification is show. At least not that I could see.
=> VPN-2804 - Get notifications to work (again) on MacOS

.github/workflows/linux.yaml, linux/mozillavpn.spec, vpnglean/CMakeLists.txt
The recent introduction of glean.rs as a build step introduced a dependency on OpenSSL that was failing on Fedora-based distributions due to an expectation that we could find a static SSL library. For security reasons, Fedora does not provide such a library.
We also do a little bit of cleanup in terms of the rust build steps to ensure we honour the Release/Debug configuration for multi-config generators.
Github #4780 ([VPN-3116](https://mozilla-hub.atlassian.net/browse/VPN-3116))
=> Cleanup Glean/Rust openssl dependencies

nebula/ui/components/forms/VPNTextArea.qml, nebula/ui/components/forms/VPNTextField.qml
The issue was introduced by PR #4738 that provides a workaround for issue #4555. We only need this change to be applied to macOS.
- Fixes #4791
- Fixes #4819
=> fix: Text input focus

nebula/ui/components/VPNFlickable.qml, nebula/ui/components/VPNScreenBase.qml, nebula/ui/components/VPNServerList.qml, nebula/ui/components/VPNTabNavigation.qml, nebula/ui/components/VPNViewBase.qml, nebula/ui/components/inAppAuth/VPNInAppAuthenticationBase.qml, src/ui/screens/ScreenCaptivePortal.qml, src/ui/screens/ScreenGetHelp.qml, src/ui/screens/getHelp/contactUs/ViewContactUsThankYou.qml, src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml, src/ui/screens/getHelp/developerMenu/ViewMessages.qml, src/ui/screens/getHelp/giveFeedback/ViewGiveFeedbackReview.qml, src/ui/screens/getHelp/giveFeedback/ViewGiveFeedbackThankYou.qml, src/ui/screens/home/ViewHome.qml, src/ui/screens/home/ViewMultiHop.qml, src/ui/screens/settings/ViewGuide.qml, src/ui/screens/settings/ViewLanguage.qml, src/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml, src/ui/screens/settings/dnsSettings/DNSSettingsTabContent.qml, src/ui/screens/tipsAndTricks/ViewTipsAndTricks.qml, src/ui/sharedViews/ViewErrorFullScreen.qml
- Make VPNFlickable calculate the amount of padding to add to it's `contentHeight` to support an even amount of spacing between the bottom of each page's content and the navbar
- Remove a bunch of arbitrary padding from views
[VPN-2875: Inconsistent content height in scrollable content](https://mozilla-hub.atlassian.net/browse/VPN-2875)
=> Consistent spacing between navbar and UI content

src/mozillavpn.cpp
Sarah debugged the issue. This PR is only the result of her work.
In VPN-2934, https://github.com/mozilla-mobile/mozilla-vpn-client/commit/37de80e874b6701d43ccdb03b7c18e4406317aee - we changed how the periodic tasks are scheduled: instead of checking the app state, we checked the existence of the JWT .
But during the subscription, we have the token, but the device has not been registered yet.
In staging, the scheduling of the periodic tasks is more aggressive (10/4-secs) and, when this happens, we reset the settings because the current device is not found the the account data from guardian.
This PR reverts part of VPN-2934. @brizental can you please check if this breaks VPN-2934?
=> Schedule the periodic tasks only when the app is in the main state - VPN-3115

src/networkrequest.cpp
This is nice to have to spot errors like VPN-3115.
=> Assert when a network request should include the JWT but this has not been set yet - VPN-3181

CODEOWNERS
L10n wasn't pinged in a recent change (#4824) to addons.
Not sure why it used to work, probably because nobody else was set as owner in the file for /addons
=> Fix CODEOWNERS for addon manifests

android/build.gradle, src/cmake/android.cmake
Forgot about ssl >:c - Also link against qt-test so it's picked up by the qmlimportscanner (it's used in the inspector it seems)
=> Android: fix cmake stuff

.taskcluster.yml, taskcluster/ci/config.yml
Migrate mozilla-vpn-client from AWS to GCP
**Requires https://phabricator.services.mozilla.com/D161329 to land first before merging!**
https://bugzilla.mozilla.org/show_bug.cgi?id=1799194
=> Bug 1799194 - Migrate mozilla-vpn-client from AWS to GCP

nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml
Opening as draft until I can smoke test on a physical device (tomorrow). 
Disable authentication inputs after clicking submit. Re-enable auth inputs if there is an error and we are unable to proceed to next step in flow. 
VPN-2702, #4219
=> Disable auth inputs after clicking submit - Fix VPN-2702

src/ui/authenticationInApp/ViewAuthenticationStart.qml
Check for valid email address formatting before enabling the "Continue" button on the start in-app auth view.
... 
I could have _sworn_ we used to check for valid email formatting before enabling the "Continue" button. Anyone remember if/why we removed it? cc @flozia 
=> Validate email before enabling submit button

nebula/ui/components/VPNServerCountry.qml, nebula/ui/nebula_resources.qrc, nebula/ui/resources/wifi-0.svg, nebula/ui/resources/wifi-1.svg, nebula/ui/resources/wifi-2.svg, nebula/ui/resources/wifi-3.svg, src/cmake/sources.cmake, src/constants.h, src/featureslist.h, src/models/server.cpp, src/models/server.h, src/models/servercity.cpp, src/models/servercity.h, src/models/servercountry.cpp, src/models/servercountrymodel.cpp, src/models/servercountrymodel.h, src/mozillavpn.cpp, src/mozillavpn.h, src/platforms/linux/linuxpingsender.cpp, src/platforms/macos/macospingsender.cpp, src/platforms/windows/windowspingsender.cpp, src/qmake/sources.pri, src/serverlatency.cpp, src/serverlatency.h, src/tasks/latency/tasklatency.cpp, src/tasks/latency/tasklatency.h, tests/unit/testmodels.cpp
This adds storage of server latency data into the `Server` class, and adds a mechanism to refresh the server latency information whenever we update the server list, and then display that latency data to the user through a wifi with a variable number of bars.
JIRA: [VPN-2526](https://mozilla-hub.atlassian.net/browse/VPN-2526)
=> Measure and display latency in server view.

src/addons/addon.cpp, src/addons/addon.h, src/tutorial/tutorialstep.cpp, src/tutorial/tutorialstep.h
I would like to add an unit-test but I don't want a good way to retrieve data from the JS execution. As soon as we have: `addon.states.session` we can write a test. @brizental would it work for you?
=> Better condition support for addon-tutorial steps

scripts/ci/jsonSchemas/tutorial.json, src/addons/addonmessage.cpp, src/addons/addontutorial.cpp, src/addons/addontutorial.h, src/adjust/adjusthandler.cpp, src/commands/commandui.cpp, src/glean/glean.cpp, src/networkwatcher.cpp, src/networkwatcher.h, src/platforms/android/androidglean.cpp, src/platforms/android/androidvpnactivity.cpp, src/platforms/android/androidvpnactivity.h, src/platforms/macos/macosstartatbootwatcher.cpp, src/platforms/macos/macosstartatbootwatcher.h, src/platforms/windows/windowsstartatbootwatcher.cpp, src/platforms/windows/windowsstartatbootwatcher.h, src/settingsholder.cpp, src/settingsholder.h, src/settingslist.h, tests/auth/CMakeLists.txt, tests/qml/CMakeLists.txt, tests/qml/helper.h, tests/unit/CMakeLists.txt, tests/unit/testaddon.cpp, tests/unit/testsettings.cpp, tests/unit/testsettings.h
This PR implements transactions for the settings. Addon tutorials will be able to start a transaction, change a few things, than revert all.
In order to support other setting changes during a tutorial, I marked all the settings with a new flag: 'user-settings'. A user-setting is something that is controlled by the user via the front-end code. Only those settings are reverted in case of a rollback or a crash.
=> Transaction for settings

nebula/ui/components/VPNSubscriptionOption.qml, src/cmake/sources.cmake, src/commands/commandui.cpp, src/featureslist.h, src/iaphandler.cpp, src/iaphandler.h, src/mozillavpn.cpp, src/platforms/android/androidiaphandler.cpp, src/platforms/android/androidiaphandler.h, src/platforms/dummy/dummyiaphandler.cpp, src/platforms/dummy/dummyiaphandler.h, src/platforms/ios/iosiaphandler.h, src/platforms/ios/iosiaphandler.mm, src/platforms/wasm/wasmiaphandler.cpp, src/platforms/wasm/wasmiaphandler.h, src/productshandler.cpp, src/productshandler.h, src/qmake/sources.pri, src/tasks/products/taskproducts.cpp, src/ui/screens/subscriptionNeeded/ViewSubscriptionNeeded.qml
Split products management out of IAPHandler. This paves the way for more purchase management in app on desktop.
This PR should be a no-op functionally. It is just separating concerns to lay the groundwork for the next PR.
Prep work for [VPN-2253](https://mozilla-hub.atlassian.net/browse/VPN-2253)
=> VPN-3071(Part 1) Split products

src/platforms/windows/windowspingsender.cpp, src/platforms/windows/windowspingsender.h
In order to prevent hanging the client when terminating a `WindowsPingSender` we need to perform an asynchronous call to `IcmpCloseHandle` from a separate thread. This can lead to a possible use-after-free bug if the kernel still needs to write userspace memory. To resolve this, we need to wait until after `IcmpCloseHandle` returns before freeing userspace memory that it accesses.
Github #4829 ([VPN-3175](https://mozilla-hub.atlassian.net/browse/VPN-3175))
=> Fix crash in Windows ping sender cleanup

src/addons/addonapi.cpp, src/addons/addonapi.h, tests/unit/addons/addons.qrc, tests/unit/addons/api_controller.js, tests/unit/testaddonapi.cpp, tests/unit/testaddonapi.h
This is needed for the split-tunnel tutorial because we want to expose it only if the VPN is off.
=> Add the controller API to addons - VPN-3236

src/ui/screens/ScreenSubscriptionNeededWeb.qml, src/ui/screens/subscriptionNeeded/ViewSubscriptionNeededWeb.qml
Adjust the layout for the ScreenSubscriptionNeededWeb layout.
- [Figma](https://www.figma.com/file/bhBrWadoHD3mq8ttagkKXy/Desktop-In-app-auth?node-id=235%3A12777&t=8CWZmo2iDTW4dBA5-0): Design spec
=> Ajustments to the ScreenSubscriptionNeededWeb layout

.gitignore, src/CMakeLists.txt, src/cmake/macos.cmake
For static builds of Qt using CMake, we need to perform a scan to link in plugins required for the QML imports. For our MacOS builds, we are attempting to do this with an explicit call to `qt6_import_qml_plugins()` however, this only picks up dependencies that exist at the time of this call. It is far better to defer this to target finalization (eg: in `qt_finalze_target()`)
Github issue #4920 ([VPN-3247](https://mozilla-hub.atlassian.net/browse/VPN-3247))
=> Possible fix to QML plugin scanner on static MacOS builds

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt
Small nits. 
-> Move state-notifications to the setter of `tunnelHandle`, and thus remove the setter of `isUp`
-> Make sure `isUp` is used in favor of checking the handle themselves, so isUp is the "truth" for all checks. 
Actual fix: 
-> Remove the `isUp` check when the client disconnects from the daemon. We only go foreground on "activation" and remove that on "deactivation". So that check was redundant anyway. As we now have connection health in the daemon, isUp might be false when that happens (as we might be switching).
=> Android: Fix serivce

src/constants.h, src/mozillavpn.cpp, src/notificationhandler.cpp, src/notificationhandler.h, translations/strings.yaml
This adds a new `SubscriptionNotFound` OS notification which is sent when the client becomes aware, for now via periodic pings to Guardian, that a valid subscription does not exist. 
VPN-3240 / #4910
=> Add subscription not found OS notification

src/connectionbenchmark/benchmarktasktransfer.cpp, src/connectionbenchmark/connectionbenchmark.h, src/constants.h
Add upload benchmark endpoints and fixes the calculation for transferred bytes.
- Jira: [VPN-2519](https://mozilla-hub.atlassian.net/browse/VPN-2519)
- #4948
=> Set upload benchmark endpoints

src/connectionbenchmark/benchmarktaskdownload.cpp, src/connectionbenchmark/benchmarktasktransfer.cpp
Some users are starting to build the VPN client on Qt version 6.4 and newer on Linux, which is leading to breakage in the Android `QDnsLookup::lookup()` workaround. We should nest the workaround checks for this to throw an error only when built for one of the affected platforms.
Github issue #4940
=> Fix android workaround check breaking builds on Qt>6.4

.gitmodules
This fixes the IPv6 bug present in iOS 16. There is a similar [PR up for wireguard](https://github.com/WireGuard/wireguard-apple/pull/17), and according to folks at Mullvad this is something that is on the radar of WireGuard folks. 
After WireGuard updates their code to include this 2 line fix, we'll put up a new PR so that we're using WireGuard's repo again, and we can remove our fork. 
After checking out this branch, you'll need to run this command in the main VPN project folder:
`git submodule sync && git submodule update --remote 3rdparty/wireguard-apple`
This bug occurs on IPv6 networks, like my cell provider. We've been unable to reproduce on WiFi, and so this may be hard to test. If you'd like me to verify the fix works in real time (by demoing connecting to my cell provider w/ the …
=> Update WireGuard for iOS

src/ui/screens/getHelp/giveFeedback/GiveFeedbackRadioDelegate.qml
- Prevents hover/focus outline from showing on iOS/Android when multiple delegates are tapped at the same time using multi-touch
[VPN-912: [mobile] More than one option can be selected on the “Give Feedback” screen](https://mozilla-hub.atlassian.net/browse/VPN-912)
=> Fix feedback radio delegate ui

balrog/build.cmd, taskcluster/ci/fetch/kind.yml, windows/tunnel/build.cmd
During the conversion to CMake, we began relying on the environment's golang version when building `tunnel.dll` and `balrog.dll`. This had a wonderful effect on build times, but we recently found that the resulting `balrog.dll` seems to have issues parsing certificates, and results in breakage of the update flow.
In my local builds, updating to the latest stable go1.18 seems to resolve the issue.
Github issue #4937 ([VPN-3255](https://mozilla-hub.atlassian.net/browse/VPN-3255))
=> Update windows/taskcluster builds to go1.18.8

nebula/ui/components/VPNCheckBoxRow.qml, src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml, src/ui/screens/settings/ViewNetworkSettings.qml, src/ui/screens/settings/ViewNotifications.qml, src/ui/screens/settings/ViewPreferences.qml, src/ui/screens/settings/appPermissions/AppPermissionsList.qml
* Disabled VPNCheckBoxRow's can no longer be checked/unchecked by clicking on their primary label
* Remove superfluous isEnabled property from VPNCheckBoxRow
[VPN-2947: “Add application” button from App permissions screen is active while the VPN is ON](https://mozilla-hub.atlassian.net/browse/VPN-2947)
=> Prevent disabled checkboxrows from being clicked

src/ui/screens/getHelp/giveFeedback/ViewGiveFeedbackReview.qml
This changes the give feedback flow to transition first to "Thank you" view before opening the app store after clicking the "Leave a Review" button. 
VPN-3031
=> feedback form: Open thank you view before app store review

src/featureslist.h
Do not enable the server connection score feature by default.
=> Disable server connection score feature flag

src/ui/screens/settings/appPermissions/AppPermissionsList.qml
- Addition to #4967 to also disable the "Add application" button in the App Permissions list
[VPN-2947: “Add application” button from App permissions screen is active while the VPN is ON](https://mozilla-hub.atlassian.net/browse/VPN-2947)
=> Disable "Add application" button when vpn is on

CMakeLists.txt, glean/CMakeLists.txt, src/CMakeLists.txt
This seems to confuse qml-importscanner, as it's omitting those libs. However DLopen will still be looking for them - therefore we can crash here.
=> Android: Do not link against libs we are not using

scripts/android/cmake.sh, taskcluster/scripts/build/android_build_release.sh
We now have a vpn-sentry project. It's url / key are secret so let's get those from taskcluster :)
=> Pass sentry info in android release builds

nebula/ui/components/forms/VPNPasswordInput.qml, translations/strings.yaml
This adds tooltip labels to the password input
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Fixes #5013 / VPN-3341
=> Add tooltip to password input eye icon

taskcluster/docker/android-qt6-build/Dockerfile, taskcluster/scripts/build/android_build_release.sh
For sentry to properly work with the stack-traces we need it to give the debug symbols. This pr's inits the sentry-cli and will upload missing info on any level-3 (main, releases) commit.
=> Sentry: Auto Upload debug symbols for level-3 commits

src/connectionbenchmark/connectionbenchmark.cpp, src/featureslist.h, tests/functional/testBenchmark.js
This reverts commit d35fb1940bab1f73524fb960e8bce771cf4ce0f9. It seem like this commit is responsible for the intermittent functional test failure of `testBenchmark.js`.
- #5008
=> Revert "Enable network upload benchmark by default (#4960)"

src/models/servercountrymodel.cpp, src/models/servercountrymodel.h
Our current algorithm to pick a random location does so in a non-uniform manner by choosing a random country and then choosting a random city within it. This disproportionately causes the selection algorithm to bias unfairly towards locations in smaller countries with fewer cities. For example, `Skopje, Macedonia` with a single server is given an equal proportion of the generated selections as all of the United States combined.
We feel that it is fairer to select a location that is weighted by the number of servers available to it. This should result in a fairer distribution of load that better matches the capacity of a given location.
=> Weight random server selection by number of servers.

src/authenticationinapp/authenticationinappsession.cpp, tests/auth/testsignupandin.cpp, tests/auth/testsignupandin.h
We were treating the `code` error message as a verification email step instead of a totp.
=> Totp error code should be treated correctly - VPN-3340

vpnglean/glean_parser_ext/run_glean_parser.py, vpnglean/glean_parser_ext/templates/cpp.jinja2
This is what the generated code looks like right now:
```cpp
struct AddonStateChangedExtra {
QVariant _addonId = QVariant();
QVariant _state = QVariant();
FfiExtra ToFfiExtra() const {
QVector<const char*> extraKeys;
QVector<const char*> extraValues;
if (_addonId.canConvert<QString>()) {
extraKeys.append("addon_id");
extraValues.append(_addonId.toString().toUtf8().constData());
}
if (_state.canConvert<QString>()) {
extraKeys.append("state");
extraValues.append(_state.toString().toUtf8().constData());
}
FfiExtra extras;
extras.keys = std::move(extraKeys.begin());
extras.values = std::move(extraValues.begin());
extras.count = extraValues.count();
return extras;
};
};
```
And what it looks like with this change:
```cpp
struct AddonStateChangedExtra {
QVariant _addonId = QVariant();
QVariant …
```
=> VPN-3382 - Do not use QVector to pass data to through the FFI boundary

src/commands/commandui.cpp
We want to create the variable, 
```
MacOSStartAtBootWatcher startAtBootWatcher
```
therefore the watchers never ran.
=> Fix start On boot

addons/message_update_v2.12/manifest.json, addons/message_update_v2.12/update.js
This is the change in the addon to force the update via web for windows if the range is [2.10.0, 2.11.0]
=> Update via web for 2.10/2.11 windows clients

.github/workflows/functional_tests.yaml, .github/workflows/ppa-automation.yaml, .github/workflows/test_lottie.yaml, .github/workflows/test_unit.yaml, .github/workflows/wasm.yaml
I have become frustrated at the functional tests taking 25 minutes to build. Let's see if we can do better.
Here is a quick breakdown of what I changed, and why it helped:
- Updating the github runners to `ubuntu-22.04` means that we no longer need to bring in a PPA for Qt6 support, and we can instead get those packages from the official repositories, which have much better caching and CDNs behind them.
- Caching `grcov` between runs saves us about 5 minuntes of compilation time.
- Minimizing the profiling data dramatically reduces the storage and bandwidth required to move the build artifacts around (3.5GB down to 250MB!).
- Now that the PPA is no longer necessary, copying the installed `.deb` files from build to test runners is actually slower than just installing fresh dependencies …
=> Functional test cleanup and speedups

ios/app/main.entitlements
We now need an entitlement to read the user-defined device name in iOS 16. This had been [added](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4768) and then reverted once. 
This PR has been tested with some changes we made in our Apple Developer account, and it now is working end-to-end.
=> iOS: Add entitlement for device name

CODEOWNERS, addons/message_update_v2.12/manifest.json, addons/message_whats_new_v2.12/manifest.json
I was once again ignored by CODEOWNERS in #5072, so I'm updating the order. From [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):
```
*.js    @js-owner
```
As for the review/fixes:
* `Opt in` is the verb, `opt-in` is the noun (like `log-in`/`log in`)
* `Multi-hop` is [always spelled](https://transvision.flod.org/?recherche=multi-hop&repo=vpn_client&sourcelocale=en&locale=en&search_type=strings_entities) with lowercase h in the product
=> Fix nits in v2.12 update/whasnew messages, update CODEOWNERS

addons/message_update_v2.12/enable.js, addons/message_update_v2.12/manifest.json, addons/message_update_v2.12/setDate.js, addons/message_update_v2.12/update.js, addons/message_update_v2.12/updateWeb.js
From JIRA:
```
1. The message “Download Mozilla VPN 2.12” is shown to users on the Windows 2.10 and 2.11 client.
2. The CTA on this message takes them to the Mozilla VPN download page: https://www.mozilla.org/en-US/products/vpn/download/
3. The message “Update to Mozilla VPN 2.12” is shown to users on the non-Windows 2.10, 2.11 and 2.11.1 clients. It also shows to users on the Windows 2.11.1 client.
4. The CTA on this message triggers the update mechanism that would be normally triggered in “About Us” > “Check for Updates”
```
Technically we do all of this in 1 single message, with 2 buttons which only one is shown based on the `enable.js` code.
=> Message Update V2.12: Show different buttons based on platform and version

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/NotificationUtil.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNTileService.kt, src/platforms/android/androidcontroller.cpp, src/platforms/android/androidnotificationhandler.cpp, src/platforms/android/androidvpnactivity.h
This is a 3part patch to fix the issues QA had. Most of those are caused of me merging a patch that was written a year ago 😅 
Well the PR was quite old on merge and was still under the assumption the Service will push the Current State on connect. Now Service-Clients need to request this themselves. 
The new `reconnect` function used for the toggle did not account that the Service might have been killed between activations - It now get's the last config from storage, like always-on.
This is really Polish. Currently the client has quite a bit of dept around notifications. It depends on the Client beeing alive and pushing the right notification text. 
This PR put's some band-aid on that, so both Tile-Service and Always-On at least show the translated "connected/disconnected" messages, when …
=> Fix the Android-Tile Service

src/ui/screens/getHelp/contactUs/ViewContactUsForm.qml, src/ui/screens/getHelp/giveFeedback/ViewGiveFeedback.qml
- Resolve issue where the "Give feedback" and "Contact support" pages would overflow off the edge of the screen when rotating the device's orientation to from portrait, to landscape, and then back to portrait
[VPN-3393: Some "Get help" page layouts get cut off on iPad after switching device orientation](https://mozilla-hub.atlassian.net/browse/VPN-3393)
=> Fix "Get help" page layouts when switching device orientation

src/featureslistcallback.h
This PR disables the Start-On boot feature on the 2.12 branch. 
It did not pass QA verification, therefore let's disable it here :)
=> Android: Disable start-on-boot for 2.12 

taskcluster/scripts/build/macos_build.sh
The level-3 macos task is broken and failing with: 
```
[task 2022-12-03T15:42:03.058Z] + ./taskcluster/scripts/get-secret.py -s project/mozillavpn/tokens -k sentry_dsn -f sentry_dsn
[task 2022-12-03T15:42:03.102Z] Traceback (most recent call last):
[task 2022-12-03T15:42:03.102Z]   File "./taskcluster/scripts/get-secret.py", line 12, in <module>
[task 2022-12-03T15:42:03.102Z]     import taskcluster
[task 2022-12-03T15:42:03.102Z] ModuleNotFoundError: No module named 'taskcluster'
```
So let's install the taskcluster dependencies :)
=> Fix MacOS build on Taskcluster

taskcluster/scripts/build/macos_build.sh, taskcluster/scripts/requirements.txt
Currently, we try to install all task cluster requirements. Not just the ones for get_secret.py
- however, our level-3 (main) runners have only python 3.6
- The level-1 (pr) have 3.8 
One of the packages requires 3.7 therefore this fails on main but not on pull-requests. >:c 
So let's only install the required packets for the script to run, which supports python 3.6
=> Only install requirements for get_secret.py

src/cmake/macos.cmake, taskcluster/ci/build/macos.yml, taskcluster/scripts/build/macos_build.sh
Reverts mozilla-mobile/mozilla-vpn-client#5057 
Breaks the CI again >:c
=> Revert "Taskcluster/OSX: Upload symbols"

nebula/ui/components/VPNTutorialPopups.qml
* Prevents an issue where the tips and tricks view wouldn't scroll after selecting a rollback tutorial, clicking "no thanks", and then exiting and re-entering the tips and tricks screen (flickable is no longer interactive because it thinks a tutorial is playing)
* Prevents a crash after clicking "no thanks" on a rollback tutorial and then starting a non-rollback tutorial
[VPN-3449: Tips and tricks view unscrollable after rejecting tutorial containing settings rollback](https://mozilla-hub.atlassian.net/browse/VPN-3449)
=> Stop tutorial when rollback warning modal is closed

src/addons/addon.cpp, src/addons/conditionwatchers/addonconditionwatcherlocales.cpp, src/collator.cpp, src/localizer.cpp, src/localizer.h, src/platforms/ios/iosutils.h, src/platforms/ios/iosutils.mm, tests/unit/testaddon.cpp, tests/unit/testlocalizer.cpp, tests/unit/testlocalizer.h
In theory QLocale::system()::uiLanguages() should return the list of ui-languages sorted. But, for some languages (es), on IOS, en-US is on top of the list even when it should not be.
=> Custom code to retrieve the iOS language - VPN-3336

.github/workflows/functional_tests.yaml, CMakeLists.txt, README.md, lottie/tests/qml/CMakeLists.txt, src/CMakeLists.txt, src/cmake/dummy.cmake, src/cmake/macos.cmake, src/cmake/signature.cmake, src/cmake/sources.cmake, src/cmake/windows.cmake, src/crashreporter/CMakeLists.txt, tests/auth/CMakeLists.txt, tests/dummyvpn/CMakeLists.txt, tests/qml/CMakeLists.txt, tests/unit/CMakeLists.txt, vpnglean/CMakeLists.txt
This allows us to generate both the genuine and dummy builds of the VPN client from the same cmake build directory, and eliminates the need for the `BUILD_DUMMY` configuration option. This also fixes building of the dummy client on MacOS, where cmake attempts to build the installer package.
This changes the path of the generated dummy client from `<build-dir>/src/mozillavpn` to `<build-dir>/tests/dummyvpn/dummyvpn`
This also lays some groundwork for making the dummy client runnable on mobile devices and their simulators (eg: by setting the `MACOSX_BUNDLE` attribute).
Github issue #4114 ([VPN-2637](https://mozilla-hub.atlassian.net/browse/VPN-2637))
Github issue #5114 ([VPN-3427](https://mozilla-hub.atlassian.net/browse/VPN-3427))
=> Split dummy client into its own cmake target

scripts/linux/script.sh
So, I think the bug here is simply that we have the logic backwards. If the repository is shallow then unshallow it, otherwise there is no need to fetch anything. This is a little bit thorny to test, because this path is only followed on the the release branches. So we kind of have to merge it before we have any idea if it works.
Github #5159 ([VPN-3472](https://mozilla-hub.atlassian.net/browse/VPN-3472))
=> Linux fix rc suffix

.github/workflows/ppa-automation.yaml, scripts/linux/script.sh
Recently we ran into some difficulty with the PPA automation workflow failing to unshallow the branches to compute the release candidate suffix. And after some discussion with @birdsarah we decided that we ought to try and do a better job aligning the version suffix with the build IDs that we generate on taskcluster. To that effect, let's just scrap the entire unshallow and refcounting process and just replace it with a timestamp instead.
This gets us a little bit closer, but we really want to just move this whole thing into taskcluster and get it to match the release process for Mac and Windows too but that's a bigger change for another PR.
Github #5159 ([VPN-3472](https://mozilla-hub.atlassian.net/browse/VPN-3472))
=> Use a timestamp for release candidate suffixes

scripts/utils/xlifftool.py
When dumping strings from an xliff file, and there is no translation found, use the source value instead. This was causing a bug in the MacOS installer for `en_US` because there aren't actually any target values for that locale. We already have similar code to handle this path for translations, but it just wasn't being called for the `--get` operation.
Github #5131 ([VPN-3439](https://mozilla-hub.atlassian.net/browse/VPN-3439))
=> Fallback to source locale when dumping strings from an xliff

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNLogger.kt, android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt, src/platforms/android/androidcontroller.cpp, src/platforms/android/androidvpnactivity.cpp, src/platforms/android/androidvpnactivity.h
Disclaimer: I don't quite understand the reason of this crash. 
Currently, when we want to have the logs, we ask the daemon. This reads the logfile and sends it over the binder. 
The controller passes that string into a QString and gets it to the client. 
The Client will feed that QString in a QTextStream into a QIODevice. Here's where the weirdness begins. 
- If that Device is a file or StdOut (like when we want to send the logfile) -> All good. 
- If that underlying Buffer is a QByteArray or QString, we will crash, if we add any more text after that backend-logfile has been appended.   
Anyway. This was a great reason to stop doing all of that. As the logfile just lives in the temp dir, we can also just have the client read that instead of having the deamon read and then IPC pass it. …
=> Android crash fix on feedback

android/AndroidManifest.xml
Given we have one unfixed high (VPN-3421), it's not ready. Let's disable this in the 2.12 branch
=> 2.12: disable tile service

src/ui/navigator/navigationBar/VPNBottomNavigationBarButton.qml
- Stop giving focus to selected navbar buttons to prevent unwanted tooltips
[VPN-2767: Upon restoring from the System Tray, the navigation bar displays the tooltip without needing to hover over the icon](https://mozilla-hub.atlassian.net/browse/VPN-2767)
=> Prevent navbar button tooltip on window focus

nebula/ui/components/VPNServerList.qml
- Fixes a regression where extra padding was added to the bottom of the server list
[VPN-3429: Excess padding at the bottom of the server list view](https://mozilla-hub.atlassian.net/browse/VPN-3429)
=> Remove excess padding at bottom of server list

CMakeLists.txt, android/build.gradle, src/cmake/android.cmake, src/cmake/android_openssl.cmake, src/models/device.cpp, vpnglean/CMakeLists.txt
Our 3rdpary/openSSL submodule did fall behind in versions. 
Google actually [provides builds of OpenSSL themselves](https://mvnrepository.com/artifact/com.android.ndk.thirdparty/openssl), however only in an aar-prefab. 
This PR adds some cmake logic to pull those, extract the right libs and feed them into our build system. 
https://mozilla-hub.atlassian.net/browse/VPN-3069
=> Android: Grab OpenSSL builds from Google

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
We restore the last connection Timestamp, so that the silent-server switch of connection health does not reset the time. We did not check if that is 0, so let's only restore it if that is the case.
=> Android: Fix Connection Time

vpnglean/CMakeLists.txt
`error()` is not a CMake command.
=> vpnglean: Use message() to report an error from CMake

src/apps/vpn/controller.cpp, src/apps/vpn/controller.h, src/apps/vpn/controllerimpl.h, src/apps/vpn/localsocketcontroller.cpp, src/apps/vpn/localsocketcontroller.h, src/apps/vpn/platforms/android/androidcontroller.cpp, src/apps/vpn/platforms/android/androidcontroller.h, src/apps/vpn/platforms/dummy/dummycontroller.cpp, src/apps/vpn/platforms/dummy/dummycontroller.h, src/apps/vpn/platforms/ios/ioscontroller.h, src/apps/vpn/platforms/ios/ioscontroller.mm, src/apps/vpn/platforms/linux/linuxcontroller.cpp, src/apps/vpn/platforms/linux/linuxcontroller.h, tests/qml/moccontroller.cpp, tests/unit/moccontroller.cpp
Currently we send ``ReasonNone`` to the iOS controller for a silent-server switch. This means it will try to activate the tunnel instead of switching. Therefore we never get a ```connected``` event back, timeout in the activation, try all servers until none is left and show the "no servers" error. 
[    i.e Jira or Github issue URL](https://mozilla-hub.atlassian.net/jira/software/c/projects/VPN/boards/344?modal=detail&selectedIssue=VPN-3352&assignee=6047c4eeaddbcd006ba87be8)
=> Fix silent-server switch on iOS

nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml
This adjusts the visibility rule of the password requirements tooltip so that it stays hidden until at least one character has been entered.
VPN-3171
=> VPN-3171: Don't show password requirements immediately on input.activeFocus

nebula/ui/components/VPNBoldInterLabel.qml
This fixes alignment of guide card text in RTL locales.
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Fix text alignment in guide cards for RTL locales

nebula/ui/components/VPNSubtitle.qml, nebula/ui/components/forms/VPNPasswordInput.qml, nebula/ui/components/forms/VPNSearchBar.qml, nebula/ui/components/forms/VPNTextField.qml
- Fixes password input show/hide button keyboard accessibility on desktop
- Adds accessibility rules to VPNSubtitle.qml for screen readers
This PR fixes some of the issues noted by QA in **VPN-3387**
`“Enter your email address to continue using Mozilla VPN” text between the Mozilla VPN logo and “Enter email” field is not narrated;`
`“Finish creating your Firefox account to continue to Mozilla VPN” text between the “Change email” button and 
“Create password” field is not narrated;`
`“Open your email and enter the verification code that was sent” text between the “Enter verification code” and text field is not narrated;`
=> Accessibility improvements to authentication flow

src/apps/vpn/appconstants.h, src/apps/vpn/ui/screens/getHelp/ViewGetHelp.qml, src/apps/vpn/ui/screens/getHelp/contactUs/ViewContactUsForm.qml, src/apps/vpn/urlopener.cpp, src/apps/vpn/urlopener.h, tests/functional/testOnboarding.js, tests/functional/testSettings.js
This routes users directly to the Mozilla VPN SUMO page, instead of redirecting through Guardian first. After discussing with Santiago and Baku the thinking is this: a Guardian outage would likely result in folks clicking the 'Help center' link, which the downed Guardian would not be able to redirect to SUMO. 
VPN-3494
=> Fix VPN-3494 - Use correct SUMO url

.github/workflows/wasm.yaml
Fixing rate limit issue in wasm tests
[VPN-3504](https://mozilla-hub.atlassian.net/browse/VPN-3504)
=> adding token to raise api limits

nebula/ui/components/VPNTabNavigation.qml
This fixes the glitch in `VPNTabNavigation` when the `currentItem` changes, which was caused by explicitly assigning a `width` to tab buttons. There is a trade-off: It also removes the sliding "active tab" indicator. This is because the sliding indicator relied on the `x` value of the tab buttons, which becomes a rubbish value when the tab button `width` is not explicitly set. If we feel strongly about the sliding indicator I am happy to open a ticket to re-implement.
https://user-images.githubusercontent.com/22355127/203120760-be36d138-5d4c-4f6b-ba29-719ef5c0d973.mov
VPN-2850
=> Fix tab navigation glitch / VPN-2850

.github/workflows/wasm.yaml
In https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5264/files
geckodriver was actually removed from the running task. It's green. 
We certainly dont need it to build the client.
=> CI: remove geckodriver.

taskcluster/ci/build/linux.yml, taskcluster/ci/docker-image/kind.yml, taskcluster/docker/linux-dpkg-build/Dockerfile, taskcluster/scripts/build/linux.sh
This PR adds Taskcluster jobs to produce packages for our supported Ubuntu releases (at present: `bionic`, `focal`, `jammy` and `kinetic`). This starts with an initial job to produce a source bundle, which is then shared by a separate build worker for each target release. The magic here is in producing a generic Docker image that matches an official Ubuntu build worker as closely as possible, but permits us to swap out the base container image.
Because we have split the build tasks up, the `build-linux/opt` task no longer really exists, and we will need to update Github's branch protection rules in order to merge this.
I haven't gone so far as to force offline builds like the official build workers do, so it is possible that a bug the golang and rust module vendoring could creep into the …
=> Add taskcluster jobs to build Ubuntu packages.

src/apps/vpn/ui/screens/settings/dnsSettings/DNSSettingsTabContent.qml
- Prevent DNS radio buttons from being selected by clicking on their labels when the radio button is disabled (VPN is turned on)
- Restore custom DNS text field placeholder text
[VPN-3546: DNS settings can be modified while the VPN is ON ](https://mozilla-hub.atlassian.net/browse/VPN-3546)
=> Disable radio button labels in DNS settings

src/apps/vpn/ui/screens/settings/dnsSettings/DNSSettingsTabContent.qml
Fixes console warning `qrc:/ui/screens/settings/dnsSettings/ViewAdvancedDNSSettings.qml:60:13: QML DNSSettingsTabContent: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (ViewAdvancedDNSSettings.qml:60)`
=> Fix console warning in ViewAdvancedDNSSettings.qml

nebula/ui/components/inAppAuth/VPNInAppAuthenticationLegalDisclaimer.qml
- Makes the legal disclaimer text on the create password/enter password authentication views accessible to a screen reader. It also prevents the HTML tags from being read by the screen reader
- NOTE: The "Terms of Service" and "Privacy Notice" links within the legal disclaimer are still unaccessible using keyboard navigation - this may need a workaround solution as I am not sure if in-line links in QML are keyboard navigable
n/a
=> Make legal disclaimer accessible to screen readers

addons/message_staging_update_v2.14/getHelp.js, addons/message_staging_update_v2.14/manifest.json, addons/message_staging_update_v2.14/update.js
- Adds a message only to be promoted to staging in order for QA to verify [VPN-3435](https://mozilla-hub.atlassian.net/browse/VPN-3435)
[VPN-3435: No clearance between the “Get help” button and navigation bar after returning to the Update message from Update recommended screen](https://mozilla-hub.atlassian.net/browse/VPN-3435)
=> Add staging message for QA testing

src/apps/vpn/ui/screens/tipsAndTricks/ViewTipsAndTricks.qml
Fixes `QML VPNViewBase: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.` in ViewTripsAndTricks.qml
=> Fix qml warning in ViewTipsAndTricks.qml

src/apps/vpn/ui/screens/getHelp/giveFeedback/GiveFeedbackRadioDelegate.qml
- Prevents feedback form from appearing like two feedback options were selected at the same time
- Prevents unchecking feedback radio buttons by tapping on a selected feedback radio button (this was a visual bug that allowed the user to progress to the next step when it looked like no feedback radio buttons were selected)
[VPN-912: [mobile] More than one option can be selected on the “Give Feedback” screen](https://mozilla-hub.atlassian.net/browse/VPN-912)
=> Feedback radio delegate fixes

src/apps/vpn/logoutobserver.cpp, src/apps/vpn/logoutobserver.h
In PR https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5278
I added a LogoutObserver to the VPNActivity, so that post-logout cleanup will be triggered. 
This means the LogoutObserver will be created even if there is no current logout happening. 
This means this Q_ASSERT currently crashes android debug builds
Nobug.
=> Logout-Observer: Remove invalid assert

.gitignore
We should not be able to commit these since they are automatically generated by Cmake
https://mozilla-hub.atlassian.net/browse/VPN-3604
=> Add auto generated l18nstrings to gitignore

taskcluster/ci/build/windows.yml, taskcluster/mozillavpn_taskgraph/transforms/build.py
In order for the sentry-stuff to actually work the build needs access to the tokens. Let's enable it for level-3 tasks :)
=> TC: Windows add Scopes for level-3 Builds

wasm/main.css
The list added in #5404 looks a bit awkward without margin. Since there are other lists, focusing only on the section.
=> Fix list margin for Welcome paragraph on WASM page

nebula/ui/components/VPNConnectionInfoContent.qml, translations/strings.yaml
Moves the dedicated callout info into the bullet list. Instead of always showing this string for multi-hop connection we decided to only show it for speed test results that we mark as “slow”.
- Jira [VPN-3218](https://mozilla-hub.atlassian.net/browse/VPN-3218): Improvements to the Speed test UI
- Figma: https://www.figma.com/file/3V7aahpQ096Qsp2L3SCT6h/Connection-Screen-Speedtest?node-id=1103%3A4728
=> Move troubleshooting info for multi-hop into list

src/apps/vpn/command.cpp, src/apps/vpn/glean/glean.cpp, src/apps/vpn/glean/glean.h, src/shared/loghandler.cpp, src/shared/loghandler.h, src/shared/loglevel.h, vpnglean/src/lib.rs, vpnglean/src/logger.rs
=> VPN-3019 - Integrate vpnglean logs with VPN logs

addons/tutorial_01_get_started/manifest.json, nebula/ui/components/VPNServerCountry.qml
This is a fix in case:
- 1 city from the first country is unavailable
- all the cities from the first country are unavailable
It's not a fix in case, the first and the second countries do not have cities available. If we want to support this scenario, we need to implement the scrolling. And this becomes out-of-scope for 2.13/2.14.
=> Fix the get-started tutorial when a server is not available - VPN-3552

tests/functional/testServers.js
The rollback of modules 8,9,10 was not correct. The real fix was related to the qmlPath porting of our tests.
Somehow there was a extra line which was "fine" for faster clients (dummyvpn), but not for wasm. The extra line was opening the server-list, closing the main view. On wasm, the main view is "released" too soon. That line needs to be removed.
=> Fix the wasm client functional test: testServers.js

src/apps/vpn/inspector/inspectorhandler.cpp
I managed to reproduce this issue with a small app that has a flickerable object + a loader + a stackView + a button.
After a few seconds, the issue can be reproduced. I did the following extra debugging steps:
- I logged out all the QT events (via `installEventFilter`) and a working sequence of events and a broken one are the same.
- I also checked all the properties of _all_ the chain of elements starting from the button, and they match in a working and a broken session.
Because of this, I suspect it's a race condition between the QT rendering thread and the main one. This issue goes away adding an extra timer before the click.
Why now? Because QmlPath makes our tests faster! We have reduced the number of operations using qmlPath and the property checks. So, for instance, instead of:
1. …
=> Add a delay to avoid race-condition Qt/QML when simulating clicks

taskcluster/ci/build/windows.yml
On windows it still seems the CI is failing to fetch secrets. 
Debugging level 3 tasks is not really a thing so here's my theory. 
Get-Secrets is trying to get the TC-Instance via the env:
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/taskcluster/scripts/get-secret.py#L48
But we did not set that - see latest main push params:
https://firefox-ci-tc.services.mozilla.com/tasks/cYij-t8aSbCx8DBjeVPZLA/definition
So let's enable the proxy-mode to have that env set.
=> Enable TC-Proxy on windows builds

nebula/ui/components/VPNConnectionInfoContent.qml
Remove the country name and only show the name of the city for each server in multihop, also center the arrow in the row. This will uniform the UI experience following issue VPN-3514 ([PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5302)).
https://mozilla-hub.atlassian.net/browse/VPN-3639
=> Only show city name for multihop server names

nebula/ui/components/inAppAuth/VPNInAppAuthenticationInputs.qml
This forces focus back to auth inputs after hitting the paste button. In the password creation view, the shift of focus back to the password input opens the password requirements tooltip fixing VPN-3652. 
VPN-3652
=> VPN-3652: Refocus auth inputs after clicking the paste button

src/apps/vpn/ui/navigator/navigationBar/VPNBottomNavigationBar.qml
Fixes VPN-3548 (part of it, see thread for details) by disabling nav buttons when they are hidden. 
VPN-3548
=> Fix VPN-3548: Tooltips appearing when nav bar buttons are disabled

nebula/ui/components/VPNConnectionInfoContent.qml
**Description:**
I originally cherry-picked this commit from `main` to bring the changes over to 2.13. For some reason, the 2.13 version of VPN did not like these changes at all and the CI screen looks a little funky even though it looks just fine in Main. 
So I am reverting this change in 2.13 and going to address the VPN-3639 bug in 2.13 specifically as a separate bug given that the fix seems to be entirely different from 2.14/main. 
Reverts mozilla-mobile/mozilla-vpn-client#5486
=> Revert "Only show city name for multihop server names (#5442)"

src/apps/vpn/controller.cpp, src/apps/vpn/controller.h, src/shared/settingsholder.cpp, src/shared/settingsholder.h
- Rollback the state of the VPN controller to what it was prior to starting a "needs rollback" tutorial
*Note: This relies on: #5450
[VPN-3125: Implement the Multi-hop Tutorial](https://mozilla-hub.atlassian.net/browse/VPN-3125)
[VPN-3124: Implement the App Permissions Tutorial](https://mozilla-hub.atlassian.net/browse/VPN-3124)
[VPN-3593: VPN previous state not restored after interrupting the “How to exclude apps from VPN protection” tutorial](https://mozilla-hub.atlassian.net/browse/VPN-3593)
[VPN-3677: The VPN state should be restored after a tutorial](https://mozilla-hub.atlassian.net/browse/VPN-3677)
[VPN-3596: [iOS] VPN is turned OFF after completing the multi-hop tutorial](https://mozilla-hub.atlassian.net/browse/VPN-3596)
=> Rollback vpn controller for rollback tutorials

nebula/ui/components/VPNConnectionInfoContent.qml
This [PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5442) from last week unintentionally made changes to the single hop CI screen where we would only list the server city name twice instead of listing country AND city. This PR fixes that regression and maintains the fix for multihop where we only want to show the entry and exit city names (and not the countries).
https://mozilla-hub.atlassian.net/browse/VPN-3639
=> Do not change server name info in singlehop CI

nebula/ui/components/VPNConnectionInfoContent.qml
If in multihop, then only show city names in the CI page. This change does not affect the UI in single hop mode.
https://mozilla-hub.atlassian.net/browse/VPN-3639
=> If in multihop, then only show city names in the CI page

src/apps/vpn/appconstants.h, src/apps/vpn/connectionbenchmark/benchmarktasktransfer.cpp
After adjustments to the _VPN Network Benchmark_ ([PR #10](https://github.com/mozilla-services/vpn-network-benchmark/pull/10)) where we limit the data that can be uploaded per request to `10MB` I noticed that the `BenchmarkUpload` unintentionally generates `~80MB`. This results in a `QNetworkReply::RemoteHostClosedError` and is the expected behaviour of the benchmark microservice.
With the _VPN Network Benchmark_ now being deployed to prod and with the `UploadDataGenerator` as of this change actually generating `10MB` the speed test within the VPN should now run fine for stage and prod.
- Jira [VPN-3561](https://mozilla-hub.atlassian.net/browse/VPN-3561): Unexpected error at CI screen access
[VPN-3561]: https://mozilla-hub.atlassian.net/browse/VPN-3561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> Actually generate 10MB of data for the upload benchmark (VPN-3561)

src/shared/settingsholder.cpp
Note this is the simple fix being applied for 2.13. A more robust fix is implemented in PR #5526 for 2.14 and later.
=> VPN-3541 Obfuscate subscription data (2.13 fix)

src/apps/vpn/websocket/websockethandler.cpp, src/apps/vpn/websocket/websockethandler.h
tl;dr; Turns out websocket is not closed when mobile applications go to the background. They go into this gray area "suspended" state and connection may or may not be resumed once the app is back on the foreground. So now we close and reopen manually on mobile when the app is backgrounded / foregrounded.
See more on: https://developer.apple.com/library/archive/technotes/tn2277/_index.html
=> VPN-3705 - Close websocket when mobile app goes to the background

addons/tutorial_03_multi_hop/manifest.json, nebula/ui/components/VPNTutorialPopups.qml, translations/strings.yaml
- Change the completion text for the multi hop tutorial on the tutorial completion modal
- Change secondary button text on the tutorial completion modal
[VPN-3614: Confusing text in the “Well done” Multi-hop tutorial modal](https://mozilla-hub.atlassian.net/browse/VPN-3614)
=> VPN-3614: Tutorial content changes

tests/unit/testaddon.cpp
If the unit-test runs slow, it can happen that the installation time is < 1 second. We need to reset the installation time before running the time-conditional addons
VPN-3904
=> Fix a race condition in the Addon unit test - VPN-3904

src/apps/vpn/appconstants.h, src/apps/vpn/connectionbenchmark/connectionbenchmark.cpp, src/apps/vpn/connectionbenchmark/connectionbenchmark.h, tests/functional/constants.js, tests/functional/servers/networkBenchmark.js, tests/functional/servers/server.js, tests/functional/setupVpn.js, tests/functional/setupWasm.js, tests/functional/testBenchmark.js, wasm/test.html
Why: functional tests should run offline. The main blocker is the benchmark test because it uses external resources such as archive.m.o and httpstats.us. With this PR, I remove these dependencies.
=> Remove external references to http resources for benchmark tests - VPN-3879

src/apps/vpn/ipaddresslookup.cpp
=> IPFinder causes a crash if the user logouts when the the VPN was active - VPN-3946

nebula/ui/components/VPNRecentConnections.qml, src/apps/vpn/commands/commandui.cpp, src/apps/vpn/models/recentconnections.cpp, src/apps/vpn/models/serverdata.cpp, src/apps/vpn/models/serverdata.h
VPN-3293
Note that this could be reproducible via a simple logout.  The bug is in the
retranslate request (ServerData::changed signal) when the language code changes
because of a setting reset.  The signal is received by the RecentConnection
model, which adds the "new" server location to its lists.
This PR renames VPNRecentConnections to VPNRecentConnectionsModel to avoid
conflicts with a nebula QML component.
=> Do not treat settings reset as a location change - VPN-3293

.github/l10n/check_l10n_issues.py, .github/workflows/linters.yaml
This removes the `lupdate` command from the Python script, and use the full `generate_ts.sh` script to extract string for both the main app and the add-ons. Then checks all these files for l10n errors.
=> l10n linter: regenerate ts files, include add-ons

nebula/ui/components/VPNConnectionInfoScreen.qml
Band-aid fix for VPN-3669. Call `VPNConnectionBenchmark.reset()` on state change to 'closing'. 
VPN-3669
=> Fix VPN-3669: Disappearing nav bar

tests/unit/testaddon.cpp
There is another similar issue to what you reviewed a few days ago. If the unit-test runs too slow, the addon+conditional watcher set to 1 sec, fails.
=> Set the installation time in all the timing-related unit-test - VPN-3904

src/apps/vpn/commands/commandui.cpp, src/apps/vpn/main.cpp, src/apps/vpn/mozillavpn.cpp, src/apps/vpn/telemetry.cpp, src/apps/vpn/telemetry.h, vpnglean/CMakeLists.txt, vpnglean/glean_parser_ext/run_glean_parser.py, vpnglean/metrics.yaml
Still to do:
- Neither `main()` nor the `MozillaVPN` singleton are available on tests. Feels unncessary to test the actual `Telemetry` functions so... No tests.
This is build on top of: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5523. The commits that matter for this PR are 047553d781399d4684c3503c12bcdc91b9b3b5b7 and a0094253b6ef675b5b283df8dd0a4231e5a4c06c.
This is based on: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4493
=> VPN-2916 - Implement "time to main screen" metric

taskcluster/scripts/build/source.sh
In PR #5607 we added some logic to help taskcluster reconstruct the gitref when we are on a branch or PR, but this didnt quite work as expected on push to main, where we wind up being given a full ref to the destination branch (eg: `refs/heads/main` instead of just `main`). Check for this occurrence, and just use the value of `$MOZILLAVPN_HEAD_REF` in these cases.
Github PR #5607
Github #5516 ([VPN-3735](https://mozilla-hub.atlassian.net/browse/VPN-3735))
[VPN-3735]: https://mozilla-hub.atlassian.net/browse/VPN-3735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Sometimes MOZILLAVPN_HEAD_REF is a full ref, just use it

nebula/ui/components/VPNConnectionInfoContent.qml
Remove anchor for the arrow to prevent overlapping 
server location and arrow in case of longer location names
https://mozilla-hub.atlassian.net/browse/VPN-3945
=> Remove center anchor for the multihop arrow

glean/metrics.yaml, nebula/ui/components/VPNControllerView.qml, nebula/ui/components/VPNDropShadowWithStates.qml, nebula/ui/components/VPNMainImage.qml, nebula/ui/components/VPNToggle.qml, src/apps/vpn/cmake/sources.cmake, src/apps/vpn/commands/commandstatus.cpp, src/apps/vpn/controller.cpp, src/apps/vpn/controller.h, src/apps/vpn/mozillavpn.cpp, src/apps/vpn/networkwatcher.cpp, src/apps/vpn/notificationhandler.cpp, src/apps/vpn/qmake/sources.pri, src/apps/vpn/settingswatcher.cpp, src/apps/vpn/settingswatcher.h, src/apps/vpn/statusicon.cpp, src/apps/vpn/systemtraynotificationhandler.cpp, src/apps/vpn/tasks/controlleraction/taskcontrolleraction.cpp, src/apps/vpn/tasks/controlleraction/taskcontrolleraction.h, src/apps/vpn/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml, src/apps/vpn/ui/screens/settings/ViewNetworkSettings.qml, src/apps/vpn/ui/screens/settings/ViewNotifications.qml, src/apps/vpn/ui/screens/settings/appPermissions/AppPermissionsList.qml, src/apps/vpn/ui/screens/settings/appPermissions/ViewAppPermissions.qml, src/apps/vpn/ui/screens/settings/dnsSettings/DNSSettingsTabContent.qml, tests/functional/helper.js, tests/qml/moccontroller.cpp, tests/unit/moccontroller.cpp
Tech Doc:
- We want to use silent-switch functionality to apply setting changes when the VPN is on. Silent-switch is something we already have implemented for unstable servers.
- We need a `SettingsWatcher` obj that observers settings change. When the VPN is on, and there is a setting change, this component triggers a server-switch appending a TaskControllerAction task to the queue.
- We also need to remove a few glean events and the VPN-is-off warning alerts
- The best way to make the silent-switch code more readable, I introduce a StateSilentSwitching. In this way we can reduce the `stateToReason` calls.
=> silent switch for settings changes - VPN-3601

vpnglean/glean_parser_ext/templates/rust.jinja2
With[ the breaking change on glean_parser](https://github.com/mozilla/glean_parser/releases/tag/v7.0.0) not to support untyped event extras, the `has_extra_types` property was removed.
=> VPN-4001 - Update glean_parser_ext to be compatible with glean_parser 7.0.0

.github/workflows/linters.yaml
With #5701 - around the corner, this task is not needed - not worth continue patching qmllint from the outside c:
=> Chore: Remove qmllint for now

nebula/ui/components/forms/VPNInputStates.qml, src/apps/vpn/appconstants.h, src/apps/vpn/mozillavpn.cpp, src/apps/vpn/mozillavpn.h, src/apps/vpn/ui/screens/settings/ViewDNSSettings.qml, tests/auth/mocmozillavpn.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp, translations/strings.yaml
- Adds placeholder text to DNS input (no ticket)
- Removes VPN.placeholderUserDNS (no ticket)
- Adds `Qt.ImhFormattedNumbersOnly` to `inputMethodHints` to fix VPN-3280. Note: We use `Qt.ImhFormattedNumbersOnly` instead of `Qt.ImhDigitsOnly` so that decimal points remain available. See screenshot. 
VPN-3280
=> Fix VPN-3280: Update DNS input placeholder text and inputMethodHints

src/apps/vpn/appfeaturelistcallback.h, src/apps/vpn/platforms/linux/daemon/apptracker.cpp, src/apps/vpn/platforms/linux/daemon/apptracker.h, src/apps/vpn/platforms/linux/linuxdependencies.cpp, src/apps/vpn/platforms/linux/linuxdependencies.h
Support KDE as a split-tunneling desktop environment, by requesting the property of the systemd unit that is the full path to the desktop file. Only works for kio > 5.75 (in KDE frameworks) which is what is tested for the feature to be enabled.
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1869
=> Kde dbus app tracking

README.md
Update min Go version number in readme to 1.18 for most platforms (i.e. all but Linux)
=> Update go minimum version for most platforms to 1.18

LICENSE.md
From @ValentinaPC - she is filing a jira issue. But in the meantime, here is the fix.
=> Fix the license to be correctly shown on the license view - VPN-4016

taskcluster/scripts/build/windows.ps1
We should remove this `--remote` everywhere else it is used.
=> VPN-4018 - Do not get latest submodule version on Windows CI

src/apps/vpn/mozillavpn.cpp
The issue described on VPN-3940 would happen only when the user logged out and the server went into silent server switch mode. With this fix that doesn't happen anymore.
It is unclear to me yet how exactly that leads the user's internet connection to break _after a while_ because in fact the controller does turn off after silen server switch is unsuccesfull. I will attempt to investigate that on Monday, but this fixes it so there you go.
Tests are not possible because the Mozilla VPN singleton is not testable.
=> VPN-3940 - Deactivate VPN on logout

vpnglean/CMakeLists.txt
When we fail the glean_parser version check. The resulting error message may suggest that the user run a script, when in practice they may be better served by updating their glean_parser version. Let's add a bit more verbosity to that message.
Github issue #5785 ([VPN-4019](https://mozilla-hub.atlassian.net/browse/VPN-4019))
[VPN-4019]: https://mozilla-hub.atlassian.net/browse/VPN-4019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-4019: Better messaging when failing the glean_parser version check

tests/functional/testIpInfo.js
Disable test that relies on new qmlpath work on releases/2.13. It is causing red ci on 2.13 as "queries" is not available in 2.13.
https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/4027715768/jobs/6923941961
=> Chore: Disable test that relies on new qmlpath work on releases/2.13

.gitignore, scripts/utils/lint_qml.sh
Just forking off a commit from my PR #5724 when I tried to fix some QML linting errors.
In my opinion, to make this tool easier to run locally, the QML linting script should:
- Terminate silently if there are no QML diffs
- Allow the caller to specify the commit to diff against (eg: `./scripts/utils/lint_qml.sh -c <commit>`)
- Make an attempt to guess the `qmllint` path if `QT_HOST_PATH` is unset
- Only attempt to lint files ending with `.qml`
None!
=> Chore: lint_qml.sh usability improvements

CMakeLists.txt
Currently only python3 is checked. In a conda env it seems we have python3 as the default `python` command.
=> VPN-Glean: Make Python a valid candidate for PYTHON_EXECUTABLE

src/apps/vpn/cmake/macos.cmake, src/apps/vpn/cmake/sources.cmake, src/apps/vpn/cmake/windows.cmake, src/apps/vpn/command.cpp, src/apps/vpn/commands/commandwgconf.cpp, src/apps/vpn/commands/commandwgconf.h, src/apps/vpn/controller.h, src/apps/vpn/platforms/windows/daemon/wireguardutilswindows.cpp, src/apps/vpn/wgquickprocess.cpp, src/apps/vpn/wgquickprocess.h
This adds a command line tool to render the current device configuration in the form of a Wireguard configuration file that can be used by a 3rd party Wireguard client.
Usage is as follows:
```
[user@example ~]$ ./src/mozillavpn wgconf
[Interface]
PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
Address = 10.112.171.249/32, fc00:bbbb:bbbb:bb01::31:abf8/128
DNS = 10.64.0.1, fc00:bbbb:bbbb:bb01::1
[Peer]
PublicKey = Hzf1JH0UERBRNxBSpTvGPZAREa93LoHtPKsJMwdcrV0=
Endpoint = 89.45.224.41:3406
AllowedIPs = 10.64.0.1/32, fc00:bbbb:bbbb:bb01::1/128, 10.124.0.0/20, 240.0.0.0/4, 208.0.0.0/4, 200.0.0.0/5, 196.0.0.0/6, 194.0.0.0/7, 193.0.0.0/8, 192.0.0.0/9, 192.192.0.0/10, 192.128.0.0/11, 192.176.0.0/12, 192.160.0.0/13, 192.172.0.0/14, 192.170.0.0/15, 192.169.0.0/16, 128.0.0.0/3, 176.0.0.0/4, …
```
=> Add wgconf command to generate a Wireguard config file.

src/apps/vpn/cmake/macos.cmake, src/apps/vpn/platforms/macos/macosstatusicon.h, src/apps/vpn/platforms/macos/macosstatusicon.mm, src/apps/vpn/platforms/macos/macossystemtraynotificationhandler.cpp
- Directly utilize `UserNotifications` on macOS to avoid duplicate menu bar icons and accept click events for each notification
- Clicking on a notification on macOS will now always show the UI and give the window focus, regardless of whether it is: 
- Hidden behind other windows
- System hidden (Right click dock icon > hide or CMD+H)
- In-App hidden (Implemented by us to hide the dock icon when the app is running)
- Minimized
- [VPN-3970: Implement persistent, clickable notifications on macos ](https://mozilla-hub.atlassian.net/browse/VPN-3970)
=> VPN-3970: Use native API for mac os notifications

nebula/ui/components/VPNButtonBase.qml, nebula/ui/components/VPNFlickable.qml, nebula/ui/components/VPNServerCountry.qml, nebula/ui/components/VPNSettingsToggle.qml, nebula/ui/components/VPNSwipeDelegate.qml, nebula/ui/components/VPNTextBlock.qml, nebula/ui/components/VPNTutorialPopups.qml, nebula/ui/components/forms/VPNComboBox.qml, nebula/ui/components/forms/VPNSearchBar.qml, nebula/ui/components/forms/VPNTextArea.qml, nebula/ui/components/forms/VPNTextField.qml, nebula/ui/themes/themes.js, src/apps/vpn/ui/main.qml, src/apps/vpn/ui/navigator/navigationBar/VPNBottomNavigationBar.qml, src/apps/vpn/ui/screens/getHelp/ViewGetHelp.qml, src/apps/vpn/ui/screens/getHelp/contactUs/ViewContactUsForm.qml, src/apps/vpn/ui/screens/messaging/ViewMessage.qml, src/apps/vpn/ui/screens/messaging/ViewMessagesInbox.qml, src/apps/vpn/ui/screens/settings/ViewPreferences.qml, src/apps/vpn/ui/screens/settings/ViewSettingsMenu.qml
- Modify the `ensureVisible` function in all flickables such that the navbar is considered and UI components are visible and not blocked when gaining focus via keyboard navigation
- Auto-scroll the screen to focused UI components during a tutorial so that all steps of a tutorial are easily accessible
[VPN-3617: [Google Pixel 4][Android] Select exit location option is overlapped by nav bar inside the Multi-hop tutorial](https://mozilla-hub.atlassian.net/browse/VPN-3617)
[VPN-3662: [a11y] Some elements are obscured by the navigation bar when scrolled into view via `ensureVisible()`](https://mozilla-hub.atlassian.net/browse/VPN-3662)
=>  VPN-3617 & VPN-3662: Ensure components are visible on focus #5673 

vpnglean/glean_parser_ext/rust.py, vpnglean/glean_parser_ext/templates/rust.jinja2
This will address the warnings added by the quick fix on [#5757](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5757)
=> VPN-4003 - Skip generating extra keys struct for events with no extra keys

android/vpnClient/build.gradle
See https://mozilla-hub.atlassian.net/browse/VPN-4022 for a bunch of description on the investigation, but...
**tl;dr;** TaskProduct was never completing due to this serialization error, blocking us from moving forward to main state.
=> VPN-4022 - Apply serializer plugin on Android

.gitmodules
We've seen failures of wg-go to build on OSX.
This was caused due to us updating to golang 1.18, this was however not noticed as the runner never "cleaned" properly after a run, and since we build in the `/3rdparty/wireguard-go` folder not the cmake_bin_dir, i never noticed too. 
Now we could rollback go... or upgrade :)
=> Update wg-go on osx

CMakeLists.txt
Correct the title to say "Mozilla VPN" instead
https://mozilla-hub.atlassian.net/browse/VPN-2736
=> VPN-2736 Fix Windows notification title

.github/dependabot.yml
This should give dependabot the ability to see our deps. 
I'm not quite sure we want that to run weekly, but for now it'd be nice just to check out the workflow. 
See: https://github.com/mozilla-mobile/mozilla-vpn-client/network/updates
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> VPN-2952: Initial dependabot config

.github/workflows/functional_tests.yaml, .github/workflows/wasm.yaml, addons/message_subscription_expiring/contactSupportLink.js, addons/message_subscription_expiring/isExpiring.js, addons/message_subscription_expiring/manageAccountLink.js, addons/message_subscription_expiring/manifest.json, package.json, scripts/addon/generate_all_tests.py, src/apps/vpn/inspector/inspectorhandler.cpp, tests/functional/helper.js, tests/functional/servers/addon.js, tests/functional/servers/guardian_endpoints.js, tests/functional/setupVpn.js, tests/functional/testAddons.js
Had to reopen it for CI to be able to run fully.
Previous PR: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5273
=> VPN-2452 - Implement subscription expiring message

nebula/ui/components/VPNServerLatencyIndicator.qml, src/apps/vpn/models/servercity.cpp, src/apps/vpn/models/servercity.h, src/apps/vpn/models/servercountrymodel.h
Now that we only really have two "scores" that a server can show, the algorithm unfairly punishes some locations. Mostly this causes some really fast locations with low redundancy appear as "bad" choices. So let's try to improve upon this as follows:
- Reduce the location redundancy requirement to 3 servers (down from 6).
- Increase the internal score range to 6 values:
- Unavailable (-1)
- NoData (0)
- Poor (1)
- Moderate (2)
- Good (3)
- Excellent (4) -- **new**
- Give an extra score point to locations in the same country as the user.
- Give an extra score point to locations with less than 30ms latency (hardcoded threshold).
JIRA epic [VPN-2492](https://mozilla-hub.atlassian.net/browse/VPN-2492)
[VPN-2492]: https://mozilla-hub.atlassian.net/browse/VPN-2492?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> VPN-2492: Tweak Location Scores

taskcluster/ci/build/macos.yml, taskcluster/scripts/build/macos_build.sh, taskcluster/test/params/pull-request-untrusted.yml
I really thought it'd be neat to have sentry enabled on pr's... however external pr's like dependabot can't access them, so let's just use dummy values on pr's instead of the real secrets, so that we sill compile with sentry enabled, but it's not usable.
=> Remove sentry-secret from pull-requests

taskcluster/scripts/build/android_build_release.sh
We can ask sentry to attach source-files to our symbols, allowing sentry to show where the error happens. Could be cool. Let's add that.
=> Chore: Upload Source Code with Sentry Symbols

.github/workflows/gh_pages.yaml
Pull requests opened from external contributers can't access this secret, therefore this workflow will always fail. 
Let's only attemt signing on main branch, as only this will be published anyway.
This theoretically should allow dependabot-pr to get that sweet green ✅
=> GH-CI: Fix addon task for untrusted contributers

nebula/ui/components/VPNServerCountry.qml
There is some concern that the connection scores shown in the multihop exit server selection may not be good enough to direct the user to a performant connection, since the latency data doesn't necessarily correlate to the user's location anymore. In the interest in only showing users information that we can be assured is correct, we have decided to remove the scores entirely from the multihop view.
JIRA issue [VPN-4128](https://mozilla-hub.atlassian.net/browse/VPN-4128)
[VPN-4128]: https://mozilla-hub.atlassian.net/browse/VPN-4128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-4128: Remove connection scores from the multihop view

taskcluster/ci/fetch/kind.yml
We updated taskgraph, therefore invalidated all caches. 
During that time rustup.exe got updated, so we need to adjust size/shasum aswell.
=> CI-Blocker: update rustup

nebula/ui/components/VPNServerList.qml, src/apps/vpn/commands/commandui.cpp, src/apps/vpn/controller.cpp, src/apps/vpn/models/server.cpp, src/apps/vpn/models/server.h, src/apps/vpn/models/servercity.cpp, src/apps/vpn/models/servercountrymodel.cpp, src/apps/vpn/models/servercountrymodel.h, src/apps/vpn/models/serverdata.cpp, src/apps/vpn/mozillavpn.cpp, src/apps/vpn/mozillavpn.h, src/apps/vpn/serverlatency.cpp, src/apps/vpn/serverlatency.h, tests/auth/CMakeLists.txt, tests/auth/mocmozillavpn.cpp, tests/qml/CMakeLists.txt, tests/qml/mocmozillavpn.cpp, tests/unit/CMakeLists.txt, tests/unit/mocmozillavpn.cpp
Expose the `ServerLatency` object to QML, and provide a `refresh()` method to trigger a new ping sweep of the available servers, plus some useful properties about the progress of that ping sweep.
And, as some extra cleanup, I have moved the latency and cooldown properties out of the `Server` model and into the `ServerLatency` object.
Github issue #3990 ([VPN-2531](https://mozilla-hub.atlassian.net/browse/VPN-2531))
[VPN-2531]: https://mozilla-hub.atlassian.net/browse/VPN-2531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-2531: Expose method to refresh server connection scores.

qtglean/CMakeLists.txt, qtglean/glean_parser_ext/rust.py, qtglean/include/glean/metrictypes.h, qtglean/include/glean/string.h, qtglean/src/cpp/string.cpp, qtglean/src/ffi/mod.rs, qtglean/src/ffi/string.rs, qtglean/vpnglean.pri
Adding string metric type to new glean implementation
https://mozilla-hub.atlassian.net/browse/VPN-3685
=> VPN-3685 - add string metric to new glean

src/apps/vpn/tasks/products/taskproducts.cpp, tests/functional/servers/guardian_endpoints.js
This was accidentally removed by https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5503.
I wonder if we could have tests that would have caught this. I had two ideas 1. Running a local instance of Guardian alongside unit / functional tests instead of mocking everything. 2. Creating a suite of integration tests that run on merge or on the release branch that do not mock Guardian at all. WDYT?
=> VPN-4139 - Add back auth header to products requests

.gitmodules
Uniform handling of gitsubmodules when it comes to "ignore"
https://mozilla-hub.atlassian.net/browse/VPN-3848
=> VPN-3848: Remove ignore=all from .gitmodules

taskcluster/scripts/toolchain/compile_openssl.ps1
Since the switch to azure, link.exe from GNU coreutils comes before VisualStudio's in $PATH.
=> Override LD in the windows openssl toolchain script

qtglean/CMakeLists.txt, qtglean/glean_parser_ext/rust.py, qtglean/include/glean/datetime.h, qtglean/include/glean/metrictypes.h, qtglean/src/cpp/datetime.cpp, qtglean/src/ffi/datetime.rs, qtglean/src/ffi/mod.rs, qtglean/vpnglean.pri
Adding datetime metric to glean. From some local tests, it seems to work.
While most of the `datetime` object is covering in this PR, two pieces were left for the future (if they're ever needed). This work is captured [in a ticket](https://mozilla-hub.atlassian.net/browse/VPN-4173), as well as a comment within `datetime.h`.
https://mozilla-hub.atlassian.net/browse/VPN-3681
=> VPN-3681 - add datetime metric to glean

README.md, ci_scripts/ci_post_clone.sh, scripts/linux/ppa_script.sh, scripts/linux/script.sh, scripts/utils/import_languages.py, taskcluster/scripts/addons/build.sh, taskcluster/scripts/build/android_build_debug.sh, taskcluster/scripts/build/android_build_release.sh, taskcluster/scripts/build/ios_build_no_adjust.sh, taskcluster/scripts/build/macos_build.sh, taskcluster/scripts/build/wasm.sh, taskcluster/scripts/build/windows.ps1, taskcluster/scripts/push-addons/deploy.sh
Use `git submodule update --init` throughout codebase in order to:
* standardize usage
* not update submodules ahead of committed versions
The exception to this is i18n which we want to pull from remote. I've isolated this to just the `import_languages.py` script.
@oskirby In making these changes, I realized that `ppa_script.sh` did not include a call to `import_languages.py`. Can you review my change.
@strseb `taskcluster/scripts/push-addons/deploy.sh`. I haven't changed it but wanted to check in with you. Why is this file:
* doing a sync first - can we document why this is necessary
* doing --recursive (it's the only place in the repo we do)
* doing --force (again only place we do it)
=> VPN-3849 Align git submodule usage

src/apps/vpn/models/servercountrymodel.cpp
It has been recommended that the default location selection should take the user's current country into account when selecting a server. This is to hopefully try and mitigate unexpected changes to the locale when browsing the web. Fortunately this can be made as a simple tweak to `ServerCountryModel::pickBest()`
Note that this is only needed for the `releases/2.14.0` branch. This algorithm has since been replaced by the recommended server algorithm in 2.15 and beyond.
Github issue #3682
Github pull request #5398
JIRA [VPN-2333](https://mozilla-hub.atlassian.net/browse/VPN-2333) and [VPN-3111](https://mozilla-hub.atlassian.net/browse/VPN-3111)
[VPN-2333]: https://mozilla-hub.atlassian.net/browse/VPN-2333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
=> VPN-3111: Prefer locations within the user's country

src/apps/vpn/ui/screens/settings/ViewDNSSettings.qml, tests/functional/testSettings.js
=> Require valid custom DNS address before enabling the 'Use custom DNS' setting - VPN-4070

src/apps/vpn/connectionbenchmark/benchmarktasktransfer.cpp
The download benchmark task that runs as a part of the speed test/CI screen is using a hardcoded DNS server of 10.64.0.1 (otherwise known as the default mullvad DNS server), but when we setup the windows kill switch, we permit DNS traffic *only* for the user's selected DNS server. This leads to a situation where the speedtest fails if the user has selected any DNS server other than the default.
I don't think we really need to force the address of the nameserver anyways, we can just rely on the system's nameserver which ought to be a more representative test of the network anyways.
Github issue #5834 ([VPN-4048](https://mozilla-hub.atlassian.net/browse/VPN-4048))
[VPN-4048]: https://mozilla-hub.atlassian.net/browse/VPN-4048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> VPN-4048: Use the default nameserver in the benchmark test

nebula/ui/components/VPNCheckBox.qml, nebula/ui/components/VPNCheckBoxRow.qml, nebula/ui/components/VPNSettingsToggle.qml, nebula/ui/components/VPNToggleCard.qml, src/apps/vpn/ui/screens/getHelp/developerMenu/ViewFeatureList.qml
Attach accessible properties to checkboxes in VPNCheckBoxRow to better support native AT, particularly screen readers and "hover text" on macos.
To enable hover text on Mac: System Preferences > Accessibility > Zoom > Enable hover text
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/22355127/218916761-d2974241-7c73-43cd-9719-2f764a1873a3.mov
</td>
<td>
https://user-images.githubusercontent.com/22355127/218916818-e3b3e055-69f1-4e28-9c1f-92eb44d03d9b.mov
</td>
</tr>
</table>
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
https://user-images.githubusercontent.com/22355127/218924660-13faf0ed-2f11-461a-81ed-7cf0b2b6447e.mov
</td>
<td>
https://user-images.githubusercontent.com/22355127/218924684-736a07e4-97c2-4f02-a75e-6c4f93486b …
=> Fix VPN-4177

src/apps/vpn/models/servercountrymodel.cpp
Yet another attempt to get intra-country preferences working when selecting the default location. It seems that we can't use an exact comparison with the country codes since we are receiving a mix of uppercase and lowercase country codes from various guardian endpoints.
JIRA issue [VPN-3111](https://mozilla-hub.atlassian.net/browse/VPN-3111)
[VPN-3111]: https://mozilla-hub.atlassian.net/browse/VPN-3111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-3111: Fix case sensitivity when matching for intra-country locations.

addons/tutorial_04_split_tunneling2/manifest.json, addons/tutorial_04_split_tunneling3/manifest.json
Fix wrong capitalization for "App exclusions"
=> Fix 'App exclusions' capitalization in tunneling addon

src/apps/vpn/platforms/macos/macosstatusicon.mm
Ok, so this works for me on a signed build built using XCode. I am not sure QA will be able to see the notifications though, but we will need to merge and see.
I have changed the notification error logging method so we will be able to see in the logs in case they do get an error.
=> VPN-4124 - Attempt to use UNNotifcations to send notifs on Mac

docs/add-on.md, scripts/ci/jsonSchemas/addon.json, src/apps/vpn/addons/addon.cpp, src/apps/vpn/addons/addon.h, src/apps/vpn/addons/addonmessage.cpp, src/apps/vpn/addons/addonmessage.h, src/apps/vpn/addons/state/addonsessionstate.cpp, src/apps/vpn/addons/state/addonsessionstate.h, src/apps/vpn/addons/state/addonstate.h, src/apps/vpn/addons/state/addonstatebase.cpp, src/apps/vpn/addons/state/addonstatebase.h, src/apps/vpn/cmake/sources.cmake, src/apps/vpn/qmake/sources.pri, tests/unit/CMakeLists.txt, tests/unit/testaddon.cpp, tests/unit/testaddon.h, tests/unit/testaddonsessionstate.cpp, tests/unit/testaddonsessionstate.h, tests/unit/testaddonstatebase.cpp, tests/unit/testaddonstatebase.h
**This is a large PR, so I suggest going commit by commit during the review.**
One note about [DO NOT MERGE THIS ONE: Refactor split tunneling tutorial to use state](https://github.com/mozilla-mobile/mozilla-vpn-client/commit/afd6e095194e41a47762e146782ea20de5a5ecc2). Turns out we were too late to the party as this addon is actually disabled starting from 2.14... I added a commit with the refactor for illustration purposes, but we can't merge this change because this tutorial will not be enabled in versions that will have addon state support.
=> VPN-4131 - Implement addon session state

nebula/ui/components/VPNServerCountry.qml, nebula/ui/components/VPNServerLatencyIndicator.qml, src/apps/vpn/models/location.cpp, src/apps/vpn/models/location.h, src/apps/vpn/models/servercity.cpp, src/apps/vpn/models/servercity.h, src/apps/vpn/models/servercountrymodel.cpp, src/apps/vpn/models/servercountrymodel.h, src/apps/vpn/serverlatency.cpp, src/apps/vpn/serverlatency.h, tests/unit/CMakeLists.txt, tests/unit/testmodels.cpp, tests/unit/testmodels.h, tests/unit/testserverlatency.cpp, tests/unit/testserverlatency.h
Recently, it was decided that the connection scoring indicators for the multihop view weren't a reliable indicator of expected connection performance, and as such we removed them in PR #5984 until they could be re-implemented in a way that's cognizant of the entry/exit server pairing. However, I **really** just want to get this featured closed out and finished, so let's implement it.
This refactors the `ServerCity` object just a little bit, and adds a QML-invokable method to compute a connection score for a multihop pairing. This method follows mostly the same algorithm as for single-hop, but uses geographic distance between the cities as a proxy for expected latency. The common components of the scoring algorithm have been split out into a private method `ServerCity::baseCityScore()` …
=> VPN-4150: Add multihop connection scoring

tests/functional/helper.js
After debugging with @mozrokafor we honed in on the fact that the mocked call to the DesktopAuthenticationListener is failing.
The DesktopAuthenticationListener is listening on QHostAddress::LocalHost. Equivalent to QHostAddress("127.0.0.1"). https://doc.qt.io/qt-6.2/qhostaddress.html#SpecialAddress-enum
I don't have confirmation of this, but I'm wondering if the Github Actions CI images changed and stopped routing "localhost" (that the test was using) to "127.0.0.1" and that's why the test suddenly broke.
=> VPN-4214 - Fix AuthenticationInBrowser test.

taskcluster/scripts/toolchain/compile_openssl.ps1
We already did this for openssl, and although the others seem to work fine without it, we probably ought to make it explicit.
This also removes the original fix attempt of setting LD for openssl, which didn't work out.
=> Removal LD override in openssl build script, which is not doing anything.

src/apps/vpn/tasks/authenticate/desktopauthenticationlistener.cpp, tests/functional/helper.js
After discussing further with @bakulf we've agreed that the original fix in #6141 is correct and this PR now is just extra comments to help make this clear for our future selves.
====
In #6141 we hard-coded 127.0.0.1 to get the AuthenticationInBrowser.js test working again:
```patch
-        hostname: urlObj.hostname,
+        hostname: '127.0.0.1',
```
This PR reverses the above change and updates the `DesktopAuthenticationListener`.
In [d553d3f](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6144/commits/d553d3fabab9e7d43dafb084f31d4912612e8be4) I update `DesktopAuthenticaitonListener` to be listening on `QHostAddress::Any` which is, both IPv4 and IPv6 addresses https://doc.qt.io/qt-6.2/qhostaddress.html#SpecialAddress-enum. @oskirby posed the question "is this secure?" to me …
=> VPN-4214 Add comments to testAuthenticationInBrowser.js

src/apps/vpn/notificationhandler.cpp, tests/functional/testServerSearch.js, translations/strings.yaml
Add a new string in strings.yaml to include both exit and entry server locations in the multihop VPN connected notification. 
Format: “Connected to X, through Y”. 
https://mozilla-hub.atlassian.net/browse/VPN-4195
=> VPN-4195 Improve Multi-Hop OS notifications

taskcluster/ci/build/linux.yml, taskcluster/ci/build/source.yml
This attempts to update the indices for the Linux build artifacts to place them at `mozillavpn.v2.mozilla-vpn-client.branch.{xxxx}.latest.build` with the rest of the build artifacts, and to include the sources in there too.
Github issue #5659 ([VPN-3914](https://mozilla-hub.atlassian.net/browse/VPN-3914))
[VPN-3914]: https://mozilla-hub.atlassian.net/browse/VPN-3914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-3914: Update index routes for linux build artifacts

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/InAppPurchase.kt, nebula/ui/components/VPNSubscriptionOption.qml, src/apps/vpn/models/subscriptiondata.cpp, src/apps/vpn/models/subscriptiondata.h, src/apps/vpn/mozillavpn.cpp, src/apps/vpn/mozillavpn.h, src/apps/vpn/platforms/android/androidiaphandler.cpp, src/apps/vpn/platforms/ios/iosiaphandler.mm, src/apps/vpn/platforms/wasm/wasmiaphandler.cpp, src/apps/vpn/productshandler.cpp, src/apps/vpn/productshandler.h, src/apps/vpn/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml, src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededIAP.qml, tests/functional/testSubscription.js, translations/strings.yaml
Subscription management screen: 
- Add "+ tax" string to the subscription plan value in the subscription management view for US + Canada based users
Mobile IAP screen: 
- Update value props to match new content
- Add "+ tax" to US and Canadian pricing sublabels
- Update monthly plan content to match other pricing tiers
~*Note: [VPN-3284](https://mozilla-hub.atlassian.net/browse/VPN-3284) depends on https://github.com/mozilla-services/guardian-website/pull/1610 to call this API before showing the mobile IAP screen~ we now use currency code from the respective mobile app stores to determine whether or not a product is subject to tax (instead of location of account creation via Guardian ip lookup)
[VPN-3292: Implement change in the in-app Subscription Management page to mention US and Canada …
=> VPN-3292 & VPN-3284: Add "+ tax" to subscription plan pricing

.github/workflows/ppa-automation.yaml, taskcluster/ci/build/linux.yml, taskcluster/ci/docker-image/kind.yml, taskcluster/docker/linux-dpkg-build/Dockerfile, taskcluster/docker/linux-rpm-build/Dockerfile, taskcluster/scripts/setup-worker.sh
Ubuntu 23.04/Lunar Lobster is due to be released sometime in the next month or two, so it's important for us to make sure that we produce viable builds prior to its release.
Github issue #6155 ([VPN-4252](https://mozilla-hub.atlassian.net/browse/VPN-4252))
[VPN-4252]: https://mozilla-hub.atlassian.net/browse/VPN-4252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-4252: Add builds for Ubuntu/Lunar

taskcluster/ci/build/linux.yml, taskcluster/ci/build/source.yml, taskcluster/ci/build/windows.yml, taskcluster/scripts/build/windows.ps1
Lately we have been encountering some pain in the Windows builds due to taskcluster failing to fetch Rust dependencies. We might be able to fix it by switching to use the Linux source bundle, which has already vendored all the Rust code and doesn't need to perform any fetching.
Github issue #6261 ([VPN-4319](https://mozilla-hub.atlassian.net/browse/VPN-4319))
[VPN-4319]: https://mozilla-hub.atlassian.net/browse/VPN-4319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Experiment: Use prepared source bundle for Windows builds

src/apps/vpn/settingswatcher.cpp, src/apps/vpn/settingswatcher.h
somehow, on mac, `onEditingFinished` does not work as expected (VPN-4166). Let's add an extra check to avoid multiple activation.
=> Avoid multiple reconnect when changing custom DNS - VPN-4304

nebula/ui/components/MZLinkButton.qml, src/apps/vpn/ui/screens/getHelp/contactUs/ViewContactUsForm.qml
- Prevents the label in MZLinkButton from overflowing
| <img width="472" alt="Screen Shot 2023-03-10 at 11 07 05 AM" src="https://user-images.githubusercontent.com/15353801/224365507-47b8479e-a4b3-44c1-8c68-17b94139263a.png"> | <img width="472" alt="Screen Shot 2023-03-10 at 11 06 29 AM" src="https://user-images.githubusercontent.com/15353801/224365556-c8115959-3780-4d59-bf2e-f5577daf66dc.png"> |
[VPN-4290: [l10n] “Mozilla VPN Privacy Notice” link from “Contact support” screen has UI issues in some languages](https://mozilla-hub.atlassian.net/browse/VPN-4290)
=> Prevent link button in contact form from overflow

nebula/CMakeLists.txt, nebula/nebula.cpp, nebula/ui/components/MZButtonBase.qml, nebula/ui/components/MZCheckBox.qml, nebula/ui/components/MZSettingsToggle.qml, nebula/ui/components/MZSwipeDelegate.qml, nebula/ui/components/MZTextBlock.qml, nebula/ui/components/forms/MZRadioButton.qml, nebula/ui/components/forms/MZTextArea.qml, nebula/ui/components/forms/MZTextField.qml, nebula/ui/utils.qrc, nebula/ui/utils/MZUtils.qml, nebula/ui/utils/qmldir
- Instead of depending on a component specifically named `vpnFlickable` when ensuring a component is visible when gaining focus, iterate through it's view hierarchy to see if it is an ancestor of a scrollable view
- Results in a fix for keyboard nav scrolling on the tips and tricks page
- Introduce MZUtils - a home for generic qml utility functions in nebula
https://user-images.githubusercontent.com/15353801/223855212-c2136daa-756b-4e24-8321-a57829c583ed.mov
[VPN-2958: [a11y] Scroll is not working as expected using keyboard](https://mozilla-hub.atlassian.net/browse/VPN-2958)
=> Stop depending on vpnFlickable id on focus change

src/apps/vpn/connectionbenchmark/benchmarktasktransfer.cpp, src/shared/networkrequest.cpp, src/shared/networkrequest.h
I have been noticing that some of the unit tests fail on Qt 6.3.2, and when digging into it I have discovered that we are not receiving the payload data when handling an HTTP error, and this is required for some of the authentication flows (eg: TOTP or e-mail verification is required). To resolve this, we must handle the `QNetworkReply::readyRead()` signal.
Github issue #6143 ([VPN-4244](https://mozilla-hub.atlassian.net/browse/VPN-4244))
[VPN-4244]: https://mozilla-hub.atlassian.net/browse/VPN-4244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-4244: Handle the QNetworkReply::readyRead signal to avoid dropped data

src/apps/vpn/mozillavpn.cpp, src/apps/vpn/mozillavpn.h, src/apps/vpn/tasks/removedevice/taskremovedevice.cpp, src/apps/vpn/telemetry.cpp, src/apps/vpn/websocket/pushmessage.cpp, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp
This is one step in the direction of clean up MozillaVPN class.
=> Move telementry glean events out of MozillaVPN - VPN-4309

src/apps/vpn/ui/screens/settings/ViewDNSSettings.qml
This prevents an inactive loader from erroneously soaking up vertical space when going from  
`DNS settings view with VPN on` -> `home view via the nav bar and turning vpn off` -> `back to DNS settings view`.  
VPN-4348
=> Fix VPN-4348

scripts/utils/import_languages.py
This code was removing non-translated strings, leaving us with no fallback.
This is being merged into `2.14.0` and not `main` because it is working on `main`:
- A "smarter fallbacks" PR was merged on Feb 14: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5987
- Some follow up work was merged on Feb 16: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6059
- https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6059 was uplifted to the `releases/2.14.0` on Mar 9. 
- But the original work wasn't uplifted, and so a bug was introduced in the release branch only
https://mozilla-hub.atlassian.net/browse/VPN-4336
=> VPN-4336 - remove snippet of uplifted code

taskcluster/scripts/build/windows.ps1
We are encountering some build difficulty in CI, we have a couple hypothesis that might be the culprit. I suspect the problem is due to an error in the python path setup, as denoted by the following snippet in the logs:
```
[task 2023-03-17T07:52:14.208Z] resolve-path : Cannot find path 'Z:\task_167903922024535\AppData\Roaming\Python\Python36\Scripts' because it does not exist.
[task 2023-03-17T07:52:14.208Z] At Z:\task_167903922024535\build\src\taskcluster\scripts\build\windows.ps1:33 char:18
[task 2023-03-17T07:52:14.208Z] + $PYTHON_SCRIPTS =resolve-path "$env:APPDATA\Python\Python36\Scripts"
[task 2023-03-17T07:52:14.208Z] +                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task 2023-03-17T07:52:14.214Z]     + CategoryInfo          : ObjectNotFound: …
```
=> VPN-4379:  Fix the fetching of Sentry secrets in Windows CI

src/shared/cmake/sentry.cmake
It seems like we have a path expansion error on Windows when invoking the external build tool for Sentry. In particular, the existence of a trailing backslash on Windows is not guaranteed, which means that `${CMAKE_CURRENT_SOURCE_DIR}../3rdparty/sentry` doesn't evaluate into a sensible path. We can simplify this, and fix the bug by using `${CMAKE_SOURCE_DIR}/3rdparty/sentry` instead.
Github issue #6358 ([VPN-4379](https://mozilla-hub.atlassian.net/browse/VPN-4379))
[VPN-4379]: https://mozilla-hub.atlassian.net/browse/VPN-4379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VPN-4379: Fix path expansion to 3rdparty/sentry

nebula/ui/components/MZStackView.qml, src/apps/vpn/mozillavpn.cpp, src/apps/vpn/mozillavpn.h, src/shared/utils.cpp, src/shared/utils.h, tests/qml/mocmozillavpn.cpp, tests/unit/mocmozillavpn.cpp
This moves 'exitForUnrecoverableError()' to MZUtils so that MZStackView can be shared across products.
=> Move 'exitForUnrecoverableError'  to shared utils

.github/l10n/check_l10n_issues.py, .github/workflows/translations.yaml
Noticed in [this run](https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/4495825421/jobs/7909875419?pr=6422) for #6422 that the linter dies on an empty string.
Turns out the script was changed to not use lxml, which apparently causes an empty string to return None. That means that the script breaks like in the run before, and wouldn't report missing comments either.
Checked the oldest release branch (2.13) and it's already using the script without lxml.
=> Fix l10n linter when strings/comments are empty

src/apps/vpn/appfeaturelistcallback.h
We have flipped this off in the last 2 releases in a row, it's still not ready, so it should be disabled until we have a plan
=> NIT: Icebox start on boot for android

nebula/ui/components/MZMenu.qml, nebula/ui/components/MZPopup.qml, nebula/ui/components/MZScreenBase.qml, nebula/ui/components/inAppAuth/MZInAppAuthenticationBase.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationSignIn.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationSignUp.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationStart.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationUnblockCodeNeeded.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml, src/apps/vpn/ui/deleteAccount/ViewDeleteAccountRequest.qml, src/apps/vpn/ui/screens/ScreenSubscriptionBlocked.qml, src/apps/vpn/ui/screens/devices/ViewDevices.qml, src/apps/vpn/ui/screens/getHelp/ViewGetHelp.qml, src/apps/vpn/ui/screens/home/controller/ControllerView.qml, src/apps/vpn/ui/screens/initialize/ViewInitialize.qml, src/apps/vpn/ui/screens/settings/ViewGuide.qml, src/apps/vpn/ui/screens/settings/ViewSettingsMenu.qml, src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededIAP.qml, src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededWeb.qml, src/apps/vpn/ui/sharedViews/ViewErrorFullScreen.qml, translations/strings.yaml
- Adds new "Close" and "Get help" strings to strings.yaml 
- Specifically removes instances of `qsTrId("...")` from MZScreenBase and MZMenu so that these can actually be shared and opportunistically updates other files still using `qsTrId` for 'Close', 'Go back', and 'Get help' strings.
=> Remove instances of 'qsTrId("...close")', 'qsTrId("...back")', and 'qsTrId("...getHelp") 

src/apps/unit_tests/testipaddress.cpp, src/apps/vpn/appsettingslist.h, src/apps/vpn/cmake/sources.cmake, src/apps/vpn/commands/commandexcludeip.cpp, src/apps/vpn/commands/commandexcludeip.h, src/apps/vpn/controller.cpp, src/shared/ipaddress.cpp
Adds a setting to allow whitelisting of IP address ranges, to extend split-tunnelling capabilities.
Unfortunately I haven’t yet figured out how to efficiently modify the qml to add a settings view for it, so this is only the function bit so far.
In the mean time any feedback would be helpful. I use this as a patch and edit the json settings directly.
As described in #5182 
I’ve ran clang-format-11.0.1
“Where needed” is quite unclear but there seem to not be much testing for similar settings?
=> Addition of setting for whitelisting of IP address ranges

nebula/ui/components/MZSignOut.qml, nebula/ui/components/MZSubscriptionOption.qml, nebula/ui/components/MZSystemAlert.qml, nebula/ui/components/MZUserProfile.qml, nebula/ui/components/inAppAuth/MZInAppAuthenticationErrorPopup.qml, src/apps/vpn/commands/commandui.cpp, src/apps/vpn/platforms/android/androidcontroller.cpp, src/apps/vpn/platforms/macos/macossystemtraynotificationhandler.cpp, src/apps/vpn/systemtraynotificationhandler.cpp, src/apps/vpn/translations/strings.yaml, src/apps/vpn/ui/authenticationInApp/ViewAuthenticationStart.qml, src/apps/vpn/ui/main.qml, src/apps/vpn/ui/screens/ScreenAuthenticating.qml, src/apps/vpn/ui/screens/ScreenPostAuthentication.qml, src/apps/vpn/ui/screens/ScreenSubscriptionBlocked.qml, src/apps/vpn/ui/screens/ScreenSubscriptionInProgressIAP.qml, src/apps/vpn/ui/screens/ScreenSubscriptionInUseError.qml, src/apps/vpn/ui/screens/ScreenTelemetryPolicy.qml, src/apps/vpn/ui/screens/ScreenViewLogs.qml, src/apps/vpn/ui/screens/getHelp/ViewGetHelp.qml, src/apps/vpn/ui/screens/initialize/ViewInitialize.qml, src/apps/vpn/ui/screens/settings/ViewAboutUs.qml, src/apps/vpn/ui/screens/settings/ViewPreferences.qml, src/apps/vpn/ui/screens/settings/ViewSettingsMenu.qml, src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededIAP.qml, src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeededWeb.qml, src/apps/vpn/ui/sharedViews/ViewUpdate.qml
This PR
- Removes instances of `qsTrId("...")` from Nebula files
- Ignores MZToggle, which is up for relocation to vpn/ in #6354 
- Ignores MZSystemAlert which needs a larger refactor that will likely make the switch to MZI18n unnecessary.
- Removes instances of `qsTrId("..")` from *some* shareable screens 
- Pretends Give Feedback flow doesn't exist since soon it really won't 
- Ignores Languages view since #6417 
- Ignores views like settings/IAP where larger needed refactors will likely make the change unnecessary
=> Remove qsTrId() from Nebula and *some* soon to be shared screens

addons/message_update_v2.15/manifest.json, addons/message_whats_new_v2.15/manifest.json
Found another spelling inconsistency while reviewing the strings for 2.15.
=> Fix 'Server location' spelling to be consistent with the app
