src/shared/cmake/sentry.cmake
src/shared/utils.cpp

We did not enforce the client internal transport, therfore no screen was shown. Also the button does cause a proper shutdown on windows/release. 
https://user-images.githubusercontent.com/9611612/227237583-edcc86b5-4841-43c5-9018-3b2ff8521b93.mp4

VPN-4409 Fix Windows/Sentry

---

src/apps/vpn/cmake/sentry.cmake
src/apps/vpn/mozillavpn.cpp

Backport of the VPN-4409 fix for 2.14, as that patch does not apply

basti/fix sentry 2.14

---

qtglean/CMakeLists.txt
qtglean/glean_parser_ext/rust.py
qtglean/include/glean/metrictypes.h
qtglean/include/glean/uuid.h
qtglean/qtglean.pri
qtglean/src/cpp/uuid.cpp
qtglean/src/ffi/mod.rs
qtglean/src/ffi/uuid.rs

Adding UUID metric type. Tested locally, and working.
https://mozilla-hub.atlassian.net/browse/VPN-3690

VPN-3690 - Add UUID metric type to qtglean

---

.gitmodules

This undoes [a prior PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/4954), as Wireguard has updated their repo to fix the bug.
I've tested this on my personal device, which was able to replicate the original issue with IPv6 networks and iOS 16.
We can’t go to the [latest](https://github.com/WireGuard/wireguard-apple/compare/c229b7c1535f748c3b0f614e933fcfab2d3d5a50...2fec12a6e1f6e3460b6ee483aa00ad29cddadab1) wireguard-apple commit, as they bumped the minimum iOS version to 15.0 in a [recent commit](https://github.com/WireGuard/wireguard-apple/commit/901fe1cf58dc40e551088cac3bf00d68e3e86db3#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677e). Our VPN app supports 13.0 and above, and so we’d have to bump the minimum version of our app.
Luckily, the commit we …

VPN-3392 - update wireguard repo

---

qtglean/glean_parser_ext/templates/cpp_metrics_header.jinja2
qtglean/glean_parser_ext/templates/cpp_pings_header.jinja2
qtglean/include/glean/boolean.h
qtglean/include/glean/counter.h
qtglean/include/glean/datetime.h
qtglean/include/glean/event.h
qtglean/include/glean/ping.h
qtglean/include/glean/quantity.h
qtglean/include/glean/string.h
qtglean/include/glean/timingdistribution.h
qtglean/include/glean/uuid.h

There was nothing wrong in the previous implementation. Just 2 things we can do better:
- we exposed a CTOR for every glean type which left `m_id` not initialized. This CTOR can be removed.
- we duplicated/copied the glean types multiple times (in the QT world) every time we use them.
About this second point the issues are:
- why allocating more memory when we can use references/pointers?
- we have all these copy-CTORs without tests
- `m_id` cannot be `const` because of the copy-CTOR.
- all of this copying is because we use Q_GADGET with works with simple struct, copied all the times.
Q_GADGET does not work with pointers. I had to replace it with Q_OBJECT. I also add `Q_DISABLE_COPY_MOVE` to remove unwanted CTORs.
No changes in the API.

Clean up glean types - VPN-4455

---

glean/metrics.yaml

Adding existing metric to session ping
https://mozilla-hub.atlassian.net/browse/VPN-4441

VPN-4441: Add controller step metric to session ping

---

src/apps/vpn/notificationhandler.cpp
src/apps/vpn/platforms/android/androidcontroller.cpp
src/apps/vpn/translations/strings.yaml
tests/functional/testConnection.js
tests/functional/testServerSearch.js
tests/functional/testServers.js

Change the notification text for connecting and disconnecting the VPN to distinguish between singlehop and multihop settings. 
Please visit the original issue for the details. The only caveat is that because we don't have a way to track the previous state of the VPN, when we are switching from single to multihop and the other way around, we don't know anything about the previous state. For example, when going from multihop to single hop, we only know we are currently switching to single hop (without knowing if before it was single or multihop). For that reason there is no way to differentiate between multi to single hop and single to single hop scenarios when switching. So for now this PR only addresses changes other than "Switching".
https://mozilla-hub.atlassian.net/browse/VPN-4274

VPN-4274 Improve OS notifications

---

linux/extra/mozillavpn-startup.desktop.in
linux/extra/mozillavpn.desktop.in

The “Version” field of a desktop entry refers to the version of the desktop entry specification to which this file complies, not the program version. This PR puts the version to “1.5”.
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys
https://wiki.archlinux.org/title/Desktop_entries

Use 1.5 for the version of desktop file specification

---

src/apps/vpn/controller.cpp

I was working a bug (https://mozilla-hub.atlassian.net/browse/VPN-4164) that I have a theory on - multihop is enabled. However, it doesn't seem like we log anything about multihop status. This fixes that moving forward.
N/A

Add multihop logging

---

src/shared/loghandler.cpp

This is something i apply on my branches all the time. 
We should not do that in release && prod. 
However limiting this only to debug builds makes testing iAP & updating annoying.

Chore: ADB logs if not in production

---

src/apps/vpn/cmake/linux.cmake
src/apps/vpn/platforms/linux/daemon/org.mozilla.vpn.dbus.service.in

Just like the systemd service file [`linux/mozillavpn.service.in`](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/b9152c9b50773a5ca7301b75f16e35b0ed9e1f5d/linux/mozillavpn.service.in), the D-Bus service file [`apps/vpn/platforms/linux/daemon/org.mozilla.vpn.dbus.service`](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/b9152c9b50773a5ca7301b75f16e35b0ed9e1f5d/src/apps/vpn/platforms/linux/daemon/org.mozilla.vpn.dbus.service) should be configured with the proper path to the binary instead of hardcoding `/usr/bin`.
None
- nothing hard to understand
- no tests for similar items

Handle install bin dir in dbus service file

---

tools/inspector/package-lock.json
tools/inspector/package.json

This commit breaks the inspector.

Revert "Bump eslint-plugin-promise from 5.2.0 to 6.1.1 in /tools/inspector (#6096)"

---

src/apps/vpn/ui/screens/settings/appPermissions/AppPermissionsList.qml

"Screen cap" of App Images on Windows display 
VPN-2953

Maybe fix wonky Windows App Exclusions images

---

src/apps/vpn/ui/main.qml
src/shared/env.cpp
tests/qml/mocconstants.cpp
tests/qml/tst_mainWindowGleanMocks.qml

During some recent refactoring, we moved many of the properties out of the `MozillaVPN` class and into a shared `MZEnv` component. Unfortunately, during that refactoring we missed the migration of `VPN.stagingMode` to `MZEnv.stagingMode` when initializing glean, resulting in many of our tests sending their telemetry pings to the production channel.
Github PR #6289 
Github issue #6586 [VPN-4541](https://mozilla-hub.atlassian.net/browse/VPN-4541)
[VPN-4541]: https://mozilla-hub.atlassian.net/browse/VPN-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4541: Fix channel for staging mode on Glean initialization

---

addons/tutorial_01_get_started/condition.js
addons/tutorial_01_get_started/manifest.json
addons/tutorial_01_get_started_recommended_locations/isRecommendedSelected.js
addons/tutorial_01_get_started_recommended_locations/manifest.json
addons/tutorial_03_multi_hop/manifest.json
nebula/ui/components/MZSegmentedToggle.qml
nebula/ui/components/MZTabNavigation.qml
nebula/ui/components/MZTutorialPopups.qml

- Improvements to both the old and new "Getting started" tutorials, including:
- Replace `min_client_version` and `max_client_version` conditions with a feature check for `recommendedServers`
- This ensures that we always have a "Getting started" tutorial to show (but should only happen in the event that the "Recommended Servers" feature flag is turned off in version 2.15+)
- Close and re-open tutorial tooltips with a small delay
- Fix old "Getting started" tutorial for 2.15+ 
- As mentioned above, we most likely won't see the old "Getting started" tutorial on 2.15+, but at least it works if we do
- Add an extra step to the new "Getting started" tutorial to have the user select the "Recommended" tab for when the user's preferences is set to the "All" tab
[VPN-3368: Implement the new "Get …

VPN-3368 / VPN-4481 / VPN-4482 / VPN-3869 - "Getting started" tutorial improvements

---

addons/tutorial_01_get_started/condition.js
addons/tutorial_01_get_started/manifest.json
addons/tutorial_01_get_started_recommended_locations/isRecommendedSelected.js
addons/tutorial_01_get_started_recommended_locations/manifest.json
addons/tutorial_03_multi_hop/manifest.json
nebula/ui/components/MZSegmentedToggle.qml
nebula/ui/components/MZTabNavigation.qml
nebula/ui/components/MZTutorialPopups.qml
src/apps/vpn/ui/screens/home/servers/ServerList.qml

- Allows both the new and old "Getting started" tutorials to function on 2.15 
- Since the "Recommended servers" feature is shipping with 2.15, the only time a user should see the old "Getting started" tutorial is if the feature is turned off
[VPN-3368: Implement the new "Get Started" Tutorial](https://mozilla-hub.atlassian.net/browse/VPN-3368)
[VPN-4481: Users who have never selected the “All” tab are not able to finalize the “Getting started with VPN” tutorial](https://mozilla-hub.atlassian.net/browse/VPN-4481)
[VPN-4482: Users are not able to finalize the “Using multi-hop VPN” / “Getting started with VPN” tutorials](https://mozilla-hub.atlassian.net/browse/VPN-4482)
[VPN-3869: Make tooltips display with a slight delay](https://mozilla-hub.atlassian.net/browse/VPN-3869)

VPN-3368 / VPN-4481 / VPN-4482 / VPN-3869 -"Getting started" tutorial improvements for 2.15

---

src/apps/vpn/models/servercity.cpp

In 2.15 we replaced the initial distance-based server selection with the recommended-server algorithm. This algorithm has a clause wherein a server with no reported latency is reported with a score of zero, which overrides the preference given to locations within the user's originating country. To try and restore this preferential treatment of the user's country, let's try showing the connection score even in the absence of latency data.
Github issue #6469 ([VPN-4449](https://mozilla-hub.atlassian.net/browse/VPN-4449))
[VPN-4449]: https://mozilla-hub.atlassian.net/browse/VPN-4449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4449: Allow connection scoring without latency

---

src/apps/vpn/purchasewebhandler.cpp

Use the correct callback for web purchases so after redirecting back to the VPN user is no longer stuck on the subscription screen.
https://mozilla-hub.atlassian.net/browse/VPN-4451

VPN-4451 Use the correct callback for web-purchase - VPN-4451

---

src/apps/vpn/purchasewebhandler.cpp

Cherry picking from `main`. Use the correct callback for web purchases so after redirecting back to the VPN user is no longer stuck on the subscription screen.
https://mozilla-hub.atlassian.net/browse/VPN-4451

Use the correct callback for web-purchase - VPN-4451 (#6616)

---

CODEOWNERS
scripts/utils/generate_strings.py
scripts/utils/generate_ts.sh
scripts/utils/import_languages.py
src/apps/auth_tests/translations/strings.yaml
src/apps/relay/translations/strings.yaml
src/apps/template/translations/strings.yaml
src/apps/unit_tests/translations/strings.yaml
src/apps/vpn/translations/strings.yaml
src/shared/translations/strings.yaml
translations/CMakeLists.txt
translations/translations.pri

There a few strings that have to be included in all the P&S products. Instead of duplicating them in all the `strings.yaml`, in this PR I introduce a shared strings.yaml which is "merged" with the product specific ones at build time.

Move common strings to a shared `strings.yaml`

---

src/shared/cmake/sentry.cmake
taskcluster/scripts/build/android_build_debug.sh
taskcluster/scripts/build/android_build_release.sh
taskcluster/scripts/build/ios_build_no_adjust.sh
taskcluster/scripts/build/ios_build_no_adjust_cmake.sh
taskcluster/scripts/build/macos_build.sh
taskcluster/scripts/build/macos_universal_build.sh
taskcluster/scripts/build/windows.ps1

We have sentry as submodule. 
Let's cmake use the submodule instead of attempting to pull the repo into the submodule itself. 
This should make that step faster :)

Nit: Don't pull sentry, just use the submodule

---

scripts/linux/script.sh

In https://github.com/mozilla-mobile/mozilla-vpn-client/pull/6661 - i stopped cmake from fetching sentry, instead it should use whatever we have locally, relying on git-submodules working. 
I forgot to make sure the linux source bundle also fetches recusive git submodules. 
This causes the windows level-3 builds to fail.

Bug: Source Bundle does not contain sentry submodules

---

src/apps/vpn/appfeaturelist.h
src/apps/vpn/controller.cpp

In discussion around VPN-4164, we decided to add back an option to force port 53, but hide it in the dev menu. Once this goes live, this user will then be able to test by always forcing port 53.
https://mozilla-hub.atlassian.net/browse/VPN-4164

VPN-4164: Add dev menu option for forcing port 53

---

src/apps/vpn/translations/strings.yaml
src/apps/vpn/ui/screens/home/servers/ServerCountry.qml
src/apps/vpn/ui/screens/home/servers/ServerLatencyIndicator.qml
src/apps/vpn/ui/screens/home/servers/ServerList.qml

- Add connectivity score to accessible names that are read out when navigating through city servers
[VPN-4210: Server latency indicators should support screen readers](https://mozilla-hub.atlassian.net/browse/VPN-4210)

VPN-4210: Screen reader support for latency indicators

---

src/apps/vpn/connectionhealth.cpp
src/apps/vpn/connectionhealth.h
src/apps/vpn/mozillavpn.cpp
src/apps/vpn/mozillavpn.h

Add a new inspector command to override connection health stability: stable, unstable and no_signal in mozillavpn.cpp which will be used in functional tests and by QA.
https://mozilla-hub.atlassian.net/browse/VPN-4406

VPN-4406 [Part 1] Add Inspector command to overwrite connection health stability

---

nebula/ui/components/MZSubscriptionOption.qml
src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeeded.qml

- Fixes the "Subscribe now" button on the IAP page for mobile. Tapping "Subscribe now" again has the same effect as tapping a selected subscription option
[VPN-4641: "Subscribe now" button on mobile IAP screen does not work](https://mozilla-hub.atlassian.net/browse/VPN-4641)

VPN-4641: Fix "Subscribe now" button on IAP page

---

extension/CMakeLists.txt
extension/manifests/linux/mozillavpn.json.in
linux/debian/rules

Change `WEBEXT_INSTALL_LIBDIR` to be consistently an absolute path.
Currently uses disagree on whether it is meant to be absolute or relative to /
From linux/mozillavpn.spec:
```
%cmake -DWEBEXT_INSTALL_LIBDIR=/usr/lib -DCMAKE_INSTALL_SYSCONFDIR=/etc -DBUILD_TESTING=OFF
```
From linux/debian/rules:
```
dh_auto_configure -- -DWEBEXT_INSTALL_LIBDIR=lib -DBUILD_ID=$(DEB_VERSION) -DBUILD_TESTING=OFF
```
This caused rpm to generate paths like `//usr/lib/mozillavpn/mozillavpnnp` which in turn cause Firefox to not find the mozillavpnnp binary.
Using an absolute path be default for `WEBEXT_INSTALL_LIBDIR`, as it is easier when variables point to install dirs in build processes, i.e. `/${lib}` is easier than stripping a leading / from `%{_libdir}`.
None

Fix double leading / in mozillavpn.json path property

---

nebula/ui/components/forms/MZTextField.qml
src/apps/vpn/ui/screens/settings/ViewDNSSettings.qml
tests/functional/testSettings.js

- Various DNS setting fixes that were uplifted to 2.14, but never uplifted to 2.15 
[VPN-4651: Standard DNS fallback not applied after leaving the custom DNS field empty and navigating from the DNS screen using the “Settings” icon](https://mozilla-hub.atlassian.net/browse/VPN-4651)

VPN-4651: Uplift DNS setting bug fixes

---

addons/message_paid_research_old/OpenSurveyURL.js
addons/message_paid_research_old/currencyCheck.js
addons/message_paid_research_old/manifest.json
addons/message_paid_research_old/setDate.js

We need to dup this addon because in 2.14 we do not have `threshold_completeness" property and the addon is rejected (correctly).

Support 2.14.0 client for message_paid_research

---

nebula/ui/components/MZPopup.qml

- Dismiss all modals whenever the screen behind the modal changes
[VPN-2830: Modal displayed on top of the “Get started” screen after a device removal if the modal is not closed before the removal action](https://mozilla-hub.atlassian.net/browse/VPN-2830)

VPN-2830: Close modals when screen changes

---

addons/message_paid_research/OpenSurveyURL.js
addons/message_paid_research/currencyCheck.js
addons/message_paid_research/manifest.json
addons/message_paid_research/setDate.js
addons/message_paid_research_old/OpenSurveyURL.js
addons/message_paid_research_old/currencyCheck.js
addons/message_paid_research_old/manifest.json
addons/message_paid_research_old/setDate.js

This PR looks to merge two new addons `message_paid_research` and `message_paid_research_old` into a branch I created `addon_releases/2.14_mid_cycle_ship_paid_research`.
We want to immediately ship the `message_paid_research` addons. But we should use the most recent addons that were QA'd and are live in production.
I branched `addon_releases/2.14_mid_cycle_ship_paid_research` at commit 89989986a10522d60abf0f623a7d44704ccaad16. I then added the addons in this PR.

Add message_paid_research addons to older branch

---

addons/message_subscription_expiring/contactSupportLink.js
addons/message_subscription_expiring/manageAccountLink.js
src/apps/vpn/appconstants.h
src/apps/vpn/mozillavpn.cpp

- Utilize correct addon api to open web links to subscription management and support pages
*This will be uplifted to 2.15
[VPN-4674: Buttons in "Subscription Expiring" message do not work](https://mozilla-hub.atlassian.net/browse/VPN-4674?search_id=6d2f1509-d6d7-42a5-9d32-fe8d82acea16)

VPN-4674: Fix subscription expiring message buttons

---

addons/message_subscription_expiring/manifest.json

- Disables the "Subscription expiring" message until other bugs are resolved
[VPN-4699: Disable "Subscription expiring" message addon for 2.15 addon RC](https://mozilla-hub.atlassian.net/browse/VPN-4699)

VPN-4699: Disable "Subscription expiring" message

---

src/apps/vpn/platforms/linux/linuxapplistprovider.cpp
src/apps/vpn/platforms/linux/linuxapplistprovider.h

Improve the search for desktop files on Linux by following freedesktop specs closer
- correct user directories (from `$XDG_DATA_HOME` if defined before `$HOME/local/data`) 
- correct system fallbacks (both `/usr/locale/share/applications` and `/use/share/applications`)
- added missing desktop-file hiding mechanisms `OnlyShowIn`, `NotShowIn`, and `Hidden`
- added autostart desktop files to cover applications started at launch (because autostart is implemented by copied desktop files which means they are referenced as different application “ids”)
None

Linux improved desktop file search

---

src/shared/platforms/windows/windowsutils.cpp
src/shared/platforms/windows/windowsutils.h
src/shared/utils.cpp

While trying to make sure that the crash reporter is working, I encountered a few intermittent builds where the `Test Crash Reporter` button wasn't able to actually crash the client. So I felt like making this a more reliable crash by using the Win32 API `RaiseException()` instead.

Chore: A more reliable crash testing method for Windows

---

tests/functional/testAddons.js

Override version in addons test to make it pass again. Line 260 `await vpn.setVersionOverride('101.0.0');` and line 341 are the only real changes in this PR, the rest is from the formatter moving code around.
n/a

Override version in addons test

---

src/apps/vpn/cmake/windows.cmake
taskcluster/scripts/build/windows.ps1

Due to some suboptimal support for `RelWithDebInfo` in CMake, we find that we have to manually enable debug symbol generation using the `/Zi` flag, unfortunately it seems that we missed that we also need to specify `/debug` as a linker option in order to produce the PDB file too.
Furthermore, the generated `vc140.pdb` with just `/Zi` was a red herring. Those were the debug symbols for the C++ runtime which don't actually include any symbols for our application.
I'm not entirely sure how to test this without pushing to the main branch, but I am significantly happier with the build artifacts that we are generating now.
Github issue #5766 ([VPN-4007](https://mozilla-hub.atlassian.net/browse/VPN-4007))
CMake `RelWithDebInfo` issue: https://gitlab.kitware.com/cmake/cmake/-/issues/20812 …

VPN-4007: Fix symbol generation for Windows builds.

---

docs/QML HotReloading.md
package-lock.json
package.json
src/shared/frontend/navigator.cpp
src/shared/frontend/navigator.h
src/shared/inspector/inspectorhandler.cpp
src/shared/inspector/inspectorhotreloader.cpp
src/shared/inspector/inspectorhotreloader.h
src/shared/sources.cmake
tools/hot.js
tools/qml_hot_reload/hot.js

I'll be out the next 2.5 weeks so i did not want to get this lost :) 
However this might make qml more sweet for people. 
This consists out of 2 things: 
-> hot.js: Is an fs_watcher and calls `live_reload <path-to-qml>` whenever something changes via inspector
-> Inspector_patchtes: new command `live_reload` -> will intercept all qml loads and replace a matching file with the new path, can be file://, http://, qrc://<file>. Will also reload the current screen.
https://user-images.githubusercontent.com/9611612/222613103-edca265c-f489-4762-afa7-22d344d62c19.mov

VPN-4270 - Hot reload qml

---

src/apps/vpn/mozillavpn.cpp
src/apps/vpn/mozillavpn.h
src/apps/vpn/purchasewebhandler.cpp
src/apps/vpn/telemetry.cpp

A signal of `subscriptionCompleted` causes us to record this metric in the telemetry file. It was not being triggered by web purchases, in part because of the two different routes to calling `completeActivation`:
- For Android/iOS IAP, a completed IAP calls `MozillaVPN::subscriptionCompleted`, which in turn calls `completeActivation`. 
- Successful web subscriptions call `MozillaVPN::completeAuthentication`, which also calls `completeActivation`. 
To have the metric recorded for both routes, we disconnect the telemetry file from `subscriptionCompleted`, and add a new signal that triggers it.
I've tested this for both iOS (IAP) and macOS (web):
- Signing into an account with an active subscription (no IAP completed metric expected)
- Fresh subscription (IAP metric expected with appropriate …

VPN-4535 add metric for web purchases

---

src/apps/vpn/ui/screens/subscriptionNeeded/ViewSubscriptionNeeded.qml

During the refactor - we moved the repeater into a `loader` - meaning the spinner cant bind to `productListRepeater`
Moving this to the repeater should fix the issue :)  
https://user-images.githubusercontent.com/9611612/236232017-96047579-1b9a-43a3-9f8d-b95fb38be805.mov

VPN-4714 - Fix Spinner

---

src/apps/vpn/cmake/macos.cmake

In PR #6734 We added support for building all Apple targets using Conda, part of which involved fixing a compilation error in the wireguard-go component. Unfortunately I only fixed it for the universal case, and neglected the case when `CMAKE_OSX_ARCHITECTURES` is unset, in which case the host architecture should be used.
To fix this, let's just gather the golang environment into one place so that there is a single source of truth for both cases.
Pull request #6734

Chore: Fix MacOS builds when CMAKE_OSX_ARCHITECTURES is empty

---

qtglean/Cargo.toml

Recently we have been failing to build the VPN client on Ubuntu/bionic due to a linker error between qtglean and libssl the offending symbols are `X509_get0_authority_issuer` and `X509_get0_authority_serial`. We have filed an upstream PR to fix the issue properly, but in order to get the 2.15.0 release building again, we may need to force a downgrade of the `openssl` and `openssl-sys` crates.
Note that this PR is only targeting the 2.15.0 release. I predict that we are either going to deprecate Ubuntu/bionic for 2.16.0, or the upstream project will release a fix.
Github issue #6772 ([VPN-4695](https://mozilla-hub.atlassian.net/browse/VPN-4695))
[VPN-4695]: https://mozilla-hub.atlassian.net/browse/VPN-4695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

VPN-4695: Force version downgrade for openssl and openssl-sys crates

---

.github/workflows/ppa-automation.yaml

My test PPA recently had an erroneous push, which was trigger by the creation of a branch named `releases/addon_releases/2.14_mid_cycle_ship_paid_research` and this has fouled up the version numbering in the PPA. To prevent such issues from happening again, we should tighten the branch matching syntax.

Chore: Tighten up PPA Automation branch matching

---

nebula/ui/components/MZTutorialPopups.qml

- Fix stutter that would occur when the first tooltip of a tutorial would show
Before:
https://user-images.githubusercontent.com/15353801/236956840-3183ea51-a593-4e41-a2e7-3fc76883ab63.mp4
After: 
https://user-images.githubusercontent.com/15353801/236956735-aaa2cde2-4565-49ba-9d5a-d339d63c0343.mov
[VPN-4568: [Android]  First tooltip of the tutorials is glitchy ](https://mozilla-hub.atlassian.net/browse/VPN-4568)

VPN-4568: Fix tutorial tooltip stutter on android

---

src/apps/vpn/telemetry/pings.yaml

Adds new ping, to set up for future metrics work.
Also updates description for `vpnsession` ping to match latest plans per the [tech spec](https://mozilla-hub.atlassian.net/wiki/spaces/SECPRV/pages/184419319/VPN+session+pings+-+Tech+spec).
https://mozilla-hub.atlassian.net/browse/VPN-4579

VPN-4579 add daemon ping

---

linux/debian/control
linux/debian/rules

Now that we are no longer required to support Ubuntu/bionic, we can switch to using Ninja as the official build system on Linux. It's faster and tends to manage dependencies significantly better than Make.

Chore: Use Ninja for Linux

---

src/apps/vpn/platforms/linux/daemon/dbusservice.cpp

In the 2.15 release, we tried to add the ability to change VPN settings without requiring the user to deactivate the VPN, and this introduced a bug in the DBus `activate()` method where apps would be could be added to the exclusion list, but they were only removed upon deactivation. This leads to a situation where the user might turn off split tunnelling in the UI, but it still gets applied by the daemon.
Github issue #3168 ([VPN-1990](https://mozilla-hub.atlassian.net/browse/VPN-1990))
[VPN-1990]: https://mozilla-hub.atlassian.net/browse/VPN-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-1990: Fix Linux split tunnel tracking on server switch

---

src/apps/vpn/platforms/windows/daemon/windowssplittunnel.cpp

This is a hunch. Neither me or @strseb were able to reproduce this issue on our own machines.

VPN-4725 - Reset windows split tunnel drive if it's already initialized

---

src/apps/vpn/daemon/daemon.cpp
src/apps/vpn/daemon/daemon.h
src/apps/vpn/platforms/windows/daemon/windowsdaemon.cpp

The Windows platform applies the App exclusions in the `Daemon::run()` method, but this method is only invoked during the `Up` and `Down` events. It is not called during server switching, which prevents the user from changing app exclusion settings while the VPN is active. Even worse, by gating the split tunnelling driver operations on the length of the exclusion list (even during deactivation), this can also lead to cases where the driver is still applying an app exclusion even after manually toggling the VPN state.
To address these cases, we need to add a `Daemon::run()` operation for the silent server switch, and we should be a little more rigorous in our attempts to start and stop the driver in all cases.
Github issue #6842 ([VPN-4725](https://mozilla-hub.atlassian.net/browse/VPN-4725) …

VPN-4725: Apply app exclusions when server switching

---

taskcluster/ci/docker-image/kind.yml

We had disabled the cache for the Ubuntu/lunar docker image while Ubuntu/lunar was in beta so that we would receive updates as they resolved issues, but now that Ubuntu/lunar has received an official release we can  enable the cache again to reduce the load on Taskcluster.

Chore: Enable cache for Ubuntu/lunar docker image

---

qtglean/src/cpp/boolean.cpp
qtglean/src/cpp/counter.cpp
qtglean/src/cpp/datetime.cpp
qtglean/src/cpp/event.cpp
qtglean/src/cpp/quantity.cpp
qtglean/src/cpp/string.cpp
qtglean/src/cpp/timingdistribution.cpp
qtglean/src/cpp/uuid.cpp
src/shared/glean/mzglean.cpp

Windows has its own 8-bit character encoding (CP-1251) which is generated by `QString::toLocal8Bit()` on Windows, but our FFI wrappers for Rust only accepts UTF-8. Normally, this difference in encoding goes unnoticed because both are supersets of ASCII. However, when the Windows account has a username containing non-ASCII characters, this results in an invalid UTF-8 string being generated for the glean directory path, but only on Windows. This causes the Glean initialization to fail, which prevents the app from launching.
To fix this, we should be using `QString::toUtf8()` when converting `QStrings` into a Rust `FfiStr`
Github issue #6063 ([VPN-4192](https://mozilla-hub.atlassian.net/browse/VPN-4192))
[VPN-4192]: https://mozilla-hub.atlassian.net/browse/VPN-4192?atlOrigin=eyJpIjoiNWRkNTljN …

VPN-4192: Encode Glean FFI strings as UTF-8

---

src/apps/vpn/telemetry/metrics_deprecated.yaml

Based on a question from the data team, I realized this entry was out of date with how our code changed to become a multi-product app. This updates the code, which will eventually update the Glean data dictionary.
N/A

Fix Glean documentation to match current code

---

linux/debian/control
linux/debian/mozillavpn.postinst

In playing with Ubuntu Lunar, I have been finding that user-accessible ICMP sockets are blocked by the system configuration. So let's see if we can get things working by running `setcap` as a postinst hook to enable raw socket access.
We need this capability for the recommended server list to generate latency data.
Github issue #6930 ([VPN-4816](https://mozilla-hub.atlassian.net/browse/VPN-4816))
[VPN-4816]: https://mozilla-hub.atlassian.net/browse/VPN-4816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4816: Linux postinst script to set cap_net_raw

---

src/apps/vpn/commands/commandui.cpp
src/apps/vpn/mozillavpn.cpp
src/apps/vpn/mozillavpn.h
tests/qml/mocmozillavpn.cpp
tests/unit/mocmozillavpn.cpp

For GUI environments, the shutdown of the client is signalled by the session manager sending a `QGuiApplication::commitDataRequest()` signal, during which we take steps to deactivate the VPN. However, this often leaves the deactivation task running in the queue when we start to deallocate objects.
On MacOS, this frequently results in an assert with the following stack trace:
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18a916d78 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18a94bee0 pthread_kill + 288
2   libsystem_c.dylib             	       0x18a886340 abort + 168
3   QtCore                        	       0x10a1d8e18 qAbort() + 12 (qglobal.cpp:3369)
4   QtCore                        	       0x10a1dcb34 …
```

Chore: Wait for deactivation to finish during shutdown

---

src/apps/vpn/appfeaturelist.h
src/apps/vpn/appfeaturelistcallback.h

- Disable the free trial feature (which was only currently supported on iOS) 
- Left code in tact in case we want to bring this feature back
[VPN-4834: [iOS] 7-day free trial text still displayed in the onboarding screen](https://mozilla-hub.atlassian.net/browse/VPN-4834)

VPN-4834: Disable free trial feature

---

taskcluster/mozillavpn_taskgraph/transforms/beetmover.py

This unbreaks release promotion.
This check neglects to take into account the fact that there are two products being beetmoved. Addons and the client. E.g, when the shipping-phase is `promote-addons`, the client tasks will have no destination paths, and that is totally valid.

ci: remove bogus check for destination_paths in beermover

---

taskcluster/mozillavpn_taskgraph/transforms/release_notify.py

We added a `by-level` key to the notify tasks, but neglected to add the transform to resolve them.
Fixes an error in the release promotion graphs.

ci: resolve 'notify.recipients' in release_notify tasks

---

ios/app/Info.plist.in

The lack of Bundle Display Name was causing this bug. (It seems like other similar features - like notifications permissions prompt - fall back on Bundle Name, but for some reason the VPN did not.) 
https://mozilla-hub.atlassian.net/browse/VPN-4773

VPN-4773: add Bundle Display Name to info.plist

---

translations/CMakeLists.txt

This was causing build errors because we were looking in ALL directories previously, including places like .DS_Store. Thank you Bea for helping track this down 😌
n/a

Ignore directories starting with . for translations

---

taskcluster/requirements.in
taskcluster/requirements.txt

This picks up a regression fix that was causing VPN indexes to not get updated.

ci: update Taskgraph to version 5.1.1

---

taskcluster/mozillavpn_taskgraph/transforms/beetmover.py

Before we assumed only addon directories would be included under the `addons` path. This patch updates the logic to "this is an addon if it is a directory with a manifest.json file."
N/A

Fix thinking CMakeLists.txt is an rcc addon

---

taskcluster/requirements.txt

Reverts mozilla-mobile/mozilla-vpn-client#7010
This caused all builds to fail with: https://firefox-ci-tc.services.mozilla.com/tasks/CgsuoED1S8WWMUYsGf348A/runs/0/logs/live/public/logs/live.log

Revert "Bump taskcluster-taskgraph from 5.1.1 to 5.2.0 in /taskcluster"

---

src/apps/vpn/connectionhealth.cpp
src/apps/vpn/connectionhealth.h
src/apps/vpn/pinghelper.h
tests/unit/CMakeLists.txt
tests/unit/mocmozillavpn.cpp
tests/unit/testconnectionhealth.cpp
tests/unit/testconnectionhealth.h

This may seem a bit random :). I wanted to see what it "feels like" to add some unit test coverage to existing components, and picked the first function I came across that seemed interesting. I couldn't convince myself easily that the EWMA calculation works correctly just by looking at the code so I tried to write a test for it. (Spoiler: Yes, it all works correctly)
I chose the path of minimal refactoring and give the tests access to some internals, which I think is fine. The alternative would be to make these internals publicly accessible, which doesn't seem right as it would make the components fragile. The trade-off here is of course that the tests are then more fragile i.e., internal changes of the component can break the tests, but that seems better than exposing those internals via …

Add some unit test coverage for connection health

---

src/apps/vpn/models/devicemodel.cpp

This removes the user's device name from logs. 
VPN-4871

Fix VPN-4871 / Remove device name from logs

---

.github/workflows/i18n_update.yaml

Our handling of the i18n repo is a bit weird. 
We have removed the auto update-to-i18n/main from our build system - the CI will still do that, to make sure we have latest strings in there. 
Developers need to manually update the submodule- but apparently we are not commiting those updates upstream. 
So the last time we updated the submodule was 3 weeks ago
- https://github.com/mozilla-mobile/mozilla-vpn-client/tree/main/src/apps/vpn/translations
This can lead to weird scenarios outside of CI. It's hard to know what commit of the vpn is build with what version of the strings. 
This PR will add a workflow that: 
1. Update the i18n repo.
2. File a pr. 
3. Approve the pr. 
4. Mark is as auto merge, which means, if CI does pass, this will be merged automatically. 
Right now this will only run …

[gh-ci] Add a Task that will update i18n automatically

---

taskcluster/ci/beetmover/kind.yml
taskcluster/mozillavpn_taskgraph/transforms/beetmover.py

Support regulary ask's users to check if a downgrade fixes their problems. So they need a android builds to be published somewhere, so how about we also beetmove them to archive automatically? 
This is my first shot at touching beetmover. The generated task looks, somewhat reasonable calling `taskgraph full`, but how would one test that this is working? 😅 
```
"beetmover-android-arm64": {
"attributes": {
"always_target": false,
"build-type": "android/arm64-v8a",
"kind": "beetmover",
"release-artifacts": [
{
"name": "public/build/mozillavpn-arm64-v8a-release.apk",
"path": "/builds/worker/artifacts/mozillavpn-arm64-v8a-release.apk",
"type": "file"
}
],
"run_on_projects": [
"all"
],
"run_on_tasks_for": [
"action"
],
"shipping-phase": "",
"shipping_phase": null
},
"dependencies": {
"signing": …
```

Nit: Beetmove android releases to archive

---

tools/wasm_chrome/branch_selector.mjs
tools/wasm_chrome/generate_branch_file.ts
tools/wasm_chrome/helpers.mjs
tools/wasm_chrome/index.html

Ok, so. There was an issue with the branch list getter code. We were only getting the first 100 branches and `main` was not part of those. This fixes that + some papercut UI fixes on the branch selector.
I believe the whatever was the issue with the WASM simulator is not happening on `main` anymore, because locally I can reproduce the issue on branch such as `VPN-4867`, but not on `main`.
I will do some more time boxed investigation to see when exactly was this broken, but since it seems the main issue has been fixed already -- the main issue being the fact that `main` was not listed in the branches for the simulator -- this is ready for review.
[UPDATE]
The error happens because we are hitting this assertion: https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/shared/locali …

VPN-4877 - Fix broken WASM simulator

---

.github/workflows/i18n_update.yaml

Check: 
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7049
As the PR was opened by Github, it will not trigger github workflows, only taskcluster ones. 
So let's swap who's opening and who's r+ ing. :)

Swap Tokens in i18n chain

---

.github/workflows/i18n_update.yaml

Under the Premise that our CI is not failing - the i18n submodule update task is working as expected: 
https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7049
So let's have the Languages updated every day.
As a side effect that also means we will be publishing a fresh wasm build using that strings every day cc @flodolo

Run the i18n Task every day at 6:00

---

env.yml

Updates `cmake` to 3.26.3 which is the minimum version required for updating the macOS builder machines to xcode 14.2
See original request at https://mozilla-hub.atlassian.net/browse/RELOPS-539

RELOPS-539 Update cmake to 3.26.3

---

taskcluster/ci/test/kind.yml
taskcluster/requirements.txt

The `test-taskgraph-definitions` task is busted but has been passing due a bug in Taskgraph. Version 5.2.0 fixes the bug so the task should start properly failing. This PR will address the failures.

ci: upgrade Taskgraph and dependencies

---

taskcluster/ci/mac-notarization/kind.yml

MacOS notarization is moving from iscript to signingscript and requires a separate task.
There are no ways of testing notarization outside production. So, this change only adds the notarization task, but *DOES NOT* affect any other tasks.
The current signing still notarizes, and is treated as source/upstream by the beetmover task.
[Bug 1774273](https://bugzilla.mozilla.org/show_bug.cgi?id=1774273)

Bug 1774273 - Part (1/2) - Add signingscript macos notarization task

---

docs/dev-setup/index.md

This PR removes the  letter `a` from `env.yaml` in our build docs, so that if you are, like I was, copying and pasting you won't hit the following... 
`EnvironmentFileNotFound: '/path/to/where/your/vpn/things/live/env.yaml' file not found`
No ticket

Tiniest fix for build docs (no ticket) 

---

qtglean/include/glean/ping.h
qtglean/src/cpp/ping.cpp
qtglean/src/ffi/boolean.rs
qtglean/src/ffi/counter.rs
qtglean/src/ffi/datetime.rs
qtglean/src/ffi/event.rs
qtglean/src/ffi/helpers.rs
qtglean/src/ffi/ping.rs
qtglean/src/ffi/quantity.rs
qtglean/src/ffi/string.rs
qtglean/src/ffi/timing_distribution.rs
qtglean/src/ffi/uuid.rs

- Add "Reason" parameter to qtglean wrapper
[VPN-4867: Support "reason" parameter for custom ping submissions](https://mozilla-hub.atlassian.net/browse/VPN-4867)

VPN-4867: Support "reason" parameter for ping submission

---

taskcluster/ci/build/macos.yml

Looking at the task output of the Mac Builder - Since 2.16 this is a universal build - the taskcluster row should reflect that :) 
```
~/D/M/M/C/MacOS  file 'Mozilla VPN'                                                                    9  18:40 
Mozilla VPN: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
Mozilla VPN (for architecture x86_64):	Mach-O 64-bit executable x86_64
Mozilla VPN (for architecture arm64):	Mach-O 64-bit executable arm64
``?

Mark OSX builds as universal in Treeherder.

---

scripts/utils/generate_ts.sh

In the last round of refactoring on the addon generation, we needed to update the `genetrate_ts.sh` script, but I left a typo in there that would fail to build the addons from release branches when CMake was used.
Github issue #7084 ([VPN-4919](https://mozilla-hub.atlassian.net/browse/VPN-4919))
[VPN-4919]: https://mozilla-hub.atlassian.net/browse/VPN-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4919: Fix cmake build invocation when extracting strings

---

android/daemon/build.gradle
android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/ConnectionHealth.kt
src/apps/vpn/telemetry/metrics.yaml
src/apps/vpn/telemetry/metrics_deprecated.yaml

The connection health checks on the Daemon are different from the connection health checks on the client. This is a caveat worth noting at analysis time. I have added a longer description to the metrics to make this more explicit.
For this work I have considered that an unstable event happens when the connection is deemed worh a silent server switch while a no signal even happens when we have given up hope. Does that make sense?

VPN-4496 - Record health metrics on the Android daemon

---

nebula/ui/components/MZSettingsToggle.qml
nebula/ui/components/MZTabNavigation.qml

This PR 
- fixes the QML error noted in VPN-4968 and VPN-4974 (follow sentry links) 
- opportunistically "fixes" `Warning: qrc:/qt-project.org/imports/QtQuick/Controls/macOS/CheckBox.qml:45: TypeError: Property 'styleFont' of object MZUIStates_QMLTYPE_7(0x6000007acd20) is not a function (CheckBox.qml:45)` which is caused by a [known Qt bug](https://bugreports.qt.io/browse/QTBUG-101026) which they've allegedly fixed in 6.5. 
No ticket.

Fix QML errors

---

src/apps/vpn/daemon/daemon.cpp
src/apps/vpn/daemon/daemon.h
src/apps/vpn/platforms/windows/daemon/windowsdaemon.cpp
src/apps/vpn/platforms/windows/daemon/wireguardutilswindows.cpp

Right now, if `bool Daemon::activate` was called and fails, it will return false. 
This function during execution does change the system state: Device Statuses, Routing Tables, Firewall rules etc, so just aborting can introduce unwanted side effects. 
This pr adds a scope guard that unless we deactivate it (after a successful run) will emit a signal that we can use to roll back any transactional state. 
I'm using that to make sure the windows firewall rules cannot be active if the activation was not successful, that will address VPN-4253. 
We might want to consider rolling back other part's but i'm not that confident in the daemon space to make suggestions. :D

VPN-4253: Give Daemon::activate a failure signal

---

taskcluster/ci/build/android.yml
taskcluster/scripts/build/android_build_release.sh

We are building 6x the Android Client - yet most of those builds are unused or checking the same thing. 
So let's trim the task's we are creating :)  
- Remove Android-Armv-7 Next ( never been used )
- Remove unused debug-intel builds
- Reduce the 'next' builds to only main (not critical if they break)
- Build a fake release build on pr's (so we know main does not explode)

Nit: Reduce Android builds created for PRs

---

nebula/ui/components/MZSettingsToggle.qml
nebula/ui/components/MZTabNavigation.qml

* Fix 'TypeError: Cannot read property 'x' of null (MZTabNavigation.qml:105)'
* Fix 'TypeError: Property 'styleFont'...'
Cherry-picking #7156 to release branch

Fix QML errors (#7156)

---

CMakeLists.txt
glean/CMakeLists.txt

At present, the VPN client fails to build on Qt 6.4 and beyond. This seems to be due to a few issues:
- Plugins are now compiled as frameworks.
- Qt 6.5 now has policies, and generates warnings if left unset.
- Qt 6.5 requires a MacOS deployment target of 10.15 or later.
Github issue: #7155 ([VPN-4980](https://mozilla-hub.atlassian.net/browse/VPN-4980))
[VPN-4980]: https://mozilla-hub.atlassian.net/browse/VPN-4980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4980: Fix build on Qt 6.4+

---

addons/message_update_v2.16/enable.js
addons/message_update_v2.16/manifest.json

- Update strings for 2.16 update message for Windows clients on 2.10-2.12 who need to upgrade via web
[VPN-4881: Implement 'What's New' and 'Update' message for 2.16](https://mozilla-hub.atlassian.net/browse/VPN-4881)

VPN-4881: Fix 2.16 update message for old windows clients

---

src/apps/vpn/ui/screens/ScreenInitialize.qml

Fixes `Warning: qrc:/ui/screens/ScreenInitialize.qml:18: ReferenceError: MZNavigator is not defined (ScreenInitialize.qml:18)`
- The client crashes on this error when running a debug build on my iPhone (14 Pro). 
- The client does not crash here when running the same build in an iPhone 14 Pro simulator. 
VPN-5026

VPN-5026: Fix reference error in ScreenInitialize.qml

---

taskcluster/ci/beetmover/kind.yml
taskcluster/mozillavpn_taskgraph/transforms/beetmover_mac_upstream.py
taskcluster/mozillavpn_taskgraph/transforms/signing.py
taskcluster/mozillavpn_taskgraph/worker_types.py

Switches singing task behavior to only sign
Beetmover now uses notarization task as upstream dependency if possible
Cherry-picks #7063 to release branch

Bug 1774273 - Part (2/2) - Use notarization task in graph (#7063)

---

docs/dev-setup/ios.md
env.yml
scripts/cmake/golang.cmake
scripts/macos/conda_setup_qt.sh

On Windows + Android we have a `conda-setup-qt.sh` that will download and setup qt for the current env. 
Since i'm too lazy to remember where qt-lives for every platform i like to have that setuped. 
- This does download + install QT of the .env's qt-version. 
- Add's activation scripts to set `QT_HOST_PATH` -> (so we can conda-pack the env for xcode-cloud) 
- add's a `qt-cmake` helper wrapper script that calls `<Qt unzipped path>/6.2.4/ios/bin/qt-cmake -S . -B build-ios -GXcode -DQT_HOST_PATH=<Qt unzipped path>/6.2.4/macos`, so i don't need to care about that.

QOL: Conda/iOS - Auto Qt setup

---

src/apps/vpn/platforms/windows/daemon/windowstunnelservice.cpp
src/apps/vpn/platforms/windows/daemon/windowstunnelservice.h
src/shared/platforms/windows/windowsutils.cpp
src/shared/platforms/windows/windowsutils.h

In a recent ticket ([VPN-4754](https://mozilla-hub.atlassian.net/browse/VPN-4754)/#6868) we are finding that the wireguard tunnel is exiting with a status of `ERROR_SERVICE_SPECIFIC_ERROR` which means that the wireguard tunnel itself detected a problem and refused to launch. However, the meaning of that error message is not printed to the logs because we ignore the value of `dwServiceSpecificExitCode`
This PR should update the error messaging to handle this exit condition correctly. While it does not fix the issue for this user, it should enable us to get better debug the next time it happens.
Github issue #6868 ([VPN-4754](https://mozilla-hub.atlassian.net/browse/VPN-4754))
[VPN-4754]: https://mozilla-hub.atlassian.net/browse/VPN-4754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

Chore: Better logging of tunnel launch errors

---

nebula/ui/components/MZCheckBoxRow.qml
nebula/ui/components/MZHeadline.qml
nebula/ui/components/MZSubtitle.qml
nebula/ui/components/MZTextBlock.qml
nebula/ui/components/inAppAuth/MZInAppAuthenticationBase.qml
nebula/ui/components/inAppAuth/MZInAppAuthenticationInputs.qml
nebula/ui/components/navigationBar/MZBottomNavigationBar.qml
src/apps/vpn/ui/authenticationInApp/ViewAuthenticationSignUp.qml
src/apps/vpn/ui/screens/ScreenPostAuthentication.qml
src/apps/vpn/ui/screens/getHelp/contactUs/ViewContactUsForm.qml
src/apps/vpn/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml
src/apps/vpn/ui/screens/messaging/ViewMessage.qml
src/apps/vpn/ui/screens/settings/ViewAboutUs.qml
src/apps/vpn/ui/screens/settings/ViewLanguage.qml
src/apps/vpn/ui/screens/settings/ViewPrivacy.qml
src/apps/vpn/ui/screens/settings/ViewSubscriptionManagement/SubscriptionManagementItem.qml
src/apps/vpn/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml

- Fix various layout issues so that UI is no longer clumped together
- Fix `MZBottomNavigationBar` drop shadow
\* Did not check every aspect of the UI, but this should at least cover the most common screens
\* Tested fixes on Qt 6.4.3 and spot checked Qt 6.2.4 and Qt 6.5.1 to ensure all UI's appear visibly intact
Main Ticket: 
- [VPN-4913: Investigate and fix QML layout issues in Qt 6.4.3](https://mozilla-hub.atlassian.net/browse/VPN-4913)
Related Tickets:
- [VPN-4494: Mozilla VPN multiple screens have layout issues on Linux (Ubuntu 23.04)](https://mozilla-hub.atlassian.net/browse/VPN-4494)
- [VPN-4499: [Linux] Some of the Developer options are not available](https://mozilla-hub.atlassian.net/browse/VPN-4499)
- [VPN-2986: Rendering issues with qt6.4 on …

VPN-4913: Fix various UI issues with Qt 6.4

---

src/apps/vpn/ui/screens/ScreenTelemetryPolicy.qml

Allows the wrapping of the privacy policy link on `ScreenTelemetryPolicy`
VPN-5051

Fix VPN-5051 - Wrap privacy policy link

---

src/apps/vpn/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml

Turn off the use of a staging server if a server address is not specified. Otherwise the next startup code path will assert that the server address is non-null when a staging server is set, and the assert will crash the app in a debug build.
The assert is in `AppConstants::setStaging`:
`Q_ASSERT(!s_stagingServerAddress.isEmpty());`
After this change, the 'Use Staging Servers' checkbox in the Developer Options page will be automatically unchecked if the server address field is made empty.
GitHub issue [6478](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/6478), [VPN-4456](https://mozilla-hub.atlassian.net/browse/VPN-4456)
[VPN-4456]: https://mozilla-hub.atlassian.net/browse/VPN-4456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4456: Don't use staging server if a server address is not specified

---

src/apps/vpn/ui/authenticationInApp/ViewAuthenticationSignIn.qml
src/apps/vpn/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml

- Fixes layout issues in the "password confirmation" and "TOTP confirmation" pages in the re-auth flow for Qt 6.4
| <img width="428" alt="Screenshot 2023-06-29 at 6 35 40 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/b8821049-0f1e-46df-b4a1-ac132e671a85"> | <img width="472" alt="Screenshot 2023-06-29 at 6 36 18 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/c67cab24-3995-4866-9d11-5aa0f03866df"> |
| <img width="472" alt="Screenshot 2023-06-29 at 6 35 48 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/7f713437-f040-40d8-9647-9cf9925ad144"> | <img width="472" alt="Screenshot 2023-06-29 at 6 36 25 PM" …

VPN-5143: Fix re-auth page layout

---

.github/workflows/ppa-automation.yaml

We rely on the PPA automation workflow a little more than we would like to admit as a part of our Linux release process, and as such, when the job fails to run (eg: to produce a dot release when a later RC already exist), this tends to cause a lot of pain for release engineering. As such, we should try our best to make sure that the workflow always produces its artifacts, even if `dput` fails for some reason.
To achieve this, we need to ensure that the `for` loop tries to upload for all distributions (even if one of them fails) and that we always upload the github workflow artifacts.
Github issue: #7119 ([VPN-4958](https://mozilla-hub.atlassian.net/browse/VPN-4958))
[VPN-4958]: https://mozilla-hub.atlassian.net/browse/VPN-4958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …

Chore: Upload PPA workflow artifacts, even if dput fails.

---

taskcluster/ci/build/macos.yml
taskcluster/ci/fetch/kind.yml

Due to us updating x-code it seems 
```
toolchain: qt-mac
```
is broken. We want to upgrade qt anyway in 2.17. 
So for 2.16 let's fetch & use the toolchain artifact used in 2.15.1

[2.16] - Pin Qt Toolchain artifact

---

scripts/utils/generate_ts.sh

Per conversation in Slack: the `2.15.0` and `2.15.1` branches were removed yesterday from this repository. That means that thousands of translations were removed from the l10n repository (won't link the PR, as it's large enough to make Firefox stall).
Reintroducing these branches exposes about 150 strings for translation, and that's not something we can afford (we can't recover previous translations). We also can't stop translating until these branches are removed again, so I'm skipping them in the generation process.
I will file an issue to make sure we remove them once there are no more `2.15.*` branches in the repository.

Ignore 2.15.* branches when extracting strings

---

taskcluster/ci/config.yml
taskcluster/mozillavpn_taskgraph/actions/release_promotion.py

Release promotion reuses tasks generated by the on-push decision task, to
avoid duplicating work.  For cached tasks however, that means reusing
index lookups that can be out of date by the time relpro runs, and
requiring a new push to pick up rebuilt cached tasks.  By listing the
cached kinds in rebuild-kinds, we force new index lookups at release
promotion time, to pick up e.g. new docker images without an extra push.
https://bugzilla.mozilla.org/show_bug.cgi?id=1835689

Bug 1835689 - don't include cached tasks in existing_tasks for release promotion

---

scripts/cmake/osxtools.cmake
scripts/macos/conda_setup_qt.sh
src/apps/vpn/cmake/macos.cmake

@oskirby - We've talked about considering using qt-prebuilds from the online installer. Given the Qt-Toolchain is busted, i thought i experiment with this just as an option :) 
This PR add's a check, that if the app is not build using a static version of QT, it will invoke macdeployqt. This will copy all dependencies we have into the `.app` bundle.

Nit: Support deployment of online-installer qt

---

src/apps/vpn/ui/screens/home/controller/connectionInfo/ConnectionInfoScreen.qml

It does not make sense to restart the speedtest when you are not connected to the VPN. I would suggest hiding the restart button so you cannot enter an invalid state.
https://mozilla-hub.atlassian.net/browse/VPN-4238
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/1068037/661f30cf-bc05-45b1-92fd-fcd679154576

VPN-4238 Hide Speedtest restart button when VPN is disabled

---

scripts/linux/script.sh
scripts/utils/import_languages.py

We need to pin the i18n branch we're using for 2.15.2, which is only going to be available on Linux. I believe this does that. It:
- updates to the proper i18n commit 
- comments out the i18n update (not sure which of these two will be run, so commented out both)
While this is ugly, it's only going into the 2.15.2 branch, so I think this is okay.
https://mozilla-hub.atlassian.net/browse/VPN-5189

VPN-5189: Pin i18n submodule for 2.15.2 (Linux only)

---

.github/workflows/gh_pages.yaml
.github/workflows/test_lottie.yaml
.github/workflows/translations.yaml

AQT has been brittle a bit lately. 
Let's switch to using the normal apt-packages, like we do on the unit-test tasks.

fixing aqt download issues by using apt

---

taskcluster/ci/release-notify/kind.yml
taskcluster/mozillavpn_taskgraph/transforms/release_notify.py

Send a matrix notification to #releaseduty on successful release promotion, modeled after the existing slack notification.
https://bugzilla.mozilla.org/show_bug.cgi?id=1841849

Bug 1841849 - add matrix notifications to release promotion tasks

---

tools/wasm_chrome/generate_branch_file.ts

Recently the Wasm_Chrome workflow has been failing on Github CI due to a missing package `Octokit`. Some quick googling suggests that we are loading it from the wrong URL (see [here](https://github.com/octokit/octokit.js) for the recommended way to import it).

Chore: Fix Wasm_Chrome workflow

---

src/shared/tasks/sentry/tasksentry.h

The VPN app uses SentryAdapter to check if there was a previous crash report. If so, it schedules a TaskSentry task to show the Crash Reporting screen, to get user consent and send the crash to Sentry. If 'Connect VPN on Startup' was set in App Preferences, the TaskSentry task was deleted when a high priority event like VPN tunnel activation occurred during app startup. Prevent this by changing TaskSentry's DeletePolicy to Reschedulable, so that TaskScheduler reschedules it after a high priority event, instead of deleting it.
GitHub issue [6943](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/6943), [VPN-4832](https://mozilla-hub.atlassian.net/browse/VPN-4832)
[VPN-4832]: https://mozilla-hub.atlassian.net/browse/VPN-4832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

VPN-4832: Prevent task that shows Crash Reporting Screen from being canceled

---

android/common/src/main/java/org/mozilla/firefox/qt/common/Utils.kt
android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNUtils.kt
src/shared/platforms/android/androidcommons.cpp

This is just a cherry-pick, it's been verified by QA in the release branch already and all. Sorry for the backwards workflow.

VPN-5049 - Move sharePlainText back to VPNUtils (#7460)

---

taskcluster/ci/build/windows.yml

Removes unused and failing `clang-cl` from the release branch.
VPN-5227

Remove build-windows/clang-cl from release CI

---

.github/dependabot.yml

We get quite a **lot** of dependabot updates. 
The flood of updates in `/tools` does quite overshadow the amount of updates we get from actual client code. 
Given nothing in `tools` is shipped to users, has no test coverage and is essentially only for us - we only risk breaking our workflows, and flooding important dependencies updates in a sea of small node tools. 
Note: this does not disable dependabot dependency-security reporting

Chore, pause dependabot for /tools

---

src/shared/tasks/sentry/tasksentry.cpp

Small nit: right now we only record the event id. This makes lookup of a sentry report possible, but you need to remember where to go. 
Let's just print the url for the report, so everony can quickly lookup what we collected.

[Sentry] Print where to find the crashreport

---

src/apps/vpn/platforms/ios/ioscontroller.swift
src/apps/vpn/platforms/ios/iostunnel.swift
src/apps/vpn/telemetry/metrics.yaml

This is the iOS-side work for VPN-4038. A separate PR will be put up for Android.
This adds in the iOS network extension metrics. 
Additionally, `activationAttemptId` was no longer sent to `startTunnel` as an option, and so we had an erroneous log line regarding the source of the VPN activation. This bug was filed as https://mozilla-hub.atlassian.net/browse/VPN-5053, and is fixed here.
To test this, at the end of the `init` of `iostunnel.swift`, add one or both of these lines:
```
Glean.shared.setDebugViewTag("VPNTest") // if you want to check in the Glean debug pings viewer
Glean.shared.setLogPings(true) // if you want to test in app logs
```
https://mozilla-hub.atlassian.net/browse/VPN-4038

VPN-4038: Add metrics to daemon

---

nebula/ui/components/forms/MZTextField.qml

VPN client crashes if we enter a special character in various keyboards such as Czech and German on OSX only due to the check `if (Qt.platform.os === "osx")` here. This change was causing an infinite loop when QT autocompletes the special character, causing a crash.
https://mozilla-hub.atlassian.net/browse/VPN-5132

[macOS]Mozilla VPN app crashes when entering specific symbols using Czech keyboard

---

src/apps/vpn/server/serverconnection.cpp

This removes the ability to deactivate the vpn via :8754. 
This can be verified by running `perl -e 'print pack("I", 18) . "{\"t\":\"deactivate\"}"' | nc -v 127.0.0.1 8754` which now returns `{"t":"invalidRequest"}`. 
VPN-5008

VPN-5008 Remove ability to deactivate connection via web extension

---

linux/debian/mozillavpn.postinst
linux/debian/mozillavpn.postrm
linux/debian/mozillavpn.preinst

It seems that when we create a custom Debian package maintainer script, it replaces the automatically generated scripts via debhelper. However, we can restore the intended debhelper behavior by adding the subsitution expression `#DEBHELPER#` back into the script. See [here](https://manpages.debian.org/testing/debhelper/dh_installdeb.1.en.html) from some breadcrumbs on the maintainer script substitution.
Github issue #7403 ([VPN-5159](https://mozilla-hub.atlassian.net/browse/VPN-5159))
Github issue #7404 ([VPN-5160](https://mozilla-hub.atlassian.net/browse/VPN-5160))
[VPN-5159]: https://mozilla-hub.atlassian.net/browse/VPN-5159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-5160]: …

VPN-5159/5160: Fix systemd service launch on installation

---

nebula/ui/components/forms/MZTextArea.qml

Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7558 to release 2.16.
https://mozilla-hub.atlassian.net/browse/VPN-5132

VPN-5132 [macOS] Mozilla VPN app crashes when entering specific symbols using Czech keyboard

---

src/apps/vpn/connectionhealth.cpp
src/apps/vpn/dnspingsender.cpp
src/apps/vpn/dnspingsender.h

I believe the issue described in VPN-4933 was happening due to the UDP socket going into an error state after the application goes inactive, either by being backgrounded or by putting the device to sleep. That error state plus a bug in Qt's code that leads to an infinite retry loop for the kernal call `sendmsg` was causing the crash.
Going back to the VPN app. In the very specific case of 
1. Turning the VPN on, through the UI
2. Going inactive
3. Turning the VPN off, through the UI
The UDP socket would go into an error state, which could be fixed by a restart of the socket. The error state would cause every call to `writeDatagram` to result in a `NetworkError`. It's important context that `NetworkError` is [the fallback error type for …

VPN-4933 - Stop DNSPingSender's UDP socket on idle

---

src/apps/vpn/controller.cpp
src/apps/vpn/controller.h
src/apps/vpn/telemetry.cpp

We were sending an extra set of connection start pings when the mobile apps launched with an already-active VPN. This fixes the bug. See detailed diagnosis on the ticket.
To test, you'll need to add a line like `Glean.shared.setDebugViewTag("MattVPN")` in `iosgleanbridge.swift` after Glean is initialized (or before, I don't believe it matters). Alternatively, you could rely on an environment variable to test this, but then you must be sure to re-launch the app from xcode, and not on the device (as the re-run on the device won't have the environment var).
https://mozilla-hub.atlassian.net/browse/VPN-5222

VPN-5222: Fix signal for VPN connection metrics on iOS/Android

---

src/apps/vpn/platforms/ios/iostunnelmanager.swift

When the [IOSTunnelManager was added](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7085/), I talked with Bea about putting up a follow up PR to refactor it to be a bit more Swift-y. 
This PR:
- Removes a bunch of force unwraps
- Makes it a bit more Swift-y with optional chaining, additional guard checks, etc.
- Removes some unnecessary small things (semicolons, the `get` in the computed vars, the return in front of completion handler)
- It removes a fatal error. The caller deals with the lack of tunnel when an error is returned, so we don't need to crash the app - the caller can deal with this. 
- I didn't see where the failure state for the tunnel was ever used, so I removed it to simplify.
I considered removing the `withTunnel` function, but decided to save that for another …

Refactor some Swift in iOS Tunnel Manager

---

android/AndroidManifest.xml

We are not using http anywhere, this was probably added so people 
can run against custom guardian instances :)

VPN-5012 enforce https

---

docs/rfcs/0002-session-id-sharing.md

One of the main concerns that prompted this RFC, was the concern on how to keep the identifiers in sync between main application and daemon and how to know if they are not in sync. 
I believe the first concern is addressed by the design itself and the second concern doesn't seem like a plausible scenario given the design. I am adding this note as a call for the reviewers  close attention to the synchronization aspect of the proposed solution. Thanks!

[RFC] VPN-4736 - Sharing a session identifier between app and daemon

---

src/apps/vpn/appsettingslist.h
src/apps/vpn/controller.cpp
src/apps/vpn/interfaceconfig.h
src/apps/vpn/mozillavpn.cpp
src/apps/vpn/mozillavpn.h
src/apps/vpn/platforms/ios/ioscontroller.mm
src/apps/vpn/platforms/ios/ioscontroller.swift
src/apps/vpn/platforms/ios/iostunnel.swift
src/apps/vpn/telemetry/metrics.yaml

Android work will come in a separate PR.
To test, you likely want to add a debug tag (`Glean.shared.setDebugViewTag("VPNTest")`) after the two Glean initialization calls in Swift. Then, look at the pings [in Glean's tool](https://debug-ping-preview.firebaseapp.com/pings/VPNTest).
https://mozilla-hub.atlassian.net/browse/VPN-4712
https://mozilla-hub.atlassian.net/wiki/spaces/SECPRV/pages/184419319/VPN+session+pings+-+Tech+spec

VPN-4712: add installation ID for iOS

---

addons/CMakeLists.txt
addons/validate.cpp

It seems sometimes the addons may pass all of our linting scripts and still generate invalid resources. Or maybe it's the rcc generation script that may sometimes fail.
I do not address the failure here, because locally my builds just work so I am guessing this will be fixed by a rebuild. But if I download the RCC files in https://mozilla-mobile.github.io/mozilla-vpn-client/addons/ it fails when it gets to the problematic addons described in VNP-5215... so at least we are preventing against that guess???
This is the output against the staging addons:
```
Generated resource file "/Users/beatrizrizental/Library/Application Support/Mozilla VPN/addons/guide_01_how_to_vpn.rcc" is valid.
Generated resource file "/Users/beatrizrizental/Library/Application Support/Mozilla …
```

VPN-5215 - Test generated addons are valid

---

nebula/ui/components/MZCollapsibleCard.qml
src/apps/vpn/ui/screens/settings/appPermissions/AppPermissionsList.qml
src/apps/vpn/ui/screens/settings/appPermissions/ViewAppPermissions.qml

- Fix layout for app permissions view and collapsible card components on Qt 6.4
| <img width="472" alt="Screenshot 2023-07-27 at 2 42 52 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/e56b6a57-4efc-456b-aea5-094cb864a067"> | <img width="472" alt="Screenshot 2023-07-27 at 2 41 53 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/7daa7ed4-0e0e-4e7f-aba4-f244cbe68ee8"> |
| <img width="472" alt="Screenshot 2023-07-27 at 2 42 30 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/9e64f0d0-3c69-4b0f-b58e-c117ec23ee3e"> | <img width="472" alt="Screenshot 2023-07-27 at 2 41 41 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/f0aaa379 …

VPN-5275: Fix app permissions and collapsible card layouts

---

addons/message_update_v2.16/manifest.json

This is the partner to https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7606. It should revert that change.
Now that addons have been released to prod, we want to re-enable this message.
N/A

Enable upgrade message

---

src/apps/vpn/models/recommendedlocationmodel.cpp
src/apps/vpn/models/recommendedlocationmodel.h
src/apps/vpn/models/servercountrymodel.cpp
src/apps/vpn/ui/screens/home/ViewServers.qml
tests/dummyvpn/CMakeLists.txt
tests/unit/testmodels.cpp

I'm hunting the `QJSEngine::qt_metacall Segfault`
We now have a [QML trace:](
https://mozilla.sentry.io/discover/vpn-client:22dd932716d94b8b6a08d705d1b262d5/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=release&homepage=true&name=All+Events&project=4504197915607040&query=release%3A2.16.0&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29)
it's crashing at: 
```
0: {column: -1, function: expression for score, line: 242, source: qrc:/ui/screens/home/servers/ServerList.qml}, 
```
So it's the an evaluated binding on `VPNRecommendedLocationModel`.
My current hunch, given that just before in the logs we can see the client fetched new servers`(ServerCountryModel) Debug: Reading from JSON`. 
So if the ServerCountryModel, calls `m_cities.clear()` - …

VPN-4974 - Do not Store raw Pointers of ServerCountryModel

---

src/shared/sentry/sentryadapter.cpp
src/shared/sentry/sentryadapter.h

Sentry Native is not making a difference between Mobile OS'ses and Desktop: 
So Android and Linux are reported as Linux
Macos is "macOS" and iOS is Darwin 😅.
This PR add's a new tag, splitting this by `MZ_Platform`, making sure we can [quickly sort those](field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=4504197915607040&query=platform%3A"MacOS"&sort=-timestamp&statsPeriod=14d&yAxis=count()) :)

Sentry-Nit: Report Proper Plattform

---

.github/scripts/get_unreleased_branches.ps1
.github/workflows/i18n_update.yaml

On Main we already have a workflow that daily pulls in the newest language-submodule.
This PR add's a bit of automation to do that too for every branch in `release/*`that has no Github Release or Release Draft present. 
We want to get rid of: 
```
for i in src/apps/*/translations/i18n; do
git submodule update --remote $i
```
Because that makes it impossible to trace what commit has been built with which language and  makes it impossible for the CI to build an older release, once the strings have been removed on the head of the strings repo. Which i just may have caused 😓 
Example Run 1: 
https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/5475097381
Created PR: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7439
Example Run before i added 2.15.2 as a draft: (note …

i18n Update-Automation for Release branches 

---

src/apps/vpn/command.cpp
src/apps/vpn/models/device.cpp
src/apps/vpn/platforms/android/androidutils.cpp
src/apps/vpn/platforms/android/androidutils.h
src/apps/vpn/ui/screens/initialize/ViewInitialize.qml

So i was pretty sure this is not a "Mozilla VPN issue" but i was supposed to look into that. So i did. 
```
SIGSEGV: Segfault
?, in rx::vk::ImageViewHelper::getLevelLayerDrawImageView
```
The segfault is actually not much to go after. The only online content i found related to that is us and ... chrome. 
Also this is actually in a system library, so something out of our control is going wrong. 
However, looking at google-play, we can clearly see the only devices encountering this crash are ChromeOS tablet's with mediatec chips... So maybe it's their driver? ( Also it would be neat if sentry told me that 😅  ) 
For my smol experiment, we can simply detect chrome-os android-vm's and put them into software rendering. If i am correct, this should stop that from happening :) 
i also added a …

VPN-5027 - Disable Hardware rendering in ChromeOS vm's

---

nebula/ui/themes/main/theme.js
src/apps/vpn/ui/screens/devices/VPNDeviceList.qml
src/apps/vpn/ui/screens/devices/ViewDevices.qml

- "Edit" button "enabled" state in devices view is now bound to active device count, so that if a second device is added or all devices (excluding the current device) are removed, the "Edit" button will enable/disable accordingly (without the need to reload the view)
- "Edit" / "Done" label text now updates to the correct state when a device is added/removed from the list by signing in/out from another device (without the need to reload the view)
-  Fix the Red Button theme to match the design system (it is now more accessible with better contrast)
[VPN-5305: The “Edit” button from My devices screen remains disabled when new device is added](https://mozilla-hub.atlassian.net/browse/VPN-5305)

VPN-5305: Fix edit button in devices view

---

src/shared/featurelist.h
src/shared/featurelistcallback.h

VPN-5246's crash is caused by Sentry on iOS. Sentry creates Android and iOS specific SDKs, but we’re using the native (C/C++) one for all platforms. It seems like this Sentry native SDK [explicitly includes Qt support](https://docs.sentry.io/platforms/native/guides/qt/). However, from that documentation: `The Qt integration is part of the sentry-native SDK, which currently supports Windows, macOS, Linux, and Android.` Additionally, in the sentry-[native SDK readme](https://github.com/getsentry/sentry-native/#platform-and-feature-support), iOS support is nowhere to be found.
Thus, I believe we should not include use the Sentry native SDK on iOS. Per discussion on the ticket, we're feature flagging this for now so we can investigate this further. I've also added a new ticket to re-add …

VPN-5246 - Turn off Sentry for iOS to prevent crashes

---

src/shared/featurelist.h
src/shared/featurelistcallback.h

Uplift https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7679 to 2.16.1. 
iOS is not getting the 2.16.0 release; we're holding the iOS release on this cherry pick. Once merged, we'll roll out 2.16.1 to iOS.

Uplift PR #7679 to 2.16.1 release branch (VPN-5246 - Turn off sentry for iOS)

---

src/apps/vpn/ui/screens/devices/VPNDeviceListItem.qml

- Elide device name and subtitle after 1 line
| ![image](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/61a4cd88-ec6c-4ef9-97b7-ce24ba98dc2a) | ![image](https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/0e9ca000-06e9-4894-8501-81ad409fe9c5) |
[VPN-5328: Long device name is not wrapped in “My devices” screen](https://mozilla-hub.atlassian.net/browse/VPN-5328)

VPN-5328: Fix device list item text layout

---

src/apps/vpn/connectionhealth.cpp

https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7512/ introduced a bug, where the health check timers were not restarted when reentering the iOS client. 
(For instance, swipe into control center with the VPN active, turn off internet, back into app, and it should show no connectivity within 4 seconds.)
We realize there is no connectivity when a health check timer goes off, and we have not received a reply ping. #7512 changed from calling `startActive` (which restarts the timers) to calling `connectionStateChanged`. Within `connectionStateChanged`, this block of code is executed (when the VPN is on):
```
MozillaVPN::instance()->controller()->getStatus(
[this](const QString& serverIpv4Gateway,
const QString& deviceIpv4Address, uint64_t txBytes,
uint64_t rxBytes) { …
```

VPN-5321 - Connection fix

---

nebula/ui/components/CMakeLists.txt
nebula/ui/components/MZStepNavigation.qml
nebula/ui/components/MZStepProgressBar.qml
nebula/ui/components/MZStepProgressBarDelegate.qml
src/apps/vpn/ui/screens/getHelp/developerMenu/ViewUiTesting.qml

- Create a navigation component that utilizes `MZStepProgressBar`
- `MZStepNavigation` is a navigation component(similar to [MZSegmentedNavigation](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/acfa3dc5684913a021988e9c340802517b6e1a75/nebula/ui/components/MZSegmentedNavigation.qml#L4) and [MZTabNavigation](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/nebula/ui/components/MZTabNavigation.qml)) comprised of an [MZStepProgressBar](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/acfa3dc5684913a021988e9c340802517b6e1a75/nebula/ui/components/MZStepProgressBar.qml#L4) in which each step corresponds to a view. 
- Views reside within a `StackView`, and as the navigation progresses, new views are pushed on top of the previous views
Notes: 
- Glitchy when used …

VPN-5147: Create MZStepNavigation nebula component

---

qtglean/Cargo.lock
qtglean/src/lib.rs

Updates Glean to 53.2.0, using the v53.2.0 tag.
Android still uses the glean submodule. The Glean Gradle Plugin for Android is about pulling the latest metrics/pings in the build. Since updating the glean gradle plugin was what was having issues on my machine (but not other people's machines), we’re just updating the Glean repo for now.
https://mozilla-hub.atlassian.net/browse/VPN-5323

VPN-5323: Update Glean to 53.2.0

---

src/apps/vpn/platforms/windows/windowsnetworkwatcher.cpp
src/apps/vpn/platforms/windows/windowspingsender.cpp

Improve Windows error logging in some connectivity-related classes:
1. The WLAN notification callback indicated that it was MSM disconnected despite being connected and receiving notification codes like wlan_notification_msm_radio_state_change, wlan_notification_msm_signal_quality_change,  indicating state changes while still remaining connected.  Fixed by logging the actual notification code.
2. WindowsPingSender did not log the error code.  The returned error code might correspond to an IP_* status code, potentially leading to value conflicts with actual error codes. For instance, the value 11006 is shared by WSA_QOS_SENDERS and IP_NO_RESOURCES, and the error message from FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM) corresponds to WSA_QOS_SENDERS. Improved this by logging the error code.

Chore: Improve connectivity-related error logging in Windows

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
src/apps/vpn/platforms/android/androidcontroller.cpp
src/shared/glean/mzglean.cpp

iOS partner work done in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7581. This adds the Android daemon work.
Additionally, I realized that there was a bug when users removed Glean permissions - Glean would automatically clear the installation ID, but it wasn't cleared from settings. Then, if a user reactivated Glean permissions, the app Glean would report no installation ID but the daemon Glean would report the old installation ID - which would have allowed their old and new sessions to be linked, which we definitely do not want. I've added some code to fix that bug.
To test, you likely want to add these lines before the two instances of `Glean.initialize(`:
```
Glean.setDebugViewTag("VPNTest")
Glean.setLogPings(true)
```   
Then, look at the pings [in Glean's …

VPN-4712: Add installation ID on Android daemon

---

src/apps/vpn/ui/screens/home/servers/ServerList.qml

See also 🔗 https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7745
We are loading both the "recomended" part and the whole list - which consumes time and actually makes them both navigateable from talkback. 
Let's unload the part that we don't want to show

QML Perf: Single-Hop - only load the current selected tab

---

android/AndroidManifest.xml

We have introduced this for our filtered adjust - campain attribution. At v2.3
However we have not used that in 1+ years, so let's remove the permission, we can re-introduce at anytime if we ever need it.

Remove Usage of Ad-ID

---

nebula/ui/components/MZRadioDelegate.qml
nebula/ui/components/MZStackView.qml
nebula/ui/components/MZTabNavigation.qml
nebula/ui/components/navigator/MZNavigatorLoader.qml
src/apps/vpn/ui/screens/home/ViewServers.qml
src/apps/vpn/ui/screens/home/servers/ServerCountry.qml
src/apps/vpn/ui/screens/home/servers/ServerList.qml

The ViewServers tabs (Recommended and All) did not have accessible names. Fixed by providing names in ViewServers.qml.
Some parent elements had names which were not useful, so have been marked as ignored.
[VPN-4831](https://mozilla-hub.atlassian.net/browse/VPN-4831)
[VPN-4831]: https://mozilla-hub.atlassian.net/browse/VPN-4831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4831: Set Accessibility names of ViewServers tabs and fix other Select Location a11y issues

---

src/apps/vpn/mozillavpn.cpp
src/shared/sentry/sentryadapter.cpp
src/shared/sentry/sentryadapter.h
src/shared/tasks/sentry/tasksentry.cpp

I've been looking why we have so many "Abnormal" sessions in sentry and so little healthy ones. 
Problem is, session_end will attempt to send a request, if that fails we're abnormal. 
So let's try to do that immediatly instead of scheudling a new task. So we have better channces to get that out. 
This also makes the crash report screen pop instantly, which also is nice c:

Chore - Schedule Sentry Tasks instantly

---

.github/workflows/release.yaml

Sentry does not parse versions, but orders them by "newest" seen. 
This is annoying, because if we do a dot release, the timeline is fucked. 
And that ruin's regressions, i.e i mark a bug solved in 2.17 - it will instantly pop up again because sentry thinks 2.15.1 is newer .___. 
So let's mark a release as "done" whenever we publish them on gh, that will make sure the order is correct... or at least the same as our gh releases :)

NIT: Finalize Sentry release on GH Release step

---

env.yml
taskcluster/ci/fetch/kind.yml
taskcluster/ci/toolchain/qt.yml
taskcluster/scripts/toolchain/bundle_qt_ios.sh

This reverts commit 412add0f6ab90d4961d983c3a33bd2ec4a6e8935, which was PR https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7604/
1. macOS unit tests are failing on 6.5.1 ([Jira](https://mozilla-hub.atlassian.net/browse/VPN-5460)), currently blocking all PRs. 
2. Due to [a bug in our build system](https://mozilla-hub.atlassian.net/browse/VPN-5461), PRs changing the Qt version are tested with the existing Qt version, which is why this wasn't caught in tests on the PR.
3. A corollary of number 2: We expect the macOS unit tests to be failing on this PR, and we'll need to merge this in anyway.
https://mozilla-hub.atlassian.net/browse/VPN-5462

Revert Qt back to 6.2.4

---

src/shared/featurelistcallback.h

This PR enables Sentry crash reports on iOS in Staging. Opening as Draft until we have confirmation this has not broken anyone's ability to build in an emulator. 
Because iOS is not listed as an officially supported platform in the [Sentry SDK docs](https://docs.sentry.io/platforms/native/#install) we are enabling this only in Staging in the interest of easier crash debugging and to watch for any undesirable/unexpected behavior.
@MattLichtenstein @mcleinman When you can, mind taking this branch for a spin in the ios emulator of your choice? Sentry was reportedly breaking emulator builds at some point in recent history but so far this is 'working on my machine' and I want to make sure this doesn't cause any grief on your ends.  
VPN-5324

Enable Sentry on iOS in Staging

---

src/apps/vpn/connectionbenchmark/connectionbenchmark.cpp
src/apps/vpn/connectionbenchmark/connectionbenchmark.h
tests/functional/testBenchmark.js

Per comment on VPN-5321, the original work neglected to catch if the connection was already gone (but the VPN tunnel was active) when the user started their speed test.
https://mozilla-hub.atlassian.net/browse/VPN-5321

VPN-5321 follow up - show error screen if no connection at start of speed test

---

macos/pkg/Distribution

We've been publishing a universal binary since 2.16 - However we totally forgot to update the installer.  This still causes rosetta to be prompted, even though it's not needed anymore q_q (See https://github.com/mozilla-mobile/mozilla-vpn-client/issues/286#issuecomment-1703937187) 
According to the docs [here](https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW7) we need to mark the cpu_arches our pkg supports. And according to [this blog post](https://scriptingosx.com/2020/12/platform-support-in-macos-installer-packages-pkg/), we can add arm :)

VPN-5473 Mark the Macos PKG as universal

---

ci_scripts/ci_post_clone.sh

This work was done for Taskcluster here: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7889/
However, our Xcode Cloud build system is different from TaskCluster, so this PR fixes it for XCode Cloud.
Xcode Cloud builds have failed for the last several days; they should work after this is merged.

Pin Qt version used by Xcode Cloud

---

ci_scripts/ci_post_clone.sh

Follow up to https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7917
I, ummm, used the wrong version for pinning. I pinned it to a Qt 6.5.1 run. This is now pinning it to 6.2.4.

Fix version for Qt pinning

---

tools/inspector/views/view-ui.js

Currently the detail sit's on a 3rd row, which might be tiny on small screens.
So let's have it float from the right, so it's visible like an overlay.
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/9611612/c817aa76-782d-4e59-b71c-850857caa2ef

Inspector Nit: Support Smol Screens

---

addons/message_update_v2.17/getHelp.js
addons/message_update_v2.17/manifest.json

- Fix `max_client_version` so that it is not a number used for local testing
- Fix `Get help` button so that it works on versions before 2.16.0
[VPN-5337: Implement 'Update' / 'Download' message for 2.17](https://mozilla-hub.atlassian.net/browse/VPN-5337)

VPN-5337: 2.17 update message fixes

---

nebula/ui/components/MZAlert.qml
nebula/ui/components/forms/MZContextualAlert.qml
src/accessiblenotification.cpp
src/accessiblenotification.h
src/cmake/sources.cmake
src/commands/commandui.cpp
src/ui/screens/home/controller/ConnectionStability.qml
src/ui/screens/home/controller/ControllerView.qml

Notify accessibility clients, like screen readers, of alert strings like "Incorrect password", "Signed out and device disconnected", so that the screen reader will read those. Also notify when connection state and health changes.
This uses the QAccessible::ValueChanged and QAccessible::updateAccessibility, which has been verified to work on Windows. Unfortunately, Qt doesn't implement this fully on other platforms. Another ticket will be opened to track investigation of potential fixes on other platforms.
[VPN-5443](https://mozilla-hub.atlassian.net/browse/VPN-5443), [GitHub 7863](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/7863)
[VPN-5443]: https://mozilla-hub.atlassian.net/browse/VPN-5443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

VPN-5443: Notify accessibility clients of alerts

---

src/platforms/linux/daemon/apptracker.cpp
src/platforms/linux/daemon/apptracker.h
src/platforms/linux/daemon/dbusservice.cpp

Currently, the split tunneling works great, but only if you launch the service sometime after the user login sessions are complete. If you let the daemon at boot (as is normally the case) then the we often detect user creation while systemd is still busy initializing things, often resulting in a failure to connect to the user's session bus because it doesn't exist yet. And without that connection to the user's session bus, we are unable to detect application launch events needed for split tunneling to work.
Unfortunately, there doesn't seem to be a signal that we can listen on to detect when the initialization is complete, so we work around the problem by polling the D-Bus user object until we get a state change out of the undocumented "opening" state.
This was also hampered by a bug in …

VPN-1990: Split tunnel boot-time fixes

---

scripts/android/cmake.sh

Apparently the step that generates the Kotlin bindings code happens earlier (i.e. on cmake build) now???

VPN-5496 - Update glean-core/uniffi.toml file earlier in Android build cycle

---

nebula/ui/components/MZAlert.qml
src/ui/screens/home/controller/ConnectionStability.qml
src/ui/screens/home/controller/ControllerView.qml

Add periods between substrings of the notification read by screen reader, to introduce pauses for better clarity.
[VPN-5443](https://mozilla-hub.atlassian.net/browse/VPN-5443), [Github 7863](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/7863)
[VPN-5443]: https://mozilla-hub.atlassian.net/browse/VPN-5443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: Add pauses between substrings of notification read by screen reader

---

src/featurelist.h

Ticket: https://mozilla-hub.atlassian.net/browse/VPN-5405
Per discussion w/ Santiago, we'll turn this on in advance of VPN-4578 being done. We'll do that testing during the QA period for 2.17. I'm leaving this as a feature flag in case we need to turn this back off.

VPN-5405: turn on super dooper

---

CMakeLists.txt

Bumping main branch to 2.18 (per release checklist), now that there is a 2.17 release branch.

version bump to 2.18

---

addons/message_update_v2.17/manifest.json
addons/message_whats_new_v2.17/manifest.json

- Content parity with main branch for the 2.17 update and what's new messages
*Note: Translations consider all branches, so even though addons are built off of `main`, these strings would still be unnecessarily translated in the `releases/2.17.0` branch if they aren't removed. 
N/A

[Uplift] Fix 2.17 messaging

---

addons/message_whats_new_v2.17/manifest.json

- Add a missing "!"
- Complete re-translation is not needed since the same string was used in [the 2.16 what's new message](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/2dabb3753f2e93313c85b24a23e001fbe9f0d192/addons/message_whats_new_v2.16/manifest.json#L23), meaning we can use translation memory
[VPN-5534: “What’s new” message content has no ending mark](https://mozilla-hub.atlassian.net/browse/VPN-5534)

VPN-5534: Fix 2.17 what's new message content

---

src/telemetry/metrics.yaml

While the [original PR had this correct](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7926/files#diff-b07fc1fd4cfa7508bc162a346e98d6c12ef6d3c30ec9bbda3c8e3fe1472b637a), the updated one [put one of the pings on the wrong metric](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7961/files#diff-b07fc1fd4cfa7508bc162a346e98d6c12ef6d3c30ec9bbda3c8e3fe1472b637a). This fixes the error in PR #7961.
After this is merged, it needs to be uplifted to 2.17.
https://mozilla-hub.atlassian.net/browse/VPN-5479?focusedCommentId=730515

VPN-5479: Fix merge

---

android/AndroidManifest.xml

Apparently we've had this since ... [forever](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/v2.0.1/android/AndroidManifest.xml#L10) ? So this is probably [a thing we just got by default from qt](https://sourcegraph.com/github.com/qt/qtbase@6.2.4/-/blob/src/corelib/CMakeLists.txt?L364) when we first generated this file. 
Just checked, the only thing we export to an external storage are the logfiles (so we can get a share intent without giving other apps access to our fs ) - that still works, given we use mediastore which does not need additional permissions, not surprising.

VPN-5540 Remove obsolete permission

---

src/cmake/msvc.cmake

[c++ hot code reloading is now a thing](https://learn.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022#visual-studio-2022-with-a-net-app-when-using-the-debugger) when using vs-studio. 
For that we need to enable "edit and continue" -> so some flags should be set when we compile `DEBUG` with msvc.
That way people can just open the project in vsstudio and it "should just work" (when you have a preset) 
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/9611612/51b356f5-629c-4670-b0eb-4aa01d95f599

Enable Visual-Studio Hot C++ Reloading :) 

---

.github/workflows/ppa-automation.yaml
taskcluster/ci/build/linux.yml
taskcluster/ci/docker-image/kind.yml

Updating the set of supported Ubuntu distributions. This adds 23.10 Mantic Minotaur which is currently in beta, and removes 22.10 Kinetic Kudu which reached EOL status on July 30th.
Ubuntu: [EOL Announcement](https://fridge.ubuntu.com/2023/06/14/ubuntu-22-10-kinetic-kudu-reaches-end-of-life-on-july-20-2023/)

Chore: Add Ubuntu/mantic and deprecate Ubuntu/kinetic

---

src/connectionbenchmark/benchmarktasktransfer.cpp

Redoing this PR to avoid rebase drama https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7844
QDnsLookup is still not supported on Android so keeping this check for now [[Qt Documentation](https://sourcegraph.com/github.com/qt/qtbase@6.5.3/-/blob/src/network/kernel/qdnslookup_android.cpp)]

Restrict check to Android only

---

src/ui/screens/tipsAndTricks/ViewTipsAndTricks.qml

- Fixes the tips and tricks layout (with tutorials removed) when built with using Qt 6.4 (often used on Linux)
| <img width="428" alt="Screenshot 2023-09-20 at 11 47 50 AM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/efd94b87-40d0-4710-9e3d-0cd1ac86bf75"> | <img width="428" alt="Screenshot 2023-09-20 at 11 47 24 AM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/6cf28c20-a1d6-4265-a32c-0cb0a75d5ae1"> |
[VPN-5567: [Linux Lunar] Tips & Tricks screen has overlapped content and is not scrollable](https://mozilla-hub.atlassian.net/browse/VPN-5567)

VPN-5567: Fix tips and tricks layout with qt 6.4

---

src/ui/screens/tipsAndTricks/ViewTipsAndTricks.qml

- Uplift changes from #8089
[VPN-5567: [Linux Lunar] Tips & Tricks screen has overlapped content and is not scrollable](https://mozilla-hub.atlassian.net/browse/VPN-5567)

[Uplift] Fix tips and tricks layout with qt 6.4 (#8089)

---

src/platforms/macos/daemon/macosroutemonitor.cpp

In MacOS, routing table entries can be scoped to a network interface, which permits the existence of multiple routes to the same prefix. However, the default-route monitor assumes that duplicate routing table entries can't exist. When multiple default routes exist, but they aren't all capable of reaching the internet it can result in a loss of VPN connectivity. Changes in these default routes can also confuse the VPN when trying to manage exclusion routing (eg: an ifscoped default route is removed, causing the VPN to think that internet connectivity is lost even if there is a second default route).
I think the correct behaviour here is to ignore routes flagged with `RTF_IFSCOPE` when monitoring the routing table.
Github issue #8088 …

VPN-5574: Ignore route changes with RTF_IFSCOPE

---

addons/message_update_v2.17/enable.js

This PR updates `message_update_v2.17` to prompt mac users on v2.16 to update via the web-based download/install flow, instead of the traditional Balrog/in-app flow. 
VPN-5587 and related VPN-5537, VPN-5538

Fix VPN-5587: Prompt web download for mac users on v2.16

---

.github/workflows/ppa-automation.yaml
taskcluster/ci/build/linux.yml
taskcluster/ci/docker-image/kind.yml

Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8038 into 2.17.0

Linux: Add Ubuntu/mantic and deprecate Ubuntu/kinetic (#8038)

---

ios/app/main.entitlements
src/connectionmanager.cpp

VPN-5400 was about a crash when the app is in the background. I fixed one crash, and then there was another crash which was identical from a user's perspective - so I fixed it too.
After this is merged, it will be uplifted to the 2.17.1 release branch.
_First crash_
This was due to Qt's handoff to QML-land, which is JS under the hood. The JS runtime is stopped pretty quick by iOS when the app is no longer foregrounded, so when the device was locked, that JS runtime didn't exist when Qt's C++ tried to hand it off to QML-land... and hence the crash.
This is a gross hacky fix. I'm open to better solutions, but after extensive testing (see ticket for details) I wasn't able to find a better way. Please let me know if you have thoughts.
I've left an explanatory comment in code to reduce risk of …

VPN-5400: Fix 2 iOS crashes

---

src/translations/strings.yaml
src/ui/authenticationInApp/ViewAuthenticationSignIn.qml
src/ui/authenticationInApp/ViewAuthenticationSignUp.qml
src/ui/deleteAccount/ViewDeleteAccountRequest.qml
src/ui/screens/ScreenSubscriptionBlocked.qml
src/ui/screens/ScreenSubscriptionExpiredError.qml
src/ui/screens/ScreenSubscriptionInUseError.qml

- Replaces all (8) in-app instances of "Firefox account" with "Mozilla account"
- `DeleteAccount.AuthSubheadline` was deleted as it is no longer used in-app
- All modified strings were given new string id's
[VPN-5117: Update account branding in mozillavpn.xliff](https://mozilla-hub.atlassian.net/browse/VPN-5117)

VPN-5117: Replace "Firefox account" with "Mozilla account"

---

src/ui/screens/onboarding/OnboardingDevicesSlide.qml

| <img width="472" alt="Screenshot 2023-10-04 at 4 55 38 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/69bf3b38-94aa-4389-afc3-ce43ab639110"> |  <img width="472" alt="Screenshot 2023-10-04 at 4 54 06 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/1a245a70-981c-459d-98b6-86d8ea3f5b93"> |
[VPN-5650:  [l10n] “Install Mozilla VPN on up to 5 devices” screen from the new onboarding flow is not wrapped in some languages](https://mozilla-hub.atlassian.net/browse/VPN-5650)

VPN-5650: Wrap "Device type" label in onboarding

---

nebula/ui/components/MZFlickable.qml
nebula/ui/components/MZSwipeAction.qml

- When navigating keyboard focus to a component that is either partially or completely off screen in the downward direction, scroll the view downward so that component is fully visible (even when the navbar is not visible)
[VPN-5559: [a11y] Some screens from the app are not scrollable when navigating via keyboard](https://mozilla-hub.atlassian.net/browse/VPN-5559)

VPN-5559: Scroll to off screen components via keyboard nav

---

src/pinghelper.cpp
src/platforms/windows/windowspingsender.cpp
src/serverlatency.cpp

Sentry reports a NULL AV in WindowsPingSender::pingEventReady around the following code, but the absence of some stack frames have made it difficult to determine the exact cause.
```
memcpy(&sequence, replies[i].Data, sizeof(quint16));
emit recvPing(sequence);
```
The pingEventReady slot  is called asynchronously when IcmpSendEcho2Ex's event has been signaled to indicate that the ping has been received. A hunch is that this event was pending in the queue when WindowsPingSender was deleted and was delivered after deletion and while the icmpCleanupHelper thread was concurrently executing. [~QObject destructor docs](https://doc.qt.io/qt-6/qobject.html#dtor.QObject) say that that all signals to the object are disconnected and pending posted events for the objects are removed from the event …

VPN-5288: Delay deletion of PingSender to avoid the risk of pending events being delivered after deletion

---

src/settingslist.h
src/ui/screens/onboarding/OnboardingPrivacySlide.qml
tests/functional/helper.js

- [Deskop only] Don't show post authentication "quick access" screen on every login when the new onboarding experience is not enabled
- Add some padding between content and buttons on privacy slide
[VPN-5660: [l10n] “Get more privacy” screen from new onboarding has no padding between the “Next” button and the description above](https://mozilla-hub.atlassian.net/browse/VPN-5660)

Miscellaneous onboarding changes

---

src/ui/screens/home/controller/connectionInfo/ConnectionInfoScreen.qml

- Prevent flickering of the connection benchmark results when closing an in-progress connection benchmark
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/600daef4-8294-4be5-8df3-fab68cbcaabf
[VPN-2859: Connection info results screen flashes when cancelling/closing a benchmark in progress](https://mozilla-hub.atlassian.net/browse/VPN-2859)

VPN-2859: Prevent connection benchmark results flicker

---

src/mozillavpn.cpp

Previously, when a user selected "Reset and Quit" from Developer Options, client settings were cleared, and the client was closed. However, the VPN tunnel was left active and used the old device public key. When the user restarted the client, they were required to re-login, resulting in the generation of a new device key.
If this new device key was not provided to the tunnel within a few minutes, the Mullvad server would drop the connection because the old key was no longer valid. This meant that if the user waited in the post-authentication UI (either the old or new onboarding UI) until Mullvad dropped the connection, the device internet would be lost. To workaround this, the user had to toggle the VPN off and then back on, to deactivate the old tunnel and to activate a new tunnel with …

VPN-5511: Deactivate VPN on hard reset and quit

---

nebula/ui/components/inAppAuth/MZInAppAuthenticationBase.qml
src/cmake/android.cmake
src/featurelist.h
src/featurelistcallback.h
src/ui/deleteAccount/ViewDeleteAccountRequest.qml

This was already implemented on iOS, so this was essentially just turning on the feature for Android. However, there were also some requests to improve the formatting and colors and spacing, so that is the bulk of this PR.
- The formatting changes: Better spacing, more consistent font sizes, blue button color for the "Cancel" button.
- Hiding elements w/ no content is to remove the additional spacing they were providing.
- The addition to `android.cmake` (`${Qt6_DIR}/../../libQt6Svg_${ANDROID_ABI}.so`) is due to a note a few lines above what I added (along with a build error I experienced): `android-deploy-qt is bad and randomly decides to not deploy some lib's we are linking to. So as long as qt is behaving bad, let's force the deployment. Feel free to add libs that are breaking on your …

VPN-5697 - Allow account deletion on Android

---

src/ui/screens/home/ViewMultiHop.qml
src/ui/screens/home/ViewServers.qml
src/ui/screens/home/servers/ServerList.qml

Some elements in the 'Select Location' screen did not have the correct Accessible names.
[VPN-5492](https://mozilla-hub.atlassian.net/browse/VPN-5492), [GitHub 7952](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/7952)
[VPN-5492]: https://mozilla-hub.atlassian.net/browse/VPN-5492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5492: Some elements in 'Select Location' screen are not read by screen reader

---

nebula/ui/components/inAppAuth/MZInAppAuthenticationBase.qml

On Android it had an extra space (per the image in the ticket). This was due to the spacing for the "change email" link. This adjustment makes it not take up space on Android. (It already this looked okay on iOS.)
https://mozilla-hub.atlassian.net/browse/VPN-5279

VPN-5279: adjust spacing

---

src/mozillavpn.cpp
src/settingslist.h
src/ui/screens/onboarding/OnboardingDataSlide.qml
tests/functional/testOnboarding.js

- Prevent data collection checkbox in onboarding from modifying internal `gleanEnabled` setting until onboarding is completed
- The reasoning for this is because we want the initial state of the checkbox to be unchecked so that no changes are necessary to be made by the user to opt out of data collection (aside from completing onboarding), but coupling this with the internal `gleanEnabled` setting would wipe all authentication telemetry for the user.
[VPN-5520: All pre-onboarding glean data being deleted upon reaching the Data Collection Consent screen](https://mozilla-hub.atlassian.net/browse/VPN-5520)

VPN-5520: Decouple data collection checkbox from setting during onboarding

---

CMakeLists.txt
addons/CMakeLists.txt
linux/debian/control
lottie/CMakeLists.txt
tests/functional/addons/CMakeLists.txt

The introduction of QML modules in the 2.17 release revealed a bug in the registration of QML modules where resources from those modules would fail to load when built with CMake 3.16. This scenario only occurs on Ubuntu 20.04 (Focal Fossa). To resolve the issue, we need to upgrade the version of CMake available to our build workers.
While this PR looks simple, the real work is in backporting CMake 3.18 to Ubuntu/focal. This was done in the `ppa:okirby/qt6-backports` repository, with the addition of this [package](https://launchpad.net/~okirby/+archive/ubuntu/qt6-backports/+sourcepub/15217683/+listing-archive-extra)
Github #8163 ([VPN-5628](https://mozilla-hub.atlassian.net/browse/VPN-5628))
CMake backport: https://github.com/oskirby/qt6-packaging/commit/6c80f268b1987dfe371bdac6158654014638 …

VPN-5628: Increase minimum CMake to 3.18

---

src/connectionmanager.cpp
src/mozillavpn.cpp
src/tasks/heartbeat/taskheartbeat.cpp
tests/functional/testHeartbeat.js

A failed Guardian heartbeat will lead to a back-end failure in the client code, but we should not be ever deactivating the VPN without the user specifically attempting to do so as it can go unnoticed by the user.
This PR removes the call to `backendFailure()` in the connection manager when user is already authenticated if the heartbeat completes with an error code. 
https://mozilla-hub.atlassian.net/browse/VPN-5612

VPN-5612 Do not deactivate VPN upon encountering backendfailure

---

addons/message_whats_new_v2.18/manifest.json
addons/message_whats_new_v2.18/setDate.js

- Adds "What's new" message for 2.18
[VPN-5636: Implement the 'What's New' message for 2.18](https://mozilla-hub.atlassian.net/browse/VPN-5636)

VPN-5636: 2.18 what's new message

---

nebula/ui/components/MZButtonBase.qml
nebula/ui/components/MZStepProgressBar.qml
src/translations/strings.yaml

1. StepProgressBar's disabled button was mistakenly identified as focusable by the Windows Narrator screen reader, causing Narrator to attempt focusing to it during the Move Next command. This focus attempt failed inside the Qt framework due to the button's disabled state, causing Qt to fall back to setting focus on the parent Focus Scope (StackView). As Narrator follows focus, this resulted in the navigation looping issue described in the bug. A disabled button is expected to be non-focusable for Accessibility, but Qt 6.2.4 has a bug where it used only activeFocusOnTab to determine focusability. (See QAccessibleQuickItem::state.) The fix also sets activeFocusOnTab to workaround this. This issue has been resolved in Qt 6.5.1.
2. The incomplete (disabled) step in StepProgressBar contained …

VPN-5524: Mark StepProgressBar's button as not focusable when disabled, Fix a11y name

---

src/platforms/ios/ioscontroller.swift

We were leaving the tunnel setup flow after saving the tunnel, but not after loading it. It seems like without loading it, Apple briefly disconnects the tunnel on the next save, which is sending a disconnected message, which we pass on until we turn off the toggle. 
I'm not yet sure if this fixed VPN-5681, but I believe it solves the problem when the app is first loaded.
N/A

Load the tunnel before leaving flow

---

nebula/ui/components/MZCheckBoxRow.qml

- For our `MZCheckBoxRow` sublabels, let wrap on a word ending if possible, otherwise, wrap on character (instead of only wrapping on word ending)
| <img width="472" alt="Screenshot 2023-10-18 at 11 59 50 AM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/1c90d022-554b-455d-8140-4bb10f194ede"> | <img width="472" alt="Screenshot 2023-10-18 at 12 00 04 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/6b761b37-3de0-4a2c-9465-976b15a19633"> |
[VPN-5733: Delete  Mozilla account screen has UI issues for some languages](https://mozilla-hub.atlassian.net/browse/VPN-5733)

VPN-5733: Fix account deletion word wrapping

---

src/connectionmanager.cpp
src/platforms/android/androidcontroller.cpp
src/platforms/ios/ioscontroller.mm
src/platforms/ios/ioscontroller.swift
src/telemetry.cpp

- After allowing the system to create a VPN configuration at the end of the mobile onboarding flow, prevent the controller from re-attempting to connect
- iOS and Android only
[VPN-5688: Client is turned ON when the user allows to create a VPN connection](https://mozilla-hub.atlassian.net/browse/VPN-5688)

VPN-5688: Prevent VPN activation when completing onboarding

---

taskcluster/ci/docker-image/kind.yml

Ubuntu 23.10 (Mantic Minotaur) was officially released on October 12th, 2023, so we can now consider the docker image we use for building to be stable enough to cache. This should speed up builds and waste less time and bandwidth rebuilding the docker image on each run.
Ubuntu release announcement: https://lists.ubuntu.com/archives/ubuntu-announce/2023-October/000296.html

Chore: Enable taskcluster image cache for Ubuntu/mantic

---

src/platforms/android/androidcontroller.cpp

It turns out that we don't need to explicitly exclude the VPN server's address when setting up the allowed IP addresses on Android, as this is already handled by the UID routing provided by Anrdoid. This should help simplify the routing configuration and eliminate strange routing quirks.
JIRA issue [VPN-4795](https://mozilla-hub.atlassian.net/browse/VPN-4795)
[VPN-4795]: https://mozilla-hub.atlassian.net/browse/VPN-4795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4795: Remove redundant exclusion routing on Android

---

addons/message_update_v2.18/manifest.json
addons/message_whats_new_v2.18/manifest.json

Annual plan feature is shipping in 2.18 behind a feature flag still. Therefore it needs to be gone from the update messages.

Chore - Remove annual plan content from update addons

---

scripts/addon/build.py
scripts/utils/import_languages.py
src/addons/addon.cpp
src/localizer.cpp

We were showing strings like `vpn.inAppAuth.signInSubtitle2` in some languages, but not others. Description of why follows, but the ultimate fix (done in this PR) is to always fall back to English.
- When we load a language's fallback languages, we always load English. But we don't load backup languages when the build believes the translation completeness is 1.0. Which was happening here.
- This completeness comes from a `translations.completeness` file, which we build ourselves.
- The translations.completeness counts the targets (translated string) and sources (English string) in each language's .xliff file (which comes from the translation repo), and uses that ratio to determine the completeness.
- The .xliff file usually has unstranslated strings  as a source.
- However, at the point …

VPN-5643 - Ensure we always use an English backup language

---

src/connectionmanager.cpp

- While attempting to request system permissions to configure the VPN in the final step of mobile onboarding, a failed subscription check was blocking the activation process due to no internet access. We are not attempting to enable (turn on) the VPN here (just request permissions) so we can ignore the results of this check
[VPN-5680: [mobile] Unable to finalize the new onboarding flow after disconnecting from Wi-Fi](https://mozilla-hub.atlassian.net/browse/VPN-5680)

VPN-5680: Complete mobile onboarding without internet

---

nebula/ui/components/CMakeLists.txt

In order to ensure that QML modules are properly registered, we need to include both the backing target, as well as the plugin target. Unfortunately, the plugin targets were missing for the `components.forms` and `components.inAppAuth` modules, which can cause the UI to fail to load some screens.
To fix it, we just need to ensure that these targets are linked.
Github issue #8163 ([VPN-5628](https://mozilla-hub.atlassian.net/browse/VPN-5628))
[VPN-5628]: https://mozilla-hub.atlassian.net/browse/VPN-5628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5628: Fix misisng forms and inAppAuth plugin registration

---

signature/src/lib.rs
signature/src/logger.rs

The new signature crate in Rust fails to build from source on Linux/arm64 due to mismatched char signedness. This isn't one of our supported targets, but the `ppa:okirby/mozilla-vpn-testing` PPA makes an attempt to build them for completeness.
The fix is to use `std::os::raw::c_char` in place of `i8` for string pointers.
Build failures:
- [focal](https://launchpad.net/~okirby/+archive/ubuntu/mozilla-vpn-testing/+build/26894925)
- [jammy](https://launchpad.net/~okirby/+archive/ubuntu/mozilla-vpn-testing/+build/26894927)
- [lunar](https://launchpad.net/~okirby/+archive/ubuntu/mozilla-vpn-testing/+build/26894929)
- [mantic](https://launchpad.net/~okirby/+archive/ubuntu/mozilla-vpn-testing/+build/26894936)

Chore: Fix signature crate build errors on Linux/arm64

---

nebula/ui/components/CMakeLists.txt

Cherry pick of PR #8337 to fix QML plugin registration on Ubuntu/Focal
Github PR #8337 ([VPN-5628](https://mozilla-hub.atlassian.net/browse/VPN-5628))
[VPN-5628]: https://mozilla-hub.atlassian.net/browse/VPN-5628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cherry-Pick: Fix missing forms and inAppAuth plugin registration

---

signature/src/lib.rs
signature/src/logger.rs

Cherry-pick of PR #8339 to fix some build failures on Linux/arm64 in the `ppa:okirby/mozilla-vpn-testing` PPA.
Github PR #8339

Cherry-pick: Fix signature crate build errors on Linux/arm64

---

src/featurelist.h
src/featurelistcallback.h

Per a request from QA, this PR enables the `annualUpgrade` feature on Stage desktop only. This means that the upgrade path in the Subscription Management view should now be visible by default for someone who: 
- Is on stage &&
- Is on a desktop device &&
- Has a monthly subscription which was purchased through SubPlat (not the App Store, not the Play Store)
VPN-5749

VPN-5749: Enable annual upgrades on Stage desktop

---

src/mozillavpn.cpp

The work involved [here](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8300) changed when we show the “Something went wrong” screen to avoid disrupting the VPN flow. While this is intended, these changes broke the inspector command `force_heartbeat_failure` which the QA uses for UI testing purposes. 
This PR adds a command `force_backend_failure` to show that screen on demand so QA can continue to perform UI tests.
https://mozilla-hub.atlassian.net/browse/VPN-5740

VPN-5740 - Add force_backend_failure to inspector commands

---

src/mozillavpn.cpp

Cherry pick [this PR ](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8341)to 2.18 so QA can test certain functionalities.
main branch PR: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8341

VPN-5740 - Add force_backend_failure to inspector commands (#8341)

---

addons/message_update_v2.18/manifest.json
addons/message_whats_new_v2.18/manifest.json

Tentative fix. Waiting for discussions on whether this is the change we want to go with.

VPN-5745 - Fix update message contents

---

taskcluster/ci/build/linux.yml
taskcluster/ci/docker-image/kind.yml

Fedora 36 has been out of support for a few months now, and Fedora 38 is also out of beta. We should update our taskcluster build artifacts to match.
Note, this requires a sentry update to resolve some compile errors in breakpad.

Chore: Update fedora taskcluster builds

---

addons/message_update_v2.18/manifest.json
addons/message_whats_new_v2.18/manifest.json
src/addons/addonapi.cpp
src/addons/addonapi.h
src/addons/addonproperty.h

Yeah, this is hacky. I thought it would be better than changing the string id so late though. Let me know.
Little bonus for addon JavaScript file logging. 
I also reverted the changes from https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8365 just to keep the repo in line with i18n repo.

VPN-5745 - Change the id for updated whats new and update messages

---

nebula/ui/components/MZStepNavigation.qml

- Resolve UI issue in onboarding on Android devices without gesture navigation (on-screen buttons) after returning from standby
Before: 
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/97e0e823-3c78-4515-9d14-67c921e1ea96
After: 
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/70b58580-f907-4239-8341-f1b85fbf3a9a
[VPN-5663: UI issues on the new onboarding screens if device enters in standby](https://mozilla-hub.atlassian.net/browse/VPN-5663)

VPN-5663: Fix onboarding UI on Android without gesture nav

---

src/ui/screens/settings/ViewDNSSettings.qml

Another Qt 6.4 layout issue 😪 
- Properly layout/render the DNS settings view after re-visiting the view while custom DNS is selected and has a value in the text field
[VPN-5592: Linux: DNS Settings screen doesn't always render correctly](https://mozilla-hub.atlassian.net/browse/VPN-5592)

VPN-5592: Fix DNS settings layout (Qt 6.4)

---

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNActivity.java
src/connectionmanager.cpp
src/connectionmanager.h
src/platforms/android/androidcontroller.cpp
src/platforms/android/androidvpnactivity.cpp
src/platforms/android/androidvpnactivity.h
src/platforms/ios/ioscontroller.mm
src/platforms/ios/ioscontroller.swift

- Prevents the VPN config system prompt from repeatedly showing when no selection (neither "Allow" or "Don't allow") has been made by the user.
- This was due to the handshake timer that begins upon an activation request and retries to activate the VPN every 15 seconds, and is only stopped once a connection either succeeds or fails. In this case, the connection success/failure was delayed due to a required response by the user to either allow or not allow the vpn configuration to be made by the OS.
- This caused onboarding to be automatically completed after the system prompt appears, ignoring it, and waiting 15 seconds 
- Repeatedly showing the VPN config system prompt when selecting "Don't allow" was resolved as part of #8328
[VPN-5532](https://mozilla-hub.atlassian.net/browse/VPN-5532) …

VPN-5532: Prevent persistent VPN config system prompt

---

nebula/ui/components/MZStepNavigation.qml
nebula/ui/themes/main/theme.js
nebula/ui/utils/MZUiUtils.js
src/ui/screens/onboarding/OnboardingDataSlide.qml
src/ui/screens/onboarding/OnboardingDevicesSlide.qml
src/ui/screens/onboarding/OnboardingPrivacySlide.qml
src/ui/screens/onboarding/OnboardingStartSlideDesktop.qml
src/ui/screens/onboarding/OnboardingStartSlideMobile.qml

- Moved checkboxes above images on relevant slides (data and start (desktop) slides)
- Made images larger on screen sizes > 852px (Plus / Max iPhones + tablets)
- Set even spacing above and below images (including QR codes)
[VPN-5678: [iOS][iPad] Extra padding on the new onboarding screens](https://mozilla-hub.atlassian.net/browse/VPN-5678)
[VPN-5709: QR code not centered in the "Install Mozilla VPN on up to 5 devices" screen](https://mozilla-hub.atlassian.net/browse/VPN-5709)
[VPN-5710: Unexpected scrolling needed "Connect Mozilla VPN on startup" screen](https://mozilla-hub.atlassian.net/browse/VPN-5710)

VPN-5678 / VPN-5709 / VPN-5710: Onboarding layout improvements

---

.gitignore
scripts/utils/generate_release_notes.sh

Little script that will grab strings from the What's New addon for a given version on the application and generate the release notes w/ translations based on a list of blocks. It's just a matter of copy pasting the generated stuff into Play Store and App Store Connect.
Generated content looks like, using 2.17 as an example:
```
<de-DE>
Dieses Update enthält kleinere Fehlerbehebungen, Anpassungen der Benutzeroberfläche und andere Leistungsverbesserungen, einschließlich:
Ein neuer „Meine Geräte“-Bildschirm, der das Anzeigen und Verwalten Ihrer Geräte erleichtert
</de-DE>
<en-US>
This update includes minor bug fixes, UI adjustments and other performance improvements, including:
A new “My Devices” screen that makes it easier to view and manage your devices
</en-US>
<es-ES>
Esta actualización …
```

No ticket - Write a little script to generate the app store release notes w/ translations

---

taskcluster/ci/build/windows.yml
taskcluster/ci/fetch/kind.yml
taskcluster/scripts/build/windows_clang_cl.ps1
windows/tunnel/CMakeLists.txt

We're currently downloading wintun on every init of the build folder from the interwebs. 
Now today that has been flaky, so let's have taskcluster fetch it and use that instead, so we don't hit the server everytime ,__,

Nit: don't download wintun for each build

---

addons/message_fpn_trial_subscription_expiring/getHelp.js
addons/message_fpn_trial_subscription_expiring/isFpnTrial.js
addons/message_fpn_trial_subscription_expiring/manifest.json

- Message that will be sent to FPN users who were given a 6 month free trial
- Does not need translations
- FPN was US-only so we're restricting this message to users who have there language set to english
- Timestamp is set to 20:00 GMT as we anticipate this message going out at that time or a little later
[VPN-4846: Phase 3: Implement and release the in-app message for the free VPN users](https://mozilla-hub.atlassian.net/browse/VPN-4846)

VPN-4846: FPN trial subscription expiring message

---

nebula/ui/components/inAppAuth/MZInAppAuthenticationLegalDisclaimer.qml
src/ui/authenticationInApp/ViewAuthenticationSignIn.qml
src/ui/authenticationInApp/ViewAuthenticationSignUp.qml
tests/functional/testAuthenticationInApp.js

The two issues found by QA were:
1. Privacy notice and terms of service interaction events were not being recorded correctly. 
2. 2fa outcome events were being recorded for users that didn't go through 2fa. I have not been able to reproduce this, but I added test cases for it just in case (the tests pass).

VPN-5251 - Address QA feedback

---

taskcluster/scripts/build/ios_build_no_adjust_cmake.sh
taskcluster/scripts/build/macos_build.sh

See: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8541/checks?check_run_id=18627540446 
This has now been happening too often 😅 
Are we re-using task-id's again?

Nit: Clean iOS build folder, if not empty

---

taskcluster/scripts/toolchain/conda_pack_android.sh

We override the QT_VERSION env variable in the toolchain-task using the env argument. 
The created env however still uses QT_VERSION used in env.yml. 
So the build runner will be using the conda-env version, therefore we need to set that in the conda-env, so it's properly pased on.

Pin the qt version inside the packed conda env

---

src/ui/screens/onboarding/OnboardingDevicesSlide.qml

- On devices with shorter screens, the "Next" and "Go back" buttons wouldn't respect the size of the QR code and would overlap it. Setting a minimum size on the QR codes layout resolves the issue
| Beforer  | After |
| <img width="472" alt="Screenshot 2023-11-09 at 12 30 31 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/b107b5fd-edaf-49f4-9780-4b553cb984fd"> | <img width="472" alt="Screenshot 2023-11-09 at 12 31 03 PM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/448181bc-b599-4d62-b31e-8bc44b268246"> |
[VPN-5802: UI issues in the Devices screen while on small screens mobile devices](https://mozilla-hub.atlassian.net/browse/VPN-5802)

VPN-5802: Onboarding - prevent buttons overlapping qr code

---

taskcluster/scripts/build/windows_clang_cl.ps1

We fetch that info during runtime, so no need to have 2 ci build paths.

Nit: we no longer need to pass the sentry secrets

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt

When the generation of this object was changed to be lazy, it would be created inside the `VPNService.turnOn` method. That method is called in a thread that is not equipped to create timers causing a crash and thus the issue described on VPN-5766.

VPN-5766 - Fix CountdownTimer generation timing

---

src/telemetry/interaction_metrics.yaml
src/ui/screens/onboarding/OnboardingDataSlide.qml
tests/functional/testOnboarding.js

- Remove telemetry for data collection checkbox in onboarding, as it is not deemed to be userful
[VPN-5098: Improvement: Implement onboarding telemetry](https://mozilla-hub.atlassian.net/browse/VPN-5098)

VPN-5098: Remove telemetry for data collection checkbox

---

wasm/main.css

I recently changed the dimensos of the wasm canvas, because turns out that can cause testing issues.
Why? Because in order to click on something for tests it needs to be in screen, if it's below or above the fold the click is unsuccessful. Yes, we could have special cased WASM clicks and so on, but that sounds excessive, instead I changed the WASM canvas to always have the same dimensions as the Desktop client. (When we run these tests on mobile devices this may come back to bite us, but then we can come up with a more elegant solution e.g. always scroll to element before a click).
Anyways, that made the WASM client look weird. Just go to https://mozilla-mobile.github.io/mozilla-vpn-client/?branch=main and see for yourself. With this change it will look like this:
A little bit better 👀

No ticket - Nit: Fix wasm canvas container

---

src/tasks/authenticate/desktopauthenticationlistener.cpp

The params are added to the login URL and are passed on to the subscription purchase page.

VPN-4604 - Add utm params to subscription url

---

nebula/ui/components/MZAlert.qml
nebula/ui/components/MZRadioDelegate.qml
nebula/ui/components/forms/MZContextualAlert.qml
nebula/ui/components/forms/MZRadioButton.qml
src/localizer.cpp
src/translations/strings.yaml
src/ui/screens/home/controller/ConnectionStability.qml
src/ui/screens/home/controller/ControllerView.qml
src/ui/screens/settings/ViewLanguage.qml

The selected state of a Radio Button is not read by the screen reader on Windows  when activated through the Accessibility PressAction command. This is a Qt limitation. Worked around by raising a "Selected" accessible notification. Accessible notifications currently are supported only in Windows by Qt. 
This workaround excludes the following scenarios, as explained in the code comment, to prevent a redundant notification:
1. When the radio button's selection causes focus to change, as seen in the DNS Settings screen, when custom DNS is selected.
2. When the radio button's selection causes the Accessible name to change, as seen in the Languages screen, when an unrelated new language is chosen.
Also, fixed the following:
1. Improved performance in the Languages screen by removing the …

VPN-5578: Work around lack of built-in RadioButton selection a11y support on Windows

---

src/translations/strings.yaml
src/ui/screens/home/controller/ControllerNav.qml
src/ui/screens/home/controller/ControllerView.qml
src/ui/screens/home/controller/connectionInfo/ConnectionInfoScreen.qml

When the Speed Test's Connection Info panel or the IP Info panel was opened, some elements in the Home screen that are under those panels ("Secure and Private", "Select location") were read by the screen reader. Fixed by ignoring them for Accessibility in this state.
Also fixed the following issues:
1. The Speed Test panel's connectionInfoToggleButton was being read when the IPInfoPanel was open.
2. The "Restart speed test" button label was not  localized.
[VPN-5597](https://mozilla-hub.atlassian.net/browse/VPN-5597), [GitHub 8125](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8125)
[VPN-5597]: https://mozilla-hub.atlassian.net/browse/VPN-5597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5597: Fix a11y issues when Speed Test and IP Info panels are opened

---

src/translations/strings.yaml
src/ui/screens/settings/privacy/PrivacyFeaturesList.qml

Remove the world "malware" from text body as it is redundant.
https://mozilla-hub.atlassian.net/browse/VPN-5883

VPN-5883 Update Malware "Privacy Feature" description

---

nebula/ui/components/MZSegmentedToggle.qml
nebula/ui/components/MZTabNavigation.qml

- Restore focus states of `MZTabNavigation` buttons and `MZSegmentedToggle`'s to how they were prior to tutorial removal. We only used these outlines for focusing on these components during tutorials, so lets remove them
[VPN-5887: Text elements of the tabbed bars from Select location screen are bordered when being pressed ](https://mozilla-hub.atlassian.net/browse/VPN-5887)

VPN-5887: Fix tab and segmented toggle focus states

---

nebula/ui/components/inAppAuth/MZInAppAuthenticationErrorPopup.qml
src/authenticationinapp/authenticationinapp.h
src/authenticationinapp/authenticationinappsession.cpp
src/authenticationinapp/authenticationinappsession.h
src/commands/commandlogin.cpp
tests/functional/servers/fxa_endpoints.js
tests/functional/testAuthenticationInApp.js
tests/functional/testAuthenticationInAppAccountCreationNav.js
tests/functional/testAuthenticationInAppErrors.js

Fixes VPN-5899
Use the `thirdPartyAuthStatus` param of the FxA [`/account/status`](https://mozilla.github.io/ecosystem-platform/api#tag/Account/operation/postAccountStatus) endpoint to determine if the account has a password or not. If the account _does not_ have a password, this means it is either a stub account (created at subscription time with only an email, and the user has not yet visited their email to set their password) or it is an SSO-linked account.
Up to this point, if a user with a passwordless account attempted to login, the client would simply hang indefinitely. This PR replaces this with a generic error. Admittedly, this is not much better, but it sets us up for a future ticket where we can replace the generic error with a error with proper wording (TBD by product and UX). …

VPN-5899: Handle FxA stub accounts

---

src/ui/screens/home/controller/ControllerView.qml

The IPInfoPanel was before its close button in the QML, and focus was on the close button when the panel was opened. This meant that the user needed to navigate backwards from the Close button to read the panel text using a screen reader, which is not intuitive. Fixed by moving IPInfoPanel after its Close button. This allows the user to read the panel's text by navigating forward in a screen reader.
Also fixed the following:
Previously the IPInfoPanel had its z-order set to the same z-order as the buttons, which hid some visibility bugs. Specifically, the visible properties of connectionInfoToggleButton and ipInfoToggleButton were not correct. connectionInfoToggleButton  should be visible only if the IPInfoPanel  is not opened.
[VPN-5783](https://mozilla-hub.atlassian.net/browse/VPN-5783), …

VPN-5783: Change IPInfoPanel's a11y navigation order so that content is after the close button

---

signature/src/lib.rs

This addresses a TODO item in the Rust unit tests that were causing our unit test job to fail due to an expired certificate.
We had some tests in the Balrog module that tried to verify certificates that we fetched from the production servers, and those certificates recently expired. The Rust language doesn't really have a mechanism to mock things like the system time when running tests, so I opted to work around the issue by parsing a timestamp out of the certificates when compiled with `#[cfg(test)]`

Chore: Fix Rust unit tests due to expired test certificate.

---

.github/workflows/i18n_update.yaml

Auto-merge is not ideal for release branches, because they can make it confusing to understand what exactly is state of a given RC.
Instead I have changed this to create the i18n update PR for the release branch, BUT NOT MERGE IT. 
Whenever a Release Manager is about to cut a new RC they should be responsible for merging any outsating PRs.
Note: this doesn't mean multiple PRs will be created for relase branches. If the previous PR is not merged it will just keep being updated untill it is time to merge.

VPN-5797 - Do not automerge i18n updates on release branch

---

.github/workflows/test_unit.yaml

The Linux unit tests have recently started to fail, and this is due to installing dependencies before doing an `apt-get update`. This causes the worker to try and fetch outdated packages from the APT repository. We were already doing and update of the repository data, it was just in the wrong order.

Chore: Fix out-of-order apt-get update in Linux tests

---

src/controller.cpp

The issue here is quite simple: we do not handle the case when there is no current device available when activating the controller. That was the cause of VPN-5948.
This can happen if a device is removed and immediatelly an activation is enqueued. 
A better option might be to just stop the task that is activating the VPN, this is a bit less drastic and maybe less risky?

VPN-5948 - Abort controller activation when there is no current device

---

addons/message_upgrade_to_annual_plan/manifest.json

- Prevent the "annual upgrade" in-app message from displaying in production
Note: this should be removed as a part of [VPN-5637: Turn the VPN plan upgrades feature ON](https://mozilla-hub.atlassian.net/browse/VPN-5637)
[VPN-5920: Upgrade to annual plan message is displayed when using Addons RC in production](https://mozilla-hub.atlassian.net/browse/VPN-5920)

VPN-5920: Display the "Annual upgrade" in-app message in staging only

---

tests/functional/testAuthenticationInApp.js

The `testAuthenticationInApp.js` functional test has recently started to fail on Linux, and this appears to be due to a race between the functional test and the asynchronous handling of the 2FA network request. In particular, the tests click on the verification button and then immediately check the glean telemetry for the expected events, but those events are set only once the 2FA network requests are completed. This leaves a race condition where the tests fail to wait for the telemetry to be set.
To resolve the problem, I just added a few waits before checking telemetry on a successful 2FA verification.

Chore: Fix race in AuthenticationInApp functional test

---

addons/message_upgrade_to_annual_plan/conditions.js
addons/message_upgrade_to_annual_plan/manifest.json
src/addons/addon.cpp
src/notificationhandler.cpp

- Re-enable (removing `staging` condition) the message
- Add condition to only enable on desktop platforms
- Fix push notification not being suppressed on condition changes when set to not notify
- Fix conditional in condition.js that was always evaluating to true
- Allows functional tests to run on addons that only support certain platforms (automatically include `dummy` in list of supported platforms)
[VPN-3362: Release a "Plan Upgrade" in-app message to monthly-plan non-IAP subscribers](https://mozilla-hub.atlassian.net/browse/VPN-3362)
[VPN-3044: Release support for In-App Messages to generate (or not) an OS notification](https://mozilla-hub.atlassian.net/browse/VPN-3044)

VPN-3362: Annual upgrade plan message fixes 

---

nebula/ui/components/forms/MZComboBox.qml
nebula/ui/components/forms/MZTextArea.qml
src/ui/screens/home/controller/ControllerView.qml

"Contact Support" screen's ComboBox and "Describe Issue" TextArea did not have a11y names, so were not read by the screen reader.
Also fixed:
1. Shift+Tab in the  "Describe Issue" TextArea was being input into the TextArea instead of moving to the previous control.
2. Subtitle in Home screen was not accessible.
[VPN-5293](https://mozilla-hub.atlassian.net/browse/VPN-5293), [GitHub 7631](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/7631)
[VPN-5293]: https://mozilla-hub.atlassian.net/browse/VPN-5293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5293: Add missing a11y names in "Contact Support" screen

---

nebula/ui/components/MZSystemAlert.qml
src/cmake/macos.cmake
src/controller.cpp
src/controller.h
src/controllerimpl.h
src/localsocketcontroller.cpp
src/localsocketcontroller.h
src/mozillavpn.cpp
src/mozillavpn.h
src/platforms/macos/daemon/dnsutilsmacos.cpp
src/platforms/macos/daemon/dnsutilsmacos.h
src/platforms/macos/daemon/macosdnsmanager.cpp
src/platforms/macos/daemon/macosdnsmanager.h
tests/auth_tests/mocmozillavpn.cpp
tests/qml/moccontroller.cpp
tests/qml/mocmozillavpn.cpp
tests/unit/moccontroller.cpp
tests/unit/mocmozillavpn.cpp
tests/unit_tests/mocmozillavpn.cpp

In this PR we attempt to make the VPN client and daemon on MacOS more resilient to abnormal exit conditions in the VPN tunnel or daemon. To accomplish this goal, we made a few changes and tweaks:
- Check for and handle errors in the UNIX socket, and re-initialize of the socket closes on us.
- Remove the "try again" link in the backend failure banner, it doesn't do anything, and it never did anything.
- Permit the controller to re-initialize itself after a backend failure.
- Add optional timeouts on `LocalSocketController::write()` to catch cases where the daemon is hung.
This alone was sufficient to get the client to recover from a crash of the daemon. But there was still a problem: if the daemon crashes while the tunnel is active this will bring the tunnel down, but we don't get to run …

VPN-4228: MacOS daemon recovery on crash

---

qtglean/src/lib.rs
src/glean/mzglean.cpp

Note this get's the system locale *not the VPN locale*. This is how Glean works in other platforms, so this is just for completion sake. We are not trying to understand what is the user chosen chosen locale in the app, but just adding a metric to desktop that we collect on mobile platforms.

VPN-5849 - Set locale for Glean pings on desktop platforms

---

docs/rfcs/0005-suggested-excluded-apps-tech-spec.md

This was an open question from the RFC, now with a proposed answer.
VPN-5758

VPN-5758: Add matching details for suggested app exclusions

---

src/telemetry/impression_metrics.yaml
src/telemetry/interaction_metrics.yaml
src/ui/screens/settings/ViewSettingsMenu.qml
src/ui/screens/settings/appPermissions/AppPermissionsList.qml
tests/functional/testAppExclusions.js
tests/functional/testSettings.js

Please note that this PR is essentially a duplicate of https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8440 but I was getting some mysterious test failures and it was more straightforward to cherry pick the changes over to this PR than to try and get the original PR to work again. Sorry! For data and PR review please refer back to the original.
Add telemetry to the buttons and screens pertaining to app exclusions in the VPN setting (and corresponding functional tests to ensure we are correctly tracking these interactions). These new additions attempt to answer the following question:
- What’s the level of interest for “App Exclusions”? (views of the “App Exclusions” screen and %age of devices)
- How often do people use search to find the apps they want to exclude? (# clicks on …

VPN-5363 Update our App Exclusions Telemetry

---

src/ui/sharedViews/ViewErrorFullScreen.qml

On some platforms, the empty text field in the Error dialog was being read. Ignore it for accessibility.
[VPN-5769](https://mozilla-hub.atlassian.net/browse/VPN-5769), [Github 8394](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8394)**
[VPN-5769]: https://mozilla-hub.atlassian.net/browse/VPN-5769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5769: Ignore Error dialog's empty text field for accessibility

---

nebula/ui/components/MZStepProgressBarDelegate.qml

Previously, long progress bar delegate labels would wrap if they impeded on a neighboring progress bar label. To resolve this, we will now right elide long labels 
| <img width="428" alt="Screenshot 2023-12-04 at 11 08 45 AM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/020a74ee-1680-4aff-bb46-1c7deb46c109"> | <img width="428" alt="Screenshot 2023-12-04 at 11 08 31 AM" src="https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/51d5d2fd-2186-4c7f-b51c-987553c66d52"> |
[VPN-5816: [l10n] New on-boarding progress bar names are not wrapped in some languages](https://mozilla-hub.atlassian.net/browse/VPN-5816)

VPN-5816: Elide step progress bar delegate labels

---

CMakeLists.txt
ios/adjust/CMakeLists.txt
lottie/CMakeLists.txt
qtglean/CMakeLists.txt
scripts/cmake/generate_translations_target.cmake
scripts/cmake/utilities.cmake
src/CMakeLists.txt
src/cmake/shared-sources.cmake
src/cmake/sources.cmake

We set `-werror` in multiple places with conditions. I wanted to add wasm to that. So let's have that condition in one place only.

Nit: Unify setting target_compile_options

---

nebula/ui/components/MZScreenBase.qml
nebula/ui/components/MZViewBase.qml
nebula/ui/components/navigator/MZNavigatorLoader.qml
src/ui/screens/ScreenGetHelp.qml
src/ui/screens/ScreenHome.qml
src/ui/screens/home/ViewServers.qml
src/ui/screens/messaging/ViewMessagesInbox.qml
src/ui/screens/settings/ViewSettingsMenu.qml

The tracking bug is an investigation into slow performance of the TalkBack screen reader on Android in starting to read a newly loaded screen in VPN. When a screen is loaded, TalkBack can take several seconds to start reading it.
The root cause is that the Qt framework sends a large number of TYPE_WINDOW_CONTENT_CHANGED accessibility events while a QML component is loading, because each geometry change triggers this event. This makes TalkBack slow to starting reading a QML component, because the flood of events need to be processed before TalkBack can start reading.  https://bugreports.qt.io/browse/QTBUG-119612 has been opened to report this Qt issue. The length of the delay increases with the the number of elements in the screen, because more elements cause more geometry changes.
While …

VPN-5439: Improve focus management when screens are loaded/shown

---

taskcluster/ci/fetch/kind.yml

The `fetch-open-ssl` task [is failing](https://firefox-ci-tc.services.mozilla.com/tasks/J9O4fWO3T2-Nn6mT6Sq_Hw/runs/0/logs/public/logs/live.log) after rebuilding cached tasks for a CoT key rotation. To be clear, the failure has nothing to do with the rotation, the rotation is just surfacing a latent error that would have popped up sooner or later anyway.
In this case I can confirm that downloading the file at the requested url yields the same hash / size that the error is complaining about... But I'm confused why the new file is so much smaller than the old one. Something seems suspicious here.

ci: Remove unused fetch-open-ssl task

---

wasm/embedded.html

Sooo, currently we only have the "wasm" runner website that expects to take on a complete screen. 
However if someone were to "just" have the client i.e. in an iframe on a cool webpage. that's currently not possible. so let's add a wrapper for that too.

Nit: add a wasm-shell for fullscreen embedding

---

android/AndroidManifest.xml

This essentially reverts https://github.com/mozilla-mobile/mozilla-vpn-client/pull/7822/. It's needed to use the Adjust SDK again.
This will be uplifted to 2.19.1 release branch after it hits `main`.
N/A

Add `ad id` permission for Android, because Adjust

---

macos/pkg/CMakeLists.txt
macos/pkg/scripts/postinstall.in
taskcluster/scripts/build/macos_build.sh

In order to prevent tampering with the VPN application, we should take steps to verify the application code signature during installation. This can be done as some additional steps in the `postinstall` script.
While at it, I also figured out the fix for VPN-3443, which is that we need to configure the application bundle to deny relocation by PackageKit.
Github issue #5137 ([VPN-3443](https://mozilla-hub.atlassian.net/browse/VPN-3443))
JIRA issue ([VPN-5911](https://mozilla-hub.atlassian.net/browse/VPN-5911))
[VPN-3443]: https://mozilla-hub.atlassian.net/browse/VPN-3443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-5911]: https://mozilla-hub.atlassian.net/browse/VPN-5911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

VPN-5911: Verify MacOS code signatures during installation.

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt

In testing https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8698/, QA noticed that Android sent daemon pings for server switches. iOS has never done this, and so this fixes the behavior on Android.
VPN-5900

VPN-5900 (part 2): Don't send Android daemon metrics when switching server

---

taskcluster/scripts/build/windows_clang_cl.ps1

Codna on windows only has `python.exe` not `python3.exe`  therefore when we called get-secret.py we did not use our conda env where we have all the dep's for that already loaded. And fail like this: 
```
[22 Uhr](https://mozilla.slack.com/archives/D02CSN2APFA/p1702473729781509)
[task 2023-12-11T19:10:56.463Z]   File "D:\task_170232135405499\mozillavpn-2.19.1~rc20231211184139\taskcluster\scripts\get-secret.py", line 12, in <module>
[task 2023-12-11T19:10:56.510Z]     import taskcluster
[task 2023-12-11T19:10:56.510Z] ModuleNotFoundError: No module named 'taskcluster'
```
As we did not fetch the secret to upload sentry secrets, we failed in uploading them too.

VPN-5841 basti/fix sentry upload

---

taskcluster/scripts/build/windows_clang_cl.ps1

It seems to now fetch the correct secret. but tries to upload the wrong file. 
```
[task 2023-12-13T17:02:10.876Z] Stored token in C:\Users\task_170248645540156\.sentryclirc
[task 2023-12-13T17:02:11.146Z] > Found 0 debug information files
[task 2023-12-13T17:02:11.146Z] > No debug information files found
[task 2023-12-13T17:02:11.287Z] 
[task 2023-12-13T17:02:11.287Z] 
```
In the Unsinged DIR we have the PDB file we want, so let's upload that! :) 
```
[task 2023-12-13T17:02:03.457Z] -- Installing: D:\task_170248645540156\/unsigned/./Mozilla VPN.exe
[task 2023-12-13T17:02:03.537Z] -- Installing: D:\task_170248645540156\/unsigned/./Mozilla VPN.pdb
[task 2023-12-13T17:02:03.694Z] D:\task_170248645540156\cmake_build\src\Mozilla VPN.exe 64 bit, release executable
[task …
```

VPN-5841 Fix sentry upload round 2

---

nebula/ui/components/MZViewBase.qml
src/ui/screens/home/ViewServers.qml

Use 'Pane' for a11y role in a view because 'Grouping' caused VoiceOver ScreenReader quick-nav problems in macOS
[VPN-5439](https://mozilla-hub.atlassian.net/browse/VPN-5439), [GitHub 8751](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8751)
[VPN-5439]: https://mozilla-hub.atlassian.net/browse/VPN-5439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5439: Use 'Pane' for a11y role instead of 'Grouping'

---

nebula/ui/components/MZSegmentedToggle.qml
nebula/ui/components/MZTabNavigation.qml

Tab button's selection state was not being read by the Screen Reader. Add selection state in Tab button's Accessibility name.
Also fixed:
1. Selection of a tab button using keyboard or screen reader shortcut was previously  not supported.
2. The text inside the button could be navigated to using a screen reader shortcut, which was redundant. Remove this.
[VPN-5291](https://mozilla-hub.atlassian.net/browse/VPN-5291), [GitHub 7629](https://github.com/mozilla-mobile/mozilla-vpn-client/issues/7629)
[VPN-5291]: https://mozilla-hub.atlassian.net/browse/VPN-5291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5291: Tab button's selection state was not being read in 'Select Server' screen

---

nebula/ui/components/CMakeLists.txt
nebula/ui/components/MZBottomSheet.qml
nebula/ui/components/MZFlickable.qml
nebula/ui/components/MZHelpSheet.qml
nebula/ui/components/qmldir
nebula/ui/themes/main/theme.js

- Create `MZBottomSheet`, a generic, reusable drawer/sheet component
- Create `MZHelpSheet`, based off of `MZBottomSheet`, but specifically tailored for our [educational content](https://mozilla-hub.atlassian.net/browse/VPN-4681)
- Notes about `MZHelpSheet`:
- Resizes to fit it's content, up to a maximum size, then scrolls
- Supports titles, text, primary buttons, and link buttons
Examples: 
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/735a2be2-860c-4bf4-b018-3b6e0f222d25
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/d60c5af8-f22e-4243-b2a6-8ccb66b3b57d
[VPN-4852: Create new "MZSheet" Nebula component to support new guides](https://mozilla-hub.atlassian.net/browse/VPN-4852)

VPN-4852: Implement MZBottomSheet and MZHelpSheet

---

src/frontend/navigator.cpp

In a recent PR, we added support for navigating to screens using deep linking. But unfortunately, in the implementation we left an infinite loop bug where upon if we fail to find a screen that matches the requested deep link, we iterate forever.
Deeplinking PR #8757
Github issue: #8742 ([VPN-5983](https://mozilla-hub.atlassian.net/browse/VPN-5983?focusedCommentId=808646))
[VPN-5983]: https://mozilla-hub.atlassian.net/browse/VPN-5983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5983: Fix infinite loop bug in Navigator::requestDeepLink()

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/NotificationUtil.kt
android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNActivity.java
src/commands/commandui.cpp
src/loghandler.cpp
src/platforms/android/androidvpnactivity.cpp
src/platforms/android/androidvpnactivity.h

This add's a few new primitives to help others build cool deeplinking things. 
- Added `AndroidVPNActivity::getOpenerURL` to get the current `mozilla-vpn://` url 
- Added `Q_SIGNAL(AndroidVPNActivity::onOpenedWithUrl)` to get notifications whenever the app is alive but got forgrounded with a new url
- Added the ability to add URL's in `NotificationUtil`
Did a little WIP demo thing to tie that together - given we registered handling  `mozilla-vpn://` urls back in 2.0 we can just test them from a browser and ` <a href="mozilla-vpn://nav/gethelp"> Open HELP Page</a> ` :) 
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/9611612/2d847e01-c225-4220-8e05-6f8c02e2beb9
--- 
There are some wierdnesses when doing a cold-start using that an url. However the url is correctly passed to the …

Android Deep Linking Bits 

---

android/AndroidManifest.xml
android/adjust/build.gradle
android/common/build.gradle
android/common/src/main/java/org/mozilla/firefox/qt/common/CoreApplication.kt
android/daemon/build.gradle
android/resources/all/xml/network_security_config.xml
scripts/android/cmake.sh

A write up of the issues on hand is in the ticket: https://mozilla-hub.atlassian.net/browse/VPN-5822?focusedCommentId=809828
Instead of a bool, let's enforce https for all known domains the client can talk to.

Adjust fixes for Android client: add a network conf, change how token is passed to gradle

---

src/platforms/linux/daemon/apptracker.cpp
src/platforms/linux/daemon/apptracker.h
src/platforms/linux/daemon/dbusservice.cpp
src/platforms/linux/daemon/dbusservice.h
src/platforms/linux/daemon/org.mozilla.vpn.dbus.xml
src/platforms/linux/linuxdependencies.cpp
src/platforms/linux/linuxdependencies.h

App exclusions on Linux mostly make use of the GTK `Launched` signal over D-Bus to kick off application detection by connecting a `*.desktop` file and a control group, and this has worked okay-ish for the most part, but it leaves a lot of edge cases where applications can fall through the cracks if the PID that we get from the GTK launch event dies before the following control group is created. And it just so happens that this has become the case for Snap-packaged applications as of Ubuntu/23.04 Lunar.
To fix this, I think it's finally time that we get off our butts and do some proper heuristic matching between the control group name and typical launcher commands used for Linux desktop environments. To make this work, we first convert the `*.desktop` file into a desktop file ID and then …

VPN-4798: Linux cgroup application matching heuristics

---

CODEOWNERS

Releng doesn't have much involvement with the build / addons scripts so we shouldn't be CODEOWNERS here. 
Btw, if VPN folks would like us to be CODEOWNERS of fewer things, let us know! We're mostly here to help catch potential problems early and are happy to remain. But if we're just holding things up we can revisit.

Remove releng as CODEOWNERS of build / addons scripts

---

src/networkwatcher.cpp
src/networkwatcher.h
src/networkwatcherimpl.h
src/platforms/android/androidnetworkwatcher.cpp
src/platforms/android/androidnetworkwatcher.h
src/platforms/dummy/dummynetworkwatcher.h
src/platforms/ios/iosnetworkwatcher.h
src/platforms/ios/iosnetworkwatcher.mm
src/platforms/linux/linuxnetworkwatcher.h
src/platforms/wasm/wasmnetworkwatcher.h
src/platforms/windows/windowsnetworkwatcher.cpp
src/platforms/windows/windowsnetworkwatcher.h
src/telemetry.cpp
src/telemetry/metrics.yaml

Remove `GetTransportTypeCode` and replace with `getReachability()` instead. GetTransportTypeCode became obsolete with Qt 6.3.
https://mozilla-hub.atlassian.net/browse/VPN-3511

VPN-3511 Remove: GetTransportType Code

---

taskcluster/kinds/build/windows.yml
taskcluster/kinds/fetch/kind.yml

Most of the build deps should live inside the conda-env, so neither go nor rustup should need to be fetched.

CI: Windows - Remove unsed fetchs 

---

src/networkwatcher.cpp
src/networkwatcherimpl.h
src/platforms/android/androidnetworkwatcher.cpp
src/platforms/android/androidnetworkwatcher.h
src/platforms/dummy/dummynetworkwatcher.h
src/platforms/ios/iosnetworkwatcher.h
src/platforms/ios/iosnetworkwatcher.mm
src/platforms/linux/linuxnetworkwatcher.h
src/platforms/wasm/wasmnetworkwatcher.h
src/platforms/windows/windowsnetworkwatcher.cpp
src/platforms/windows/windowsnetworkwatcher.h

Check QNetworkInformation::instance() exists first before attempting to access its reachability. If it doesn't exist, return reachability::unknown.
https://mozilla-hub.atlassian.net/browse/VPN-6042

VPN-6042 Check QNetworkInformation::instance() exists first

---

nebula/ui/components/MZUserProfile.qml
src/frontend/navigator.cpp
src/telemetry/impression_metrics.yaml
src/telemetry/interaction_metrics.yaml
src/telemetry/metrics.yaml
src/ui/screens/settings/ViewSubscriptionManagement/SubscriptionManagementItem.qml
src/ui/screens/settings/ViewSubscriptionManagement/ViewSubscriptionManagement.qml
tests/functional/queries.js
tests/functional/testAddons.js
tests/functional/testSubscription.js
tests/unit_tests/CMakeLists.txt
tests/unit_tests/testnavigator.cpp
tests/unit_tests/testnavigator.h

- Add impression telemetry for the subscription management view
- Replace old manage account and manage subscription telemetry with new interaction format
- Add new telemetry for navbar button presses (that records source view as extra key)
- Source views need to be added to the screen via [Navigator::addView](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8838/files#diff-bf5452c5d9bf001e7b2cf467b8ef9ea5d752617491b1aeaf711f7e5a674e25d6R333)
- Source views need a [telemetryScreenId property](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8838/files#diff-801f8102a46fbdeea68eacfcedafcc467b5a247655c88dfa7f4c963ed9612424R17)
- Left [old navbar button press telemetry](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8838/files#diff-bf5452c5d9bf001e7b2cf467b8ef9ea5d …

VPN-5547: Implement subscription management telemetry

---

scripts/android/cmake.sh
taskcluster/scripts/build/android_build_release.sh
taskcluster/scripts/build/macos_build.sh

We fetch sentry info from guardian, no need to pass it as cmake args anymore. 
Should fix: 
```
[task 2024-01-02T14:35:35.776Z] Fetching tokens...
[task 2024-01-02T14:35:36.323Z] Outputting secret to: /opt/worker/tasks/task_169453793109859/checkouts/vcs/sentry_dsn
[task 2024-01-02T14:35:36.323Z] Traceback (most recent call last):
[task 2024-01-02T14:35:36.323Z]   File "/opt/worker/tasks/task_169453793109859/checkouts/vcs/./taskcluster/scripts/get-secret.py", line 106, in <module>
[task 2024-01-02T14:35:36.323Z]     main()
[task 2024-01-02T14:35:36.323Z]   File "/opt/worker/tasks/task_169453793109859/checkouts/vcs/./taskcluster/scripts/get-secret.py", line 94, in main
[task 2024-01-02T14:35:36.324Z]     write_secret_to_file(
[task 2024-01-02T14:35:36.324Z]   File …
```

Nit: Remove Sentry config from CI

---

src/platforms/macos/macosutils.mm

Update the API we use to manage loginItems and startAtBoot. What we were using(`SMLoginItemSetEnabled()`) is deprecated on MacOS 13 and beyond and is replaced by `registerAndReturnError` and `unregisterAndReturnError`. To continue backwards compatibility, if the OS is older than MacOS 13 we still fall back to the old way of managing login items.
https://mozilla-hub.atlassian.net/browse/VPN-4126
https://mozilla-hub.atlassian.net/browse/VPN-4307

VPN-4307 Use registerAndReturnError to replace deprecated API for managing LoginItems

---

src/frontend/navigator.cpp
tests/unit_tests/testnavigator.cpp
tests/unit_tests/testnavigator.h

- Make sure the screen that is being navigated away from (on nav bar button click) has at least one layer (stack or view) before attempting to get it's `telemetryScreenId` property
[VPN-6067: [Intermittent] [macOS] Mozilla VPN is crashing without clear steps while the VPN is OFF](https://mozilla-hub.atlassian.net/browse/VPN-6067)

VPN-6067: Null check navigator screen layers

---

addons/message_whats_new_v2.20/manifest.json

- Prevent triggering an OS notification when the "What's New" in-app message is received 
[VPN-3044: Release support for In-App Messages to generate (or not) an OS notification](https://mozilla-hub.atlassian.net/browse/VPN-3044)

VPN-3044: Suppress OS notification for "What's new" message

---

src/addons/manager/addonmanager.cpp
src/feature/feature.cpp
src/feature/feature.h
src/feature/featuremodel.cpp
src/feature/featuremodel.h
src/settings/settinggroup.cpp
src/tasks/getfeaturelist/taskgetfeaturelist.cpp
tests/unit_tests/feature/testfeaturemodel.cpp
tests/unit_tests/feature/testfeaturemodel.h
tests/unit_tests/testsettingsholder.cpp
tests/unit_tests/testsettingsholder.h

This is part one as there are a bunch of changes still required to actually get Guardian to send the experimental features. 
This part of the ticket got a bit big, because I also did some cleanup here -- removed some unused code and separated a big function into smaller functions. 
**Anyways, what this PR aims to do is parse the `experimentalFeatures` property that will be returned from Guardian once the Guardian PR is merged and deployed.**
The Guardian companion PR is: https://github.com/mozilla-services/guardian-website/pull/1688
> Note: I reccomend reviewing this commit by commit as there are some clean up changes that might get in the way.

VPN-5855 - Part 1 - Parse experimentalFeatures property returned from featurelist Guardian endpoint

---

taskcluster/kinds/beetmover-promote/kind.yml
taskcluster/kinds/beetmover-ship/kind.yml
taskcluster/kinds/beetmover/kind.yml
taskcluster/kinds/release-notify/kind.yml
taskcluster/mozillavpn_taskgraph/transforms/beetmover.py
taskcluster/mozillavpn_taskgraph/transforms/release_notify.py

The way the beetmover tasks/transforms are currently defined means the task definitions change based on the shipping_phase parameter. This breaks expectations, and should be changed so that there are separate push-to-candidates and copy-to-releases tasks in the full graph, with the selection of which one(s) to run happening as part of targeting.
Jira: https://mozilla-hub.atlassian.net/browse/VPN-6080
Issue: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8919

Refactor beetmover tasks to be distinct to each shipping phase

---

taskcluster/mozillavpn_taskgraph/transforms/beetmover.py

This fixes a regression from #8931 to the Windows beetmover task.
Issue: #8919

[VPN-6080] Fix regression to beetmover-promote-windows task

---

addons/message_update_v2.20/manifest.json

Fix an oversight from [this PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8910) to fix the max client version
Issue:
https://mozilla-hub.atlassian.net/browse/VPN-5914

set max client version to 2.19.9

---

src/constants.h
src/mozillavpn.cpp
src/translations/strings.yaml
src/ui/screens/home/ViewMultiHop.qml
src/ui/screens/home/ViewServers.qml
src/ui/screens/home/servers/ServerList.qml
tests/functional/queries.js
tests/functional/testMultihop.js

**NOTE: Depends on [#8864: VPN-4687: Add DNS settings help sheet](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8864)**
- Implement help sheet for location selection
- Remove collapsible help cards for recommended servers and multihop
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/1206ee69-9c9a-4a8e-a7a0-5ee416562bf5
[VPN-4691: Implement the 'Location Selection' in-product help sheet](https://mozilla-hub.atlassian.net/browse/VPN-4691)

VPN-4691: Add location selection help sheet

---

src/constants.h
src/mozillavpn.cpp
src/translations/strings.yaml
src/ui/screens/devices/ViewDevices.qml

**NOTE: Depends on [#8864: VPN-4687: Add DNS settings help sheet](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8864)**
- Implement help sheet for device management
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/ae55c2ec-09bf-492e-8ae0-7d5931410604
[VPN-4685: Implement the 'Device Management' in-product help sheet](https://mozilla-hub.atlassian.net/browse/VPN-4685)

VPN-4685: Add device management help sheet

---

src/constants.h
src/mozillavpn.cpp
src/translations/strings.yaml
src/ui/screens/settings/appPermissions/ViewAppPermissions.qml

**NOTE: Depends on [#8864: VPN-4687: Add DNS settings help sheet](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8864)**
- Implement help sheet for excluded apps
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/15353801/bfde51ba-a118-4824-ad77-edccd191f8da
[VPN-4690: Implement the 'App Exclusions' in-product help sheet](https://mozilla-hub.atlassian.net/browse/VPN-4690)

VPN-4690: Add excluded apps help sheet

---

nebula/ui/components/MZSignOut.qml
src/ui/screens/settings/ViewSettingsMenu.qml

- Only record `signOutSelected` events from the settings menu, instead of from all sign out buttons app-wide
- Fixes broken sign out button (button did not do anything) on other screens (subscription not found, subscription is linked with another account, update view) caused by referencing an undefined variable
[VPN-6020: [iOS] “Sign out” button from “Problem confirming subscription” error screens is not working](https://mozilla-hub.atlassian.net/browse/VPN-6020)

VPN-6020: null check telemetryScreenId in MZSignOut

---

src/controller.cpp
src/controller.h
src/feature/featurelist.h
src/mozillavpn.cpp
src/networkwatcher.cpp
src/networkwatcher.h

This PR does 2 things:
1. Check for internet connection upon activation. This is the backend code only, [frontend](https://mozilla-hub.atlassian.net/browse/VPN-3711) will be completed in a later sprint
2. Add inspector command force_connection_down to mock network connection being down.
Please note that functional tests cannot be added until the front end work is done.
https://mozilla-hub.atlassian.net/browse/VPN-5994
https://mozilla-hub.atlassian.net/browse/VPN-4987

VPN-4987 [Part 1] - Check for internet connectivity upon activation + VPN-5994 - Inspector command

---

android/daemon/build.gradle
android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/NotificationUtil.kt
android/daemon/src/test/java/org/mozilla/firefox/vpn/daemon/NotificationUtilTest.kt
taskcluster/config.yml
taskcluster/kinds/build/android.yml
taskcluster/kinds/test/junit.yml
taskcluster/kinds/test/kind.yml
taskcluster/kinds/test/taskgraph.yml
taskcluster/scripts/build/android_build_debug.sh

This is a really embarrasing bug lol. The data class for the notification has the requestScreen as `String?` however in the json we assume `String!`, therefore it throws if we do not pass that. 
Sooooo given this is clearly something a unit test would have catched, let's add junit test support on tc.

"VPN-6037 - fix de-serialisation of canned notifications" 

---

src/constants.h
src/settings/settingsmanager.cpp

The Functional tests are using the same Settings file as the normal vpn client. 
This set's settings like "only use localhost requests" which means i always need to nuke that file after running tests. 
Let's have this file per-test suite.

VPN-5594 Use a diffrent Settings File for testing and running the client!

---

taskcluster/kinds/test/junit.yml
taskcluster/kinds/test/kind.yml

This pr attempts to enable running the unit tests written in #8976. 
I originally tried to get a build artifact from the android-build task and then run the test suite against that, 
however given how glean on android works, i was unable to create a portable artifact 😭  - so for now i'm just building the project as normal.

Fix JUnit testing for android

---

taskcluster/kinds/build/windows.yml
taskcluster/scripts/build/windows_clang_cl.ps1

Currently i can only test sentry uploading on main. I've moved the upload key to level-1 which allows me to have a dry-run on pull requests.

Dry run sentry upload

---

extension/CMakeLists.txt

We only invoke cargo for vpnnp, resulting in a binary matching the host arch. 
This Pr changes the logic similar to how be build libs, invoke for every OSX_ARCH and lipo the binaries into one fat :) 
Results in: 
```
~/C/mozilla-vpn-client  file build/conda_vpn/extension/bridge/release/mozillavpnnp
build/conda_vpn/extension/bridge/release/mozillavpnnp: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
build/conda_vpn/extension/bridge/release/mozillavpnnp (for architecture x86_64):        Mach-O 64-bit executable x86_64
build/conda_vpn/extension/bridge/release/mozillavpnnp (for architecture arm64): Mach-O 64-bit executable arm64
```
closes https://github.com/mozilla-mobile/mozilla-vpn-client/issues/8855

VPN-6049 Build a fat-bin for vpnnp

---

src/ui/screens/home/ViewMultiHop.qml
src/ui/screens/home/servers/ServerList.qml
tests/functional/queries.js
tests/functional/testMultihop.js

- Add collapsible help cards back to the recommended server and multi-hop views that are only visible when the `helpSheets` feature is disabled
[VPN-6121: Expandable tooltips from Select location screens are not displayed when the “Help sheets” feature flag is disabled](https://mozilla-hub.atlassian.net/browse/VPN-6121)

VPN-6121: Reinstate recommended/multiphop collapsible cards

---

src/ui/screens/home/ViewMultiHop.qml
src/ui/screens/home/servers/ServerList.qml
tests/functional/queries.js
tests/functional/testMultihop.js

- Uplift #8983
[VPN-6121: Expandable tooltips from Select location screens are not displayed when the “Help sheets” feature flag is disabled](https://mozilla-hub.atlassian.net/browse/VPN-6121)

VPN-6121: Reinstate recommended/multiphop collapsible cards (#8983)

---

src/ui/screens/devices/ViewDevices.qml
src/ui/screens/home/ViewServers.qml
src/ui/screens/settings/ViewDNSSettings.qml
src/ui/screens/settings/appPermissions/ViewAppPermissions.qml
src/ui/screens/settings/privacy/ViewPrivacy.qml

- Updates the tooltip text for icon buttons that open help sheets from "Help" to "Get help"
[VPN-5095: Implement Accessibility requirements](https://mozilla-hub.atlassian.net/browse/VPN-5095)

VPN-5095: Fix help sheet button tooltip text

---

nebula/ui/components/MZBottomSheet.qml
nebula/ui/components/MZHelpSheet.qml
nebula/ui/themes/main/theme.js
src/ui/screens/devices/ViewDevices.qml
src/ui/screens/home/ViewServers.qml
src/ui/screens/settings/ViewDNSSettings.qml
src/ui/screens/settings/appPermissions/ViewAppPermissions.qml
src/ui/screens/settings/privacy/ViewPrivacy.qml
tests/functional/queries.js
tests/functional/testAppExclusions.js
tests/functional/testDevices.js
tests/functional/testServers.js
tests/functional/testSettings.js

- Change `MZBottomSheet` root to be a loader so that we don't always need to remember to put it in a loader during usage
- Make `MZHelpSheet`'s `contentItem` a loader so that it's content is only loaded when opened and destroyed when closed (before this, content was loaded regardless of whether the drawer was loaded/opened)
- Add help sheet margins to `theme.js
- Add functional tests for all of the help sheets
- Refactor `testAppExclusions` to be consistent with the other functional tests
*Note: A lot of the changes are caused by indentation / slight refactoring
[VPN-6124: Help sheet functional tests](https://mozilla-hub.atlassian.net/browse/VPN-6124)

VPN-6124: Help sheet improvements

---

nebula/ui/components/MZBottomSheet.qml
nebula/ui/components/MZHelpSheet.qml
src/telemetry/impression_metrics.yaml
src/telemetry/interaction_metrics.yaml
src/ui/screens/devices/ViewDevices.qml
src/ui/screens/home/ViewServers.qml
src/ui/screens/settings/ViewDNSSettings.qml
src/ui/screens/settings/ViewSettingsMenu.qml
src/ui/screens/settings/appPermissions/ViewAppPermissions.qml
src/ui/screens/settings/privacy/ViewPrivacy.qml
tests/functional/queries.js
tests/functional/testAppExclusions.js
tests/functional/testDevices.js
tests/functional/testServers.js
tests/functional/testSettings.js

- Add telemetry for help sheets
- Add impression telemetry for Devices, app exclusions, dns settings, privacy features, and select location screens
- Add functional tests for added telemetry
Miro board reference: https://miro.com/app/board/uXjVMk7nhvA=/
**Needs data review**
[VPN-5092: Implement telemetry](https://mozilla-hub.atlassian.net/browse/VPN-5092)

VPN-5092: Help sheet telemetry

---

.github/workflows/gh_pages.yaml
package.json
tools/inspector/package.json

We recently changed so that the inspector can be build as a library and the standalone client. 
Therefore we also need to update the path  as we now have`/dist/lib ; /dist/app`

Nit: fix inspector paths

---

linux/mozillavpn.service.in
src/platforms/linux/dbusclient.cpp
src/platforms/linux/dbusclient.h
src/platforms/linux/linuxcontroller.cpp
src/platforms/linux/linuxcontroller.h

We are concerned that in the event that the Linux daemon crashes, it may leave the user in an unprotected state and the VPN broken. The first step in tightening this failure mode up is to enable the automatic restart of the daemon upon an abnormal exit condition.
JIRA subtask [VPN-4226](https://mozilla-hub.atlassian.net/browse/VPN-4226)
[VPN-4226]: https://mozilla-hub.atlassian.net/browse/VPN-4226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4226: Enable automatic restart of linuxdaemon

---

src/mozillavpn.cpp

The existing logic simulates disconnection under the hood by returning "Disconnected" as the reachability value but doesn't seem to reflect in the Inspector UI that we are in NoSignal. The reachability code seems to work as expected otherwise so I think this is a Inspector limitation and we need to specifically set the Connection Health value.
n/a

Set Inspector to nosignal/stable or stable for UI purposes

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt

In investigating VPN-6129, I noticed that there were far fewer `end` pings as `start` pings for android daemon telemetry. (Over 10x difference. This was not true for iOS.) 
I believe this is due to silent server switch recording start telemetry but not end telemetry. (When the silent switch comes from the app, telemetry is not currently recorded - but when it comes from the daemon, it is.) This disconnect between when start and end pings are recorded causes this difference. This PR skips telemetry for reconnects from silent server switches.
While we could do a hacky change to the config to take advantage of the existing `shouldRecordMetrics`, I'm not sure how that state gets wiped/updated, and am reluctant to introduce hacky changes to something so core to the experience. …

VPN-6129: Android Daemon - skip telemetry on silent server switch

---

src/mozillavpn.cpp

This bug existed for the following situation:
- Have an account with five devices.
- Sign in on a new device
- Remove a device from the account as part of the sign in flow
- End up on main screen
- Force kill app
- Reopen it
- Note that you need to sign in again - not what we expected
The list of valid devices comes from the Guardian, and is saved in local settings (as the device list JSON). Upon launch, we check if the current device is in those devices, and if not, we ask the user to sign in again.
When we sign into the app when an account already has max devices, we retrieve the device list from Guardian twice - once upon initial launch, and a second time after we remove a device and add our current one. *However, we were only saving it to settings after that first retrieval.* Thus, on …

VPN-5932: Change where we save device model

---

src/feature/featurelist.h
src/feature/featurelistcallback.h

This PR re-enables Sentry on production iOS (VPN-5844).

VPN-5844: Re-enable Sentry on production iOS

---

src/controller.cpp

As a result of auditing all calls to deactivate() in the client code, the following 2 calls to `deactivate()` are flagged to be removed since they can disable the VPN without the user explicitly being aware of this.
- [controller.cpp#701](https://searchfox.org/mozilla-vpn-client/source/src/controller.cpp#701): we’re calling deactivate() Controller::connected(...) if there are no next steps. We should not be deactivating here. 
- [controller.cpp#267](https://searchfox.org/mozilla-vpn-client/source/src/controller.cpp#267): gets called in `controller::handshakeTimeout()`. We can end up in handshake timeout for example if in a multihop connection there are issues connecting to the entry or exit server, but we don’t know and can’t tell why it failed and we shouldn’t just automatically …

VPN-6145 Remove deactivate() when not needed

---

src/controller.cpp

This is a follow up on [this PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9056). Rather than removing the call to `deactivate()` entirely, we should check and still continue to deactivate if the next step is quit, update or disconnect. 
https://mozilla-hub.atlassian.net/browse/VPN-6145

VPN-6145 Only deactivate if next step is update, quit or disconnect

---

src/ui/screens/home/controller/ControllerImage.qml

This PR addresses a personal nit of mine I noticed while debugging something else: The status icon and background circle in `ControllerImage.qml` are off-center (see picture for reference). Here we adjust the positioning of said icon and circle to bring us back into alignment. 
<table>
<tr>
<th>Before</th><th>After</th>
</tr>
<tr>
<td>
Note the red circle is just the tiniest bit too low and too far left.
</td>
<td>
</td>
</tr>
</table>
VPN-6171

No ticket nit fix to better position central icon

---

ConnectionHealth.swift
src/platforms/macos/macospingsender.cpp

From prior and current investigation, iOS is crashing somewhere in this function. We don't have solid repro steps, though it's happening often enough to know we'll get a few samples a week from QA. These log lines are to start narrowing in on where the issue is. After we get crash logs from QA, we'll remove these log lines (and possibly add more logging in to figure out exactly where the problem lies). Then we'll fix it.
VPN-5766 (sorta)

Adding logging to investigate VPN-5766

---

.github/workflows/gh_pages.yaml
.github/workflows/linters.yaml
.github/workflows/linux.yaml
.github/workflows/linux_tests.yaml
.github/workflows/macos_tests.yaml
.github/workflows/ppa-automation.yaml
.github/workflows/test_unit.yaml
.github/workflows/translations.yaml
.github/workflows/wasm_tests.yaml

We are getting a lot of spurious test failures due to connection errors when installing python and node packages, so let's see if we can stabilize the tests a bit by caching these packages between test runs. Fortunately, this is something supported by the `actions/setup-node@v4` and `actions/setup-python@v4` actions, we just have to turn it on.
Github [actions/setup-node@v4](https://github.com/actions/setup-node#caching-global-packages-data) docs.
Github [actions/setup-python@v4](https://github.com/actions/setup-python#caching-packages-dependencies) docs

Nit: Enable node and pip cache in Github actions

---

src/cmake/android.cmake
src/cmake/android_openssl.cmake
src/platforms/android/sources.cmake

So from Qt 6.4 we need to also bundle openssl 3.x.x. As before, i'm going to use kdab :) 
We're keeping the 1.x, as our rust builds seem to rely on those q_q

VPN-5986 Add openssl-3 on Qt 6.4+

---

taskcluster/kinds/fetch/kind.yml

I have noticed that we seem to occasionally get download errors when fetching packages in Conda that look something like this:
```
[task 2024-02-07T17:53:39.589Z] Collecting package metadata (repodata.json): ...working... failed
[task 2024-02-07T17:53:39.602Z] 
[task 2024-02-07T17:53:39.602Z] # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
[task 2024-02-07T17:53:39.602Z] 
[task 2024-02-07T17:53:39.602Z]     Traceback (most recent call last):
[task 2024-02-07T17:53:39.602Z]       File "/opt/worker/tasks/task_169453793109859/checkouts/vcs/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
[task 2024-02-07T17:53:39.602Z]         self.chunk_left = int(line, 16)
[task 2024-02-07T17:53:39.602Z]     ValueError: invalid literal for int() with base …
```

Update taskcluster conda to 23.11.0

---

src/cmake/sentry.cmake

When compiling with vs-studio and therefore using link.exe, linking sentry fails. 
So we need to pass all libs manually, lld seems to just find this 😅

NIT: Fix Sentry Compile when using link.exe

---

taskcluster/scripts/build/macos_build.sh

It seems that the miniconda installation directory gets cached between task runs on our MacOS workers, and we run the installer with the `-u` option (for upgrade), which means that we never really install Conda and are just kind of relying on the cached version to be correct.
Unfortunately, when there are multiple versions of Conda being used by our taskcluster jobs, such as when upgrading packages, this can result in broken packages. To ensure that Conda is correctly installed, we should flush these caches when the job starts and do a fresh install.

Fix: Taskcluster/MacOS ensure a fresh install of miniconda on each run

---

nebula/ui/components/CMakeLists.txt
nebula/ui/components/MZSettingsToggle.qml
nebula/ui/components/MZToggleCard.qml
nebula/ui/components/MZToggleRow.qml
nebula/ui/themes/main/theme.js
src/translations/strings.yaml
src/ui/screens/onboarding/OnboardingDataSlide.qml
src/ui/screens/onboarding/OnboardingDevicesSlide.qml
src/ui/screens/onboarding/OnboardingPrivacySlide.qml
src/ui/screens/onboarding/OnboardingStartSlideDesktop.qml
src/ui/screens/onboarding/OnboardingStartSlideMobile.qml
src/ui/screens/settings/ViewNotifications.qml
src/ui/screens/settings/ViewPreferences.qml
src/ui/screens/settings/privacy/PrivacyFeaturesList.qml
tests/functional/queries.js
tests/functional/testOnboarding.js
tests/functional/testSettings.js

- Add `MZToggleRow` component (for toggles with labels, similar to [MZCheckBoxRow](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/nebula/ui/components/MZCheckBoxRow.qml)
- Replaces checkboxes with toggles on 
- Onboarding data slide
- Onboarding privacy slide
- Onboarding start slide (desktop)
- Privacy feature settings
- App preferences
- Notification settings
- Add dividers to
- Privacy feature list (onboarding and settings)
- App preferences
- Notification settings
[VPN-6050: UX Improvement: Switch checkboxes to toggles](https://mozilla-hub.atlassian.net/browse/VPN-6050)

VPN-6050: Change checkboxes to toggles

---

.github/workflows/linux.yaml

Fedora 37 is EOL since 2023-12-05 (cf. https://docs.fedoraproject.org/en-US/releases/eol/).
Current builds (tried e.g. `mozillavpn-2.20.0~build20240125-1.x86_64`
downloaded from https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/7661282763)
depends upon `libQt6Network.so.6(Qt_6.5_PRIVATE_API)(64bit)` but since
Fedora 39 is on Qt 6.6 no current package provides that symbol.
Also update from YUM to DNF:
* https://fedoraproject.org/wiki/Yum_to_DNF_Cheatsheet
* https://www.redhat.com/sysadmin/create-rpm-package

Update RPM build to Fedora 39

---

.github/workflows/ppa-automation.yaml
taskcluster/kinds/build/linux.yml
taskcluster/kinds/docker-image/kind.yml

Ubuntu 23.04 went EOL on January 25th, so let's update the builds to pick up the next LTS release which is currently in beta.
Ubuntu/23.04 EOL [announcement](https://lists.ubuntu.com/archives/ubuntu-announce/2024-January/000298.html)

Update builds for Ubuntu/24.04 Noble Numbat

---

CMakeLists.txt
linux/debian/control
scripts/cmake/addons.cmake
scripts/cmake/rustlang.cmake
tests/functional/addons/CMakeLists.txt

The upcoming `mz_add_new_module()` work initially required a minimum CMake version of 3.20 to cleanup dependency handling when building the VPN code as modules. But unfortunately this broke on Ubuntu 20.04/Focal which our PPA only provided version 3.18.
Well, I went and updated the PPA to provide a backport of the Ubuntu 22.04/Jammy cmake package which should now give us access to CMake version 3.22. So, let's use it and cleanup some of our outstanding hacky workarounds for older CMakes.
Github PR: #9090
Discussion: [here](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9090#discussion_r1480622632)
Backporting: https://github.com/oskirby/qt6-packaging/commit/db3b19117a337a20eef31734be98f08be522298c

Bump minimum cmake to 3.20

---

extension/bridge/src/main.rs
extension/manifests/linux/mozillavpn.json.in
extension/manifests/macos/mozillavpn.json
extension/manifests/windows/mozillavpn.json

To let the extension allow talking to the client, we need to make sure the right id is there c:
Looking at:
https://github.com/mozilla-extensions/mozilla-vpn-extension/blob/main/src/manifest.json#L8
we chose mozilla.com instead of .org

VPN-6152 - Allow WebExt to talk to VPN

---

.dictionary
.github/workflows/wasm_tests.yaml
CMakeLists.txt
docs/Building/cmake.md
docs/Components/cmake-project-structure.md
docs/index.mdx
linux/debian/rules
scripts/android/cmake.sh
scripts/cmake/utilities.cmake
taskcluster/scripts/build/ios_build_debug.sh
taskcluster/scripts/build/macos_build.sh
taskcluster/scripts/build/wasm.sh
taskcluster/scripts/build/windows_clang_cl.ps1
tests/auth_tests/CMakeLists.txt
tests/nativemessaging/CMakeLists.txt
tests/qml/CMakeLists.txt
tests/unit/CMakeLists.txt

This is extracted from my YOLO sprint PR: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8961
The modularization itself is a lot of code, but maybe we can sneakly introduce the utility to create modules and if we happen to create a new module (please raise your hand now @strseb 👀 ) we can create it in this format?
Usage examples can be found all over that PR:
- https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8961/files#diff-2660e919af9eddfb4d2b5933f6a0166edde95992e5813193b6f7eec51978a4da
- https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8961/files#diff-76a02f3395033bf965cc8168ee9e36408f914cd1b6a4f57960998abc979e087d
- https://github.com/mozilla-mobile/mozilla-vpn-client/pull/8961/files#diff-b4e86c3c2ea7c1aa8ff606965604a64b8d68866dea660318e35e2543f37372b7
- …

Introduce mz_add_new_module CMake utility

---

taskcluster/scripts/build/macos_build.sh

We recently updated the Taskcluster jobs for MacOS to use `conda-pack` for the build environment to resolve some flaky build tasks, but it seems that this change got partially reverted by a squash/merge of PR #9090, and it no longer works because of a missing fetch dependency. This should put the use of `conda-pack` back.
Github issue: #9166 ([VPN-6220](https://mozilla-hub.atlassian.net/browse/VPN-6220))
Github PR: #9090
[VPN-6220]: https://mozilla-hub.atlassian.net/browse/VPN-6220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6220: Fix MacOS Taskcluster jobs after bad squash/merge

---

linux/debian/rules
scripts/utils/xlifftool.py

Recently the VPN builds have been failing on Ubuntu/Noble. It seems like the problem is caused by change in the installation path of the Systemd service files. Because these files are generated, we wind up trying to use the installed files for `dh_systemd_install` but this is a little bit janky. So let's instead try to run `dh_systemd_install` using the generated files in the build dir instead.
Also, starting with Ubuntu/noble, we have been getting a bunch of warnings when trying to compile regex in the `xlifftool.py` script, so I figured it would be a good opportunity to fix those at the same time.
Github issue: #9166 ([VPN-6220](https://mozilla-hub.atlassian.net/browse/VPN-6220))
[VPN-6220]: https://mozilla-hub.atlassian.net/browse/VPN-6220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

VPN-6220: Fix systemd installation on Ubuntu/noble

---

src/platforms/macos/macospingsender.cpp
src/sentry/sentryadapter.cpp
src/serverlatency.cpp
src/serverlatency.h

Big credit to @oskirby for coming up with the fix after the source of the problem was identified.
iOS is closing sockets when the device is closed (and probably while the app is backgrounded), causing this crash when the device is turned back on. This makes sense as to why QA is running into this the most - as they are more likely to launch the app and immediately background it.
To reproduce:
1. Ensure VPN is off
2. Cold launch of app
3. In about a second or two, press power button to turn screen off
4. In 5-10 seconds, unlock phone (this part seemed inconsistent - the crash doesn’t happen if it’s only a couple seconds)
5. Crash happens
This PR does 3 things:
- Improves logging (removes some logging we added to diagnose the problem, adds some better logging for any future issues)
- Adds …

VPN-5766: Fix iOS crash

---

src/daemon/daemon.cpp
src/daemon/daemon.h
src/localsocketcontroller.cpp
src/platforms/linux/daemon/dbusservice.h
src/platforms/macos/daemon/macosdaemon.h
src/platforms/windows/daemon/dnsutilswindows.cpp
src/platforms/windows/daemon/dnsutilswindows.h
src/platforms/windows/daemon/windowsdaemon.h
src/platforms/windows/daemon/windowstunnelservice.cpp
src/platforms/windows/windowscommons.cpp

In order to add a bit more robustness to the VPN client, we should ensure we can recovery gracefully in the event of a crash of the daemon. This adds some handling of unexpected daemon termination and takes steps to ensure that the system remains in a usable state even if a crash occurs.
Github issue #7986 ([VPN-4227](https://mozilla-hub.atlassian.net/browse/VPN-4227))
Github issue #7987 ([VPN-4231](https://mozilla-hub.atlassian.net/browse/VPN-4231))
[VPN-4227]: https://mozilla-hub.atlassian.net/browse/VPN-4227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-4231]: https://mozilla-hub.atlassian.net/browse/VPN-4231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4227: Windows daemon recovery on crash

---

ConnectionHealth.swift

In https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9069/, I mistakenly added a stub of a file that was to be used in VPN-4979 (now on pause).

remove file

---

src/addons/manager/addonmanager.cpp
src/loghandler.cpp

Per ticket, we don't need the full file names in the logs. This PR handles the existing ones in 3 ways:
- Removes the file locations from the log line, as the same locations/names are covered by earlier logs lines.
- Uses the PII-ish log lines only when on a debug build, otherwise uses a version without the actual filename.
- In one case, only uses a log line when on a debug build, as it has limited utility otherwise.
VPN-6005

VPN-6005: strip out log names

---

src/loghandler.cpp
src/platforms/ios/ioscommons.mm

While we had the code to cleanup logs, we weren't using it. While this ticket was about iOS, I also added relevant code for all non-Android platforms.
Reason for not implementing on Android:
- On desktop platforms, we save the log file, so it can always be found.
- On iOS, we only clear logs if we get a positive signal that the user did something with the logs. (If they cancel out of the share sheet screen, the logs are not cleared.)
- On Android, we don't have a way to discover whether the user did something with the share sheet - and thus they could have canceled out without sharing the logs anywhere. In those cases, we don't want to clear the logs. And since we can't tell which type of case we're in, I'm being conservative and keeping the logs for Android.
VPN-5101

VPN-5101: cleanup logs after they are exported for iOS and desktop

---

nebula/ui/components/MZCheckBoxRow.qml
src/platforms/ios/ioscontroller.mm
src/platforms/ios/ioscontroller.swift
src/settingslist.h
src/translations/strings.yaml
src/ui/screens/settings/ViewPreferences.qml

This is here mostly for illustration purposes for now, therefore it's a draft and doesn't really require a review.
Notes:
1. CheckBox enabled setting is not doing anything. @MattLichtenstein anything that immediatelly pops out? TBH, I did not deeply investigate it given the state of this PR, but if already know what it is, good.
2. Do we want to add telemetry to the new button?
3. Can't write tests for this, because it's iOS and we don't run tests there yet.
4. A lot of copy paste from https://github.com/mozilla-mobile/mozilla-vpn-client/pull/5096
Screenshot:

VPN-5466 - Bring back LAN Bypass setting on iOS

---

.clang-tidy
CMakeLists.txt
docs/Checks/clang-tidy.md
scripts/cmake/clang_tidy.cmake
scripts/cmake/utilities.cmake
scripts/run-clang-tidy.py
src/cmake/shared-sources.cmake
src/cmake/sources.cmake

I don't think i need to pitch why we should use clang-tidy. 
given it's a tidbit non intuitive to use and i would need to write a script anyway, why not just hide all that in a cmake target to build a report. 
So if you configure the project cmake will tell you if you are ready for clang-tidy, , otherwise it will tell you what to do. 
If all ready, we add a new target  `cmake --build <build_dir> --target clang_tidy_report`, builds a folder containing a .yaml file for each target. each file contains the notes, errors and suggestions. 
The task "fails" if checks that marked as errors throw (see .clang-tidy), allowing us to inform and enforce in CI. 
If suggestions are generated they can then be aplied with `clang-apply-replacements`
Also i added a docs page :) …

VPN-4769 Add Clang-Tidy 

---

.github/workflows/test_unit.yaml

Windows unit tests are flaky with 
```
Downloading Wintun, as WINTUN_FOLDER is unset
CMake Error at windows/tunnel/CMakeLists.txt:11 (file):
file DOWNLOAD cannot compute hash on failed download
status: [22;"HTTP response code said error"]
-- Configuring incomplete, errors occurred!
ninja: error: loading 'build.ninja': The system cannot find the file specified.
```
We only care about wintun when buulding the client, so providing a nonexistent path still stops the download and
should make it less flaky

Nit: Stop downloading wintun for Unit-Tests

---

scripts/cmake/utilities.cmake
src/cmake/sources.cmake

in #9239 i added support for clang tidy, trying to not add dependencies if the clang_tidy target was not created. 
I did not consider that those can depend on targets that are not created for all plattforms i.e sentry is not built on 32bit android.
This caused all 32bit android builds to go bust on main, while the PR was green. 
given this, let's add a util that adds dependencies between 2 targets if they both exist, so it's a bit more clean :)

Fix TC android builds

---

signature/Cargo.lock
signature/Cargo.toml
signature/src/balrog.rs
signature/src/lib.rs
src/constants.h
src/feature/featurelist.h
src/feature/featurelistcallback.h
src/update/balrog.cpp
src/update/balrog.h

We need to do some testing against Balrog staging over the next few months. We used to use Balrog stage for QA testing, but this resulted in a lot of manual work for SRE, and our QA channel was moved to Balrog prod in #4741 in order to better automate our release and QA process. We are basically adding this back, but putting it behind a feature flag.
However, the content signing root CA for Balrog staging is up for renewal, so it is also important to implement a little more flexibility when handling the root hash pinning when switching to Balrog stage. In order to do this, we have refactored the API to the `signature` crate in order to migrate the root hash verification job into the Qt/C++ world.
Github PR removing balrog stage: #4741
Bugzilla staging CA rotation: …

VPN-6236: Re-introduce Balrog staging as a feature

---

src/ui/screens/settings/ViewReset.qml

This PR removes `property bool wasNavbarVisible` from ViewReset.qml to fix VPN-6215 because:
- `wasNavbarVisible` overwrites the [default navbar visibility handling](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/162e1b947fcd83252d73dbbe4340f72010d160ca/src/ui/main.qml#L179-L190) which causes the navbar to erroneously stay visible after logout. 
- The `wasNavBarVisible` property is not needed given navbar visibilit is handled in the above code chunk, even when on the Get help menu and Get help sub pages.
VPN-6215

VPN-6215 : Fix navbar visibility after viewing reset options

---

scripts/cmake/utilities.cmake
src/hacl-star/kremlin/minimal/fstar_uint128_msvc.h
src/platforms/windows/daemon/windowsdaemon.h
src/platforms/windows/daemon/windowsfirewall.cpp
src/platforms/windows/daemon/windowsroutemonitor.cpp
src/platforms/windows/daemon/windowstunnellogger.cpp
src/platforms/windows/daemon/windowstunnelservice.cpp

For clang& gcc we set `-Wall -Werror -Wno-conversion`
for windows we skip this. I just noticed a warning and thought, let's fix them all :)

Nit: Compiler Warnings as Errors when using MSVC

---

src/platforms/ios/PingAnalyzer.swift
src/platforms/ios/iostunnel.swift

[VPN-4979](https://mozilla-hub.atlassian.net/browse/VPN-4979) was planned to be a set of 3 PRs:
1. Set up connection health monitoring (https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9146)
2. Add silent server switching (https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9288)
3. Add telemetry (to be done after step 2 is merged)
This could be considered 1.5 - it fixes a bug I introduced when making some last minute changes in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9146. 
I went through a few ways to write this (we don't want to use `guard` here, as that can't fall through, though it's somewhat stylistically appropriate), and I went back and forth. Unfortunately, I left a bug in my final change:
```
let endpointIP = String(describing: endpointHost) …
```

Fix up for VPN-4979 part 1

---

.clang-tidy
.dictionary
CMakeLists.txt
docs/Checks/clang-tidy.md
scripts/cmake/clang_tidy.cmake
scripts/cmake/generate_translations_target.cmake
src/cmake/shared-sources.cmake
taskcluster/kinds/source-test/clang.yml
taskcluster/kinds/source-test/kind.yml
taskcluster/scripts/source-test/clang-tidy.ps1

This PR adds taskcluster jobs to run clang-tidy. Given we have diffrent c++ source files for each plattform i did create Tasks covering Android,Windows,Macos which should cover most users. 
iOS and Linux should be easy to add, but given this pr is already 27 commit's this will be a Followup. 
I also touched the clang-tidy file, adding a few checks, however only `clang-analyzer-security.*` will produce errors, therefore can block merging, for now :)

Run Clang-Tidy on taskcluster

---

src/constants.h

The root CA for signing Balrog update messages is due to expire in 2025, and a new root certificate has been prepared for prod. Let's add the fingerprint of the new root to Balrog so that the CA transition can be handled smoothly.
Bugzilla [1882147](https://bugzilla.mozilla.org/show_bug.cgi?id=1882147)

Bugzilla 1882147: Add fingerprint for new AMO production root CA to Balrog

---

tests/functional/testSubscription.js

We have been seeing a bunch of flaky test failures in the `testSubscription.js` functional test. This seems to occur when checking the subscription management links, and the logs appear to show the test failing to register a click of the various subscription management buttons. I suspect that the cause of the failure is clicking too soon after opening the subscription management view, so we try to work around it by waiting for the stackview to finish its transition.

Chore: Fix flaky subscription test

---

src/commands/commandui.cpp
src/main.cpp

So far when building in MZ_DEBUG we allocated a console instead of using the perfectly fine ones in my IDE >:( 
This pr changes so that we attach to a parent console if it exists, so the client behaves the same way like we do on MacOS. (just as broken lmao) 
This also enables use to use the cli. 
https://mozilla-hub.atlassian.net/browse/VPN-2656

VPN-2656 Support Windows CLI 

---

nebula/ui/components/MZCheckBox.qml
nebula/ui/components/MZList.qml
nebula/ui/components/MZViewBase.qml
nebula/ui/components/forms/MZSearchBar.qml
src/ui/screens/settings/appPermissions/AppPermissionsList.qml
src/ui/screens/settings/appPermissions/ViewAppPermissions.qml

The "App Exclusions" screen used a Repeater for the list items, which required all application names and their icons to be obtained when the screen was loaded. Obtaining icons is expensive, and slowed screen load. Switch this to ListView, which lazily loads list items as they become visible in the viewport. This allows icons to be obtained only when needed and improves screen load time.
The following additional changes were required to switch to ListView:
1. The MZViewBase parent is a flickable and ListView is also a flickable. To prevent conflicts, the MZViewBase has been marked interactive:false. 
2. The ListView is implemented in MZList, with its own ensureVisible() which is used to scroll an item in the flickable into the visible part of the viewport.
3. The controls before and after …

VPN-6021: Improve "App Exculsions" screen load time by switching from Repeater to ListView

---

nebula/ui/components/MZSettingsToggle.qml

This is a hack to prevent default checkboxes from appearing over our stylized toggles on Windows. We do  the same thing [here ](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/d9aca561a638cf2985ac9d60ed56502844cd6b85/nebula/ui/components/MZCheckBox.qml#L25)in MZCheckbox. 
Here is a crummy video taken with my iPhone since screen casting on Windows seems (at least at current energy level) non-trivial. 
https://github.com/mozilla-mobile/mozilla-vpn-client/assets/22355127/3023bd79-d10f-4149-81fd-4ef6cff13443
VPN-6224

VPN-6224: Prevent default checkboxes from appearing on hover 

---

src/platforms/ios/ConnectionHealth.swift
src/telemetry/metrics.yaml

Adding telemetry to iOS health checks in the network extension. Similar work was done for Android in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9057.
VPN-4979

VPN-4979 part 3: Add telemetry to iOS health checks

---

taskcluster/scripts/toolchain/conda_pack_ios.sh
taskcluster/scripts/toolchain/conda_pack_macos.sh

It seems our machines now have recieved a global pip config restricting download from the moz-pip mirror.
```
ask 2024-04-15T16:32:39.715Z] env_var:
[task 2024-04-15T16:32:39.715Z] env:
[task 2024-04-15T16:32:39.715Z] global:
[task 2024-04-15T16:32:39.716Z]   /Library/Application Support/pip/pip.conf, exists: True
[task 2024-04-15T16:32:39.716Z]     install.no-index: true
[task 2024-04-15T16:32:39.716Z]     install.disable-pip-version-check: true
[task 2024-04-15T16:32:39.716Z]     install.find-links: 
[task 2024-04-15T16:32:39.716Z]     https://pypi.pub.build.mozilla.org/pub/
[task 2024-04-15T16:32:39.716Z]     install.trusted-host: 
[task 2024-04-15T16:32:39.716Z]     pypi.pub.build.mozilla.org
[task 2024-04-15T16:32:39.716Z]     global.disable-pip-version-check: true
[task …
```

Let Conda-Pack on Macos use Pypi

---

src/connectionhealth.cpp

Just notice this log message is a bit too chatty. See, for example: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/9348

Chore - Remove spammy log message

---

src/localsocketcontroller.cpp

After a bunch of debugging, I realized that the problem went away when we didn't flush the logs.
And I remembered that I recently changed the behavior of log flushing, which would be why this is a recent bug: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9231 (It's me, hi, I'm the problem it's me)
Digging into *why* flushing logs caused the problem, it was because of a race condition between asking for backend logs and flushing the logs. We reset the `m_logCallback` after we get the daemon's response with backend logs (as we'd expect), but we also clear `m_logCallback` when asking to flush the logs. Since both requests were being made before the daemon returned with the backend logs, `m_logCallback` was null by the time we wanted to use it with the first request.
This chunk of …

VPN-6251: fix backend logs

---

src/settingslist.h

We've been asked to add this to be default excluded .

Make Android auto default excluded

---

.github/workflows/linters.yaml
android/AndroidManifest.xml
android/build.gradle
android/buildSrc/build.gradle.kts
android/buildSrc/src/main/kotlin/Config.kt
android/buildSrc/src/main/kotlin/SharedDependencies.kt
android/common/src/main/java/org/mozilla/firefox/qt/common/CoreApplication.kt
android/daemon/build.gradle
android/daemon/src/main/AndroidManifest.xml
android/daemon/tunnel/CMakeLists.txt
android/daemon/tunnel/libwg-go/Makefile
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
android/qtglean/build.gradle
android/settings.gradle
android/vpnClient/build.gradle
env.yml
qtglean/Cargo.lock
qtglean/android.cmake
qtglean/glean_parser_ext/templates/rust_pings.jinja2
qtglean/ios.cmake
qtglean/src/lib.rs
qtglean/src/uploader.rs
src/cmake/android.cmake
src/telemetry/metrics.yaml
src/telemetry/pings.yaml
taskcluster/docker/lint/Dockerfile

~We should do the same for Android. Let's do it in a separate PR because this is currently breaking CI IIUC.~
Doing Android here since fixing things for iOS broke them for Android.

VPN-6290 - Stop using the glean sdk generator script

---

src/connectionhealth.cpp
src/dnspingsender.cpp
src/dnspingsender.h

In the logs we see errors, however they are currently unhandled. 
So let's assume start as failable. Also we can now abort whenever something is wierd.

VPN-6267 Respect Errors of DNSPingsender

---

src/translations/extras/extras.xliff

This pull request adds the en xliff file for languages and servers as an extra for translations.
This file will replace language.json and servers.json.
Whenever a new language / server is added we simply add a new entry to this file. 
After talking to @flodolo and Santiago we decided not to migrate over the currency translations, the gist being: they are all the same, so doesn't seem to be a point anyways.
The part where I actually remove languages.json and servers.json will come in a follow up PR. For now this is here to be a companion to https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/435

VPN-5175 - Add the extras.xliff en file, which will replace languages and servers.json

---

addons/message_update_v2.22/manifest.json

In my haste to get the "Update" addon messages out the door, I neglected to check my work against the Figma file, and I must shamefully admit that I got the content of the strings completely wrong. This PR attempts to update the strings accordingly to match the design documents. 
There is a small discrepancy in that we have a paragraph separating `How to reset Mozilla VPN:` and the ordered list which follows, as I don't think we can create a text block that includes an ordered list, so they wound up as separate blocks.
JIRA issue: [VPN-6307](https://mozilla-hub.atlassian.net/browse/VPN-6307)
Figma designs: [here](https://www.figma.com/file/Disx2dX7tw81NQIN39BrYo/In-app-Messaging?type=design&node-id=2979-430&mode=design&t=RqBsLawIkiVWea7c-0)
Previous attempt: #9396
[VPN-6307]: …

VPN-6307: Fix update message to match Figma

---

addons/message_whats_new_v2.22/manifest.json

In my last attempt to author a "What's New" addon message, I neglected to check the figma docs and got the strings completely wrong. This should attempt to set the strings right and get us as close to the Figma file as possible.
There is a small discrepancy in that we have a paragraph separating `How to reset Mozilla VPN:` and the ordered list which follows, as I don't think we can create a text block that includes an ordered list, so they wound up as separate blocks.
JIRA issue: [VPN-6306](https://mozilla-hub.atlassian.net/browse/VPN-6306)
Figma designs: [here](https://www.figma.com/file/Disx2dX7tw81NQIN39BrYo/In-app-Messaging?type=design&node-id=2979-430&mode=design&t=RqBsLawIkiVWea7c-0)
Previous attempt: #9395
[VPN-6306]: https://mozilla-hub.atlassian.net/browse/VPN-6306?atlOrigin=eyJpI …

VPN-6306: Fix what's new addon message to match Figma

---

src/translations/strings.yaml
src/ui/screens/home/ViewMultiHop.qml
src/ui/screens/home/servers/ServerList.qml

The collapsible info cards in the server lists are a thing of the past now that we have help sheets. This PR removes them from the server list views.
VPN-6327

VPN-6327: Remove server list info cards and associated strings

---

android/vpnClient/build.gradle

We reverted to 5.2.0 due to a crash. 
>I tried to add the desugar_jdk_libs with the right version as dependecy to the vpnClient project, but then I get the error "Execution failed for DexingNoClasspathTransform". 
Well now those deps have been upgraded to the latest one (thanks @brizental ) , i just tired bumping the version, iAP works fine now :)

VPN-6333 Bump BillingLib from 5.2.0 to 5.2.1 

---

android/vpnClient/build.gradle

Cherry-pick of PR #9424 to the `releases/2.22.0` branch in order to unblock release candidate uploads to Google Play.
JIRA issue: [VPN-6333](https://mozilla-hub.atlassian.net/browse/VPN-6333)
Github PR #9424
[VPN-6333]: https://mozilla-hub.atlassian.net/browse/VPN-6333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cherry-pick VPN-6333: Bump Android billinglib to v5.2.1

---

taskcluster/kinds/beetmover-apt/kind.yml
taskcluster/mozillavpn_taskgraph/transforms/beetmover_apt.py

From our side we have nothing that would block us to publish to the Mozilla APT instead of the PPA. 
So this pr (fixes my failed merge) and also enables beetmover-apt.

VPN-6208 Enable Beetmover apt

---

src/platforms/android/androidcommons.cpp
src/platforms/android/androidcommons.h
src/platforms/android/androidiaphandler.cpp
src/platforms/android/androidvpnactivity.cpp

`runOnAndroidThreadSync` was a thing in Qt5, so obviously when upgrading we just replaced it with `AndroidCommons::runOnAndroidThreadSync`. 
This obviously can lead to deadlocks, i.e if we're waiting to run a task on the main thread but i.e an Accessbility Service is trying to read the screen info from the Qt Thread. 
None of the callsites actually require the code to be run in sync, so it's better for the callsites to use the QFuture returned and decide what to do :)

VPN-6340 Remove Multithreading Footgun

---

taskcluster/kinds/source-test/clang.yml

I really should fix that upstream 😅 
The conda-rust-package set's `CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER` to a nonexistent path in the env which makes cargo fail to find the linker. Therefore compilation of the crate fails -> source_test cannot continue.

Nit, try to fix source-test-android

---

.github/workflows/auth_tests.yml
.github/workflows/macos_tests.yaml

The auth tests are currently broken for MacOS, this is probably going on for a long time.
The issue is the same we had and fixed for MacOS functional tests, so this is very stright forward.
We should monitor this failures more closely though.

VPN-5971 - Use Conda environment on MacOS auth tests

---

android/daemon/src/main/AndroidManifest.xml

> Declare new permission to use foreground service types
If apps that target Android 14 use a foreground service, they must declare a specific permission, based on the foreground service type, that Android 14 introduces. 
https://developer.android.com/about/versions/14/changes/fgs-types-required#permission-for-fgs-type
We did add a type here 
https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/android/daemon/src/main/AndroidManifest.xml#L9 
We did not add the permission, so the connection fails

VPN-6344 Add missing permission

---

scripts/android/conda_setup_qt.sh

This is the error: https://firefox-ci-tc.services.mozilla.com/tasks/Wi-gr5dLRval_TEDLPp8OQ/runs/0/logs/public/logs/live.log
```
Use release config./scripts/android/cmake.sh: line 134: /builds/worker/fetches/Qt/6.6.3/android_armv7/bin/qt-cmake: Permission denied
```
Looking at the packed conda env, it seems the exectutable bit was not set on this file, so let's manually do that.

Nit: Fix Android-Armv7 builds

---

nebula/ui/components/MZLinkButton.qml

This PR fixes the alignment of the focus indicator in MZLinkButton {}. 
<table>
<tr>
<th colspan="3">After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</td>
</table>
VPN-6330

VPN-6330: Fix focus ring alignment in MZLinkButton

---

.github/workflows/wasm_tests.yaml
nebula/ui/components/inAppAuth/MZInAppAuthenticationBase.qml
nebula/ui/components/inAppAuth/MZInAppAuthenticationInputs.qml
nebula/ui/components/inAppAuth/MZInAppAuthenticationThirdParty.qml
src/frontend/navigator.cpp
src/inspector/inspectorhandler.cpp
src/ui/authenticationInApp/ViewAuthenticationSignIn.qml
src/ui/authenticationInApp/ViewAuthenticationSignUp.qml
src/ui/authenticationInApp/ViewAuthenticationSsoAccount.qml
src/ui/authenticationInApp/ViewAuthenticationStart.qml
src/ui/authenticationInApp/ViewAuthenticationStubAccount.qml
src/ui/authenticationInApp/ViewAuthenticationUnblockCodeNeeded.qml
src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml
src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByTotpNeeded.qml
src/ui/deleteAccount/ViewDeleteAccountRequest.qml
src/ui/screens/home/controller/ip/IPInfoPanel.qml
src/ui/screens/home/servers/ServerCountry.qml
src/ui/screens/home/servers/ServerList.qml
src/ui/screens/settings/ViewReset.qml
tests/functional/helper.js
tests/functional/queries.js
tests/functional/testAuthenticationInApp.js
tests/functional/testAuthenticationInAppErrors.js
tests/functional/testDevices.js
tests/functional/testFactoryReset.js
tests/functional/testIpInfo.js
tests/functional/testMultihop.js
tests/functional/testServerSearch.js
tests/functional/testServers.js
tests/functional/testSubscription.js

I have been seeing a bunch of auth functional tests failing in CI due to an assert in `QTest::mouseEvent()` due to a null `QWindow` pointer. After some digging, I think this is really a consequence of the bug noted by [VPN-3697](https://mozilla-hub.atlassian.net/browse/VPN-3697), where we encounter a race condition between the rendering thread and the GUI thread.
To resolve this, we should poke the rendering thread and wait for the frame draw to finish before submitting the click to the window. This should ensure that the QML scene graph is synchronized with the QML content before we process the click event.
Some subtle changes that revealed some bugs:
- Sending the click to `item->window()` can actually click things that are offscreen, and sending the click to the root window revealed a …

VPN-6356: Fix assert in QTest::mouseEvent()

---

CMakeLists.txt

In https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9400/
we switched to qml_modules and the paths were updated. On my Mac with Qt 6.6.3 the app no longer finds main.qml.
In Qt6.5+ the way qml_modules path works have been changed https://doc.qt.io/qt-6/qt-cmake-policy-qtp0001.html. 
```
The OLD behavior of this policy is that, the RESOURCE_PREFIX argument for qt_add_qml_module() defaults to ":/".
The NEW behavior of this policy is that the RESOURCE_PREFIX argument for qt_add_qml_module() defaults to ":/qt/qml/". The new behavior ensures that modules are put into the [QML Import Path](https://doc.qt.io/qt-6/qtqml-syntax-imports.html#qml-import-path) and can be found without further setup.
```
Looking at 
```
const QUrl url(QStringLiteral("qrc:/Mozilla/VPN/main.qml")); …
```

Fix QML paths for Qt6.5+

---

src/constants.h

This PR removes references to 'en-US' from urls in `constants.h` so that folks visiting these pages from the client are presented the page content in the language their browser has been configured to use instead of in english by default.

No ticket: Remove en-US from constants urls

---

ci_scripts/ci_post_clone.sh

We already pack a conda-env with qt to compile iOS in Taskcluster. 
We can simply re-use that in xcode cloud. 
This upgrades all builds to 6.6.0

VPN-4677 Use Conda (with qt 6.6) in XCode-Cloud 

---

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/VPNActivity.java

In case we kill the activity before the serviceconnection is valid, for example when writing speedy integration tests, 
this will cause a crash :)

Nit: Only try to unbound the Daemon if it exists

---

scripts/android/cmake.sh
taskcluster/mozillavpn_taskgraph/transforms/build.py

It is important for Android building that the version code orders the build APKs by architecture, with the 32-bit architectures first, and the 64-bit architectures having higher versions. Failing to do so will result in rejection by Google Play because they will incorrectly assume that we fail to support 64-bit.
To correct this, we need to share a consistent timestamp (which is used to generate the version code) across all the tasks, regardless of when they actually start. I think we can do this by grabbing the `build_date` taskgraph config and setting it as an environment variable in the build jobs.
The current strategy here simply truncates the current time to try and get a similar number, which works-ish, but leaves us with a race condition when the truncated value rolls over and can …

VPN-6370: Try to set a consistent build timestamp for APK build ordering.

---

src/sentry/sentryadapter.cpp

One annoying thing right now is that sentry does not parse our versions. So if we mark something fixed on 2.23 (which is on stage) but we push a 2.22.1 hotfix still with that bug, the bug will be re-opened until a newer release is created. 
That is because sentry currently goes by "when was this release first seen" vs "what does the number say". 
For that we need to pass that string formatted using semver. 
With that pr i created a test crash: see semver is now "yes" for 2.23.
https://mozilla.sentry.io/releases/mozilla-vpn%402.23.0/?project=4504197915607040

Nit: [Sentry] - Pass version using semver

---

src/ui/sharedViews/ViewFullScreen.qml

Small UI tweaks to improve the visibility of factory reset view elements on mobile. 
<table>
<tr>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
</table>
VPN-6351

VPN-6351 Improve visibility of ViewReset elems

---

.github/workflows/i18n_server_list_update.yaml

Workflow is currently broken (missing deps), and has the same name of another workflow.

Fix workflow to update server names

---

.github/workflows/auth_tests.yml
.github/workflows/cloudflare_pages.yml
.github/workflows/gh_pages.yaml
.github/workflows/linters.yaml
.github/workflows/linux.yaml
.github/workflows/linux_tests.yaml
.github/workflows/macos_tests.yaml
.github/workflows/ppa-automation.yaml
.github/workflows/test_unit.yaml
.github/workflows/translations.yaml
.github/workflows/wasm_tests.yaml

There are currently over 100 warnings in checks, mostly due to obsolete GitHub actions.

Reduce warnings in GitHub workflows

---

.github/workflows/gh_pages.yaml

There is a step in this workflow that only runs for pushes on main, so I missed it.
Not completely sure that updating the actio version will fix it, but it seemed to work on my fork.

Fix GH pages workflow (update deploy action)

---

.github/codecov.yml
.github/workflows/auth_tests.yml
.github/workflows/linux_tests.yaml
.github/workflows/macos_tests.yaml
.github/workflows/test_unit.yaml

Codecov has never really worked all that great, and hasn't had someone to maintain it since @mozrokafor left the team. So in the interest of cutting down on needless work and maintenence burden, we should just remove it from our CI jobs.
None

Remove code coverage from github actions.

---

taskcluster/kinds/docker-image/kind.yml

Ubuntu 24.04 Noble Numbat was officially released on April 25th and can now be considered stable. We should enable the docker image cache for this build.
None

Chore: Enable taskcluster docker cache for Ubuntu/noble

---

scripts/utils/generate_language_names_map.py

For some reason I thought it would be a good idea to fallback to the translation for "English" in whatever language if the translation for the actual language name was not present. So, say the translation for `es_CL` is missing for `es_CL` we would instead get the translation for `en` ("Inglés") instead of leaving it blank and letting Qt do the translation... 🤦‍♀️

VPN-5156 - Do not fallback to English on language name map

---

src/ui/screens/settings/ViewPreferences.qml

This PR addresses the following QML warnings in ViewPreferences.qml
```
[22.04.2024 16:46:57.653] Warning: qrc:/ui/screens/settings/ViewPreferences.qml:114:13: QML MZSettingsItem: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (ViewPreferences.qml:114)
[22.04.2024 16:46:57.653] Warning: qrc:/ui/screens/settings/ViewPreferences.qml:135:13: QML MZSettingsItem: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. (ViewPreferences.qml:135)
[22.04.2024 16:46:57.653] Warning: qrc:/ui/screens/settings/ViewPreferences.qml:153:13: QML MZSettingsItem: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead. …
```

No ticket: Fix layout related console warnings in ViewPreferences.qml

---

nebula/ui/components/MZScreenBase.qml
src/ui/CMakeLists.txt
src/ui/screens/messaging/ViewMessage.qml
src/ui/screens/messaging/ViewMessagesInbox.qml

Ok, something funky is happening with the Qt6.6 imports.
Here is the thing, this patch fixes it. But I kinda hate the way it fixes it, makes no sense.
Opening as a draft, as food for thought. It seems sometime Qt6.6 is unable to resolve QML files in the same module???? cc @lesleyjanenorton for QML knowledge.

VPN-6375 - Fix QML modules import

---

taskcluster/kinds/repackage-signing/kind.yml
taskcluster/kinds/signing/kind.yml

The old cert expires June 19, 2024.
https://bugzilla.mozilla.org/show_bug.cgi?id=1894209

Bug 1894209 - use new certificate for windows code signing

---

scripts/android/cmake.sh

This Glean hack we have cmake.sh would not clean itself up after a failed build and leave the glean 3rdparty module dirty. I fixed it.

Not ticket - Make the Glean Android hack a bit less bad

---

src/platforms/ios/ioscontroller.swift
src/platforms/ios/iostunnel.swift
src/platforms/ios/iostunnelmessage.swift

iOS connection time has a bug when following these steps:
1. Start the VPN
2. Wait 10 seconds or so
3. Switch servers (timer will not reset)
4. Hard quit the app
5. Relaunch the app. The timer should still be counting up from the original connection time, but instead it's jumped back 10 seconds - to when the server switched.
This is because when the app starts up use the iOS network extension's timestamp as the connection start time (which the count up timer comes from). The iOS network extension's timestamp is the last time we connected to any server, which is a different definition of session start than we're using. (We do not want to turn off the timer until the user turns off the VPN - user-generated or silent server switches should result in the timer continuing to increment without …

VPN-2367: Save iOS start time

---

scripts/android/cmake.sh

I believe we missed a character in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9510/. Build timestamp was being set to the string `s`, and thus it was failing downstream.
VPN-6390

Fix android build script

---

.github/workflows/linux_tests.yaml
.github/workflows/macos_tests.yaml
.github/workflows/wasm_tests.yaml
nebula/ui/components/MZStackView.qml
nebula/ui/components/MZStepNavigation.qml
nebula/ui/components/navigator/MZNavigatorLoader.qml
src/inspector/inspectorhandler.cpp
src/ui/screens/home/controller/ip/IPInfoPanel.qml
src/ui/screens/home/servers/ServerCountry.qml
src/ui/screens/home/servers/ServerList.qml
tests/functional/helper.js
tests/functional/queries.js
tests/functional/setupWasm.js
tests/functional/testAuthenticationInApp.js
tests/functional/testAuthenticationInAppAccountCreationNav.js
tests/functional/testDevices.js
tests/functional/testInitialize.js
tests/functional/testIpInfo.js
tests/functional/testOnboarding.js
tests/functional/testServers.js
tests/functional/testSettings.js
tests/functional/testSubscriptionNeeded.js

These just seem to make the tests take far longer than necessary and make it harder to spot flaky tests. Besides, we already have the `--retries 3` option passed to mocha when running tests. We shouldn't need retries ontop of our retries.
This revealed the following test instabilities, which will need to be fixed for this to land:
None! Just my own personal annoyance.

Nit: Remove GHA retries for failed tests

---

tests/functional/testAuthenticationInBrowser.js

Spotted in the wild, a flaky [testAuthenticationInBrowser](https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/9136718785/job/25125964448) and I think this can be fixed simply by waiting for the stackview to load.
`None`

Nit: Maybe fix a flaky testAuthenticationInBrowser test

---

linux/debian/control
scripts/utils/qt6_compile.sh
taskcluster/kinds/toolchain/qt.yml
taskcluster/scripts/toolchain/compile_qt_6_mac.sh

To fix the missing fonts for Qt static builds, we need to rebuild Qt with fontconfig support (which also requires `-system-freetype`) and we patch up a missing `libxcb-cursor0` dependency too while we are at it.
However! Because this just so happened to touch the Qt build scripts, we also needed to address some breakage in MacOS due to a busted homebrew install. In this case, I opted to just ditch homebrew and use conda because it's already a part of our build tooling anyways. 
JIRA issue: [VPN-6330](https://mozilla-hub.atlassian.net/browse/VPN-6330)
[VPN-6330]: https://mozilla-hub.atlassian.net/browse/VPN-6330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6330: More Linux static packaging fixes

---

src/ui/screens/settings/appPermissions/AppPermissionsList.qml

This fixes the unusually large "+" icon in the '+ Add application' button in AppPermissionsList.qml.
After:
VPN-6227

VPN-6227: Use correct theme variable in AppPermissionsList.qml

---

linux/netfilter/netfilter.go
src/cmake/linux.cmake
src/controller.cpp
src/controller.h
src/daemon/wireguardutils.h
src/platforms/linux/daemon/linuxfirewall.cpp
src/platforms/linux/daemon/linuxfirewall.h
src/platforms/linux/daemon/wireguardutilslinux.cpp
src/platforms/linux/daemon/wireguardutilslinux.h
src/rfc/rfc4291.cpp
src/rfc/rfc4291.h

The approach for these firewall rules is "deny by default". I have added two new chains to our Linux firewall configuration:
```
chain mozvpn-input {
type filter hook input priority filter; policy drop;
meta iiftype loopback accept
iifname "moz0" accept
meta protocol ip meta l4proto udp @nh,96,32 @mozvpn-addrset accept
ip6 saddr fc00::/7 accept
ip6 saddr ff00::/8 accept
ip saddr 10.0.0.0/8 accept
ip saddr 172.16.0.0/12 accept
ip saddr 192.168.0.0/16 accept
ip saddr 224.0.0.0/4 accept
udp sport 68 ip daddr 255.255.255.255 udp dport 67 accept
udp sport 68 udp dport 67 accept
}
chain mozvpn-output {
type filter hook output priority filter; policy drop;
meta oiftype loopback accept
oifname "moz0" accept
meta protocol ip meta l4proto udp @nh,128,32 @mozvpn-addrset accept
ip6 daddr fc00::/7 …
```

VPN-5865 - Move a few rules from ip rules to the firewall

---

taskcluster/mozillavpn_taskgraph/transforms/beetmover_apt.py

For the 2.23 release, we would like to automate the promotion of static linux builds to the stage APT repository for QA and internal testing. To do so, I think we need to check the `shipping_phase` config option and direct releases to the `release` bucket and non-releases to the `dep` bucket.
JIRA issue [VPN-6392](https://mozilla-hub.atlassian.net/browse/VPN-6392)
[VPN-6392]: https://mozilla-hub.atlassian.net/browse/VPN-6392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6392: Allow promote-client to stage repository for beetmover-apt

---

taskcluster/mozillavpn_taskgraph/transforms/beetmover_apt.py

The scopes aren't set up properly and there's some oddities (like using the `dep` bucket in production relpro). It seems these tasks aren't quite ready to run in production releases, and they are holding up release candidates. So let's disable them there for now.

ci: Don't run beetmover-apt tasks as part of relpro yet

---

.github/workflows/auth_tests.yml
.github/workflows/macos_tests.yaml
.github/workflows/test_unit.yaml
tests/functional/testAddons.js
tests/unit_tests/qml/a.qml
tests/unit_tests/testlocalizer.cpp
tests/unit_tests/testqmlpath.cpp

This PR updates macos functional tests and macos and windows unit tests to run with Qt 6.6.3. There are two workarounds to be cognizant of:
1. testlocalizer.cpp and testaddons.js were updated to accommodate a change in datetime formatting as of CLDR 42, which replaced the regular white space "10:00 AM" with a _narrow_ no break space "10:00 AM". Qt adopted CLDR 42 in v6.5 which means that our Linux tests, which are still using Qt 6.2.4, expect a white space but tests running with anything after v6.5 expect the narrow no-break space. I've left more detailed comments and links to the relevant ephemera in those files. 
2. After _much_ going back and forth with adding and removing Qt features from Qt6_compile in #9615 to no avail, I've resorted to commenting out three tests in QMLPath that …

Run unit tests and macos functional tests with Qt 6.6.3

---

taskcluster/kinds/beetmover-apt/kind.yml
taskcluster/mozillavpn_taskgraph/transforms/beetmover_apt.py

We want to have two tasks, one for promote and one for ship. The bucket / scopes that gets used should depend only on which of these tasks is running, and the tasks should then get filtered out at the target phase.
We also remove the 'filter_shipping' transforms because these tasks will get filtered at the target phase. The generation (aka full) phase doesn't need to be doing any pre-filtering of its own.

ci: split 'beetmover-apt' into promote and ship tasks

---

src/extrastrings.h
src/ui/screens/devices/ViewDeviceLimit.qml

@flodolo [pointed out](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9484#discussion_r1626396386) that I missed a couple strings in #9484 that were being done the old way.
For the macOS installer string (in `extrastrings.h`), I've maintained the old way of doing translations as we have little translation work in the C++ layer. In part for quickness of a fix (to not have to learn how to pass a variable from new translation system via C++ to our mac installer - and that mac installer is an area of our codebase I'm not familiar with at all), I'm suggesting we keep using the old translation system in this one case.
N/A

Follow up to VPN-5969 - fix final 2 strings

---

src/sentry/sentryadapter.cpp
src/settings/settingsmanager.cpp

On windows it seems we're not properly cleaning up those. 
Leakdetector is complaining >:(

Nit: proper cleanup on shutdown

---

src/ui/screens/home/controller/ControllerView.qml

Short story: This PR makes a two line tweak to the controller view to fix VPN-6151. 
Longer story: Depending on the locale, text in the controller view occasionally changes from a single line to multiple lines when connecting/disconnecting and requires 'special handling' to maintain evenly distributed vertical space without repositioning the vpn toggle button and changing the overall size of the containing purple background square. At some point in quasi-recent history, that handling was dropped for the controller subtitle text (but only when the VPN is on). This PR restores that handling so that the subtitle text can reposition itself correctly. 
VPN-6151

VPN-6151: Fix vertical alignment of text in controller view

---

src/mozillavpn.cpp
src/mozillavpn.h
src/platforms/ios/ioscommons.h
src/platforms/ios/ioscommons.mm
src/ui/screens/initialize/ViewInitialize.qml
tests/auth_tests/mocmozillavpn.cpp
tests/qml/mocmozillavpn.cpp
tests/unit/mocmozillavpn.cpp
tests/unit_tests/mocmozillavpn.cpp

This ended up being a bug on iOS 16 only, so the fix only affects iOS 16 and below. Somehow the status bar type is getting reset to `default`, causing the issue here. I checked all the places our code resets it to default, and it didn't seem to be happening in any of those spots - so I made this fix.
Once our minimum iOS version is iOS 17, we can remove this code - and I've left notes in the code that remind us of this.
VPN-2387

VPN-2387: Fix iOS status bar color on iOS 16

---

.github/workflows/translations.yaml
README.md
docs/Building/macos.md
docs/Building/windows.md
docs/index.mdx
env.yml
taskcluster/kinds/build/ios.yml
taskcluster/kinds/build/macos.yml
taskcluster/kinds/build/windows.yml
taskcluster/kinds/fetch/kind.yml
taskcluster/kinds/toolchain/conda_osx.yml
taskcluster/kinds/toolchain/qt.yml

This PR: 
- Removes Mac and Windows next builds and bumps release and pr builds to 6.6.3
- Removes qt-hotfix and qt-windows-x86_64-6.2.4 toolchains
- Removes ios TC next build, and bumps ios-arm64/debug to 6.6.0
- Updates QT_VERSION in env.yml to 6.6.3
- Updates static links and references to 6.2.4 in Mac and Windows build docs
VPN-6384, VPN-6382, VPN-5563

Update Mac and Windows builds to 6.6.3

---

qtglean/CMakeLists.txt

Recently, I have found myself unable to build tests on MacOS, which ends with the following linker error:
```
Undefined symbols for architecture arm64:
"_SCDynamicStoreCopyProxies", referenced from:
system_configuration::dynamic_store::SCDynamicStore::get_proxies::h7cf43ef2a47c43d1 in libqtglean.a(system_configuration-5a1250e520b516c2.system_configuration.6155de0b-cgu.4.rcgu.o)
"_SCDynamicStoreCreateWithOptions", referenced from:
system_configuration::dynamic_store::SCDynamicStore::create::hcb281992b6c549d9 in libqtglean.a(system_configuration-5a1250e520b516c2.system_configuration.6155de0b-cgu.4.rcgu.o)
"_kSCDynamicStoreUseSessionKeys", referenced from:
system_configuration::dynamic_store::SCDynamicStoreBuilder$LT$T$GT$::create_store_options::h5b5370c6a1f89759 in …
```

Nit: Fix reqwest/libglean dependencies on MacOS

---

CMakeLists.txt

This PR bumps CMAKE_OSX_DEPLOYMENT_TARGET for mac from `10.5` to `11.0`, which is the minimum supported platform for macos in Qt6.6. 
VPN-6445

VPN-6445: Bump macos deployment target

---

src/app.cpp
src/app.h
src/logoutobserver.cpp
src/logoutobserver.h
src/mozillavpn.cpp
src/mozillavpn.h
src/platforms/ios/iosiaphandler.mm
src/ui/main.qml
src/ui/screens/getHelp/contactUs/ViewContactUsForm.qml
src/ui/sharedViews/ViewUpdate.qml
tests/functional/helper.js
tests/functional/testAuthenticationInApp.js
tests/functional/testDevices.js
tests/functional/testFactoryReset.js
tests/functional/testSubscription.js
tests/unit/testaddon.cpp
wasm/presets.js

Spotted in the wild: a flaky [testSubscription.js](https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/9281903149/job/25539154427?pr=9617).
This was hauntingly familliar to a bug I fixed in one of my experimental hackathons in which `vpn.authenticateInApp()` returns success as soon as we get to the `UserAuthenticated` state but the model initialization is still waiting on a bunch of tasks to finish. If this happens during the initial test setup, and we quit before those jobs finish -  we are left with a settings file that is incomplete (the token is set but no keys are) and all the subsequent test jobs fail to load.
To fix this properly, I think the best approach is to combine the `App::state` and `App::userState` states together to eliminate potential race conditions …

Nit: Combine App::state and App::userState to fix test races

---

scripts/macos/conda_setup_qt.sh

if `scripts/macos/conda_setup_qt.sh` fails due to a network error we still continue and cache that. 
This butched the iOS conda toolchain. So let's fix that, and let it fail so tc can resheudle..

Fix iOS toolchain generation

---

tests/unit_tests/CMakeLists.txt
tests/unit_tests/main.cpp
tests/unit_tests/qml/a.qml
tests/unit_tests/testqmlpath.cpp

The `TestQmlPath` test has been failing for me on Qt 6.6.0 and later, and after a bit digging I traced the crash down into the depths of Qt, which was failing at `qquickpathview.cpp:68:75` with the expression `QGuiApplicationPrivate::platformIntegration()` returning a null pointer. This occurs because the app unit tests are invoked as `QCoreApplication` instead of a `QGuiApplication` so the platform integration plugins are never initialized, leading to the segmentation fault in the QML engine.
There are two reasonable ways to fix this issue:
1. We move this test case into the QML Tests, which does initialize the Gui and QML engine, or
2. We just convert the app unit tests into a GUI application.
I have gone with option 2 here.
JIRA issue: …

VPN-6423: Fix TestQmlPath on Qt 6.6.0 and later

---

nebula/ui/components/MZDropShadowWithStates.qml
src/captiveportal/captiveportaldetection.cpp
src/commands/commandstatus.cpp
src/controller.cpp
src/controller.h
src/inspector/inspectorhandler.cpp
src/networkwatcher.cpp
src/statusicon.cpp
src/systemtraynotificationhandler.cpp
src/tasks/controlleraction/taskcontrolleraction.cpp
src/tasks/controlleraction/taskcontrolleraction.h
src/ui/screens/home/controller/ControllerImage.qml
src/ui/screens/home/controller/ControllerView.qml
src/ui/screens/home/controller/VPNToggle.qml
src/webextensionadapter.cpp
tests/functional/helper.js
tests/functional/testWebExtensionApi.js
tests/functional/utils/webextension.js
tests/qml/moccontroller.cpp
tests/unit/moccontroller.cpp

This pull request introduces support for a new StateOnPartial state in the controller, enhancing the VPN's state management. It also adds an ActivationPrincipal enum to track whether a connection was initiated by a user or an extension, along with corresponding permission checks for deactivation. Additionally, this update includes several new methods and refines existing ones to handle the new state and activation principal, ensuring improved VPN control and security.

VPN-5992 Allow extensions to request Access to the Proxy Network

---

src/platforms/macos/macoscryptosettings.h
src/platforms/macos/macoscryptosettings.mm

As noted in the discussion of #9584 we have a need to be a bit smarter in how and when we enable cryposettings on MacOS. Traditionally this was done at compile time by doing a no-op for the `getKey()` in the dummy builds, but this should really be done by examining the processes' entitlements to know whether the binary can access the encrypted settings. The entitlement that guards this access is the `keychain-access-group` permission.
Normally, when this entitlement is missing, the user is greeted with a login prompt asking for the user's password before permitting them access to the keychain, which is a minor annoyance for developers. This PR will also make unsigned developer builds fall back to plaintext settings instead of triggering such a prompt.
Inciting PR: #9584 
Discussion: …

MacOSCryptoSettings: Disable encryption if keychain entitlement is missing

---

src/cmake/msvc.cmake

When compiling with MSVC (VisualStudio 2019), the compilation fails with on a warning in `winbase.h` due to macro expansion rules:
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: macro expansion producing 'defined' has undefined behavior
```

MSVC: Disable warning 5105 to fix error in winbase.h

---

src/platforms/windows/windowsutils.cpp
src/update/balrog.cpp
src/update/balrog.h

Thanks to -> https://github.com/mozilla-releng/balrog/issues/3071 
We can now add the OS version to balrog requests to depricate specific versions. 
This PR adds the env::Osversion into that request. Also we change the behavior of windows detection, we just report build number. Otherwise we can only select for "Windows 11 or Windows 10" vs windows 11-22-H1.  
Just see how many builds there are 💀 
https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information
https://learn.microsoft.com/en-us/windows/release-health/release-information

VPN-5588 Add OS Version to balrog requests

---

addons/message_update_v2.23/manifest.json
addons/message_update_v2.23/osCheck.js

Checking OS via a JS condition.
I don't believe this adds any translations, but perhaps those strings did something weird? I'm not sure why @flodolo got auto-added to this PR.
This PR overrides https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9686. However, I'm keeping that one open for now - I asked whether we want to modify that to add the condition in, so that we can use it in the future once enough users are on a version that include that condition.
Also, I might be doing over-defensive code with this check: `if (!osVersion || (typeof osVersion !== "string") || osVersion.length === 0)`. I don't write JS often; please let me know if there is a better way to do this.
VPN-6473

VPN-6473: check for OS in addons

---

src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml
tests/functional/queries.js
tests/functional/testSettings.js

Now that this is a public feature, we're removing it from the dev menu.
I also removed the test. I kept the currently-unused developer screen menu in `tests/.../queries.js` in case we want to use it in the future. Happy to remove it if y'all think it would be cleaner.
VPN-6487

VPN-6487: Remove "reset and quit" from dev menu

---

src/addons/conditionwatchers/addonconditionwatchertriggertimesecs.cpp

Have you been experiencing unstable unit tests in the `TestAddon::conditionWatcher_group()` test case? Well we have an exciting, limited time offer for you! A fix to the addon condition time calculation now available for the low LOW price of one r+ to this simple PR!
The gist of the issue is that addon condition times are specified in seconds relative to the installation time, but the installation time is stored in milliseconds. The truncation in handling the expiration calculation can result in a second of jitter around the actual emission of the `conditionChanged()` signal. Sometimes, when the jitter overlaps we can wind up with the conditions going true in reverse order, which is what causes this test to fail.
To fix this, I felt the best approach was to do all the math in …

Nit: Fix timing jitter in AddonConditionWatcherTriggerTimeSecs

---

src/telemetry/metrics.yaml

---
In https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9057/, we added several new metrics to measure connection health. From that PR: `We're adding 9 new metrics, and removing a bunch as well. We think that some subset of these 9 will be most useful, but aren't quite sure. Thus, these metrics all will live for about 6 months, and we'll then evaluate the data and decide which ones to keep in perpetuity.`
Unfortunately, according to our Product Manager, we're still figuring out how to best analyze this new data in Looker, and these metrics expire in 2 weeks. This PR adds another 9 months to continue the experiment of figuring out which subset should get an expiration of "never", and which should be removed.
N/A

Extend metric expiration date

---

tests/functional/setupWasm.js

Sometimes, when a Wasm functional test fails and gets rerun, the log files are mangled and a closer examination shows that they are full of null characters. This seems to be due to a bug in how we handle the lot output from the Firefox webdriver, which doesn't really truncate the logs correctly.
A synopsis of how this bug occurs:
1. The `beforeAll()` hook spawns the webdriver and tells it to write Firefox's `stdout` to a file.
2. The `afterEach()` hook checks for the results of the test, dumps the log file to the test runner's console, and then truncates the log file.
3. However! Because the file descriptor passed to Firefox is still open, it is still pointing at some offset way into the file.
4. The next time firefox writes anything the write occurs at an offset, and Linux does a sparse …

Fix log truncation in Wasm tests

---

src/mozillavpn.cpp
src/notificationhandler.cpp
src/notificationhandler.h
src/platforms/linux/linuxcontroller.cpp
src/translations/strings.yaml

This adds a system tray notification which is triggered upon a connection failure, and connects it to the controller errors.
JIRA Issue: [VPN-5589](https://mozilla-hub.atlassian.net/browse/VPN-5589)
[VPN-5589]: https://mozilla-hub.atlassian.net/browse/VPN-5589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5589: Add system tray notification for connection failures

---

linux/netfilter/netfilter.go
src/platforms/linux/daemon/linuxfirewall.cpp

The killswitch code on Linux doesn't handle crashes very well, and can be left in place after the daemon crashes. Unfortunately, the kill switch gets in the way of the recovery by preventing the client from re-establishing a connection after restart. To try and clean this up, we do two things:
1. Combine the firewall tables into one to make manual recovery easier (eg: `sudo nft delete table inet mozvpn-inet`), and
2. Delete any existing tables in the `LinuxFirewall` constructor to get back to a known state after recovery.
Linux daemon recovery issue: [VPN-4226](https://mozilla-hub.atlassian.net/browse/VPN-4226)
[VPN-4226]: https://mozilla-hub.atlassian.net/browse/VPN-4226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-4226: Linux firewall cleanup upon crash/restart

---

src/connectionhealth.cpp
src/controller.cpp
src/controller.h
src/mozillavpn.cpp
src/ui/main.qml
tests/unit/testconnectionhealth.cpp

In #8826 and #9174 a subscriber reports occasionally getting erroneously disconnected from the VPN (through no action of their own) and seeing the 'Server Unavailable' modal upon reopening the client. 
We hypothesize this is caused by the subscriber's connection becoming `Unstable`, whereupon we go into a silent server switch which fails sending us into the server unavailable routine and eventual disconnection. 
#8978 attempted to resolve this by adding logic to the server unavailable routine to check if the state is `StateSilentSwitching` or `StateOn` and bypassing the call the deactivate if so. This treatment was insufficient because, by the time we get to `ServerUnavailable`, the user is either in `StateConfirming` or `StateConnecting`. 
In this PR we remove the call to deactivate from …

VPN-6228: Don't deactivate during silent server switches

---

src/controller.cpp

A few lines were added in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9639, and they broke server switching on iOS. (Notably, it works on macOS - this seems to be iOS-specific.) While I'm deeply curious why an additional time setting the state to Connecting would cause this behavior (and would love to dig deeper to understand *why* this caused the behavior), the most time-judicious fix seems to be wrapping this new code in a platform flag to not run it on iOS.
VPN-6495

VPN-6495: fix iOS server switching bug

---

.dictionary
docs/Components/daemon.md

We have a need to better document how the daemon works, why we need it, and how it is expected to recover in the event of a crash. This PR should add a new document at `docs/Components/daemon.md` with the desired details.
JIRA Issue: [VPN-6252](https://mozilla-hub.atlassian.net/browse/VPN-6252)
[VPN-6252]: https://mozilla-hub.atlassian.net/browse/VPN-6252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6252: Add Daemon Documentation

---

.github/workflows/linux.yaml

Fedora 40 was released on 2024-04-23,
cf. https://discussion.fedoraproject.org/t/announcing-fedora-linux-40/114034
Current builds (tried `mozillavpn-2.23.0~build20240425-1.x86_64`
downloaded from https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/8833883299)
depend upon `libQt6Qml.so.6(Qt_6.6_PRIVATE_API)(64bit)` but since
Fedora 40 is on Qt 6.7 no current package provides that symbol.

Update RPM build to Fedora 40

---

src/platforms/android/androidcontroller.cpp

In PR #9674 we tried to improve the LAN exclusion implementation for Windows and Linux. However, this introduced a bug in Android where the LAN exclusion calculation would cause routes to the internal Mulvad network to get lost. This causes the VPN's connectivity checks to fail, and results in the client entering the `No Signal` state shortly after connecting.
The cause of the bug is that `IPAddress::excludeAddresses()` doesn't handle routes nested inside an excluded route. For example, `excludeAddresses({"0.0.0.0/0", "10.64.0.1/32"},{"10.0.0.0/8"})` will ignore the route to `10.64.0.1` because it is excluded by `10.0.0.0/8` despite having a longer prefix length.  
JIRA issue: [VPN-6523](https://mozilla-hub.atlassian.net/browse/VPN-6523)
Previous PR: #9674
[VPN-6523]: …

VPN-6523: Fix Android LAN exclusions

---

addons/message_update_v2.24/osCheck.js

Update criteria for showing the "update to latest version" addon message. We don't want to show it on Android or iOS (most mobile users get automatic updates), and we do not want to show it on macOS versions less than 11.0 (our current minimum requirement).
VPN-6529

VPN-6529: Do not show update message for any Android or any iOS or macOS 10.x.

---

Cargo.lock

```
linux-build/src/ui/mozillavpn-ui_autogen/LWZFM5XUEJ/moc_VPNServerCountryModel.cpp /__w/mozilla-vpn-client/mozilla-vpn-client/BUILD/mozillavpn-2.24.0~build20240802/src/ui/singletons/VPNServerCountryModel.h
2024-08-02T16:21:41.0873817Z error[E0282]: type annotations needed for `Box<_>`
2024-08-02T16:21:41.0883588Z   --> /__w/mozilla-vpn-client/mozilla-vpn-client/BUILD/mozillavpn-2.24.0~build20240802/signature/vendor/time/src/format_description/parse/mod.rs:83:9
2024-08-02T16:21:41.0892295Z    |
2024-08-02T16:21:41.0904521Z 83 |     let items = format_items
2024-08-02T16:21:41.0914971Z    |         ^^^^^
2024-08-02T16:21:41.0921127Z ...
2024-08-02T16:21:41.0940724Z 86 |     Ok(items.into())
2024-08-02T16:21:41.0941497Z    |              ---- type must be known at this point …
```

Update cargo deps for "time" 

---

src/controller.cpp
src/controller.h
src/webextensionadapter.cpp

Currently we dont communicate since "when" we're connected to the VPN. The extension is going to show the time, so lets pass it.

[webExt] Let the client communicate the connectionTime

---

addons/message_update_v2.24/osCheck.js

Egg on my face from VPN-6529: I missed an early return, and that meant the check kept evaluating. On line 29/30, we `enable` the addon in all cases - so when the macOS check was disabling the addon, it was being re-enabled a few lines later.
VPN-6540

VPN-6540: Add missing return to addons condition

---

android/vpnClient/build.gradle

Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9761 to the 2.24.0 release branch

Cherry pick Android billing library update to release branch

---

src/telemetry/metrics.yaml

In https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9057/, we added several new metrics to measure connection health. I wanted `ping_analyzer_error` to be a short term metric used as a gut check to make sure nothing was erroring out around here. When the original PR was put up on May 23rd, I was far too optimistic that it would be approved and released with at least a few weeks to go before July 15th (the metric expiration date). 
At this point, 2.24 (the release this metric is first part of) is not yet out, and the metric is already expired - we've gathered no data from it. (Even worse, when we extended several of the expiration dates a few weeks ago in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9710, I mistakenly thought we had data from `ping_analyzer_error` …

Extend `ping_analyzer_error` expiration date

---

src/telemetry/metrics.yaml

Cherry pick https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9773

Cherry pick to 2.24: extend ping_analyzer_error expiration date

---

src/feature/featurelist.h
src/feature/featurelistcallback.h
src/proxycontroller.cpp

The local proxy currently is a bit hard to enable: 
-> You need to be in stage mode 
-> you need split tunnel 
-> you need to have the binary in a certain place. 
And if one of those fails, we silently fail. 
Let's make it a featureflag, with the precondition of "is windows | linux" and use the featureflag mechanism to allow it to turn it on, make it default on in stage :) 
This also makes it look on "Debug" builds inside the build dir instead of an "install" like folder, making setup better. 
Also add logs if things fail so people can self troubleshoot.

Nit: Make ProxyController a featureflag

---

src/platforms/windows/daemon/windowsfirewall.cpp

Previously, on the LAN bypass saga, our heros sought to make LAN bypass better by utilizing route cloning to direct traffic outside of the VPN tunnel, which required the addition of a new method `WindowsFirewall::enableLanBypass()` to specifically permit LAN traffic through the firewall that would be otherwise blocked by the "Block internet" rule.
Unfortunately, this filter rule shared the same weight as the DNS killswitch rule in `WindowsFirewall::enableInterface()` which makes it unclear which firewall rule will apply to DNS traffic sent to the LAN. This means that a web browser might start before the VPN and decide that the user's LAN should be used for DNS, fail to detect that the VPN has changed DNS configuration, and then merrily continue to use the LAN for its DNS resolution so …

VPN-6517: Fix contention between LAN bypass and DNS killswitch on Windows

---

Cargo.lock

Builds are failing due to some breakage in the `time` crate. This was fixed in `main` by PR #9768 so let's cherry-pick that onto `releases/2.24.0` as well.
Github PR #9768

Cherry pick:  Update cargo deps for "time"

---

src/platforms/windows/daemon/windowsfirewall.cpp

Cherry-pick of PR #9795 to `releases/2.24.0` to fix a leaky DNS killswitch.
PR to main: #9795
JIRA issue: [VPN-6517](https://mozilla-hub.atlassian.net/browse/VPN-6517)
[VPN-6517]: https://mozilla-hub.atlassian.net/browse/VPN-6517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cherry-Pick VPN-6517: Fix contention between LAN bypass and DNS killswitch on Windows

---

src/update/balrog.cpp
src/update/balrog.h

Balrog computes its file hashes by converting the hash to a hex string and then comparing it to the hash string received from Balrog. While this works, it is sloppy and it means that hash comparisons can fail depending on case sensitivity. The better approach is to compare hashes as a `QByteArray` so that the string case doesn't matter.
JIRA issue: [VPN-6569](https://mozilla-hub.atlassian.net/browse/VPN-6569)
[VPN-6569]: https://mozilla-hub.atlassian.net/browse/VPN-6569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6569: Compute balrog installer hashes as QByteArrays

---

scripts/addon/build.py

When coming up to speed on addon translations as part of VPN-5478, I noticed this quirk. I can't find a reason why it would exist (other than an error), so I'm putting up this patch.
`locale_file_fallback` is the file for a given fallback language's translations (`ts` file type), built from `translations_fallback[locale]`. However, we never do anything with `locale_file_fallback` after creating it - however we again use the `translations_fallback[locale]` in creating the final translation pack. (Additionally, for languages with multiple fallback languages, we overwrite `locale_file_fallback` each time, as we use the source language's abbreviation in creating the filename, not the fallback language - so it ends up overwritten if there are 2 fallback languages.) This all seems like an …

Addons: Fix fallback languages

---

.github/workflows/test_unit.yaml

The Windows unit tests have been extremely brittle lately, and they frequently fail to download the Wireguard NT driver. Let's see if we can stabilize this by using a cache to save this artifact between builds.

Cache Wireguard-NT for windows unit tests

---

macos/pkg/scripts/postinstall.in

We've found that it's possible to corrupt a Mozilla VPN installation through the use of misplaced symlinks inside the application directory, therefore we should introduce some extra checks to detect this situation and error out early during the installation process.
While we're at it, we can also do a little bit of tidying up to the postinstall script.
JIRA Issue [VPN-6572](https://mozilla-hub.atlassian.net/browse/VPN-6572)
[VPN-6572]: https://mozilla-hub.atlassian.net/browse/VPN-6572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6572: Add extra checks for symlinks in MacOS/postinstall script

---

windows/installer/MozillaVPN.wxs

Given QA's ticket mentions they uninstall the old version, using wix_upgrade detected is not sufficient. So let's just "ask" w10 users to reboot after installation :)

VPN-6448 try to scheudle a reboot on w10 (2.24 only)

---

.github/workflows/ppa-automation.yaml
taskcluster/kinds/build/linux.yml
taskcluster/kinds/docker-image/kind.yml

Ubuntu/23.10 Mantic Minotaur has reached EOL status as of June 11th this year, and as such we should no longer be attempting to build it.
EOL Announcement: https://lists.ubuntu.com/archives/ubuntu-announce/2024-June/000302.html

Deprecate Ubuntu/23.10 Mantic Minotaur

---

src/webextensionadapter.cpp
src/webextensionadapter.h
tests/functional/testWebExtensionApi.js

We cannot stop people from installing the extension if "localProxy" is not a thing. So let's have the extension be able to query feature flags that are relevant for it. 
This can allow the webextension to work, simply without that functionality if the client does not support that.

Let the extension query relevant featureflags

---

tests/functional/testWebExtensionApi.js

I have noticed that the `tetWebExtensionApi.js` has been failing, and the test ends with
```
4 passing (22s)
1 failing
1) WebExtension API
A Webextension can get a Subset of the Featurelist:
TypeError: this.isFeatureEnabled is not a function
at Context.<anonymous> (tests/functional/testWebExtensionApi.js:97:39)
```
I think this was a simple typo. The test was calling `this.isFeatureEnabled()` when it ought to have called `vpn.isFeatureEnabled()`.

Maybe fix testWebExtensionApi.js

---

.github/workflows/ppa-automation.yaml

It is a little bit annoying to have to manually update the list of current Ubuntu releases everytime something new comes along or a release goes EOL. So why not automate it by pulling the release data directly from the [distro-info-data](https://launchpad.net/ubuntu/+source/distro-info-data) repository and computing which releases are active.

Experiment: Attempt to automate PPA release selection

---

.github/workflows/linux.yaml
.github/workflows/ppa-automation.yaml

Starting September 2nd, Github workflows now exclude all hidden files and directories from the `actions/upload-artifact` workflows by default. This is intended as a security measure to make it harder to accidentally export and upload credential files.
However, this breaks our `Linux/Source` workflow which stages the sources in `.tmp` before passing them onto another task, and it has been the reason the Linux workflow has been failing ever since.
See: https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/

Set include-hidden-files in the Linux/Source workflow

---

.github/workflows/ppa-automation.yaml

In my last round of PPA automation hacking, I attempted to auto-generate the list of current Ubuntu distributions by fetching the distro-info-data repository and parsing the Ubuntu release data for EOL and release date.
Unfortunately, I left a typo in the file that led to a corrupted github outputs. Shame on me!
The workflow ends with an error message like the following:
```
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'releasesfocal jammy noble oracular '
```
PR Introducing the issue: #9828

Fix typo in ppa-automation workflow

---

src/mozillavpn.cpp
src/ui/screens/home/controller/ControllerImage.qml
src/ui/screens/home/controller/VPNToggle.qml
tests/functional/helper.js
tests/functional/testSettings.js

Here we:
- Stop loading the Home, Settings, and Messages screens "Persistently" in favor of loading them "Temporarily"
- Fix UI flickering in ScreenHome when the Screen loads and which becomes much more noticeable when the view is loaded every time the home button is clicked.  
- Annoyingly: I can't say with 100% confidence _why_ these changes, mostly to how we name states and assign property changes, fixes the flicker but I suspect that assigning state changes conditionally with `when: someConditionIsTrue` was causing the FOUC.  
- Also annoyingly: The main toggle still fades in somewhat noticeably. This is fixable but less trivial to fix and, given the a11y wins we gain by doing this, is I think acceptable. 
<table>
<th>Before flicker fixes <br>(Note the toggle wiggliness)</th><th>After …

VPN-2876: Stop loading screens persistently

---

src/constants.h

Slow down some of the staging checks. I couldn't find any other super-frequent ones that are more frequent than they are on prod. (There are some "once per second" checks, but they're that way on both staging and prod.)
N/A

slow staging checks

---

linux/flatpak/flatpak-update-crates.sh
linux/flatpak/flatpak-vpn-crates.json

Looks like there was a bug in the script used to update flatpak package dependencies. Notably the argument count check is incorrect which causes the script to run exclusively by pulling cargo.lock from main. Unfortunately this breaks PRs which attempt to update the `Cargo.lock` file, such as our dependabot PRs.
The fix is simply to correct the conditional check, but we also add some logging to the script to be extra sure where it is fetching the `Cargo.lock` file from.
Introduced by: #9798

Fix bug in flatpak crate update script

---

nebula/ui/components/MZSignOut.qml
src/controller.cpp
src/controller.h
src/mozillavpn.cpp
src/mozillavpn.h
src/ui/main.qml
src/ui/screens/ScreenSubscriptionInUseError.qml
src/ui/screens/devices/ViewDeviceLimit.qml
tests/qml/moccontroller.cpp
tests/unit/moccontroller.cpp

We have something of a race condition in the handling of the logout proceedure whenever the VPN is active. This seems to be due to some spaghetti code around this proceedure and being a bit too overzealous in our efforts to deactivate the VPN. 
The race condition goes something like this:
1. The user clicks a `Sign Out` button somewhere in the QML, which invokes `Controller::logout()`
2. `Controller::logout()` then calls `MozillaVPN::logout()` to clear out state and log out:
- Schedules a task to remove the device's public key.
- Schedules a task to deactivate the VPN.
- Flush out the application state, erase settings, and reset.
3.  `MozillaVPN::logout()` returns, and execution continues in `Controller::logout()` which then immediately deactivates the VPN.
4. The device removal task …

VPN-6570/VPN-6583: Fix logout race condition when VPN is active

---

tests/functional/setupVpn.js
tests/functional/testFactoryReset.js

I think I have managed to figure out a possible race in the functional tests when restarting the VPN client. What we see sometimes is that the client needs to be terminated, and restarted for some reason. The race goes something like this:
1. The client is instructed to quit by sending a `quit` command over the inspector. This does little more than dump a string into a websocket and return.
2. Quitting, for whatever reason, takes a bit of time as destructors run, threads are reaped, telemetry is sent and so on.
3. Meanwhile, the test carries on and a new client is launched via `setup.startAndConnect()`
4. The new client, in `EventListener::checkForInstances()` finds that the UI socket is still alive, because the last client hasn't finished quitting. So the new client sends message over …

Fix possible test race when restarting the VPN client

---

.gitignore
src/proxycontroller.cpp
src/proxycontroller.h

Ohno who wrote all that? 
The biggest culprit for an endless loop is this
```c++
mCrashSignal = QObject::connect(
mCurrentProcess, &QProcess::finished, [this](){ ..., start()}
```
So whenever the proxy would exit, we would try to reboot it, which sounds sensible. *IN THEORY* 
Except that i did forget to remove that listener when we actually want to stop it. i.e we switch servers or disconnect, or extra fun in `QObject::connect(mCurrentProcess, &QProcess::errorOccurred,`. 
This means on any error we call  
```
QProcess::errorOccurred -> calls stop() -> triggers QProcess::finished -> calls start() -> which given we have a m_process calls kill() -> WHICH TRIGGERS QProcess::errorOccurred  -> which calls stop() -> ....
```
- so stop now actually removes signals from the about to be killed …

Avoid Start loops for localproxy

---

src/webextensionadapter.cpp

We have a few states where the error can only properly be solved by the VPN client. i.e Not Subbed, not authed. 
So let's give the extension the ability to summon the vpn window to the foreground to address those issues :) 
https://github.com/user-attachments/assets/0d1a12fc-b3b9-4ce5-ae86-cde5769f861a

Nit: Add Commands to help troubleshoot errors

---

src/ui/screens/authenticationInApp/ViewAuthenticationInApp.qml
tests/functional/helper.js
tests/functional/queries.js

There seems to be a race in the authentication helpers during functional testing. This results in a hang during the login (often breaking a test in the `beforeEach` step), and it tends to fall over as the authentication view fails to receive a click event after setting the user email.
I suspect this is caused by the asynchronous QML loader used in `ViewAuthenticationInApp.qml` which means that the QML is being loaded in a background task, making it somewhat uncertain what happens if we try to interact with the screen. I think that by adding a `ready` property we can wait for the loading to finish before proceeding with the authentication steps.

Maybe fix test race in authentication helpers

---

src/settingslist.h
src/ui/screens/onboarding/OnboardingStartSlideDesktop.qml
tests/functional/testOnboarding.js

https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9818/ introduced a couple issues (in order of importance):
1) When upgrading to 2.24, users who have never changed their "start on boot" preference got updated from false to true. (Today I learned that the default setting is not written in local storage - Updates to a settings are written to local storage, and otherwise we use the default. So changing the default affects existing users.)
2) The VPN was turned on at the end of onboarding (this is only expected for iOS), with a session timer that is not 0:00 (as it got turned on during the user's onboarding).
This PR fixes this by creating a temporarily boolean used during onboarding, and sets the "start on boot" setting to that temporary boolean as the user passes the onboarding …

VPN-6593: Improve start on boot

---

docs/rfcs/0005-suggested-excluded-apps-tech-spec.md
src/telemetry/impression_metrics.yaml
src/telemetry/interaction_metrics.yaml
src/translations/strings.yaml
src/ui/screens/settings/ViewReset.qml
src/ui/screens/settings/ViewSettingsMenu.qml
src/ui/screens/settings/appPermissions/AppPermissionsList.qml
src/ui/screens/settings/appPermissions/ViewAppPermissions.qml
tests/functional/testAppExclusions.js

A quick string change.
- I also changed dev-only strings (test descriptions and some markdown docs) for consistency for future maintainers of the app.
- I couldn't find a spot where we still use `infoText2`, so I removed that string.
- The help info sheet for the feature already used the "excluded apps" nomenclature, so there was nothing to update there.
VPN-6580

VPN-6580 change 'App Exclusions' to 'Excluded Apps'

---

src/ui/screens/onboarding/OnboardingStartSlideDesktop.qml
tests/functional/testOnboarding.js

This reverts commit 7a16aa76aefa8c68e1215032e5de52e74ed4d301 from the 2.24.0 release branch. It came in yesterday as https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9880
It was intended to fix a blocking bug, but did not. Thus, we're backing it out to increase confidence in the release.
Note: This code remains on `main` branch.

Revert cherry pick of VPN-6593

---

src/networkrequest.cpp
src/networkrequest.h
src/update/balrog.cpp

The update check task has been fairly noisy in the logs which is due to Balrog returning a 404 status code whenever there are no updates available and the `NetworkRequest` task handles this as an error when it is really the expected the response in this case.
To suppress some of the noise in the logs, let's extend the `NetworkRequest` class so that it can accept more than one expected status code, and let's not treat it as an error when we happen to receive one of the expected status codes.
After this change, the log messages for a typical run of Balrog, when no updates are available, now looks like this:
```
[17.09.2024 10:44:32.700] (Updater) Debug: Updater created
[17.09.2024 10:44:32.701] (Balrog) Debug: Balrog created
[17.09.2024 10:44:32.701] (Balrog) Debug: URL: …
```

Nit: Suppress Balrog network errors

---

.github/workflows/ppa-automation.yaml

In the change to the PPA automation workflow, we did a bit of refactoring to submit a second package, the `mozilla-vpn-keying`, to the testing PPAs. However, we missed that the github `runner` context isn't defined at the job level which means we can't set the `GNUPGHOME` variable globally like we can all the others.
Introduced by #9839

Fix GNUPGHOME variable in PPA automation workflow

---

taskcluster/kinds/build/linux.yml
taskcluster/kinds/fetch/kind.yml
taskcluster/kinds/toolchain/qt.yml

Doing a bit of an update cycle to our Qt taskclusters jobs. This should settle on Qt 6.6.3 for all of the release targets, and then upgrades the Qt/next targets to version 6.7.2 (the latest release as of today).
Most notably, this should upgrade the Linux static builds to 6.6.3 from 6.2.4, which was the last straggler on 6.2.x (excluding the PPA packaged builds, which we don't have any real control over).
As a minor annoyance, I wish we didn't have the Qt version number in the artifact URL for the Windows and MacOS builds, but we can't really change those because they are relied on externally via the Github CI jobs.
JIRA Issue: [VPN-6598](https://mozilla-hub.atlassian.net/browse/VPN-6598)
[VPN-6598]: https://mozilla-hub.atlassian.net/browse/VPN-6598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

VPN-6598: Update taskcluster Qt jobs to 6.6.3

---

windows/installer/MozillaVPN.wxs

We have a bit of an obnoxious bug in our Windows MSI installer, when running the installer multiple times the installer is started in maintenence mode which attempts to minimize the changes to the system by leaving unmodified files in place. Unfortunately, this causes the installer to behave inconsistently depending on whether it is running in upgrade or maintenence mode.
To fix this, we make an attempt to detect this situation (using the Wix condition `Installed and NOT (REMOVE="ALL") AND NOT REINSTALL`) and then force the re-installation of the VPN client by setting the `REINSTALL` property. This condition checks that:
- `Installed` is true, which means that an existing VPN installation was found on the system.
- `NOT (REMOVE="ALL")` means that the MSI was not invoked for …

VPN-6953: Force MSI reinstallation when in maintenence mode

---

src/platforms/windows/daemon/windowsdaemon.cpp
src/platforms/windows/daemon/windowsdaemon.h
src/platforms/windows/daemon/windowsfirewall.cpp
src/platforms/windows/daemon/windowsfirewall.h
src/platforms/windows/daemon/windowssplittunnel.cpp
src/platforms/windows/daemon/windowssplittunnel.h
src/platforms/windows/daemon/wireguardutilswindows.cpp
src/platforms/windows/daemon/wireguardutilswindows.h

Stacked PRs:
* #9892
* #9891
* #9890
* __->__#9889
--- --- ---
Currently you need to create the object and then call
the correct functions in order to have an initialized object.
Similar to wgnt lets make sure that no "invalid" object can even exist.
so that we can assert you will not call i.e. start() on a closed handle.
Given that it's not cool to have constructors throw exceptions lets add
a create() factory that will spit out nullptr or a working instance.

SplitTunnel 01: Use a factory for creation

---

src/platforms/windows/daemon/windowsdaemon.cpp
src/platforms/windows/daemon/windowsdaemon.h
src/platforms/windows/daemon/windowsfirewall.cpp
src/platforms/windows/daemon/windowsfirewall.h
src/platforms/windows/daemon/windowssplittunnel.cpp
src/platforms/windows/daemon/windowssplittunnel.h
src/platforms/windows/daemon/wireguardutilswindows.cpp
src/platforms/windows/daemon/wireguardutilswindows.h

Stacked PRs:
* #9892
* #9891
* __->__#9890
* #9889
--- --- ---
Inline Lambdas are cool, let's use them to reduce dupecode and lets
give this function a failstate to bubble that up later to the client.

SplitTunnel 02: remove dupe code in generateIPConfiguration

---

linux/flatpak/org.mozilla.vpn.yml

Update flatpak finish args. I am testing on KDE Fedora 40. 
-  "--socket=fallback-x11" seems to be best practice
- "--socket=wayland" is required to get the app to start at all
- "--talk-name=org.kde.StatusNotifierWatcher" is required to see the app in the systray
- "--device=dri" Optional, but required for graphics accel

Add flatpak sandbox config to run on 'KDE Fedora 40'

---

src/connectionhealth.cpp
src/dnspingsender.cpp
src/dnspingsender.h
src/pinghelper.cpp
src/platforms/macos/macospingsender.cpp
src/platforms/macos/macospingsender.h

In PingHelper.cpp, we have this block:
```
m_pingSender = PingSenderFactory::create(m_source, this);
// Some platforms require root access to send and receive ICMP pings. If
// we happen to be on one of these unlucky devices, create a DnsPingSender
// instead.
if (!m_pingSender->isValid()) {
m_pingSender->deleteLater();
m_pingSender = new DnsPingSender(m_source, this);
} 
```
If you comment out this entire snippet except `m_pingSender = new DnsPingSender(m_source, this);` (that is, pretend we need root access), this bug reliably repros a few seconds after turning the VPN on, as well as when doing a cold launch of the app when the VPN is active.
`DnnsPingSender` has a `start` method. This should be called before `sendPing` it seems. (That is how it works in `ConnectionHealth`, the only …

VPN-5407: Start DnsPingSender

---

src/cmake/sources.cmake
src/webextensionadapter.cpp
tests/functional/testWebExtensionApi.js

In order to show connection health things in the extension, we should pass that info first.

Nit: Pass connectionhealth status to Extension

---

src/translations/extras/extras.xliff

https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9885
Looks like import is failing because of missing language names
> Languages ['ko', 'vi'] found in the i18n submodule do not have language names strings in extras.xliff!

Add missing language names (Korean, Vietnamese)

---

.github/scripts/get_unreleased_branches.ps1

`i18n_update.yml` has been [failing for over a week](https://github.com/mozilla-mobile/mozilla-vpn-client/actions/workflows/i18n_update.yaml) (the PR goes through to `main`, it's just the next step failing). The reason is that there are no unreleased branches.
I think this should fix, but hard to tell considering there are no unreleased branches at the moment.
```
InvalidOperation: /home/runner/work/mozilla-vpn-client/mozilla-vpn-client/.github/scripts/get_unreleased_branches.ps1:34
Line |
34 |  if ( $UNRELEASED_BRANCHES.GetType() -Eq [string] ){
|       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| You cannot call a method on a null-valued expression.
Error: Process completed with exit code 1.
```

Fix script for getting unreleased branches when there are none

---

scripts/linux/postinst.cmake
src/cmake/linux.cmake

This just automates things a little better when doing daemon debugging. We add a script that runs on `cmake --install` for Linux. A quick synopsis of what this script does:
1. Check that `DESTDIR` is unset, indicating that we are installing onto the host system, and we are not doing some packaging thing.
2. Check that we have root permissions (eg: run with `sudo`).
3. Reload and restart the Systemd services.
4. Grant the `CAP_NET_RAW` capability to the `mozillavpn` binary.
This is only needed for local development. These tasks are normally handled by the `linux/debian/mozillavpn.postinst` script when installed via a Debian package.

Nit: Add postinstall hook for Linux development

---

src/feature/featurelist.h
src/feature/featurelistcallback.h
src/webextensionadapter.cpp

The Extension itself cannot know on which plattform it is on, and if that is supported. 
So let's have the client send a signal whether it supports "webextension" 
Also while at it, i consolidated a few `FeatureListCallback_X` with a consteval func, so in the end the compiler will evaluate to a simple `()=>true|false` lambda same as before but i think it looks neat to not change to a diffrent file to check when a feature is enabled 😅

Add Webext Feature flag

---

.github/workflows/ppa-automation.yaml
taskcluster/kinds/build/linux.yml
taskcluster/kinds/docker-image/kind.yml

This is a trio of cherry-picks to get the PPA automation workflow to detect the currently available Ubuntu releases.
This cherry-picks the following commits:
- #9827
- #9828
- #9840

Cherry-pick: PPA automate release selection

---

.github/workflows/flatpak.yml
linux/flatpak/flatpak-vpn-crates.json

After my last messing around with the Flatpak manifests, it turns out that it wasn't a good idea to check in a static version of `flatpak-vpn-crates.json` since our `Cargo.lock` is updated automatically by Dependabot and the two files will quickly fall out of sync. Let's make another attempt to write some automation to ensure it's updated.
The last time I tried this, it got stuck because Github prevents workflows from retriggering themselves (this runs the risk of creating an infinite loop). So we would wind up with a PR that would automatically update the flatpak manifests, but then none of the required checks wound run, leaving the PR in an un-mergeable state. However, there are some [recommended workarounds](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guid …

Attempt to auto-update flatpak crates

---

src/cmake/ios.cmake
src/constants.cpp
src/constants.h
src/platforms/ios/iosiaphandler.h
src/platforms/ios/iosiaphandler.mm
src/platforms/ios/iosiaphandler.swift
src/tasks/purchase/taskpurchase.cpp
src/tasks/purchase/taskpurchase.h

StoreKit (formerly called StoreKit2)  has been the modern way to build In App Purchase for a few years now. And Apple has announced Original StoreKit is deprecated after iOS 18.0. We needed to update the library we use, which is done in this PR. 
StoreKit2 is only available on iOS 15 and greater. Since it was trivial to maintain support for iOS 14 and earlier by using the original StoreKit APIs, there is forking logic all over this.
For a swift-only app, StoreKit2 is fairly straightforward. However, that doesn't work for our app. This is a mix of Objective C++ and Swift:
- Callbacks into our Qt code shared across platforms cannot be written in Swift, so those need to be in C++ or Objective C++.
- StoreKit2 is a Swift-only API, so code that interacts with it must be written in Swift. …

VPN-6512: Update Apple in app purchase to use StoreKit2

---

.github/workflows/flatpak.yml

In PR #9915 we tried to add a github workflow to keep the flatpak crates updated whenever dependabot tries to apply an update. And this worked great in PRs, but it failed as soon as dependabot tried to update a crate for real. The root of the issue is that dependabot pull requsts are explicitly prohibited from accessing repository secrets, where the `WIKI_TOKEN` was set.
We can work around the issue by creating a separate token just for dependabot and installing it into the "Dependabot secrets" instead. I have created a new token for this purpose, and named it `DEPENDABOT_TOKEN` so in theory we just need to update the workflow to use this secret and it should start working again.
Flatpak crate update PR #9915

Use a different token for dependabot PRs

---

linux/mozillavpn.spec
src/cmake/linux.cmake
src/commands/commandui.cpp
src/cryptosettings.cpp
src/cryptosettings.h
src/platforms/android/androidcryptosettings.cpp
src/platforms/android/androidcryptosettings.h
src/platforms/dummy/dummycryptosettings.h
src/platforms/linux/linuxcryptosettings.cpp
src/platforms/linux/linuxcryptosettings.h
src/platforms/linux/xdgcryptosettings.cpp
src/platforms/linux/xdgcryptosettings.h
src/platforms/linux/xdgportal.cpp
src/platforms/macos/macoscryptosettings.h
src/platforms/macos/macoscryptosettings.mm
src/platforms/windows/windowscryptosettings.cpp
src/platforms/windows/windowscryptosettings.h
src/settingslist.h
taskcluster/kinds/build/linux.yml
taskcluster/kinds/docker-image/kind.yml
tests/unit/testcryptosettings.cpp
tests/unit/testcryptosettings.h

We have a steady stream of users reporting that their Linux clients are frequently loosing their settings across reboot. This looks and smells like a failure in the `LinuxCryptoSettings` class to retrieve the settings encryption keys from the `libsecret` API. We have seen this before, and it typically results from the user's keyring being locked at the time that they launch the VPN client.
Fortunately, there is a better way to generate an application encryption key using the XDG [Secrets Portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Secret.html), and we already have it implemented for Flatpaks. This PR attempts to provide a migration strategy for users who have settings encrypted with `libsecret` to switch over to the XDG secrets instead.
We …

VPN-6422: Migrate to XDG Secrets Portal

---

src/platforms/ios/iosiaphandler.mm

Reset and quit was crashing the app, caused by #9873.
Something that made this take a lot longer: There is a pre-existing issue that when on a debug build, reset and quit doesn't work (at least when the VPN is active). That predates #9873, and is not fixed here. But you must build a release build to have this work.
I tested for both the iOS 15+ code path and the iOS 14 code path:
- reset before logged in
- reset when logged in, VPN on
- reset when logged in, VPN off
VPN-6640

VPN-6640: Fix crash on reset and quit

---

src/localizer.cpp
tests/unit_tests/testlocalizer.cpp

On iOS, I believe all device locales were broken - we were just pulling the major language, regardless of the country.
3 things were preventing properly reporting the device locale:
1) iOS: We were breaking it on the wrong character within `parseIOSLanguages`. This resulted in never getting the country. Instead, that function was returning `es` instead of `es` and `MX`, etc. (I've added some comments to this method as well.)
2) iOS and Android: Chinese was reporting in as Hans and Hant, when consider it TW and CN. I've added some hacky code manually adjusting this.
3) Android: We were ignoring anything that wasn't 2 letters for a country/script. I've adjusted this to also accept "Hans" and "Hant".
VPN-6622

VPN-6622: Fix broken device language for Chinese

---

extension/socks5proxy/bin/CMakeLists.txt
extension/socks5proxy/bin/linuxbypass.cpp
extension/socks5proxy/bin/linuxbypass.h
extension/socks5proxy/bin/main.cpp
extension/socks5proxy/bin/verboselogger.cpp
extension/socks5proxy/bin/verboselogger.h
extension/socks5proxy/bin/windowsbypass.cpp
extension/socks5proxy/bin/windowsbypass.h
extension/socks5proxy/src/CMakeLists.txt
extension/socks5proxy/src/socks5.cpp
extension/socks5proxy/src/socks5.h
extension/socks5proxy/src/socks5connection.cpp
extension/socks5proxy/src/socks5connection.h
extension/socks5proxy/src/socks5local_default.cpp
extension/socks5proxy/src/socks5local_linux.cpp
extension/socks5proxy/tests/testsocks5.cpp
linux/netfilter/netfilter.go
src/controller.cpp
src/platforms/windows/daemon/windowsfirewall.cpp
src/platforms/windows/daemon/windowsfirewall.h

A couple months ago, I made an attempt to get the firefox extension working on MacOS by binding the proxy connections to an interface with `IP_BOUND_IF` to try and get them to bypass the VPN connection. Unfortunately, this work never got anywhere so the MacOS implementation was abandoned.
However, when some of our devs started to experience some difficulty in getting their split tunneling drivers working on Windows, I figured it might be worth revisiting this work by doing the same thing on Windows. This should allow us to implement firefox extension in a way that doesn't require the split tunneling driver at all.
Along the way, we also implemented it for Linux, mostly because it was the easiest way to test out all the connection handling changes (it's easy there because we just need a …

FXVPN-218: Socks Proxy bypass without split tunneling

---

nebula/ui/components/CMakeLists.txt
nebula/ui/components/MZBottomSheet.qml
nebula/ui/components/MZExternalLinkListItem.qml
nebula/ui/components/MZLinkRow.qml
nebula/ui/components/qmldir
src/constants.h
src/mozillavpn.cpp
src/ui/screens/settings/ViewPreferences.qml

Adding a row with a link to the help article for Android start on boot. (Users need to set this up from Android Settings themselves.)
While the Figma (attached to the ticket) for this has link icon center justified (along with the toggle), I made this top justified to match what the toggle actually looks like.
While there is a similar looking component on the help screen, it is not a row - and didn't work here. I also tried adjusting another component to make it work as a link row, but ultimately Lesley helped me realize that we needed to create a new component for this situation.
VPN-3112

VPN-3112: Auto start breadcrumb on Android

---

src/controller.cpp

Occasionally, when starting the VPN from the extension, the client sends an invalid initial `connectedSince` value to the extension resulting in the extension timer erroneously reporting that the extension has been connected for > 480,000 hours. This PR checks that `m_connectedTimeInUTC` is valid before converting it to milliseconds and sending it to the extension and creates a new `timStampForExtension` if it isn't. 
FXVPN-213

FXVPN-213: Fix timer wonkiness in extension

---

src/connectionhealth.cpp
src/controller.cpp
src/ui/screens/home/controller/ConnectionStability.qml
src/ui/screens/home/controller/ControllerImage.qml

Here we make adjustments to the UI and to ConnectionHealth to provide connection stability updates to the extension when the client is in StateOnPartial. This allows the extension to surface "No Signal" / "Unstable" UI in the tool bar icon and popup. The UI changes are to prevent connection stability UI changes in the VPN client when in StateOnPartial.
VPN-6641

VPN-6641: Send connection health info to ext in StateOnPartial

---

src/inspector/inspectorhandler.cpp
src/itempicker.cpp
src/localsocketcontroller.cpp
src/networkrequest.cpp
src/platforms/linux/daemon/apptracker.cpp
src/platforms/linux/daemon/dbustypeslinux.h
src/settings/setting.cpp
tests/unit/testmodels.cpp

- Fixes #9966.
```
In file included from /build/source/build/src/mozillavpn_autogen/UM7GZO45JR/../../../../src/platforms/linux/daemon/dnsutilslinux.h:12,
from /build/source/build/src/mozillavpn_autogen/UM7GZO45JR/../../../../src/platforms/linux/daemon/dbusservice.h:13,
from /build/source/build/src/mozillavpn_autogen/UM7GZO45JR/moc_dbusservice.cpp:9,
from /build/source/build/src/mozillavpn_autogen/mocs_compilation.cpp:88:
/build/source/build/src/mozillavpn_autogen/UM7GZO45JR/../../../../src/platforms/linux/daemon/dbustypeslinux.h: In function 'const QDBusArgument& operator>>(const QDBusArgument&, DnsResolver&)':
/build/source/build/src/mozillavpn_autogen/UM7GZO45JR/../../../../src/platforms/linux/daemon/dbustypeslinux.h:49:26: error: 'qsizetype QByteArray::count() const' is deprecated: Use …
```

Fix build errors from deprecated `QByteArray::count()`, `QVariant::type()`, `QEventPoint::pos()`

---

src/controller.cpp

In State on partial we allow wireguard to only route to a subset of ip adresses.
The default dns is the exit server, however if a privacy value is added, we currently dont add that private ip adress to the routes -> it's unreachable blocking stuff.

VPN-6676 Include dns traffic in stateOnPartial

---

nebula/ui/components/MZLinkRow.qml
src/ui/screens/settings/ViewPreferences.qml

QA caught that we're missing accessibility text for the button; it was reading as "unlabeled".
VPN-3112

VPN-3112: read title for a11y link

---

nebula/ui/components/MZAlert.qml
nebula/ui/components/MZBottomSheet.qml
nebula/ui/components/MZDropShadowWithStates.qml
nebula/ui/components/MZSettingsToggle.qml
nebula/ui/components/MZSubscriptionOption.qml
nebula/ui/components/MZToolTip.qml
nebula/ui/components/forms/MZComboBox.qml
nebula/ui/themes/main/colors.js
src/ui/screens/ScreenViewLogs.qml
src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml
src/ui/screens/getHelp/developerMenu/ViewTelemetryDebugging.qml
src/ui/screens/getHelp/developerMenu/ViewUiTesting.qml
src/ui/screens/home/ViewHome.qml
src/ui/screens/home/controller/ConnectionStability.qml
src/ui/screens/home/controller/ControllerView.qml
src/ui/screens/home/controller/VPNToggle.qml
src/ui/screens/messaging/ViewMessage.qml
src/ui/screens/settings/ViewAboutUs.qml

VPN-6213 is to refactor main theme to separate layout/spacing from the colors, and while we're at it remove explicit colors from the code.
This is going to be done as 3 PRs, stacked on top of one another:
1) Change explicit colors to variable colors (this PR)
2) Change use of variable colors in the code to named variables, and set them to colors (to make them easy to swap out for other themes) - so instead of a border being `grey20` it's a new variable `borderColor`, and `borderColor` is set to `grey20`.
3) Pull colors out from the rest of theming, so it's easy to swap in new color schemes as desired
For this PR - some of these color choices are pretty straightforward (looking at you, #FFFFFF and #000000), but some were slight judgement calls. I tried to match QT explicit colors (in …

VPN-6213 (part 1): Remove explicit colors

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/ConnectionHealth.kt
src/platforms/ios/ConnectionHealth.swift

Based on the data coming back from this ticket, we decided to do server switches from the mobile daemons at most once every 15 minutes. On iOS this is simply changing a variable (we had previously done one at most every 5 minutes), and on Android we had to build some new logic in.
VPN-6407

VPN-6407: 15 minutes between daemon server switches

---

.gitignore
extension/socks5proxy/bin/CMakeLists.txt
nebula/ui/components/MZFlickable.qml
src/commands/commandui.cpp
src/platforms/windows/daemon/windowsfirewall.cpp

Soooo i did set up a 6.8 dev build and was able to repro the crash seen in #9966 - this is a fun one. 
In 6.8.0 we get the "onHeightChange" before the window has finished to initialize, so that when we call ` mapToItem(window.contentItem)` we defer a nullptr and crash.

Re:#9966 Fix Crash in MZFlickable

---

src/platforms/windows/daemon/windowssplittunnel.cpp

Valentina notes on some "hotspot" networks split tunnel breaks. 
From valentinas logs: 
``` 
[23.10.2024 17:53:21.923] (WindowsSplitTunnel) Debug: Getting adapter info for: MozillaVPN
[23.10.2024 17:53:21.930] (WindowsSplitTunnel) Debug: Getting adapter info for: Wi-Fi
[23.10.2024 17:53:21.930] (WindowsSplitTunnel) Debug: Ipv6 Conversation error 0
[23.10.2024 17:53:21.930] (WindowsSplitTunnel) Error: Failed to set Network Config
[23.10.2024 17:53:21.930] (WindowsSplitTunnel) Debug: Pushing new Ruleset for Split-Tunnel  3
[23.10.2024 17:53:21.930] (WindowsSplitTunnel) Debug: \Device\HarddiskVolume4\Program Files\Mozilla Firefox\firefox.exe
[23.10.2024 17:53:21.934] (WindowsSplitTunnel) Debug: New Configuration applied:  STATE_RUNNING
```
Currently we assume the local network adapter …

Fix split tunnel on ipv4 only networks

---

taskcluster/docker/linux-qt6-build/Dockerfile

In the last change to the Rust version, we missed a spot and left the Static QT Docker image on version 1.69 while the rest of our project moved onto version 1.75. To fix this, I think we just need to bump the version in the rust download URL during the docker container setup.
This is causing dependabot to fail when trying to update dependencies to versions that no longer build cleanly on 1.69 (such as #9792)
Introduced by #9935

Bump to rust 1.75.0 for static QT builds too

---

android/common/src/main/java/org/mozilla/firefox/qt/common/CoreBinder.kt
android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/ConnectionHealth.kt
android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNServiceBinder.kt
src/controller.cpp
src/models/serverdata.cpp
src/models/serverdata.h
src/platforms/android/androidcontroller.cpp
src/platforms/android/androidcontroller.h
src/platforms/android/androidvpnactivity.h
src/platforms/ios/ConnectionHealth.swift
src/platforms/ios/ioscontroller.mm
src/platforms/ios/ioscontroller.swift
src/platforms/ios/iostunnel.swift
src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml

There are a few things in this PR, apologies. If you'd like them broken out into separate PRs, please let me know and I'll happily restructure.
1) (no ticket) Adding a developer debug option for daemon silent switching on Android. This exists on iOS already, and this was extended for Android as well. (This was necessary to test other work in this PR.)
2) (VPN-6408) Currently daemon silent server switches (which exist only on mobile, as on desktop the client is always running) will attempt a single switch to a new server. Once they've used their backup server, they never again try to switch until the VPN is again activated from the client. This updates it to use up to 4 servers, and rotate between them.
3) (VPN-6678) In looking at the code and testing my work, I discovered a bug - Special …

VPN-6408 and VPN-6678: Turn daemon server switches into round robin of servers, and fix DNS bug

---

taskcluster/config.yml
taskcluster/kinds/beetmover-apt/kind.yml

For now there isn't a good place for us to import the candidate package during the promote phase for QA to be able to test. So we use the "staging" apt repo. However, this lives in the non production GCP project, so we have to use the level 1 workers.
In the future we'll want to either:
1. Create a second apt repo in the production GCP project that we can use for QA prior to shipping.
2. Import the package into the main `mozillavpn` production apt repo but with a different name (e.g include `rc###` or similar). Then add a repackage task that renames it to the proper name during the ship phase.

Bug 1927890 - Hardcode beetmover-apt-promote task to level 1 worker

---

linux/keyring/Makefile
linux/keyring/debian/control

The `mozilla-vpn-keyring` package isn't building on Ubuntu/Focal because we set the `debhelper-compat` package version to 13. Unfurtunately, that is too new of a debhelper version for Focal which only supports up to version 12.
I also added a phony target of `deb` to do the package build, because I forgot the commands to do so and felt silly having to look it up.
JIRA Issue: [VPN-6365](https://mozilla-hub.atlassian.net/browse/VPN-6365)
[VPN-6365]: https://mozilla-hub.atlassian.net/browse/VPN-6365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reduce keyring debhelper compat to 12

---

src/platforms/windows/daemon/windowssplittunnel.cpp

Clang auto infers that all code-paths return a value .... msvc is unable to do so and therefore throws an error :)

Nit: Fix MSVC warning

---

nebula/ui/themes/main/colors.js
src/ui/screens/home/controller/VPNToggle.qml

This is part of the work to get colors ready for multiple themes. In this PR, all derived colors are turned into named color strings. In a few cases, I've swapped colors for ones that look identical to the naked eye.
Additionally, I had swapped the names for `dullPurple` and `dullGreen` in a prior PR. That is fixed here.
This PR builds on https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10014, which in turn builds on https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9983. Both have been merged into main.
Next few PRs for this ticket, to be built on top of one another:
1. Everything below the comment in the color file should not have hashes. Also fix alpha bug.
2. Remove unused color names - not base colors, but theming colors
3. Variable colors to general words, and break …

VPN-6213 (part 3) - Remove explicit color strings from derived colors

---

nebula/ui/themes/main/colors.js

Pulling out all unused colors. At one point I changed all `addTransparency(someColorName, 0.0)` to `color.transparent` but that led to bugs. I left a comment to try to steer others away from this same trap.
From my testing, there are no missing colors when using the app. The logs do have some statements like `QML MZInputBackground: The current style does not support customization of this control (property: "background" item: MZInputBackground_QMLTYPE_133(0x6000020bebc0, parent=0x0, geometry=0,0 0x0)). Please customize a non-native style (such as Basic, Fusion, Material, etc). For more information, see: https://doc.qt.io/qt-6/qtquickcontrols2-customize.html#customization-reference (MZSearchBar.qml:41)`, but this is unrelated to VPN-6213 - it exists on `main` as well.
This builds on …

VPN-6213 part 4: Remove unused colors

---

docs/Building/linux.md
linux/debian/control
linux/debian/mozillavpn.postinst
scripts/linux/postinst.cmake

I have been fighting with the `XdgCryptoSettings` on my Fedora machine which fails to retrieve the secret. The XDG Desktop portal throws an error because the clients procfs entry is root-owned. It turns out this is because the process image has elevated capabilities and we need to drop them before XDG will let us read secrets.
So, why do we have `CAP_NET_RAW` granted at all? Well, it was added to enable the client to send ICMP pings using a raw socket if the kernel doesn't allow us to use ICMP sockets. However, we now have workarounds that use TCP for connection health monitoring too, so it's not really needed anymore.
JIRA Issue [VPN-6422](https://mozilla-hub.atlassian.net/browse/VPN-6422)
Introduced by: #9922
[VPN-6422]: https://mozilla-hub.atlassian.net/browse/VPN-6422?atlOrigin=eyJpIjo …

Linux: Drop CAP_NET_RAW capability from binary

---

linux/netfilter/netfilter.go

In PR #9906 I messed around a bit with the firewall rules to get IPv6 traffic to split tunnel correctly when originating with a firewall mark (eg: `sudo ping6 -m 51820 <dest>`) by making better use of connection tracking to re-set the firewall mark upon packet reception.
However, I goofed up during the rebase and I forgot the most important part of that change: the firewall mark has to be applied *after* connection tracking, and unfortunately a raw hook happens before connection tracking. The result of that error is that split tunneling just doesn't work on some machines because the inbound packets loose their firewall mark and get rejected by RPF.
To fix this, we just need to adjust the priority of the `preroute` chain from `ChainPriorityRaw` to `ChainPriorityMangle` so that it happens …

FXVPN-218: Fix busted split tunneling on Linux

---

extension/socks5proxy/bin/CMakeLists.txt
extension/socks5proxy/bin/main.cpp
extension/socks5proxy/bin/sockslogger.cpp
extension/socks5proxy/bin/sockslogger.h
extension/socks5proxy/bin/socksproxy.service.in
extension/socks5proxy/bin/verboselogger.cpp
extension/socks5proxy/bin/verboselogger.h
extension/socks5proxy/bin/windowsbypass.cpp
extension/socks5proxy/bin/windowsbypass.h
extension/socks5proxy/bin/winfwpolicy.cpp
extension/socks5proxy/bin/winfwpolicy.h
extension/socks5proxy/bin/winsvcthread.cpp
extension/socks5proxy/bin/winsvcthread.h
extension/socks5proxy/bin/winutils.cpp
extension/socks5proxy/bin/winutils.h
extension/socks5proxy/src/CMakeLists.txt
extension/socks5proxy/src/socks5local_windows.cpp
extension/socks5proxy/tests/CMakeLists.txt
extension/socks5proxy/tests/curlpipe.cpp
linux/debian/rules
linux/mozillavpn.spec
windows/installer/MozillaVPN.wxs

Time for some more wild experiments in the VPN extension's proxy. This time we try to make it autonomous as a windows service. For now, this just starts the service using a fixed port number (8123) but eventually we will probably want to make this dynamic (or use named pipes).
In this PR:
- Finally get around to testing named pipe support on Windows.
- Add firewall code to automatically install the split tunneling rules.
- Add a `WinSvcThread` class to handle the Windows service glue.
- Generate a sensible logfile so that we can inspect what the service is doing.
- Add a new service in the Wix installer to start the proxy automatically.
- Install the proxy tool as a systemd service.
This also adds a firewall policy to restrict the connecting clients to just web browsers. We do this by …

VPN-6626: Install socks proxy as a service

---

scripts/ci/update_server_names.py
src/translations/extras/extras.xliff

Malmö is the only city with special characters in the name. Our build scripts should handle this fine - and we use `Servers.Malm` for the string ID. It builds perfectly on my machine, but was failing on TaskCluster. This failure was due to taskcluster not handling special characters in string IDs in the same way my machine does, apparently. While special characters should be removed from string IDs, they weren't being removed.
This PR adds "cleaning of special characters" on the front end - before we pass the string IDs to the translation repo. Thus, we'll now keep the ID as `servers.Malm` for the round trip journey from our client repo to the translation repo and back. 
VPN-6649 will be fixed as 4 separate PRs, merged in order:
1. A PR on the translation repo to copy all existing …

VPN-6649: fix translations for cities with special characters

---

taskcluster/scripts/build/ios_build_debug.sh

The iOS builds have been failing on Taskcluster for a while now, and it seems like the problem is related to the `SDKROOT` environment being set. I am guessing this is due to a change on the MacOS worker machines. To fix it, we basically just need to unset the environment variable and let CMake do its thing.

Fix iOS build failures on Taskcluster

---

src/controller.cpp
src/controller.h
src/mozillavpn.cpp
src/mozillavpn.h
src/ui/screens/ScreenBackendFailure.qml
tests/qml/moccontroller.cpp
tests/unit/moccontroller.cpp

Time for some cleanup.
This was the old hearbeat check
```c++
void MozillaVPN::heartbeatCompleted(bool success) {
logger.debug() << "Server-side check done:" << success;
if (!success) {
m_private->m_controller.backendFailure();
return;
}
if (m_state != StateBackendFailure) {
return;
}
if (!modelsInitialized() || m_userState != UserAuthenticated) {
setState(StateInitialize);
return;
}
maybeStateMain();
}
```
So there we actually needed the controller to deativate and come back later. 
Nowadays we only care during auth for heartbeat, we so vpn can't be activated anymore. So let's remove the controller code and rename all the screens to heartbeat failure, as otherwise a confused engineer might think this could have something to do with the daemon :)

Nit: Cleanup "BackendFailures" in controller.cpp

---

src/authenticationinapp/authenticationinapp.h
tests/functional/testAuthenticationInAppAccountCreationNav.js

At last, my cup runneth over with frustration when it comes to the `AuthenticationInAppAccountCreationNav` tests, and it's time to figure out why they are flaky. It seems the problem has to do with the fact that we have multiple QML loaders at play in the authentication screens, and for the most part we want to be waiting on the Authentication screen's loader to finish rather than the global loader.
We should also be checking the auth state as well to ensure we get the correct state transitions.
I should probably look at the Addons tests too at some point, but those are scary.
So, so many test retries. Arggggggghhhhh

Fix flaky AuthenticationInAppAccountCreationNav tests

---

.github/workflows/linux.yaml

Akin to https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9028/commits 
Current builds (tried e.g. mozillavpn-2.24.3~rc20241030191255-1.x86_64.rpm package downloaded from https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/11600067264/job/32299824195) depends upon `libQt6Core.so.6(Qt_6.6_PRIVATE_API)(64bit)` and `libQt6Qml.so.6(Qt_6.6_PRIVATE_API)(64bit)` but since Fedora 41 is on Qt 6.8 no current package provides that symbol.
Trying to install via `dnf` yields the error:
```
Problem: conflicting requests
- nothing provides libQt6Core.so.6(Qt_6.6_PRIVATE_API)(64bit) needed by mozillavpn-2.24.3~rc20241030191255-1.x86_64 from @commandline
- nothing provides libQt6Qml.so.6(Qt_6.6_PRIVATE_API)(64bit) needed by mozillavpn-2.24.3~rc20241030191255-1.x86_64 from …
```

Update RPM build to Fedora 41

---

.github/workflows/linters.yaml
README.md
nebula/ui/components/MZAlert.qml
nebula/ui/components/MZPopupButton.qml
nebula/ui/themes/main/theme.js
nebula/ui/themes/not-designer-approved/theme.js
nebula/ui/themes/theme-derived.js

I introduced this bug [right here](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10015/files#diff-9fc531023123071c2001a81ad0ff768a4408ea77e9b30a28cef024c3074f087eL183), by replacing `color.overlayBackground = '#4D000000';` with `color.overlayBackground = addTransparency(color.black, 0.0);`. Of course, 4D is 30%, not 0%. 
I went through and audited every other use of 0.0 transparency, to make sure I didn't have any other copy/paste errors. I found just one other spot that used 0.0 but the wrong color, and updated it as part of this PR. (Not all #00xxxxx colors are identical. While they look identical on screen, in transitions or with opacity changes they may look different. Changing all `addTransparency(color.[anything], 0.0)` to `color.transparency` will cause UI bugs.)
I also …

VPN-6700: fix color

---

.github/workflows/build_addons.yaml
.github/workflows/linux_tests.yaml
.github/workflows/macos_tests.yaml
.github/workflows/wasm_tests.yaml
env.yml
src/dnshelper.h

The functional tests are slow, and it sucks. Here are some tweaks to make it go faster:
- Install `ccache` which we'll use to cache compiled objects.
- Setup `actions/cache@v4` to save the results of the ccache folder on every `push`
- Setup `actions/cache@v4` to pull the ccache folder from the PR's base commit.
- Refactor the test addon build into a reusable workflow and cache the addons since they rarely change.
Some future work to make it go even faster:
- The rust libraries don't benefit from `ccache` and they are slow to build. However, they don't change very often so maybe we should just cache the generated libs?
- Miniconda is sloooooow. Unfortunately, caching it is complicated because of how it interracts with pip packages.
- Miniconda is kinda too big to cache. Github workers …

Use caching to speed up functional tests

---

.github/workflows/flatpak.yml

Since I am up to my eyeballs in getting the CI working better, the Flatpak build jobs are taking far too long for my liking.
It seems that the github action they are built with has support for caching, but we include the `${{ github.sha }}` in it, which basically means the cache will never hit.
If we change that to `${{ github.event.pull_request.base.sha }}` then at least pull requests will build off the cached build from `main`.

Try to pick a better flatpak cache key

---

.github/workflows/linux.yaml
extension/socks5proxy/bin/CMakeLists.txt
linux/debian/rules

The socksproxy binary, when built with static Qt, fails to start on Linux as follows:
```
/usr/bin/socksproxy: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
This works in the main VPN binary because OpenSSL gets statically linked in through glean, but there is no glean in the socks proxy so it reverts to the default behaviour of Qt. In order to guide Qt (or really CMake in general) to choose static linking for OpenSSL we need to set the `OPENSSL_USE_STATIC_LIBS` variable. This best done at the project configuration stage.
However, there is a minor wrinkle. We have to set it before `find_package(Qt)`, which means we can't use CMake to check the Qt feature flags. To workaround this, we add some magic to the `debian/rules` …

VPN-6738: Statically link socksproxy to OpenSSL for Static Qt

---

src/settings/settingsmanager.cpp

At some point in the past the auth tests were broken due to a bad assert that was causing the test worker to fail if there was no SettingsManager created. Rather than an assert, we should just check to see if the SettingsManager was created and handle the test cleanup accordingly.
There's a 99.999% chance that I am to blame for the failed test, but we just never noticed because we don't run the auth tests in PR.

Fix assert fail in auth tests

---

scripts/cmake/addons.cmake
tests/functional/addons/CMakeLists.txt

I have noticed that the flatpak builds started failing after merging #10064 due to a failure to build the test addons, which I failed to notice because the flatpak builds were kinda flaky lately anyways. The problem seems to be that we have a buggy use of `GLOB_RECURSE` in addons.cmake that doesn't include any glob patterns and can fail to match any addons when `CMAKE_CURRENT_SOURCE_DIR` and `ADDON_SOURCE_DIR` differ.
While we're at it, we don't need to use inline python to parse the `ADDON_ID`. We have since upgraded to CMake > 2.20 which now includes native support for JSON parsing.
Example build failure: https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/12019520242/job/33506273223

Fix buggy globbing rules in addon build

---

taskcluster/docker/linux-qt6-build/Dockerfile

The smoking gun in the Qt build logs seems to be this:
```
Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.
```
To enable X11 accesibility support, I think we just need to make sure that Qt is built with the development libraries `libdbus-1-dev` and `libatspi2.0-dev` installed.
JIRA Issue: [VPN-6399](https://mozilla-hub.atlassian.net/browse/VPN-6399)
[VPN-6399]: https://mozilla-hub.atlassian.net/browse/VPN-6399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6399: Add Linux Qt build dependencies for accessibility

---

.github/l10n/check_l10n_issues.py
addons/CMakeLists.txt
docs/Components/Addons/index.md
scripts/addon/build.py
scripts/shared.py
scripts/utils/generate_shared_addon_xliff.py

The “shared addons strings” for VPN ([VPN PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9763/), [translations PR](https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/466)) had a bug - the string IDs in pontoon are of the form `CommonStringsSubtitle`, and the intention was `vpn.commonStrings.subtitle`. While this is non-standard (per the rest of our string IDs), it also provides an unlikely-but-real technical issue of a future clash - `update.soonMessage` and `updateSoon.message` from different parts of the YAML file would end up with the same ID of `CommonStringsUpdateSoonMessage`.
This PR does 3 things:
- Fixes the bug in `generate_shared_addons_xliff.py`
- Adds a new test in `check_l10n_issues.py` that probably should have been there from the start - it would …

VPN-6749: Fix shared addon ids

---

tests/functional/addons/CMakeLists.txt

Reverting part of: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10076
This should fix this PR test build error: https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/12123777006/job/33799991957?pr=10045

fix addon tests

---

.github/workflows/wasm_tests.yaml

I think this was introduced by #10053 which made an error in how we pass the generated test list to the functional test jobs. This should fix it and make the wasm job consistent with Linux and MacOS.
Introduced by #10053

Fix matrix evaluation for wasm functional tests

---

.github/workflows/build_addons.yaml

It looks like the attempted caching of addons for functional testing didn't work as expected. In particular I think that calling `hashFiles('addons/')` doesn't recursively scan the directory, which means that it doesn't react to changes in the addon content. Maybe using a `hashFiles('addons/**') with a globstar instead will do the trick.
While we're at it, let's throw the addons build tooling into the hash too.

Fix addon cache keying

---

qtglean/glean_parser_ext/run_glean_parser.py
qtglean/src/lib.rs
qtglean/src/uploader.rs
src/cmake/sources.cmake
src/glean/mzglean.cpp
src/glean/mzglean.h
src/settingslist.h
src/telemetry/extension_metrics.yaml
src/telemetry/pings.yaml
src/ui/screens/getHelp/developerMenu/ViewTelemetryDebugging.qml
src/webextensionadapter.cpp
src/webextensiontelemetry.cpp
src/webextensiontelemetry.h

This PR adds commands for the extension to send telemetry to the client. 
It's a bit bigger, therefore i've split this across 3 commits, for easyier reivew. 
1. In : https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10057/commits/d6e1d7782b1f1780a36d494f795f4af65a3b7786
I've only added the metrics, the data review happens in a google doc, i can link that if it's done. 
2. In https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10057/commits/a897f14912442bb1d84cc31e74fb0da6a81e362c
I add 3 commands:  `{t:telemetry, name: metric_name: args: any}` `{t:start_session}` `{t:stop_session}` - Those allow the extension to send any events or counts. For the bools we save them and attach them to the next ping, similar how we do that with our settings related bools. 
3. …

Add extensionTelemetry

---

src/platforms/windows/daemon/windowssplittunnel.cpp
src/platforms/windows/daemon/wireguardutilswindows.cpp

Some things found while we played with the config files: 
- **Dont try to give a pointer to an unallocated vector**
- **Dont try to create an address from an empty string**
- **Use correct byteorder for wireguard**

Nits for mordor

---

.github/workflows/linters.yaml
.github/workflows/translations.yaml
scripts/utils/generate_ts.sh

_When testing, I found that the git branch wasn't properly picked up by this script, and I fixed that. That one line is *not* part of this bug, but is a fix I included in this PR._
This is 100% egg on my face. While we did extensive testing of the addons shared string work to ensure it extracts shared strings, builds the app with shared strings, and uses those shared strings, I neglected to consider that *additionally* we do not want those shared strings to be duplicated for translation within the addons that they're utilized in. I take full responsibility for this, with a giant caveat that our use of GitHub actions makes true end-to-end testing of this pipeline extremely difficult.
The duplicated addon translations come from this path: 
1. Within the `mozilla-vpn-client-l10n` repo, the …

VPN-6763: Do not include shared translations when importing addon-specific ts files

---

scripts/cmake/Info.plist.QtGleanBindings

After https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10078 was merged in, Xcode Cloud reported failures because `ITMS-90208: Invalid Bundle - The bundle MozillaVPN.app/Frameworks/QtGleanBindings.framework does not support the minimum OS Version specified in the Info.plist.`
Updating the minimum version to match.
VPN-6742 follow up

qtglean bindings must match min version

---

src/webextensionadapter.cpp
src/webextensionadapter.h
tests/functional/testWebExtensionApi.js
tests/functional/utils/webextension.js

Companion: https://github.com/mozilla-extensions/mozilla-vpn-extension/pull/134
This PR adds the WebExt Handler - functions to reflect and modify certain VPN Client settings.

Allow sending settings to the web-ext

---

.github/dependabot.yml

- Removed weekly updates for Windows Wireguard-Go and Balrog Updater from the Dependabot configuration.

Remove weekly updates nonexistent Windows Wireguard-Go and Balrog Updater

---

src/translations/extras/extras.xliff

[New language in Pontoon](https://pontoon.mozilla.org/th/mozilla-vpn-client/mozillavpn.xliff/?string=276710) - Thai!
Our linter fails when there is a new language that is not yet in `extras.xliff`, as you can see in a recent run of "merge in the most recent translations": https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/12336343269/job/34428760557?pr=10125
This PR gets everything moving again.
N/A

Add Thai to extras.xliff

---

scripts/shared.py

Short explanation: Deep in the translation build scripts, `en` is treated differently than `en-US` - it causes the script to think that `en-US` does not actually have any translations, and thus when switching to `en` language it disables the addon. (This has not come up before for reasons explained in the essay below.)
---
How does adding 3 characters allow us to use English addons that have shared strings? (This turned into an essay, sorry.)
- Looking at and logging the client code for a while, I saw one of the times that we'll enable/disable addons is when the language changes
- In these cases, it looks at the `translations.completeness` file to see if the addon is translated in the new language
- The `translations.completeness` file for the addons using shared strings is showing `0.0` …

VPN-6778: fix English translations for addons w/ shared string

---

src/interventions/killernetwork.cpp

KillerNetwork::systemAffected() consistently returns `false` due to permissions issues. This PR tweaks the way we detect Killer Networking Software to use `WindowsUtils::getServiceStatus()` instead of ` WindowsServiceManager::open()` to get around this.
VPN-6790

VPN-6790 : Tweak Killer software detection

---

src/settingslist.h

Telemetry on the VPN extension is opt-out. This PR changes the default value of our `extensionTelemetryEnabled` setting to true by default. 
FXVPN-319

FXVPN-319: Change extensionTelemetry to true by default

---

addons/message_try_firefox_extension/manifest.json

QA requested removal of the timing condition to make testing easier: https://mozilla-hub.atlassian.net/browse/FXVPN-32?focusedCommentId=974354
I've included "adding this back in" in the ticket to finalize this addon: https://mozilla-hub.atlassian.net/browse/FXVPN-280
https://mozilla-hub.atlassian.net/browse/FXVPN-32?focusedCommentId=974354

Remove addon condition for testing

---

src/platforms/ios/ConnectionHealth.swift
src/platforms/ios/PingAnalyzer.swift
src/telemetry/metrics.yaml
src/translations/extras/extras.xliff

This metric is expiring, and it seems like there are [more errors being logged](https://mozilla.cloud.looker.com/explore/mozilla_vpn/event_counts?qid=hDrw9dQlABqE7xcvV1cRmx&toggle=fil,vis) than I'd expect. It's happening on about 10% of iOS user's devices (though it should have no user-facing impact), and I'd like to know why an error is being thrown. 
Thus, I've extended the expiration and added an extra bit to learn which error is being thrown.
This will require data review.
N/A

extend metric, add extra

---

.gitmodules

Commit 37793a9617e4797a8218c2bc495cf507b6b6c300 (#5198) incompletely deleted this submodule: it removed the gitlink without removing the .gitmodules entry.
- https://github.com/mozilla-mobile/mozilla-vpn-client/issues/1014#issuecomment-2561945273

Remove .gitmodules entry for dead 3rdparty/openSSL submodule

---

src/profileflow.cpp
src/profileflow.h
src/tasks/getsubscriptiondetails/taskgetsubscriptiondetails.cpp
src/tasks/getsubscriptiondetails/taskgetsubscriptiondetails.h
src/translations/strings.yaml
src/ui/screens/settings/ViewSettingsMenu.qml
tests/functional/queries.js
tests/functional/testSubscription.js

My understanding of this ticket is that once we switch from in app auth to web based auth, the call to get subscription details will fail due to insufficient scopes. This PR adds a flow when this call fails - if it fails due to authentication and the user is using web-based authentication, we show a popup prompting the user to reauthenticate on web.
If we ever get a bad response for getting subscription details for the account profile screen and it's a `AuthenticationRequiredError`, this screen will pop up. This is what we want in the transition to web, but if this error pops up other times... it isn't the worst to try to reauthenticate, so I think this is okay. 
Since you need a specific token to trigger this (if I understand the ticket correctly), I hacked together a test setup:
1. Add …

VPN-6318: Add reauth to subscription management flow

---

src/platforms/windows/daemon/windowsfirewall.cpp

While investigating VPN-6293, it seems that the logging around the windows firewall kind of sucks and it would be nice if we could get a log of the error codes rather than just reporting than an error occurred. This refactors a bit of how the firewall gets set up so that we can log the codes.
While we're at it, I also cleaned up some of the firewall setup by using FWPM transactions and scope guards to handle the unhappy path.
JIRA issue [VPN-6293](https://mozilla-hub.atlassian.net/browse/VPN-6293)
[VPN-6293]: https://mozilla-hub.atlassian.net/browse/VPN-6293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve Windows firewall logging

---

src/theme.cpp
src/theme.h

I tested this by adding some code to run this when loading themes. I created [another ticket](https://mozilla-hub.atlassian.net/browse/VPN-6783) to later add code to detect changes immediately.
VPN-6064

VPN-6064 - detect dark mode

---

tests/functional/testSettings.js

For reasons i don't know the language page causes a dlopen , which is not supported. Sadly emscripten does not want to tell WHAT is trying to load :( so for now let's disable the test on wasm, given we have coverage from the other plattforms

Disable broken wasm test

---

src/tasks/authenticate/taskauthenticate.cpp
src/tasks/authenticate/taskauthenticate.h
src/telemetry/metrics.yaml

Add telemetry described in VPN-6323. 
I also included links to some data reviews that had been previously neglected.
VPN-6324

VPN-6324: Telemetry for web based authentication

---

src/platforms/android/sources.cmake
src/platforms/ios/sources.cmake

We want to disable adjust, but in a way that we can re-enable it if we later decide to. Commenting out this section removes the `MZ_ADJUST` flag in the builds, which disables adjust.
You can verify that Adjust is not running by finding the log line `Debug: Adjust not included in build.` shortly after the app initializes, rather than `Debug: Adjust included in build.`. (Build with a placeholder Adjust token when testing this; without one, Adjust will never be included in the build whether that section is commented out or not.)
VPN-6581

VPN-6581: disable adjust

---

extension/socks5proxy/bin/sockslogger.cpp

While trying to take a look at the log files for [FXVPN-323](https://mozilla-hub.atlassian.net/browse/FXVPN-323), it seems that the logs weren't particularly helpful due to a lack of timing information. This PR attempts to add a timestamp to the start of each line as we write it to the logfile.
JIRA Issue: [VPN-6805](https://mozilla-hub.atlassian.net/browse/VPN-6805)
[FXVPN-323]: https://mozilla-hub.atlassian.net/browse/FXVPN-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-6805]: https://mozilla-hub.atlassian.net/browse/VPN-6805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6805: Add timestamp to socksproxy logfile

---

src/feature/featurelistcallback.h

Changes Linux and macOS to use web-based auth in prod. Rewrites this area a little to (hopefully) be clearer.
VPN-6320

VPN-6320: change authentication default for macOS and Linux

---

extension/socks5proxy/bin/winfwpolicy.cpp

Looking at your convo in the ticket, maybe the browser is not excluded. 
Let's also log the path, so we can assert that.

Nit: add browser path to log

---

linux/debian/mozillavpn.postinst

When upgrading from 2.24.x to 2.25, we removed the legacy autostart scripts and switched to the XDG desktop portal instead for handling start-on-boot. However, because the autostart scripts are installed under `/etc` they don't get removed on package upgrade, meaning that we can wind up launching the VPN application twice.
The second launch can have a malformed application ID, which can also lead to the corruption of the settings file.
To fix this, we need to make sure that these autostart files are removed.
JIRA issue: [VPN-6804](https://mozilla-hub.atlassian.net/browse/VPN-6804)
Autostart scripts removed by #9922
[VPN-6804]: https://mozilla-hub.atlassian.net/browse/VPN-6804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove legacy XDG autostart files

---

src/profileflow.cpp

https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10141/ had a testing bug. This set of tasks results in being hung on the new "reauth" popup:
- Reset app
- Launch app - in debug menu use staging server, flip InAppAuth on (so that it is on for staging)
- Relaunch app, sign in (via in app auth)
- In Debug menu turn InAppAuth pref off
- In inspector, give `force_subscription_management_reauthentication` command
- Tap into the "Account" screen in settings
This was because we re-run profile flow after the reauth, but weren't clearing out the flag to force reauth before the second run. (In testing before putting up the original PR, I was testing via a different path.)
VPN-6318

VPN-6318 follow up: Fix for testing

---

scripts/utils/generate_release_notes.sh

Now that we're using 22 languages (instead of 6), I wanted to update the script to be able to use it. (6 languages were okay to do manually, 22 is annoying.)
Updated the bash script to use the updated file for shared strings. Also added the additional languages. As part of that:
- I had to change to a for loop to get the strings in order. (Otherwise it takes them in the order of the `strings.xliff` file - which for 2.25, gives an incorrect output order due to how `strings.xliff` is sorted.)
- I updated how we decide if a language is missing a translation, as it wasn't working for Greek (which has a missing string for the 2.25 release).
N/A

Update release notes script

---

macos/pkg/conclusion.html.in

[See diagnosis on the ticket](https://mozilla-hub.atlassian.net/browse/VPN-6813). I'm the one who broke this in https://github.com/mozilla-mobile/mozilla-vpn-client/pull/9641.
VPN-6813

VPN-6813 fix translation in install string

---

src/profileflow.cpp
src/ui/screens/settings/ViewSettingsMenu.qml

This comes from QA's latest checks on VPN-6318. The issues were that the pop up wasn't resetting, and TaskAuthenticate was left hanging. This fixes both of those.
After this gets merged into `main`, it will need to be uplifted into the release branch.
VPN-6318

VPN-6318 follow up - better resetting of state

---

src/CMakeLists.txt
src/commands/commandui.cpp
src/platforms/windows/windowsutils.cpp
src/platforms/windows/windowsutils.h
src/theme.cpp
src/theme.h
tests/auth_tests/CMakeLists.txt
tests/qml/CMakeLists.txt
tests/unit/CMakeLists.txt
tests/unit_tests/CMakeLists.txt

The Designers aren't looking quick lets change some things. 
IMHO RN our Window on Windows has multiple issues: 
| Dark  | Light |
|-------|-------|
| ![old_dark](https://github.com/user-attachments/assets/3d0d6d88-41fe-4019-9626-c53507620429) | ![old_light](https://github.com/user-attachments/assets/8d8e0bee-9ff1-4199-8b27-80166a71bbd1) 
❌ The Titlebar shows a very pixelated icon
❌ The Icon is not the one in our [figma windows "window"](https://www.figma.com/design/lHbmTJ5xaTFWhI8MMYyLVH/Key-screen---Windows?node-id=0-1&node-type=canvas&m=dev)
❌ The Titlebar is not responsive to neither theme / sys prefrence
❌ The Titlebar is not using the same background as the client app
Whenever this opens on windows it looks ... cheap, especially the title bar not beeing part of the client space, …

Window Polish on Windows

---

src/cmake/wasm.cmake

so i'm trying to hunt a bug. But it seems we have no debug info. Let's see if this publishes a usable dwarf file, so i can properly set breakpoints. 
Update: IT WORKS !!

WIP WASM: Publish debug info 

---

src/platforms/windows/daemon/windowsdaemon.cpp
src/platforms/windows/daemon/windowsfirewall.cpp
src/platforms/windows/daemon/windowsfirewall.h
src/platforms/windows/daemon/windowssplittunnel.cpp
src/platforms/windows/windowscommons.cpp

We have a bit of a bug in our handling of split-tunnelling when there is no IPv6 connectivity. In particular, if there are no IPv6 routers on the LAN then the network interface will only have link-local addresses, which cannot be used to enable the split tunneling driver. To ensure that split tunneling works on such networks, we need to take care when selecting addresses to avoid link-local addresses.
This PR rewrites ` WindowsSplitTunnel::getAddress()` so that we rank IPv6 addresses to select the address which is most likely to route to the internet, while also ignoring explicitly unroutable addresses such as link-local and loopback.
While we are at it, we also identified an endian conversion bug in the interface selection logic that would also sometimes result in invalid split tunneling …

VPN-6632: Fix split tunnel when IPv6 unreachable

---

src/controller.cpp
src/ui/screens/home/ViewHome.qml

So far we have removed the option to have show the serverlist in state on partial. 
Let's allow that, and keep the activation principal, so that a server switch in partial will result to stay in stateonpartial after the switch. 
This will cause a gui glitch but our pm specifically said he wants that despite that :)

Allow for switches in stateonpartial

---

src/daemon/daemon.cpp
src/daemon/daemon.h
src/platforms/windows/daemon/windowsdaemon.cpp
src/platforms/windows/daemon/windowsdaemon.h
src/platforms/windows/windowscommons.cpp

It seems that split tunneling on Windows is broken when used in combination with multihop. This seems to be caused by calling `prepareActivation()` upon activation of the exit hop. During this call, we try to lookup the interface that routes to the server address, but this is the VPN interface when examining the exit hop.
To fix this, we need to use the address of the entry server, which can be found in the `Daemon::m_connection` member.
While we're at it, we don't really need to explicitly call this `prepareActivation()` method before bringing up the interface, we can just do this whenever since we use the routing table to exclude Wireguard traffic from re-entering the tunnel.
Oh, and there was also a bug in the error logging in `WindowsCommons::AdapterIndexTo()` that we might as well …

VPN-6830: Fix split tunnel on Windows with multihop

---

addons/message_try_firefox_extension/manifest.json

Get ready for this to go to prod.
VPN-6837

Remove staging condition from extension promo addon

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
src/controller.cpp

This PR fixes the timer when relaunching the Android app after a silent server switch or a server location switch initiated by the user. (In both cases, we want the timer to continue counting up and not reset to zero. While this was working as expected while the app remained open, when the app was quit and re-launched the timer would change.)
There were two parts to this fix:
First - In `VPNService.kt`, do not reset the timer when it is a server switch.
However, that didn't fix the bug. I ended up rabbit holing on this for quite a while. Eventually in the logs I noticed additional controller state changes when doing a server switch on Android that didn't exist in similar server switches on iOS. And then I realized the bug is Android's version of #9733. While the bug on Android isn't as …

VPN-6710: fix Android time

---

nebula/ui/components/inAppAuth/MZInAppAuthenticationPasswordCondition.qml
src/ui/authenticationInApp/ViewAuthenticationVerificationSessionByEmailNeeded.qml

I saw a warning in the logs for one of these, then audited [the PR that changed how we handle images](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10170/files) to confirm there were no other omissions - and I found one more.
VPN-6829 (I just created this ticket for tracking purposes)

VPN-6829: add 2 missing imports

---

CODEOWNERS

Strings should no longer be in the manifest files, but will be in the shared strings file - let's make sure that @flodolo reveiws those.
VPN-6838

Update CODEOWNERS per the new addon shared strings

---

.dictionary
docs/Components/updater.md

Add documentation so we don't lose info on the update mechanisms.
VPN-6839

VPN-6839 - add updater info

---

src/theme.cpp

Detect when the system theme changes. VPN-6178 will add the code that actually exposes this to the user.
This will not work on Qt version <6.5, to keep it in line with the [prior system color work](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10131).
VPN-6783

VPN-6783: detect system theme changes

---

Cargo.lock
linux/flatpak/flatpak-vpn-crates.json
signature/Cargo.toml

It looks like we have a bit of a dependency tangle that dependabot isn't able to resolve. In particular it seems like the `asn1-rs`, `oid-registry` and `x509-parser` crates all need to be updated together to cross some kind of API change. So, let's update these dependencies manually so that we can group them together into the same PR.
Conflicting dependabot PRs:
- #10251
- #10222
- #10200

Nit: Update asn1-rs crate and friends

---

CMakeLists.txt
scripts/cmake/check_qt_breakage.cmake

As seen in those issues: 
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/9989
https://github.com/mozilla-mobile/mozilla-vpn-client/issues/9966
We do know it's broken, it's not our fault. 
All we can do here is throw a warning for folks to use 6.8.1 instead :)

VPN-6671 Add a warning for qt 6.8.0

---

Cargo.lock
extension/bridge/Cargo.toml
extension/bridge/src/commands.rs

Based on top of: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10196
Right now we only check if the Split-Tunnel List includes `Firefox*` - but if i.e you have nightly excluded and use the extension on ESR, we still block out. 
Given that Firefox will spawn the nativemessaging process, we can ask it to check it's parent executable. 
This allows the extension to check if the Firefox used is excluded or not.

Give the extension the ability to get the parent process info

---

taskcluster/kinds/repackage-signing/kind.yml
taskcluster/kinds/signing/kind.yml

And while I'm in here, remove the `linux` entries that are long unused.
This needs to wait for https://github.com/mozilla-releng/scriptworker-scripts/pull/1123 to be deployed before it can.

bug 1942364: switch to autograph gcp production for signing

---

src/cmake/sources.cmake
src/controller.cpp
src/controller.h
src/controller_p.cpp
src/controller_p.h
src/platforms/windows/daemon/windowsfirewall.cpp
tests/unit/CMakeLists.txt
tests/unit/main.cpp
tests/unit/testcommandlineparser.cpp
tests/unit/testcontroller_p.cpp
tests/unit/testcontroller_p.h

**Fix the DNS handling in StateOnPartial**
If you put a custom DNS that is not in your LAN, it did not get added to the allowed-ip list in state-on-partial. This caused our firewall rule to catch this and block it.

FXVPN-377 Fix DNS Inclusion

---

extension/socks5proxy/src/socks5.cpp
extension/socks5proxy/src/socks5connection.cpp

When Excluding youtube i noticed quite a bit of buffering, as in the background fetching just stalls. Yt is loading this via http 1.1 so it is going to be holding a bunch of tcp connections open to re-use. The devtools list a lot of fetches aborting with "NS_BINDING_ABORTED". 
So i tried enabling keepalive and this problem goes away :)

FXVPN-383 (?) Proxy: Enable TCP Keepalive

---

linux/flatpak/flatpak-vpn-crates.json

A few weeks ago, a new crate was added for the native messaging bridge to enable browsers to detect if they had been excluded by split tunnelling. Unfortunately, we neglected to update the Flatpak manifests to match, which has been resulting in build failures ever since.
To fix this, we just need to run the `flatpak-update-crates.sh <Cargo.lock>` script to regenerate the manifest accordingly.
JIRA Issue: [VPN-6855](https://mozilla-hub.atlassian.net/browse/VPN-6855)
Introduced by #10216
[VPN-6855]: https://mozilla-hub.atlassian.net/browse/VPN-6855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update flatpak crate manifests after sysinfo crate was added

---

addons/message_update_v2.25.1/enable.js
addons/message_update_v2.25.1/getHelp.js
addons/message_update_v2.25.1/manifest.json
addons/message_update_v2.25.1/osCheck.js
addons/message_update_v2.25.1/update.js
addons/message_update_v2.25.1/updateWeb.js
tests/functional/testAddons.js

Adding an update message for 2.25.1. Since 2.25.1 is just for Windows, we need to maintain a 2.25 update message for all other platforms. Thus, I duplicated the files involved (and added a new `platforms` condition to the 2.25 message).
We also needed to skip a test that catches if there are 2 update messages - but in this case (because of the different versions for different platforms) we want one.
While the 2.25.1 message could omit some things like the `"javascript": "osCheck.js"` condition, I decided to keep them - they don't hurt (except the most minor of a one-time performance hit, as we're running a few lines of unnecessary code), and I'm concerned if we remove lots of this we'll forget to add it back in when creating the messages for 2.26. (Typically, we don't change much when …

VPN-6872: update message for 2.25.1

---

src/ui/screens/home/servers/ServerList.qml

The menu title text is [manually set when pushing in](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/src/ui/screens/home/ViewMultiHop.qml#L62), but wasn't being touched when popping back out. This adds "setting the menu title" to every pop after a multihop server was selected.
[Video of fix](https://github.com/user-attachments/assets/983f1b92-f976-4b6a-a7f9-274af31ed1ae)
VPN-6753

VPN-6753: Reset menu title after location selection

---

src/platforms/android/androidcontroller.cpp
src/platforms/ios/ioscontroller.mm

This callback is being hit on every VPN activation, so it was sending the metric way too often. Wrapping this is an "is it onboarding?" statement fixes the issue.
VPN-6437

VPN-6437: stop extra metric recordings

---

src/commands/commandui.cpp
src/platforms/windows/windowsutils.cpp
src/platforms/windows/windowsutils.h

Hiding and Re-rendering the window can cause the flicker seen in the issue. The best thing, that was completly unneeded.

VPN-6828 - Remove uneeded Window destruction

---

src/addons/manager/addonmanager.cpp
src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml

The "reinstate messages" button wasn't working. We were using a different style of creating the setting group than in other places - once this was updated the modern method, it worked.
Also, the user must relaunch the client after pressing the "reinstate messages" button, so clicking the button now shows the pre-existing "restart required" component.
Also added a tiny bit of logging.
VPN-6892

VPN-6892: Fix "reinstate messages" debug option

---

src/inspector/inspectorhotreloader.cpp
src/inspector/inspectorhotreloader.h
tools/qml_hot_reload/hot.js

I've been trying to get the QML hot reloader working on my Linux machine, and I ran into a couple of difficulties. First the HTTP transport wasn't working outside of localhost, which kind of defeats the point of using HTTP at all, and secondly, we have too many files in the git tree for the `chokidar` library to handle, so we need to restrict the watch list to just QML content.
JIRA issue [VPN-6856](https://mozilla-hub.atlassian.net/browse/VPN-6856)
[VPN-6856]: https://mozilla-hub.atlassian.net/browse/VPN-6856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6856: Fix QML hot reloader tools

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
src/connectionhealth.cpp
src/connectionhealth.h

We record the data transfer telemetry from wireguard. This wireguard data only resets every time there is a new peer (VPN activation, silent server switch, location switch, etc.). We were sending it in every timer ping - which means we were counting data multiple times, as the subsequent timer/end ping would report the cumulative data since the user connected to the peer.
While there are probably ways to make fancy data science dashboards that only use the latest one reported, it seems easiest to fix this by only reporting data transfer when the peer is changed (or the VPN is turned off). (This also has a benefit of allowing adhoc metrics to be run more easily.)
Desktop - We just need to remove the data transfer metrics from the timer ping.
Android - This one was a bit harder, as there …

VPN-6854: fix data throughput Glean issues

---

docs/Troubleshooting/inspector.md
src/platforms/ios/ioscontroller.swift
src/platforms/ios/iostunnel.swift

Ultimately this is pretty simple - We had been assuming that switching the config only happened when the VPN was active. However, when the server/city wasn't available, the VPN was never activated - and thus switching the server was happening when no VPN was active, and getting us into this terrible state
Unfortunately, I wasn't able to figure out precisely how this is happening. I can confirm that when we send the update message from `iosController` to the `iostunnel`, it eventually sends an `update` message to `WireGuardAdapter` - which immediately returns an `.invalidState` back to `iostunnel` (because the adapter wasn't in a `started` state), which in turn doesn’t do anything for the `ioscontroller`. `Even if we run a `disconnectOnErrorCallback` in this situation it doesn’t fully fix …

VPN-6842: invalid server fix

---

extension/socks5proxy/bin/windowsbypass.cpp
extension/socks5proxy/bin/windowsbypass.h
extension/socks5proxy/src/dnsresolver.cpp
extension/socks5proxy/src/dnsresolver.h

In continuing my testing with the socksproxy and the DNS resolution woes, I came across a couple of bugs that can lead to breakage.
The first issue is that when selecting DNS servers, when the first choice is a link-local IPv6 address, we don't set a scope ID in the address, which can prevent `c-ares` from being able to connect to it. We can fix this just by calling `QHostAddress::setScopeId()` when building the list of DNS servers. While implementing this, I also performed a bit of cleanup by moving the DNS server selection into `WindowsBypass::updateNamserver()`
The second issue, which was a bit trickier to track down, is that we have a use-after-free bug in the socks proxy that can occur between the `c-ares` resolver thread and the Qt thread. This happens when the `Socks5Connection` is …

socksproxy: Fix localhost DNS and use-after-free crash

---

nebula/ui/components/navigationBar/MZBottomNavigationBarButton.qml

The opacity was killing the button background effect on dark mode. I replaced it with an equivalent color, so light mode has no perceptible changes.
VPN-6965

VPN-6965: missing navbar background on dark mode

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/ConnectionHealth.kt
src/connectionhealth.cpp
src/connectionhealth.h
src/platforms/ios/ConnectionHealth.swift
src/telemetry/metrics.yaml
tests/unit/testconnectionhealth.cpp
tests/unit/testconnectionhealth.h

We created a range of connection health metrics as we weren't sure which ones would be most useful. At this point, they've expired, and we know which ones we want to extend: the connection health counts.
This PR removes a bunch of metrics, and extends the others.
I looked at the count metrics, and they seem solid explainer of health. I'll be updating our dashboards to use them as part of VPN-5991. The [pinganalyzer error](https://mozilla.cloud.looker.com/x/H8X3cZDDdn7sRqjVy6PFnH) affects about 150 people per day, which isn't enough to worry about at the moment.
VPN-6954

VPN-6954 - remove most metrics, extend others

---

addons/message_update_v2.27/manifest.json
addons/message_whats_new_v2.27/manifest.json

Dark mode isn't coming until 2.28 - so we need to update the addon text to reflect this
VPN-6976

VPN-6976: update 2.27 messages to default text

---

scripts/utils/generate_release_notes.sh

It errored on producing the release notes for this month - because there was only one string.
VPN-6981

VPN-6981: only require 1 argument (string) in release notes script

---

src/cmake/linux.cmake
src/feature/featurelistcallback.h
src/platforms/linux/xdgappearance.cpp
src/platforms/linux/xdgappearance.h
src/platforms/linux/xdgcryptosettings.cpp
src/platforms/linux/xdgportal.cpp
src/platforms/linux/xdgportal.h
src/platforms/linux/xdgstartatbootwatcher.cpp
src/settingslist.h
src/theme.cpp
src/theme.h

It's been reported that Linux doesn't correctly detect the system theme on some Qt versions, and some have reported it broken altogether. So, let's throw together a quick workaround by pulling the theme information from the [XDG Settings portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html).
JIRA issue: [VPN-6971](https://mozilla-hub.atlassian.net/browse/VPN-6971)
[VPN-6971]: https://mozilla-hub.atlassian.net/browse/VPN-6971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6971: Implement theme detection fallback on Linux via XDG portal

---

nebula/ui/components/forms/MZContextualAlert.qml
nebula/ui/components/forms/MZContextualAlerts.qml
nebula/ui/components/forms/MZSearchBar.qml
nebula/ui/components/inAppAuth/MZInAppAuthenticationInputs.qml
src/ui/screens/getHelp/developerMenu/ViewDeveloperMenu.qml
src/ui/screens/settings/ViewDNSSettings.qml

While fixing https://github.com/mozilla-mobile/mozilla-vpn-client/issues/10375 - i noticed anothing thing beeing utterly broken by qt 6.9.0. 
qmllmodels moved from qt.labs to the qt namespace but i could not see a way to conditionally do an `import` if we're on 6.9.+ - 
Now given all that did was switch colors of the button i'm taking your tricks using enums and just remove that dependency.

Qt 6.9 compat:  Remove Qt.labls.qmlmodels usage

---

lottie/lib/lottiestatus.h

Looking at: https://github.com/mozilla-mobile/mozilla-vpn-client/issues/10375
it seems moc generates a function call that tries to call it without arguments. Given all our callsites are providing one, we can just add defaults so moc can happily compile :)

Qt 6.9 compat: Provide default args for LottieStatus::changed so moc can call it

---

.dictionary
docs/Building/macos.md
macos/pkg/CMakeLists.txt
scripts/cmake/osxtools.cmake
src/cmake/macos.cmake

While working away on #10358 it was necessary to be able to build and sign both the Mozilla VPN bundle as well as the MacOS installer package. But unfortunately this has been rather broken outside of Xcode for a while now. So while working on that PR, I have collected a bunch of fixes to get codesigning working again outside of Xcode.

MacOS: Fix a bunch of codesign issues when building outside Xcode

---

android/vpnClient/src/main/java/org/mozilla/firefox/vpn/qt/PackageManagerHelper.kt
src/settingslist.h

Make [Google Fi](https://play.google.com/store/apps/details?id=com.google.android.apps.tycho) show up on the list, and exclude it by default.
While I can confirm that the app shows up on the list and is excluded by default, I do not have a Google Fi cell plan and thus cannot check if this rectifies the calling issue.
I've also left a comment to make the secondary allow list more obvious to find in the future.
VPN-6983

VPN-6983: exclude Google Fi

---

src/controller.cpp

For the last long while, the WASM UnsecuredNetworkAlert functional test has been flaky. It mostly passes, but fails maybe 20% of the time. A rerun typically fixes it. 
It errors out on a timeout in `afterEach`. I isolated the issue to [this line](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/main/tests/functional/setupWasm.js#L167). While you can see it is wrapped in a try/catch, the timeout for `afterEach` doesn't seem to throw. And wrapping that block in a `Promise.race` didn't fix it either.
Digging in to the controller's quit function, it doesn't seem to handle the `confirming` state. Given that at the end of this test, we're usually in some state of connecting, it makes sense that this could be the reason for inconsistent failures. I haven't been able to get a run to …

VPN-6893 part 2 - fix WASM’s UnsecuredNetworkAlert functional test

---

src/platforms/macos/macoscontroller.h
src/platforms/macos/macoscontroller.mm
src/ui/screens/ScreenPermissionRequired.qml

In PR #10358 we tried to add a new mechnaism to register the macOS daemon using the `SMAppService` API, but unfortunately I missed an edge case and mis-handled the Obj-C object lifecycle leading to a possible crash when compiled for release.
First off, the crash was being caused by saving the `SMAppService` object reference in the `MacOSController` class. It seems that Obj-C will automatically garbage collect the references at the end of the function scope, leading to a use-after-free bug that could crash the application. For whatever reason, this crash was only observed once compiled for release. To fix this, we stop saving the `SMAppService` object and we just created it anew whenever we need it.
The second issue occurs when upgrading the daemon. In this scenario we attempt to get the …

VPN-6945: Fix SMAppService registration bugs

---

src/ui/screens/settings/ViewAppearance.qml
src/ui/screens/settings/ViewDNSSettings.qml
src/ui/screens/settings/appPermissions/AppPermissionsList.qml

From feedback on foxfooding - improve tap targets for the Dark/Light appearance. I went ahead and fixed the few other spots I could find a similar issue.
VPN-7010

VPN-7010: make entire rows tap targets

---

nebula/ui/components/MZMobileStatusBarModifier.qml
src/theme.h

We could remove a whole lot of the code for status bar and it would *almost* all work as expected - but logging in on light mode on iOS 16 (and possibly iOS 15) would end up with an incorrect color for the email/password/etc. screens. I [wrote up code for this](https://github.com/mozilla-mobile/mozilla-vpn-client/compare/vpn-6974-fix-status-bar-color?expand=1), and tested it out. Though we have few users on iOS 15 and iOS 16, this PR's solution works for iOS 15-18. However, once we cut off iOS 16 in a couple years, we'll be able to get rid of a bunch of this code.
I tested this on iOS 15, iOS 16, iOS 17, and iOS 18 (all the major versions we support) - both dark mode and light mode, on the log in flow and in the main app. For all these scenarios, I tested both a cold launch, and switching …

VPN-6974: status bar color when logging in on dark mode

---

tests/functional/testServers.js

I'm going to put each test fix up as a separate PR. This fixes the Servers functional test. 
[I created this test](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10238/files#diff-ecac75875a7bfd126997889026cef83ea780e46d4c1f0e985db256eabe718c14) a while back.
There is some sort of inconsistent race condition. For some reason, this line doesn't work:
` await this.waitForQueryAndClick(queries.screenHome.serverListView.ALL_SERVERS_TAB.visible());`
The test sometimes passes this line before the all servers tab is selected. I tried a few different ways to get around this - and the best thing I could find is this awful hack here.
VPN-6893

VPN-6893: part 1 - fix servers test

---

src/ui/screens/messaging/ViewMessagesInbox.qml

While not directly related, this came out of the dark mode work. Jamie pointed out this is a fairly pointless message bar, given the quantity of messages we use now (and will likely ever use in the future). Let's simplify our code and remove it!
VPN-6920

VPN-6920: remove messages search bar

---

.github/workflows/linux.yaml

Fedora 42 was released on 2025-04-15, cf. https://fedoramagazine.org/announcing-fedora-linux-42/
Current builds (tried 2.27.0~rc20250414171010-1 downloaded from https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/14451532392) depend upon libQt6Gui.so.6(Qt_6.8_PRIVATE_API)(64bit) but since Fedora 42 is on Qt 6.9 no current package provides that symbol.
N/A

Update RPM build to Fedora 42

---

src/ui/screens/settings/ViewAppearance.qml
src/ui/screens/settings/ViewDNSSettings.qml
src/ui/screens/settings/appPermissions/AppPermissionsList.qml

This is a follow up to https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10443, thanks to something QA found.
For reasons I don't fully understand, `MZMouseArea` results in 16 points of horizontal space being used - causing the regression described by QA. (You can confirm this by moving `MZMouseArea` in between the radio button and the text label - and that area will grow too large.) 
I'm not sure why this happens, but we can hide this extra space (while keeping the functionality) by moving it to the end of the row.
It's now fixed:
VPN-7010

VPN-7010 follow up - make spacing better

---

nebula/ui/themes/color-themes/dark-mode.js
nebula/ui/themes/color-themes/main.js
nebula/ui/themes/theme-derived.js
src/ui/screens/home/controller/VPNToggle.qml

Updated the disconnected switch to have an outline on dark mode (with a main color identical to the background). Also tweaked colors of the toggle's circle.
Also made that hover glow slightly larger, as this border is outside the toggle - so that glow looked too thin with a couple points being taken up by this new outline.
Video shows dark mode and light mode - both using the mouse, then using the keyboard, then finally showing what the default toggles look like (they do not change in this PR): https://github.com/user-attachments/assets/c780c317-9ba9-4cab-ae05-a43c0dd29622
VPN-7017

VPN-7017: improved dark mode toggle

---

extension/socks5proxy/bin/linuxbypass.cpp
extension/socks5proxy/bin/linuxbypass.h
extension/socks5proxy/bin/windowsbypass.cpp
extension/socks5proxy/bin/windowsbypass.h
extension/socks5proxy/src/dnsresolver.cpp
extension/socks5proxy/src/dnsresolver.h
extension/socks5proxy/src/socks5.cpp
extension/socks5proxy/src/socks5.h
extension/socks5proxy/src/socks5connection.cpp
extension/socks5proxy/src/socks5connection.h

The `socksproxy` tool is capable of generating DNS queries on behalf of the browser, but at present we don't take any explicit steps to exclude those DNS queries from the VPN tunnel. Normally this isn't a big deal as the DNS server is typically on the user's LAN, but if they happen to be using a DNS server on the public internet then this can result in incorrectly routed DNS queries.
To fix this, we need to use the `c-ares` socket functions in order to provide a hook on socket creation/connection where we can insert the VPN bypass code. As a side effect, we must also disable the `c-ares` thread and integrate it with the Qt event loop in order for these hooks to work.
This should resolve the case where some users are unable to exclude websites due to their ISP's DNS servers rejecting …

VPN-6966: Exclude DNS traffic from socksproxy

---

.gitignore
extension/bridge/src/commands.rs

I'm currently hacking on the extension's "let's start the vpn when entering PBM". 
Given we switch to on-partial mode, nothing visually happens in the client when we activate the extension. 
So it's a bit off-putting that if you then open a private browsing mode a vpn windows appears in the center of your screen, empty, deactivated. Like it's judging you to activate it. 
But we actually already did this the moment you see the screen, so let's just allow the extension to start the vpn in the background 🥳

Allow the extension to trigger a minimized start

---

android/AndroidManifest.xml

> On [Android 12 (API level 31)](https://developer.android.com/about/versions/12/12L/summary#dev-device-orientation-request) and higher, device manufacturers can configure individual device screens (such as the tablet-sized screen of a foldable) to ignore this suggestion, and instead force an activity to be letterboxed within the user's preferred orientation of the device.
If we look at #10442 we're clearly in that letterboxing case that seems to fuck stuff up. 
My current hypothesis is that while we're letterboxed, qt still assumes the full width+height of the landscape screen

Android: Remove orientationlock

---

macos/pkg/scripts/postinstall.in

When users attempt to upgrade from 2.27 to the latest and greatest. The installer package would leave the `/Library/LaunchDaemons/org.mozilla.macos.FirefoxVPN.daemon.plist` file on disk. This would cause problems when trying to install the daemon service using `SMAppService` which gets confused and thinks the daemon already exists.
To ensure that the daemon can be cleanly installed, we need to make sure to clean that file up at package installation.
JIRA Issue: [VPN-7024](https://mozilla-hub.atlassian.net/browse/VPN-7024)
JIRA Issue: [VPN-6945](https://mozilla-hub.atlassian.net/browse/VPN-6945)
[VPN-7024]: https://mozilla-hub.atlassian.net/browse/VPN-7024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-6945]: …

VPN-7024: Remove legacy daemon plist during package install

---

src/controller.h
src/ui/screens/home/controller/ControllerImage.qml
src/ui/screens/home/controller/VPNToggle.qml

A few things to make this smoother:
- Fix the `insetCircle` color on initialization. This fixes the "inset circle is green when there is no daemon found" problem.
- Give the `toggleColor` a default value. This fixes the "there is a flicker on dark mode when moving to this screen while the switch is off" problem.
- Change all the remaining `vpnToggleDisconnected` to `vpnToggleDisconnectedMainSwitch`. This fixes the "when no daemon, the switch shows as solid gray on dark mode" problem.
- Update `StatePermissionRequired` to show the proper outline border.
VPN-7027

VPN-7027: Fix main switch for transitions and when there is no daemon

---

.github/workflows/flatpak.yml

So i noticed that sometimes the flatpack builds fail i.e 
https://github.com/mozilla-mobile/mozilla-vpn-client/actions/runs/14845508171/job/41712574160?pr=10478 
```
========================================================================
Building module mozillavpn in /__w/mozilla-vpn-client/mozilla-vpn-client/.flatpak-builder/build/mozillavpn-1
========================================================================
Updated Git hooks.
Git LFS initialized.
fatal: unable to read tree (cd92b367c45901b0bc742d1018c5c0c8f87b8c97)
Error: module mozillavpn: Child process exited with code 128
```
What put me off is that the commit `cd92` it fails to load is not part of the pr: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10478
It seems that the `${github.sha}` points to: 
> Note that …

CI: Have Flatpack build the branch rather a merge commit

---

macos/pkg/scripts/postinstall.in
src/localsocketcontroller.h
src/platforms/linux/backendlogsobserver.cpp
src/platforms/macos/daemon/macosdaemonserver.cpp
src/platforms/macos/daemon/macosdaemonserver.h
src/platforms/macos/macoscontroller.h
src/platforms/macos/macoscontroller.mm

Sometimes we get support tickets from users where the daemon is offline for one reason or another, and we find ourselves having to guide users through manually fetching the logs off disk. This is a pain in the butt and in many cases we can automate this with some platform-specific code in the controller to access the log files.
This implements the fallback for macOS and Linux. I don't think it's feasible to do the same on Windows as the log file is written to a protected directory.
JIRA Issue [VPN-7035](https://mozilla-hub.atlassian.net/browse/VPN-7035)
[VPN-7035]: https://mozilla-hub.atlassian.net/browse/VPN-7035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7035: Add background log fallback when daemon is not running

---

src/constants.h
src/mozillavpn.cpp
src/ui/sharedViews/ViewPermissionRequiredOSX.qml

The new OSX permission required screen doesn't match the Figma designs, in particular the `Help` link is in the wrong place and is inteded to open a SUMO article instead of opening the help screen. This should move the link and add a URL to SUMO as expected.
The updated screen is as follows:
JIRA Issue: [VPN-6941](https://mozilla-hub.atlassian.net/browse/VPN-6941)
Figma Design: [link](https://www.figma.com/design/aqZq6eYrgAthI6BU3Soasr/macOS-Permissions-Update?node-id=97-157)
[VPN-6941]: https://mozilla-hub.atlassian.net/browse/VPN-6941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6941: Update OSX permission required screen to use SUMO link

---

src/ui/main.qml

Adding newer iPhone sizes. I didn't realize we manually set this; I've added a reminder for myself to update this (if needed) when new iOS devices come out. I checked these sizes against a [couple](https://www.ios-resolution.com/) [spots](https://www.practicallynetworked.com/iphone-size-comparison-chart/), and confirmed against [Apple's docs](https://www.apple.com/iphone-16-pro/specs/) for the 16 Pros.
(Unnecessary grumble grumble... a native app is typically setup to handle this automatically by default, at this point only something like Qt needs manual updates to keep this working when new devices sizes come out... shakes fist at sky.)
VPN-7034

VPN-7034: add new iPhone sizes to fix layout issue

---

nebula/ui/components/MZPopupButton.qml

For reasons unknown, `MZPopupButton` is only used in `VPNRemoveDevicePopup`, so this is the only place with this issue. I introduced this problem in [a recent PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10462/files#diff-ed0c2a194000472763071a0f94554aa7e7b9c74c6bf0dd7cae9e6e044d275d7b), where I changed how button colors were created. I didn't realize that this button was defined differently from the rest, and required the color to be set here.
Screenshots of it fixed:
VPN-7025

VPN-7025: fix button font color

---

.github/workflows/flatpak.yml

From [docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs) on `head-ref`: `The head_ref or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either pull_request or pull_request_target.`
So by definition, it’s expected this would fail when running tests on `main`, as we've observed. But it’s succeeding on PRs. (And this changed [in a recent PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10480/files).)
Looking at [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs), maybe `ref` is what we want?
VPN-7040

VPN-7040: fix flatpaks tests?

---

src/platforms/ios/iosiaphandler.mm
src/platforms/ios/iosiaphandler.swift
src/purchaseiaphandler.cpp

I believe adding `transaction.finish()` fixes the bug, likely completely. The rest of this code is mostly to make things more defensive in case similar edge cases pop up - we only try to complete transactions if we're actually in the process of doing a transaction in the UI.
I'm not 100% sure if we need to call `transaction.finish()` on the expired/upgraded/revoked code paths. The documentation is silent on this, and there are a variety of opinions in forums. Ultimately, with the defensive work done it shouldn't matter for these code paths whether we finish them or not.
- Pretty quickly, I identified via the client logs that we were running `TaskAddDevice` more than we should, and that sometimes we didn't think the current device was in the account. This led me down an unfruitful rabbit …

VPN-6921: Logout upon launch w/ in app purchase

---

extension/CMakeLists.txt

The systemd service file for the `socksproxy` service used for the Firefox extension uses the `CMAKE_INSTALL_FULL_BINDIR` variable to determine the path to the binary. This variable is defined by the `GNUInstallDirs` CMake package which we include in the main project, but can be missing for the extension. To fix this, we simply need to include the module.
Thanks to @awisse for reporting this one.
JIRA Issue: [VPN-7012](https://mozilla-hub.atlassian.net/browse/VPN-7012)
Github issue: #10446
[VPN-7012]: https://mozilla-hub.atlassian.net/browse/VPN-7012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7012: Fix Socksproxy service paths

---

extension/socks5proxy/bin/main.cpp
extension/socks5proxy/bin/sockslogger.cpp

The status logger in the `socksproxy` tool periodically writes to `stdout` to show some live statistics when the proxy is running, but this is inappropriate to be printing into logfiles. We should disable this feature when the output device is not a TTY.
During testing, it was also found that we have a bug on Qt 6.2.4 where the `QHostAddress` class doesn't automatically get registered as a metatype for signal/slot delivery, which can result in another source of spammy log messages and breakage of of the socket bypass hooks.
Thanks to @awisse for reporting this one!
JIRA Issue: [VPN-7039](https://mozilla-hub.atlassian.net/browse/VPN-7039)
Github issue: #10490
[VPN-7039]: https://mozilla-hub.atlassian.net/browse/VPN-7039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …

VPN-7039: Fix socksproxy logspam

---

macos/app/service.plist.in
macos/pkg/scripts/postinstall.in
src/cmake/macos.cmake
src/platforms/macos/macoscontroller.h
src/platforms/macos/macoscontroller.mm

So, digging a little deeper into the bowels of macOS, and I think there's some jankiness in the process of upgrading a service from the legacy launchd-style daemon into an embedded daemon managed with SMAppService. The problem seems to stem from a lack of coordination between launchd and the background task manager.
The problem goes something like this:
1. We remove the old launchd daemon during package installation and purge its plist off disk.
2. We install the new VPN application bundle and it tries to register the service.
3. The daemon identifier is still known as a legacy daemon by the background task manager. So it rejects the service installation.
4. Eventually, the background task manager rescans its database and drops the legacy daemon. But this doesn't seem to occur in any kind …

VPN-7024: Rename SMAppService daemon to org.mozilla.macos.FirefoxVPN.service

---

extension/CMakeLists.txt

This is mostly just developer pain, but when performing a universal build under Xcode we find that the `cargo` tool in the path may not necessarily be the one installed from Conda, in which case it can fail to locate the Rust standard libraries for the cross-compiled targets.
To fix this, we basically just need to use the full path to the Conda-installed `cargo` and `rustc` tools. Fortunately, we already did all this in the `rustlang.cmake` scripts and we just need to use the variables they already defined.

Nit: Fix universal builds of mozillavpnnp under Xcode

---

src/ui/screens/home/controller/ControllerImage.qml

This was caused by going to default colors. I gave it some explicit state.
FWIW, it's not noticable on desktop because it moves from StateSilentSwitching to StateConnecting in a few milliseconds. Whereas on iOS, it moves from StateSilentSwitching to StateOn, which takes a few hundred milliseconds typically.
To repro/test on desktop, just comment out the `deactivate()` line in `Controller::silentSwitchServers`.
VPN-7050

VPN-7050: give explict colors for StateSilentSwitching

---

src/qmlengineholder.cpp

I just upgraded my build machine to Qt 6.9.x 
we use stuff from windows.h but we got that from a QT import

Bugfix: ICWYU - Include windows.h

---

.github/workflows/auth_tests.yml
CMakeLists.txt
docs/Building/index.md
src/cmake/sentry.cmake

- **Let the people disable sentry**
- **the auth tests do not need that**

CMAKE: Add an option to disable sentry

---

src/platforms/macos/macoscontroller.h
src/platforms/macos/macoscontroller.mm

Another entry in the endless saga of the MacOS daemon upgrade. This time we put some debugging energy into macOS13 to see what happens.
It seems like there is a bit of an API behaviour difference on macOS 13 vs. later operating systems. In particular `registerAndReturnError` can fail when permission has been denied, so we actually need to retry `regsiterAndReturnError` until we get a successful return code and the status of the service is `SMAppServiceStatusEnabled`
JIRA Issue: [VPN-6945](https://mozilla-hub.atlassian.net/browse/VPN-6945)
[VPN-6945]: https://mozilla-hub.atlassian.net/browse/VPN-6945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6945: Add SMAppService registration retries

---

macos/pkg/scripts/postinstall.in
src/controller.cpp
src/tasks/controlleraction/taskcontrolleraction.cpp

There is something of a deadlock that can occur during shutdown of the VPN client if the backend service is also unavailable. This can manifest on a macOS machine during package upgrade (or when triggered manually with `sudo pkill -x "Mozilla VPN"`).
The sequence of events that lead to the deadlock goes something like this:
1. The VPN client receives a `SIGTERM` signal and requests the Controller class to quit. The controller, is already disconnected so this is a no-op and the controller class emits `readyToQuit()`
2. The `MozillaVPN` class receives `readyToQuit` and starts the shutdown process. During this time, it flushes the task queue and calls `MozillaVPN::disconnect(true)` which requests the controller to disconnect and blocks until complete. This is done using a …

VPN-7042: Fix shutdown/upgrade deadlock

---

src/platforms/macos/macoscontroller.mm

I found another edge case that can result in a stuck client during service registration. In particular, it seems that sometimes when removing a service registration it can take a bit of time for the old service to terminate. During this time the call to `registerAndReturnError` can return an error and leave the status in `not regsitered`. Simply retrying the registration at a later time seems to fix the issue.
I have observed this occurring on macOS 13 when re-installing 2.29 over an existing 2.29 build.
JIRA Issue: [VPN-6945](https://mozilla-hub.atlassian.net/browse/VPN-6945)
[VPN-6945]: https://mozilla-hub.atlassian.net/browse/VPN-6945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-6945: Add retries on service not registered error

---

src/webextensiontelemetry.cpp

In case of an event we did not submit the extras object we might have been sending from the extension

Submit Telemetry Extras 

---

macos/loginitem/main.m

After we increased the minimum macOS deployment target to 11.0, the legacy branch in the loginitem handler is no longer reachable, and it has left a bunch of deprecated code warnings in the `loginitem` target due to the deprecation of [launchAppWithBundleIdentifier](https://developer.apple.com/documentation/appkit/nsworkspace/launchapplication(withbundleidentifier:options:additionaleventparamdescriptor:launchidentifier:)) in macOS 11.0. We can simply delete the offending code.
The errors go something like this:
```
(vpn) naomi@Naomi-MBP build-macos % cmake --build . --target loginitem
[0/2] Re-checking globbed directories...
[2/3] Building OBJC object macos/loginitem/CMakeFiles/loginitem.dir/main.m.o
/Users/naomi/Work/mozilla-vpn-client/macos/loginitem/main.m:32:66: warning: …
```

Nit: Remove dead code from macos loginitem

---

src/platforms/wasm/wasmcontroller.cpp

In PR #10520 I introduced a bug that was leading to an infinite loop in the WASM Connection test, the underlying cause is a little bit sneaky but has to do with the lack of threading on WASM. The issue occurs in the race condition test, and it goes something like this:
1. When the race condition occurs, we wind up with two `TaskControllerAction` in the `TaskScheduler`.
- `m_running_task` is activating the VPN
- a queued task is waiting to silent-switch the VPN.
2. In the final step of the activation, the daemon polls for the server handshake time and does an `emit` in the middle of the for-loop in `Daemon::checkHandshake()` to signal that the connection is up.
3. Note that because WASM is single-threaded, all the signal handling occurs in the same callstack, so in the middle of this …

WASM: queue the activate/deactivate daemon commands

---

scripts/linux/script.sh
src/feature/featurelistcallback.h
taskcluster/kinds/build/linux.yml
taskcluster/kinds/docker-image/kind.yml

Ubuntu 20.04/Focal Fossa is coming to its EOL status on May 29th, 2025, and as such the Launchpad PPA will longer accepts builds for this platform. This means that we can start to remove out build tasks and support for this target.
JIRA Issue: [VPN-7068](https://mozilla-hub.atlassian.net/browse/VPN-7068)
ESM Announcement: https://lists.ubuntu.com/archives/ubuntu-announce/2025-April/000310.html
[VPN-7068]: https://mozilla-hub.atlassian.net/browse/VPN-7068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7068: Deprecate Ubuntu/20.04 Focal Fossa

---

src/main.cpp
src/platforms/windows/windowsutils.cpp
src/platforms/windows/windowsutils.h

We should only need to call loadlibrary with things in our app path and system32, really.

Lock down where we can load dll's at runtime

---

src/cmake/macos-daemon.cmake

The daemon uses a few functions out of the `Security` framework to determine its signing identities and enforce codesigning of the connecting clients. Unfortunately, it seems that we forgot to link to the `Security` framework causing build failures for some developers.
JIRA Issue: [VPN-7070](https://mozilla-hub.atlassian.net/browse/VPN-7070)
[VPN-7070]: https://mozilla-hub.atlassian.net/browse/VPN-7070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7070: Daemon should link to the Security framework

---

src/utils/loghandler.cpp

Here's a neat bug.
In PR #10571 we fiddled a bit with the `LogHandler` to preserve the logfile path of the daemon, and in order to do this we moved the lookup of `QStandardPaths::writeableLocation(QStandardPaths::AppDataLocation)` from a static variable (initialized at the C++ runtime setup) into the `LogHandler` constructor (initialized on first use).
Normally, `QStandardPaths::AppDataLocation` resolves into some path that contains the org and app names (eg: `~/Library/Application Support/<organization>/<app name>`), but when this is invoked before setting the `QCoreApplication::applicationName()` this actually omits the org and app names causing the path to resolve to the same thing as `QStandardPaths::GenericDataLocation`.
Therefore, by moving the initialization code around, we …

Nit: Fix changed log path

---

taskcluster/kinds/mac-notarization/kind.yml

In PR #10594 we reorganized the macOS taskcluster jobs to split the package step into its own `repackage-macpkg` task separate from the application codesigning. Unfortunately, this seems to have broken the `mac-notarization` task due to a chain-of-trust validation error, which is trying to validate the `repackage-macpkg` task under the expectation it was run as a scriptworker task.
I think the culprit is the `buildType` settings in the `upstream-artifacts`, which should have been updated to `repackage` from `signing`
Introduced by: #10594
JIRA Issue: [VPN-7090](https://mozilla-hub.atlassian.net/browse/VPN-7090)
JIRA Issue: [VPN-7091](https://mozilla-hub.atlassian.net/browse/VPN-7091)
[VPN-7090]: https://mozilla-hub.atlassian.net/browse/VPN-7090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

VPN-7090: Fix macOS repackage chain of trust

---

src/commands/commandui.cpp

According to [Qt documentation](https://doc.qt.io/qt-6/qguiapplication.html#setHighDpiScaleFactorRoundingPolicy), `setHighDpiScaleFactorRoundingPolicy` "must be called before creating the application object."
In [a recent PR](https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10571/files#diff-705b181dfea5ef23cadef0ed0e133fdf1192f2d41d0ba9435e4b7f5ecd8f8cfcR207-R225), this was moved and was no longer called before the app object was created - which apparently causes this bad behavior. I isolated the issue to this single line (removing the line with `setHighDpiScaleFactorRoundingPolicy` makes it work as expected), but moved this whole chunk of graphics stuff up to be on the safe side of things.
Looks okay again:
VPN-7087

VPN-7087: Fix Android nav bar

---

addons/message_upgrade_to_bundle_1/conditions.js
addons/message_upgrade_to_bundle_2/conditions.js
addons/message_upgrade_to_bundle_3/conditions.js

Santiago pointed out that for those of us with long-running subscriptions, the date shown in the addon can be years ago. (See Jira issue for image.) The original logic was to show the "date this addon would be enabled on", which is in line with many of our other addons.
This updates the logic to use "date the addon was released" (which is hardcoded) or the date the addon would be enabled for your situation - whichever is more recent.
VPN-7120

VPN-7120: update addon date

---

.github/workflows/auth_tests.yml
.github/workflows/linters.yaml
.github/workflows/macos_tests.yaml
.github/workflows/test_unit.yaml
docs/Building/android.md
docs/Building/index.md
docs/Building/ios.md
docs/Building/macos.md
env-android.yml
env-apple.yml
scripts/android/conda_trim.sh
scripts/macos/conda_install_extras.sh
taskcluster/kinds/toolchain/conda_android.yml
taskcluster/kinds/toolchain/conda_osx.yml
taskcluster/scripts/toolchain/conda_pack_android.sh
taskcluster/scripts/toolchain/conda_pack_ios.sh
taskcluster/scripts/toolchain/conda_pack_macos.sh

As a prerequisite to supporting OSX cross compilation, we are going to need to add a bunch of tooling to the conda environment and rather than injecting a lot of cruft into the Android build environment, it would be best if we just split the Conda environments for Apple and Android targets.
For what it's worth, we have never really had a common environment anyways, since the `conda_trim.sh` script removes a lot of stuff from the Android environment.
Prerequisite for [VPN-5276](https://mozilla-hub.atlassian.net/browse/VPN-5276)
Split from: #10584
[VPN-5276]: https://mozilla-hub.atlassian.net/browse/VPN-5276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-5276: Split apple and android conda environments

---

taskcluster/kinds/mac-notarization/kind.yml
taskcluster/kinds/repackage-signing/kind.yml
taskcluster/kinds/repackage/kind.yml
taskcluster/mozillavpn_taskgraph/transforms/signing.py
taskcluster/mozillavpn_taskgraph/worker_types.py

We recently updated the macOS taskcluster jobs to use a new hardened signer that gives us more fine-grained control over the provisioning profiles and entitlements used to sign the application, but this left us with an unsigned macOS installer package, which then failed notarization.
To fix this, we need to add an extra `repackage-signing-macpkg` job to taskcluster to sign the installer package before notarization.
This depends on a new `mac_sign_pkg` signing behavior in `iscript` which needs to land first.
Waiting on: mozilla-releng/scriptworker-scripts#1236
Signing change: https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10594
JIRA Issue: [VPN-7090](https://mozilla-hub.atlassian.net/browse/VPN-7090)
JIRA Issue: [VPN-7091](https://mozilla-hub.atlassian.net/browse/VPN-7091) …

VPN-7090: Add repackage-signing-macpkg task to sign the macOS installer

---

taskcluster/kinds/mac-notarization/kind.yml

After merging PR #10604 we are correctly producing signed macOS installer packages, but the notarization task fails with an error like the following:
```
2025-06-26T22:07:39     INFO - Running scriptworker version 60.10.2
2025-06-26T22:07:39     INFO - build_task_dependencies scriptworker aTNCHHK7S8KmgPiPiQsHbw
2025-06-26T22:07:39     INFO - find_sorted_task_dependencies scriptworker aTNCHHK7S8KmgPiPiQsHbw
2025-06-26T22:07:39     INFO - found dependencies: [('scriptworker:parent', 'G3KSWn_ZS0KWmT5AkSRYNQ'), ('scriptworker:repackage-signing', 'IbZr3rUOT9K7f0gT9cIyqw')]
2025-06-26T22:07:39    DEBUG -  scriptworker:parent G3KSWn_ZS0KWmT5AkSRYNQ is docker-worker
2025-06-26T22:07:39    DEBUG -  makedirs(/app/workdir/cot/G3KSWn_ZS0KWmT5AkSRYNQ)
2025-06-26T22:07:39     INFO - …
```

VPN-7090: Change taskType to signing for mac-notarization

---

macos/pkg/CMakeLists.txt

During some recent macOS signing changes, we split the generation of the macOS installer package into a separate taskcluster job. Unfortunately, by doing so we introduced a bug where the postinstall codesigning checks were left without app and team identifiers defined. This causes the postinstall script to fail its codesigning checks, resulting in a failed package installation.
To fix this, we can pull the app identifiers out of the application bundle's plist and we provide a sensible default for the development team. 
Introduced by: #10594
JIRA Issue: [VPN-7090](https://mozilla-hub.atlassian.net/browse/VPN-7090)
JIRA Issue: [VPN-7091](https://mozilla-hub.atlassian.net/browse/VPN-7091)
[VPN-7090]: https://mozilla-hub.atlassian.net/browse/VPN-7090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

VPN-7090: Fix codesign identifier detection when building macpkg

---

src/cmake/macos.cmake

We recently added a new `icnsutil` tool to generate the macOS AppIcon, but unfortunately it doesn't quite work on Xcode because the tool doesn't exist in Xcode's paths. To make it work, we need to use a tool that was found in CMake using `find_program` which will ensure it is invoked by the full path.
Introduced in PR #10607

Fix icnsutil when building with Xcode

---

src/cmake/android_openssl.cmake

The android builds have begun to fail recently due to an upstream commit to the [KDAB/android_openssl](https://github.com/KDAB/android_openssl) project. This resulted in a change in the hash of the master commit archive.
This should fix the build by doing two things:
1. We specify the what to check out by it's commit hash, which should be a stable identifier.
2. We update `FetchContent_declare()` to use the GIT repository rather than the github archive URL.

android: Update openssl to fetch a stable git commit

---

taskcluster/kinds/mac-notarization/kind.yml
taskcluster/kinds/signing/kind.yml

It seems that the taskcluster index route for the latest macOS build points to the `signing-macos/opt` task. This was a bit dubious before the recent signing changes as this would have linked to a signed-but-not-notarized installer package but after the signing change this now points to an intermediate build artifact.
What this should really point to is either `repackage-signing-macpkg` or `mac-notarization`.
JIRA Issue: [VPN-7138](https://mozilla-hub.atlassian.net/browse/VPN-7138)
[VPN-7138]: https://mozilla-hub.atlassian.net/browse/VPN-7138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7138: Update macos index route to use mac-notarization

---

src/daemon/daemon.h
src/platforms/macos/daemon/xpcdaemonserver.mm
src/platforms/macos/macoscontroller.mm

When we added the XPC service API, we rewrote the implementation of `MacOSController::getBackendLogs()` and we introduced a bug where we can fail to read the logs in a way that never invokes the error handler either. This results in a call to `getBackendLogs()` that never closes the logfile, and results in an incomplete log file.
This occurs when the daemon is not running, and has never successfully been initialized. In such a situation `m_connection` is a null pointer, which results in no XPC call ever being made. To fix this, we can create an ad-hoc XPC connection to the daemon for reading the logs. This should ensure that an attempt is always made to read the logs, regardless of the state of the daemon.
JIRA issue: [VPN-7122](https://mozilla-hub.atlassian.net/browse/VPN-7122)
JIRA …

VPN-7122: Fix view logs when macOS daemon not running

---

scripts/cmake/rustlang.cmake

We have a build failure as a result of PR #10609 which moved some things around in the rustlang configuration. This work caused the incorrect linker path to be provided to the `armv7a` android builds. This is due to the fact that the rustc target architecture is `armv7-linux-androideabi` but the toolchain's linker binary prefix is `armv7a-linux-androideabi` (note the extra `a`).
The `armv7a` architecture is a special case, and it also only happens to be built only on main, which is why we missed the error.
Introduced by #10609

Fix android rust linker for armv7-a

---

src/utils.cpp
src/utils.h
src/utils/loghandler.cpp
src/utils/loghandler.h

Now that things are moving again with Flatpak distribution, I have done some testing discovered that the view logs link doesn't work as expected when running in a Flatpak, or any sandboxed environment for that matter.
The problem is that we look for the following paths to write logs:
- desktop
- home
- tmp
But, none these paths are not reachable outside the sandbox, so when the client tries to open a URL to the log file, it doesn't get translated into anything the host environment can access. To fix this, we should try to write the logs first to the path indicated by the [XDG_DATA_HOME](https://specifications.freedesktop.org/basedir-spec/latest/#variables) environment variable.
JIRA issue: [VPN-7156](https://mozilla-hub.atlassian.net/browse/VPN-7156)
[VPN-7156]: …

VPN-7156: Fix view logs in containerized environments

---

scripts/cmake/rustlang.cmake

In PR #10609 we tried to merge all the rustlang environment hacking into a common `config.toml` file, which mostly worked, but in that change it seems like we broke the setting of the library rpath for iOS Frameworks.
This attempts to fix the issue by setting the rpath after the build using the `install_name_tool` program, after which we can remove the linker arguments.
JIRA Issue [VPN-7153](https://mozilla-hub.atlassian.net/browse/VPN-7153)
Bug introduced by PR https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10609
[VPN-7153]: https://mozilla-hub.atlassian.net/browse/VPN-7153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7153: Use install_name_tool to set rpath for iOS frameworks

---

src/platforms/linux/daemon/iputilslinux.cpp

It seems like the default interface flags for Wireguard include `IFF_PROMISC` which some users seem to find undesirable. We don't need this flag to be set for any particular reason, so it shouldn't do any harm to disable it.
JIRA issue: [VPN-7157](https://mozilla-hub.atlassian.net/browse/VPN-7157)
Github issue: #10541
[VPN-7157]: https://mozilla-hub.atlassian.net/browse/VPN-7157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7157: Disable IFF_PROMISC on VPN network interface

---

scripts/cmake/rustlang.cmake

Cherry-pick PR #10657 to `releases/2.30.0`
JIRA Issue: [VPN-7153](https://mozilla-hub.atlassian.net/browse/VPN-7153)
[VPN-7153]: https://mozilla-hub.atlassian.net/browse/VPN-7153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cherry-pick: VPN-7153: Use install_name_tool to set id instead of rpath

---

android/daemon/src/main/java/org/mozilla/firefox/vpn/daemon/VPNService.kt
src/models/serverdata.cpp
src/models/serverdata.h
src/platforms/android/androidcontroller.cpp
src/platforms/ios/ioscontroller.mm
src/platforms/ios/ioscontroller.swift
src/platforms/ios/iostunnel.swift
src/telemetry.cpp
src/telemetry/metrics.yaml

Adding new telemetry to see if the user connected to a server in the same location that they are located in.
I'm open to feedback on a better name for this metric. Other ones I considered:
- using_in_country_server
- server_in_user_location
- server_in_true_country
- user_country_is_server_country
- server_country_is_user_country
- is_server_location_in_user_country
VPN-7133

VPN-7133: server location telemetry

---

tests/unit_tests/addons/api_settimedcallback.js
tests/unit_tests/testaddonapi.cpp

We have a flaky unit test on macOS in `TestAddonApi` and reading through the test, I don't think it's really testing anything... so let's rewrite it to actually excercise the timed callback.
The test works by creating an addon with a timed callback, waiting for the callback to verify and then checking the condition. But the verification check is connected to a timer *after* it expires so it likely never runs.
There is also a bit of an anomaly in the failed test runs, with the timestamps showing that `qWait()` ran for more than twice as long as expected, indicating something janky is happening. So lets swap that out with `QTRY_VERIFY()` instead.

Maybe fix TestAddonApi timed callback test

---

.github/actions/qt-setup-taskcluster/action.yml
.github/workflows/auth_tests.yml
.github/workflows/flatpak.yml
.github/workflows/linux_tests.yaml
.github/workflows/macos_tests.yaml
.github/workflows/test_unit.yaml
docs/Building/macos.md
docs/Building/windows.md
scripts/windows/conda_setup_win_qt.ps1

In PR #10650 we changed a bunch of toolchain artifacts from `zip` compression to `xz` instead and this saved a tremendous amount of disk space and network traffic, but as a downside it also forced us to change the URLs to some taskcluster artifacts, most notably the Qt6 builds for macOS and Windows.
Now that that change has landed and the taskcluster index has updated, we need to update the consumers of those toolchains as well.
Windows turned out to be a bit of a dumpster fire. The Github `windows-latest` runner image doesn't support `tar.xz` compression and tar extraction is painfully slow. To mitigate the pain on Windows, we moved the Qt setup into a resuable action and add support for caching the Qt directory.
This also revealed that we were misusing the cache action in our functional …

Fix GitHub tests after taskcluster artifact trim

---

nebula/ui/components/MZToggleRow.qml

QA found a situation where the toggle background color sometimes doesn't change. I'm able to repro, but it's somewhat inconsistent.
It seems like the mousearea doesn't always cause the background color to change, as it registers differently. Thus, let's make sure to use the toggle's onclicked when the toggle is active.
VPN-7141 / follow up to https://github.com/mozilla-mobile/mozilla-vpn-client/pull/10646

VPN-7141 follow up fix

---

taskcluster/kinds/signing/kind.yml

In PR #10708 we added a signing task for the `macos/next` build type, but we neglected to update the index route logic accordingly. This resulted in a duplicate index route (one for `signing-macos/next`  and one for `mac-notarization`) and caused the Decision Task to fail.
Bug introduced by: #10708
JIRA Issue: [VPN-7205](https://mozilla-hub.atlassian.net/browse/VPN-7205)
[VPN-7205]: https://mozilla-hub.atlassian.net/browse/VPN-7205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7205: Remove accidental index route to macos/next build

---

macos/app/xpc-daemon.plist.in
macos/pkg/scripts/postinstall.in
src/cmake/macos.cmake
src/platforms/macos/daemon/xpcdaemonserver.mm
src/platforms/macos/macoscontroller.mm

In the 2.30 release, it seems like I screwed up when splitting the GUI and daemon executable and introduced an issue where the daemon would fail to launch after an upgrade.
The problem occurs because `launchd` on macOS makes use of designated requirements when installing daemons to identify the same software component across upgrades, and it uses the signing identifier of the daemon binary as one of the components in that designated identifier. When we split the GUI and daemon, this resulted in changing the signing identifier of the daemon such that it no longer satisfies the designated requirements and `launchd` will refuse to start the daemon after the upgrade.
There appear to be to ways to address the problem:
- We change the daemon service name yet again, so that it appears to …

VPN-7191: Rename daemon service to xpc-daemon

---

src/mozillavpn.cpp
src/platforms/linux/xdgportal.cpp

Qt 6.8 introduced a bug where using `QDBusConnection::sessionBus()` before `QCoreApplication` is created will silently break D-Bus signal connections.
We currently use such bus connections for two purposes:
- Reading the settings encryption key from the XDG [Secret](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Secret.html) portal.
- Configuring the application ID and scope if otherwise unset.
For the XDG secrets portal, this is an easy fix - we simply move the creation of `QCoreApplication` earlier in the program flow so that it exists before we try to reading any settings.
Configuring the application ID is a bit trickier as this needs to be done before we create `QCoreApplication`, otherwise a bunch of D-Bus activity during the application setup will go …

VPN-7172: Workaround for QTBUG-135928

---

extension/socks5proxy/CMakeLists.txt
extension/socks5proxy/bin/CMakeLists.txt
extension/socks5proxy/bin/linuxbypass.cpp
extension/socks5proxy/bin/sockslogger.cpp
extension/socks5proxy/bin/sockslogger.h
extension/socks5proxy/src/CMakeLists.txt
extension/socks5proxy/src/dnsresolver.cpp
extension/socks5proxy/src/httpconnection.cpp
extension/socks5proxy/src/httpconnection.h
extension/socks5proxy/src/httpconnectionbase.cpp
extension/socks5proxy/src/httpconnectionbase.h
extension/socks5proxy/src/httprequest.cpp
extension/socks5proxy/src/httprequest.h
extension/socks5proxy/src/masqueconnection.cpp
extension/socks5proxy/src/masqueconnection.h
extension/socks5proxy/src/proxyconnection.cpp
extension/socks5proxy/src/proxyconnection.h
extension/socks5proxy/src/proxylocal_default.cpp
extension/socks5proxy/src/proxylocal_linux.cpp
extension/socks5proxy/src/proxylocal_windows.cpp
extension/socks5proxy/src/socks5.cpp
extension/socks5proxy/src/socks5.h
extension/socks5proxy/src/socks5connection.cpp
extension/socks5proxy/src/socks5connection.h
extension/socks5proxy/tests/testsocks5.cpp
extension/socks5proxy/tests/testsocks5.h

This does a bit of refactoring to add support for multiple proxy protocols in the `socksproxy` tool. To get there we refactor a bunch of generic proxy handling code into a parent `ProxyConnection` class which now has three concrete subclasses:
- `Socks5Connection`: Implements version 5 of the SOCKS protocol from [RFC1928](https://datatracker.ietf.org/doc/html/rfc1928)
- `HttpConnection`: Implements the HTTP `CONNECT` method from [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616#section-9.9)
- `MasqueConnection`: Implements HTTP datagram and `connect-udp` support from MASQUE/[RFC9298](https://datatracker.ietf.org/doc/html/rfc9298)
The proxy protocol being used is snooped by peeking at the start of the header data using the `isProxyType()` static method. This allows the `Socks5` class …

Experiment: Support HTTP connect and MASQUE/UDP proxies

---

src/models/device.cpp

When installed via a flatpak, or any containerized environment, the values we get from `QSysInfo` can be misleading and tend to describe the container rather than the host operating system. Fortunately for us, flatpak mounts the host's `/etc/os-release` file at `/run/host/os-release` that we can parse to get information about the host OS instead.
JIRA Issue: [VPN-7173](https://mozilla-hub.atlassian.net/browse/VPN-7173)
[VPN-7173]: https://mozilla-hub.atlassian.net/browse/VPN-7173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7173: Use host os-release info for device name

---

.github/actions/qt-setup-taskcluster/action.yml
.github/workflows/auth_tests.yml
src/authenticationinapp/authenticationinappsession.cpp
tests/auth_tests/main.cpp

The Auth tests for Windows have been failing for a while, but we don't really notice it because it only runs on push (not on PR). Let's fix them.
This more or less just applies all the recent unit test fixes into the `auth_tests.yaml` workflow.
JIRA issue: [VPN-7217](https://mozilla-hub.atlassian.net/browse/VPN-7217)
[VPN-7217]: https://mozilla-hub.atlassian.net/browse/VPN-7217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7217: Fix Auth unit test hang on TOTP error

---

src/feature/featurelistcallback.h

When we migrated our split tunneling implementation from cgroups v1 to v2, we neglected to update the `FeatureCallback_splitTunnel()` method to remove support for desktop environments that only used cgroupsv1. Until these desktop environments can support application grouping via cgroups, it will not be possible to support split tunneling.
JIRA Issue:  [VPN-7208](https://mozilla-hub.atlassian.net/browse/VPN-7208) - #10720
Support is blocked by:
- Cinnamon: linuxmint/cinnamon#12015
- MATE: mate-desktop/mate-desktop#519
- Unity: project appears to be dead.
[VPN-7208]: https://mozilla-hub.atlassian.net/browse/VPN-7208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VPN-7208: Disable split tunnel for MATE, Cinnamon and Unity

---

src/commands/commandui.cpp
src/networkrequest.cpp
src/networkrequest.h
src/platforms/macos/macosutils.mm

The navigation tests on macOS are failing because the `performance.time_to_main_screen` timer is taking too long and results in a failed test. This test is set up to fail if it takes more than a second to show the main UI, and we are repeatedly taking 1.5-3 seconds to get there on the test runners.
I have three hypotheses as to why the tests are failing:
- Loading of the SSL intervention certificate takes too long because it has to re-import all of the system certificates.
- Lack of a valid codesign causes the `MacOSStartAtBootWatcher` to hang for a second or two.
- The first run of the client spends way too long compiling the QML cache.
JIRA Issue: [VPN-7230](https://mozilla-hub.atlassian.net/browse/VPN-7230)
[VPN-7230]: https://mozilla-hub.atlassian.net/browse/VPN-7230?atlOrigin=eyJpIjoi …

VPN-7230: Fix navigation test failure on macOS

---

src/feature/featurelistcallback.h
src/platforms/linux/daemon/apptracker.cpp
src/platforms/linux/linuxutils.cpp
src/platforms/linux/linuxutils.h
src/platforms/linux/xdgportal.cpp
src/platforms/linux/xdgportal.h

It's been a while since we took a look at how application scoping is handled on KDE, and there seem to be a few bugs in there. It seems that modern versions of KDE are now launching applications as systemd `service` units rather than `scope` or `slice` as we typically see on Gnome. Failing to handle this causes the VPN client to unnecessarily create a new systemd unit at startup.
This cgroup parsing change also affects how split tunneling is handled in KDE, and rather than implementing this twice, we expose a new `XdgPortal::parseCgroupAppId()` method that the split-tunneling `AppTracker` class can make use of when tracking application launches.
It also seems that our KDE version detection broke during the transition to KDE 6. So let's update that one too.
Systemd: [desktop …

VPN-7212: Support KDE cgroup parsing

---

linux/debian/rules

It seems that the PPA builds have been failing in something to do with the vendored cargo crates. The issue occurs because vendoring the crates causes modifications to the `Cargo.toml` file, while preserving the original as `Cargo.toml.orig`. Unfortunately, `dh_clean` mistakes these for cruft left after a merge failure, and deletes them.
To fix this, we can explicitly exclude the `3rdparty` directory where the crates are vendored when running `dh_clean`

Exclude 3rdparty from dh_clean

---

src/mozillavpn.cpp
src/networkwatcher.cpp
src/networkwatcher.h
src/networkwatcherimpl.h
src/notificationhandler.cpp
src/platforms/linux/linuxnetworkwatcherworker.cpp
src/platforms/linux/linuxnetworkwatcherworker.h
src/platforms/macos/macosnetworkwatcher.mm
src/platforms/wasm/wasmnetworkwatcher.cpp
src/platforms/windows/windowsnetworkwatcher.cpp
src/translations/strings.yaml

Starting with macOS 14, reading the Wi-Fi SSID requires location services to be enabled for the application, but unfortunately this would lead to a bunch of popups and security notices for our application that doesn't make sense for the minor functionality added by knowing the SSID (IIUC, it is only used to fill in the notification text).
However, the current `MacOSNetworkWatcher` implementation uses the existence of an SSID as a proxy for whether the current network interface is a Wi-Fi device, which causes us to ignore the network changes because we treat them as wired networks.
This PR works around the issue by checking for the 802.11 PHY mode instead to determine if the interface is Wi-Fi or Wired and then uses a generic text string in place of the SSID-specific notification text. …

VPN-5469: Fix unsecured WiFi detection on macOS 14 and later
